### ISSUE TITLE
Building Nest App on CircleCI hangs

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#1899] opened 2019-09-30 15:12 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Nest app builds without issues

## Current Behavior

When building locally it builds fine in a very short period of time (I have an 8 core Macbook pro), but when building on CircleCI it hangs at `95% emitting fork-ts-checker-webpack-plugin`.

### Context

Please provide any relevant information about your setup:

- @nrwl/nest 8.5.2
- angular cli 8.3.3
- and most importantly - a use-case that fails

```
"configurations": {
                        "production": {
                            "optimization": false,
                            "sourceMap": false,
                            "extractLicenses": false,
                            "inspect": false,
                            "fileReplacements": [
                                {
                                    "replace": "apps/core/src/environments/environment.ts",
                                    "with": "apps/core/src/environments/environment.prod.ts"
                                }
                            ]
                        }
                    }
```

It was failing almost instantly with sourceMaps turned on, with sourceMaps off it hangs at 95%

### Failure Logs

(sorry for the bad output, copied from the CircleCI console)

```85% chunk order optimization 85% chunk order optimization OccurrenceOrderChunkIdsPlugin                                       85% before chunk ids 85% before chunk ids NamedChunksPlugin              86% chunk id optimization 86% after chunk id optimization              87% record modules 87% record modules RecordIdsPlugin                  87% record chunks 87% record chunks RecordIdsPlugin                       88% hashing 88% content hashing 88% content hashing JavascriptModulesPlugin                           89% after hashing   89% record hash 90% module assets processing  90% chunk assets processing 91% additional chunk assets processing                          91% recording 92% additional asset processing    92% chunk asset optimization 93% after chunk asset optimization             93% asset optimization 94% after asset optimization               94% after seal   95% emitting 95% emitting fork-ts-checker-webpack-plugincontext canceled```

## Other

The nest app is probably about medium sized with a large shared module (this is actively being reduced into libraries). The project was just merged into our mono repo as it was in it's own repo before and built within minutes using jsut a plain webpack config.

**Comment by bcabanes** [comment] 2019-10-03 22:04
Hi @yharaskrik!

Could you provide a repro?
Thank you!

**Comment by vsavkin** [comment] 2019-12-12 01:44
Sorry, but I'm going to close this one. If the problem is still present, please reopen it with a repro.

**Closed by vsavkin** 2019-12-12 01:44 UTC
Labels: blocked: repro needed
