### ISSUE TITLE
HookWebpackError: ENOENT: no such file or directory, scandir at makeWebpackError while trying to run storybook

### ISSUE THREAD

**Issue by innoveltec** [nrwl/nx#7929] opened 2021-11-29 08:35 UTC
@juristr as requested by you on the storybook github page i am reopening this issue here on the nx github. 

Upgraded my angular nx repo(v13.2.1) to the newest version which is using storybook 6.4.0-rc.3. After that i have run the npx sb@next automigrate command which suggests me to install some webpack-5 dependencies and i also added the core builder property to webpack5 in my main.js file. Now when i try to run my storybook i am getting an error with the following stacktrace:

[webpack-dev-middleware] HookWebpackError: ENOENT: no such file or directory, scandir
at makeWebpackError (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\HookWebpackError.js:48:9)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:3055:12
at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :31:1)
at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:478:17)
at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :28:1)
at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :46:1)
at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:490:9)
at _next4 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :41:1)
at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :59:1)
at eval (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :11:1)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\SourceMapDevToolPlugin.js:549:10
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2830:7
at Object.each (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2857:9)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\SourceMapDevToolPlugin.js:384:17
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2830:7
at Object.each (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\neo-async\async.js:2857:9)
-- inner error --
Error: ENOENT: no such file or directory, scandir
at Object.readdirSync (fs.js:1021:3)
at CacheBackend.provideSync (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
at WebpackFileSystem.listPaths (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
at LicenseTextReader.readLicense (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
at PluginChunkReadHandler.processModule (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
at WebpackModuleFileIterator.internalCallback (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
at WebpackModuleFileIterator.iterateFiles (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
at WebpackChunkModuleIterator.iterateModules (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
at PluginChunkReadHandler.processChunk (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:19:29)
at _loop_1 (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:135:37)
at WebpackCompilerHandler.iterateChunks (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:160:17)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:50:31
at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:476:10)
at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :28:1)
caused by plugins in Compilation.hooks.processAssets
Error: ENOENT: no such file or directory, scandir
at Object.readdirSync (fs.js:1021:3)
at CacheBackend.provideSync (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:233:32)
at WebpackFileSystem.listPaths (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackFileSystem.js:78:24)
at LicenseTextReader.readLicense (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\LicenseTextReader.js:37:54)
at PluginChunkReadHandler.processModule (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:46:62)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:22:23
at WebpackModuleFileIterator.internalCallback (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:25:13)
at WebpackModuleFileIterator.iterateFiles (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackModuleFileIterator.js:10:9)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:20:32
at WebpackChunkModuleIterator.iterateModules (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackChunkModuleIterator.js:42:21)
at PluginChunkReadHandler.processChunk (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\PluginChunkReadHandler.js:19:29)
at _loop_1 (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:135:37)
at WebpackCompilerHandler.iterateChunks (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:160:17)
at C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\license-webpack-plugin\dist\WebpackCompilerHandler.js:50:31
at fn (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\webpack\lib\Compilation.js:476:10)
at _next5 (eval at create (C:\Users\G53188\source\repos\ag-nx-webtemplate\aginsurance\node_modules\tapable\lib\HookCodeFactory.js:33:10), :28:1)

**Comment by innoveltec** [comment] 2021-11-29 08:36
And here was my nx report:

Node : 14.15.4
OS : win32 x64
npm : 6.14.10

nx : 13.2.1
@nrwl/angular : 13.2.1
@nrwl/cli : 13.2.1
@nrwl/cypress : 13.2.1
@nrwl/devkit : 13.2.1
@nrwl/eslint-plugin-nx : 13.2.1
@nrwl/express : undefined
@nrwl/jest : 13.2.1
@nrwl/linter : 13.2.1
@nrwl/nest : undefined
@nrwl/next : undefined
@nrwl/node : undefined
@nrwl/nx-cloud : 12.5.4
@nrwl/react : undefined
@nrwl/react-native : undefined
@nrwl/schematics : undefined
@nrwl/tao : 13.2.1
@nrwl/web : undefined
@nrwl/workspace : 13.2.1
@nrwl/storybook : 13.2.1
@nrwl/gatsby : undefined
typescript : 4.4.4
rxjs : 6.6.7
Community plugins:
@angular/animations: 13.0.0
@angular/common: 13.0.0
@angular/compiler: 13.0.0
@angular/core: 13.0.0
@angular/elements: 13.0.0
@angular/forms: 13.0.0
@angular/platform-browser: 13.0.0
@angular/platform-browser-dynamic: 13.0.0
@angular/router: 13.0.0
devextreme-angular: 21.2.3
ngx-bootstrap: 7.1.0
@angular-devkit/build-angular: 13.0.3
@angular/cli: 13.0.3
@angular/compiler-cli: 13.0.0
@angular/language-service: 13.0.0
@storybook/angular: 6.4.0-rc.3

**Comment by juristr** [comment] 2021-11-29 09:00
_(for context: https://github.com/storybookjs/storybook/issues/16755)_

**Comment by innoveltec** [comment] 2021-12-06 12:56
Hello would like to know if there is any news on this error? Kind regards, Gerry

**Comment by innoveltec** [comment] 2021-12-08 11:30
Hello @mandarini sorry for asking again but is there already some news on this error i am having? This is blocking me of moving to the newest nx version with angular 13 :-)

**Comment by mandarini** [comment] 2021-12-14 13:52
Hi there @innoveltec ! I am just looking at this, apologies for leaving this go on for so long! :) Is there any minimum reproduction repository I can take a look at?

Also, can you please do a clean install of your node modules: 
1. `rm -rf node_modules`
2. `npm install`

And see if the issue persists?

Out of curiosity, why did you use `npx sb@next` since you already had used `nx migrate`? I am thinking that maybe something got messed up there, but maybe I'm also wrong. I'm trying to reproduce locally, but please do the above, and if you can give me a minimum repro repo that would be very helpful. I'll try to help you as much as I can! :)

**Comment by innoveltec** [comment] 2021-12-15 08:35
Hello @mandarini i tried to remove my node modules and my package lock json file and after that did a npm install but unfortunately the issue still persists. The repo is my client's property so i can not share that. I have to see if i can make a reproduction repository where the issue also persist. I ran `npx sb@next automigrate` command because i saw this on the website of storybook that this command would check if your stories and if they are not compatible with the version of storybook you are installing it will show you the changes that has to be made and will offer to fix them for you. Maybe this is not needed when using nrwl storybook?

**Comment by innoveltec** [comment] 2021-12-15 12:11
Hello @mandarini , 

I think I have found the cause of the error is was having. I have a publishable component library in my nx-workspace and for this library I was using storybook. In the preview.js file inside the .storybook folder of my library I had the following import statement => `import '!style-loader!css-loader!sass-loader!../styles/styles.scss';` because I needed to import some styles like bootstrap(imported inside my styles.scss file) etc... inside my running storybook app. I remember some time ago I needed to have this import statement because otherwise these styles were not loaded in my storybook. It seems like removing this import statement fixes the error I was having and now the styles from the styles.scss file inside the styles folder of my lib are automagically working inside my storybook. How does storybook knows it should take these styles and use it in the storybook? 

Kind regards,

Gerry

**Comment by mandarini** [comment] 2021-12-15 16:43
Hi @innoveltec ! I am so happy that you found the issue and solved it! :) :) 

_re: automagically works:_ Is that style file inside the `build` target in your `project.json` (or `angular.json`) of your project? I mean in the `"styles": []` array? If it is, it will take it from there! Can you check and let me know? [Here's an issue](https://github.com/nrwl/nx/issues/7908#issuecomment-994115337) you can look at. If your issue is solved, can we close this?

**Comment by innoveltec** [comment] 2021-12-15 21:12
Hi @mandarini yes indeed the style file was inside the styles array of the build target from my default project which was an application and not the library. Didn't know it would take it from there so thanks for letting me know :-) You can close this issue ;-)

Greetz Gerry

**Comment by mandarini** [comment] 2021-12-16 14:37
Ohh cool!! :) Thanks! :)

**Closed by mandarini** 2021-12-16 14:37 UTC
Labels: type: bug, scope: storybook
