### ISSUE TITLE
Wrong JSON structure in `...\node_modules\yargs\locales\cs.json` during a migration process

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#12380] opened 2022-10-03 20:47 UTC
## Current Behavior

Running the `nx migrate latest`  (or any other with a concrete version) command leads to a runtime error (Windows 10 with Czech locale set). I already created a PR in the `yargs` package for it: https://github.com/yargs/yargs/pull/2242

```
SyntaxError: syntax error in C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\locales\cs.json
    at JSON.parse (<anonymous>)
    at Y18N._readLocaleFile (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\y18n\build\index.cjs:141:37)
    at Y18N.__ (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\y18n\build\index.cjs:30:18)
    at Object.P.n.getPositionalGroupName (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\build\index.cjs:1:14322)
    at Xt.positional (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\build\index.cjs:1:41613)
    at withMigrationOptions (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\nx\src\command-line\nx-commands.js:644:10)
    at C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\nx\src\command-line\nx-commands.js:247:64
    at M.applyBuilderUpdateUsageAndParse (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\build\index.cjs:1:7384)
    at M.runCommand (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\build\index.cjs:1:7078)
    at Xt.[runYargsParserAndExecuteCommands] (C:\Temp\tmp-26860-zE27hc4eyGFz\node_modules\yargs\build\index.cjs:1:57900)
```

When checking the file `cs.json`, it's clear that there is a mistake in the JSON structure on line 18 (`"other": "Nedostatek argumentů: zadáno %s, je potřeba alespoň %s",`), where an extra comma is placed at the end of the line. Other locale files (like en.json, ...) don't have this mistake.

## Expected Behavior

Valid JSON structure of the `cs.json` file.

**Comment by AgentEnder** [comment] 2022-10-04 16:21
Hey @mlc-mlapis! As noted, this is an issue in the `yargs` package. I'm going to close this out, since the issue is not related to Nx directly (aside from `nx` using `yargs`). Once your PR has been released in `yargs`, we will investigate updating to the next version.

**Closed by AgentEnder** 2022-10-04 16:21 UTC
Labels: type: bug

**Comment by mlc-mlapis** [comment] 2022-10-04 16:27
@AgentEnder Fine, that was the primary reason for creating the issue here + informing others about it.
>we will investigate updating to the next version.

**Comment by nexdrew** [comment] 2022-10-16 22:35
Not sure if this helps, but you should be able to get around the problem by assuming another (non-Czech) locale when you run the `nx` CLI by setting a `LC_ALL` environment variable (per the `os-locale` package) that specifies a different language, perhaps like so:

```
LC_ALL=en nx migrate latest
```

Maybe give that a shot and let us know if it works. I assume it should then print out an error message in English.

**Comment by mlc-mlapis** [comment] 2022-10-17 15:17
@nexdrew Thanks for the tip. I tried it, and it works.

> LC_ALL=en nx migrate latest

**Comment by mlc-mlapis** [comment] 2022-11-02 16:08
@AgentEnder Hi, the new version of Yargs is ready now, https://github.com/yargs/yargs/releases/tag/v17.6.1, can you update the Nx dependencies? The problem with the valid JSON structure of the Yargs cs.json file has been fixed already. Thanks.

**Comment by nexdrew** [comment] 2022-11-02 16:15
Note that yargs 17.6.1 has not yet been published to the npm registry ... hopefully will be soon.

**Comment by mlc-mlapis** [comment] 2022-11-02 16:25
@nexdrew I hope so. I didn't check. 💡

**Comment by nexdrew** [comment] 2022-11-02 17:06
It's published as latest now, so you should be good to go with upgrading the yargs dependency.
