### ISSUE TITLE
Unable to show images in a react application

### ISSUE THREAD

**Issue by rpspall** [nrwl/nx#14532] opened 2023-01-21 23:06 UTC
### Current Behavior

Followed the nx dev tutorial TO THE LETTER :-)

https://nx.dev/react-tutorial

I then added a logo.png file to my application directory...

<workspace>/apps/<appname>/src/app/logo.png

I then modified app.tsx to use the logo:

import { Banner } from '@ydsreact/common-ui';
import { exampleProducts } from '@ydsreact/products';
import siteLogo from "./logo.png";

export function App() {
  
  return (
    <>
    <img
            src={siteLogo}
            width="137px"
            height="47px"
            alt="Yamaha | Revs Your Heart"
          />
      <Banner text="Welcome to our admin app." />
      <ul>
        {exampleProducts.map((product) => (
          <li key={product.id}>
            <strong>{product.name}</strong> Price: {product.price}
          </li>
        ))}
      </ul>
    <div />
    </>
  );
}

export default App;

Finally ran npx nx serve <appname> to preview my react application. This runs fine, I open the browser page (http://localhost:4200/) but the image is not displayed:

![BrokenImage](https://user-images.githubusercontent.com/6170653/213890347-12f7bd62-03d0-458b-a8dc-684a03e44a37.png)

### Expected Behavior

Expected image to be displayed

### Steps to Reproduce

1. Follow https://nx.dev/react-tutorial
2. Modify app.tsx for my first application
3. Add new logo.png file to my app directory
4. Launch serve

### Nx Report

```shell
No nx report, the image simply doesn't display!
```

### Additional Information

I tried putting logo.png in other locations such as:

<workspace>/apps/<appname>/src/logo.png
<workspace>/apps/<appname>/src/assets/logo.png

And modified import path to fix import errors with same problem when I tried to test the application.

The image file is 13KB in size, I did read:

https://nx.dev/recipes/other/adding-assets-react#adding-images,-fonts,-and-files

Meanwhile in the chrome debugger, the img was shown as:

<img src="data:image/png;base64,ZXhwb3J0IGRlZmF1bHQgX193ZWJwYWNrX3B1YmxpY19wYXRoX18gKyAibG9nby5wbmciOw==" width="137px" height="47px" alt="Yamaha | Revs Your Heart">

**Comment by jamieathans** [comment] 2023-01-22 00:21
Possible duplicate of - https://github.com/nrwl/nx/issues/14378.

**Comment by merobal** [comment] 2023-01-22 16:04
It works well with v15.4.5 and it's broken at 15.4.6 and above (still with 15.5.3).

**Comment by rpspall** [comment] 2023-01-22 17:06
Confirmed it works with 15.4.5... Thank you, as I can now continue with my react application migration

**Comment by martinmosko** [comment] 2023-01-25 22:08
# Issue
The issue seems to be related to using in Webpack 5 both new asset module & deprecated file-loaders where file-loader is missing backward compatible attribute `type: "javascript/auto"`

See https://github.com/nrwl/nx/blob/0bcab85ce7dcfc6b0601d178d5df8a1bf2dc7267/packages/webpack/src/utils/with-web.ts#L360-L375

# Workaround

Modify used webpack.config
```
const { composePlugins, withNx } = require('@nrwl/webpack');
const { withReact } = require('@nrwl/react');

// Nx plugins for webpack.
module.exports = composePlugins(withNx(), withReact(), (config) => {
  
  config.module.rules = config.module.rules.map((rule) => {
    if (/file-loader/.test(rule.loader)) {
      return {
        ...rule,
        type: "javascript/auto", // This is fixing issue https://webpack.js.org/guides/asset-modules/
      };
    }

    return rule;
  });

  return config;
});
```

**Comment by DanielSchiavini** [comment] 2023-01-26 08:19
Thanks for the workaround, it works like a charm

**Comment by asherccohen** [comment] 2023-01-26 09:24
doesn't work for me. Is this maybe a setting for next.js?
I'm in a simple react SPA app.

**Comment by asherccohen** [comment] 2023-01-26 13:13
workaround fixes images for me, but not svgs

**Comment by hans-weber** [comment] 2023-01-27 09:16
> workaround fixes images for me, but not svgs

https://github.com/nrwl/nx/issues/14378#issuecomment-1405312953 this may with svgs and images right now

**Comment by asherccohen** [comment] 2023-01-27 09:18
sure, see my answer below https://github.com/nrwl/nx/issues/14378#issuecomment-1405312953

**Comment by popoleeMaster** [comment] 2023-02-13 10:36
I tried those workaround, but my image return `[object Module]` instead of the image and are still broken

**Comment by xiongemi** [comment] 2023-05-04 20:12
i could no longer replicate this issue with @nx/react@16, @nx/webpack@16, webpack@5.75.0. closing this issue for now.

**Closed by xiongemi** 2023-05-04 20:12 UTC
Labels: type: bug, scope: react
