### ISSUE TITLE
@nrwl/angular:move not updating jest.config.js in root

### ISSUE THREAD

**Issue by mackelito** [nrwl/nx#6792] opened 2021-08-20 14:44 UTC
```
> Executing task: ng generate @nrwl/angular:move --destination=data-access/pharmacy --projectName=shared-data-access-pharmacy --no-interactive <

DELETE libs/shared/data-access-pharmacy/src/lib/shared/contracts/pharmacy-cart-mapping.model.ts
DELETE libs/shared/data-access-pharmacy/src/lib/shared/contracts/stored-pharmacy-diffs.interface.ts
DELETE libs/shared/data-access-pharmacy/src/lib/pharmacy.service.ts
DELETE libs/shared/data-access-pharmacy/src/index.ts
DELETE libs/shared/data-access-pharmacy/src/test-setup.ts
DELETE libs/shared/data-access-pharmacy/.eslintrc.json
DELETE libs/shared/data-access-pharmacy/README.md
DELETE libs/shared/data-access-pharmacy/jest.config.js
DELETE libs/shared/data-access-pharmacy/tsconfig.json
DELETE libs/shared/data-access-pharmacy/tsconfig.lib.json
DELETE libs/shared/data-access-pharmacy/tsconfig.spec.json
CREATE libs/data-access/pharmacy/src/lib/shared/contracts/pharmacy-cart-mapping.model.ts
CREATE libs/data-access/pharmacy/src/lib/shared/contracts/stored-pharmacy-diffs.interface.ts
CREATE libs/data-access/pharmacy/src/lib/pharmacy.service.ts
CREATE libs/data-access/pharmacy/src/index.ts
CREATE libs/data-access/pharmacy/src/test-setup.ts
CREATE libs/data-access/pharmacy/.eslintrc.json
CREATE libs/data-access/pharmacy/README.md
CREATE libs/data-access/pharmacy/jest.config.js
CREATE libs/data-access/pharmacy/tsconfig.json
CREATE libs/data-access/pharmacy/tsconfig.lib.json
CREATE libs/data-access/pharmacy/tsconfig.spec.json
UPDATE apps/ecom-web-client/src/app/checkout/shared/summary/cart-panel-summary.component.ts
UPDATE apps/ecom-web-client/src/app/core/core.module.ts
UPDATE libs/ecom-web-client/feature-order-detail/src/lib/order-detail-info-table/order-detail-info-table.component.ts
UPDATE libs/ecom-web-client/feature-nebraska-rx-flow/src/lib/ecom-web-client/rx-flow/rx-flow.component.ts
UPDATE tsconfig.base.json
UPDATE jest.config.js
UPDATE nx.json
UPDATE angular.json
```

as you can see it states that the jext.config.js in root has been updated but there is no diff in git.. ?

### Environment

````
  Node : 14.15.4
  OS   : darwin x64
  yarn : 1.21.1
  
  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 11.6.1
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.4
````

**Comment by leosvelperez** [comment] 2021-10-04 11:25
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/6303. Please note the issue was solved in https://github.com/nrwl/nx/pull/6313 and released as part of v12.6.0. Further improvements have been released in later versions. Please update to the latest version to get the fixes.

Closing as it has already been fixed in later versions.

**Closed by leosvelperez** 2021-10-04 11:25 UTC
Labels: type: bug, scope: angular
