### ISSUE TITLE
Allow iife format for esbuild

### ISSUE THREAD

**Issue by ThePlenkov** [nrwl/nx#19545] opened 2023-10-10 19:26 UTC
## Description
I'd like iife format to become available for esbuild options

## Motivation
I'm building Google apps scripts with nx and for that purpose I need bundled code to be wrapped into self-executed function, while rest of global functions we control with esbuild plugin

## Suggested Implementation
I suggest just to allow iife to become one of available formats, it will be enough.

## Alternate Implementations
How else I can build something like this?
```
let global = this;
// src/index.ts
function say() {
}
"use strict";
(() => {
  // src/index.ts
  global.say = function() {
    say("Hi!");
  };
  function say(what) {
    console.log(what);
  }
})();

```

**Comment by Coly010** [comment] 2024-05-16 09:37
Closing as duplicate of this: https://github.com/nrwl/nx/discussions/23427

**Closed by Coly010** 2024-05-16 09:37 UTC
Labels: type: feature, scope: bundlers
