### ISSUE TITLE
Preset angular-nest does not work

### ISSUE THREAD

**Issue by herve-ch** [nrwl/nx#13893] opened 2022-12-17 20:46 UTC
### Current Behavior

Hello, when running

`npx  create-nx-workspace --preset angular-nest`

the command fail with:

 >  NX   Nx failed to create a workspace.

log error show :

npm ERR! must provide string spec

Tried on macos and windows with node 16 and 18 LTS, npm and yarn

### Expected Behavior

Command should create a working project

### Steps to Reproduce

1. run npx  create-nx-workspace --preset angular-nest

### Nx Report

```shell
nx report show error:  >  NX   Could not find Nx modules in this workspace.
Have you run npm/yarn install?

But i can't run yarn or npm install

Error when i try is:

error An unexpected error occurred: "https://registry.yarnpkg.com/angular-nest: Not found".
```

**Comment by leosvelperez** [comment] 2022-12-21 10:29
Thanks for reporting this!

Please note that `angular-nest` is not a valid preset. It used to be valid, but the pre-defined presets changed and that one was removed. You can achieve the same by running:

```shell
npx create-nx-workspace@latest --preset angular-monorepo
cd <workspace name>
npm i -D @nrwl/nest@latest
npx nx g @nrwl/nest:application
```

You can also see the currently pre-defined presets by running `npx create-nx-workspace@latest` without specifying the `--preset` option.

I'm closing this since the preset provided is no longer valid and that's by design.

**Closed by leosvelperez** 2022-12-21 10:29 UTC
Labels: type: bug, scope: angular

**Comment by herve-ch** [comment] 2022-12-24 10:46
Thanks for the info
