### ISSUE TITLE
Inferred tasks set wrong current working directory

### ISSUE THREAD

**Issue by DurchblickerFabian** [nrwl/nx#22515] opened 2024-03-26 13:01 UTC
### Current Behavior

When trying to use nx with @nx/next plugins inferred tasks and Nextra (documentation tool), it always results in the following error: "Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root"
Looking into nextras code, it seems they look for the directory in `process.cwd()`, which at that point somehow is the root directory of the monorepo even though the inferred task view suggests that the cwd is set to the correct subdir.
I could also reproduce this behavior when trying to use the cwd in next.config.js, which also results in the root directory of the monorepo instead of the sub-project directory. The project was freshly initialized, configs basically untouched.

### Expected Behavior

Current working directory in next.config.js resolves to the correct project directory. I have a second monorepo using basically the exact same setup with NX 17 which works as expected.

### Steps to Reproduce

Minimal reproducible steps:
1. Create nx workspace
2. Generate project with @nx/next generator
3. Log `process.cwd()` in next.config.js
4. Start Next
5. See workspace root directory instead of project directory where Next resides in

### Nx Report

```shell
Node   : 18.19.0
OS     : darwin-arm64
npm    : 10.2.3

nx (global)        : 18.1.3
nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/devkit         : 18.1.3
@nx/eslint-plugin  : 18.1.3
@nx/next           : 18.1.3
@nx/react          : 18.1.3
@nrwl/tao          : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.1.3
typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment] 2024-03-27 17:51
@ndcunningham Could you take a look how we can emulate the config loading with the cwd set to the directory of the config file?

**Comment by terrymun** [comment] 2024-05-31 11:39
I can also reproduce it: our generators stopped working, and with further investigation it turns out the issue is coming from `@nx/next/plugin`. I am not sure which version of nx broke it though:

```text
Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  The "@nx/next/plugin" plugin threw an error while creating nodes from apps/docs/next.config.js:
    Error: > Couldn't find any `pages` or `app` directory. Please create one under the project root
```

**Comment by ndcunningham** [comment] 2024-08-19 21:13
This should be fixed.

**Closed by ndcunningham** 2024-08-19 21:13 UTC
Labels: type: bug, scope: nextjs
