### ISSUE TITLE
The "@nx/react:application" generator doesn't yet support the existing TypeScript setup

### ISSUE THREAD

**Issue by guyi-cymulate** [nrwl/nx#28346] opened 2024-10-07 16:25 UTC
### Current Behavior

The "@nx/react:application" generator doesn't yet support the existing TypeScript setup in my workspace
run
nx g @nx/react:application test-client --dry-run 

installed nx 20.0
installed @nx/react 20.0

### Expected Behavior

create app

### Steps to Reproduce

1.create new nx repp
install nx 20
install @nx/react
generate react app and you will failed.

### Nx Report

 NX   The "@nx/react:application" generator doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/react:application" generator. We'll soon release a new version of Nx with support for it.

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by brianlagunas** [comment] 2024-10-07 17:44
Same for me. The @nx/web - application generator doesn't work either.

**Comment by guyi-cymulate** [comment] 2024-10-07 19:00
which version should works?

**Comment by leosvelperez** [comment] 2024-10-09 10:07
Closing as duplicate of #28322. Please check https://github.com/nrwl/nx/issues/28322#issuecomment-2401699185 for an explanation and solution.

**Closed by leosvelperez** 2024-10-09 10:07 UTC
Labels: type: bug
