### ISSUE TITLE
Do not hide CI output behind nx.cloud

### ISSUE THREAD

**Issue by hugo-vrijswijk** [nrwl/nx#27817] opened 2024-09-08 10:12 UTC
### Current Behavior

Since upgrading nx from 16.6.2 to 16.6.4, a new task output is shown:

![image](https://github.com/user-attachments/assets/375be168-4fb5-4c8d-87f9-2c67170a17e7)

This output does not make it possible to view the log output in CI of any run tasks. Instead, I am forced to leave my CI provider (Github) and go to nx.cloud to view the logs of any (failed) tasks. This makes debugging much more difficult and is unexpected behaviour for anyone just wanting to view logs of their CI output.

### Expected Behavior

The behaviour on previous versions was much better. Where tasks would be collapsed to a nice overview, and I could quickly look into logs:

![image](https://github.com/user-attachments/assets/8867c20f-7ae3-4e70-9c37-c4615ae5da2a)

Hiding the logs seems like a dark pattern to push users towards nx.cloud. It's completely unexpected behaviour for a task executor to start hiding logs, unless viewed on a proprietary cloud service. I sincerely hope this is a bug and not intended

### Steps to Reproduce

1. Run any task on Github actions
2. Observe output is hidden

### Nx Report

```shell
Node           : 20.12.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.0

nx          : 19.6.5
lerna       : 8.1.8
@nx/devkit  : 19.6.4
@nrwl/tao   : 19.6.5
typescript  : 5.5.4
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@19.6.4
  - @nrwl/devkit@19.6.4

To fix this, run `nx migrate nx@19.6.5`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by StalkAltan** [comment] 2024-09-09 14:30
Hi! Sorry for the confusion! You can disable this by following the steps here: https://nx.dev/blog/improved-ci-log-with-nx-cloud#revert-to-the-old-behavior

We genuinely think Nx Cloud is a better log viewing experience than within your CI platform, but we understand that not everyone will agree, so you can opt out!

Closing as this is not a bug.

**Closed by StalkAltan** 2024-09-09 14:30 UTC
Labels: type: bug

**Comment by splincode** [comment] 2024-09-13 16:32
Why not add `NX_CLOUD_OUTPUT_VERBOSE=true`?

**Comment by PointSingularity** [comment] 2024-09-23 15:19
I like the suggestion @splincode made.
Is there a way to set this up the old way without going into the NX settings on the website?

**Comment by ChrisSargent** [comment] 2024-09-25 17:16
I like the tables, except when stuff is failing and timing out and then there are NO logs anywhere.

**Comment by itspers** [comment] 2024-10-14 10:29
This is crazy - now i have "No terminal output was found for this task. Nx only sends the terminal output for cacheable operations." and no option to disable this crap in workspace settings. Only way to make things work - disable this nx cloud at all.

**Comment by nbolton** [comment] 2024-11-13 11:58
> We genuinely think Nx Cloud is a better log viewing experience than within your CI platform, but we understand that not everyone will agree, so you can opt out!

I disagree with this. This error from Nx Cloud is the most frustrating thing about Nx:

```
No terminal output was found for this task. Nx only sends the terminal output for cacheable operations.
```

This kind of thing wastes a lot of time for busy developers.

**Comment by alfaproject** [comment] 2024-11-15 11:37
I've disabled Nx Cloud altogether because the new business model is just insane and I only get a table as well, wth...

**Comment by webberwang** [comment] 2024-12-10 11:01
This option no longer shows up in NX Cloud, what's the solution now?
