### ISSUE TITLE
Error: ENOENT: no such file or directory when using nx g @nrwl/angular:app appName

### ISSUE THREAD

**Issue by normal1ze** [nrwl/nx#8811] opened 2022-02-02 02:32 UTC
## Current Behavior
Running `nx g @nrwl/angular:app appName` to produce a brand new Angular app results in:

```
Error: ENOENT: no such file or directory, open 'D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\apps\app-name\project.json'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at Observable._subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\@angular-devkit\core\node\host.js:163:50)   
    at Observable._trySubscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Observable.js:44:25)       
    at Observable.subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Observable.js:30:22)
    at Object.innerSubscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\innerSubscribe.js:102:23)     
    at SwitchMapSubscriber._innerSub (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\operators\switchMap.js:63:51)
    at SwitchMapSubscriber._next (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\operators\switchMap.js:53:14)
    at SwitchMapSubscriber.Subscriber.next (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\util\subscribeToArray.js:5:20) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Work\\[BLANK]\\repos\\[BRANCH]\\fulcrum\\apps\\app-name\\project.json'
}
```

## Expected Behavior
A new Angular application scaffolding found at `apps/appName`

## Steps to Reproduce
1. Opening a new terminal at the existing NX workspace root. 
2. Run `nx g @nrwl/angular:app appName`

### Failure Logs

```
Error: ENOENT: no such file or directory, open 'D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\apps\app-name\project.json'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at Observable._subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\@angular-devkit\core\node\host.js:163:50)   
    at Observable._trySubscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Observable.js:44:25)       
    at Observable.subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Observable.js:30:22)
    at Object.innerSubscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\innerSubscribe.js:102:23)     
    at SwitchMapSubscriber._innerSub (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\operators\switchMap.js:63:51)
    at SwitchMapSubscriber._next (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\operators\switchMap.js:53:14)
    at SwitchMapSubscriber.Subscriber.next (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\Work\[BLANK]\repos\[BRANCH]\fulcrum\node_modules\rxjs\internal\util\subscribeToArray.js:5:20) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Work\\[BLANK]\\repos\\[BRANCH]\\fulcrum\\apps\\app-name\\project.json'
}
```

### Environment

```
  Node : 14.17.1
  OS   : win32 x64
  npm  : 6.14.13

  nx : undefined
  @nrwl/angular : 13.7.1
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.7.1
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.7.1
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.7.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 12.2.16
         @angular/cdk: 12.2.13
         @angular/common: 12.2.16
         @angular/compiler: 12.2.16
         @angular/core: 12.2.16
         @angular/forms: 12.2.16
         @angular/material: 12.2.13
         @angular/platform-browser: 12.2.16
         @angular/platform-browser-dynamic: 12.2.16
         @angular/platform-server: 12.2.16
         @angular/router: 12.2.16
         @angular/service-worker: 12.2.16
         devextreme-angular: 21.1.6
         ngx-bootstrap: 5.6.2
         @angular-devkit/build-angular: 0.1002.3
         @angular/cli: 12.2.16
         @angular/compiler-cli: 12.2.15

```

**Comment by normal1ze** [comment] 2022-02-02 02:33
Note: running `nx g @nrwl/react:app appName` to create a new react app works fine. Only the Angular scaffolding has this issue.

**Comment by normal1ze** [comment] 2022-02-02 04:03
Update: I had to re-create a brand new workspace starting with the Angular app first, then add React to it. Rather than starting a workspace for blank apps, no plugins, then adding React and Angular.

**Comment by FrozenPandaz** [comment] 2022-02-14 16:49
Your package versions were misaligned in your original report. Since you've since solved the issue, I'm going to close this issue. I believe the cause of the issue was the misaligned versions.

**Closed by FrozenPandaz** 2022-02-14 16:49 UTC
Labels: type: bug, scope: angular

**Comment by rallz-dev** [comment] 2022-05-03 12:19
I am facing the same issue. I can create all code scaffolding just fine, except for angular one.
I created the workspace with `npx create-nx-workspace@latest`

I'm running on Windows 10 x86-64

`$ npm version
{
  'bosch-design-system': '0.0.0',
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
}`

And for my packages file:

`"devDependencies": {
    "@angular-devkit/schematics": "^13.3.4",
    "@nrwl/angular": "^14.0.5",
    "@nrwl/cli": "14.0.5",
    "@nrwl/cypress": "^14.0.5",
    "@nrwl/jest": "14.0.5",
    "@nrwl/react": "^14.0.5",
    "@nrwl/workspace": "14.0.5",
    "@nxext/stencil": "^13.2.3",
    "@nxext/svelte": "^13.3.1",
    "@stencil/core": "^2.14.0",
    "@stencil/sass": "1.5.2",
    "@types/jest": "27.4.1",
    "@types/node": "16.11.7",
    "@types/puppeteer": "~5.4.4",
    "jest": "27.5.1",
    "nx": "14.0.5",
    "prettier": "^2.5.1",
    "puppeteer": "~5.3.1",
    "ts-jest": "27.1.4",
    "ts-node": "9.1.1",
    "typescript": "~4.6.2"
  },`

Can anyone provide help?
