### ISSUE TITLE
Wrong dist folder when using importPath in lib output

### ISSUE THREAD

**Issue by shlomiassaf** [nrwl/nx#4462] opened 2021-01-07 15:24 UTC
When setting an `importPath` for a library that is different then the physical path
the dist output is based on the actual source physical path and not the import path.

When the library is publishable, this is incorrect because as a node module it will be imported
based on the physical location which does not match the `importPath`.

For example:

I have a library located at `libs/@finance/fx`.

> **@finance** is a sub-group of packages, it's not a scope but it has the **@** because we want it to be clear its a folder with packages and not a package.

To create it I set:

- **name**: fx
- **directory**:  `@finance`
- **importPath**: `@my-org/finance-fx`

We don't want to have  `@my-org/finance/fx` because that can lead to long, nested imports which we want to avoid.  
Some packages has secondary packages and we keep the level of nested packages to 2.

For example, a secondary package called **us**:  
We want it to be `@my-org/finance-fx/us` and not `@my-org/finance/fx/us`.

The problem is, when generating the files, **workspace.json** get's a dist folder matching the physical location.  
`dist/libs/@finance/fx` which when publishing makes no sense.

It should be `dist/libs/finance-fx` based on the import path.

**Comment by vsavkin** [comment] 2021-01-10 18:41
Hi there! Thanks for submitting the issue. 

The dist folder matches the source folder by design. There are several reasons for that, the main one being that there might be two libraries with the same `importPath` in the same workspace. `importPath`  doesn't have to be unique, whereas the physical location has to be.

Having said that you can always change the output path to match the import path by hand (or when generating a lib) if you prefer that. 

I'm going to close this issue. Thanks!

**Closed by vsavkin** 2021-01-10 18:41 UTC
Labels: type: bug
