### ISSUE TITLE
react library build failed

### ISSUE THREAD

**Issue by Jimmysh** [nrwl/nx#2496] opened 2020-02-16 16:07 UTC
# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior
React library can build success.
```typescript
export async function create() {
  return { a: 1 };
}
export async function test() {
  const { a } = await create();
  console.log(a);
}
```
## Current Behavior
Build failed.
error message 
.../test.tsx: Property name expected type of string but got null

change file to this can build success.
```typescript
export async function create() {
  return { a: 1 };
}
export async function test() {
  const c = await create();
  console.log(c.a);
}
```

## Context
error same as https://github.com/storybookjs/storybook/issues/4615

**Comment by jaysoo** [comment] 2020-02-19 20:05
Thanks for the report, we'll look into it.

**Comment by rarmatei** [comment] 2020-02-20 12:59
hey @Jimmysh - thank you so much for reporting this. I'm having some trouble reproducing the error you're seeing. The issue you linked to seems to have been fixed in Storybook 4.1.x (we are using `5.3.9`).

I also tried build the project referenced in https://github.com/aiao-io/aiao/issues/52
..but it seems to have been removed https://github.com/aiao-io/aiao/tree/master/integration/stencil-toolkit-nx

Would you be able to share a repo please that showcases this and the command you're running?

**Comment by Jimmysh** [comment] 2020-02-20 13:11
@rarmatei 
repo: https://github.com/Jimmysh/nx-issues-2496
```console
  npx nx build react-lib
```

**Comment by rarmatei** [comment] 2020-02-20 13:27
Thanks for the super quick response! I can definitely reproduce it now in a fresh nx workspace as well:

```
nx g @nrwl/react:lib test-lib --publishable
//add the await code you mentioned to libs/test-lib/src/index.ts
nx build test-lib
```

I'll look into ti

**Comment by rarmatei** [comment] 2020-02-20 14:27
I think it's related to: https://github.com/babel/babel/issues/10808

Can confirm setting: https://github.com/nrwl/nx/blob/master/packages/web/src/utils/babel-config.ts#L24 to `undefined` fixes it

@jaysoo what do you think is best? should we wait for updates on that babel issue, or is there anything we can do about that `targets` config?

**Comment by jaysoo** [comment] 2020-02-20 15:50
We might be able to remove `targets` and the `esm2015` format since the only reason we had `esm5` vs `esm2015` was because it was ported from Angular.

- ESM5 = ES5 + ESM
- ESM2015 = ES6/ES2015 + ESM

But we really don't care about ES5 vs ES2015+, what we really need is UMD vs ESM formats. Whether the user wants to compile to ES5, ES2015, ES2020, etc. is up to them and how they customize their babel config.

**Closed** 2020-02-24 15:10 UTC
Labels: scope: react, type: bug

**Comment by Jimmysh** [comment] 2020-06-19 06:45
9.4.4 this error come back. https://github.com/Jimmysh/nx-issues-2496
