### ISSUE TITLE
NX Cypress doesn't respect screenshotsFolder option

### ISSUE THREAD

**Issue by atomicrobokid** [nrwl/nx#19576] opened 2023-10-12 08:55 UTC
### Current Behavior

When i add the config for `screenshotsFolder` to my `cypress.config.ts`, NX ignores this and outputs the screenshots to `dist/cypress/apps` and `dist/cypress/libs` 

### Expected Behavior

NX should correctly pass any config to Cypress and ensure that the screenshots/videos etc are saved to the correct directory

### Steps to Reproduce

1. Set up new nx monorepo, install cypress component testing
2. Set cypress.config.ts screenshotsFolder option
3. Run a failing test, look at where screenshot is saved

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/node           : 16.10.0
   @nx/rollup         : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc      : 1.1.21
   @jscutlery/semver       : 3.3.0
   @nxkit/style-dictionary : 3.0.2
   @storybook/angular      : 7.4.6
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-12-12 11:47
Thanks for reporting this!

I can't reproduce the issue. You might be overwriting the option incorrectly.

Similar to what @rogervanwile suggested in https://github.com/nrwl/nx/issues/19576#issuecomment-1828311148, to overwrite the option for component testing, you should do it like in the following:

```ts
export default defineConfig({
  component: {
    ...nxComponentTestingPreset(__filename),
    screenshotsFolder: 'your/custom/path',
  },
});
```

Please note you need to overwrite the `screenshotsFolder` option inside the `component` options (Component Testing specific options).

I'm going to close this since it seems to be a misconfiguration. If you still have an issue after doing the above, please feel free to leave a comment with more information (better if a repro is provided) so we can reopen and troubleshoot the issue.

**Closed by leosvelperez** 2023-12-12 11:47 UTC
Labels: type: bug, scope: testing tools
