### ISSUE TITLE
Yarn packages resolution warnings

### ISSUE THREAD

**Issue by aevaldas** [nrwl/nx#19223] opened 2023-09-19 08:23 UTC
### Current Behavior

`yarn install` provides warnings

### Expected Behavior

No warning should come after `yarn install`.

### Steps to Reproduce

```bash
yarn init
yarn add @nx/linter @nx/react @nx/storybook @nx/vite @nx/webpack
yarn add -D nx
yarn set version berry
yarn # this step will provide resolution warnings
```

### Nx Report

```shell
Nx workspaces are not set up at this example.
```

### Failure Logs

```shell
yarn                                                                                                                                                                                       ─╯
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @nrwl/devkit@npm:16.8.1 doesn't provide nx (p4b00a), requested by @nx/devkit
➤ YN0002: │ @nrwl/vite@npm:16.8.1 doesn't provide vite (p25914), requested by @nx/vite
➤ YN0002: │ @nrwl/vite@npm:16.8.1 doesn't provide vitest (pd1d79), requested by @nx/vite
➤ YN0002: │ @nx/cypress@npm:16.8.1 [7c002] doesn't provide nx (pec146), requested by @nx/devkit
➤ YN0002: │ @nx/cypress@npm:16.8.1 [7c002] doesn't provide typescript (pde18d), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/js@npm:16.8.1 [6016b] doesn't provide @types/node (p32460), requested by ts-node
➤ YN0002: │ @nx/js@npm:16.8.1 [6016b] doesn't provide nx (pd6dfb), requested by @nx/devkit
➤ YN0002: │ @nx/js@npm:16.8.1 [6016b] doesn't provide typescript (p70177), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/js@npm:16.8.1 [6016b] doesn't provide typescript (pe6efe), requested by ts-node
➤ YN0002: │ @nx/linter@npm:16.8.1 [6c692] doesn't provide nx (p14405), requested by @nx/devkit
➤ YN0002: │ @nx/linter@npm:16.8.1 [ac300] doesn't provide nx (p3aa7f), requested by @nx/devkit
➤ YN0002: │ @nx/react@npm:16.8.1 doesn't provide nx (p351db), requested by @nx/devkit
➤ YN0002: │ @nx/react@npm:16.8.1 doesn't provide typescript (p6ff2a), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/react@npm:16.8.1 doesn't provide webpack (p7643c), requested by file-loader
➤ YN0002: │ @nx/storybook@npm:16.8.1 doesn't provide nx (p84ecf), requested by @nx/devkit
➤ YN0002: │ @nx/storybook@npm:16.8.1 doesn't provide typescript (p37c68), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/vite@npm:16.8.1 [ac300] doesn't provide nx (p758ea), requested by @nx/devkit
➤ YN0002: │ @nx/vite@npm:16.8.1 [ac300] doesn't provide typescript (pa44c5), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/vite@npm:16.8.1 [f02a2] doesn't provide nx (p5db10), requested by @nx/devkit
➤ YN0002: │ @nx/vite@npm:16.8.1 [f02a2] doesn't provide typescript (pf4433), requested by @phenomnomnominal/tsquery
➤ YN0002: │ @nx/web@npm:16.8.1 doesn't provide nx (p00a7c), requested by @nx/devkit
➤ YN0002: │ @nx/webpack@npm:16.8.1 doesn't provide nx (pab399), requested by @nx/devkit
➤ YN0002: │ @nx/webpack@npm:16.8.1 doesn't provide typescript (p5ae8a), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @nx/webpack@npm:16.8.1 doesn't provide typescript (p65354), requested by ts-loader
...
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 450ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 564ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 673ms
➤ YN0000: Done with warnings in 2s 13ms
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by aevaldas** [comment] 2024-03-21 08:32
Wow 🙌

**Comment by Jazzmanpw** [comment] 2024-04-19 07:54
I'm interested in it as well. I fixed these dependencies with yarn config, but it looks terrible

**Comment by FrozenPandaz** [comment] 2024-05-15 21:55
Sorry, I'm not sure I understand the issue. Our dependencies rely on other dependencies being installed. If you use the generators those packages come with, then the dependencies will be setup properly automatically. If you don't use the generators, then these warnings instruct you that you are missing dependencies which you can remedy by installing them into your workspace.

I'm going to mark this issue as closed as I don't think there is actionable for us to do here.

If there is a specific peer dependency which is not needed or isn't specified properly as optional, please open a separate issue.

**Closed by FrozenPandaz** 2024-05-15 21:55 UTC
Labels: type: bug, blocked: more info needed, scope: misc

**Comment by Jazzmanpw** [comment] 2024-05-15 23:33
@FrozenPandaz the issue is that [yarn is strict on peer dependency handling](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency). Nx packages have some implicit peer deps, yarn doesn't like it. Adding `peerDependencies` to a couple of `package.json` would fix the issue. It shouldn't change anything at the runtime, but it allows yarn to guess less
