### ISSUE TITLE
After Upgrade to 15.9.2 Circuclar Dependency Error

### ISSUE THREAD

**Issue by Kyoss79** [nrwl/nx#16321] opened 2023-04-15 12:08 UTC
### Current Behavior

When linting the project, I get the message, that there is a circular dependency between an app and a library.

`/Users/xxx/apps/jpi/src/pages/p/[page].tsx
   7:1   error    Circular dependency between "jpi" and "ui" detected: jpi -> ui -> jpi

Circular file chain:
- apps/jpi/src/pages/p/[page].tsx
- undefined  @nrwl/nx/enforce-module-boundaries
`

However it is nowhere stated where that circular dependency should come from.

The dep-graph does **not** show any imports from "lib" into "jpi". There is a arrow, but the file list is empty.

### Expected Behavior

I wish it would just work like before the update to 15.9.2

### Steps to Reproduce

1. run lint
2. see error

### Nx Report

```shell
Node : 16.15.1
   OS   : darwin arm64
   pnpm : 7.5.0
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   @nrwl/nx-cloud          : 15.3.5
   typescript              : 4.9.4
```

**Comment by meeroslav** [comment] 2023-04-18 11:33
Thank you @Kyoss79 for reporting this. Can you please provide a minimal repo where this issue can be reproduced?

Please run also `npx nx reset` to make sure you are not experiencing some stale cache issue.

**Comment by danr-za** [comment] 2023-04-20 16:34
Having this one as well, `nx reset` helped but it happened at least twice after it as well...
Might be something bad happening with caching? IIRC, it shouldn't cache failed tasks output, no?


```sh
 2:1  error  Circular dependency between "feature-a" and "feature-b" detected: feature-a -> feature-b -> feature-c -> feature-a

Circular file chain:
- libs/feature-a/Module.ts
- undefined
- [ ... ] # some entries here

@nrwl/nx/enforce-module-boundaries
```

**Comment by MartinDavi** [comment] 2023-04-23 17:24
@danr-za Thanks Dan, `nx reset` fixed this issue for me as well - I agree it's gotta be caching related, I did momentarily have a circular dependency going on as I moved some code around and `nx reset` fixed things.

**Comment by meeroslav** [comment] 2023-04-23 19:35
If one of you can create the exact steps which would help me to reproduce it, it would be amazing.

Or if you can still reproduce it and have time for a debugging session, I would love to hop on a call to get to the bottom of this.

**Comment by danr-za** [comment] 2023-04-23 20:28
Thanks for your willingness @meeroslav .

Okay, I almost gave up, but after a few tries, I was able to reproduce it, steps:
1. Create a circular dependency between 2 libs
2. Generate a new library
3. Remove the import that causes the circular dependency

Result:
```sh
ESLint: 
Circular dependency between "island-feature-auditing-common" and "island-feature-policy-common" detected: island-feature-auditing-common -> island-feature-policy-common -> island-background-common -> island-feature-auditing-common

Circular file chain:
- libs/feature-a/Module.ts
- undefined
- [ ... ]
```

It seems related to modifying `tsconfig.base.json` while having the error.

This makes some sense and might be related to another issue we had, where we moved a library **without** using the `move` generator but rather manually, **did not** update `tsconfig.base.json`, but for some reason, it still **passed** in our CI because it restored everything from cache (which his a bit

**Comment by danr-za** [comment] 2023-04-23 20:29
Thanks for your willingness @meeroslav .

Okay, I almost gave up, but after a few tries, I was able to reproduce it, steps:
1. Create a circular dependency between 2 libs
2. Generate a new library
3. Remove the import that causes the circular dependency

Result:
```sh
ESLint: 
Circular dependency between "feature-a" and "feature-b" detected: feature-a -> feature-b -> feature-c-> feature-a

Circular file chain:
- libs/feature-a/Module.ts
- undefined
- [ ... ]
```

It seems related to modifying `tsconfig.base.json` while having the error.

This makes some sense and might be related to another issue we had, where we moved a library **without** using the `move` generator but rather manually, **did not** update `tsconfig.base.json`, but for some reason, it still **passed** in our CI because it restored everything from cache (which his a bit

**Comment by danr-za** [comment] 2023-04-25 09:14
@meeroslav another **super weird** issue I also had, which might be related to this:
* Ran a custom generator that generates a JS lib called "Foo" (with some modifications)
* Ran `git clean -df` and reverted the `tsconfig.base.json` modifications
* Worked on this branch for a while
* Switched to `main` branch
* Ran `jest MyFile.spec` 

Error it threw:
```sh
Error: Can't find a root directory while resolving a config file path.
Provided path to resolve: /Users/dan/work/apps/libs/foo/jest.config.ts
```

`nx reset` fixed the issue.

I am unsure whether it is the Nx Daemon or some `jest` cache, but it is odd that this file was created and **removed** in a different branch.

I still didn't have an issue with the `build` target, but it is a bit concerning regarding CI and Production builds.
If you want me to open a separate ticket for that LMK.

**Comment by meeroslav** [comment] 2023-04-25 10:22
Hey, @dan-za, thank you for the details. 

We had a known issue on `nx` where the graph was not properly updated when a package was removed.
This should be fixed now. I'll check with latest `v15` and last `v16` beta to see if I can reproduce it.

**Closed** 2023-04-28 17:08 UTC
Labels: type: bug, blocked: repro needed, blocked: more info needed, scope: linter
