### ISSUE TITLE
Impossible to build storybook of lib after upgrading to v13 (possibly wrong ts config)

### ISSUE THREAD

**Issue by VictorienTardif** [nrwl/nx#7846] opened 2021-11-23 08:09 UTC
## Current Behavior
Any imported other lib with `import { x } from "@company/otherLib"` generates a `Module not found: Error: Can't resolve '@company/otherLib' in currentLib/.storybook`.

But it's working fine with v12.

## Steps to Reproduce
I just ran `nx migrate latest` and applied migrations. 

Note that when applying migrations, I got a message:
```
Running migration migration-v13
    Could not find TypeScript project for project: currentLib
    Could not find TypeScript project for project: otherLib
```

I think that it could be the main problem as building after upgrading I see `Using angular project with "tsConfig:apps/public/tsconfig.app.json` and I don't see `Loading 1 config file` anymore:

Before upgrading:
```
info => Cleaning outputDir: xxx/xxx/dist/storybook/currentLib
info => Loading presets
info => Compiling manager..
info => Compiling preview..
info => Loading 1 config file in "xxx/xxx/libs/currentLib/.storybook"
info => Loading 8 other files in "xxx/xxx/libs/currentLib/.storybook"
info => Adding stories defined in "xxx/xxx/libs/currentLib/.storybook/main.js"
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "public:build" for configuring Storybook
info => Using angular-cli webpack config
info => Using default Webpack5 setup
...
>  NX   SUCCESS  Running target "build-storybook" succeeded
```

After upgrading:
```
info => Cleaning outputDir: xxx/xxx/dist/storybook/currentLib
info => Loading presets
info => Compiling manager..
info => Compiling preview..
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config for angular >= 13.0.0
info => Using angular browser target options from "public:build"
info => Using angular project with "tsConfig:apps/public/tsconfig.app.json"
info => Using default Webpack5 setup
Starting type checking service...
ERR! => Failed to build the preview
ERR! Module not found: Error: Can't resolve '@company/otherLib' in 'xxx/xxx/libs/currentLib/.storybook'
```

### Environment
```
  Node : 14.15.0
  OS   : darwin x64
  yarn : 1.22.17
  
  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : undefined
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/cdk: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/fire: 7.1.1
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/platform-server: 13.0.2
         @angular/router: 13.0.2
         @angular/service-worker: 13.0.2
         @ionic/angular: 5.8.5
         @ngneat/transloco: 2.23.3
         @nguniversal/express-engine: 12.1.2
         @taiga-ui/core: 2.21.0
         @angular-devkit/architect: 0.1202.8
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @nguniversal/builders: 12.1.2
         @storybook/angular: 6.4.0-rc.3

```

**Comment by LukasMachetanz** [comment] 2021-11-23 13:17
I can confirm the issue. Struggling with the same.

**Comment by mehmet-erim** [comment] 2021-11-24 09:00
Same here

**Comment by VictorienTardif** [comment] 2021-11-24 13:47
@mehmet-erim this is not the problem I have so you might want to open an other issue.
For me the problem is a `Module not found: Error` when building storybook but the migration succeeded and I never encountered your issue.

**Comment by mehmet-erim** [comment] 2021-11-24 14:48
@VictorienTardif OK, I've created:
https://github.com/nrwl/nx/issues/7866

**Comment by KylerJohnsonDev** [comment] 2021-11-24 15:49
Until this is resolved, a possible work around is to use a relative file path in your import statement. Nx's linting doesn't like this, however, so you'll need to disable it for that line. 

Here's what I had that broke with this update:
```typescript
import { SomeModel } from '@client/domain/models';
```

The work around:
```typescript
// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import { SomeModel } from '../../../../../domain/models/src/index';
```

**Comment by oco2000** [comment] 2021-11-26 08:19
My workaround is to add this to main.js of strybook to modify webpack configuration:

```
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

...

config.resolve.plugins = config.resolve.plugins || [];
    config.resolve.plugins.push(
      new TsconfigPathsPlugin({
        configFile: 'insert filename of your tsconfig.json here'
      })
    );
```

**Comment by LukasMachetanz** [comment] 2021-11-26 10:05
My error looks like this when running `nx run-many --target=build-storybook --configuration production --all`:

```
> nx run auth-data-service-skeleton:build-storybook 

>  NX  ui framework: @storybook/angular


>  NX  Storybook builder starting ...

info => Cleaning outputDir: /Users/machetanz/@smarter-ecommerce/ui-foundation/dist/storybook/auth-service-skeleton
info => Loading presets
WARN   Failed to load preset: "/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js"
ERR! Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/bundles/ngcc/index.js
ERR! require() of ES modules is not supported.
ERR! require() of /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
ERR! Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/package.json.
ERR! 
ERR!     at new NodeError (internal/errors.js:322:7)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at interopRequireDefault (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20)
ERR!  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/bundles/ngcc/index.js
ERR! require() of ES modules is not supported.
ERR! require() of /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/bundles/ngcc/index.js from /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
ERR! Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@angular/compiler-cli/package.json.
ERR! 
ERR!     at new NodeError (internal/errors.js:322:7)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at Object.<anonymous> (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/angular/dist/ts3.9/server/framework-preset-angular-ivy.js:70:14)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:93:18)
ERR!     at interopRequireDefault (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:159:16)
ERR!     at getContent (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:175:10)
ERR!     at loadPreset (/Users/machetanz/@smarter-ecommerce/ui-foundation/node_modules/@storybook/core-common/dist/cjs/presets.js:184:20) {
ERR!   code: 'ERR_REQUIRE_ESM'
ERR! }
info => Compiling manager..
info => Compiling preview..
info => Loading 1 config file in "/Users/machetanz/@smarter-ecommerce/ui-foundation/libs/auth-data-service-skeleton/.storybook"
info => Loading 9 other files in "/Users/machetanz/@smarter-ecommerce/ui-foundation/libs/auth-data-service-skeleton/.storybook"
info => Adding stories defined in "/Users/machetanz/@smarter-ecommerce/ui-foundation/libs/auth-data-service-skeleton/.storybook/main.js"
info => Found custom tsconfig.json
info => Using implicit CSS loaders
info => Loading angular-cli config
info => Using angular project "design-system-demo:build" for configuring Storybook
ERR! => Could not get angular cli webpack config
Cannot read property 'target' of undefined

```

**Comment by VictorienTardif** [comment] 2021-11-30 08:36
FYI https://github.com/storybookjs/storybook/issues/16759

**Comment by yharaskrik** [comment] 2021-12-02 02:55
I can confirm I'm running into both the import issue and the esm issue. With my packages fully updated I get the esm, then it continues then fails with the import issue.

**Comment by VictorienTardif** [comment] 2021-12-03 09:14
I did not test yet but it should be fixed in latest Storybook release, see : https://github.com/storybookjs/storybook/issues/16759#issuecomment-985306563

And in next Nx release: https://github.com/nrwl/nx/pull/7917

**Comment by mandarini** [comment] 2021-12-06 10:49
PR merged, so closing this! :)

**Closed by mandarini** 2021-12-06 10:49 UTC
Labels: type: bug, scope: storybook

**Comment by LukasMachetanz** [comment] 2021-12-06 12:57
Thanks for tackling this. Everything works as expected now.
