### ISSUE TITLE
E2E (14.5.1 ): Error when using multiple --env with github and NX_CLOUD_DISTRIBUTED_EXECUTION

### ISSUE THREAD

**Issue by ureciocais** [nrwl/nx#11401] opened 2022-08-02 13:55 UTC
## Current Behavior

Prior we've been executing our e2e providing 3 env vars to Cypress.
Something like `yarn nx run project-e2e:e2e --env.USERNAME --env.PASSWORD --env.SECRET`
It's been working fine with NX_CLOUD_DISTRIBUTED_EXECUTION, until this version: 14.5.1
Now we are getting this error: "Property 'env' does not match the schema. '[object' should be a 'object'"

## Expected Behavior

I would expect it to forward the env vars to the agents. It looks like instead, it is forwarding the string "--env=[object Object]"

## Steps to Reproduce

Create a workflow on github, with agents, where you run the e2e nx command on a project and pass in several envs, as shown above

### Environment

 @nrwl/express : Not Found
   @nrwl/jest : 14.5.1
   @nrwl/js : 14.5.1
   @nrwl/linter : 14.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.1
   @nrwl/nx-cloud : 14.2.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.1
   @nrwl/web : 14.5.1
   @nrwl/workspace : 14.5.1
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

**Comment by AgentEnder** [comment] 2022-08-02 14:18
Duplicate of #10808

**Closed by AgentEnder** 2022-08-02 14:18 UTC
Labels: type: bug, scope: testing tools
