### ISSUE TITLE
@nx/vite no waiting for vite-plugin-checker on build 

### ISSUE THREAD

**Issue by acroquelois** [nrwl/nx#21043] opened 2024-01-08 15:07 UTC
### Current Behavior

When I build my app with @nx/vite and vite-plugin-checker activated in my vite.config.ts, the build command doesn't wait the vite-plugin-checker output to end command. So, even if I have errors in my vite-plugin-checker, the command succeeds.

### Expected Behavior

It seems more logical that the buid command should fail on the failure of vite-plugin-checker

### Steps to Reproduce

1. project.json

```
"build": {
      "executor": "@nx/vite:build",
      "outputs": ["{options.outputPath}"],
      "defaultConfiguration": "production",
      "configurations": {
        "development": {
          "mode": "development"
        },
        "production": {
          "mode": "production"
        },
        "pilot": {
          "mode": "pilot"
        },
        "preview": {
          "mode": "preview"
        }
      },
      "options": {
        "outputPath": "services/view/dist",
        "configFile": "services/view/vite.config.ts",
        "skipTypeCheck": true
      }
    }
```

2. vite.conf.ts

```
plugins: [
      VueDevTools(),
      tsconfigPaths({
        root: path.resolve(__dirname),
      }),
      checker({
        // typescript: true,
        vueTsc: {
          root: path.resolve(__dirname),
        },
      }),
    ],
```

3. Run nx build and see that it succeed even if type checker failed

### Nx Report

```shell
Node   : 20.2.0
   OS     : linux-x64
   yarn   : 1.22.19
   
   nx             : 17.2.8
   @nx/js         : 17.2.8
   @nx/jest       : 17.2.8
   @nx/linter     : 17.2.8
   @nx/eslint     : 17.2.8
   @nx/workspace  : 17.2.8
   @nx/cypress    : 17.2.8
   @nx/devkit     : 17.2.8
   @nrwl/tao      : 17.2.8
   @nx/vite       : 17.2.8
   @nx/webpack    : 17.2.8
   typescript     : 4.9.5
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

When i run native ```vite build``` I have the expected behaviour

**Comment by mandarini** [comment] 2024-01-10 15:39
Hi there @acroquelois thanks for filing an issue! We are moving away from executors soon, so the intention is indeed to use the native `vite build` function. If I have time during the next week I'll take a look as to what we may be missing in your case, if you can provide a simple reproduction repository it will be super helpful, but in any case your error will go away soon, once we move over to not using our executors.

**Comment by mandarini** [comment] 2024-05-10 13:16
I'll be closing this issue now, since starting Nx 18 this should be resolved, since we're using `vite build` directly! Please feel free to re-open if it persists beyond Nx 18!

**Closed by mandarini** 2024-05-10 13:16 UTC
Labels: type: bug, scope: bundlers
