### ISSUE TITLE
NX spam opens and closes console when files are added/removed

### ISSUE THREAD

**Issue by OscarVantagePOS** [nrwl/nx#11247] opened 2022-07-22 00:22 UTC
## Current Behavior

When running a command that adds/removes files (e.g `npm install` or `git checkout`) a console windows are opened and closed repeatedly for a few seconds.

## Expected Behavior

When files are added/removed all NX operations are run in the background.

## Steps to Reproduce

Running `npm install` on a Windows machine with an NX repo

### Failure Logs

N/A

### Environment

```
   Node : 16.15.1
   OS   : win32 x64
   npm  : 8.11.0

   nx : 14.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : Not Found
   @nrwl/js : Not Found
   @nrwl/linter : Not Found
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment] 2022-07-28 21:55
Sorry, it's not clear how to reproduce it. We tried on a Windows machine and could not reproduce it.

What version of Windows are you on? What is your default terminal?

**Comment by OscarVantagePOS** [comment] 2022-07-28 23:52
I am on Windows 11 (build no. 22000.795) and my default terminal is the newer Windows Terminal.

**Comment by FrozenPandaz** [comment] 2022-07-29 20:20
Ah thank you for the information.

There's also a duplicate issue here: https://github.com/nrwl/nx/issues/10822

I'm going to close this in favor of that one. Thank you for providing more information here!

**Closed by FrozenPandaz** 2022-07-29 20:20 UTC
Labels: type: bug, blocked: more info needed, scope: core

**Comment by OscarVantagePOS** [comment] 2022-07-31 23:43
Yes can confirm this is a duplicate. Thanks
