### ISSUE TITLE
Generate @nrwl/node:application command not working

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#5719] opened 2021-05-19 16:20 UTC
## Current Behavior

When running the `nx generate @nrwl/node:application <node-app>` command, an error gets thrown.

```
Expected argument `jsonString` to be a `string`, got `object`
```

## Expected Behavior

The command should work.

### Environment

Node : 14.15.4                  
OS   : win32 x64                
yarn : 2.4.1                    
                                
nx : 11.1.1                     
@nrwl/angular : Not Found       
@nrwl/cli : 12.1.1              
@nrwl/cypress : 12.1.1          
@nrwl/devkit : 12.1.1           
@nrwl/eslint-plugin-nx : 12.1.1 
@nrwl/express : Not Found       
@nrwl/jest : 12.1.1             
@nrwl/linter : 12.1.1           
@nrwl/nest : Not Found          
@nrwl/next : Not Found          
@nrwl/node : 12.3.4             
@nrwl/react : 12.1.1            
@nrwl/schematics : 8.12.11      
@nrwl/tao : 12.1.1              
@nrwl/web : 12.1.1              
@nrwl/workspace : 12.1.1        
@nrwl/storybook : 12.1.1        
@nrwl/gatsby : Not Found        
typescript : 4.2.4

**Comment by Peter-NZ** [comment] 2021-05-20 01:51
I ran into the same issue today using the @nrwl/gatsby generators as well as the @nrwl/node generators. After some debugging it looks like it was caused by read the read method in the tree class of @nrwl/tao returning a buffer instead of a string due to the generator using the wrong version of the @nrwl/tao for some reason. The version causing the error was lacking the method signature "encoding" param present in the correct version.

I resolved it for now by adding @nrwl/tao as a dependency for my project. I'll do some more looking into it later but hope this works for you!

**Comment by nemonemi** [comment] 2021-05-20 06:19
@Peter-NZ thanks for the hint! It worked like this for me as well.
However, I'll keep this bug opened because it should not be the desired workflow.

**Comment by ismael-su** [comment] 2021-05-20 13:37
This has something to do with the latest version, @Peter-NZ 's solution didn't work for me, i had to install version the version 11.4.0 or @nrwl/react in order to get it work.

**Comment by nemonemi** [comment] 2021-05-20 13:50
@ismael-su, as you can see above, I have version 12.1.1, which is not the latest, but it still works.

**Comment by Corsico** [comment] 2021-05-20 18:21
Have the same issue trying to generate @nrwl/react 
nx version 12.3.3 
node v16.1.0
npm v7.11.2

**Comment by rullymartanto** [comment] 2021-05-21 07:15
How to downgrade the version ? maybe still working in the old version ?

**Comment by ismael-su** [comment] 2021-05-21 07:29
@rullymartanto  just go to package.json file and find the line "@nrwl/react" in dependencies and change whatever version you have there with the one I just mentioned

**Comment by rullymartanto** [comment] 2021-05-21 08:05
@ismael-su  still not working, can I know your package.json ?

**Comment by nemonemi** [comment] 2021-05-21 08:51
@rullymartanto have you tried with these versions?
Node : 14.15.4
OS : win32 x64
yarn : 2.4.1

nx : 11.1.1
@nrwl/angular : Not Found
@nrwl/cli : 12.1.1
@nrwl/cypress : 12.1.1
@nrwl/devkit : 12.1.1
@nrwl/eslint-plugin-nx : 12.1.1
@nrwl/express : Not Found
@nrwl/jest : 12.1.1
@nrwl/linter : 12.1.1
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : 12.3.4
@nrwl/react : 12.1.1
@nrwl/schematics : 8.12.11
@nrwl/tao : 12.1.1
@nrwl/web : 12.1.1
@nrwl/workspace : 12.1.1
@nrwl/storybook : 12.1.1
@nrwl/gatsby : Not Found
typescript : 4.2.4

**Comment by rullymartanto** [comment] 2021-05-21 09:09
still not working,..

**Comment by nemonemi** [comment] 2021-05-21 09:16
Here's my package.json's complete list of dependencies. Hope it helps.
<details>
<summary>Package.json dependencies list</summary>
<p>

```
"dependencies": {
    "@graphql-mesh/cli": "0.29.14",
    "@graphql-mesh/graphql": "0.17.9",
    "@graphql-mesh/transform-mock": "0.9.5",
    "@material-ui/core": "4.11.3",
    "@material-ui/data-grid": "4.0.0-alpha.24",
    "@material-ui/icons": "~4.11.2",
    "@material-ui/lab": "4.0.0-alpha.57",
    "@material-ui/x-grid": "4.0.0-alpha.24",
    "@material-ui/x-grid-data-generator": "4.0.0-alpha.24",
    "ag-grid-community": "25.1.0",
    "ag-grid-enterprise": "25.1.0",
    "ag-grid-react": "25.1.0",
    "axios": "~0.21.1",
    "core-js": "~3.9.1",
    "document-register-element": "1.13.1",
    "graphql": "15.5.0",
    "i18next": "~19.9.1",
    "i18next-xhr-backend": "~3.2.2",
    "lodash": "~4.17.21",
    "nodemon": "2.0.7",
    "postscribe": "2.0.8",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-error-boundary": "3.1.1",
    "react-i18next": "11.8.8",
    "react-is": "17.0.2",
    "react-query": "3.12.0",
    "react-router-dom": "~5.2.0",
    "react-transition-group": "~4.4.1",
    "styled-components": "5.3.0",
    "tslib": "2.1.0"
  },
  "devDependencies": {
    "@babel/core": "7.13.8",
    "@babel/helper-builder-react-jsx-experimental": "7.12.11",
    "@babel/helper-regex": "7.10.5",
    "@babel/preset-env": "7.13.9",
    "@babel/preset-react": "7.12.13",
    "@babel/preset-typescript": "7.13.0",
    "@nrwl/cli": "12.1.1",
    "@nrwl/cypress": "12.1.1",
    "@nrwl/eslint-plugin-nx": "12.1.1",
    "@nrwl/jest": "12.1.1",
    "@nrwl/react": "12.1.1",
    "@nrwl/schematics": "8.12.11",
    "@nrwl/storybook": "12.1.1",
    "@nrwl/tao": "12.1.1",
    "@nrwl/web": "12.1.1",
    "@nrwl/workspace": "12.1.1",
    "@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
    "@storybook/addon-essentials": "6.1.21",
    "@storybook/addon-knobs": "6.1.11",
    "@storybook/react": "6.1.11",
    "@svgr/webpack": "5.4.0",
    "@testing-library/cypress": "7.0.4",
    "@testing-library/jest-dom": "5.11.9",
    "@testing-library/react": "11.2.5",
    "@testing-library/react-hooks": "5.1.0",
    "@testing-library/user-event": "12.8.1",
    "@types/faker": "~5.1.7",
    "@types/jest": "26.0.20",
    "@types/lodash": "4.14.168",
    "@types/node": "14.14.33",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.3",
    "@types/react-is": "17.0.0",
    "@types/react-router-dom": "5.1.7",
    "@types/react-transition-group": "~4.4.1",
    "@types/styled-components": "5.1.9",
    "@types/webpack": "4.41.26",
    "@typescript-eslint/eslint-plugin": "4.19.0",
    "@typescript-eslint/parser": "4.19.0",
    "babel-jest": "26.6.3",
    "babel-loader": "8.2.2",
    "babel-plugin-styled-components": "1.12.0",
    "commitizen": "~4.2.2",
    "conventional-changelog-cli": "2.1.1",
    "css-loader": "5.2.4",
    "cypress": "6.6.0",
    "cz-customizable": "~6.3.0",
    "dotenv": "8.2.0",
    "eslint": "7.22.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "2.11.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "faker": "~5.1.0",
    "file-loader": "^6.2.0",
    "husky": "4",
    "jest": "26.6.3",
    "jest-styled-components": "7.0.3",
    "lcov-result-merger": "~3.1.0",
    "lint-staged": "10.5.4",
    "miragejs": "~0.1.41",
    "prettier": "2.2.1",
    "react-refresh": "0.10.0",
    "sass-loader": "10.2.0",
    "style-loader": "2.0.0",
    "ts-jest": "26.5.5",
    "ts-node": "9.1.1",
    "tslint": "6.1.3",
    "type-fest": "0.16.0",
    "typescript": "4.2.4",
    "typescript-styled-plugin": "~0.15.0",
    "url-loader": "3.0.0",
    "webpack": "4.44.2"
  },
```
</p>
</details>

**Comment by ochomoswill** [comment] 2021-05-23 16:47
I experienced the same issue.

I was able to fix it by:

1. Updating nx packages by running:
    ```yarn nx migrate latest```
2. Installed the updated nx packages
    ```yarn```

After this, the error was no more.

**Comment by rullymartanto** [comment] 2021-05-24 03:53
@ochomoswill  Awesome it's work 
`$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/cli@12.3.4
Fetching @nrwl/cypress@12.3.4
Fetching @nrwl/devkit@12.3.4
Fetching @nrwl/eslint-plugin-nx@12.3.4
Fetching @nrwl/express@12.3.4
Fetching @nrwl/jest@12.3.4
Fetching @nrwl/linter@12.3.4
Fetching @nrwl/node@12.3.4
Fetching @nrwl/react@12.3.4
Fetching @nrwl/storybook@12.3.4
Fetching @nrwl/tao@12.3.4
Fetching @nrwl/web@12.3.4
Fetching @nrwl/workspace@12.3.4

>  NX  The migrate command has run successfully.

- package.json has been updated
- migrations.json has been generated

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'
- Run 'nx migrate --run-migrations'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
`

**Comment by AgentEnder** [comment] 2021-06-24 21:33
I'm going to close this for now, but if anyone is still having issues here ping me and I'll get it reopened.

**Closed by AgentEnder** 2021-06-24 21:33 UTC
Labels: scope: node, type: bug
