### ISSUE TITLE
Error: Value is non of these types

### ISSUE THREAD

**Issue by canataly-backupta** [nrwl/nx#28560] opened 2024-10-22 13:02 UTC
### Current Behavior

After updating to Nx19, running nx server/build in my monorepo fails with

```
 NX   Daemon process terminated and closed the connection

Please rerun the command, which will restart the daemon.
If you get this error again, check for any errors in the daemon process logs found in /<repo-path>/.nx/workspace-data/d/daemon.log
```

### Expected Behavior

Should properly execute Nx command on my monorepo

### Steps to Reproduce

1. Migrate from 19.8.2 to 19.8.3

### Nx Report
```
Node           : 22.9.0
OS             : linux-x64
Native Target  : x86_64-linux
yarn           : 1.22.22

nx (global)        : 20.0.0
nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/cypress        : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.3
@nx/react          : 20.0.3
@nx/storybook      : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/storybook/plugin
```
### Failure Logs
```
[NX Daemon Server] - 2024-10-22T12:54:35.513Z - Started listening on: /tmp/50625ecafd77cce1884f/d.sock
[NX Daemon Server] - 2024-10-22T12:54:35.515Z - [WATCHER]: Subscribed to changes within: /<project-path> (native)
[NX Daemon Server] - 2024-10-22T12:54:35.517Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-10-22T12:54:35.518Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-22T12:54:35.519Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-10-22T12:54:35.520Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-10-22T12:54:36.027Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-10-22T12:54:36.027Z - [REQUEST]: 
[NX Daemon Server] - 2024-10-22T12:54:36.027Z - [REQUEST]: 
[NX Daemon Server] - 2024-10-22T12:54:36.115Z - Time taken for 'loadNxPlugins' 504.32701399999996ms
[NX Daemon Server] - 2024-10-22T12:54:36.115Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-22T12:54:36.115Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-22T12:54:36.116Z - Closed a connection. Number of open connections: 2
[NX Daemon Server] - 2024-10-22T12:54:36.116Z - Established a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-22T12:54:36.119Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.120Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.120Z - Handled HASH_GLOB. Handling time: 2. Response time: 1.
[NX Daemon Server] - 2024-10-22T12:54:36.120Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-22T12:54:36.121Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-22T12:54:36.121Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-22T12:54:36.124Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.124Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.124Z - Handled HASH_GLOB. Handling time: 2. Response time: 0.
[NX Daemon Server] - 2024-10-22T12:54:36.129Z - [REQUEST]: Responding to the client. handleGlob
[NX Daemon Server] - 2024-10-22T12:54:36.130Z - Done responding to the client handleGlob
[NX Daemon Server] - 2024-10-22T12:54:36.130Z - Handled GLOB. Handling time: 4. Response time: 1.
[NX Daemon Server] - 2024-10-22T12:54:36.130Z - Established a connection. Number of open connections: 5
[NX Daemon Server] - 2024-10-22T12:54:36.135Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.136Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.136Z - Handled HASH_GLOB. Handling time: 4. Response time: 1.
[NX Daemon Server] - 2024-10-22T12:54:36.136Z - Closed a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-22T12:54:36.140Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.140Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.140Z - Handled HASH_GLOB. Handling time: 3. Response time: 0.
[NX Daemon Server] - 2024-10-22T12:54:36.143Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.144Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.145Z - Handled HASH_GLOB. Handling time: 2. Response time: 2.
[NX Daemon Server] - 2024-10-22T12:54:36.167Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.168Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.168Z - Handled HASH_GLOB. Handling time: 3. Response time: 1.
[NX Daemon Server] - 2024-10-22T12:54:36.282Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.282Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.282Z - Handled HASH_GLOB. Handling time: 5. Response time: 0.
[NX Daemon Server] - 2024-10-22T12:54:36.287Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.287Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.287Z - Handled HASH_GLOB. Handling time: 4. Response time: 0.
[NX Daemon Server] - 2024-10-22T12:54:36.292Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.292Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.292Z - Handled HASH_GLOB. Handling time: 4. Response time: 0.
[NX Daemon Server] - 2024-10-22T12:54:36.299Z - [REQUEST]: Responding to the client. handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.300Z - Done responding to the client handleHashGlob
[NX Daemon Server] - 2024-10-22T12:54:36.300Z - Handled HASH_GLOB. Handling time: 4. Response time: 1.
[NX Daemon Server] - 2024-10-22T12:54:36.337Z - [WATCHER]: Processing file changes in outputs

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {},
  addMatchAll: true
}
[33mThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.[39m
(node:15913) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at /<project-path>/tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: '/<project-path>/tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: '/<project-path>',
  paths: {
  },
  addMatchAll: true
}
- REPEATS-REMOVED -
[NX Daemon Server] - 2024-10-22T12:55:30.224Z - Time taken for 'build-project-configs' 718.630228ms
[NX Daemon Server] - 2024-10-22T12:55:30.235Z - Time taken for '@nx/vite/plugin:createDependencies' 22.040336000000025ms
[NX Daemon Server] - 2024-10-22T12:55:30.236Z - Time taken for '@nx/storybook/plugin:createDependencies' 20.0159450000001ms
[NX Daemon Server] - 2024-10-22T12:55:30.284Z - [SYNC]: collect registered sync generators
[NX Daemon Server] - 2024-10-22T12:55:30.286Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-10-22T12:55:30.288Z - Time taken for 'total for creating and serializing project graph' 1295.4297479999998ms
[NX Daemon Server] - 2024-10-22T12:55:30.290Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-10-22T12:55:30.290Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 1295. Response time: 5.
[NX Daemon Server] - 2024-10-22T12:55:30.510Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-22T12:57:08.804Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-22T12:57:08.805Z - Closed a connection. Number of open connections: 3
[NX Daemon Server] - 2024-10-22T12:57:08.806Z - Established a connection. Number of open connections: 4
[NX Daemon Server] - 2024-10-22T12:57:08.808Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-10-22T12:57:08.809Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2024-10-22T12:57:08.811Z - Time taken for 'total for creating and serializing project graph' 0.4656529999920167ms
[NX Daemon Server] - 2024-10-22T12:57:08.813Z - Done responding to the client project-graph
[NX Daemon Server] - 2024-10-22T12:57:08.813Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 1. Response time: 4.
/<project-path>/node_modules/nx/src/hasher/native-task-hasher-impl.js:10
        this.projectGraphRef = (0, native_1.transferProjectGraph)((0, transform_objects_1.transformProjectGraphForRust)(projectGraph));
                                                                 ^

Error: Value is non of these types `InputsInput`, `String`, `FileSetInput`, `RuntimeInput`, `EnvironmentInput`, `ExternalDependenciesInput`, `DepsOutputsInput`, 
    at new NativeTaskHasherImpl (/<project-path>/node_modules/nx/src/hasher/native-task-hasher-impl.js:10:66)
    at new InProcessTaskHasher (/<project-path>/node_modules/nx/src/hasher/task-hasher.js:36:27)
    at handleHashTasks (/<project-path>/node_modules/nx/src/daemon/server/handle-hash-tasks.js:28:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleResult (/<project-path>/node_modules/nx/src/daemon/server/server.js:172:16)
    at async handleMessage (/<project-path>/node_modules/nx/src/daemon/server/server.js:110:9)
    at async /<project-path>/node_modules/nx/src/daemon/server/server.js:72:9 {
  code: 'InvalidArg'
}
```
### Package Manager Version

1.22.22

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

Using WSL2.

**Comment by andrei-shoreline** [comment] 2024-10-22 14:47
I've got the same issue on macOS. I'm currently on `19.8.2` and the issue is reproducing starting with `19.8.3`.

**Comment by canataly-backupta** [comment] 2024-10-22 14:54
Indeed I confirmed it is starting happening on 19.8.3

**Comment by chrislcs** [comment] 2024-10-23 14:41
I have the same issue. Occurs when the Storybook plugin is used. Without storybook it works fine.

**Comment by xalechez** [comment] 2024-10-24 08:10
Same for me. Migration to v20 didn't help

**Comment by jaysoo** [comment] 2024-10-25 18:25
Fixed in https://github.com/nrwl/nx/pull/28641

We'll cut patches for 19.8 and 20.0.

**Closed** 2024-10-25 18:30 UTC
Labels: type: bug, scope: storybook
