### ISSUE TITLE
Build fails with @nx/webpack:webpack executor when setting generatePackageJson to true

### ISSUE THREAD

**Issue by martialanouman** [nrwl/nx#22040] opened 2024-02-28 14:18 UTC
### Current Behavior

An error is raised when trying to build app with @nx/webpack:webpack executor while the `generatePackageJson` option is set to `true`

### Expected Behavior

Successful build

### Steps to Reproduce

1. Create a workspace
2. Generate a nestjs app
3. Update build task executor in app `project.json`: set build task executor to `@nx/webpack:webpack` and set options accordingly
4. Run `nx build <app_name>` 

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-x64
pnpm   : 8.15.3

nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/nest           : 18.0.5
@nx/node           : 18.0.5
@nx/playwright     : 18.0.5
@nx/react          : 18.0.5
@nx/remix          : 18.0.5
@nrwl/tao          : 18.0.5
@nx/vite           : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-tools/nx-container : 5.2.0
```

### Failure Logs

```shell
NX   The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object

Pass --verbose to see the stacktrace.
```

### Package Manager Version

pnpm@8.15.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

```javascript
// webpack.config.js

const { NxWebpackPlugin } = require('@nx/webpack')
const { join } = require('path')

module.exports = {
	output: {
		path: join(__dirname, '../../dist/apps/gateway'),
	},
	plugins: [
		new NxWebpackPlugin({
			target: 'node',
			compiler: 'tsc',
			main: './src/main.ts',
			tsConfig: './tsconfig.app.json',
			assets: ['./src/assets'],
			optimization: false,
			outputHashing: 'none',
			generatePackageJson: true,
		}),
	],
}

```

Target config in project.json

```json
"build": {
   "executor": "@nx/webpack:webpack",
   "outputs": ["{options.outputPath}"],
   "options": {
     "webpackConfig": "apps/gateway/webpack.config.js",
     "outputPath": "dist/apps/gateway"
   }
 }
```

**Comment by martialanouman** [comment] 2024-03-07 10:21
Hi,
Any update on this ?

**Comment by dan-cooke** [comment] 2024-03-13 19:56
@martialanouman I have the same issue

**Comment by SirPhemmiey** [comment] 2024-03-25 00:32
Hello, any update on this, please?

**Comment by dan-cooke** [comment] 2024-03-25 09:18
I cannot reproduce this, I am using generate package successfully in my project. Check you guys are setting out path correctly

**Comment by SirPhemmiey** [comment] 2024-03-25 09:20
@dan-cooke can you provide the github project for us to compare? and what do you mean by "setting out path correctly">

**Comment by SirPhemmiey** [comment] 2024-03-25 15:49
@dan-cooke i would highly appreciate it, thank you.

**Comment by martialanouman** [comment] 2024-03-29 07:55
Hi @dan-cooke , could you provide the configuration example you mentioned in your last comment?

**Comment by dan-cooke** [comment] 2024-03-29 09:40
```.json
{
  "name": "api",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/api/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "options": {
        "webpackConfig": "apps/api/webpack.config.js",
        "outputPath": "dist/apps/api"
      }
    }
}
```

```.js
const { NxWebpackPlugin } = require('@nx/webpack');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/api'),
  },
  plugins: [
    new NxWebpackPlugin({
      target: 'node',
      compiler: 'tsc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      generatePackageJson: true,
      transformers: [
        {
          name: '@nestjs/swagger/plugin',
          options: {
            introspectComments: true,
          },
        },
      ],
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
    }),
  ],
};
```
Works for me

I can post a min repro someday soon, but have you made sure you are not running with the nx cache? I _always_ run my builds with `--skipNxCache` because i've found it to be stale most of the time

**Comment by martialanouman** [comment] 2024-04-02 10:06
Hi @dan-cooke,
Thanks. Testing it...

**Comment by pmwisdom** [comment] 2024-05-03 21:04
I'm not sure if this helps but I ran into this issue with an application that was using TSC that was importing a SWC library with a custom executor I wrote to generate the application's package json since it couldn't use esbuild or webpack.

My executor looked like this

```javascript
   // The call to getHelperDependenciesFromProjectGraph was failing
    const helperDependencies = getHelperDependenciesFromProjectGraph(
        context.root,
        context.projectName!,
        context.projectGraph!
    );

    const packageJson = createPackageJson(context.projectName!, context.projectGraph!, {
        target: context.targetName,
        root: context.root,
        isProduction: true,
        helperDependencies: helperDependencies.map((dep) => dep.target),
    });
````

Removing the function call `getHelperDependenciesFromProjectGraph` and passing in an empty array for helperDependencies alleviated the issue for that application

**Comment by Coly010** [comment] 2024-05-10 09:28
This issue has been resolved and therefore I'm going to close it.

Thanks everyone for weighing in!

**Closed by Coly010** 2024-05-10 09:28 UTC
Labels: type: bug, scope: bundlers
