### ISSUE TITLE
Web rollup asset paths validation

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#3985] opened 2020-10-28 16:00 UTC
## Description
I would like to change the validation for the assetPath validation inside the @nrwl/web package to use the projectRoot instead of the sourceRoot directory. It would be possible to use other project templates that don't see the assets folder inside of the src directory. Shouldn't be hard to change (example I'd see linked).

Any reason against a change?

**Comment by jaysoo** [comment] 2020-10-30 15:15
Hi @DominikPieper the validation is needed when using string paths.  This is because anything in `src/` would be flattened in the output `dist/`. 

e.g. `libs/mylib/src/README.md` becomes `dist/libs/mylib/README.md`

If you have something outside of `src/` then it would to go `dist/libs/` instead of `dist/libs/mylib/` which is wrong. The workaround for now is to use the glob object instead:

```
{
  "input": "./libs/mylib",
  "glob": "README.md",
  "output": "./"
}
```

We have discussed relaxing the restriction so you can specify a string `libs/mylib/README.md` and have that go to `dist/libs/mylib/README.md`. It is something we have to consider more carefully since it may have implications on existing workspaces.

**Comment by jaysoo** [comment] 2020-11-09 18:09
Going to close this issue since it is working as intended. For anyone experiencing the same issue, please use the glob object workaround.

e.g.

```
{
  "input": "./libs/mylib",
  "glob": "README.md",
  "output": "./"
}
```

^^^ This will copy `libs/mylib/README.md` to `dist/libs/mylib/README.md`. You can use this for other files and directories as well.

**Closed by jaysoo** 2020-11-09 18:09 UTC
Labels: type: question / discussion

**Comment by evanjmg** [comment] 2021-02-02 12:45
@jaysoo  this doesn't seem to work with assets like so: 
```
 {
                "input": "./src/assets",
                "glob": "**/**",
                "output": "./"
              }
```
