### ISSUE TITLE
@nrwl/nx-plugin:e2e does not support plugins using paths from tsconfig.base.json

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#4851] opened 2021-02-20 14:29 UTC
## Current Behavior
When importing within the same workspace plugins e2e fail.

## Expected Behavior
I should be able to run e2e tests in plugins workspace when importing within the same workspace.

## Steps to Reproduce
1. Create new nrwl workspace: `npx create-nx-plugin my-org --pluginName core`
2. Create second plugin: `nx g @nrwl/nx-plugin:plugin serverless`
3. In `core` create some utility method
4. Use it in `serverless`
5. Run `nx e2e serverless-e2e`

[Repository link](https://github.com/Bielik20/nx-plugins/tree/ff1b00e42d605cba38979c1b3d1125b4652cad24).

### Failure Logs

```
    Command failed: npm install --legacy-peer-deps

      at runPackageManagerInstall (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:50:19)
      at newNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:70:3)
      at Object.ensureNxProject (../../packages/nx-plugin/src/utils/testing-utils/nx-project.ts:82:3)
      at tests/serverless.spec.ts:37:7
      at ../../node_modules/tslib/tslib.js:117:75
      at Object.__awaiter (../../node_modules/tslib/tslib.js:113:16)
```

### Environment

```
  Node : 12.18.3
  OS   : darwin x64
  npm  : 6.14.6

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.3.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : 11.3.0
  @nrwl/eslint-plugin-nx : 11.3.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.0
  @nrwl/linter : 11.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.3.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.0
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.0
  typescript : 4.0.7
```

**Comment by Bielik20** [comment] 2021-03-11 10:04
I have done some more digging. I have few conclusions:

1. [nx-plugin e2e builder](https://github.com/nrwl/nx/blob/556385c0122255f072f6a2956bf399fe2166d47d/packages/nx-plugin/src/builders/e2e/e2e.impl.ts#L26) should run build target with `with-deps` so that everything that is needed is built.
2. Second issue is with [ensureNxProject](https://github.com/nrwl/nx/blob/a25e081a84509d83db5c5c4c27d2898dcad79f65/packages/nx-plugin/src/utils/testing-utils/nx-project.ts#L77-L83). It should accept an array of objects:
```ts
interface PatchPackageOptions {
  npmPackageName: string;
  pluginDistPath: string;
}

export function ensureNxProject(
  ...options: PatchPackageOptions[]
): void;
```

I realise this would be a breaking change, so maybe we could craft something entirely new.

---

The second issue is far less pressing, because this is something people can just do for themselves. The first one is a must have, that builder should run with `with-deps` flag so that we can link them as well.

Now, I am not sure, if setting this file path in `package.json` generated by e2e command will work for all packages in dist. I would expect `npm` to "flatten" structure, so that `file` version would take precedence over version generated by `build` command, but this is something to check. We could always update those `package.json` files as well when we are at it.

**Comment by Bielik20** [comment] 2021-03-30 10:09
I think this is important to encourage people to create community plugins.

**Comment by Bielik20** [comment] 2021-04-19 16:27
I did simple POC. I updated workspace.json:

```json
    "nx-serverless-e2e": {
      "projectType": "application",
      "root": "e2e/nx-serverless-e2e",
      "sourceRoot": "e2e/nx-serverless-e2e/src",
      "targets": {
        "e2e": {
          "executor": "@nrwl/nx-plugin:e2e",
          "options": {
            "target": "nx-serverless-e2e:prepare",
            "npmPackageName": "@ns3/nx-serverless",
            "pluginOutputPath": "dist/packages/nx-serverless",
            "jestConfig": "e2e/nx-serverless-e2e/jest.config.js"
          }
        },
        "prepare": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "nx run nx-serverless:build --with-deps"
          }
        }
      }
    },
```

So that ` "target": "nx-serverless-e2e:prepare",`, this should be handled by nx itself so that I would not need to make this workaround.

And then in test:
```ts
  beforeAll(() => {
    ensureDirSync(tmpProjPath());
    cleanup();
    runNxNewCommand('', true);
    patchPackageJsonForPlugin('@ns3/nx-serverless', 'dist/packages/nx-serverless');
    patchPackageJsonForPlugin('@ns3/nx-core', 'dist/packages/nx-core');
    runPackageManagerInstall();
  });
```

This is because `@ns3/nx-serverless` uses stuff from `@ns3/nx-core` and so we need both to be copied.

**Comment by minijus** [comment] 2021-09-16 17:21
It would be great to be able to import from libs (defined in tsconfig.base.json) for executors and generators as well!

**Comment by Bielik20** [comment] 2023-03-12 14:44
fighting a stale bot

**Comment by Chanki-Min** [comment] 2023-03-19 16:45
I'm with you @Bielik20

**Comment by samuelfernandez** [comment] 2023-04-05 08:55
Need help here as well

**Comment by AgentEnder** [comment] 2023-04-05 14:33
I'd love a community contribution here - this has continually gotten pushed back on my priority list unfortunately. Looking at the source provided, there is a change that I'd like made:

Rather than listing all of the dependencies in an array, can we have it as only the root nodes listed? Something like:

```
export async function ensureComplexNxProject(...inputs: PluginInput[]): void {
  ensureDirSync(tmpProjPath());
  cleanup();
  runNxNewCommand();
  const workspaceLibraryDependencies = collectLibraryDependenciesFromGraph(inputs, await createProjectGraphAsync())
  patchPackageJsonForPlugins(inputs);
  runPackageManagerInstall();
}
```

**Comment by samuelfernandez** [comment] 2023-04-05 18:20
> I'd love a community contribution here - this has continually gotten pushed back on my priority list unfortunately. Looking at the source provided, there is a change that I'd like made:
> 
> 
> 
> Rather than listing all of the dependencies in an array, can we have it as only the root nodes listed? Something like:
> 
> 
> 
> ```
> 
> export async function ensureComplexNxProject(...inputs: PluginInput[]): void {
> 
>   ensureDirSync(tmpProjPath());
> 
>   cleanup();
> 
>   runNxNewCommand();
> 
>   const workspaceLibraryDependencies = collectLibraryDependenciesFromGraph(inputs, await createProjectGraphAsync())
> 
>   patchPackageJsonForPlugins(inputs);
> 
>   runPackageManagerInstall();
> 
> }
> 
> ```

I like your approach of automatically inferring dependencies. That being the case, I'd propose to use the existing `ensureNxProject` yet detecting dependencies internally. This way it will just work with existing generators without code changes. Sounds good? Any recommendation on how to get the dist folder for dependent packages? Feel free to assign this issue to me if you agree with the proposal

**Comment by AgentEnder** [comment] 2023-04-05 18:41
We can reuse the existing `ensureNxProject` function, but I'd still want to make use of the `...PluginInput` syntax - this is to support running e2e on a workspace that has multiple plugins installed which aren't necessarily related to each other via the project graph.  

If we reuse `ensureNxProject` for this, the syntax shouldn't change when calling with 1 project so its still not breaking.

**Comment by AgentEnder** [comment] 2023-05-05 22:07
@samuelfernandez I **_really_** appreciate the effort you put in on the PR for this, but we are working on a slightly different more complex approach to solving this problem.


I'm going to close this out as a duplicate of #10992, as our solution path will close both. We are working on this area soon, stay tuned. 📺

**Closed by AgentEnder** 2023-05-05 22:07 UTC
Labels: type: bug, scope: plugins

**Comment by samuelfernandez** [comment] 2023-05-16 12:22
@AgentEnder Thanks for the feedback, it is always good to learn along the way! Looking forward to the new solution 👀

**Comment by tommazzo89** [comment] 2023-06-15 09:11
Hi @AgentEnder,
Issue #10992 has been automatically closed yesterday. Is there any issue or pull request that we can subscribe to in order to be notified when the new solution is ready? That would be really great.

**Comment by tommazzo89** [comment] 2023-06-16 08:59
Hi @AgentEnder,
Great, thanks for reopening #10992 !
