### ISSUE TITLE
npx create-nx-workspace installs Nx 13 packages

### ISSUE THREAD

**Issue by marckassay** [nrwl/nx#10102] opened 2022-05-02 19:54 UTC
## Current Behavior
The following command `npx create-nx-workspace --preset=ts` installs Nx `13.10.3` packages

## Expected Behavior
With Nx `14.0.5` being the current version, I would expect Nx `14.0.5` packages to be installed.

As a workaround, this command installs Nx 14 packages: `npx create-nx-workspace@latest --preset=ts` 

## Steps to Reproduce
The following installs Nx 13 packages: ` npx create-nx-workspace --preset=ts`

### Environment
```
   Node : 16.11.1
   OS   : win32 x64
   npm  : 8.0.0
   
   nx : 13.10.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : 13.10.3
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.3
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by PieterjanDeClippel** [comment] 2022-05-03 12:31
Hi, did you run `npm update --global nx` or `npm install --global nx@latest` in a cmd as Administrator?

**Comment by marckassay** [comment] 2022-05-03 13:09
No, I did not. I don't have Nx installed as a global dep.

**Comment by AgentEnder** [comment] 2022-05-03 17:44
@marckassay Its possible that npx has cached Nx at 13.10.3. Can you try again with `npx create-nx-workspace@latest`?

**Comment by marckassay** [comment] 2022-05-03 20:55
@AgentEnder Having `latest` as a suffix worked! But I mentioned that in the description.

I searched thru Nx repo expecting to find an outdated hard-coded version variable for Nx packages. Unfortunately unable to find anything. More curious at this point in time as to what change is needed.

**Comment by AgentEnder** [comment] 2022-05-03 20:58
There isn't a hard-coded version that you'll find. `npx create-nx-workspace` downloads and runs the create-nx-workspace package. The version that it downloads, is the version that will get created. Because of npx's caching mechanisms, it's possible that this would not automatically be the latest version.

I'm going to close this issue out, since it is working as intended. If you run `npx create-nx-workspace@{v}`, its going to create a workspace containing `nx@{v}` as intended.

**Closed by AgentEnder** 2022-05-03 20:58 UTC
Labels: type: bug, blocked: retry with latest, scope: misc
