### ISSUE TITLE
Angular 11.2.0 project with TailwindCSS not working with Nx Workspace

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#4775] opened 2021-02-12 09:32 UTC
## Current Behavior
If I create a new Angular 11.2.0 project and add TailwindCSS, it works right out of the box. However, it does not work with Nx Workspace. The CSS doesn't get picked up.

## Expected Behavior
TailwindCSS classes should be included

## Steps to Reproduce
- Create a new Angular CLI project
- Add TailwindCSS: yarn add -D tailwindcss, npx tailwindcss init
- Add ng add @nrwl/workspace
- ng serve
[tailwind.zip](https://github.com/nrwl/nx/files/5970775/tailwind.zip)

### Failure Logs
I get this error:
```
Error: ./apps/tailwind/src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
TypeError: getProcessedPlugins is not a function
    at /Users/crash/Desktop/tailwind/node_modules/tailwindcss/lib/processTailwindFeatures.js:75:83
    at LazyResult.runOnRoot (/Users/crash/Desktop/tailwind/node_modules/@angular-devkit/build-angular/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/Users/crash/Desktop/tailwind/node_modules/@angular-devkit/build-angular/node_modules/postcss/lib/lazy-result.js:355:26)
    at async Object.loader (/Users/crash/Desktop/tailwind/node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/index.js:95:14)
    at /Users/crash/Desktop/tailwind/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/crash/Desktop/tailwind/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/crash/Desktop/tailwind/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/crash/Desktop/tailwind/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/crash/Desktop/tailwind/node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/index.js:104:7)

```

### Environment
Node : 12.20.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.1.5

**Comment by olegkuibar** [comment] 2021-02-13 08:18
Upgrading node to the latest version should resolve the issue

**Comment by bjornharvold** [comment] 2021-02-13 10:25
Hi @olegkuibar 

I am using the latest supported version of node 12.x. Angular does not support anything above 12.

To reiterate, this works fine on a new angular 11.2 project but fails the moment you add a Nx Workspace.

**Comment by SebastianSchenk** [comment] 2021-02-13 21:08
Had the same problem. As a workaround, you can create a `postcss.config.js` with the follwong content:
```
module.exports = {
  plugins: {
    tailwindcss: { config: 'apps/<app-name>/tailwind.config.js' },
    autoprefixer: {},
  },
}
```

**Comment by bjornharvold** [comment] 2021-02-15 02:05
@SebastianSchenk So it's happening because of Nx's directory structure?

**Comment by pumano** [comment] 2021-02-15 08:17
@SebastianSchenk I try your solution it's not working for me. 

I use plain css and properly migrated angular project with working tailwind, but after migration to nx tailwind styles not working. Looks like postcss not processed.

**Comment by pumano** [comment] 2021-02-20 19:22
Very important feature for us, because we want to use it asap in our company.

**Comment by brandonroberts** [comment] 2021-02-26 21:32
This seems to be caused by different versions of `postcss` being installed. I was able to fix the issue using `yarn` by adding `"postcss": "8.2.4"` to the `resolutions` in the `package.json` file.

**Comment by jogelin** [comment] 2021-03-11 15:36
and for people who are using [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) I also had to add:

```
...
"resolutions": {
    "postcss": "8.2.8",
    "@angular-devkit/architect": "0.1102.4",
    "@angular-devkit/build-angular": "0.1102.4",
    "@angular/core": "11.2.5"
  }
...
```

because [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) is using an internal dependencies (and not peerDependencies) and it is not yet up to date with the last version

**Comment by bjornharvold** [comment] 2021-03-30 00:52
Is adding postcss as another dependency considered the final solution here?

**Comment by dasuew** [comment] 2021-03-30 09:53
> Is adding postcss as another dependency considered the final solution here?

From my perspective this solution does not work. 
I have no build errors, but the Tailwind CSS classes are not accessible. This means the classes are not imported in my global stylesheet. 
![image](https://user-images.githubusercontent.com/6399116/112969915-fc84c100-914d-11eb-97e5-02c4eea058ae.png)
We just upgraded to Nx. Before that, TailwindCSS works like a charm, but now it´s broken. We would like to use Nx but we depend on TailwindCSS.
We are on nx version 11.6.0 and angular version 11.2.7.
Actually we put the tailwind.config and the postcss.config in the <app-name> folder. I also tried to moved them on hierachy higher to the global <app> folder. But this also does not work. 
Can someone help us out? Do you need more information?

**Comment by leosvelperez** [comment] 2021-04-12 13:11
@bjornharvold I was looking at this issue and tried to follow the reproduction steps you mentioned and those steps didn't work for me.

In a brand new Angular CLI 11.2.8 project, if I run (as in those steps):
- `yarn add -D tailwindcss`;
- `npx tailwindcss init`;

I get the following error:

```bash
❯ npx tailwindcss init
Cannot find module 'autoprefixer'
Require stack:
- /Users/leosvel/code/issues/bar/node_modules/tailwindcss/lib/cli/commands/build.js
- /Users/leosvel/code/issues/bar/node_modules/tailwindcss/lib/cli/commands/index.js
- /Users/leosvel/code/issues/bar/node_modules/tailwindcss/lib/cli/main.js
- /Users/leosvel/code/issues/bar/node_modules/tailwindcss/lib/cli.js
```

`tailwindcss` has `postcss` and `autoprefixer` as peer dependencies and as such we need to install them as well in the project. The official docs don't have an installation section for Angular, but looking at the Vue one you can see you should install those 2 packages as well. By doing so, I was able to properly initialize TailwindCSS, migrate to Nx and everything was working fine as you can see in this repo https://github.com/leosvelperez/tailwind-nx (it's using Nx 11.2.12 as the original post in this issue). The master branch has everything with `npm` and I have another branch there with `yarn` just to make sure everything was working fine in both, there are some difference in regards to resolution, so with `npm` I didn't need to add `postcss` and `autoprefixer` and everything still works. Both branches have atomic commits so you can see step by step what I did there, maybe we're doing some things differently.

I also "reverted" the Nx migration changes in the repo you shared just to make sure I was not doing anything different and I still had the issue regarding TailwindCSS initialization, which was solved by adding the needed deps and from that point on everything works (including the migration to Nx workspace). You can see the modified reproduction here: [tailwind.zip](https://github.com/nrwl/nx/files/6296879/tailwind.zip) with only the `tailwindcss` package added and before running the initialization.

**Comment by leosvelperez** [comment] 2021-04-12 13:24
> From my perspective this solution does not work.
> I have no build errors, but the Tailwind CSS classes are not accessible. This means the classes are not imported in my global stylesheet.

@dasuew could you provide a reproduction repo? It'd help us to troubleshoot it. I created a Nx workspace using version 11.6.0 as you mentioned you're using, I added tailwind to it the same way as I explained in the comment above and it works for me, the classes get applied correctly.

**Comment by dasuew** [comment] 2021-04-18 22:31
> > From my perspective this solution does not work.
> > I have no build errors, but the Tailwind CSS classes are not accessible. This means the classes are not imported in my global stylesheet.
> 
> @dasuew could you provide a reproduction repo? It'd help us to troubleshoot it. I created a Nx workspace using version 11.6.0 as you mentioned you're using, I added tailwind to it the same way as I explained in the comment above and it works for me, the classes get applied correctly.

Hi @leosvelperez, 

thanks for your engagement. We just decided against Nx because of multiple reasons, so from my point of view the issue is resolved. Thanks a lot. Maybe we had some config issues, because wie upgrade an existing Angular app to Nx.

**Comment by pumano** [comment] 2021-04-18 23:56
I also confirm that tailwindcss works with 11.2+ angular and latest nx. I got it.

**Comment by leosvelperez** [comment] 2021-05-05 11:40
Closing this one as per above [comment](https://github.com/nrwl/nx/issues/4775#issuecomment-817799090). If you think this is still an issue, please feel free to reopen it.

**Closed by leosvelperez** 2021-05-05 11:40 UTC
Labels: scope: angular, type: bug

**Comment by duxor** [comment] 2021-08-31 20:43
> > Had the same problem. As a workaround, you can create a `postcss.config.js` in you app folder with the following content:
> > ```
> > module.exports = {
> >   plugins: {
> >     tailwindcss: { config: 'apps/<app-name>/tailwind.config.js' },
> >     autoprefixer: {},
> >   },
> > }
> > ```
> 
> That way you are limited to a single app with tailwind. What if you want your all apps to use it?

Hey @HackPoint 
You can tray with this (works for me in angular v12.1):
```
package.json:

"build:website:prod": "NODE_ENV=production APP_NAME=website ng build --prod --project website"


tailwind.config.js:
module.exports = {
  prefix: "",
  purge: {
    enabled: process.env.NODE_ENV === "production",
    content: [
      `./apps/${process.env.APP_NAME}/src/**/*.html`,
      './libs/**/*.html',
    ]
  },
  mode: 'aot',
  darkMode: "class", // or 'media' or 'class'
  theme: {
    extend: {}
  },
  variants: {
    extend: {}
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")]
};
```

**Comment by faisalmuhammad** [comment] 2021-12-16 19:58
Following worked changes in `tailwind.config.js` worked for me for every app in the mono repo:

```
module.exports = {
    purge: {
        content: [
            './apps/**/src/**/*.{html,ts}',
            './libs/**/*.html'
        ]
    },
}
```

**Comment by benzara-tahar** [comment] 2022-01-03 23:15
in my case I wanted to share the tailwind config for all the libs and apps, so i moved it to the root folder and updated the config file  as follow
```ts 
 content: [
    join(__dirname, 'apps/**/*.{html,ts}'),
    join(__dirname, 'libs/**/*.{html,ts}'),
    ...createGlobPatternsForDependencies(__dirname),
  ],
```
and added the tailwindConfig in angular.json file for the apps and libs

```json
// app
 "customer": {
      "projectType": "application",
      "root": "apps/customer",
      "sourceRoot": "apps/customer/src",
      "prefix": "foodeli",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "outputs": ["{options.outputPath}"],
          "tailwindConfig": "./tailwind.config.js",

// lib

 "components-ui": {
      "projectType": "library",
      "root": "libs/components-ui",
      "sourceRoot": "libs/components-ui/src",
      "prefix": "foodeli-ui",
      "architect": {
        "build": {
          "builder": "@nrwl/angular:ng-packagr-lite",
          "outputs": ["dist/libs/components-ui"],
          "assets": ["libs/components-ui/src/lib/assets"],

          "options": {
            "project": "libs/components-ui/ng-package.json",
            "tailwindConfig": "./tailwind.config.js"
          },
...
.....



```
