### ISSUE TITLE
@nrwl/web:rollup main package.json always points to umd

### ISSUE THREAD

**Issue by diogomiguel** [nrwl/nx#9924] opened 2022-04-21 13:54 UTC
## Current Behavior
package.json main property always refers to umd file even if project.json does not have it in `options.format`

## Expected Behavior
package.json should point to another module if umd is not provided

## Steps to Reproduce
Open project.json. Change `@nrwl/web:rollup` executor options.format to not include umd. e.g:
```
"options": {
     "format": ["esm", "cjs"],
     ....
}
```

Faulty code:
https://github.com/nrwl/nx/blob/master/packages/web/src/executors/rollup/rollup.impl.ts#L308

**Comment by diogomiguel** [comment] 2022-04-21 13:56
This relates or almost duplicate https://github.com/nrwl/nx/issues/8475

**Comment by AgentEnder** [comment] 2022-04-21 16:04
As mentioned this is a duplicate of #8475, so I'm going to close it.

**Closed by AgentEnder** 2022-04-21 16:04 UTC
Labels: type: bug, scope: react
