### ISSUE TITLE
Is there a way I can publish npm libs from nx workspace / libs

### ISSUE THREAD

**Issue by a5hik** [nrwl/nx#428] opened 2018-04-16 10:10 UTC
I created a nx workspace and I added a lib and a demo app that uses the lib, now I need to publish the lib.. Is there a way I can accomplish with nx?

**Comment by noelmace** [comment] 2018-04-18 19:55
Duplicate of #225. Please close.

**Comment by a5hik** [comment] 2018-04-19 01:17
closing this considering #225

**Comment by vsavkin** [comment] 2018-04-25 15:08
Closing this issue. It's duplicate of #225.

**Closed by vsavkin** 2018-04-25 15:08 UTC
