### ISSUE TITLE
VS Code's "Find All References" feature does not find usage of shared code from libraries

### ISSUE THREAD

**Issue by zilia-gmethot** [nrwl/nx#19538] opened 2023-10-10 16:25 UTC
### Current Behavior

When you generate a new library and start using its exported code in applications or libraries, using VS Code's "Find All References" on an exported symbol does not show its usage in the applications and libraries that depend on it.

This is problematic for refactoring such as changing a function's name because the IDE tells you it is not used anywhere, and renaming the function will break all code that depends on it.

From what I can remember, this used to work fine. I'm assuming that VS Code's TypeScript language server made some changes to their [behind-the-scenes in-memory .d.ts generation process](https://www.typescriptlang.org/docs/handbook/project-references.html#caveats-for-project-references) and that the TypeScript configuration generated by default by Nx, which is quite different from [what seems to be suggested in the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/project-references.html#overall-structure), is problematic.

In fact, using project references as explained in the TypeScript documentation, that is using the `composite` option and defining a project reference between the library and the application that uses it, and by having a solution `tsconfig.json` that defines references to all the leaf-nodes projects, makes VS Code's "Find All References" feature work properly again.

However, that requires quite a lot of manual mapping between the projects TypeScript configuration files, and hope that it won't interfere with what Nx expects in term of TypeScript configuration. In addition, this whole process goes against the hands-off approach pitched by Nx.

### Expected Behavior

The expected behavior is that the TypeScript configuration generated by default by Nx for applications and libraries is such that VS Code code navigation and type hints, in particular the "Find All References" feature, work as expected.

### GitHub Repo

https://github.com/zilia-gmethot/nx-vscode-find-references-issue

### Steps to Reproduce

1. Clone the repository and install dependencies.
2. Open the repository with VS Code.
4. Open the file `/libs/my-lib/src/lib/my-lib.ts`, right-click on the function `myLib`, then select "Find All References". You should see that no usage is found.
5. Open the file `/apps/my-app/src/main.ts`. Notice that the function `myLib` is used.
6. Open the file `/libs/my-lib/src/lib/my-lib.ts`, right-click on the function `myLib`, then select "Find All References". You should see that the usage has now been found.

### Nx Report

```shell
Node   : 16.20.2
   OS     : linux-x64
   npm    : 8.19.4

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by BurningEnlightenment** [comment] 2023-11-22 10:10
I think this is a dupe of #3106 😞

**Closed** 2024-05-15 21:36 UTC
Labels: type: bug, scope: js
