### ISSUE TITLE
Can I Customise the way Nx generator works?

### ISSUE THREAD

**Issue by EfstathiadisD** [nrwl/nx#2252] opened 2020-01-01 17:15 UTC
I am curious, if Nx, supports(Pretty sure it does not), or if it plans to support some customisation regarding the Generator. For example, in the following commands:

**Regarding Workspace:**
```
// This is the command that creates a new Nx Workspace
➜ yarn create nx-workspace "<NAME_OF_THE_WORKSPACE>"

// I would like to be able to configure how to generate the files and support Symbols. Example:
➜ yarn create nx-workspace --libsOutput="@Libraries" --appsOutput="@Applications" "<NAME_OF_THE_WORKSPACE>"
```
With the above example, I would like to be able to customise how my Generated Files are gonna be named. This structure `@SomeProject`, is very important to me.

**Regarding App and Lib Generation:**
```
// This is the command that creates a new React Application in the apps directory
➜ nx generate @nrwl/react:"<NAME_OF_THE_FOLDER>" "<NAME_OF_THE_APP>"

// I would like to be able to create a Project(App or Lib) within one Folder. Example:
➜ nx generate @nrwl/react:@Applications @MillionDollarProject --single
```
With the above example, I would like to be able to insert E2E Tests in the same master folder as the Main Projects.

In both those above examples, I also mean to never change the naming to match your standards. And also the Capitalisation. Example:

```
// I wanted to Generate this NestJS Project. Exactly that naming Scheme
➜ nx generate @nrwl/nest:app @IncapableBE

// This is what I got back:
➜ ls
@incapable-be     @incapable-ui     @incapable-ui-e2e
```

> This Casing and Transformation unfortunately is unacceptable. This is my 2 Biggest Problems with Nx.

Do you think something like that is possible? I wouldn't mind working on it if it isn't something that would require me to deeply understand how Nx Works under the hood. Anyway. Thanks for your time. **Happy New Year.**

**Comment by FrozenPandaz** [comment] 2020-01-03 15:22
No, this functionality does not exist currently but it could be added.

You should be able to move the files after they are generated and it should work after reconfiguring everything.

Is someone in the community interested in adding this feature to the code generation?

**Comment by FrozenPandaz** [comment] 2020-01-03 21:06
I found an existing issue so I am closing this issue as a duplicate of: https://github.com/nrwl/nx/issues/2182

**Closed by FrozenPandaz** 2020-01-03 21:06 UTC
Labels: community, scope: misc, type: feature

**Comment by EfstathiadisD** [comment] 2020-01-03 21:09
Cool. I see that now both Issues are closed. I would keep one as open. I am gonna work on this on my free time.. Will submit a PR once ready.. Thanks!!
