### ISSUE TITLE
Linting related issue in Nx10

### ISSUE THREAD

**Issue by sameerinfodb** [nrwl/nx#3575] opened 2020-08-20 20:09 UTC
## Current Behavior
ng lint performs linting of all the project, but nx lint or npm run lint does not perform linting of all the project in the workspace in Nx10

## Expected Behavior
Should perform linting of all the projects in the workspace. Just like ng lint

## Steps to Reproducehould 
Here is the link to source code  [Link](https://github.com/sameerinfodb/seed-work-space)
1. Download load the source code. 
2. execute npm install
3. execute npm run lint

**Comment by ahnpnl** [comment] 2020-08-24 08:41
I have the same issue, this issue started from nx 9, nx 8 doesn't have this issue.

**Comment by webberwang** [comment] 2020-08-26 10:20
Yeah this needs to be fixed

**Comment by ahnpnl** [comment] 2020-08-27 13:21
the workaround is following the workaround written in `decorate-angular-cli.js`

**Comment by sameerinfodb** [comment] 2020-08-27 13:38
> the workaround is following the workaround written in `decorate-angular-cli.js`

@ahnpnl  sorry i did not understand this statement. please explain.

**Comment by ahnpnl** [comment] 2020-08-27 13:58
When migrating to nx 9, nx added a `decorate-angular-cli.js` file, this file contains some comments which describes the way how to opt-out it. If you follow the instruction in that file, it will solve the issue.

**Comment by sameerinfodb** [comment] 2020-08-27 15:12
> When migrating to nx 9, nx added a `decorate-angular-cli.js` file, this file contains some comments which describe the way how to opt-out it. If you follow the instruction in that file, it will solve the issue.

will that disable the computation cache feature because now command will be executed with ng instead of nx right.

**Comment by ahnpnl** [comment] 2020-08-27 15:56
I think so, the whole lint issue is caused by that file. My colleagues also told me that `ng` commands are kind of broken because of that script.

**Comment by sameerinfodb** [comment] 2020-08-27 17:04
@vsavkin do we have a command to initiate the computational Cache explicitly.So that after opt-out the decorate-angular-cli.js script,we can use the computational cache.

**Comment by HonoluluHenk** [comment] 2021-03-10 10:45
bump because I can still reproduce this behavior

**Comment by rafaelgfx** [comment] 2021-04-09 13:37
Bump

**Comment by Maximaximum** [comment] 2021-07-30 14:28
After a year, this still hasn't been fixed? 😕

**Comment by vpishuk** [comment] 2021-08-14 02:22
Bump...

**Comment by joelkesler** [comment] 2021-11-08 22:59
This solution was mentioned in https://github.com/nrwl/nx/issues/3724 and it may be helpful:

> You can run the lint on all the projects via this command: `nx run-many --all --target=lint`
https://github.com/nrwl/nx/issues/3724#issuecomment-691902988

**Comment by AgentEnder** [comment] 2021-11-09 18:21
I'm going to go ahead and close this  out. This behavior is working as intended at this point, as we target execution is a general problem and we don't special case them. This works similarly to `nx build`, or `nx serve`, or `nx {anything}` in that it will hit your default project as determined by `nx.json` or the cwd of your terminal. 

For linting the whole workspace, there is always the run-many option, but its more likely that you want to use `nx affected:lint` to only hit what actually needs to be linted (its also a shorter command 😄)

**Closed by AgentEnder** 2021-11-09 18:21 UTC
Labels: type: bug, scope: misc

**Comment by zaslavskyv** [comment] 2022-03-24 09:40
> This works similarly to `nx build`, or `nx serve`, or `nx {anything}`

`nx format` formats everything.

**Comment by drmikecrowe** [comment] 2022-04-23 10:03
@AgentEnder -- please reopen this.  As @zaslavskyv  said, `nx lint` is functionally different.  I agree we have a workaround, but as a new `nx` user, I just got bit by this inconsistency
