### ISSUE TITLE
NX not passing flag to the first job in affected run

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#7514] opened 2021-10-25 18:35 UTC
## Current Behavior
When running:

```
nx affected --target publish --parallel --base <hash> --with-deps --pkgVersion 1.3.0
```

The first job that gets run doesn't receive flag.

```
  - nx-core
  - nx-jest-playwright
  - nx-serverless
  - nx-npm
  
  With flags:
    --pkgVersion=1.3.0

...

nx run nx-core:publish 

...

nx run nx-jest-playwright:publish --pkgVersion=1.3.0 
...
```

Consecutive jobs get it, but the first one is missing one.

## Expected Behavior

All jobs should get flag.

## Steps to Reproduce

You can see the run here: https://github.com/Bielik20/nx-plugins/runs/3997050209?check_suite_focus=true

### Environment

```
  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.10

  nx : 13.0.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.0.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 13.0.2
  @nrwl/nx-cloud : 12.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : Not Found
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment] 2021-11-12 16:16
Thanks for reporting this!

I was able to reproduce it locally and it seems there's an issue with the usage of `--with-deps`. Please note that the flag is deprecated and it'll be removed in the next major version. If you configure your target dependencies instead, it should work correctly. You can edit your `nx.json` to look like:

```json
"targetDependencies": {
  "build": [
    {
      "target": "build",
      "projects": "dependencies"
    }
  ],
  "publish": [
    {
      "target": "publish",
      "projects": "dependencies"
    }
  ],
},
```

In the meantime, I'll have a look at the issue with the `--with-deps` flag, even though is deprecated, it should work correctly until removed.

**Comment by Bielik20** [comment] 2021-11-15 08:28
Great, thank you for handling that 🙇 

To be honest you scared me now. I was expecting `withDeps` to remain for foreseeable future. I was very excited at first when I saw `targetDependencies`, but soon found out they are not working as one might expect yet. When you have my kind of exemple:
```
nx-core <-- nx-serverless
```

If I run `nx run nx-serverless:publish --pkgVersion=1.3.0 --with-deps` - It will run both `nx-serverless` and `nx-core` with `--pkgVersion=1.3.0`. That is the desired behaviour ✅ 

But with configured `targetDependencies` I run `nx run nx-serverless:publish --pkgVersion=1.3.0` - then it will run `nx-serverless` with `--pkgVersion=1.3.0` flag, but `nx-core` with no flags ❌ 

I know this is not a place to report that, but I was really under the impression that `targetDependencies` are still very much experimental.

**Comment by Bielik20** [comment] 2021-11-20 08:15
@leosvelperez Hello, since the fix has been reverted in latest release, what is current status of this issue?
https://github.com/nrwl/nx/pull/7815

**Comment by leosvelperez** [comment] 2021-11-22 10:38
@Bielik20 I just noticed this is a duplicate of an existing issue #7136. As such, I'll keep this closed and you can follow that one for updates. A PR was previously created to forward flags to dependencies with the same target name, but I saw it was [closed to further discuss more about it](https://github.com/nrwl/nx/pull/7055#issuecomment-926987910).

**Comment by Bielik20** [comment] 2021-11-22 14:20
@leosvelperez Yeah, I agree that [this comment](https://github.com/nrwl/nx/issues/7514#issuecomment-968647412) is better tracked in https://github.com/nrwl/nx/issues/7136 I even commented there as well.

What I was referring in [here](https://github.com/nrwl/nx/issues/7514#issuecomment-974614312) is that [latest release](https://github.com/nrwl/nx/releases/tag/13.2.1) reverted this fix: https://github.com/nrwl/nx/pull/7830

**Comment by Bielik20** [comment] 2021-12-03 17:07
@leosvelperez This issue still persists, I have just tried with the newest version. THIS issue should be reopened and addressed. I still do not understand rationale for reverting your fix. Can you PLEASE give me some feedback on that?

**Comment by leosvelperez** [comment] 2021-12-06 10:53
hey @Bielik20! Sorry if there was any confusion, but as I mentioned in [this comment](https://github.com/nrwl/nx/issues/7514#issuecomment-975385598), this issue remains closed because it's a duplicate of #7136. Please follow that one for updates.

My previous fix was wrong and it introduced a bug, that's why it was reverted, you can see the explanation of the introduced issue in the PR #7815 description.

As I mentioned [before](https://github.com/nrwl/nx/issues/7514#issuecomment-975385598), a PR was previously created to forward any received flags to the target dependencies with the same target name but it was [closed to further discuss it](https://github.com/nrwl/nx/pull/7055#issuecomment-933615685). You can have a look at the conversation in that PR and follow the #7136 issue for updates regarding this.

**Comment by Bielik20** [comment] 2021-12-06 14:05
@leosvelperez Thank you for responding I appreciate that.

I have seen the other issue https://github.com/nrwl/nx/issues/7136 I think it is very important and calls for a larger debate. That being said, I do not agree it is a duplicate of THIS issue.

https://github.com/nrwl/nx/issues/7136 is about target dependencies and handling arguments in that NEW approach. Here we are discussing behaviour with `withDeps` flag which used to work fine and now it doesn't, which is a regression.

This is really critical regression for me, because I cannot update my [repository that holds Nx Plugins](https://github.com/Bielik20/nx-plugins) because it will break the release process.

**Comment by leosvelperez** [comment] 2021-12-06 15:20
@Bielik20 you're absolutely right. I'm sorry, I missed the issues and forgot the original issue was about `--with-deps`.

I'm re-opening this and we'll have a look.

**Closed** 2021-12-09 09:46 UTC
Labels: type: bug, scope: core
