### ISSUE TITLE
`nx migrate latest` fails on an Angular workspace: `Unable to fetch migrations for @ngrx/signals@18.0.0`

### ISSUE THREAD

**Issue by gergelyszerovay** [nrwl/nx#26985] opened 2024-07-18 15:58 UTC
### Current Behavior

I try to migrate an Angular workspace (Nx 19.1.0, Angular 18.0.1) to the latest Nx (19.5.1) using the `pnpm exec nx migrate latest` command, and I get the following error message:

```
Unable to fetch migrations for @ngrx/signals@18.0.0: Command failed: npm install @ngrx/signals@18.0.0
```

### Expected Behavior

It should update the packages and the workspace

### Steps to Reproduce

Angular workspace (Nx 19.1.0, Angular 18.0.1), run  using the `pnpm exec nx migrate latest`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : win32-x64
pnpm   : 9.4.0

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/cypress        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/storybook      : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.4.5
---------------------------------------
Community plugins:
@ngrx/component-store : 17.2.0
@ngrx/effects         : 17.2.0
@ngrx/entity          : 17.2.0
@ngrx/operators       : 17.2.0
@ngrx/signals         : 17.2.0
@ngrx/store           : 17.2.0
@ngrx/store-devtools  : 17.2.0
@rx-angular/template  : 17.0.1
@storybook/angular    : 7.6.2
ng-mocks              : 14.12.1
ngx-toastr            : 17.0.2
ngxtension            : 3.5.5
```

### Package Manager Version

pnpm 9.4.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

`@ngrx/signals@18.0.0` wasn't released yet: https://github.com/ngrx/platform/issues/4394

**Comment by netanelb-carbyne** [comment] 2024-07-25 16:33
@leosvelperez If you interested to know, @ngrx/signals has just released
https://github.com/ngrx/platform/issues/4394#issuecomment-2250893812

**Comment by leosvelperez** [comment] 2024-07-25 16:56
@netanelb-carbyne, thanks for the heads-up! That alone makes the issue go away, though it hides the actual underlying issue, which is a very infrequent one. This is the first time that it has appeared. We'll get to address it at some point, but it has a lower priority given how unlikely it is to happen.

@gergelyszerovay could you try updating again and confirm everything works for you now?

**Comment by aahunt-cisco** [comment] 2024-07-25 17:19
I am still getting this error when running `nx migrate latest`. Nx is expecting `18.0.1` but `18.0.0` is what was just released today for ngrx signals.

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/65ee57a7-ecdc-4ea9-a3dd-4ee394cf679b">

**Comment by leosvelperez** [comment] 2024-07-26 06:06
@aahunt-cisco thanks for confirming! Alright, so, I'll work on fixing it given it will continue to cause problems.

**Comment by leosvelperez** [comment] 2024-07-26 06:07
I'm closing this one as a duplicate of https://github.com/nrwl/nx/issues/26799. That one was open first and it's the same issue. Please follow it for updates.

**Closed by leosvelperez** 2024-07-26 06:07 UTC
Labels: type: bug, scope: angular, scope: core
