### ISSUE TITLE
@nrwl/angular :app and :lib schematics should support eslint

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#2950] opened 2020-05-03 04:43 UTC
## Expected Behavior

It would be great if we could create Angular apps and libs with eslint preconfigured.

## Current Behavior

Currently the option `--linter` is there, but it only allows selecting `tslint` which is deprecated.

## Other

I'm happy to give a shot at a PR that adds this, I just want to make sure if this is desired and if there are things I need to keep in mind while adding the functionality.

**Comment by brandonroberts** [comment] 2020-07-10 15:58
Closing as a duplicate of #1699. We'll track progress there

**Closed by brandonroberts** 2020-07-10 15:58 UTC
Labels: scope: angular, type: feature
