### ISSUE TITLE
findOriginalKeys is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by kjetilhp** [nrwl/nx#16875] opened 2023-05-09 07:29 UTC
### Current Behavior

Creating a nestjs application

### Expected Behavior

Create a lock file based on the generated package.json - or add config to not generate the lockfile and use only the generated package.json.

### Steps to Reproduce

1. create an nestjs app
2. add tools/libs to make it work with cloudrun 

```
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

import { http } from '@google-cloud/functions-framework';

import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';

import { AppModule } from './app/app.module';

import express from 'express';
import { ExpressAdapter } from '@nestjs/platform-express';
const NestServer: express.Express = express();

const environment = {
  dev: !!process.env.DEV,
};

export const createNestServer = async (expressInstance) => {
  const app = await NestFactory.create(
    AppModule,
    new ExpressAdapter(expressInstance)
  );
  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);
  app.enableCors();
  return app.init();
};

createNestServer(NestServer)
  .then((v) => {
    console.log('Environment', environment);
    if (!environment.dev) {
      Logger.log('🚀 Starting production server...');
    } else {
      Logger.log(
        `🚀 Starting development server on http://localhost:${
          process.env.PORT || 3333
        }`
      );
      v.listen(process.env.PORT || 3333);
    }
  })
  .catch((err) => Logger.error('Nest broken', err));

http('api-devent', NestServer);
```

3. build project

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.15.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx (global)        : 16.0.0
   nx                 : 16.1.3
   @nx/js             : 16.1.3
   @nx/jest           : 16.1.3
   @nx/linter         : 16.1.3
   @nx/workspace      : 16.1.3
   @nx/angular        : 16.1.3
   @nx/cypress        : 16.1.3
   @nx/devkit         : 16.1.3
   @nrwl/devkit       : 15.7.0
   @nx/esbuild        : 16.1.3
   @nx/eslint-plugin  : 16.1.3
   @nx/nest           : 16.1.3
   @nx/node           : 16.1.3
   @nx/plugin         : 16.1.3
   @nx/storybook      : 16.1.3
   @nrwl/tao          : 16.1.3
   @nx/web            : 16.1.3
   @nx/webpack        : 16.1.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-extend/gcp-cloud-run : 3.4.5
   @nxext/svelte            : 15.7.0
   @nxtensions/astro        : 3.5.0
   @taiga-ui/cdk            : 3.26.0
   @taiga-ui/core           : 3.26.0
   ngfire                   : 0.0.52
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.7.0
   
   To fix this, run `nx migrate nx@16.1.3`
```

### Failure Logs

```shell
❯ nx build de-api

> nx run de-api:build:production  [existing outputs match the cache, left as is]


 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable


   TypeError: findOriginalKeys is not a function or its return value is not iterable
    at /Users/kjetil/devent/dev/de-mono/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:190:41
    at Array.forEach (<anonymous>)
    at mapSnapshots (/Users/kjetil/devent/dev/de-mono/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:189:26)
    at stringifyYarnLockfile (/Users/kjetil/devent/dev/de-mono/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:131:23)
    at createLockFile (/Users/kjetil/devent/dev/de-mono/node_modules/nx/src/plugins/js/lock-file/lock-file.js:132:60)
    at /Users/kjetil/devent/dev/de-mono/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/Users/kjetil/devent/dev/de-mono/node_modules/@nx/webpack/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/Users/kjetil/devent/dev/de-mono/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/kjetil/devent/dev/de-mono/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/kjetil/devent/dev/de-mono/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)

chunk (runtime: main) main.js (main) 10.7 KiB [entry] [rendered]
webpack compiled successfully (8fb3382306f2ae6b)
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

generated package.json 
```

{
  "name": "api",
  "version": "0.0.1",
  "dependencies": {
    "@google-cloud/functions-framework": "3.2.0",
    "@nestjs/common": "9.4.0",
    "@nestjs/core": "9.4.0",
    "@nestjs/platform-express": "9.4.0",
    "express": "4.18.2",
    "firebase-admin": "11.8.0",
    "firebase-functions": "4.4.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "7.8.1",
    "tslib": "2.5.0"
  },
  "main": "main.js"
}
```

**Comment by leosvelperez** [comment] 2023-05-09 08:38
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/16825. I'm closing this in favor of that one. Could you please add your reproduction info to that issue in a comment so it can help with the troubleshooting?

**Closed by leosvelperez** 2023-05-09 08:38 UTC
Labels: type: bug

**Comment by meeroslav** [comment] 2023-05-09 10:42
@kjetilhp please follow up the warning from your `nx report` to ensure all `nx` packages are in sync and try again.

**Comment by kjetilhp** [comment] 2023-05-09 11:33
> @kjetilhp please follow up the warning from your `nx report` to ensure all `nx` packages are in sync and try again.

same result, as mentioned, works fine before adding mentioned libraries

```

❯ nx report                           

 >  NX   Report complete - copy this into the issue template

   Node   : 18.13.0
   OS     : darwin arm64
   yarn   : 3.5.1
   Hasher : Native
   
   nx (global)        : 16.1.3
   nx                 : 16.1.3
   @nx/js             : 16.1.3
   @nx/jest           : 16.1.3
   @nx/linter         : 16.1.3
   @nx/workspace      : 16.1.3
   @nx/angular        : 16.1.3
   @nx/cypress        : 16.1.3
   @nx/devkit         : 16.1.3
   @nx/esbuild        : 16.1.3
   @nx/eslint-plugin  : 16.1.3
   @nx/nest           : 16.1.3
   @nx/node           : 16.1.3
   @nx/plugin         : 16.1.3
   @nx/storybook      : 16.1.3
   @nrwl/tao          : 16.1.3
   @nx/web            : 16.1.3
   @nx/webpack        : 16.1.3
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nxtensions/astro : 3.5.0
   @taiga-ui/cdk     : 3.26.0
   @taiga-ui/core    : 3.26.0
   ngfire            : 0.0.52

❯ nx build de-ng-api                       

> nx run de-ng-api:build:production


 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable


   TypeError: findOriginalKeys is not a function or its return value is not iterable
   ....

chunk (runtime: main) main.js (main) 11 KiB [entry] [rendered]
webpack compiled successfully (61b3e4e8dff48a74)

 >  NX   Successfully ran target build for project de-ng-api (3s)
```
