### ISSUE TITLE
Affected script fails on nested Git Repository

### ISSUE THREAD

**Issue by domkrel** [nrwl/nx#613] opened 2018-07-03 06:07 UTC
**Problem:**
Affected script does not calculate the affected projects correctly
```
npm run affected:* -- --base=origin/master --head=HEAD
e.g. npm run affected:dep-graph -- --base=origin/master --head=HEAD
```

**Situation:**
Mono Repository that contains more than only an angular project  
> monorepo
  └── backend
  └── angular-project
  └── more stuff

**Problem located:**
directlyTouchedProjects and implicitlyTouchedProjects (@nrwl/schematics/src/command-line/affected-apps.js) do a comparison of the filename and the root of the project.

- The root of a project can be something like this:  apps/my-app
- The expected file path is: apps/my-app/src/my-component.ts

The path of the touched files gets calculated by getFilesUsingBaseAndHead (shared.js) which gets a path with the root of the git repository.

- The expected file path is: apps/my-app/src/my-component.ts
- The given file path is: **angular-project**/apps/my-app/sry/my-componen.ts
- The comparison does not work on a file that starts with anything else than the project root

**Not working solution:**
I changed the root of the project to: angular-project/apps/my-app
This  led to a not correct calculation of the dep-graph because the file array of the projects was empty.

**Comment by FrozenPandaz** [comment] 2018-07-06 16:11
Hi, this seems like an interesting problem.

Is it possible to provide a minimal reproduction of this issue?

**Comment by exequiel09** [comment] 2018-07-15 12:33
Same problem here as well. The same scenario and almost identical structure provided in the situation section of the issue.

**Comment by exequiel09** [comment] 2018-07-15 12:43
I used the patch provided in the associated PR #621  and it's correctly working.

**Comment by domkrel** [comment] 2018-07-20 05:13
Still a repo for reproduction needed?

**Comment by exequiel09** [comment] 2018-07-26 03:37
I've switched my `affected:*` scripts to `affected:* --all` until this issue is resolved and the PR #621 is reviewed and merged since it's broken when the workspace root is not on the root of the repo.

**Comment by tfiwm** [comment] 2018-07-26 04:47
It takes to much time for us to use all ;) we just do a copy & Paste after npm install to patch the file till it gets merged

**Comment by exequiel09** [comment] 2018-09-01 20:15
@FrozenPandaz this issue can be closed now since the fix is already merged 👍

**Comment by bcabanes** [comment] 2018-09-24 15:53
Closing the issue, fix merged.

**Closed by bcabanes** 2018-09-24 15:53 UTC
Labels: blocked: repro needed, type: bug
