### ISSUE TITLE
 Calling @nrwl/react application schematic from another schematic with dry run results in error

### ISSUE THREAD

**Issue by devinshoemaker** [nrwl/nx#2456] opened 2020-02-08 17:46 UTC
## Expected Behavior

I expect that I can call the `@nrwl/react` schematic from another in order to extend it. 

## Current Behavior

I created an Nx plugin with the `create-nx-plugin` tool, and in one of my schematics, I imported the `application` schematic from `@nrwl/react`. I used the same schema so that I could just forward the options to the `@nrwl/react`, and then I can make my own modifications from there. This actually works well, except for when it's executed with `--dry-run`. When executed with this flag, I get an error saying `Expected apps/my-app/tsconfig.json to exist. Please create one.` I am able to dry run `@nrwl/react` with the exact same command and there is no error, so I believe it has to do importing the schematic. 

## Failure Information (for bugs)

Command: `nx g @nxtend/ionic-react:app myApp --style=css --routing=false --dry-run`
Output: `Expected apps/my-app/tsconfig.json to exist. Please create one.`

### Steps to Reproduce

1. Check out this repo and branch: https://github.com/devinshoemaker/nxtend/tree/nx-repro
2. `cd nxtend && yarn install`
2. `nx build ionic-react`
3. `cd dist/libs/ionic-react && yarn link && cd ../../../`
4. `yarn link @nxtend/ionic-react`
5.  `nx g @nxtend/ionic-react:app myApp --style=css --routing=false --dry-run`

### Context

- Created with `create-nx-plugin`
- Nx v8.12.2

### Failure Logs

`Expected apps/my-app/tsconfig.json to exist. Please create one.`

## Other

This is an interesting issue because it actually works without a dry run, so functionally speaking it's okay, however, a working dry run would be useful.

## EDIT

I wanted to provide a quick update. It seems that I misunderstood the situation, and so I will be updating this issue when I get some more time to reflect that. At first, I thought the issue was centered around doing a dry run on an imported schematic, but it turns out it's actually related to a coincidental file path issue. It seems that when the `@nrwl/react:application` schematic creates the application files using the file path of `.files/app`, it ends up looking for that folder within my schematic folder instead. I was able to get past this issue for both dry runs and not by copying the `files/` directory from `@nrwl/react:application`. I will try and work with this as it's not the worst workaround, however, it is less maintainable than I would like it to be. I'm not sure if using the Nrwl schematics in this manner is officially supported, but it seems like it could be a very useful feature for custom Nx plugins.

**Comment by jaysoo** [comment] 2020-02-13 19:03
Hi @devinshoemaker Definitely interested in what the problem is that is preventing `@nrwl/react:app` schematic from being extended from. It is a use-case that should be supported, either as a third-party plugin or workspace schematic.

**Comment by devinshoemaker** [comment] 2020-02-13 19:43
It must be a filepath scoping issue. When the `@nrwl/react` application schematic adds the project files with the path `./files/app` it ends up looking in the folder where my schematic is (the one calling the Nrwl React schematic).

**Comment by devinshoemaker** [comment] 2020-02-13 20:00
Here is another branch with the example. If you delete `libs/ionic-react/src/app/files/` then the build will start failing due to not being able to find `tsconfig.json` (because it wasn't ever copied since the `@nrwl/react` application schematic couldn't find the files).

**Comment by devinshoemaker** [comment] 2020-02-13 21:38
Sorry for the volume of replies. I figured out that using the `externalSchematic` function in the Angular schematics library actually solves my issue, so I'm going to put this one on user error, unless I'm misunderstanding something.

**Comment by jaysoo** [comment] 2020-06-24 00:40
Okay awesome, sounds like this was figured out a while back. Closing this one.

**Closed by jaysoo** 2020-06-24 00:40 UTC
Labels: blocked: more info needed, scope: react
