### ISSUE TITLE
create-nx-workspace@16.5.5 fails to create a workspace with angular app

### ISSUE THREAD

**Issue by dackyD** [nrwl/nx#18299] opened 2023-07-25 12:03 UTC
### Current Behavior

The cli stops in creating workspace and has the following error:
```
Error: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

By inspection the cli generates a workspace without an angular application.

### Expected Behavior

The cli should generate the a monorepo workspace with an angular app without an error.

### Steps to Reproduce

1. Run npx create-nx-workspace@latest

```
$ npx create-nx-workspace@latest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · angular-mono-16
✔ Which stack do you want to use? · angular
✔ Standalone project or integrated monorepo? · integrated
✔ Application name · web
✔ Default stylesheet format · scss
✔ Would you like to use Standalone Components in your application? · Yes
✔ Would you like to add routing? · Yes
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.5.5 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✖ Creating your workspace in angular-mono-16

 >  NX   Failed to create a workspace.

   Error: npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.20.0
   OS     : darwin-x64
   npm    : 8.19.4

   nx             : 16.5.5
   @nx/js         : 16.5.5
   @nx/jest       : 16.5.5
   @nx/linter     : 16.5.5
   @nx/workspace  : 16.5.5
   @nx/angular    : 16.5.5
   @nx/cypress    : 16.5.5
   @nx/devkit     : 16.5.5
   @nrwl/tao      : 16.5.5
   @nx/webpack    : 16.5.5
   typescript     : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-07-28 15:20
Thanks for reporting this!

The actual error is being swallowed and therefore, you're not getting the feedback you should get. This is failing because of the workspace name.

When creating a workspace, the provided workspace name is used as the `npmScope` (https://nx.dev/reference/nx-json#npm-scope). In the specific case of Angular, there's the concept of the prefix used in the HTML selectors for components. This prefix must be a valid HTML selector:

> Valid selector prefixes must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.

When generating an application, the `npmScope` is used as the prefix unless a `prefix` option is provided. The problem is that when generating a workspace, there's no option to provide a `prefix` and therefore, it always uses the provided workspace name as the `npmScope` and `prefix`.

So, the issue is you're using `angular-mono-16`, which is not a valid HTML selector (as per the description above) and therefore, the `create-nx-workspace` fails when creating the initial app.

An error is correctly thrown to mention this, but somewhere in the process is being swallowed. I'll push a fix to make sure the error is correctly surfaced.

**Comment by dackyD** [comment] 2023-07-31 13:46
Thanks for the thorough explanation @leosvelperez.

**Comment by mandarini** [comment] 2023-10-24 12:50
@leosvelperez I think we can close this issue now, right? It seems resolved on my end?

**Closed** 2023-10-24 13:13 UTC
Labels: type: bug, scope: angular
