### ISSUE TITLE
Generating angular material schematic failed

### ISSUE THREAD

**Issue by RyanAntenor** [nrwl/nx#17009] opened 2023-05-14 13:55 UTC
### Current Behavior

I'm not able to generate the ng-material schematics in my shared-ui by running this command
`npx nx generate @angular/material:navigation main-nav --project=shared-ui `

and run into problem with the following error:
```
Error: Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
    at findModule (C:\Users\...:76:11)
    at findModuleFromOptions (C:\Users\...)
    at findModuleFromOptions (C:\Users\...)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\..
    at async callRuleAsync (C:\Users\....)
```

My current structure is:
Workspace:
```
├───apps
├───shared-ui
│   └───src
│       └───lib
│           └───shared-ui-.module
```

### Expected Behavior

I would assume this will generate the angular material schematics in the libs folder in the shared-ui module
which similar to 
`ng generate @angular/material:navigation main-nav -m shared-ui`

### Steps to Reproduce

1. `npx create-nx-workspace@latest`
2.  create an Angular app
3. ` yarn add @angular/material`
4.  create shared library:  `nx g @nx/angular:library shared-ui`
5. `nx g @angular/material:ng-add --project=shared-ui`
6. `nx generate @angular/material:navigation main-nav --project=shared-ui`

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.4
   Hasher : Native

   nx (global)        : 16.1.4
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/web            : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

### Failure Logs

```shell
Error: Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
    at findModule (C:\Users\...:76:11)
    at findModuleFromOptions (C:\Users\...)
    at findModuleFromOptions (C:\Users\...)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\..
    at async callRuleAsync (C:\Users\....)
```

### Operating System

- [X] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-05-15 09:31
Thanks for reporting this!

The `@angular/material:navigation` doesn't support libraries. If you follow similar steps in an Angular CLI workspace, it won't work either. You'll see a different error, but the underlying issue is the same: libraries don't seem to be supported. Whether that's a bug or intentional, I don't know.

I'm closing this since it's an issue with the Angular Material schematic and not caused by Nx. You can report this in the Angular Material repo with Angular CLI workspace reproduction if you think it should work or be supported.

**Closed by leosvelperez** 2023-05-15 09:31 UTC
Labels: type: bug, scope: angular
