### ISSUE TITLE
Crashes when doing an nx serve <app> after creating a fresh Angular + Nest project

### ISSUE THREAD

**Issue by AshMcConnell** [nrwl/nx#5683] opened 2021-05-16 20:10 UTC
## Current Behavior
Crashes when doing an nx serve <app> after creating a fresh Angular + Nest project.  It does work correctly with an angular only project.

## Expected Behavior
Should compile and serve correctly

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/497941/118411067-bbf3ef00-b68a-11eb-9bf8-5e9ccd4ffbe6.png)

### Failure Logs
`> nx run race-timing:serve:development
⠋ Generating browser application bundles...(node:19264) UnhandledPromiseRejectionWarning: TypeError: webpack_1.node.NodeTargetPlugin is not a constructor
    at WebpackResourceLoader._compile (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\resource_loader.js:83:13)
    at WebpackResourceLoader.get (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\resource_loader.js:210:44)
    at Object.resourceHost.readResource (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\ivy\host.js:30:35)
    at AdapterResourceLoader.preload (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\resource\src\loader.js:88:39)
    at resolveStyleUrl (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:192:49)
    at C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:83
    at Array.map (<anonymous>)
    at ComponentDecoratorHandler.preanalyze (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:50)
    at _loop_1 (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:53)
    at TraitCompiler.analyzeClass (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:343:35)
    at visit (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:113:27)
    at visitNodes (C:\dev\angular\slowtoast\node_modules\typescript\lib\typescript.js:28217:30)
    at Object.forEachChild (C:\dev\angular\slowtoast\node_modules\typescript\lib\typescript.js:28456:24)
    at visit (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:115:20)
    at TraitCompiler.analyze (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:117:13)
    at TraitCompiler.analyzeAsync (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:79:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |     Size
runtime.js          | runtime       | 99 bytes

                    | Initial Total | 99 bytes

Build at: 2021-05-16T20:08:33.159Z - Hash: 44c7eb1857464e1007ac - Time: 5711ms

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

⠋ Generating browser application bundles...(node:19264) UnhandledPromiseRejectionWarning: TypeError: webpack_1.node.NodeTargetPlugin is not a constructor
    at WebpackResourceLoader._compile (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\resource_loader.js:83:13)
    at WebpackResourceLoader.get (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\resource_loader.js:210:44)
    at Object.resourceHost.readResource (C:\dev\angular\slowtoast\node_modules\@ngtools\webpack\src\ivy\host.js:30:35)
    at AdapterResourceLoader.preload (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\resource\src\loader.js:88:39)
    at resolveStyleUrl (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:192:49)
    at C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:83
    at Array.map (<anonymous>)
    at ComponentDecoratorHandler.preanalyze (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:50)
    at _loop_1 (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:53)
    at TraitCompiler.analyzeClass (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:343:35)
    at visit (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:113:27)
    at visitNodes (C:\dev\angular\slowtoast\node_modules\typescript\lib\typescript.js:28217:30)
    at Object.forEachChild (C:\dev\angular\slowtoast\node_modules\typescript\lib\typescript.js:28456:24)
    at TraitCompiler.analyze (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:117:13)
    at TraitCompiler.analyzeAsync (C:\dev\angular\slowtoast\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:79:25)
(node:19264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
✔ Browser application bundle generation complete.

1 unchanged chunks

Build at: 2021-05-16T20:08:34.306Z - Hash: 44c7eb1857464e1007ac - Time: 819ms

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function

Error: webpack_1.util.cleverMerge is not a function`

### Environment

  Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 12.3.3
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : 12.3.3
  @nrwl/next : Not Found
  @nrwl/node : 12.3.3
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by uspasojevic96** [comment] 2021-05-16 21:33
This one is same as #5682

**Comment by leosvelperez** [comment] 2021-05-18 11:20
Thanks for reporting this!

As mentioned above, this is a duplicate of #5682. Please follow the progress on that issue and in [this comment](https://github.com/nrwl/nx/issues/5682#issuecomment-842320300) you'll find a workaround.

Closing this.

**Closed by leosvelperez** 2021-05-18 11:20 UTC
Labels: scope: angular, type: bug
