### ISSUE TITLE
ng generate app is throwing error

### ISSUE THREAD

**Issue by praveenkumar-r** [nrwl/nx#260] opened 2018-02-07 07:06 UTC
Installed nrwl version 0.7.0-beta.1
              cli version 1.6.5

Getting Following error

C:\Users\rajenpk\Documents\Angular5>ng generate app eRoutes --routing
Schematic "app" not found in collection "@schematics/angular".
Error: Schematic "app" not found in collection "@schematics/angular".
    at BaseException (C:\Users\rajenpk\AppData\Roaming\npm\node_modules\@angular
\cli\node_modules\@angular-devkit\core\src\exception\exception.js:12:9)
    at UnknownSchematicException (C:\Users\rajenpk\AppData\Roaming\npm\node_modu
les\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:29
:9)
    at NodeModulesEngineHost.createSchematicDescription (C:\Users\rajenpk\AppDat
a\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\
tools\file-system-engine-host-base.js:137:19)
    at SchematicEngine.createSchematic (C:\Users\rajenpk\AppData\Roaming\npm\nod
e_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine
.js:108:40)
    at CollectionImpl.createSchematic (C:\Users\rajenpk\AppData\Roaming\npm\node
_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\collect
ion.js:11:29)
    at Object.getSchematic (C:\Users\rajenpk\AppData\Roaming\npm\node_modules\@a
ngular\cli\utilities\schematics.js:45:23)
    at Class.run (C:\Users\rajenpk\AppData\Roaming\npm\node_modules\@angular\cli
\tasks\schematic-get-options.js:12:40)
    at Class.beforeRun (C:\Users\rajenpk\AppData\Roaming\npm\node_modules\@angul
ar\cli\commands\generate.js:90:31)
    at Promise.resolve.then (C:\Users\rajenpk\AppData\Roaming\npm\node_modules\@
angular\cli\ember-cli\lib\cli\cli.js:138:24)

**Comment by jdk339** [comment] 2018-03-01 14:24
I am also getting this error. Would be great if this would get some attention

**Comment by vsavkin** [comment] 2018-04-25 12:49
Could you please retry using Nx 1.0.2?

**Comment by vsavkin** [comment] 2018-05-29 14:21
Closing this issue. If the issue is still present in Nx 1.0.3 or Nx 6, please reopen it with a repro.

**Closed by vsavkin** 2018-05-29 14:21 UTC
Labels: needs: retry with latest, type: bug

**Comment by hknozturk** [comment] 2018-07-27 07:59
I got the same error in Nx 6. We just upgrade from Angular 5 to 6 and when I tried to add new app to workspace with 'ng generate app' command I got 

Schematic "app" not found in collection "@schematics/angular".
Error: Schematic "app" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (/home/hawken/Desktop/c3po/frontends/node_modules/@angular-devkit/schematics/src/engine/engine.js:155:23)
    at CollectionImpl.createSchematic (/home/hawken/Desktop/c3po/frontends/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at GenerateCommand.getOptions (/home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/models/schematic-command.js:194:40)
    at GenerateCommand.<anonymous> (/home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/commands/generate.js:38:53)
    at Generator.next (<anonymous>)
    at /home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/commands/generate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/commands/generate.js:3:12)
    at GenerateCommand.initialize (/home/hawken/Desktop/c3po/frontends/node_modules/@angular/cli/commands/generate.js:30:16)


ng --version

Angular CLI: 6.0.8
Node: 9.4.0
OS: linux x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.0.28
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.1
@angular/cli                      6.0.8
@angular/material                 6.4.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
