### ISSUE TITLE
Cannot find module '@my/proto' or its corresponding type declarations

### ISSUE THREAD

**Issue by redplane** [nrwl/nx#16821] opened 2023-05-05 18:30 UTC
### Current Behavior

Hi,

I'm facing with a frustrating issue with `nx 16.1.0`.
I have a monorepo with the following structure:

workspace
- apps
  - api 
- libs
  - my-api
  - my-core
  - my-strapi
  - proto
      

This is what `tsconfig.base.json` looks like:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@my/proto": ["libs/proto/src/index.ts"],
      "@my/api": ["libs/my-api/src/index.ts"],
      "@my/app": ["apps/api/src/index.ts"],
      "@my/core": ["libs/my-core/src/index.ts"],
      "@my/strapi": ["libs/my-strapi/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

At the moment, I'm trying to build `my-api` and `my-strapi` project which has this import: `import {MessageService} from '@my/proto';`

However, an error returned:
```
Compiling TypeScript files for project "my-strapi"...
libs/my-strapi/src/my-strapi.model.ts:1:30 - error TS2307: Cannot find module '@my/proto' or its corresponding type declarations.

1 import {MessageService} from '@my/proto';
```

My webstorm IDE can still recognize the paths, but build failed :(
![image](https://user-images.githubusercontent.com/7974095/236538563-9472a4ff-02db-435c-917e-e73892739761.png)

      
I have created a [minimal re-production](https://github.com/redplane/frustrating-issue) on Github.

Please support, 

 

### Expected Behavior

The library project must be built successfully.

### GitHub Repo

https://github.com/redplane/frustrating-issue

### Steps to Reproduce

1. Clone the minimal re-production
2. Run `nx build my-strapi` or `nx build my-api`

### Nx Report

```shell
Node   : 16.14.0                                         
   OS     : win32 x64                                       
   npm    : 8.19.2                                          
   Hasher : Native                                          
                                                            
   nx                 : 16.1.0                              
   @nx/js             : 16.1.0                              
   @nx/jest           : 16.1.0                              
   @nx/linter         : 16.1.0                              
   @nx/workspace      : 16.1.0                              
   @nx/devkit         : 16.1.0                              
   @nx/eslint-plugin  : 16.1.0                              
   @nx/nest           : 16.1.0                              
   @nx/node           : 16.1.0                              
   @nrwl/tao          : 16.1.0                              
   @nx/webpack        : 16.1.0                              
   typescript         : 5.0.4
```

### Failure Logs

```shell
Compiling TypeScript files for project "my-strapi"...
libs/my-strapi/src/my-strapi.model.ts:1:30 - error TS2307: Cannot find module '@my/proto' or its corresponding type declarations.

1 import {MessageService} from '@my/proto';
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mjwebblue** [comment] 2023-08-02 21:54
I have the same issue. I reverted the nx version to 16.5.5 and now it works fine.

**Comment by jjdaosavanh** [comment] 2023-09-28 22:55
I think i had the same issue. I had to configure ts-node in tsconfig.base.json

```
 "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
```

**Comment by kopach** [comment] 2023-10-17 10:02
In my case, solved it like described here https://github.com/nrwl/nx/issues/15464#issuecomment-1766084219

**Comment by jderboven** [comment] 2023-12-14 20:35
Still not resolved for me with latest versions, any news ?

**Comment by dylannnn** [comment] 2023-12-18 10:23
Same issue on version 17.1.3

**Comment by e-kulikov** [comment] 2024-01-02 14:23
This is a huge workaround, but it seems it works for me.

`package.json` of my imported library I have:
```json
{
"main": "./index.cjs",
  "module": "./index.js",
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.js",
      "require": "./index.cjs"
    }
  }
}
```

The structure of the library looks like this:
![image](https://github.com/nrwl/nx/assets/3277076/359588b6-2ebc-4964-8342-bf560a268a8d)

File `index.d.ts` is a trick: it isn't included into typescript compiation (typescript creates a correct one instead), but helps Webstorm to detect types of the lib:
```
// index.d.ts
export * from './src';
```

**Comment by jln-dk** [comment] 2024-03-27 11:22
Facing the same issue on `nx@18.1.3`

**Comment by jaysoo** [comment] 2024-07-25 14:14
The issue is that the lib's `tsconfig.json` file is overriding `compilerOptions.paths` and `compilerOptions.baseUrl`. Both of these need to be removed.

I've pushed a fix here to the original repo here: https://github.com/jaysoo/issue-16821

New JS libs generated should have the correct tsconfig options so you can use that as a reference if you run into more issues.

**Closed by jaysoo** 2024-07-25 14:14 UTC
Labels: type: bug, scope: node
