### ISSUE TITLE
DepGraph - Based on import statements

### ISSUE THREAD

**Issue by aravindfz** [nrwl/nx#676] opened 2018-08-08 05:05 UTC
I'm trying to understand the depgraph, I have two modules, Dashboard & Dashboard Summary. 

Dashboard Summary will be using the states from the Dashboard Module, ideally my dep-graph should look as 
![image](https://user-images.githubusercontent.com/22231525/43817294-50a88092-9af6-11e8-911c-48a00bf8afe1.png)

Since I'm using the states in the Dashboard and I have the following import statement,

```
import { DashboardState } from '@workspace/dashboard';
constructor(private store:Store<DashboardState>){ }
```
My dep graph changes as below, 
![image](https://user-images.githubusercontent.com/22231525/43817348-93c67762-9af6-11e8-9382-3f6c991948ac.png)

Is this the dependency, I assume that if the particular Module is inserted into the imports of the another module, there exists a dependency. In this case I'm trying to use a model which is already created in another library.

Help me to understand this

**Comment by aravindfz** [comment] 2018-09-01 08:47
@vsavkin Can you please help me on this ?

**Comment by skydever** [comment] 2018-09-01 20:40
maybe this helps ... you are importing something from the Dashboard lib within the DashboardSummary lib, do you also import something from the DashboardSummary lib within the Dashboard lib? If so, the linter should say *circurlar dep. detected* at the corresponding import statements, is that not the case? do you have tslint activated and/or does the linter script pass? how and when did you generate the dep graphs (a feature could be to color circ. deps)? seems like you have a circ. dep. here, you should check other imports within the libs too pointing to each other ... also interesting maybe (concerning the linter), the typescript config has the default nx path mappings?

**Comment by skydever** [comment] 2018-09-02 20:40
... do you use `@workspace\dashboard` imports within the dashboard lib? I came/come across this some times, and the suggestion here is to use relative paths when you import within/from the same lib and use the path/absolute imports `@workspace\...` only when you reference other libs ... see [#252](https://github.com/nrwl/nx/issues/252#issuecomment-405714153), also mentioned here #16 ... I also came across some issues building apps using absolute paths within a lib pointing to itself, but can't find them at the moment ... maybe using the absolute paths within a lib is preventing the linter from bringing up the right error messages?

**Comment by bcabanes** [comment] 2019-09-30 16:51
No reproduction have been shared. Closing the ticket because it is too old. Please, do not hesitate to create a new issue if needed.

**Closed by bcabanes** 2019-09-30 16:51 UTC
Labels: blocked: repro needed
