### ISSUE TITLE
Proper configurations for dependent publishable libs (Angular) giving error is not under 'rootDir'

### ISSUE THREAD

**Issue by bizappzone** [nrwl/nx#17950] opened 2023-07-04 16:34 UTC
### Current Behavior

Simple setup with 3 angular  libs
Lib-A - publishable @myOrg/Lib-A
Lib-B - publishable @myOrg/Lib-B
Lib-C - publishable @myOrg/Lib-C 

Now Lib-C imports 

- @myOrg/Lib-A, 
- @myOrg/Lib-B
Now executing build @myOrg/Lib-C  get error  Lib-A, Lib-B error is not under 'rootDir'

both A and B are published. 

What configurations are missing?  paths for A &B are in tsconfig.base.json  

Why can this not resolve from packages/Lib-A or Packages/Lib-B??

### Expected Behavior

Lib-C should build from local lib (as if it were installed in package.json (node_modules).  Or resolve from dist/LibA?

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.15.0
   OS     : win32 x64
   npm    : 9.3.1
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/angular        : 16.2.2
   @nx/cypress        : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/storybook      : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/web            : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc    : 1.1.21
   @ngrx/component-store : 16.0.1
   @ngrx/effects         : 16.0.1
   @ngrx/entity          : 16.0.1
   @ngrx/router-store    : 16.0.1
   @ngrx/schematics      : 16.0.1
   @ngrx/store           : 16.0.1
   @ngrx/store-devtools  : 16.0.1
   @storybook/angular    : 7.0.20
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-07-14 15:31
Thanks for providing a reproduction!

The issue happens because of a misconfiguration. Your `nx.json` is extending from `nx/presets/npm.json`, which is a preset configuration not meant to be used in Angular workspaces. That preset disables the `@nx/js` static analysis performed by the project graph plugin, which is what scans your source to identify dependencies between projects. If you run `nx graph` on that provided repo, you'll see there are no dependencies between those two packages.

Additionally, the target dependency between `build` targets is not configured anywhere. Normally, you'd have:

```json
{
  ...
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    },
    ...
  }
  ...
}
```

When using the right preset to create the workspace (Angular presets in this case) and the generators provided by the `@nx/angular` plugin to create projects, this is all set up correctly for you. It looks like the wrong preset was used when creating the workspace and there has been either some manual manipulation of the config files or they were generated with third-party generators that don't configure the target dependencies correctly.

In summary, replacing the contents of your `nx.json` with the following, will address the isue:

```json
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e",
          "build-storybook"
        ]
      }
    }
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "generators": {
    "@nx/angular:application": {
      "style": "css",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "none"
    },
    "@nx/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nx/angular:component": {
      "style": "css"
    }
  },
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
    "test": {
      "inputs": ["default", "^production", "{workspaceRoot}/jest.preset.js"]
    },
    "e2e": {
      "inputs": ["default", "^production"]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore"
      ]
    }
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/.eslintrc.json"
    ],
    "sharedGlobals": []
  },
}
```

**Note:** There are some extra changes to make the file in sync with what the Nx generators would have generated.

**Comment by leosvelperez** [comment] 2023-07-14 15:32
I'm closing this since it's a misconfiguration of the workspace. You could read more about the `nx.json` in the docs https://nx.dev/reference/nx-json for further reference.

**Closed by leosvelperez** 2023-07-14 15:32 UTC
Labels: type: bug, blocked: repro needed, scope: angular

**Comment by leosvelperez** [comment] 2023-07-21 07:44
Right, if you do want to use a package-based repo, you need to either configure Nx for detecting deps automatically or add the dependencies to the `package.json` files of each package.

As I explained in my previous comment, the `nx/presets/npm.json` preset disables the source code static analysis. With that disabled, you need to explicitly configure the dependencies between those packages. The `npm` preset by default relies on you using the package manager workspace capabilities. While you do have a `workspace` property configured at the root `package.json`, the individual `package.json` files of each package don't have the local packages they depend on specified as dependencies. That's why your projects have no relationships with each other and therefore, when building a project, its dependencies are not built.

The easiest way is to set the following to your `nx.json` (you don't need to remove the preset):

```json
{
  ...
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": true
    }
  },
}
```

Note that you still need to add the configuration for the `build` target to depend on the dependencies' `build` target. Check my previous comment for that. You can also read more about configuring the task pipelines at https://nx.dev/concepts/task-pipeline-configuration#define-task-dependencies-(aka-task-pipelines).

Another way to do this without setting the configuration above is to add the dependencies between local packages in the `package.json` of each package. A package-based monorepo is based on the package manager monorepo capabilities. In your case, you're using npm workspaces. For more reference, you can check https://nx.dev/getting-started/tutorials/package-based-repo-tutorial#local-linking-of-packages.
