### ISSUE TITLE
Error on generated package.json with npm package at private registries

### ISSUE THREAD

**Issue by cit-guilhermenogueira** [nrwl/nx#14825] opened 2023-02-06 16:37 UTC
### Current Behavior

We have some npm packages hosted on private registries.

When building apps, package.json is generated with invalid formatting.

Example:

"@centralit-governanca-corporativa/wanderson": "npm:1.3.2::__archiveUrl=https%3A%2F%2Fnpm.pkg.github.com%2Fdownload%2F%40centralit-governanca-corporativa%2Fwanderson%2F1.3.2 %2Fe6ee6ef7b13c682ce3f386f1c9b37922153c8b9f"

### Expected Behavior

"@centralit-governanca-corporativa/wanderson": "^1.3.2"

### Steps to Reproduce

1. Create an APP with a dependency hosted by private registry:

project.json

{
  "name": "api",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/api/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/api",
        "main": "apps/api/src/main.ts",
        "tsConfig": "apps/api/tsconfig.json",
        "assets": [
          "apps/api/.env-example",
          "apps/api/{assets,files,pipelines}/**/*",
          "apps/api/src/templates/**/*.hbs"
        ],
        "updateBuildableProjectDepsInPackageJson": true,
        "buildableProjectDepsInPackageJsonType": "dependencies"
      }
    },
  "tags": []
}

2. Build APP

3. See generated package.json

"@centralit-governanca-corporativa/wanderson": "npm:1.3.2::__archiveUrl=https%3A%2F%2Fnpm.pkg.github.com%2Fdownload%2F%40centralit-governanca-corporativa%2Fwanderson%2F1.3.2 %2Fe6ee6ef7b13c682ce3f386f1c9b37922153c8b9f"

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin arm64
   yarn : 3.3.1
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : 15.3.3
   @nrwl/next : 15.3.3
   @nrwl/node : 15.3.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by meeroslav** [comment] 2023-02-08 10:24
This is a duplicate of https://github.com/nrwl/nx/issues/14721 and has been fixed in https://github.com/nrwl/nx/pull/13864

**Closed by meeroslav** 2023-02-08 10:24 UTC
Labels: type: bug, scope: js
