### ISSUE TITLE
@nrwl/angular -- webworker (Schematic) - Missing path in tsconfig.worker.json

### ISSUE THREAD

**Issue by un33k** [nrwl/nx#7388] opened 2021-10-15 19:12 UTC
## Current Behavior
When `@nrwl/angular` schematic is used to create a webworker, the `tsconfig.worker.json` file misses the path where the file is created, `if` the file is not created in the `src` directory of the targeting app.

## Expected Behavior
If the path is not defined, the web worker file is created in the `targeted` application project. 
If the path is defined, the web worker file is created, let's say in a `libs/<name>/src/lib/web.worker.ts`, however  the `tsconfig.worker.json` file is still referencing the application directory ONLY.

## Steps to Reproduce
- run `nx generate @nrwl/angular:web-worker --name=<workerName> --project=<appName> --path=libs/<libName>/src/lib/<workerName> --no-interactive`
- check the `apps/<appName>/src/tsconfig.worker.json`

```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/worker",
    "lib": ["es2018", "webworker"],
    "types": []
  },
  "include": ["src/**/*.worker.ts"] <--- the path to the libName is not included
}
```

## Recommended Fix
```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/worker",
    "lib": ["es2018", "webworker"],
    "types": []
  },
  "include": ["src/**/*.worker.ts", "libs/<libName>/src/lib/**/*.worker.ts" ] <--- included the created file path as well
}
```

### Failure Logs
```Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error:<path>/libs/<libName>/src/lib/<workerName>/<name>.worker.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at <path>/node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/loader.js:59:26```

### Environment
 Node : 14.17.0
  OS   : darwin arm64
  yarn : 1.22.10
  
  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : 12.9.0
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by leosvelperez** [comment] 2021-11-11 10:30
@un33k As mentioned above, the `path` property was never intended to be used to provide a path outside of the project the web worker is being created for. This is actually not a bug, but a request for a new feature, the generator is working as expected.

That said, I'd like to understand better the use case for having the web workers in a different project to see if it's something we should support or not. Normally workers are located close to the usage. We can't make use of the TS path mappings to refer to them, so placing them in a separate library would mean using long relative paths to provide the worker paths.

I'm not sure if the idea is to be able to share web workers across projects, if that's the case, maybe extracting the web worker logic to a library would be a better DX, you'd keep the web worker close to the usage, avoid using long relative paths to it and still be able to share the logic of it.

Could you please expand what's your use case for this feature?

**Comment by Coly010** [comment] 2022-01-17 10:36
This has been sitting for a while with no update. I'm going to close this issue, and if any new information comes along that pushes this in the direction of a required feature, we can reopen it.

**Closed by Coly010** 2022-01-17 10:36 UTC
Labels: type: feature, scope: angular

**Comment by domiSchenk** [comment] 2022-04-11 12:35
Just came across this issue.
@leosvelperez / @Coly010 

I think we have a similar requirement.
I try to migrate our angular projects into a nx workspace, and im asking my self how I can handle multiple web-workers.

Currently we do have something like a core repo that only contains multiple "libs" and our web-workers.
In another some other repos(~4) we have our apps. 

In our use case i want 1 or 2 libs for our web-workers (they do different stuff) and i want to reference them in all of our apps.

(we hope for speedup in development and easier to debug/test)
