### ISSUE TITLE
Update "jasmine-marbles" and "rxjs-for-await" to fix "incorrect peer dependency" warnings

### ISSUE THREAD

**Issue by hakimio** [nrwl/nx#8717] opened 2022-01-27 12:58 UTC
## Current Behavior
Installing `@nrwl/angular` with yarn produces following warnings:
```
warning "@nrwl/angular > jasmine-marbles@0.8.4" has incorrect peer dependency "rxjs@^6.5.3".
warning "@nrwl/angular > rxjs-for-await@0.0.2" has incorrect peer dependency "rxjs@^6.0.0".
```

## Expected Behavior
No warnings or errors during installation.

## Steps to Reproduce
Try to install `@nrwl/angular` with yarn package manager

### Failure Logs
```
warning "@nrwl/angular > jasmine-marbles@0.8.4" has incorrect peer dependency "rxjs@^6.5.3".
warning "@nrwl/angular > rxjs-for-await@0.0.2" has incorrect peer dependency "rxjs@^6.0.0".
```

### Environment
```
   Node : 16.13.2
   OS   : win32 x64
   yarn : 1.22.17

   nx : 13.5.3
   @nrwl/angular : 13.5.3
   @nrwl/cli : 13.5.3
   @nrwl/cypress : 13.5.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.5.3
   @nrwl/eslint-plugin-nx : 13.5.3
   @nrwl/express : undefined
   @nrwl/jest : 13.5.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.5.3
   typescript : 4.5.5
   rxjs : 7.5.2
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.0
         @angular/cdk: 13.2.0
         @angular/common: 13.2.0
         @angular/compiler: 13.2.0
         @angular/core: 13.2.0
         @angular/fire: 7.2.0
         @angular/forms: 13.2.0
         @angular/material: 13.2.0
         @angular/platform-browser: 13.2.0
         @angular/platform-browser-dynamic: 13.2.0
         @angular/router: 13.2.0
         @datorama/akita: 7.1.1
         @ngrx/component: 13.0.2
         @angular-devkit/architect: 0.1302.0
         @angular-devkit/build-angular: 13.2.0
         @angular/cli: 13.2.0
         @angular/compiler-cli: 13.2.0
         @angular/language-service: 13.2.0
```

**Comment by Coly010** [comment] 2022-01-31 10:10
We are aware of this and unfortunately, we're stuck between a rock and a hard place with that scenario right now due to Angular's decision to only use RxJS 7 with new workspaces. 

The problem is due to Angular 13 installing RxJS 7 for new workspaces, but keeping existing workspaces at RxJS 6. We cannot migrate to RxJS 7 with Nx without breaking all existing workspaces. However, new workspaces should not encounter any issue beyond the peer dependency warning being logged.

I'll close this issue as there doesn't seem to be any erroneous behaviour associated with this right now.

**Closed by Coly010** 2022-01-31 10:10 UTC
Labels: type: bug, scope: angular

**Comment by Plorax** [comment] 2022-07-21 23:10
This is a rather bad eye-sore when installing components that rely on these. I wish there was a way you can fix this.
