### ISSUE TITLE
`nx affected` cannot analyze the affected projects at the file level

### ISSUE THREAD

**Issue by aosnow** [nrwl/nx#21964] opened 2024-02-23 09:41 UTC
### Current Behavior

![image](https://github.com/nrwl/nx/assets/3865017/146f8309-2738-4991-a7e1-91594699e3c2)

As shown in the above figure, assuming

- There are a.ts and b.ts files in util.
- app01 and app02 reference members from a.ts.
- app02 and app03 reference members from b.ts.
- Modifying the referenced members in a.ts.
- The result obtained through `nx affected --target=build` is that all 3 apps are rebuilt.

### Expected Behavior

When executing `nx affected`, it performs precise analysis at the file level. As stated in the above problem, app3 should be unrelated to a.ts and should not be built.

### Steps to Reproduce

1. Any nx monorepo project
2. Create 3 apps: app01, app02, app03
3. Create libs/util and create a.ts, b.ts with simple members defined, such as `export const echo = (v: string) => v;`
4. app01 and app02 reference the echo method in a.ts
5. app02 and app03 reference the echo method in b.ts
6. Commit the current changes
7. Check the new branch like release
8. On the release branch, modify the echo method in a.ts
9. Execute `nx affected` to view the results.

### Nx Report

```shell
$ nx affected --target=build --base=release

    √  nx run app01:build:production  [existing outputs match the cache, left as is]
    √  nx run app03:build:production (9s)
    √  nx run app02:build:production (9s)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for 3 projects and 2 tasks they depend on (10s)

   Nx read the output from the cache instead of running the command for 1 out of 3 tasks.

Done in 10.76s.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment] 2024-05-09 17:53
I'm going to close this issue as its the intended behavior.

The project level splits the difference between being efficient and being easy to understand. Both are important.

If those 2 files represented very different functionalities, then I would recommend splitting them into 2 separate projects.

**Closed by FrozenPandaz** 2024-05-09 17:53 UTC
Labels: type: feature, scope: core
