### ISSUE TITLE
NX DTE not uploading cached results for @nx-tools/nx-container for nextjs

### ISSUE THREAD

**Issue by FaresKi** [nrwl/nx#18783] opened 2023-08-22 20:25 UTC
### Current Behavior

I'm not exactly sure if it's a bug or not.

I'm currently using the [@nx-tools/nx-container](https://github.com/gperdomor/nx-tools) generator to build Docker images out of my apps in my repo.

The "container" generator uses the build generator, originally provided by nx. It requires to run build, and tests, and linting...etc.

That being said, the building is cached thru DTE, and works accordingly. However, the cache isn't uploaded to the CI, and thus the Dockerfile, when fetching the <app-name>/.next folder, can't find it since the build was cached and thus not executed.

Is there a way to upload the cached results, or not?

### Expected Behavior

I would like to be able to upload the cached results to reuse them with other generators.

### Steps to Reproduce

1. Generate a nextjs app thru nx
2. Install the nx-tooling/nx-container above
3. cache the production build in nx cloud
4. try to build containers using that cache

### Nx Report

```shell
Node   : 18.15.0
   OS     : darwin-x64
   pnpm   : 8.6.12
   
   nx (global)        : 16.5.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.7.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.7.2
   @nx/eslint-plugin  : 16.6.0
   @nx/next           : 16.6.0
   @nx/react          : 16.7.0
   @nrwl/tao          : 16.5.0
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.0.3
   ---------------------------------------
   Local workspace plugins:
         @sahl-apps/email-tooling
         @sahl-apps/data-access
         @sahl-apps/zod-types
         @sahl-apps/logger
```

### Failure Logs

```shell
>  NX   Running target container for 3 projects and 7 tasks they depend on:

    - sahl-admin-dashboard
    - sahl-showcase-site
    - sahl

> nx run sahl-showcase-site:build:production  [remote cache]
...
[Dockerfile]: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref i4cj9sxklw2vr2b7ryba6kcd2::g176vuli380pkuys0qon1yief: "/apps/sahl-showcase-site/.next": not found
> nx run sahl:build:production  [remote cache]
...
[Dockerfile]: ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref i4cj9sxklw2vr2b7ryba6kcd2::wk9w78ilbdsrdh4o7rgc8p17s: "/apps/sahl/.next": not found
> nx run sahl-admin-dashboard:build:production (works as expected)
...
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment] 2023-08-23 20:30
I'm going to close this as a duplicate of https://github.com/gperdomor/nx-tools/issues/877 for now.

Hopefully they can help you. If not, feel free to open another issue here.

**Closed by FrozenPandaz** 2023-08-23 20:30 UTC
Labels: type: bug
