### ISSUE TITLE
Nx eslint workspace-rule dosn't work with eslint flat config

### ISSUE THREAD

**Issue by beaussan** [nrwl/nx#19754] opened 2023-10-20 13:14 UTC
### Current Behavior

Currently, none of the workspace rules are detected in eslint flat config. I've tried to setup from scratch and generate the workspace rule after the flat config, and before the migration, none works.

### Expected Behavior

The workspace rule is detected and run

### GitHub Repo

https://github.com/beaussan/repro-nx-workspace-rule-with-flat-config

### Steps to Reproduce

- create a workspace, typescript, node, single server, vanilla. Any other will work since it's an issue with the `@nx/eslint` package.
- `nx run-many -t lint --all` => ✅
- `nx generate @nx/eslint:convert-to-flat-config` => ✅
- `nx run-many -t lint --all` => ✅
- `nx generate @nx/eslint:workspace-rule --name "demoRule"` => ✅
- `nx run-many -t lint --all` => ❌

Fails with `TypeError: Key "rules": Key "@nx/workspace/demoRule": Could not find plugin "@nx/workspace".`.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

Node   : 18.18.1
OS     : linux-x64
yarn   : 1.22.18

nx                 : 17.0.0
@nx/js             : 17.0.0
@nx/jest           : 17.0.0
@nx/linter         : 17.0.0
@nx/eslint         : 17.0.0
@nx/workspace      : 17.0.0
@nx/devkit         : 17.0.0
@nx/esbuild        : 17.0.0
@nx/eslint-plugin  : 17.0.0
@nx/node           : 17.0.0
@nrwl/tao          : 17.0.0
typescript         : 5.1.6
```

### Failure Logs

```shell
TypeError: Key "rules": Key "@nx/workspace/demoRule": Could not find plugin "@nx/workspace".
at throwRuleNotFoundError (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/eslint/lib/config/rule-validator.js:65:11)
at RuleValidator.validate (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/eslint/lib/config/rule-validator.js:127:17)
at FlatConfigArray.[finalizeConfig] (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/eslint/lib/config/flat-config-array.js:231:23)
at FlatConfigArray.getConfig (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/@humanwhocodes/config-array/api.js:969:55)
at FlatConfigArray.isFileIgnored (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/@humanwhocodes/config-array/api.js:993:15)
at /workdir/repro-nx-workspace-rule-with-flat-config/node_modules/eslint/lib/eslint/eslint-helpers.js:312:49
at Array.reduce (<anonymous>)
at entryFilter (/workdir/repro-nx-workspace-rule-with-flat-config/node_modules/eslint/lib/eslint/eslint-helpers.js:299:28)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I also tried with a non flat config, and run the generator, and the result is the same: workspace rules don't work with flat config

**Comment by pumano** [comment] 2023-10-24 07:39
Got that behaviour too, I have custom nx workspace rules and it not working:

```
TypeError: Key "rules": Key "@nx/workspace/no-deprecated-rxjs-imports": Could not find plugin "@nx/workspace".
```

That workspace rules perfectly works with standard eslint config, but not works with flat config.

**Comment by MJez29** [comment] 2023-11-02 14:17
I think this is partially an issue with eslint flat configs not supporting more than one `/`. Anecdotally, I'm working in a project that doesn't use nx workspace rules but uses a plugin (ex. `@abc/eslint-plugin`) that has a rule with a slash in it (ex. `def/ghi`). When I updated to flat configs eslint stopped being able to resolve this rule so the rule name needed to be updated to get rid of the `/`

**Comment by meeroslav** [comment] 2023-11-06 08:52
Thank you, @beaussan, for reporting this issue. I will look into it as soon as possible.

**Comment by beaussan** [comment] 2023-11-06 08:55
@meeroslav thanks!
Given how the new eslint flat config work, we should be able to import a eslint plugin with a import call and not have to deal with the nx workspace eslint workaround?

**Comment by meeroslav** [comment] 2023-11-06 08:56
> Given how the new eslint flat config work, we should be able to import a eslint plugin with a import call and not have to deal with the nx workspace eslint workaround?

I agree. The workspace rules have gone under my radar, unfortunately. I'll try to fix this as soon as possible.

**Comment by meeroslav** [comment] 2023-12-14 14:53
@pumano, I don't think you issue is related to this one. Please open another issue and explain what are you experiencing and how to reproduce it.

**Comment by meeroslav** [comment] 2023-12-14 15:37
Oh wow, this was unexpected. It turns out that names such as `@nx/workspace/rule-name` are no longer possible with flat config. 

Changing the logic to construct names like `@nx/workspace-rule-name` works.

@JamesHenry were you aware of this? I will check with ESLint team and then we'll decide if this requires fix on their side or migration on ours.

**Comment by meeroslav** [comment] 2023-12-14 15:59
Reported to ESLint https://github.com/eslint/eslint/issues/17857

Let's get their suggestion on where this should be fixed.

**Closed** 2023-12-15 15:00 UTC
Labels: type: bug, blocked: third-party, scope: linter
