### ISSUE TITLE
Cannot Read Properties of null (reading 'replace')

### ISSUE THREAD

**Issue by nii-kwartei** [nrwl/nx#16722] opened 2023-05-03 13:37 UTC
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback
- [x] Tutorial Error 

I'm trying out the angular standalone tutorial here: https://nx.dev/tutorials/angular-standalone-tutorial. 
After creating the workspace and attempting to create a shop following this command: `npx nx g @nx/angular:component shop --project=store`, I get this error: 

`NX  Generating @nx/angular:component

NX   Cannot read properties of null (reading 'replace')

TypeError: Cannot read properties of null (reading 'replace')
    at removeWindowsDriveLetter (/Users/I545703/SAPDevelop/PoCs/Frontend/devXp/monorepo/store/node_modules/nx/src/utils/path.js:6:27)
    at normalizePath (/store/node_modules/nx/src/utils/path.js:12:12)
    at findModuleFromOptions (/store/node_modules/@nx/angular/src/generators/component/lib/module.js:13:43)
    at /store/node_modules/@nx/angular/src/generators/component/component.js:43:64
    at Generator.next (<anonymous>)
    at /store/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter /store/node_modules/tslib/tslib.js:163:16)
    at componentGenerator (/store/node_modules/@nx/angular/src/generators/component/component.js:9:20)
    at Object.<anonymous> (/store/node_modules/nx/src/command-line/generate.js:249:36)`

I'm not sure how to resolve this issue.

**Comment by cotneit** [comment] 2023-05-03 14:22
This seems to be an issue for apps initialized with standalone components, try adding `--standalone`, this seems to work for me. Alternatively, you can try using `@schematics/angular` instead of `@nx/angular`

**Comment by AgentEnder** [comment] 2023-05-03 14:23
This is a duplicate of #16689, so I'm going to close it out. Feel free to subscribe to #16689 to be notified of progress on the issue.

**Closed by AgentEnder** 2023-05-03 14:23 UTC
Labels: type: docs
