### ISSUE TITLE
Can't find workspace libraries in storybook build in nx@^16.9.0

### ISSUE THREAD

**Issue by GabrielAPineiro** [nrwl/nx#19657] opened 2023-10-17 15:24 UTC
### Current Behavior

In the latest releases (16.9.0 and 16.10.0) while trying to build storybook the builder is unable to find a lib that is placed within the workspace.

### Expected Behavior

Resolution works correctly as in 16.8.1.

### Steps to Reproduce

1. Try to run build-storybook command
![image](https://github.com/nrwl/nx/assets/104081429/27efcb49-55e8-43b9-ba2b-f763d6b6c86e)

### Nx Report

```shell
Node   : 18.16.1
   OS     : win32-x64
   yarn   : 1.22.19

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/angular        : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/plugin         : 16.10.0
   @nx/storybook      : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/webpack        : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core              : 1.23.0
   @storybook/angular           : 7.4.6
   @trumbitta/nx-plugin-openapi : 1.12.1
   ng-mocks                     : 14.11.0
   ---------------------------------------
   Local workspace plugins:
   @exclaimer/workspace-plugin
```

### Failure Logs

```shell
npx nx run configuration-feature-audit-log:build-storybook

> nx run configuration-feature-audit-log:build-storybook

info => Cleaning outputDir: \dist\storybook\feature-audit-log
Error: Cannot find module '@exclaimer/shared/storybook'
Require stack:
- .\libs\configuration\frontend\feature-audit-log\.storybook\main.ts
- .\node_modules\@storybook\core-common\dist\index.js
- .\node_modules\@storybook\cli\dist\index.js
- .\node_modules\@storybook\angular\dist\builders\build-storybook\index.js
- .\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- .\node_modules\@angular-devkit\architect\node\index.js
- .\node_modules\nx\src\adapter\ngcli-adapter.js
- .\node_modules\nx\src\command-line\run\run.js
- .\node_modules\nx\bin\run-executor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Module.require (.\node_modules\nx\src\adapter\compat.js:34:40)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (.\libs\configuration\frontend\feature-audit-log\.storybook\main.ts:24:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._compile (.\node_modules\esbuild-register\dist\node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (.\node_modules\esbuild-register\dist\node.js:2262:9)


 >  NX   Broken build, fix the error above.

   You may need to refresh the browser.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target build-storybook for project configuration-feature-audit-log (15s)

    ×    1/1 failed
    √    0/1 succeeded [0 read from cache]

   View structured, searchable error logs at https://cloud.nx.app/runs/fhfnZnASMU
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The internal lib only has a list of strings that is shared as part of the storybook configuration
![image](https://github.com/nrwl/nx/assets/104081429/b6b6d064-6068-4063-94ae-76f81e7d8552)

**Comment by mandarini** [comment] 2023-10-18 07:26
Ah @GabrielAPineiro I see. It's because you're trying to import your library into your `main.ts` or your Storybook configuration files. That would not work, because this happens before the TypeScript compilation. What I suggest is you can create a root `.storybook` folder, and have the "shared" configuration you need in there, and then import this file into your projects. 

Take a look at this docs page: https://nx.dev/recipes/storybook/custom-builder-configs#global-configuration

I know you are not trying to configure webpack or vite, you just need the extra addons in your case. But in any case, this is how it could work for you:

1. Create a `.storybook` directory in the root of your workspace
2. Create a `main.ts` file in there
3. Add any global Storybook configuration in that file
4. In your project-level `.storybook/main.ts` do, for example:
```
...
import rootMain from '../../../.storybook/main';

const config: StorybookConfig = {
  ...rootMain,
  stories: ...,
  addons: ...,
 framework: ...
};

export default config;
```

Does this make sense?

I will close this issue since it's not a bug, but please reply here with any more questions or concerns and I'll be happy to answer!

**Closed** 2023-10-18 07:26 UTC
Labels: type: bug, scope: storybook
