### ISSUE TITLE
Run `run-many` in order

### ISSUE THREAD

**Issue by seravifer** [nrwl/nx#6577] opened 2021-08-02 11:29 UTC
## Current Behavior
Every time I launch the command, it runs all the projects in a random order.

## Expected Behavior
I want it to launch in sequential order as it is passed to the command.
It would be interesting if you used the dependency graph to know which one you can compile first.

## Steps to Reproduce
`nx run-many --target=build --projects=styles,icons,core,components,schematics`

Expected build: styles > icons > core > ...

### Environment
```
  Node : 14.17.0
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.5.7
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment] 2021-08-03 14:51
Thanks for reporting this!

Nx schedules tasks to be run based on the tasks dependencies. It guarantees that dependencies of any given task are always run first.

If you are having an issue where a task is run before its dependencies, could you please share a minimal repo where this issue can be reproduced?

**Comment by seravifer** [comment] 2021-08-04 13:01
Ok, I'm going to try to reproduce it in a test repo.

When I launch the command for example, I get this message in some packages:
```
> nx run core-ui:build 
Some of the project core-ui's dependencies have not been built yet. Please build these libraries before:
- components

Try: nx run core-ui:build --with-deps
```

**Comment by seravifer** [comment] 2021-08-04 13:15
Minimal repo: [https://github.com/seravifer/nx-playground](https://github.com/seravifer/nx-playground)
Run: `nx run-many --target=build --projects=components,core,core-ui`

Result:  ERROR  Running target "build" failed

**Comment by leosvelperez** [comment] 2021-08-04 15:02
Oh, I see. You need to instruct Nx on how to handle dependencies by configuring the [target dependencies](https://nx.dev/latest/angular/core-concepts/configuration#target-dependencies). I'm sorry, I was wrongly assuming your workspace had it configured.

You can add the following to the `nx.json` file to make sure that all dependent `build` targets will run:

```json
"targetDependencies": {
  "build": [
    {
      "target": "build",
      "projects": "dependencies"
    }
  ]
}
```

This setup Nx so when any `build` target is run, it has to run the `build` target of all its dependencies. This solves the issue.

**Comment by leosvelperez** [comment] 2021-08-04 15:25
I'm closing this since the solution was provided in the previous comment. If you still think there's an issue, please feel free to reopen this or create another issue.

**Comment by seravifer** [comment] 2021-08-05 07:30
We removed `targetDependencies` because it was causing us a lot of problems executing build tasks. We usually `--skip-nx-cache` and that causes the builds to be launched multiple times.
So the problem still exists. We need the `run-many` commands to be executed in the order that is passed and not randomly as it happens now.

**Comment by seravifer** [comment] 2021-08-05 07:43
We have something like this:
```
          "prepare-publish": {
            "executor": "@nrwl/workspace:run-commands",
            "options": {
              "commands": [
                "nx lint core-ui --skip-nx-cache",
                "npm run test:core-ui:ci -- --skip-nx-cache",
                "nx build core-ui --skip-nx-cache"
              ],
              "parallel": false
            }
          }
```
And if we have "targetDependencies" then NX rebuild all last package. So the idea is that `run-many` work run sequence

**Comment by leosvelperez** [comment] 2021-08-05 10:11
> And if we have "targetDependencies" then NX rebuild all last package.

I'm not sure I understand this statement or the issue you refer to. Nx will run the provided tasks and their dependencies according to what you specify in the `targetDependencies` configuration, so it comes down to how you organize your targets and configure their dependencies. 

To clarify something, the tasks are not being run "randomly". The order in which tasks are executed is consistent, you don't get a different order in every run.

I do think it's a valid point to run them in the specified sequence by default, though it seems like you are trying to do manually what `targetDependencies` can do for you automatically.

I'm reopening this, I'd like to understand better what issue you are having with `targetDependencies`. I think solving that can improve your commands by reducing the manual setup of projects to be run in a specific order. Could you please expand a bit more on the issue you're having with `targetDependencies`?

**Comment by seravifer** [comment] 2021-08-06 10:40
Thanks for the help, i will try to explain it better.

Our objective is to build, lint and test each library of our monorepo without using the Nx cache, that is, in a clean way before publishing. For this we have the `prepare-publish` executor shown above that performs these three tasks for each library.

Now the next thing we do is run each `prepare-publish` in dependency order: `nx prepare-publish core && nx prepare-pusblish components && ...`. We want to avoid that.

If we configure the `targetDependencies` we see that some libraries are built multiple times.

We are probably doing something wrong. How should we execute those three tasks for each library without using cache?

I have updated the test repository with this case.

If your run `nx run-many --target=prepare-publish --projects=core,components,core-ui --skip-nx-cache` you will see that compile `core` then `core and components` and `core, components and core-ui`.

if we remove the `--skip-nx-cache` from `nx build components --skip-nx-cache` on the `prepare-build`works but is using the cache.

How do we avoid that?

Maybe it should be possible to pass more than one `target` to the command.
I think the only option I'm seeing is to have a `run-many` for lint another for test and another for build.

I hope it is understood and thanks again for the help.

**Comment by leosvelperez** [comment] 2021-08-06 13:55
Thanks for explaining!

I see what you meant now, I didn't understand it before.

The problem is that each individual command is skipping the cache and yes, that would make it build every dependency even if it has been built before. Each command in `run-commands` will spawn a process where the task along with its dependencies will be built. When cached is enabled, the repeated projects build are just retrieved from the cache and not rebuilt every time.

What you'd rather seem to need is to clear the cache once and then run the `prepare-publish` with the commands in `angular.json` without the `--skip-nx-cache`. That way you start with no cache and as tasks get executed the cache is populated and you benefit from it. Something like this should work:

```json
// package.json
{
  ...
  "scripts": {
    ...
    "publish": "nx clear-cache && nx run core-ui:prepare-publish"
    ...
  }
  ...
}
```

Please note that if you're using Nx Cloud that alone won't work. The `nx clear-cache` only clears the local cache. If that's the case, additional things can be done (use a different tasks runner) to not use Nx Cloud when running `prepare-publish`.

That said, what you've been trying to do also works, it won't schedule the dependencies and therefore you're in control of what gets executed, but it does come with a maintenance burden. I'll push a fix soon, so the tasks get executed using by default the provided projects order.

Out of curiosity, why do you need to run the publish without the cache? What's retrieved from the cache, it's supposed to not have changed. Are you facing scenarios where the cache is not being properly invalidated?

**Closed** 2021-08-06 22:16 UTC
Labels: type: bug, scope: core
