### ISSUE TITLE
V16 breaks .env variables scope when running @nx/js:node with buildTarget dependencies 

### ISSUE THREAD

**Issue by rezoled** [nrwl/nx#17128] opened 2023-05-21 13:48 UTC
### Current Behavior

If you have a serve task that its buildTarget has other apps as dependencies, the other apps will get the original tasks env variables, and not their own env vars that are defined in their local .env file.

If you run the buildTarget directly the env var scope works fine, and each dependency gets its own env vars.

### Expected Behavior

Have a consistent scoping of env vars, that each app receives the vars from its local .env file.

### GitHub Repo

https://github.com/roypeled/nx-16-bug

### Steps to Reproduce

Each application has a local .env in the specific app root, with an APP_NAME var.

1. install all dependencies
2. run ```nx build api```
3. notice the 3 api.txt files generated in ```generated/api/api.txt```, ```generated/foo/api.txt``` and ```generated/bar/api.txt``` - each api.txt prints the name of the application 
4. run ```nx serve api``` - which has a target of ```api:build```
5. notice now the api.txt files, they are all the same with the env var ```APP_NAME=api``` from the initial serve command

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/esbuild        : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/node           : 16.2.1
   @nrwl/tao          : 16.2.1
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is critical for our company, we have many microservices and each generates a standard schema file with its app name in the schema fields. 
The app name is injected via .env files for each MS.
In V15 we had not problem and every schema for each MS was generated correctly, now we can't run the app locally since our main API gateway service overwrites its dependencies env vars...

**Comment by jaysoo** [comment] 2023-05-23 17:17
@rezoled Which version of Nx 15 did you upgrade from?

**Comment by rezoled** [comment] 2023-05-23 18:07
Thanks @jaysoo! I am awaiting your conclusion.

**Comment by jaysoo** [comment] 2023-05-23 18:52
@rezoled I provided a workaround in a PR to your repro: https://github.com/roypeled/nx-16-bug/pull/1

In terms of the correct behavior, it is correct that when `serve` runs `buildTarget`, it should also run dependencies. 

The one odd thing is how `.env` files are treated. Previously since dependencies were not re-run, it sounds like you just run `nx build` before `nx serve`, which would generate those schema files. Our intention with the new change is that `nx serve` should be runnable without `nx build` first (since nx build is meant for production build).

I hope the workaround I posted is enough to unblock you. I need to discuss the `.env` behavior with the other core contributors because there is inconsistency between running `nx schema foo` by itself and within the context of `nx serve api` when there are overlaps in environment variables, even though logically I know why it happens maybe it's something we can improve on.

**Comment by jaysoo** [comment] 2023-05-25 15:36
After further consideration, I think this behavior is correct for a couple of reasons:

1. Environment variables in `.env` files should always consider overrides from CLI or CI. For example, running `DATABASE_URL=postgresql://test:test@localhost:5432/test nx serve` would provide the DB URL to use for connection. This means that results from running Nx commands should vary on the execution context.
2. We can't reliably know if an environment variable is set in the system (e.g. `.bashrc` or CI), through CLI command (e.g. `DATABASE_URL=... nx serve`), or through `.env` files. We need to chain environment variables from parent process down the child processes because they may depend them (e.g. `DATABASE_URL`, `NODE_ENV`).

For any environment variable used, think if it's possible to set them in the system (e.g. `.bashrc`) or passed in CLI commands. If not due to conflicts, then maybe rename the variables, or rework the scripts/programs such that the problem doesn't exist. I think the workaround I showed in the [PR here](https://github.com/nrwl/nx/issues/17128#issuecomment-1559969334) is  good starting point.

---

Will close this since it's an intended behavior.

**Closed by jaysoo** 2023-05-25 15:36 UTC
Labels: type: bug, scope: node

**Comment by rezoled** [comment] 2023-05-28 08:07
I agree with your points, however I do think that the problem stems from the fact that dependencies' tasks inherit the env vars of their dependent process. 
Especially for buildTarget, the dependencies should run in their own scope, since run target and build target are completely different.

**Comment by rezoled** [comment] 2023-05-29 06:55
Just for example of a use case, to generate GQL schemas in a NestJS app you would need to run the server, after bootstrap the server generates the GQL files and afterwards we can kill it.
This is necessary for Frontend development since you need updated GQL schemas to write your queries.
 Having all of the Frontend dependencies generate GQL schemas when serving frontend is great, running the schema generation with frontend env vars is not great.
