### ISSUE TITLE
App name isn't listed if I run the command nx affected:apps or nx print-affected if only app is modified

### ISSUE THREAD

**Issue by siirtecirlioglu** [nrwl/nx#3134] opened 2020-06-08 07:46 UTC
## Current Behavior
Hi, I recently started using Nx. When I edit a file in one of my apps, it does not show when I do nx affected:apps or even in nx print-affected. However, these commands work as expected if I edit a lib that the app depends on.

## Expected Behavior
I would expect the app name and the app's e2e app name to be listed when I run either of the commands.

## Steps to Reproduce
1. Create myapp1
2. Commit to git
3. Modify app.component.ts in myapp1
4. Run nx print-affected
5. The "projects" list is empty. Expected: "projects": ["myapp1", "myapp1-e2e"]

**Comment by FrozenPandaz** [comment] 2020-06-12 22:25
I'm not able to reproduce this on http://github.com/nrwl/nx-examples

Can you please provide a repo exhibiting the issue?

**Comment by FrozenPandaz** [comment] 2020-08-14 19:16
@siirtecirlioglu I'm going to close this issue since there hasn't been a response. Please open a new issue if you continue to run into this issue.

**Closed by FrozenPandaz** 2020-08-14 19:16 UTC
Labels: blocked: repro needed, scope: core, type: bug
