### ISSUE TITLE
[feat] ng add - keep git history when moving existing cli src folder to apps/

### ISSUE THREAD

**Issue by MarkPieszak** [nrwl/nx#554] opened 2018-05-31 15:07 UTC
Hi everyone :wave: 🐬 

When porting an existing CLI application to Nx with `ng add`, all git history is lost when the files from `/src/` are moved to `/apps/[app_name]`.

If we used `git mv` (syntatic sugar for git add / git remove), we'd be able to hold onto all of the history of those files etc.

Current implementation using `fs.renameSync()`:

```ts
function moveOutOfSrc(sourceRoot: string, appName: string, filename: string) {
  fs.renameSync(
    path.join(sourceRoot, filename),
    path.join('apps', appName, filename)
  );
}
``` 

Possible git mv syntax that could be used (or some alternative)

```bash
git mv src apps/project_name

- stripped down version

mv before after
git add after
git rm before
```

To reproduce simply create a new CLI application and ng add nrwl schematics to see all history is lost.

**Comment by bcabanes** [comment] 2018-11-23 21:54
Closing as duplicate of #32.

**Closed by bcabanes** 2018-11-23 21:54 UTC
Labels: type: enhancement
