### ISSUE TITLE
Workspace version of Prettier is not respected, causing nullish coalescing operator to fail

### ISSUE THREAD

**Issue by dopsonbr** [nrwl/nx#2102] opened 2019-11-25 22:56 UTC
## Expected Behavior
Format command should not fail when it encounters a file with the nullish coalescing operator. 
Prettier support for the operator was introduced in version [1.19.1](https://github.com/prettier/prettier/pull/6657)

## Current Behavior

The nx format command fails when it encounters a file containing a `??` (nullish coalescing operator).

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

#### minimal repo with issue
``` bash
git clone https://github.com/dopsonbr/reproduce-prettier-format-issue \
&& cd reproduce-prettier-format-issue \
&& yarn install --frozen-lockfile \
&& echo '\n' >> apps/reproduce/src/app/app.component.ts \
&& yarn format
```

#### from scatch

- `yarn create nx-workspace reproduce-prettier-format-issue`
- `yarn ng update @angular/cli @angular/core --next --force`
- `yarn ng update typescript prettier --force`
- replace app.component.ts with

```text
import { Component } from '@angular/core';

interface Foo {
  readonly bar: string;
  readonly fubar?: string;
}

@Component({
  selector: 'reproduce-prettier-format-issue-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'reproduce';
  fooWithNull: Foo = {
    bar: 'fizz'
  };

  getFoo(): Foo {
    return {
      bar: this.fooWithNull.bar,
      fubar: this.fooWithNull.fubar ?? 'aFubar'
    }
  }
}
```
- `yarn format`

## error message:
```text
yarn run v1.19.1
$ nx format:write

>  NX   NOTE  Affected criteria defaulted to --base=master --head=HEAD

apps/reproduce/src/app/app.component.ts
[error] apps/reproduce/src/app/app.component.ts: SyntaxError: Expression expected. (23:38)
[error]   21 |     return {
[error]   22 |       bar: this.fooWithNull.bar,
[error] > 23 |       fubar: this.fooWithNull.fubar ?? 'aFubar'
[error]      |                                      ^
[error]   24 |     }
[error]   25 |   }
[error]   26 |
package.json 33ms
/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: Command failed: node "/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/@nrwl/workspace/node_modules/prettier/bin-prettier.js" --write "apps/reproduce/src/app/app.component.ts" "package.json"
    at checkExecSyncError (child_process.js:631:11)
    at Object.execSync (child_process.js:668:15)
    at write (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/@nrwl/workspace/src/command-line/format.js:84:25)
    at /Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/@nrwl/workspace/src/command-line/format.js:42:40
    at Array.forEach (<anonymous>)
    at Object.format (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/@nrwl/workspace/src/command-line/format.js:42:23)
    at Object.handler (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:72:98)
    at Object.runCommand (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/yargs/yargs.js:1022:30)
    at Object.get [as argv] (/Users/bxd5017/github/dopsonbr/reproduce-prettier-format-issue/node_modules/yargs/yargs.js:965:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Context

Please provide any relevant information about your setup:
#### yarn nx report
```
yarn run v1.19.1
$ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.8.2
  @nrwl/cli : 8.8.2
  @nrwl/cypress : 8.8.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.8.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.8.2
  @nrwl/web : Not Found
  @nrwl/workspace : 8.8.2
  typescript : 3.7.2

✨  Done in 1.25s.

```
- prettier version 1.19.1

**Comment by FrozenPandaz** [comment] 2019-11-29 21:12
Thank you for reporting this issue.

This is a bug where `@nrwl/workspace` has it's own version of `prettier` installed which is used when running `nx format` instead of the one installed in the workspace. I edited the title to cover that.

Unfortunately, until we either fix this bug or update our version of `prettier`, you won't be able to use that version of `pretttier`.

Mismatching versions of `prettier` can be a large inconvenience since editors will format files in a way which Nx will report as invalid.

**Comment by vsavkin** [comment] 2019-12-02 23:30
@dopsonbr would you like to send a PR fixing it? We can help.

**Comment by vsavkin** [comment] 2019-12-03 15:33
Actually, this appears to be a duplicate of https://github.com/nrwl/nx/issues/1863.

I'm going to close this issue.

**Closed by vsavkin** 2019-12-03 15:33 UTC
Labels: community, type: bug
