### ISSUE TITLE
Jest: Do Not Stomp On Entire "globals" Field

### ISSUE THREAD

**Issue by source-transformer** [nrwl/nx#1771] opened 2019-08-30 18:55 UTC
We're using @nrwl 8.4.12 (including @nrwl/jest 8.4.12).

## Expected Behavior

We expect to be able to pass globals data and not have it entirely stomped on.

## Current Behavior

The current behavior is derived from:
node_modules/@nrwl/jest/src/builders/jest/jest.impl.js

Specifically this line:
globals: JSON.stringify({
            'ts-jest': tsJestConfig
        }

It's fine to inject/override
globals.ts-jest 

with the tsJestConfig.  But, users should be able to add other globals to suit their needs.

## Failure Information (for bugs)

Don't stomp on the entire globals object.

### Steps to Reproduce

1. Put any data into the globals object in your jest.config.js
2. Observe in the runtime - your data is not accessible

### Context

- @nrwl 8.4.12 

### Failure Logs

N/A

**Comment by mehrad-rafigh** [comment] 2019-08-31 21:18
This is a duplicate of https://github.com/nrwl/nx/issues/1059

**Comment by vsavkin** [comment] 2019-09-02 18:58
@source-transformer thanks for submitting the issue. As @mehrad-rafigh mentioned it looks like it is a duplicate of #1059 . We will try to land the fix in the next minor release.

**Closed by vsavkin** 2019-09-02 18:58 UTC
