### ISSUE TITLE
Regression: Can't use Angular Injectable static properties in Cypress

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#7967] opened 2021-12-02 08:25 UTC
## Current Behavior
After migrating to Nx13, when using Angular Injectable static properties in Cypress specs it throws this error:

```
Error: Webpack Compilation Error
/Users/ariel/www/nx13/node_modules/@angular/common/fesm2015/common.mjs
Module not found: Error: Can't resolve '@angular/core' in '/Users/ariel/www/nx13/node_modules/@angular/common/fesm2015'
resolve '@angular/core' in '/Users/ariel/www/nx13/node_modules/@angular/common/fesm2015'
  Parsed request is a module
  using description file: /Users/ariel/www/nx13/node_modules/@angular/common/package.json (relative path: ./fesm2015)
    Field 'browser' doesn't contain a valid alias configuration
    Looked for and couldn't find the file at the following paths:
```

## Expected Behavior
Should work without errors as it was before the upgrade.

## Steps to Reproduce
Create new Nx project with Angular. Create a todos library and export the following service:

```ts
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class TodosService {
  static url = 'todos';
}
```

Use it in a Cypress spec:

```ts
import { getGreeting } from '../support/app.po';
import { TodosService } from '@foo/todos';

describe('foo', () => {
  beforeEach(() => {
    cy.intercept(TodosService.url);
    cy.visit('/')
  });

  it('should display welcome message', () => {
    cy.login('my-email@something.com', 'myPassword');
    getGreeting().contains('Welcome to foo!');
  });
});
```

**Comment by leosvelperez** [comment] 2021-12-07 14:22
Thanks for reporting this!

I'll close this one as it's a duplicate of #7901, please, follow that one for updates.

**Closed by leosvelperez** 2021-12-07 14:22 UTC
Labels: type: bug, scope: angular
