### ISSUE TITLE
angular.json vs .angular-cli.json

### ISSUE THREAD

**Issue by vdiaz1130** [nrwl/nx#470] opened 2018-05-08 17:39 UTC
I'm trying to configure Nrwl Nx with Angular 6. It seems there are hard-coded references to .angular-cli.json which has been changed to angular.json.

Error: no such file or directory, open '...\.angular-cli.json'

Is angular-cli v6 support coming soon?

**Comment by beeman** [comment] 2018-05-08 17:54
Yesterday there was an alpha release as mentioned by Victor [here](https://github.com/nrwl/nx/pull/419#issuecomment-387433968).

Won't most likely take very long until v6 support is in production.

**Comment by vdiaz1130** [comment] 2018-05-09 01:54
Tried it. Works well up until you want to serve an app:
```
ng serve -a=client-admin
**Unknown option: '-a'**
```

```
ng serve -app=client-admin
**Unknown option: '-a'**
```

Tried various other options (e.g. -a="...", -app="...")

Any ideas or workaround?

**Comment by vdiaz1130** [comment] 2018-05-09 02:39
Dang it! It's not selecting the app. I'm trying to generate a component into the "ui" lib, but it wants to add it to the "client-admin" app. I tried various options. Am I missing something or doing something wrong?

// Selects wrong app...
ng g c splash-view --app=ui --dry-run
ng g c splash-view ui --dry-run
ng g c splash-view -a ui --dry-run
ng g c splash-view --app="ui" --dry-run
ng g c splash-view --app=ui --dry-run
ng g c splash-view --app ui --dry-run
ng g c splash-view -app="ui" --dry-run
ng g c splash-view -app=ui --dry-run
ng g c splash-view -app ui --dry-run
ng g c splash-view -a="ui" --dry-run
ng g c splash-view -a=ui --dry-run
ng g c splash-view -a ui --dry-run

// Selects wrong app
```CREATE apps/client-admin/src/app/splash-view/splash-view.component.html (30 bytes)
CREATE apps/client-admin/src/app/splash-view/splash-view.component.spec.ts (657 bytes)
CREATE apps/client-admin/src/app/splash-view/splash-view.component.ts (288 bytes)
CREATE apps/client-admin/src/app/splash-view/splash-view.component.css (0 bytes)
UPDATE apps/client-admin/src/app/app.module.ts (678 bytes)

NOTE: Run with "dry run" no changes were made.
```
// These result in error
ng g c splash-view -app ui --dry-run
ng g c splash-view -app=ui --dry-run
ng g c splash-view -app="ui" --dry-run
```Schematic input does not validate against the Schema: {"dryRun":true,"a":true,"prefix":["","ui"],"inlineStyle":false,"inlineTemplate":false,"changeDetection":"Default","styleext":"css","spec":true,"flat":false,"skipImport":false,"export":false}```

**Comment by beeman** [comment] 2018-05-09 02:52
@vdiaz1130 you should use `--project`, as you can see when you run:
```
ng generate component --help
```

**Comment by vdiaz1130** [comment] 2018-05-09 02:54
Progress! Thank you!

**Comment by beeman** [comment] 2018-05-09 02:56
@vdiaz1130 [this post](https://medium.com/@beeman/how-to-do-x-in-angular-cli-v6-db7530c23066) might be useful, feel free to post any comments/questions about the changes in the CLI there

**Comment by jeffbcross** [comment] 2018-05-10 21:18
Closing this for now, since it seems like the issue is just that the docs need to reflect the need to use `--project`. Thanks @vdiaz1130 and @beeman!

**Closed by jeffbcross** 2018-05-10 21:18 UTC
