### ISSUE TITLE
Can't use yarn pnp

### ISSUE THREAD

**Issue by Himadu2000** [nrwl/nx#5607] opened 2021-05-09 02:09 UTC
## Current Behavior
C:\Website2\test>nx run react-test:build 

> nx run react-test:build 
Starting type checking service...
Using 1 worker with 2048MB memory limit
Hash: 4a26e441abcd7f203f86
Built at: 05/09/2021 7:12:31 AM
Entrypoint main = runtime.js runtime.js.map vendor.js main.js main.js.map
Entrypoint polyfills = runtime.js runtime.js.map polyfills.js polyfills.js.map
Entrypoint styles = runtime.js runtime.js.map styles.js styles.js.map
chunk {main} main.js, main.js.map (main) 29.9 KiB ={runtime}= ={vendor}= [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 238 KiB ={runtime}= [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={styles}= ={vendor}= [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 7.73 KiB ={runtime}= [initial] [rendered]
chunk {vendor} vendor.js (vendor) 2.46 KiB ={main}= ={runtime}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)`

ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./app/logo.svg
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src\app'

ERROR in ./app/star.svg
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src\app'

ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react-dom' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react/jsx-dev-runtime' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./app/app.tsx
Module not found: Error: Can't resolve 'react/jsx-dev-runtime' in 'C:\Website2\test\apps\react-test\src\app'

———————————————————————————————————————————————

>  NX   ERROR  Running target "react-test:build" failed

  Failed tasks:

  - react-test:build

VS Code extension not showing anything.

## Expected Behavior
> Executing task: nx build react-test <

> nx run react-test:build 
Starting type checking service...
Using 1 worker with 2048MB memory limit
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
Hash: 3563cf7106f599cbdd91
Built at: 05/09/2021 7:32:18 AM
Entrypoint main [big] = runtime.js runtime.js.map vendor.js main.js main.js.map
Entrypoint polyfills [big] = runtime.js runtime.js.map polyfills.js polyfills.js.map
chunk {main} main.js, main.js.map (main) 140 KiB ={runtime}= ={vendor}= [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 243 KiB ={runtime}= [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={vendor}= [entry] [rendered]
chunk {vendor} vendor.js (vendor) 14.5 MiB ={main}= ={runtime}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)

Terminal will be reused by tasks, press any key to close it.

VS Code extension works fine.

Is this a regression? No.

## Steps to Reproduce
Install yarn
Generate a react-app with nx
Run `yarn --pnp`
Run `nx run app:build`

### Failure Logs
ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./app/logo.svg
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src\app'

ERROR in ./app/star.svg
Module not found: Error: Can't resolve 'react' in 'C:\Website2\test\apps\react-test\src\app'

ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react-dom' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./main.tsx
Module not found: Error: Can't resolve 'react/jsx-dev-runtime' in 'C:\Website2\test\apps\react-test\src'

ERROR in ./app/app.tsx
Module not found: Error: Can't resolve 'react/jsx-dev-runtime' in 'C:\Website2\test\apps\react-test\src\app'

———————————————————————————————————————————————

>  NX   ERROR  Running target "react-test:build" failed

### Environment

C:\Website2\test>nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.1.1
  @nrwl/cypress : 12.1.1
  @nrwl/devkit : 12.1.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.1.1
  @nrwl/linter : 12.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.1.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.1.1
  @nrwl/web : 12.1.1
  @nrwl/workspace : 12.1.1
  @nrwl/storybook : 12.1.1
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by Himadu2000** [comment] 2021-11-15 16:20
Is there any plans to support pnp in this year?

**Comment by Himadu2000** [comment] 2022-05-15 08:56
Could someone disable stale issue action please. And this action should not even be used on a repository.

**Comment by AgentEnder** [comment] 2022-06-10 17:18
I'm going to close this out since it is a duplicate of #2386. I can't provide any updates as to yarn 2 / pnp support, but it is something that we are aware of.

**Closed by AgentEnder** 2022-06-10 17:18 UTC
Labels: type: bug, scope: misc
