### ISSUE TITLE
Cannot find @nrwl/node document

### ISSUE THREAD

**Issue by alt1o** [nrwl/nx#11871] opened 2022-09-05 10:23 UTC
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

Enter the URL or documentation section here.

### Additional context or description

Provide any additional details here as needed.

**Comment by alt1o** [comment] 2022-09-05 10:24
https://user-images.githubusercontent.com/21084335/188427767-6d37faa7-c44b-49c5-8c76-9da3c60b39d1.mov

**Comment by AgentEnder** [comment] 2022-09-06 14:30
Duplicate of #11863

**Closed by AgentEnder** 2022-09-06 14:30 UTC
Labels: type: docs
