### ISSUE TITLE
Images (PNG, JPG) is corrupted after migration to the Nx Workspace structure

### ISSUE THREAD

**Issue by vlodko** [nrwl/nx#3491] opened 2020-08-10 09:38 UTC
## Current Behavior / Steps to reproduce

1. Run `ng add @nrwl/workspace` in the regular Angular CLI project
2. After successful migration, start the app locally and observe places with PNG or JPG images.
3. Images are not loading

## Expected Behavior
Images are being moved to a folder in a new structure without corrupting.

### Environment
 @nrwl/angular : 9.0.4
  @nrwl/cli : 9.0.4
  @nrwl/cypress : 9.0.4
  @nrwl/jest : 9.0.4
  @nrwl/tao : 9.0.4
  @nrwl/workspace : 9.0.4
  typescript : 3.7.5

**Comment by vsavkin** [comment] 2020-08-13 19:22
@vlodko 

It's an interesting issue. We are using the standard Angular builder to serve Angular applications. We aren't modifying it in any way. I wonder what's going on there.

Could you provide a repro? Two repos: the Angular CLI project and the transformed project?

**Comment by brandonroberts** [comment] 2020-08-13 20:47
This is a duplicate of https://github.com/nrwl/nx/issues/2469 also

**Comment by brandonroberts** [comment] 2020-08-28 13:41
Closing this one to track with the original reported issue

**Closed by brandonroberts** 2020-08-28 13:41 UTC
Labels: blocked: repro needed, scope: angular, type: bug
