### ISSUE TITLE
Unable to execute node ES Modules

### ISSUE THREAD

**Issue by jmattiace** [nrwl/nx#10565] opened 2022-06-03 02:58 UTC
## Current Behavior
When attempting to execute an ES Module with the `@nrwl/node:node` executor, we get the error reported in the below [Failure Logs section](#failure-logs). After debugging, I've identified that the issue is because the executor is attempting to `require` the module, which is of course not supported for ES Modules.

## Expected Behavior
The ES Module node.js application should properly execute without errors.

## Steps to Reproduce
[Pull this repo](https://github.com/cadenzatv/nx-issue-es-module) in order to reproduce.

1. Create a new node.js project ` nx generate @nrwl/node:app` 
2. Update `tsconfig.app.json` with the following fields:
```json
"module": "esnext",
"target": "es2020"
```
3. Update `project.json` `build` target to use executor `@nrwl/node:webpack`
4. Update `project.json` `build` target with the following fields
```json
"outputFileName": "main.mjs",
"webpackConfig": "webpack.config.js"
```
5. Update `project.json` `serve` target to use executor `@nrwl/node:node`
6. Create root `webpack.config.js` file with the following content
```javascript
module.exports = (config, context) => ({
    ...config,
    experiments: {
        ...config.experiments,
        outputModule: true,
        topLevelAwait: true,
    },
    output: {
        path: config.output.path,
        chunkFormat: 'module',
        library: {
            type: 'module',
        },
    },
})
```

### Failure Logs
```
/app/node_modules/@nrwl/node/src/executors/node/node-with-require-overrides.js:16
        return originalLoader.apply(this, arguments);
                              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/dist/packages/test/main.mjs not supported.
Instead change the require of /app/dist/packages/test/main.mjs to a dynamic import() which is available in all CommonJS modules.
    at Function.Module._load (/app/node_modules/@nrwl/node/src/executors/node/node-with-require-overrides.js:16:31)
    at Object.<anonymous> (/app/node_modules/@nrwl/node/src/executors/node/node-with-require-overrides.js:19:1)
```

### Environment
```
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : darwin x64
   npm  : 8.1.0
   
   nx : 14.1.7
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.7
   @nrwl/eslint-plugin-nx : 14.1.7
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.7
   @nrwl/js : 14.1.7
   @nrwl/linter : 14.1.7
   @nrwl/nest : 14.1.7
   @nrwl/next : Not Found
   @nrwl/node : 14.1.7
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.7
   typescript : 4.3.5
   rxjs : 7.2.0
   ---------------------------------------
   Community plugins:

```

**Comment by bulldog98** [comment] 2022-06-04 07:45
This is fixed by #10414

**Comment by jmattiace** [comment] 2022-06-16 17:44
I just confirmed that #10414 fixes the issue. Thanks @bulldog98! Do you have any idea when this will get merged in and released?

**Comment by bulldog98** [comment] 2022-06-16 19:50
@jmattiace no plan when it will be merged, I'm still waiting for a maintainer to run the test, after that it should be merged

**Comment by jmattiace** [comment] 2022-06-22 00:16
@KeithGillette the changes in #10414 fixed the issue for me. I would suggest using a debugger to ensure that the changes you made in the dependency file have in fact taken effect.

**Comment by KeithGillette** [comment] 2022-06-22 01:16
Thank, @jmattiace. It turns out the custom `webpack.config.js` was not being run because in step #4 the noted fields actually need to go into the `build.options` property (duh!). That change executed the modified `node-with-require-overrides.js` but still left me with a similar but different error:

`(node:52911) UnhandledPromiseRejectionWarning: ReferenceError: require is not defined in ES module scope, you can use import instead`

**Comment by omsharp** [comment] 2022-10-22 14:40
My whole project is halted because of this issue, and I've been seriously thinking of moving from NX to something else! Only the migration pain is what's holding me from pulling the trigger now. I'll probably just do it next couple of days, and move on!

**Comment by bulldog98** [comment] 2022-10-23 08:43
@omsharp you could patch the @nrwl/node module (it was moved in a later version of nx) where you just replace in src/executors/node/node-with-require-overrides.js the require with an import, that is a hotfix, until the nx team decides to introduce proper esm support

**Comment by omsharp** [comment] 2022-10-23 19:10
> @omsharp you could patch the @nrwl/node module (it was moved in a later version of nx) where you just replace in src/executors/node/node-with-require-overrides.js the require with an import, that is a hotfix, until the nx team decides to introduce proper esm support

I tried changing ` \node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js`  to use `dynamicImport`

Sadly, I'm still getting the same error! I'm not sure if I'm doing something wrong!

**Comment by omsharp** [comment] 2022-10-23 19:22
@bulldog98 
I tried changing ` \node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js` to use `dynamicImport` as in #10414 

Sadly, I'm still getting the same error! I'm not sure if I'm doing something wrong!

**Comment by bulldog98** [comment] 2022-10-24 05:27
oh you just have to write instead of `require` `import` in the js file, the problem why you can not do that in typescript, is because it import gets replaced by require with the settings of typescript nx uses.

**Comment by Tilesto** [comment] 2022-12-25 15:00
The same error for the bundle: Nest + Angular 15 + NG Universal.

Fully agree with it(( 
> My whole project is halted because of this issue, and I've been seriously thinking of moving from NX to something else! Only the migration pain is what's holding me from pulling the trigger now. I'll probably just do it next couple of days, and move on!

**Comment by sovcik** [comment] 2023-03-06 07:35
Well, the same issue here, but started appearing after I added package `get-folder-size` to the project. Removing it "fixed" the issue. Maybe you could use that package to reproduce the error.
Using NX 15.7.2, node 19.6

**Comment by B-R-Bender** [comment] 2023-03-17 14:39
same here with https://github.com/meetecho/janode

**Comment by arielweinberger** [comment] 2023-04-19 21:23
Still an issue.

**Closed** 2023-05-04 22:02 UTC
Labels: type: bug, scope: node
