### ISSUE TITLE
Angular 18.1 should default to prebundle:false in serve targets for vite builds (edit: maybe appShell related)

### ISSUE THREAD

**Issue by asgerjensen** [nrwl/nx#27294] opened 2024-08-05 12:50 UTC
### Current Behavior

system acts as if prebundle is true if not set, causing `nx serve` to fail.

### Expected Behavior

prebundle should be set to false as default option

### GitHub Repo

https://github.com/asgerjensen/nx-issue-27294.git

### Steps to Reproduce

1. Create angular application
2. use either @nx/angular:application or @angular-dev-kit/build-angular:application with associated serve target
3. add a dependecy to a commonjs module, add use of this in code (example `crypto-js`)
4. see that `nx build` works, but `nx serve` doesn't

### Nx Report

```shell
Node           : 20.11.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.2.4

nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/angular        : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nrwl/tao          : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.5.4
---------------------------------------
Community plugins:
@perpendicular/plugins-nx : 18.0.1
ng-mocks                  : 14.13.0
```

### Failure Logs

```shell
NX   Cannot find module '/Users/XXX/work/XXX/node_modules/crypto-js/lib-typedarrays' imported from /Users/XXX/work/XXX/.angular/prerender-root/31513cbc-18d0-4973-be87-9881b1f3d8e9/index.js

Did you mean to import crypto-js/lib-typedarrays.js?
Pass --verbose to see the stacktrace.
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

After upgrading from Angular 17/nx18, to Angular 18.1.3/nx19, i got in a weird situation where 
- `nx build` 
worked, and produced runnable assets

but

- `nx serve`

failed to start, complaining about imports not being correctly resolved. I'm unsure if this is related to those imports being commonJS or not.
```
The "allowedHosts" option will not be used because it is not supported by the "@angular-devkit/build-angular:application" builder.

 NX   Cannot find module '/Users/XXX/work/XXX/node_modules/crypto-js/lib-typedarrays' imported from /Users/XXX/work/XXX/.angular/prerender-root/31513cbc-18d0-4973-be87-9881b1f3d8e9/index.js

Did you mean to import crypto-js/lib-typedarrays.js?
Pass --verbose to see the stacktrace.
```

I was using the @angular-devkit/build-angular:dev-server , but changing to @nx/angular:dev-server gave same result

Anyways, after much trial and error, i found that

a) it started working again, if i rolled back to @angular-devkit/build-angular@^18.0 from ^18.1.
b) this commit https://github.com/angular/angular-cli/commit/940e382db27474dba6479f57e4ffefee04cfca66 talks about changing of some default behavior regarding vite prebundling. 

I then added `prebundle:false` to my serve target, and reverted back to the 18.1 version of `@angular-devkit/build-angular`, and `nx serve` started to work again.

NX Docs for prebundle mentions that angular/cli cache must also be enabled for this to work, but makes no indication on how to achieve this

**Comment by leosvelperez** [comment] 2024-08-05 13:44
Thanks for reporting this!

I tried reproducing the issue following the provided information, but I couldn't. Please provide a repo where the issue can be reproduced so we can troubleshoot it.

**Comment by asgerjensen** [comment] 2024-08-06 09:53
Reproduction repo:
https://github.com/asgerjensen/nx-issue-27294.git


In creating the reproduction, i actually found out, that it  was triggered by `appShell: true`. Without this, the error does not manifest.

**Comment by asgerjensen** [comment] 2024-08-09 07:39
@leosvelperez i'm unsure if i need to do something else to remove the `blocked` label. If so, please let me know

**Comment by leosvelperez** [comment] 2024-08-13 12:43
@asgerjensen this behavior can be reproduced in a plain Angular CLI repo, so it's not an issue introduced by Nx. You can see it at https://github.com/leosvelperez/issue-27294-ng-cli. If you were to generate the app shell using the `app-shell` generator, the configuration would be slightly different and the app would be served correctly. You can check the branch https://github.com/leosvelperez/issue-27294-ng-cli/tree/generate-app-shell to see that `appShell: true` is set on the `production` configuration of the `build` target instead of on the `build` target options.

Doing the same in an Nx repo would also work. Please note that Nx didn't generate that specific setting for you and that the error is thrown by the Angular CLI builder. The matching Nx executor also invokes the Angular CLI builder under the hood.

I'm closing this since it's either a misconfiguration (you manually set `appShell` in the `build` target options), or if you think that should be supported, you can create an issue on the Angular CLI repo.

**Closed by leosvelperez** 2024-08-13 12:43 UTC
Labels: type: bug, scope: angular
