### ISSUE TITLE
Running command with nx cli repeats outputs

### ISSUE THREAD

**Issue by bombillazo** [nrwl/nx#10702] opened 2022-06-10 22:54 UTC
## Current Behavior
When running some commands via the `nx` shortcuts, the output may be printed multiple times when the cli is on a waiting state or updating a status to the cli.

## Expected Behavior
The command line running the `nx` command acts as a normal cli command.

## Steps to Reproduce
1. Use `nx` to run cli command (in my case it was eas build cli).
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/44002321/173160079-9c5d61ff-bd93-4f5c-adda-8f72e7699f41.png">

### Failure Logs
N/A

### Environment
```
Node : 16.14.2
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.2.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.2.4
   @nrwl/detox : 14.2.4
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.2.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.2.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : 14.2.4
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
         @nrwl/expo: 14.2.3
```

**Comment by AgentEnder** [comment] 2022-06-11 05:27
Can you provide a reproduction repo for this so that we can troubleshoot? Thanks!

**Comment by bombillazo** [comment] 2022-06-12 02:26
Sure, here you go: https://github.com/bombillazo/nx-cli-bug

Running the command `nx eas-android` from the root and continue the prompt instructions. During the package upload and other steps, the command line starts repeating outputs making the output unreadable.

**Comment by xiongemi** [comment] 2023-03-31 21:59
closing this issue since i could not reproduce it locally.

**Closed** 2023-03-31 21:59 UTC
Labels: type: bug, scope: react-native
