### ISSUE TITLE
Watch mode not working when running @nx/webpack:webpack on target build

### ISSUE THREAD

**Issue by Lewis-software** [nrwl/nx#21807] opened 2024-02-14 04:04 UTC
### Current Behavior

If using a custom **_build_** target on a _project.json_ file, when running `nx run project:serve` you won't get hot reload on any file change in the project directory.

This is the build target I'm currently using:

```
"targets": {
    "build": {
      "executor": "@nx/webpack:webpack",
      "outputs": ["{options.outputPath}"],

      "options": {
        "main": "apps/project-main-dir/auth-api/src/main.ts",
        "webpackConfig": "apps/project-main-dir/auth-api/webpack.config.js",
        "outputPath": "dist/apps/project-main-dir/auth-api",
        "tsConfig": "apps/project-main-dir/auth-api/tsconfig.app.json",
        "assets": [
          "apps/project-main-dir/auth-api/src/assets",
        ],
        "generatePackageJson": true,
        "generateLockfile": true,
        "watch": true,
        "target": "node",
        "compiler": "tsc"
      },
      "configurations": {
        "production": {
          "optimization": true,
          "extractLicenses": true,
          "inspect": false
        }
      }
    },
```

And `webpack.config.js` is the one that comes with default when crating a project.

### Expected Behavior

Hot reload should work as expected, since it's not manually disabled.

### Steps to Reproduce

1. Create a new integrated workspace
2. Create a test project
3. On project.json add a custom build target like the one provided.
4. Launch `nx run test:serve `
5. Now the projects starts but with watch mode disabled.

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-arm64
   pnpm   : 8.15.2
   
   nx (global)        : 18.0.0
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/jest           : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/nest           : 18.0.4
   @nx/node           : 18.0.4
   @nx/web            : 18.0.4
   @nx/webpack        : 18.0.4
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JRafael91** [comment] 2024-03-09 07:15
I had the same problem, I had problems with file permissions.
Check the .nx/cache/d/daemon.log file for errors with the WATCHER and verify the cause.

```bash
[NX Daemon Server] - 2024-03-09T07:05:45.638Z - Started listening on: /tmp/5ac5adf7d2482042323aa/d.sock
[NX Daemon Server] - 2024-03-09T07:05:45.640Z - [WATCHER]: Subscribed to changes within: /<path> (native)
[NX Daemon Server] - 2024-03-09T07:05:45.648Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-03-09T07:05:45.650Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-03-09T07:05:45.652Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-03-09T07:05:45.653Z - [REQUEST]: Client Request for Project Graph Received
```

**Comment by poeck** [comment] 2024-05-08 14:51
> I had the same problem, I had problems with file permissions. Check the .nx/cache/d/daemon.log file for errors with the WATCHER and verify the cause.
> 
> ```shell
> [NX Daemon Server] - 2024-03-09T07:05:45.638Z - Started listening on: /tmp/5ac5adf7d2482042323aa/d.sock
> [NX Daemon Server] - 2024-03-09T07:05:45.640Z - [WATCHER]: Subscribed to changes within: /<path> (native)
> [NX Daemon Server] - 2024-03-09T07:05:45.648Z - Established a connection. Number of open connections: 1
> [NX Daemon Server] - 2024-03-09T07:05:45.650Z - Established a connection. Number of open connections: 2
> [NX Daemon Server] - 2024-03-09T07:05:45.652Z - Closed a connection. Number of open connections: 1
> [NX Daemon Server] - 2024-03-09T07:05:45.653Z - [REQUEST]: Client Request for Project Graph Received
> ```

@JRafael91 Have you solved the issue?

**Comment by poeck** [comment] 2024-05-08 17:26
What editor are you using? 

I was using vim which when writing a file, first deletes it to then recreate it. This caused nx to break.
Check if your editor does this as well and how you can disable it.

[Here](#22945) you can find a more detailed explanation

**Comment by poeck** [comment] 2024-05-13 04:51
Found the solution in #22945

**Comment by Coly010** [comment] 2024-05-13 08:23
Closing as duplicate of #22945

**Closed by Coly010** 2024-05-13 08:23 UTC
Labels: type: bug, scope: bundlers
