### ISSUE TITLE
Angular library generator doesn't use standaloneConfig

### ISSUE THREAD

**Issue by TheophileSketo** [nrwl/nx#6211] opened 2021-07-01 11:19 UTC
## Current Behavior

Generating a library with `nx generate @nrwl/angular:library --standaloneConfig` does not create a project.json in the library's directory but instead updates the root workspace.json with the library's configuration.

## Expected Behavior

`nx generate @nrwl/angular:library --standaloneConfig` should generate a library with project-specific configuration.

## Steps to Reproduce

`nx generate @nrwl/angular:library --standaloneConfig`

### Environment

@nrwl/angular : 12.5.0

**Comment by labeled** [comment] 2021-07-01 17:26
+1 I also am seeing this same behavior. I closed the other bug because it was a duplicate of this.

**Comment by FrozenPandaz** [comment] 2021-07-05 22:20
@AgentEnder Can you please take a look?

**Comment by AgentEnder** [comment] 2021-07-06 14:18
Looks like the flag got missed when merging in the swap to nx-devkit. I'll handle this in #6180 as it is touching the same files.

**Closed** 2021-07-14 17:49 UTC
Labels: scope: angular, type: bug
