### ISSUE TITLE
Angular Workspace: `cssUrl: "inline"` in ng-package.json is not respected

### ISSUE THREAD

**Issue by paulheising** [nrwl/nx#7795] opened 2021-11-18 18:31 UTC
## Current Behavior
I have an angular workspace that contains a library and an app, and in the library, the ng-package.json contains the `cssUrl: "inline"` flag, to replace things like `background-image: url(path/to/file.svg)` to an inline url with a data URL, like this: `background-image: url("data:image/svg.....")`

If I `nx build demo-lib` and look into the lib bundle, I see the URL was properly inlined.

But if I `nx build demo-app` (depends on `demo-lib`), and look inside the bundle, I see, the value of the `background-image` has not been inlined, it still contains the original file reference, salted with a hash. 

I suspect this is due to the fact, that per default, in the tsconfig.base.json, we get those library paths pointing to the index.ts of the librarie's *source* directory, so my guess is that nx would not use the built library at alll, but instead just consume the library directly from the source code, and therefore does not respect the special config in the ng-package.json from the library.

If I were to replace the tsconfig path from this: `"@my-demo/demo-lib": ["libs/demo-lib/src/index.ts"]` to `"@my-demo/demo-lib": ["dist/libs/demo-lib"]`, I verified that the app's bundle actually contains the inlined url, because then, when the app builds, it builds against the *previously* built lib, where inlining was done properly. Of course, changing the path to point to the dist directory, has some other disadvantages. You can't just `nx serve demo-app` any more, but would have to start an `nx build demo-lib --watch` first and then serve the app and if you change the lib, and forgot to run the `nx build demo-lib --watch`, it won't update automatically when you modifiy the lib during development. Additional scripting would be necessary to fix that.

So my idea to work around this issue was, trying to configure it in such a way, that for *development* builds, it would compile against `libs/demo-lib/src/index.ts`, and for *production* builds, it would compile against the built lib in the dist dir. Since nx automatically builds the lib before building the app, this would be optimal, because I could get the most comfortable way from `nx serve` and still build my prod app against the actual prod library. Unfortunately, I could not figure out a way to do so. I tried it with a `fileReplacement` in the angular.json, but that only seems to work for the source code, not for the tsconfig. 

But of course, all of this would not be necessary, if the `cssUrl: "inline"` in the ng-package.json would be respected. 

## Expected Behavior
I think I already covered that in my thoughts above. When I build the app, and the library it depends on has some special config like `cssUrl: "inline"`, I expect the compiler to respect that, no matter where it pulls the source code for my library from.

## Steps to Reproduce
Demo Repo to reproduce the issue: https://github.com/paulheising/nx-angular-lib-css-url-issue-demo

Find description of steps to reproduce in the readme.md

### Environment
```

  Node : 14.18.1
  OS   : linux x64
  npm  : 6.14.15
  
  nx : 13.1.4
  @nrwl/angular : 13.1.4
  @nrwl/cli : 13.1.4
  @nrwl/cypress : 13.1.4
  @nrwl/devkit : 13.1.4
  @nrwl/eslint-plugin-nx : 13.1.4
  @nrwl/express : Not Found
  @nrwl/jest : 13.1.4
  @nrwl/linter : 13.1.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.1.4
  @nrwl/web : Not Found
  @nrwl/workspace : 13.1.4
  @nrwl/storybook : 13.1.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

```

**Comment by leosvelperez** [comment] 2021-11-19 11:32
Thanks for reporting this!

The issue is that your application is using the Angular CLI builder `@angular-devkit/build-angular:browser`. That builder doesn't know about compiled libraries in the workspace, the Angular CLI has a different workflow than Nx.

If you want your application to take into account the already built libraries, you need to use the `@nrwl/angular:webpack-browser` executor for your application `build` target. That executor will pick the compiled output of built libraries instead of the source.

**Comment by leosvelperez** [comment] 2021-11-19 11:32
I'm going to close this issue. If you still have an issue after changing the executor, please feel free to reopen the issue.

**Closed by leosvelperez** 2021-11-19 11:32 UTC
Labels: type: bug, scope: angular

**Comment by paulheising** [comment] 2021-11-19 14:44
@leosvelperez Thanks a lot! That simple oneliner solved the issue I was trying to work around for hours :smile: 

Just a question: Is there any reason why `@nrwl/angular:webpack-browser` is not the default executor for app build targets when using nx? I generated the app with the corresponding nx generator (`ng generate @nrwl/angular:application`) so now that I ack'd the existence of that executor, my first thought is that this should be default when generating via nx.

Or are there any drawbacks / disadvantages when using it compared to the default angular executor?

**Comment by leosvelperez** [comment] 2021-11-19 15:03
@paulheising it's not the default because that executor was thought for the incremental builds scenario. It has some additional overhead to re-route dependencies on the fly to the compiled outputs. Not every application uses buildable/publishable libraries, so they don't need to pay the price by default. Incremental builds setup is not for every application and generally would fit better medium to large applications.

**Comment by paulheising** [comment] 2021-11-19 15:16
@leosvelperez Thanks for pointing that out. I see. 

I was just looking through the docs to see, if I could configure the default app builder for my workspace (potentially somewhere in nx.json). But from what I see, this is not possible correct?

Also I wonder if it would be a good idea if it was possible to preselect the builder when invoking the angular application generator. So when I use NxConsole to invoke the generator, I would have a field for that and I'd be reminded to think about, which executor I want to use for building my app. Was this ever considered?

**Comment by leosvelperez** [comment] 2021-11-19 15:58
>I was just looking through the docs to see, if I could configure the default app builder for my workspace (potentially somewhere in nx.json). But from what I see, this is not possible correct?

That's correct, It's not possible.

>Also I wonder if it would be a good idea if it was possible to preselect the builder when invoking the angular application generator. So when I use NxConsole to invoke the generator, I would have a field for that and I'd be reminded to think about, which executor I want to use for building my app. Was this ever considered?

This hasn't been considered as far as I'm aware.
