### ISSUE TITLE
NX / Angular unable to generate scss for components inside library

### ISSUE THREAD

**Issue by timververs-ihomer** [nrwl/nx#11137] opened 2022-07-14 11:33 UTC
## Current Behavior

When using nx version 14.4.x or higher with the commands provided in the reproduce steps (even in a fresh workspace), it won't generate the selected style sheet.

## Expected Behavior

That the css files are in .scss format, this is reflected in the nx.json in the generate section
`"@nrwl/angular:component": {
      "style": "scss"
    }`

## Steps to Reproduce

`npx create-nx-workspace@latest --preset=angular`
Workspace name: myorg
Application name: todos
Default stylesheet format: scss

`npx nx g @nrwl/angular:lib ui`
`npx nx g component button --project=ui --export`

It will generate a default .css file instead of the selected .scss file.

### Environment

```
   Node : 16.13.1
   OS   : win32 x64
   npm  : 8.14.0

   nx : 14.4.2
   @nrwl/angular : 14.4.2
   @nrwl/cypress : 14.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.2
   @nrwl/eslint-plugin-nx : 14.4.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.4.2
   @nrwl/js : 14.4.2
   @nrwl/linter : 14.4.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.4.2
   @nrwl/web : 14.4.2
   @nrwl/workspace : 14.4.2
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:

```

**Comment by leosvelperez** [comment] 2022-07-14 12:57
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/11004. Please note that the issue was already fixed in https://github.com/nrwl/nx/pull/11006 and should be released soon. Keep an eye on the releases to get the fix.

**Closed by leosvelperez** 2022-07-14 12:57 UTC
Labels: type: bug, scope: angular
