### ISSUE TITLE
react-native localhost fetching api not working

### ISSUE THREAD

**Issue by victorrik** [nrwl/nx#11481] opened 2022-08-05 23:55 UTC
i use the steps for react **[native applications](https://nx.dev/guides/react-native)** and try to use axios to make the petitions on my localhost server and always throws error connections and i using the ip of my computer

i'm using firebase functions emulator for the backend 

this is how my functions looks
![carbon](https://user-images.githubusercontent.com/15133959/183224182-d0e1e4ba-896c-4506-a86e-fc07b08ad082.png)

And this is de code that i use to make de petition in both applications
![carbon (1)](https://user-images.githubusercontent.com/15133959/183224294-4e1436c1-3a8b-40ef-8497-c1d06dc3fe24.png)

this is what i got and expected on the application with **[npx react-native init AwesomeProject](https://reactnative.dev/docs/environment-setup)** 
![Screen Shot 2022-08-05 at 18 39 25](https://user-images.githubusercontent.com/15133959/183224382-9dcf4261-2fd6-411b-971e-1f24bd72dcea.png)

this is what i got with the application with nx
![Screen Shot 2022-08-05 at 18 38 09](https://user-images.githubusercontent.com/15133959/183224424-88d5a274-e89a-4cce-9630-47e529ddd9fd.png)

Computer: Mac mini M1
Mobile: Samsung Galaxy S10e
Dependecies : 
@nrwl/next: 14.5.2
@nrwl/react-native: 14.5.2
@nrwl/workspace: 14.5.2
@react-native-firebase/app": ^15.2.0
@react-native-firebase/functions": ^15.2.0
axios": ^0.27.2

**Comment by xiongemi** [comment] 2022-08-17 18:35
@victorrik i think it might be related to this issue: https://stackoverflow.com/questions/38418998/react-native-fetch-network-request-failed.

you need to add your api url to Info.plist and add request URL to NSExceptionDomains under NSAppTransportSecurity for ios, like:
```
<key>NSAppTransportSecurity</key>  
 <dict>  
  <key>NSExceptionDomains</key>  
  <dict>  
   <key>localhost</key>  
   <dict>  
    <key>NSExceptionAllowsInsecureHTTPLoads</key>  
    <true/>  
   </dict>  
   <key>192.168.100.37</key>  
   <dict>  
    <key>NSExceptionAllowsInsecureHTTPLoads</key>  
    <true/>  
   </dict>
  </dict>  
 </dict>
```

for android, you might need to change /android/app/src/main/res/xml/network_security_config.xml, and add the request URL to this config file:
```
<?xml version="1.0" encoding="utf-8"?>  
<network-security-config>  
    <domain-config cleartextTrafficPermitted="true">  
        <domain includeSubdomains="true">10.0.2.2</domain>  
        <domain includeSubdomains="true">localhost</domain>  
        <domain includeSubdomains="true">NSExceptionAllowsInsecureHTTPLoads</domain>  
    </domain-config>  
</network-security-config>
```

closing this issue since it is not a bug.

**Closed by xiongemi** 2022-08-17 18:35 UTC
Labels: type: bug, scope: react-native
