### ISSUE TITLE
Error while creating pruned lockfile

### ISSUE THREAD

**Issue by pvorona** [nrwl/nx#17816] opened 2023-06-27 11:38 UTC
### Current Behavior

When building the project with `@nx/webpack:webpack` executor and `"generatePackageJson": true` option error is thrown:
<img width="1355" alt="Screenshot 2023-06-27 at 14 33 34" src="https://github.com/nrwl/nx/assets/11915087/5a5271db-f3ff-44ac-8a66-75a13248d8c8">

### Expected Behavior

No error is thrown

### Steps to Reproduce

1.

### Nx Report

```shell
$ /Users/pavelvorona/Projects/DappBack/dappback/node_modules/.bin/nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/node           : 16.4.0
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/vite           : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   	 @dappback/common-client
   	 @dappback/common
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/node@16.4.0
     - @nrwl/node@16.4.0
   
   To fix this, run `nx migrate nx@16.4.0`

✨  Done in 1.08s.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I added debug logs to `yarn-parser.js:244:47` to see what causes the error and it looks like the package `string-width-cjs` is not available in the `existingKeys` map. Listing out all the keys shows that there is a key `string-width` (without `-cjs` postfix).
Running `npm ls` shows that `firebase-tools` depend on this package.
<img width="531" alt="Screenshot 2023-06-27 at 14 36 05" src="https://github.com/nrwl/nx/assets/11915087/9958e25d-5cf2-4365-b3bb-55e9882019f6">
A lot of other packages depend on `string-width` (without `-cjs`)
<img width="611" alt="Screenshot 2023-06-27 at 14 43 19" src="https://github.com/nrwl/nx/assets/11915087/ea2356d9-4d1c-45b6-a5e0-a5928d28965d">

**Comment by cwoebker** [comment] 2023-06-27 12:19
@pvorona This is already reported and discussed here #17440 and here #17329 I believe.

**Comment by meeroslav** [comment] 2023-06-29 11:40
Closing as duplicate of #17440

**Closed by meeroslav** 2023-06-29 11:40 UTC
Labels: type: bug, scope: js
