### ISSUE TITLE
DTE doesn't respect app defined environment variables

### ISSUE THREAD

**Issue by Bielik20** [nrwl/nx#18565] opened 2023-08-10 11:31 UTC
### Current Behavior

Let say we have application `my-api`. It has configuration named `stg`. Our repository looks like:

* apps
  * my-api
    * `.env.stg`
* `.env.stg`

`{workspaceRoot}/.env.stg`

> STAGE=root

`{workspaceRoot}/apps/my-api/.env.stg`

> STAGE=app

When running `npx nx affected -t deploy`:

* on my local machine: deploy is run with `STAGE=app` ✅ 
* on gh actions using Nx Cloud DTE: deploy is run with `STAGE=root` ❌ 

### Expected Behavior

Running `npx nx affected -t deploy` on gh actions using Nx Cloud DTE should result in: deploy is run with `STAGE=app` ✅ 

### Steps to Reproduce

1. create target with configuration `stg` that uses `STAGE` env variable (like echo)
2. create `.env.stg` files in repository root and app root with `STAGE` env variable
3. run target on gh actions using DTE

### Nx Report

```shell
Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 8.19.4

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 15.7.2
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
   ---------------------------------------
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Bielik20** [comment] 2023-09-11 14:09
Still an issue. Main job (controller) does recognise correct .env but agents do not.

```
    "nx-cloud": "16.4.0",
```

**Comment by StalkAltan** [comment] 2023-09-11 14:13
Hi @Bielik20 sorry for the delay on this, I will take a look this week.

**Comment by StalkAltan** [comment] 2023-09-15 20:36
Hi again @Bielik20, we've found the root cause here. This should be resolved with 16.5.0, but that will have to coincide with a release of our services. That should come sometime next week, and I'll keep this issue up to date with the status of that.

**Comment by gabriel-calin-lazar** [comment] 2023-09-22 12:42
when would this land in a specific release ?

**Comment by Bielik20** [comment] 2023-10-17 13:10
Problem still persists:

```
   nx-cloud           : 16.5.2
```

Did test it using `run-many`.

**Comment by StalkAltan** [comment] 2023-10-17 13:44
Hey @gabriel-calin-lazar / @Bielik20 apologies again. This will be resolved today.

**Comment by StalkAltan** [comment] 2023-10-17 14:33
This has been fixed. You can find a test repository here: https://github.com/StalkAltan/agent-env

If you are already on nx-cloud@16.5.2, you should be able to run `nx reset` and have this start working. This would not be needed in a CI environment.

If `nx reset` does not work, you can run a single command with `NX_CLOUD_FORCE_REVALIDATE=true` and that should resolve the problem.

Thank you for the patience here.

**Closed by StalkAltan** 2023-10-17 14:33 UTC
Labels: type: bug, scope: nx-cloud
