### ISSUE TITLE
The "@nx/jest/plugin" plugin threw an error while creating nodes from client-app/jest.config.ts:

### ISSUE THREAD

**Issue by listepo** [nrwl/nx#22591] opened 2024-03-31 12:18 UTC
### Current Behavior

The "@nx/jest/plugin" plugin threw an error while creating nodes from client-app/jest.config.ts
<img width="817" alt="Screenshot 2024-03-31 at 15 12 48" src="https://github.com/nrwl/nx/assets/2510800/3636c79a-4aa6-4d79-b4e9-b2e2d2982314">
<img width="446" alt="Screenshot 2024-03-31 at 15 13 16" src="https://github.com/nrwl/nx/assets/2510800/36d41f04-3580-4025-810b-f514dbbd474a">

### Expected Behavior

<img width="260" alt="Screenshot 2024-03-31 at 15 14 11" src="https://github.com/nrwl/nx/assets/2510800/aceab563-8627-4b2e-b91b-ea7a330d0e5d">
but I have new error 
<img width="792" alt="Screenshot 2024-03-31 at 15 15 17" src="https://github.com/nrwl/nx/assets/2510800/3aaa5352-beee-4356-9abc-bc8a53525766">

### Steps to Reproduce

1. Create empty workspace
2. Add RN plugin
3. run ios or android

### Nx Report

```shell
nx (global)        : 18.2.1
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/react          : 18.2.1
@nx/react-native   : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by listepo** [comment] 2024-03-31 12:37
// displayName: 'client-app'
slove the problem

**Comment by FrozenPandaz** [comment] 2024-04-02 16:32
Duplicate of https://github.com/nrwl/nx/issues/22478. Follow there for updates.

**Closed by FrozenPandaz** 2024-04-02 16:32 UTC
Labels: type: bug
