### ISSUE TITLE
serve command: double processing in CLI 12 > Browser application bundle generation complete.

### ISSUE THREAD

**Issue by mlc-mlapis** [nrwl/nx#5699] opened 2021-05-18 11:18 UTC
## Current Behavior

Each command ng serve or nx run myapp:serve leads to the situation that it looks like double processing:

Build at: 2021-05-15T18:26:37.746Z - Hash: ecbd21f6a2b7772c6755 - Time: 154931ms
Build at: 2021-05-15T18:27:00.757Z - Hash: cf1562cbbca533d796f4 - Time: 10838ms

It's unclear what it means. It seems that the same doesn't happen with an incremental build. It looks like something modifies a file (like packages.json, angular.json or nx.json, ...) in an insignificant way and together with Webpack 5 it leads to the repeated generation.

## Expected Behavior

Only one browser application bundle generation.

Yes, it works correctly in the context of Angular CLI 11.2.x, even together with Nx CLI 12.3.3.

## Steps to Reproduce

Each project under Nx environment.
https://github.com/angular/angular-cli/issues/20809

### Failure Logs

<pre><code>
✔ Browser application bundle generation complete.

Initial Chunk Files     | Names         |      Size
main.js                 | main          |  41.70 MB
vendor.js               | vendor        |   8.27 MB
polyfills.js            | polyfills     | 584.27 kB
styles.css, styles.js   | styles        | 448.95 kB
scripts.js              | scripts       |  83.67 kB
runtime.js              | runtime       |  11.83 kB

                        | Initial Total |  51.07 MB

Lazy Chunk Files ... 23 lazy-loaded modules

Build at: 2021-05-15T18:26:37.746Z - Hash: ecbd21f6a2b7772c6755 - Time: 154931ms
** Angular Live Development Server is listening on localhost:1111, open your browser on http://localhost:1111/ **
√ Compiled successfully.

✔ Browser application bundle generation complete.
29 unchanged chunks
Build at: 2021-05-15T18:27:00.757Z - Hash: cf1562cbbca533d796f4 - Time: 10838ms
√ Compiled successfully.
</code></pre>

### Environment
<pre><code>
Angular CLI: 12.0.0
Nx CLI: 12.3.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser       
... platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------    
@angular-devkit/architect        0.1200.0
@angular-devkit/architect-cli    0.1200.0
@angular-devkit/build-angular    12.0.0
@angular-devkit/core             12.0.0
@angular-devkit/schematics       12.0.0
@angular-devkit/schematics-cli   12.0.0
@schematics/angular              12.0.0
rxjs                             6.6.7
typescript                       4.2.4
</code></pre>

**Comment by samartomar** [comment] 2021-05-19 04:12
I am facing the same issue too, i was thinking this is being caused by Tailwind configuration in NX but +1 from me.

**Comment by mlc-mlapis** [comment] 2021-05-19 08:08
We don't use Tailwind at all.

**Comment by leosvelperez** [comment] 2021-05-19 08:58
@mlc-mlapis thanks for reporting this!

I tried to reproduce this by creating an Angular workspace but I didn't get the issue. It does happen to me in an Angular CLI project due to ngcc running prior to the serve command and modifying files. In the linked Angular CLI issue you are sharing you mention it happens all the time, regardless of ngcc running or not, but I'm not able to reproduce it.

Could you please share a minimal repo where the issue can be reproduced?

**Comment by mlc-mlapis** [comment] 2021-05-19 09:42
@leosvelperez I would like to do it. Actually, the same happens in 3 different projects where each of them is located in a different Nx monorepo. That's why it seems to be a repeated behavior pattern and not a unique exception. I guess that it's somehow related to the Webpack 5 change detection mechanism, but it's a question of what invokes such a dummy change.

**Comment by mlc-mlapis** [comment] 2021-05-19 09:55
@leosvelperez I can share one private project on GitHub with you, so you can run it and see. Is it acceptable for you?

**Comment by leosvelperez** [comment] 2021-05-19 09:58
@mlc-mlapis sure, that would help.

**Comment by mlc-mlapis** [comment] 2021-05-19 10:02
@leosvelperez OK. I have to do some manual steps related to that project migration to v12 first because `nx migrate latest` didn't work as expected, so let a day or two.

**Comment by mlc-mlapis** [comment] 2021-05-20 22:38
@leosvelperez I invited you to the repository where the above problem can be seen.

* Create a local clone of it with `m-kbase` name.
* Use `ML-Upgrade-to-Angular&CLI-V12` branch.
* Run `npm i`.
* It's supposed that there is a global Nx installation of 12.3.4.
* Run `nx serve`.

And this should be a result. The highlighted part in yellow is the problem.
![image](https://user-images.githubusercontent.com/5693835/119057270-73ab3880-b9cc-11eb-9f50-f6c956e33391.png)

**Comment by leosvelperez** [comment] 2021-05-21 12:42
@mlc-mlapis thanks for sharing it! Unfortunately, I can't reproduce the issue there either. I wonder if it has something to do with the OS, I'm using MacOS and I see in the description of the issue you're using Windows 🤷🏻 

![image](https://user-images.githubusercontent.com/12051310/119138881-49905f80-ba3a-11eb-9009-355f141cec82.png)

**Comment by mlc-mlapis** [comment] 2021-05-21 14:32
@leosvelperez Yep, it's on the Windows platform. Any chance you can take a try on Windows somewhere?

**Comment by mlc-mlapis** [comment] 2021-05-21 14:32
@leosvelperez And on NodeJS 14.17.0.

**Comment by leosvelperez** [comment] 2021-05-26 08:39
@mlc-mlapis I'm sorry, I've been busy with other tasks. As soon as I have some time, I'll see if I can reproduce it in a Windows env.

**Comment by mlc-mlapis** [comment] 2021-05-26 09:26
@leosvelperez OK, thanks. Do you think it has more sense to report this with the same reproduction project on the Angular CLI repo. I did it already, but as expected, it was closed because I didn't have that reproduction project at that time.

**Comment by leosvelperez** [comment] 2021-05-26 09:30
If you can reproduce it in a project without Nx, then it's not an Nx issue and it should be addressed by the Angular CLI team.

**Comment by mlc-mlapis** [comment] 2021-05-26 09:32
@leosvelperez Sure, but I don't know it at this time.

**Comment by mlc-mlapis** [comment] 2021-05-26 11:54
@leosvelperez It would be nice of you to do the basic test of the reproduction demo on the Windows platform. It would be the confirmation that it's a general problem, at least. Also, it's probably relatively easy for you to check what files are detected as dummy changed ones.

**Comment by mlc-mlapis** [comment] 2021-06-02 22:20
@leosvelperez I have great news. The problem was identified and already solved in CLI 12.0.2. It wasn't related to Nx at all.

https://github.com/angular/angular-cli/issues/20809

**Closed** 2021-06-02 22:21 UTC
Labels: blocked: repro needed, scope: angular, type: bug
