### ISSUE TITLE
Custom Builder — Cannot find module '@my-org/webpack-builder/package.json'

### ISSUE THREAD

**Issue by Kundin** [nrwl/nx#3395] opened 2020-07-24 08:51 UTC
I created @nrwl/nx-plugin `webpack-builder` and try to use it for my application. 

```JSON
workspace.json

"projects": {
    "website": {
      ...
      "architect": {
        "build": {
          "builder": "@my-org/webpack-builder:build"
          ...
        }
      }
    }
}
```

But, when i run command `nx run website:build` then receive error `Cannot find module '@my-org/webpack-builder/package.json'`

If build webpack-builder and use full path to folder in workspace.json (i.e. `./dist/libs/webpack-builder:build`) that works correctly.

What i do wrong?

**Comment by FrozenPandaz** [comment] 2020-07-24 22:05
I think there might be some confusion here.

`@nrwl/nx-plugin`s are intended to be published and used outside of the repo they are written in.

Building `webpack-builder` and using the full path in `workspace.json` is a legitimate workaround that works as intended if that is a suitable workaround for you.

Thus, I don't think there is any unintentional behavior here. I'm going to close this issue as it doesn't seem like a bug to me.

We can however, consider resolving `@my-org/webpack-builder` to the source code. Though I'm not sure at this point how that would look like. If that sounds like a good idea, would you mind opening an issue describing how you expect that feature to work?

**Closed by FrozenPandaz** 2020-07-24 22:05 UTC
Labels: type: bug
