### ISSUE TITLE
@nrwl/workspace:move schematics on Angular library does not update path

### ISSUE THREAD

**Issue by Jad31** [nrwl/nx#8952] opened 2022-02-13 17:54 UTC
## Current Behavior
Using the schematics `@nrwl/workspace:move` does not update the "dest" path of the library in `ng-package.json`.

## Expected Behavior
I want the schematics to update the "dest" path in `ng-package.json`.

## Steps to Reproduce

- Create a workspace: `npx create-nx-workspace@latest --preset=apps --name=workspace --nx-cloud=no --packageManager=yarn`

- Add Angular to the workspace: `yarn add -D @nrwl/angular:library`

- Create an Angular library: `yarn run nx generate @nrwl/angular:library --name=my-lib --routing=true --buildable=true --strict=true importPath=@workspace/my-lib`

- Use the schematics: `yarn run nx generate @nrwl/workspace:move --project my-lib new-directory-my-lib --destination=new/directory/my-lib --importPath==@workspace/new-directory-my-lib`

You will see that the "dest" path in `ng-package.json` was not updated.

### Environment
```bash
> yarn run nx report

yarn run v1.22.17
 >  NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.8.1
   @nrwl/angular : 13.8.1
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : undefined
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : undefined
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
         @angular/cli: 10.0.2

✨  Done in 0.62s.
```

**Comment by leosvelperez** [comment] 2022-02-14 10:35
Thanks for reporting this!

Please note that for Angular projects you need to use the `@nrwl/angular:move` generator instead. Angular has specific configurations and files that are not handled by the generic `@nrwl/workspace:move` generator.

I'm closing this since the `@nrwl/workspace:move` is not intended to be used with Angular projects and the `@nrwl/angular:move` generator works as intended. I created a [PR updating the docs](https://github.com/nrwl/nx/pull/8959) to advise using this generator for Angular projects.

**Closed by leosvelperez** 2022-02-14 10:35 UTC
Labels: type: bug
