### ISSUE TITLE
Building a React project in production loads the wrong environment variables

### ISSUE THREAD

**Issue by cereallarceny** [nrwl/nx#4420] opened 2021-01-01 14:46 UTC
## Current Behavior
When building a @nrwl/react app in production mode (`nx build XXX --prod`), the development environment variables (`.local.env`) are loaded in addition to the production environment variables (`.env`) and thus, the production variables are overwritten.

## Expected Behavior
When building a @nrwl/react app in production mode (`nx build XXX --prod`), I expect only the production variables to be included in the build.

## Steps to Reproduce
1. Create a @nrwl/react app
2. Create a `.env` file with some production variables inside
3. Create a `.local.env` file with some development variables (with same key names as the one in the `.env` file inside
4. Run `nx build XXX` and notice that only development variables are included - _this IS the intended behavior_
5. Run `nx build XXX --prod` and notice that only development variables are included - _this is NOT the intended behavior_

### Environment
  Node : 12.19.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.0.18
  @nrwl/cypress : 11.0.18
  @nrwl/devkit : 11.0.18
  @nrwl/eslint-plugin-nx : 11.0.18
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.18
  @nrwl/linter : 11.0.18
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.0.18
  @nrwl/react : 11.0.18
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.18
  @nrwl/web : 11.0.18
  @nrwl/workspace : 11.0.18
  typescript : 4.0.5

I also have the NX CLI installed to version 11.0.18, but I don't believe it was captured in the environment report above.

**Comment by jaysoo** [comment] 2021-01-11 15:31
Hi @cereallarceny, the intention of the `.local.env` file is that it isn't checked into the repo. It's use case is to allow devs to override certain environment variables to fit their use cases.

Thus, I think the best way to address this issue is to:
1. Add `.local.env`  file to `.gitignore`
2. Remove from git repo (if it has been added  previously)
3. Then when you need to use production values, you can comment out the file entirely or pull in the values you need

Does that make sense?

**Comment by jaysoo** [comment] 2021-01-11 16:11
Going to close this one because I don't think we need to special case the `production`  configuration, but let me know if you are still having problems.

**Closed by jaysoo** 2021-01-11 16:11 UTC
Labels: scope: react, type: bug

**Comment by cereallarceny** [comment] 2021-01-13 20:21
@jaysoo I think you might misunderstand the problem though. 

> When building a @nrwl/react app in production mode (nx build XXX --prod), the development environment variables (.local.env) are loaded in addition to the production environment variables (.env) and thus, the production variables are overwritten.

What I mean here is that if there is ANY file named `.local.env` in your project, those variables will take preference over the variables in `.env`. I can understand that `.local.env` variables should not be considered in a build, but you also shouldn't have to comment them out every time you run a build either. All my PR is trying to do is to ensure that the overwriting process never happens. **I'm not changing your desired functionality - just trying to protect users against making a common mistake.** I believe my PR does that in a way that's as minimally invasive as possible - would you please consider re-reading the PR again?

**Comment by nuno-mrks** [comment] 2021-02-04 15:28
@jaysoo, I'm currently facing a similar issue.
I'm configuring TailwindCSS (and its purge features) on my shared libs folder and for that reason I can't use my application's (Angular) `environment.ts` replacement file to only perform purging actions on production builds (`--prod`).
My application's `.env` file has a `PRODUCTION=true` entry, and my `.local.env` has `PRODUCTION=false`.
For some reason, `local.env` value is always taking precedence over `.env` and so, I never have `PRODUCTION` value set as `true`. That only happens when I remove the `.local.env` file.
I believe @cereallarceny's PR is intended to cover cases just like this.

**Comment by cereallarceny** [comment] 2021-02-04 16:37
Could we at least reconsider opening this @jaysoo?

**Comment by TheMeteoRain** [comment] 2021-07-06 04:53
I have similar problem where my `yarn build XXX --prod` only detects `.env` file and doesn't read `.env.production`.

I think they should function pretty much as described here: https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

**Comment by dukex** [comment] 2022-03-03 01:44
Same problem here, the @TheMeteoRain link has a good description about the expected behavior

**Comment by zanona** [comment] 2022-03-21 09:35
Please reconsider this as it'd be really useful for deployments outside sandboxed CI environments where `.env.local` is available but should be ignored for production commands.

**Comment by pjw9963** [comment] 2022-06-01 12:54
I agree with the above sentiment. There is value in having separate env values for production and development environments. Adding and removing a local.env file every time I need a production build feels like a hack

**Comment by Elyahou** [comment] 2022-07-14 15:00
I agree, there is a value with checking in the `.local.env` file, to get every developper the same env when working locally, but we still need a way to not use it when running in CI or production...

**Comment by igor-q-bio** [comment] 2022-07-20 23:14
Create-react-app is doing it in a way more flexible and convenient way: https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used

This should be considered as a way to go

**Comment by unrealsolver** [comment] 2022-09-12 10:33
@jaysoo I would also ask to reopen that issue.
I have both .env and .local.env. Sometimes I have to use manual deploys with e.g. `nx run app:deploy:production`. In this case I want to ignore `.local.env` and use my `.env` (or .env.production`)
Currently, I have to remove .local.env and then restore it. It just makes no sense

**Comment by dangerdespain** [comment] 2022-11-04 19:51
@jaysoo +1 here as well for reconsidering this issue. I bumped into this during my workweek as well.. our CI pipeline broke and it took me a while to figure out that .env.local variables were being injected into our NextJS dist output during the build step. The ability to exclude .env.local during production builds via configuration would be very useful here.
