### ISSUE TITLE
project creation with number causes error

### ISSUE THREAD

**Issue by zackarychapple** [nrwl/nx#2020] opened 2019-11-01 21:24 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Cannot create new nx workspace if the name of the workspace is a number.

## Current Behavior

Creating an angular application via `npx create-nx-workspace@latest 2020` does not complete creation due to error below. 

## Failure Information (for bugs)

```Schematic input does not validate against the Schema: {"name":"ng-atlanta2020","inlineStyle":false,"inlineTemplate":false,"prefix":"2020","skipTests":false,"style":"scss","enableIvy":false,"routing":false,"skipInstall":true,"skipPackageJson":false}
Errors:

  Data path ".prefix" should match format "html-selector".
Workspace creation failed, see above.
(node:50459) UnhandledPromiseRejectionWarning: Error: Command failed: "/var/folders/0m/fg82x83s0z111z5g4281x6lw2jsx0b/T/tmp-50459Fiaz8tPw3meU/node_modules/.bin/ng" new 2020 --preset="angular" --appName="ngAtlanta2020" --style="scss" --collection=@nrwl/workspace
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at createApp (/Users/zackaryc/.npm/_npx/50459/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:356:21)
    at /Users/zackaryc/.npm/_npx/50459/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:50459) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50459) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run `npx create-nx-workspace@latest 2020`
2. select `angular`
3. select `sass`
4. Error occurs

**Comment by FrozenPandaz** [comment] 2019-11-01 21:31
Hi @zackarychapple,

Workspace names cannot start with a `number` among other restrictions:
https://github.com/angular/angular-cli/blob/29b1533fa9a4d84f0b16592ddce276785c60ebd5/packages/angular_devkit/schematics/src/formats/html-selector_spec.ts#L35

Perhaps `my-project-2020` would be a better project name?

Closing this issue as it is intended behavior.

**Closed by FrozenPandaz** 2019-11-01 21:31 UTC

**Comment by zackarychapple** [comment] 2019-11-02 13:39
Thank you for the explanation @FrozenPandaz. Would mind if I switch this to an enhancement request to ask that the CLI give an error message when someone tries to use a number rather than continuing to try the build then bombing out with an error?
