### ISSUE TITLE
Ability to run @nrwl/angular executors in verbose mode

### ISSUE THREAD

**Issue by ChazUK** [nrwl/nx#7612] opened 2021-11-04 16:01 UTC
## Description
Sometimes there's a need to run executors in verbose mode to get the full log information for debugging. It would be great if this could be added to the options portion of a target.

## Suggested Implementation
```json
  "targets": {
    "build": {
      "executor": "@nrwl/angular:package",
      "outputs": [
        "dist/libs/angular-package"
      ],
      "options": {
        "project": "libs/angular-package/ng-package.json",
        "verbose": true
      },
```

## Alternate Implementations
Catch `--verbose` flag from cli

**Comment by Coly010** [comment] 2022-01-17 10:29
Essentially a duplicate of https://github.com/nrwl/nx/issues/7451

Closing so that we can track in one place.

**Closed by Coly010** 2022-01-17 10:29 UTC
Labels: type: feature, scope: angular
