### ISSUE TITLE
Build Failure with Nx 18 and @nx/next:build Executor When Next.js Outputs Warnings

### ISSUE THREAD

**Issue by KentoMoriwaki** [nrwl/nx#22295] opened 2024-03-13 07:00 UTC
### Current Behavior

After upgrading my NX application to version 18, I encountered a bug that prevents building a Next.js app when Next.js build process outputs any warnings and the @nx/next:build executor is used instead of Inferred Tasks. The build process fails with a syntax error due to an unexpected end of JSON input.

### Expected Behavior

The build process should complete successfully, even when Next.js outputs warnings, regardless of whether @nx/next:build executor or Inferred Tasks are used.

### GitHub Repo

https://github.com/KentoMoriwaki/nx-next-build-bug

### Steps to Reproduce

1. Clone the repository.
1. Run pnpm i to install dependencies.
1. Execute pnpm nx run myapp:build to build the application.

The build will fail with an error similar to the one shown below:

```
❯ nx run myapp:build    

> nx run myapp:build:production

   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · outputFileTracingRoot

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Skipping linting
 ✓ Checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/6)  [=   ]undefined:1

SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at parseChannelMessages (node:internal/child_process/serialization:152:15)
    at parseChannelMessages.next (<anonymous>)
    at channel.onread (node:internal/child_process:624:18)

Node.js v20.10.0

```

Switching to Inferred Tasks by modifying apps/myapp/project.json resolved the issue for this project. However, it was challenging to identify this as the cause, and such errors are unexpected.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.10.0
OS     : darwin-arm64
pnpm   : 8.11.0

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/jest           : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/cypress        : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/next           : 18.0.8
@nx/playwright     : 18.0.8
@nx/react          : 18.0.8
@nx/storybook      : 18.0.8
@nrwl/tao          : 18.0.8
@nx/web            : 18.0.8
@nx/webpack        : 18.0.8
typescript         : 5.3.3
```

### Failure Logs

```shell
❯ nx run myapp:build    

> nx run myapp:build:production

   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · outputFileTracingRoot

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Skipping linting
 ✓ Checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/6)  [=   ]undefined:1

SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at parseChannelMessages (node:internal/child_process/serialization:152:15)
    at parseChannelMessages.next (<anonymous>)
    at channel.onread (node:internal/child_process:624:18)

Node.js v20.10.0
```

### Package Manager Version

8.11.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This issue might not affect all NX + Next.js projects, but it could pose significant obstacles for those it does affect, especially due to the difficulty in diagnosing the problem. Reporting this issue to help improve the tooling for future releases and assist others who might encounter the same problem.

**Comment by ShadiBlitz** [comment] 2024-03-13 08:04
Duplicate of https://github.com/nrwl/nx/issues/22270

**Comment by ndcunningham** [comment] 2024-08-19 21:37
Issue should be fixed. Update your Nx version to have the changes!

**Closed by ndcunningham** 2024-08-19 21:37 UTC
Labels: type: bug, scope: nextjs
