### ISSUE TITLE
Error: Some of the library <YOUR LIBRARY> dependencies have not been built yet. Please build these libraries before: -testing

### ISSUE THREAD

**Issue by egdraper** [nrwl/nx#2463] opened 2020-02-11 00:16 UTC
We are getting this error: 
`Error: Some of the library "my-library" dependencies have not been built yet. Please build these libraries before: -testing`

We have just upgraded to Angular 8 and are having an issue with our build.

We have two libraries generated by the Nrwl schematics (in Angular 7) within the same project. They are "my-library" and "testing". 

"testing" is a library that contains nothing but **stubs** for Angular components that exist in "my-library". We build this library separate and place the build files in "my-library's" distribution folder. This is so we can have the following pattern in our other applications.
 ```
    import { myComponent } from "@abc/my-library"  // for components
    import { myComponentStub } from "@abc/my-library/testing"  // for testing
```
Our dist folder structure looks like this.
```
     dist > 
        @abc >
             my-library >
                 testing > // testing directory
                 package.json
                 .....                               
```
We never had an issue with this error until we upgraded to angular 8 using Nx and tried to build.

**The error shows up when we do `ng build my-library`.** 

"Testing" is not a dependency used by "my-library" directly. But, the **spec** files within the library do.

They reference the stubs like so:
`Import { myComponentStub } from @abc/testing` mapped through the jest.config.

jest.config.js
```  
   ...
  moduleNameMapper: {
    "@abc/testing": "<rootDir>../../libs/testing/src/index.ts",
  }, 
```
The issue might lie in these test imports. The build might be looking for "@abc/testing" at `dist > @abc > testing`.

Prior versions of Angular "ng build" didn't care about the spec file and their dependencies. Seeing this error is something only found in the Nx repo during a google search (angular-package.test.ts). I thought I would ask you.

Any idea how to resolve this?

**Comment by FrozenPandaz** [comment] 2020-05-29 19:26
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by beeman** [comment] 2020-06-15 01:52
@FrozenPandaz I think I got a repo where this same error appears.

When adding the code in [this pr](https://github.com/KikstartDev/kikstart-ui/pull/4/files) my build also fails, without it it builds perfectly.

It might be something that I'm doing wrong in one of the libraries but I can't seem to spot it.

**Comment by psurrey** [comment] 2020-07-03 15:29
I've got the same issue. When running `nx run shared-core-ui:build --with-deps` Nx correctly detects that there is another lib to be built before (`>  NX  Running target build for project shared-core-ui and its 1 deps.`) and it starts even building this lib:

```
> ng run shared-utils:build 
Building Angular Package
```

After this one is successfully build, the build of the `shared-core-ui` lib fails: 

```
Built shared-utils

------------------------------------------------------------------------------
Built Angular Package
 - from: libs/shared/utils
 - to:   component-lib/shared-utils
------------------------------------------------------------------------------

> ng run shared-core-ui:build 
Some of the project shared-core-ui's dependencies have not been built yet. Please build these libraries before:
- shared-utils

Try: nx run shared-core-ui:build --with-deps

———————————————————————————————————————————————

>  NX   ERROR  Running target "build" failed

  Failed projects:
  
  - shared-core-ui
```

Seems like the issue is that the compiled output of the first library isn't found again when building the second library. How does Nx know where to find the compiled versions of libraries? Somewhere there has to be a mapping!? 🤔 

Would be great if the error message would include the path where Nx is looking for the compiled library for easier debugging. 😉

**Comment by psurrey** [comment] 2020-07-03 16:05
After digging around through the code I was able to fix it! 👍 

I found out that you can define the path for the "outputs" like this:

```
"architect": {
  "build": {
    "builder": "@nrwl/angular:package",
    "outputs": ["component-lib/shared-utils"],
    "options": {
      "tsConfig": "libs/shared/utils/tsconfig.lib.json",
      "project": "libs/shared/utils/ng-package.json"
    }
  }
}
```

Without this Nx has defaulted to `dist/libs/shared/utils` - see: https://github.com/nrwl/nx/blob/master/packages/workspace/src/tasks-runner/utils.ts#L73

**Comment by vsavkin** [comment] 2020-07-23 02:17
Folks,

Our guide on buildable libraries doesn't cover this in depth (https://nx.dev/angular/guides/ci/incremental-builds#incremental-builds), and it probably should.

1. Buildable libraries can only depend on other buildable libraries, and those should be built before hand. The reason: if you publish library A to npm, everything A depends on has to be published to npm as well. It cannot depend on anything in the repo it came from that wasn't published.
2. Your testing code is part of the same library. So if it depends on something, whatever it depends on has to be built first.
3. If Lib A depends on Lib B, Nx will use the output of B to build A. So Nx needs to find this output. It will check the outputs property first, then the outputPath option of the builder, and, finally, will default to dist/libs/libb.

Does it make sense?

**Comment by vsavkin** [comment] 2020-08-13 20:22
Closing this issue

**Closed by vsavkin** 2020-08-13 20:22 UTC
Labels: scope: core, type: bug

**Comment by maxfriedmann** [comment] 2021-05-04 07:06
In my case, the @nrwl/angular:move command forgot to change the path set in libs/<YOUR LIBRARY>/ng-package.json. In any case someone (or my future me) stumbles over this issue again: Check the dist folder output!

**Comment by AndreThompson-Atlow** [comment] 2021-08-05 17:32
> Folks,
> 
> Our guide on buildable libraries doesn't cover this in depth (https://nx.dev/angular/guides/ci/incremental-builds#incremental-builds), and it probably should.
> 
> 1. Buildable libraries can only depend on other buildable libraries, and those should be built before hand. The reason: if you publish library A to npm, everything A depends on has to be published to npm as well. It cannot depend on anything in the repo it came from that wasn't published.
> 2. Your testing code is part of the same library. So if it depends on something, whatever it depends on has to be built first.
> 3. If Lib A depends on Lib B, Nx will use the output of B to build A. So Nx needs to find this output. It will check the outputs property first, then the outputPath option of the builder, and, finally, will default to dist/libs/libb.
> 
> Does it make sense?

no offense but it doesn't really sound like your answer addressed the issue-- we understood that it had a dependency, the issue was that it didn't appear to be using it even though it had built already.

**Comment by Arvi2k17** [comment] 2022-03-29 18:37
Hey, I was facing the same similar issue but in a different scenario while building in my local machine the build is succeeded but while deploying on the server it is getting failed while building my node-app. 

The library which is getting failed is the node library & the same library has been used in the frontend too.

**Error Faced**:

>  nx run middleware-student:build 
Some of the project middleware-student's dependencies have not been built yet. Please build these libraries before:
>- shared-student-model
> Try: nx run middleware-student:build --with-deps
> Error
>     at /var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/@nrwl/node/src/executors/package/package.impl.js:19:19
>     at Generator.next (<anonymous>)
>     at /var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/tslib/tslib.js:117:75
>     at new Promise (<anonymous>)
>     at __awaiter (/var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/tslib/tslib.js:113:16)
>     at packageExecutor (/var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/@nrwl/node/src/executors/package/package.impl.js:13:34)
>     at /var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/@nrwl/tao/src/commands/run.js:144:23
>     at Generator.next (<anonymous>)
>     at /var/lib/jenkins/workspace/DEV-Release-student-App/node_modules/tslib/tslib.js:117:75
>     at new Promise (<anonymous>)
> [1m[31mERROR: Something went wrong in @nrwl/run-commands - Command failed: nx build student-node-app --prod --skip-nx-cache[39m[22m
> 

**project.json**

> {
>   "root": "libs/shared/student-model",
>   "sourceRoot": "libs/shared/student-model/src",
>   "projectType": "library",
>   "targets": {
>     "build": {
>       "executor": "@nrwl/node:package",
>       "outputs": [
>         "{options.outputPath}"
>       ],
>       "options": {
>         "outputPath": "dist/libs/shared/student-model",
>         "tsConfig": "libs/shared/student-model/tsconfig.lib.json",
>         "packageJson": "libs/shared/student-model/package.json",
>         "main": "libs/shared/student-model/src/index.ts",
>         "assets": [
>           "libs/shared/student-model/*.md"
>         ]
>       }
>     },
>     "lint": {
>       "executor": "@nrwl/linter:eslint",
>       "outputs": [
>         "{options.outputFile}"
>       ],
>       "options": {
>         "lintFilePatterns": [
>           "libs/shared/student-model/**/*.ts"
>         ]
>       }
>     }
>   },
>   "tags": []
> }

**tsconfig.json**:
![image](https://user-images.githubusercontent.com/70632639/160679572-e069df40-f399-40eb-94c0-ee5e3c252326.png)

**tsconfig.lib.json**:
![image](https://user-images.githubusercontent.com/70632639/160679755-fb072826-41f1-4cc1-9976-6f6b5832725a.png)


@vsavkin, we understood the point you said but what will be the solution or workaround?.

**Comment by Arvi2k17** [comment] 2022-03-29 18:42
> I've got the same issue. When running `nx run shared-core-ui:build --with-deps` Nx correctly detects that there is another lib to be built before (`> NX Running target build for project shared-core-ui and its 1 deps.`) and it starts even building this lib:
> 
> ```
> > ng run shared-utils:build 
> Building Angular Package
> ```
> 
> After this one is successfully built, the build of the `shared-core-ui` lib fails:
> 
> ```
> Built shared-utils
> 
> ------------------------------------------------------------------------------
> Built Angular Package
>  - from: libs/shared/utils
>  - to:   component-lib/shared-utils
> ------------------------------------------------------------------------------
> 
> > ng run shared-core-ui:build 
> Some of the project shared-core-ui's dependencies have not been built yet. Please build these libraries before:
> - shared-utils
> 
> Try: nx run shared-core-ui:build --with-deps
> 
> ———————————————————————————————————————————————
> 
> >  NX   ERROR  Running target "build" failed
> 
>   Failed projects:
>   
>   - shared-core-ui
> ```
> 
> Seems like the issue is that the compiled output of the first library isn't found again when building the second library. How does Nx know where to find the compiled versions of libraries? Somewhere there has to be a mapping!? 🤔
> 
> Would be great if the error message would include the path where Nx is looking for the compiled library for easier debugging. 😉

Hey hi @psurrey, have you found any workarounds or solutions?

**Comment by nicolajkirchhof** [comment] 2022-04-22 07:58
@Arvi2k17 
I was fighting with this problem as well. In my case the dependent library was moved but apparently the @nrwl/workspace:move did not change the ng-package.json 'dest' property. 

Thus, in my case I had to make sure that the library in `libs/shared/ui-helpers` had its dest in `ng-package.json` set to `"dest": "../../../dist/libs/shared/ui-helpers"` so that it was found in the build by the including library.

**Comment by sangecz** [comment] 2022-08-22 10:40
> @Arvi2k17 I was fighting with this problem as well. In my case the dependent library was moved but apparently the @nrwl/workspace:move did not change the ng-package.json 'dest' property.
> 
> Thus, in my case I had to make sure that the library in `libs/shared/ui-helpers` had its dest in `ng-package.json` set to `"dest": "../../../dist/libs/shared/ui-helpers"` so that it was found in the build by the including library.

This is still happening, `dest` remained unchanged after move cmd @vsavkin
