### ISSUE TITLE
Angular app name containing dot will end up with root component selector containing dot and doesn't work.

### ISSUE THREAD

**Issue by EricAskari** [nrwl/nx#5110] opened 2021-03-24 19:42 UTC
nx generate @nrwl/angular:app myapp.com

## Current Behavior
`ERROR Error: The selector "myapp.com-root" did not match any elements at DefaultDomRenderer2.selectRootElement`

root selector: myapp.com-root

## Expected Behavior
root selector: myappcom-root or something without dot 
( I am not sure but I've never seen dot in component selector)

### Failure Logs
![Screenshot 2021-03-24 at 21 38 54](https://user-images.githubusercontent.com/32340808/112373716-ef00ae80-8ce9-11eb-94d6-4ae8d17fb6ce.png)

### Environment
```
  Node : 14.15.5
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.5.2
  @nrwl/cli : 11.5.2
  @nrwl/cypress : 11.5.2
  @nrwl/devkit : 11.5.2
  @nrwl/eslint-plugin-nx : 11.5.2
  @nrwl/express : 11.5.2
  @nrwl/jest : 11.5.2
  @nrwl/linter : 11.5.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.5.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.2
  @nrwl/web : Not Found
  @nrwl/workspace : 11.5.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.0.7

```

**Comment by vsavkin** [comment] 2021-04-04 16:25
Thank you for submitting the issue!

The issue isn't with Nx but with the Angular Compiler, so http://github.com/angular/angular will be a better repo to open the issue in.

I'm going to close this.
Thank you!

**Closed by vsavkin** 2021-04-04 16:25 UTC
Labels: scope: angular, type: question / discussion

**Comment by dzoech** [comment] 2021-05-03 11:48
This one bit me as well when using a workspace name having a dot. Would it make sense to at least give a warning?
