### ISSUE TITLE
When using nx g move the jest.config.js (v10+) is not updated with new lib name

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#4086] opened 2020-11-13 16:45 UTC
## Current Behavior
When using `nx g move` the *.json files are updated with the new name but jest.config.js is not

## Expected Behavior
When renaming a library it should update each of the necessary configuration files

## Steps to Reproduce
Move any lib in a repo in v10+

### Environment
```
 NX  Report complete - copy this into the issue template

  nx : Not Found
  @nrwl/angular : 10.3.2
  @nrwl/cli : 10.3.2
  @nrwl/cypress : 10.3.2
  @nrwl/eslint-plugin-nx : 10.3.2
  @nrwl/express : 10.3.2
  @nrwl/jest : 10.3.2
  @nrwl/linter : 10.3.2
  @nrwl/nest : 10.3.2
  @nrwl/next : Not Found
  @nrwl/node : 10.3.2
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.2
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.2
  typescript : 3.9.7
```

I am more than happy to open a PR with a fix if this isn't already being worked on.

**Comment by beeman** [comment] 2020-11-13 18:50
Seems like a duplicate of #4014

**Closed** 2020-11-13 18:59 UTC
Labels: type: bug
