### ISSUE TITLE
Nested lib Cypress generation Issues (Wrong Path)

### ISSUE THREAD

**Issue by lexbrayan** [nrwl/nx#7151] opened 2021-09-27 21:30 UTC
## Current Behavior
When running this command from a Windows machine: 

npx nx g @nrwl/angular:storybook-configuration my-project --configureCypress --generateCypressSpecs --generateStories --force 

an error of "Could not read TS file (libs/my/project/src/lib/my/project/src/lib/my-panel/my-panel.co.ts)." is seen. This path is generated from appending **projectPath** “libs\my\project\src\lib” and **componentPath** “libs/my/project/src/lib/my-panel” from line 10 in @nrwl\angular\src\generators\component-story\component-story.js 

**NOTE: This only happens if it is a library inside a folder**

## Expected Behavior

Able to properly generate a Cypress e2e folder on a Windows machine. 

## Steps to Reproduce

Run this on a Windows machine - 

npx nx g @nrwl/angular:storybook-configuration my-project --configureCypress --generateCypressSpecs --generateStories –force 

Where my-project has nested libs in an Nx Angular workspace. 

### How To Fix
In  **\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\utils\path.js** for the **joinPathFragments** function add the code below: 

```
function joinPathFragments(...fragments) {
    for (let i = 0; i < fragments.length-1; i++) {
        fragments[i] = fragments[i].replace(/\\{1,}/g, '/');
     }
     if (fragments[1].includes(fragments[0])) {
        fragments[1] = "." + fragments[1].replace(fragments[0], "");
     }
     
    return normalizePath(path.join(...fragments));
}
```

This may fix any redundant part of the projectPath within the componentPath. 
### Environment
Node : 12.22.0 

OS : Windows 10 x64  
npm : 6.14.11 

nx : Not Found 
@nrwl/angular : 12.5.7 
@nrwl/cli : 12.5.7 
@nrwl/cypress : 12.9.0 
@nrwl/devkit : Not Found 
@nrwl/eslint-plugin-nx : 12.5.7 
@nrwl/express : 12.5.7 
@nrwl/jest : 12.5.7 
@nrwl/linter : Not Found 
@nrwl/nest : 12.5.7 
@nrwl/next : Not Found 
@nrwl/node : 12.5.7 
@nrwl/react : Not Found 
@nrwl/schematics : Not Found 
@nrwl/tao : 12.5.7 
@nrwl/web : Not Found 
@nrwl/workspace : 12.5.7 
@nrwl/storybook : 12.5.7 
@nrwl/gatsby : Not Found 
typescript : 4.2.4

**Comment by mandarini** [comment] 2021-10-21 12:14
Hi there @lexbrayan ! Thanks for filing this issue! I see that you already have a suggested fix. Have you tested your fix, does it fix the issue?

If yes, why don't you try it as your first contribution to Nx? I can help you through if you want!

**Comment by mandarini** [comment] 2022-01-17 15:37
@lexbrayan hi there! We could not reproduce, neither on Windows or on MacOS. Can you verify that the issue still exists? If not, can I go ahead and close this?

**Closed** 2022-01-17 15:39 UTC
Labels: type: bug, blocked: repro needed, scope: storybook, os: windows

**Comment by atix9000** [comment] 2022-01-21 10:24
@mandarini i have same issue and the @lexbrayan's fix worked for me
