### ISSUE TITLE
Angular MFE + SSR -> Static Remotes stuck building on consecutive runs + remoteEntry messes up routing and guards

### ISSUE THREAD

**Issue by kevinriemens** [nrwl/nx#22722] opened 2024-04-08 07:13 UTC
### Current Behavior

When running `nx serve` it builds x remotes statically. The builds succeed on the first run, but each consecutive run (without any code chances) results in the console hanging indefinitely on 'Building x static remotes'.

With the first build, it looks like some of the configuration is broken, probably because of remoteEntry, because the routing for that second remote is broken. 

When running nxServe together with devRemotes, all is working fine.

### Expected Behavior

Static build should serve correctly.

### Steps to Reproduce

1. Install latest nx with Angular (modules) + SSR + Webpack + Module federation (shell + 2+ remotes). 
2. Run nx serve
3. Stop the process
4. run nx serve again

### Nx Report

```shell
Node   : 18.19.1
OS     : darwin-arm64
yarn   : 1.22.21

nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/jest           : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/angular        : 18.2.3
@nx/cypress        : 18.2.3
@nx/devkit         : 18.2.3
@nx/eslint-plugin  : 18.2.3
@nrwl/tao          : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.3
---------------------------------------
Community plugins:
@ng-bootstrap/ng-bootstrap       : 16.0.0
@ngneat/transloco                : 4.1.2
@ngrx/component-store            : 17.0.1
@ngrx/effects                    : 17.0.1
@ngrx/entity                     : 17.0.1
@ngrx/router-store               : 17.0.1
@ngrx/schematics                 : 17.0.1
@ngrx/store                      : 17.0.1
@ngrx/store-devtools             : 17.0.1
ng-mocks                         : 14.12.1
ngx-bootstrap                    : 12.0.0
```

### Package Manager Version

Yarn 1.22.21

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2024-04-18 09:37
Thanks for reporting this!

This is a duplicate of #20973. Please follow that issue for updates and provide any meaningful information on that issue.

**Closed by leosvelperez** 2024-04-18 09:37 UTC
Labels: type: bug, scope: module federation
