### ISSUE TITLE
Even w. version set to 2, new module definitions go into workspace.json inline instead of just referencing project.json

### ISSUE THREAD

**Issue by bjornharvold** [nrwl/nx#10354] opened 2022-05-18 06:57 UTC
## Current Behavior
When upgrading to Angular 13 and the latest version of Nx, we also converted to the more modular way of configuration as opposed to the old v1 way of keeping everything in angular.json. So we renamed angular.json to workspace.json and set the version property to 2. and executed the migration script: `npx nx generate @nrwl/workspace:convert-to-nx-project --all=true` and `npx nx format`. Everything works. However, every time we create a new module, it gets specified in workspace.json in its entirety / inline and we have to run the conversion script each time. 

Is there a flag we are missing somewhere?

## Expected Behavior
We expect the module to be referenced in workspace.json only.

## Report
```
Node : 16.15.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 14.1.6
   @nrwl/angular : 14.1.6
   @nrwl/cypress : 14.1.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.6
   @nrwl/eslint-plugin-nx : 14.1.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.6
   @nrwl/js : 14.1.6
   @nrwl/linter : 14.1.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.6
   @nrwl/web : 14.1.6
   @nrwl/workspace : 14.1.6
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ng-bootstrap/ng-bootstrap: 12.1.1
   	 @ngneat/transloco: 4.0.0
   	 @ngrx/component: 13.2.0
   	 @ngrx/component-store: 13.2.0
   	 @ngrx/data: 13.2.0
   	 @ngrx/effects: 13.2.0
   	 @ngrx/entity: 13.2.0
   	 @ngrx/router-store: 13.2.0
   	 @ngrx/store: 13.2.0
   	 @ngrx/store-devtools: 13.2.0
   	 angular-calendar: 0.29.0
   	 @compodoc/compodoc: 1.1.19
   	 @jscutlery/semver: 2.23.4
   	 @ngrx/schematics: 13.2.0
   	 @storybook/angular: 6.4.22
```

**Comment by bjornharvold** [comment] 2022-06-03 02:26
This has not been resolved. We are still typing the "convert" after every new module we create.

**Comment by bjornharvold** [comment] 2022-06-19 12:12
Still having the same issue

**Comment by bjornharvold** [comment] 2022-07-04 05:27
Still having the same issue

**Comment by bjornharvold** [comment] 2022-07-15 09:23
Hi @AgentEnder 

Apologies. No I don't. 

Here's our workspace.json.

```
`{`
  "version": 2,
  "projects": {
    "activity-domain": "libs/activity/domain",
    ...
    "workspace": {
      "root": ".",
      "targets": {
        "version": {
          "executor": "@jscutlery/semver:version",
          "options": {
            "syncVersions": true,
            "commitMessageFormat": "chore(${projectName}): release version ${version}"
          }
        }
      }
    }
  }
}

```

Here's nx.json:

```
{
  "implicitDependencies": {
    "workspace.json": "*",
    "package.json": {
      "dependencies": "*",
      "devDependencies": "*"
    },
    ".eslintrc.json": "*"
  },
  "affected": {
    "defaultBase": "master"
  },
  "npmScope": "wink",
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/workspace/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e",
          "build-storybook"
        ]
      }
    }
  },
  "targetDependencies": {
    "build": [
      {
        "target": "build",
        "projects": "dependencies"
      }
    ]
  },
  "cli": {
    "packageManager": "yarn",
    "defaultCollection": "@nrwl/angular"
  },
  "defaultProject": "booking-engine",
  "generators": {
    "@nrwl/angular": {
      "application": {
        "linter": "eslint"
      },
      "library": {
        "linter": "eslint"
      },
      "storybook-configuration": {
        "linter": "eslint"
      }
    },
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress",
      "strict": true
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest",
      "strict": true
    },
    "@nrwl/angular:component": {
      "style": "scss",
      "changeDetection": "OnPush"
    }
  }
}

```

Also notice that the default change detection is not being honored when creating new components but that could be the fault of the ddd plugin I am using.

**Comment by AgentEnder** [comment] 2022-07-15 12:52
I'm going to go ahead and close this out, it looks like I was correct:

> The most common reason for this, would be that the default for new projects is determined by the current workspace.json... If any are inline, the new is inline etc.

Your workspace.json has the project named workspace as an inline project. Because there is a project inline, the default for new projects is inline. This is intended behavior.

**Closed** 2022-07-15 12:52 UTC
Labels: type: bug, blocked: repro needed, blocked: more info needed, scope: core

**Comment by bjornharvold** [comment] 2022-07-15 13:59
Hi @AgentEnder 

Not sure I follow. This is how the workspace.json was [re-]organized after I migrated using the command:
`npx nx generate @nrwl/workspace:convert-to-nx-project --all=true`

Before, every project was in here. Now they all reference a project.json in each individual project.

How do I avoid having to type the convert command every time I create a new module?

Thank you

**Comment by AgentEnder** [comment] 2022-07-15 14:21
That doesn't look like its the case. Looking at your message:
> ```
>{
>  "version": 2,
> "projects": {
>    "activity-domain": "libs/activity/domain",
>    ...
>   "workspace": {
>      "root": ".",
>      "targets": {
>        "version": {
>          "executor": "@jscutlery/semver:version",
>          "options": {
>            "syncVersions": true,
>            "commitMessageFormat": "chore(${projectName}): release version ${version}"
>          }
>        }
>      }
>    }
>  }
> }
> ```

That last project, named "workspace" is an inline project.

**Comment by bjornharvold** [comment] 2022-07-15 14:36
AFAIK workspace was created by either the semver plugin and later also used by Husky. I don't know if they would work without it. In any case, workspace is not one of my modules. But I understand, you're saying this is what's the issue.

Thank you
