### ISSUE TITLE
npx create-nx-workspace@latest [project_name] intrepreted as [project-name]

### ISSUE THREAD

**Issue by sonyarianto** [nrwl/nx#16326] opened 2023-04-16 06:30 UTC
### Current Behavior

When I type
`npx create-nx-workspace@latest project_name` (with underscore), internally nx will interpret `project-name`, so when the CLI complete it error since it tries to look on `project-name` directory, but actually Nx is creating `project_name` directory.

### Expected Behavior

Nx should properly go to `project_name` directory, instead of `project-name` since the user inputing `project_name` on CLI argument.

### Steps to Reproduce

1. `npx create-nx-workspace@latest project_name`
2. it will create project_name directory
3. but Nx internally use project-name
4. At the end there is error Error: ENOENT: no such file or directory, open 'C:\Users\Sony AK\projects\project-name\error.log' which is that directory is not exists

### Nx Report

```shell
PS C:\Users\Sony AK\projects> npx create-nx-workspace@latest jogja_nx

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Choose what to create                 · react
√ Bundler to be used to build the application · vite
√ Default stylesheet format             · css
√ Enable distributed caching to make your CI faster · Yes

 >  NX   Nx is creating your v15.9.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: jogja-nx.
⠋ Setting up NxCloudnode:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\Sony AK\projects\jogja-nx\error.log'
    at Object.openSync (node:fs:589:3)
    at writeFileSync (node:fs:2247:35)
    at C:\Users\Sony AK\AppData\Local\npm-cache\_npx\505743838affa773\node_modules\create-nx-workspace\src\utils\child-process-utils.js:34:40
    at exithandler (node:child_process:427:5)
    at ChildProcess.errorhandler (node:child_process:439:5)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Sony AK\\projects\\jogja-nx\\error.log'
}

Node.js v19.8.1
```

**Comment by 4javier** [comment] 2023-04-25 16:36
This ticket can be merged with this one: https://github.com/nrwl/nx/issues/16501
I tracked down the issue and it comes from the same code.
`create-empty-workspace` uses "plain" user input  name for directory creation 
https://github.com/nrwl/nx/blob/438dff76f56cb6879ff6c6bef28f708db832ab63/packages/create-nx-workspace/src/create-empty-workspace.ts#L41
but returns the name of the workspace after calling string-utils's `getFileName` on it:
https://github.com/nrwl/nx/blob/438dff76f56cb6879ff6c6bef28f708db832ab63/packages/create-nx-workspace/src/create-empty-workspace.ts#L83

The problem is the latter "sanitizes" the string turning it to lowercase and changing underscores to dash:
https://github.com/nrwl/nx/blob/438dff76f56cb6879ff6c6bef28f708db832ab63/packages/create-nx-workspace/src/utils/string-utils.ts#L5-L10

So, if you choose a name containing underscores or capitalized letters for your workspace, the directory will be created according to that, but following commands will be executed spawning a non existent project directory name (the "sanitized" one).

**Closed** 2023-05-03 20:47 UTC
Labels: type: bug, scope: misc
