### ISSUE TITLE
create-nx-workspace error on git command

### ISSUE THREAD

**Issue by aminfara** [nrwl/nx#16874] opened 2023-05-09 06:04 UTC
### Current Behavior

Creating a new nx workspace errors out on the `git` command:

```
➜ npx create-nx-workspace@latest
Need to install the following packages:
  create-nx-workspace@16.1.3
Ok to proceed? (y) y

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Choose what to create                 · integrated
✔ What to create in the new workspace   · apps
✔ Repository name                       · TestMonoRepo
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v16.1.3 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: test-mono-repo.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/sh ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/sh',
  path: '/bin/sh',
  spawnargs: [ '-c', 'git rev-parse --is-inside-work-tree' ]
}

Node.js v18.16.0
```

I tested on two different macbooks. One X86 and one M1 macbook and both had the same error.

```
16:01:08 in ~/Workplace/temp
➜ cd TestMonoRepo

16:01:12 in ~/Workplace/temp/TestMonoRepo via ⬢ v18.16.0
➜ ls -ahl
total 168
drwxr-xr-x   13 user  admin   416B  9 May 15:56 .
drwxr-xr-x    4 user  admin   128B  9 May 15:56 ..
-rw-r--r--    1 user  admin   245B  9 May 15:56 .editorconfig
-rw-r--r--    1 user  admin   500B  9 May 15:56 .gitignore
drwxr-xr-x    3 user  admin    96B  9 May 15:56 .vscode
-rw-r--r--    1 user  admin   592B  9 May 15:56 README.md
drwxr-xr-x    3 user  admin    96B  9 May 15:56 apps
drwxr-xr-x    3 user  admin    96B  9 May 15:56 libs
drwxr-xr-x  134 user  admin   4.2K  9 May 15:56 node_modules
-rw-r--r--    1 user  admin   661B  9 May 15:56 nx.json
-rw-r--r--    1 user  admin    61K  9 May 15:56 package-lock.json
-rw-r--r--    1 user  admin   215B  9 May 15:56 package.json
drwxr-xr-x    3 user  admin    96B  9 May 15:56 tools

16:01:13 in ~/Workplace/temp/TestMonoRepo via ⬢ v18.16.0
```

no git directory is initialised.

### Expected Behavior

Creating a new workspace do not error out.

### Steps to Reproduce

1. Just type `npx create-nx-workspace@latest` (on a macOS).

### Nx Report

```shell
16:01:13 in ~/Workplace/temp/TestMonoRepo via ⬢ v18.16.0
➜ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin x64
   npm    : 9.5.1
   Hasher : Native

   nx             : 16.1.3
   @nx/workspace  : 16.1.3
   @nx/devkit     : 16.1.3
   @nrwl/tao      : 16.1.3
```
```


### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by leosvelperez** [comment] 2023-05-09 07:59
Thanks for reporting this!

The root cause of this issue is the same as https://github.com/nrwl/nx/issues/16841 and was fixed by https://github.com/nrwl/nx/pull/16855. The fix should be released in a patch version soon. Please keep an eye on the releases to get the fix.

In the meantime, if you want to unblock yourself, instead of providing `TestMonoRepo` as the repo name, you can provide `test-mono-repo`.

**Closed by leosvelperez** 2023-05-09 07:59 UTC
Labels: type: bug
