### ISSUE TITLE
updateBuildableProjectDepsInPackageJson (is wrongly) set to true in nx 16.6.0 migration where it was not defined

### ISSUE THREAD

**Issue by ckaeslin** [nrwl/nx#18616] opened 2023-08-14 13:55 UTC
### Current Behavior

Doing the nx migration to 16.6.0 it sets updateBuildableProjectDepsInPackageJson to true where it was not defined.
This has broken our build.
Despite the documentation previous to 16.6.0 saying that the default is true, isn't the behaviour rather that default is false? e.g. https://github.com/nrwl/nx/blob/b8a64a16cb94612ff43d643ca1d52bdd3e14ac2b/packages/rollup/src/executors/rollup/lib/update-package-json.ts#L79

### Expected Behavior

Migrating to nx 16.6.0 should not set updateBuildableProjectDepsInPackageJson to true where it was not defined.

### Steps to Reproduce

1. any nx repo previous to 16.6.0
2. don't specifiy updateBuildableProjectDepsInPackageJson
3. migrate to nx 16.6.0
4. updateBuildableProjectDepsInPackageJson is set to true

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.6.7

   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/nest           : 16.6.0
   @nx/next           : 16.6.0
   @nx/node           : 16.6.0
   @nx/plugin         : 16.6.0
   @nx/react          : 16.6.0
   @nx/rollup         : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @koliveira15/nx-sonarqube        : 3.0.2
   @nxkit/playwright                : 3.0.2
   @trumbitta/nx-plugin-unused-deps : 1.12.1
   ---------------------------------------
   Local workspace plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ckaeslin** [comment] 2023-08-14 14:12
I have not really looked further into the issue as it all worked after removing updateBuildableProjectDepsInPackageJson=true everywhere it got added.
The error message was about missing some npm package, which was clearly installed and available in node_modules.

**Comment by leosvelperez** [comment] 2023-08-14 14:18
Do you have the `updateBuildableProjectDepsInPackageJson` option set to `false` in your `targetDefaults` in `nx.json`?

**Comment by ckaeslin** [comment] 2023-08-14 14:20
We have not used updateBuildableProjectDepsInPackageJson anywhere before the 16.6.0 migration.
I can't find anything in nx.json or anywhere else, also not before the migration.

**Comment by ckaeslin** [comment] 2023-08-14 14:24
We have migrated from nx 16.5.0 to nx 16.6.0. Directly after some projects failed to build with
`../../node_modules/@elastic/apm-rum-react/dist/es/get-apm-route.js
Module not found: Can't resolve 'react-router-dom`

After removing updateBuildableProjectDepsInPackageJson from these projects, everything worked again.

**Comment by leosvelperez** [comment] 2023-08-14 14:33
Sorry, we'll need a reproduction to troubleshoot this. As explained, if you didn't have the option set anywhere, the executor would have used it as it was set to `true` because that was its default value. So, it is correct for the migration to set it to `true` because we changed the default value to `false` and that would have been a breaking change.

**Comment by ckaeslin** [comment] 2023-08-14 15:02
So in 16.5.0 the default value seems to be true and the build works. It only affects shared libraries for us.
With 16.6.0 some projects which use these shared libraries fail to build if the updateBuildableProjectDepsInPackageJson is set to true. So the issue seems to be something else.

**Comment by leosvelperez** [comment] 2023-08-14 15:43
If you later find what the issue is and you think Nx is at fault, please create a new issue with details.

I'm going to close this since the migration since to be working as expected.

**Closed by leosvelperez** 2023-08-14 15:43 UTC
Labels: type: bug, blocked: more info needed, scope: misc

**Comment by tinesoft** [comment] 2023-08-16 09:02
I've just migrated my plugins at https://github.com/tinesoft/nxrocks to `Nx 16.7.0` and I faced the same issue described by @ckaeslin ...

Since  I now rely solely on `@nx/dependency-checks` ESLINT rule to manage  the dependencies of my plugins,
I had no `updateBuildableProjectDepsInPackageJson` flag at all in my `project.json` files, and when linting (with `--fix`)  + building the plugins, the proper deps were properly set.

The migration  added  back `"updateBuildableProjectDepsInPackageJson": true`, which somehow is not the same as not having the flag set at all, despite what you said @leosvelperez .
In fact, with the former,  when I lint (with `--fix`)  and build my plugins again, the generated `package.json` in `dist`, are different (even wrong, as they contain transitive dependencies from an internal package + the internal package itself).

I had to manually remove it again after the migration

**Comment by leosvelperez** [comment] 2023-08-16 09:38
hey @tinesoft!

That migration targets Nx 16.6.0, so if you migrated from 16.6.0 to 16.7.0, the migration shouldn't run again. I can see it ran when you migrated to 16.6.0 https://github.com/tinesoft/nxrocks/commit/e500428da1595cf263ea8712ae0058025c0268b5.

I'll reiterate that all the migration is doing is keeping the same value for the flag as your workspace had (explicitly or implicitly). You can see:

- the default value was switched from `true` to `false`: https://github.com/nrwl/nx/commit/64765eb313d33c93bd4db35d86b21ecb43fa5757#diff-250477db693f3f1cb8440b6c2e2326973db0683f370426c24b914aa2b5b73a83
- the migration sets the option to `true` if you didn't have any explicit value for it (therefore if was using the default value): https://github.com/nrwl/nx/commit/64765eb313d33c93bd4db35d86b21ecb43fa5757#diff-2dfa552c5ccade1c8808b1d753b8dd2ec1d09c1dc9b38d814040262f35a42089

I think the issue is that you have the `migrations.json` file committed to your repo and I guess there were no migrations for 16.7.0, so, that file was unchanged and you probably ran `nx migrate --run-migrations`. That would have run the migrations again.

**Comment by leosvelperez** [comment] 2023-08-16 09:55
Looking at your commits and their timeline confirms the above:

1. Migrated to 16.6.0 and the migration run setting the option for targets that didn't have it set: https://github.com/tinesoft/nxrocks/commit/e500428da1595cf263ea8712ae0058025c0268b5
2. Removed the options and started using the ESLint rule: https://github.com/tinesoft/nxrocks/commit/cfac383c7d2aebd329a98f410df66b726b64d28a
3. Migrated to 16.7.0 and ran the same migration again (because the `migrations.json` file exists with the old migrations): https://github.com/tinesoft/nxrocks/commit/356c26c50e1ad3edd3eb2778a562884451f5b701

As you had already switched the defaults (by migrating to 16.6.0) and explicitly removed the option afterward, you shouldn't run that migration again. You can avoid this in the future by either:

- Not committing the `migrations.json` file or removing it before migrating to a new version
- When the `nx migrate latest` command doesn't collect any new migrations (it would tell you after the command is run), don't run `nx migrate --run-migrations`, just install the packages

Having said that, I'll bring up internally the fact that running `nx migrate latest` doesn't remove the existing `migrations.json` if no migrations were collected. That could be a safety net on our side to prevent such an issue.

**Comment by tinesoft** [comment] 2023-08-16 10:01
Hi @leosvelperez 

Thank you for the quick and very detailed explanation, much appreciated 👍🏾.

I will do as you suggest and uncommit `migrations.json` from now on.
Having `nx migrate` automatically remove it as you suggest, would be great as well.


Anyway, thank you and have a great day!
