### ISSUE TITLE
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by YevheniiYusenkov** [nrwl/nx#17065] opened 2023-05-17 13:04 UTC
### Current Behavior

I generated a new nx workspace with npx create-nx-workspace@latest, installed @nx/nest and generated a new nestjs app.
After run nx serve appname its failed with this error:

Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

How to fix it?

### Expected Behavior

I need to run app without any errors

### Steps to Reproduce

1. npx create-nx-workspace@latest
2. npm install -D @nx/nest
3. nx g @nx/nest:app some-app
4. nx serve some-app

### Nx Report

```shell
Node   : 16.16.0
   OS     : win32 x64
   npm    : 8.11.0
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   typescript         : 5.0.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment] 2023-05-17 14:55
This is a duplicate of #16834 and fixed by #16911, we are working on releasing 16.2.0 which should have the fix.

**Closed by AgentEnder** 2023-05-17 14:55 UTC
Labels: type: bug
