### ISSUE TITLE
`nx migrate latest` overwrites non-nx dependencies in package.json

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10631] opened 2022-06-08 09:08 UTC
After migrating to 14.2.1 (from 14.1.9), versions in package.json were overriden for non-nx and non-@nrwl dependencies.
I don't know why would you need to control the version of @ngrx/store or @angular/animations I want to use.
Please do not do this, it can be very destructive. At least ask if I want to change them. And do not remove "^" or "~" signs from versions.

Sorry that this bug report is not made using your form, but it's kind of unusal bug.

Node: 18.2.0
npm:  8.10.0

**Comment by e-oz** [comment] 2022-06-08 09:49
While upgrading another project, I've noticed that it happens right after the `nx migrate latest` command.

**Comment by fatihdogmus** [comment] 2022-06-08 11:20
I think this is not a bug though. To give a better migration experience, I think nx manages some dependencies like cypress, jest, angular and typescript. If there are breaking changes, they write migrations script to accommodate those changes, and I think it is a good thing that I do not have to worry about versions of some dependencies. But an option to disable non-nrwl package upgrade can be useful for some.

**Comment by leosvelperez** [comment] 2022-06-08 12:19
hey @e-oz!

This is not a bug and it's the intended behavior. Nx plugins will manage some packages they are related to and depend on to ensure the plugin works correctly. This is by design, a given version of a plugin can't work with all versions.

Please note this process is not "destructive", packages aren't installed automatically and you have the option to review the changes to your `package.json` file before installing them (even if you install the packages you could always revert the changes). You would have seen a message in the terminal saying `Make sure package.json changes make sense and then run 'npm install'` (the install command changes according to your package manager) when you run `nx migrate latest`. This is why Nx migrations are a 2-step process: migrations are identified first and applied later. After `nx migrate latest` is run, you can review the package version changes and the migrations that are going to run and you are free to modify that before actually running the migration.

You can read more about Nx migrations in https://nx.dev/using-nx/updating-nx.

Please note that, as I've said before, the package versions the migration bumps to are what any given Nx plugin recommends and what has been tested to work well with the plugin. Doing something different might not work as expected since it's something that hasn't been tested with the plugin.

Some remarks about some specific packages/versions you mentioned:

- `@ngrx/store` latest stable version is `13.2.0`, that's what has been tested with the plugin.
- `jest-preset-angular` latest stable version compatible with Jest 27 (the Jest version supported by our `@nrwl/jest` plugin) is `11.1.2`, that's what has been tested.
- From experience, we prefer to use patch versions (`~`) to reduce the possibility of our plugin tooling being broken. We've had issues in the past when using minor versions (`^`).

I'm going to close this since it's not an issue, the migrations are working as intended. If you want to keep your own versions or prevent any specific change from a migration, you are free to edit your `package.json` file after you run `nx migrate latest` and before installing the packages or running `nx migrate --run-migrations`. Note that by doing so, you'd be using package versions that are not tested with the plugin and therefore, it might not work correctly.

**Closed by leosvelperez** 2022-06-08 12:19 UTC
Labels: type: bug

**Comment by e-oz** [comment] 2022-06-08 12:28
hey @leosvelperez

So it basically means that after every "nx migrate" I'll need to restore all my "^" (you are not just replacing them with "~", you are removing them, and "~" too), and resolve manually all the destructive changes. Not so friendly behavior, but ok, so far Nx positive effects outweigh negative ones.

Thank you for the response.
