### ISSUE TITLE
ProjectGraphBuilder

### ISSUE THREAD

**Issue by a1e8andre** [nrwl/nx#3045] opened 2020-05-21 10:10 UTC
```js
    addNode(node) {
        this.nodes[node.name] = node;
        this.dependencies[node.name] = {};
    }
```

This method overwrites node when the name of the package and own project match.
Look this file https://github.com/nrwl/nx/blob/master/packages/workspace/src/core/project-graph/project-graph.ts;
```js
        const builder = new project_graph_builder_1.ProjectGraphBuilder(incremental.projectGraph);
        const buildNodesFns = [
            build_nodes_1.buildWorkspaceProjectNodes, // <-
            build_nodes_1.buildNpmPackageNodes, // <-
        ];
        const buildDependenciesFns = [
            build_dependencies_1.buildExplicitTypeScriptDependencies,
            build_dependencies_1.buildImplicitProjectDependencies,
            build_dependencies_1.buildExplicitNpmDependencies,
        ];
        buildNodesFns.forEach((f) => f(ctx, builder.addNode.bind(builder), fileRead));
        buildDependenciesFns.forEach((f) => f(ctx, builder.nodes, builder.addDependency.bind(builder), fileRead));
```
### Steps to Reproduce

1. nx g @nrwl/nest:library lib_name --publishable
2. npm i lib_name
3. nx build lib_name

### Failure Logs

```
Unexpected error:
TypeError: Cannot read property 'build' of undefined
    at getOutputsForTargetAndConfiguration (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:42:42)
    at Object.getOutputs (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:38:12)
    at TaskOrchestrator.forkProcess (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:120:37)
    at takeFromQueue (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:48:26)
    at TaskOrchestrator.<anonymous> (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:69:27)
    at Generator.next (<anonymous>)
    at /Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:4:12)
    at TaskOrchestrator.runRest (/Users/alex/Work/nestjs-libs/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:40:16)
```

**Comment by FrozenPandaz** [comment] 2020-05-21 14:55
Closing this issue as a duplicate of https://github.com/nrwl/nx/issues/2396 which there is a PR #2997 to fix.

**Closed by FrozenPandaz** 2020-05-21 14:55 UTC
