### ISSUE TITLE
Add support for Mutation Testing

### ISSUE THREAD

**Issue by danieldanielecki** [nrwl/nx#1749] opened 2019-08-23 09:10 UTC
It could have been great to have in a freshly generated monorepo a support for mutation testing, [Stryker](https://stryker-mutator.io/) supports Jest & TypeScript.

**Comment by SebasG22** [comment] 2019-08-26 01:47
I can help with that. Instead of making it mandatory when generating a monorepo, it would be that it could be easily integrated into existing projects through `schematics`.

**Comment by mehrad-rafigh** [comment] 2019-08-28 12:04
This would be nice indeed. 

I am thinking of adding a new flag to app and lib generation `--mutation-test-runner`
It could have `none`as the default option and `stryker-mutator` as an option to invoke the schematic and setup everything needed.

What do guys think? I would have the time to tackle this.

**Comment by SebasG22** [comment] 2019-08-29 04:09
Awesome, let's do it. @mehrad-rafigh 
I will start working on this feature this weekend.
My plan is to generate the basic schematic for `stryker` then we can integrate this option to the `libs and apps` schematic.

**Comment by mehrad-rafigh** [comment] 2019-08-29 15:50
@SebasG22 Sounds good! If I can help you in any ways, let me know :)

**Comment by SebasG22** [comment] 2019-09-14 01:08
Hi @mehrad-rafigh @danieldanielecki, I made good progress these days on this feature and be able to implement stryker builder with partial support for jest and use it in an `nx repo`.
You can take a look here https://github.com/SebasG22/nx-mutation
To run the builder use: `yarn ng run demo2:mutate`.

Next steps:
- Support karma test runner
- Improve jest configuration to handle `tsconfig` paths
- Generate schematics for `stryker.config.js`
- Support `stryker.config.js`

**Comment by SebasG22** [comment] 2019-10-02 01:55
Hey folks, 
I'm happy to announce that I was able to create the `stryker` schematics & builder that supports `jest` and `karma` runners. I will submit the PR to be part of `nrwl/nx` on this weekend. 🚀 

**Note**: You can take a look at  [NX Mutation Examples](https://github.com/SebasG22/nx-mutation/tree/1.jest/apps)

**Comment by SebasG22** [comment] 2019-10-08 02:12
Hey folks,
It's amazing to know that nx will support mutation testing soon...
https://github.com/nrwl/nx/pull/1925

**Comment by davidgaulin** [comment] 2019-11-12 02:49
@SebasG22 are you moving forward with the nx-stryker plugin as suggested in our your PR?  interesting functionality for sure!

**Comment by SebasG22** [comment] 2019-11-12 14:44
Hey @davidgaulin, 
Sure. I'm working hard to move it as a plugin for angular and nx projects.
😄

**Comment by twittwer** [comment] 2020-03-10 22:25
@SebasG22 Thx for the hard work you already done
Do you make progress or maybe need help?

**Comment by danieldanielecki** [comment] 2020-03-11 08:20
@twittwer I just opened an [issue ](https://github.com/SebasG22/nx-mutation/issues/3 ) that I couldn't fetch the package. Looks like @SebasG22 is about releasing it in the near future.

**Comment by FrozenPandaz** [comment] 2020-05-29 19:22
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by mehrad-rafigh** [comment] 2021-01-11 08:37
@SebasG22 This issue can be closed because of your plugin right?

**Comment by fguitton** [comment] 2021-03-29 19:29
This is still of interest for ongoing projects

**Comment by fguitton** [comment] 2021-12-05 11:49
This is still of interest 💯 !

**Comment by barbados-clemens** [comment] 2022-02-18 20:46
closing this issue as we aren't looking to support a new testing plugin atm, since @SebasG22 made the plugin available at [SebasG22/nx-mutation](https://github.com/SebasG22/nx-mutation) I suggest a discussion on that repo.

**Closed by barbados-clemens** 2022-02-18 20:46 UTC
Labels: type: feature, scope: testing tools
