### ISSUE TITLE
No liniting errors shown in browser when using "@nrwl/next"

### ISSUE THREAD

**Issue by tar-aldev** [nrwl/nx#4768] opened 2021-02-11 14:26 UTC
## Current Behavior

When launching next or react project, it launches without warnings, although they are shown in ide.
The warnings also shown when running `nx lint`;

It is very inconvenient as there is a chance to miss some warnings, becuase they were not shown anywhere.
## Expected Behavior

Warnings (e.g. about exhaustive hook dependencies or unused vars) should be shown in browser terminal;

## Steps to Reproduce

1. Create a fresh react app;
2. in component declare a variable e.g. `const a = 10`; without using it;
3. Go to browser.
4. No warning is shown.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

 nx : 11.2.6
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.6
  @nrwl/devkit : 11.2.6
  @nrwl/eslint-plugin-nx : 11.2.6
  @nrwl/express : 11.2.11
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.6
  @nrwl/nest : Not Found
  @nrwl/next : 11.2.10
  @nrwl/node : 11.2.10
  @nrwl/react : 11.2.10
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.6
  @nrwl/web : 11.2.10
  @nrwl/workspace : 11.2.10
  typescript : 4.1.3

**Comment by vsavkin** [comment] 2021-02-11 16:34
Hi there!

This is by design. I don't think linting errors should be treated the same as compiler errors. 

Linting errors don't ensure correctness. They are about consistency and to some degree about code quality. I don't think they should distract you from interacting with your app. Many of them can be autofixed, so they are somewhat similar to formatting inconsistencies. Those too should not distract you from developing a feature.

We treat lint checks same as formatting checks or unit tests. It is an extra check ensuring that your code is consistent with the rest of the codebase.

Many people set up pre push hooks running lint checks or formatting checks. It can be helpful, but what is really important is to run lint checks and formatting checks in CI, so they cannot be missed.

I'm going to close this as it works as intended.

**Closed by vsavkin** 2021-02-11 16:34 UTC
Labels: scope: react, type: question / discussion
