### ISSUE TITLE
Package names aren't being printed in topological order

### ISSUE THREAD

**Issue by NathanJAdams** [nrwl/nx#19234] opened 2023-09-19 15:10 UTC
### Current Behavior

Package names **aren't** printed in topological order

### Expected Behavior

Package names **are** printed in topological order

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Run any of the commands:
    npx nx show projects --projects="libs/**" --affected
    npx nx show projects --projects="libs/**" --all
    npx nx print-affected --select=projects --type=lib --all

### Nx Report

```shell
Node   : 16.14.0
   OS     : win32-x64
   yarn   : 1.22.10

   nx                 : 16.8.0
   @nx/js             : 16.8.0
   @nx/jest           : 16.8.0
   @nx/linter         : 16.8.0
   @nx/workspace      : 16.8.0
   @nx/angular        : 16.8.0
   @nx/cypress        : 16.8.0
   @nx/devkit         : 16.8.0
   @nx/eslint-plugin  : 16.8.0
   @nx/react          : 16.8.0
   @nrwl/tao          : 16.8.0
   @nx/web            : 16.8.0
   @nx/webpack        : 16.8.0
   nx-cloud           : 16.4.0
   typescript         : 5.1.3
   ---------------------------------------
   Community plugins:
   @ngrx/component-store : 16.0.0
   @ngrx/effects         : 16.0.0
   @ngrx/entity          : 16.0.0
   @ngrx/router-store    : 16.0.0
   @ngrx/store           : 16.0.0
   @ngrx/store-devtools  : 16.0.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment] 2023-09-22 00:52
The order of the projects from nx show isn't guaranteed, but it's not a bug for it to be in any given order.

What use case would you have for it to be in topological order?

I'm going to close this out, the orders not guaranteed and relying on it should be seen as an antimatter. If you need things to run in order, they should probably be targets so that they can run via `nx run`. If you need the graph in a script, it'd be better to get it via `createProjectGraphAsync`

**Closed** 2023-09-22 00:53 UTC
Labels: type: bug
