### ISSUE TITLE
bare bones jest lib fails tests

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#782] opened 2018-09-21 16:39 UTC
following this [Faster Testing With Jest](https://blog.nrwl.io/nrwl-nx-6-3-faster-testing-with-jest-20a8ddb5064) post I create a new lib and component in that lib and set the test runner as jest.  Here are the commands I ran:
```
ng g lib jestlib --unit-test-runner jest

ng g c blah --project jestlib

ng test jestlib
```

The default tests for the module and the component both failed.  Is there something else I need to do?  Here is the output of the tests:

```
Test Suites: 0 of 2 total
Tests:       0 total
Snapshots:   0 total
Time:        4sts-jest[backports] (WARN) "[jest-config].globals.__TRANSFORM_HTML__" is deprecated, use "[jest-c
onfig].globals.ts-jest.stringifyContentPathRegex" instead.
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].global
s.ts-jest.tsConfig" instead.
ts-jest[backports] (WARN) Your Jest configuration is outdated. Use the CLI to help migrating it: ts-jest config
 FAIL  libs/jestlib/src/lib/blah/blah.component.spec.ts (15.915s)
  ● BlahComponent › should create

    Uncaught (in promise): Failed to load blah.component.html

      at resolvePromise (../../node_modules/zone.js/dist/zone.js:814:31)
      at resolvePromise (../../node_modules/zone.js/dist/zone.js:771:17)
      at ../../node_modules/zone.js/dist/zone.js:873:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:3
1)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/a
sync-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/proxy.js:
156:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:420:3
6)
      at Zone.Object.<anonymous>.Zone.runTask (../../node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (../../node_modules/zone.js/dist/zone.js:595:35)
      at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (../../node_modules/zone.js/dist/zone.js:5
00:21)
      at invokeTask (../../node_modules/zone.js/dist/zone.js:1540:14)
      at XMLHttpRequest.globalZoneAwareCallback (../../node_modules/zone.js/dist/zone.js:1566:17)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at XMLHttpRequestEventTargetImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-
impl.js:119:9)
      at XMLHttpRequestEventTargetImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTar
get-impl.js:82:17)
      at XMLHttpRequest.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:2
1)
      at Request.properties.client.on (../../node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:940:11)
      at IncomingMessage.<anonymous> (../../node_modules/request/request.js:1083:12)

  ● BlahComponent › should create

    This test module uses the component BlahComponent which is using a "templateUrl" or "styleUrls", but they w
ere never compiled. Please call "TestBed.compileComponents" before your test.

      at TestBed.Object.<anonymous>.TestBed._initIfNeeded (../../../../packages/core/testing/src/test_bed.ts:35
3:17)
      at TestBed.Object.<anonymous>.TestBed.createComponent (../../../../packages/core/testing/src/test_bed.ts:
552:10)
      at Function.Object.<anonymous>.TestBed.createComponent (../../../../packages/core/testing/src/test_bed.ts
:201:25)
      at src/lib/blah/blah.component.spec.ts:17:23
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:128:
39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (../../node_modules/jest-zone-patch/index.js:50:27)

  ● BlahComponent › should create

    expect(received).toBeTruthy()

    Received: undefined

      21 |
      22 |   it('should create', () => {
    > 23 |     expect(component).toBeTruthy();
         |                       ^
      24 |   });
      25 | });
      26 |

      at src/lib/blah/blah.component.spec.ts:23:23
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/dist/proxy.js:128:
39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length (../../node_modules/jest-zone-patch/index.js:50:27)

 FAIL  libs/jestlib/src/lib/jestlib.module.spec.ts (16.032s)
  ● JestlibModule › should create

    Uncaught (in promise): Failed to load blah.component.html

      at resolvePromise (../../node_modules/zone.js/dist/zone.js:814:31)
      at resolvePromise (../../node_modules/zone.js/dist/zone.js:771:17)
      at ../../node_modules/zone.js/dist/zone.js:873:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:421:3
1)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/a
sync-test.js:90:25)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../node_modules/zone.js/dist/proxy.js:
156:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../node_modules/zone.js/dist/zone.js:420:3
6)
      at Zone.Object.<anonymous>.Zone.runTask (../../node_modules/zone.js/dist/zone.js:188:47)
      at drainMicroTaskQueue (../../node_modules/zone.js/dist/zone.js:595:35)
      at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (../../node_modules/zone.js/dist/zone.js:5
00:21)
      at invokeTask (../../node_modules/zone.js/dist/zone.js:1540:14)
      at XMLHttpRequest.globalZoneAwareCallback (../../node_modules/zone.js/dist/zone.js:1566:17)
      at invokeEventListeners (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at XMLHttpRequestEventTargetImpl._dispatch (../../node_modules/jsdom/lib/jsdom/living/events/EventTarget-
impl.js:119:9)
      at XMLHttpRequestEventTargetImpl.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/events/EventTar
get-impl.js:82:17)
      at XMLHttpRequest.dispatchEvent (../../node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:2
1)
      at Request.properties.client.on (../../node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:940:11)
      at IncomingMessage.<anonymous> (../../node_modules/request/request.js:1083:12)


=============================== Coverage summary ===============================
Statements   : 94.74% ( 36/38 )
Branches     : 56.86% ( 29/51 )
Functions    : 62.5% ( 5/8 )
Lines        : 100% ( 29/29 )
================================================================================
Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        19.321s
Ran all test suites.
```

**Comment by FrozenPandaz** [comment] 2018-09-21 17:45
Duplicate of https://github.com/nrwl/nx/issues/776 which has been resolved already but not published. Quick Fix: install `jest-preset-angular@6.0.1`

**Closed** 2018-09-21 17:45 UTC

**Comment by jasedwards** [comment] 2018-09-21 20:05
@FrozenPandaz  A user on that other ticket stated that the work around did not work for them.  It also did not work for me.  I updated to 6.0.1 and am getting the exact same error as above.

**Comment by FrozenPandaz** [comment] 2018-09-21 20:16
I see, I've reopened the other issue.
