### ISSUE TITLE
NX 11->12 migration failure

### ISSUE THREAD

**Issue by jimdubbs** [nrwl/nx#5431] opened 2021-04-22 14:33 UTC
## Current Behavior
following migration instructions the command fails.

## Expected Behavior
migration to be completed sucessfully.

### Failure Logs
![image](https://user-images.githubusercontent.com/3068059/115732553-a4af3380-a362-11eb-8bc0-94ef6f749f14.png)

### Environment
![image](https://user-images.githubusercontent.com/3068059/115732689-c4465c00-a362-11eb-8052-fc88bd50a21e.png)

**Comment by FrozenPandaz** [comment] 2021-04-22 18:16
This is a duplicate of https://github.com/nrwl/nx/issues/5174.

I'll push a fix soon.

**Comment by jimdubbs** [comment] 2021-04-22 18:45
My apologies didn't see the Dupe. Appreciate the quick response!

**Closed** 2021-04-22 18:52 UTC
Labels: type: bug
