### ISSUE TITLE
ng g @nrwl/angular:application failing while running using externalSchematic on Windows machine

### ISSUE THREAD

**Issue by sandeeppatidar30** [nrwl/nx#8253] opened 2021-12-21 13:41 UTC
## Current Behavior
`ng g @nrwl/angular:application` if i run it using `externalSchematic`.

## Expected Behavior
It should not break the `ng g @nrwl/angular:application` 

## Steps to Reproduce
1. Create a custom generator 
2. Run `ng g @nrwl/angular:application`  using `externalSchematics`
 ```ts
import { chain, externalSchematic, mergeWith, Rule, SchematicContext, template, Tree,  url } from '@angular-devkit/schematics';
    export default function(schema: Schema): Rule {
      return (host: Tree, context: SchematicContext) => {
    
        return chain([
          externalSchematic('@nrwl/angular', 'application', {
            name: 'myapp'
          })
        ])(host, context);
      };
    }
```
3. After running above generator e.g. ng g @org/mylib:my-custom-generator

### Failure Logs
 ```

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
    at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
    at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
    at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\component\index.js:105:66
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
    at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
    at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
odule.
    at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
    at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
    at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\component\index.js:105:66
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
    at findModule (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:81:11)
    at findModuleFromOptions (C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schematics\angular\utility\find-module.js:26:38)
    at C:\workspace\tooling\tooling-examples\556-check\ruf560test5\node_modules\@schem
```

### Environment
@angular-devkit/architect v0.1301.2
@angular-devkit/build-angular v13.1.2
@angular-devkit/schematics v13.1.2
@nrwl/angular v13.3.11

<img width="605" alt="nrwl" src="https://user-images.githubusercontent.com/31273891/146939669-2ad49fcf-5995-46d1-b66a-f3a3cfea5435.png">

**Comment by Coly010** [comment] 2022-01-14 11:13
@sandeeppatidar30 
Thanks for filing the issue! 

I'm struggling to reproduce this locally. Would you be able to provide a minimal repo that I could clone that reproduces this error so I can investigate further?

**Comment by Coly010** [comment] 2022-01-19 10:43
This has been sitting a while now with no update. I'm going to close this issue as a result.

If there is any new information, feel free to tag me :)

**Comment by sandeeppatidar30** [comment] 2022-01-28 05:14
Hey @Coly010, 

I'm sorry i was busy in some work so could not update you.

Please find the attached repos to reproduce the issue.

I have attached 2 applications. First one is for "my-app" is my custom schematics application and second one  "nrwl1350" is a Nrwl workspace created using nrwl v13.5.0.

Steps to setup the applications -

1. Run "npm install" in my-app application.
2. Run "npm install" in nrwl1350 application.
3. Run "npm run build" in my-app, which generates a "dist/myapp" directory.
4. Run "npm link <path-to/dist/myapp>"  in nrwl1350 application.
5. Run "ng g @ruf/myapp:app" in nrwl1350 application.
6. Check the issue in console.

[my-app.zip](https://github.com/nrwl/nx/files/7955832/my-app.zip)
[nrwl1350.zip](https://github.com/nrwl/nx/files/7955841/nrwl1350.zip)

**Comment by seadonk** [comment] 2022-02-14 23:13
dup of https://github.com/nstudio/xplat/issues/286?

**Comment by sandeeppatidar30** [comment] 2022-02-18 07:41
i'm still facing this issue even with Nrwl v13.8.2 and @schematics/angular v13.2.3.

**Comment by sandeeppatidar30** [comment] 2022-02-18 16:14
@habtim, Did you run `nx g app` using external schematics? I have created my own schemaitcs and internally i'm running `nx g app` using `externalSchematic()` and i'm getting this issue.

e.g.
```ts
import { chain, externalSchematic, mergeWith, Rule, SchematicContext, template, Tree,  url } from '@angular-devkit/schematics';
   export default function(schema: Schema): Rule {
     return (host: Tree, context: SchematicContext) => {
   
       return chain([
         externalSchematic('@nrwl/angular', 'application', {
           name: 'myapp'
         })
       ])(host, context);
     };
   }
```

**Comment by habtim** [comment] 2022-02-18 16:43
@sandeeppatidar30
No, running `nx g app` in terminal works. 
I did experience same issue when running `externalSchematics` in a custom schematic.

**Comment by Coly010** [comment] 2022-02-21 10:59
@sandeeppatidar30 After running your reproduction, I do get the warning about writeWorkspace, but I do not get any errors. The warning is fine. It's just to make you aware that you could break your application by using `writeWorkspace` if you're not careful. That is fine.

**Comment by habtim** [comment] 2022-02-21 13:37
@Coly010 Could you verify [this repo](https://github.com/habtim/test-nrwl-generator), by running `nx workspace-generator application`? 
I dont get, why this error should not be reproduceable...

**Comment by sandeeppatidar30** [comment] 2022-02-21 14:26
@Coly010,

I'm able to reproduce this issue with error logs `Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.`

Did you make any changes to repo? It is a complete blocker for our application, we can not move ahead with this issue.

**Comment by Coly010** [comment] 2022-02-21 16:18
@habtim 
No error, just the warning. 
https://user-images.githubusercontent.com/12140467/154992782-93acf601-43d1-4ad7-8bd4-039e913765f4.mp4

**Comment by sandeeppatidar30** [comment] 2022-02-21 16:50
@Coly010,

May I know some details about your machine environment.

Node version  -
Npm version -
OS -

**Comment by Coly010** [comment] 2022-02-21 17:10
@sandeeppatidar30 

Node version - 16.14.0
Npm version - 8.3.1
OS - macOS 12.1

**Comment by habtim** [comment] 2022-02-21 22:12
Updated node to 16.14.0 and npm to 8.3.1
Updated global angular cli (to 13.8.1)
Deleted node_modules and ran `npm cache clean --force`

Still the same issue...  Running on win10 btw

**Comment by sandeeppatidar30** [comment] 2022-02-22 08:55
@Coly010,

I can confirm it works on macOS but fails on windows machine with error logs `Error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.`

**Comment by Coly010** [comment] 2022-02-22 09:28
Ah interesting. Ok, in that case, we'll need to do some further investigation. Some path mapping from UNIX-style to Windows-style must be borked.

**Comment by Quken** [comment] 2022-02-23 09:12
> Ah interesting. Ok, in that case, we'll need to do some further investigation. Some path mapping from UNIX-style to Windows-style must be borked.

@Coly010, I'm also faced with the same issue using Nrwl v13.8.1 on Windows 10 (on macOS, everything works fine). Are there any workarounds to fix this or any other thoughts?

**Comment by sandeeppatidar30** [comment] 2022-02-23 17:17
@zjkipping, it works till NX v13.2.4 with Angular v13.1.x, so if you are planning for migration then you can still try with NX v13.2.4 till we get the fix.

**Comment by zjkipping** [comment] 2022-02-23 17:21
@sandeeppatidar30 We have tried this upgrade three times. 13 then 13.2.x and now on latest 13.8.x. We have had issues spanning across cypress, jest, storybook, and eslint across those upgrades. This has been the first time everything has worked (with some minor fixes on our side) disregarding this issue with schematics for angular applications. So, we will probably stay put until a fix/work around is put through for this instead of backporting to a lesser version of everything.

**Comment by zjkipping** [comment] 2022-03-01 22:52
@Coly010 Hey, not to bother you too much, but is there any status update on this issue? Would this be something that is fixed in a month? or the more immediate future?

**Comment by Coly010** [comment] 2022-03-02 12:07
Still working on it. Not sure when a fix will land for this.

A workaround, which is admittedly more involved, but does work:

 - Change your schematic/generator to use Nx Devkit rather than Angular Devkit.
 
 The problem appears to be in the hand off to Angular Devkit, trying to narrow it down.
 
 If you have a schematic like the following using the Angular Devkit
 
 ```ts
import { Rule, chain, externalSchematic } from '@angular-devkit/schematics';
import { Tree } from '@nrwl/devkit';

export default function createApp(_options: any) {
  return function (_tree: Tree, schema: any): Rule {
    return chain([
      externalSchematic('@nrwl/angular'. 'application', { name: _options.name })
    ]);
  };
}
```

Then you can convert it to Nx Devkit by doing the following

Update `schema.json` to add: `"cli": "nx"`

Update the generator to be

```ts
import { Tree } from '@nrwl/devkit';
import { applicationGenerator } from '@nrwl/angular/generators';

export default async function createApp(tree: Tree, _options: any) {
  await applicationGenerator(tree, _options);
}
```

**Comment by zjkipping** [comment] 2022-03-03 19:19
This worked out very well for us! We ended up only rewriting the one schematic that uses the angular application generator. We ended up crafting some quick utility functions to map from Nx devkit's `Tree` type and Angular devkits `Tree` type for `create/overwrite` and `write`. Overall went smoothly and looking forward to rewriting the rest of our schematics over to using the nx devkit instead :)

**Comment by ennovum** [comment] 2022-05-02 15:44
@Coly010 have you been able to find something here? Since this is a blocker for me right now, I've spend a couple of our experimenting and found the following. 

The Nx app generator calls Ng app generator and then Ng component generator to create the Nx sample/welcome component. The component generator throws an error because it can't find a module file where it can add itself. So the `Tree` object on Ng side does not seem to "see" the generated app's files. But the `Tree` object on Nx side seems to see it all.

If I remove the sample/welcome component creation from the Nx generator, the generator is able to finish it's run. Of course there are no component files in the result, but the app's files are all there. Including the module file (which Ng generator did not see).

It seems to me the problem lies in chronology. My suspect #1 now is `wrapAngularDevkitSchematic` implementation and how it translates `Tree` between Nx and Ng.

I must admit I'm losing hope I can find the solution this way, the codebase is new to me. Also I'm currently unable to build either Nx or Ng projects, so I'm literally playing around with transpiled files... I could use some help. @Coly010 do you think you could find some time to look into this once more?

**Comment by ennovum** [comment] 2022-05-03 11:55
One more thing. I believe it broke between:
```
@nrwl/angular@13.2.4 @nrwl/workspace@13.2.4
```
and
```
@nrwl/angular@13.3.4 @nrwl/workspace@13.3.4
```

**Comment by leosvelperez** [comment] 2022-05-10 10:53
This issue has been solved in https://github.com/nrwl/nx/pull/10113 and the fix was released in [v14.1.0](https://github.com/nrwl/nx/releases/tag/14.1.0). Please make sure to migrate your workspace to that version or greater.

I'm closing this. If you still have an issue after migrating, feel free to reopen this issue or create a new one.

**Closed by leosvelperez** 2022-05-10 10:53 UTC
Labels: type: bug, scope: angular, os: windows

**Comment by pliniodng** [comment] 2022-08-05 12:31
Hey @leosvelperez, any chances this fix can be released on a patch version for NX 13? We have several repos running NX 13 with no bandwidth to migrate to 14, and this issue has been affecting several developers that are running windows.

**Comment by epliXs** [comment] 2023-01-23 22:13
> Using `libraryGenerator` from `'@nrwl/angular/generators'` instead works, the library is generated successfully, but I still get the warnings:
> 
> ```
> [NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json
> [NX] Double check workspace.json before proceeding
> ```

Note `libraryGenerator` has options `standaloneConfig` which supposed to omit changes to `workspace.json`, but result is the same, still showing warnings.
