### ISSUE TITLE
angular - v14.7.5 - Unable to generate components - The path provided for the component does not exist under the project root

### ISSUE THREAD

**Issue by PieterjanDeClippel** [nrwl/nx#12042] opened 2022-09-16 12:46 UTC
## Current Behavior

@nrwl/angular 14.7.5 - Unable to generate components

    Error: The path provided for the component (libs/lib-one/src/lib) does not exist under the project root (apps/wspapp). Please make sure to provide a path that exists under the project root.

## Expected Behavior

`nx generate component` should create a component

## Steps to Reproduce

Open an administrator cmd. Update @angular/cli and nx globally

    npm install --global @angular/cli@latest
    npm install --global nx@latest

Open a cmd in a path without spaces, and run

    npx create-nx-workspace --name wsp --app-name wspapp --preset angular --style=scss --nx-cloud false
    cd wsp
    nx g @nrwl/angular:lib lib-one --buildable --publishable --import-path @example/lib-one
    cd .\libs\lib-one\src\lib\
    
    nx g c comp-one --export
    > Cannot read properties of undefined (reading 'exists')
    // So we run
    nx generate component comp-one --export
    > Success

Environment

```
C:\repos\bsp\libs\lib-one\src\lib>nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : win32 x64
   npm  : 8.1.2

   nx : 13.10.6
   @nrwl/angular : 13.10.6
   @nrwl/cypress : 13.10.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.6
   @nrwl/eslint-plugin-nx : 13.10.6
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.6
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.6
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.6
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:

```

Now let's update the workspace to the latest stable nrwl version

    nx migrate latest

Open the root package.json and restore the version specifiers (`^` and `~`)

    npm update
    npx nx migrate --run-migrations

Now open a new cmd in the lib folder and run

```
PS C:\repos\wsp\libs\lib-one\src\lib> nx generate component comp-two --export --verbose

>  NX  Generating @nrwl/angular:component


 >  NX   The path provided for the component (libs/lib-one/src/lib) does not exist under the project root (apps/wspapp). Please make sure to provide a path that exists under the project root.


Error: The path provided for the component (libs/lib-one/src/lib) does not exist under the project root (apps/wspapp). Please make sure to provide a path that exists under the project root.
    at checkPathUnderProjectRoot (C:\repos\wsp\node_modules\@nrwl\angular\src\generators\component\component.js:34:15)
    at C:\repos\wsp\node_modules\@nrwl\angular\src\generators\component\component.js:14:9
    at Generator.next (<anonymous>)
    at C:\repos\wsp\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\repos\wsp\node_modules\tslib\tslib.js:114:16)
    at componentGenerator (C:\repos\wsp\node_modules\@nrwl\angular\src\generators\component\component.js:11:20)
    at Object.<anonymous> (C:\repos\wsp\node_modules\nx\src\command-line\generate.js:250:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\repos\wsp\node_modules\tslib\tslib.js:115:62)
```

```
PS C:\repos\wsp\libs\lib-one\src\lib> nx report
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

```

## Problem

    at C:\repos\wsp\node_modules\@nrwl\angular\src\generators\component\component.js:34:15

[checkPathUnderProjectRoot](https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/component/component.ts#L31)

[Here's what I did to debug NX schematics](https://www.youtube.com/watch?v=OGV4R0cPRPc)

    C:\repos\wsp\libs\lib-one\src\lib> node ..\..\..\..\node_modules\@nrwl\cli\bin\nx.js generate component comp-two --export --verbose

**Comment by leosvelperez** [comment] 2022-09-16 12:56
Thanks for reporting this!

This is a duplicate of #11919 and it has already been fixed in #11980. The fix should be released soon. Please keep an eye on the releases.

While waiting for the fix to be published, you can still generate the component by specifying the `--project` flag with the project name where the component is going to be generated. The fix removes this requirement when a path is provided.

**Closed by leosvelperez** 2022-09-16 12:56 UTC
Labels: type: bug
