### ISSUE TITLE
Uncaught Error: Automatic publicPath is not supported in this browser

### ISSUE THREAD

**Issue by gschuager** [nrwl/nx#10163] opened 2022-05-05 13:30 UTC
## Current Behavior

Newly created application using the react preset randomly fails to load in Firefox

## Steps to Reproduce

```
npx create-nx-workspace --preset=react
cd workspace
nx serve app
```

Opening `http://localhost:4200/` in Firefox and reloading several times results in the mentioned error almost half of the time.

The issue does not seem to occur in Chrome.

### Failure Logs

```
Uncaught Error: Automatic publicPath is not supported in this browser
    <anonymous> publicPath:14
    <anonymous> runtime.js:630
    <anonymous> runtime.js:1326
```

This is the browser view when it fails:

![image](https://user-images.githubusercontent.com/139658/166934169-45ec3c67-84a4-4d96-a93a-f607efc65248.png)

This is the browser view when it doesn´t fail:

![image](https://user-images.githubusercontent.com/139658/166934311-1c3f304d-6a27-4f96-b613-3220e34f5efa.png)

### Environment

```
>  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : linux x64
   npm  : 8.5.5

   nx : 14.1.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.1
   @nrwl/eslint-plugin-nx : 14.1.1
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.1
   @nrwl/js : 14.1.1
   @nrwl/linter : 14.1.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.1
   @nrwl/web : 14.1.1
   @nrwl/workspace : 14.1.1
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by hattiq** [comment] 2022-05-21 10:39
No solution for this? Any updates?

**Comment by hattiq** [comment] 2022-05-21 14:31
used this workaround solution https://stackoverflow.com/a/64715069. 
had to write a custom webpack config file following this  https://nx.dev/guides/customize-webpack.

**Comment by prmichaelsen** [comment] 2022-08-13 21:18
mind posting your webpack for posterity? did you have to use the federatedModule?

**Comment by bridzius** [comment] 2022-08-24 13:10
The same issue can be observed with `@nrwl/angular` when building Module Federated apps.

**Comment by joshstovall** [comment] 2022-11-09 15:41
> mind posting your webpack for posterity? did you have to use the federatedModule?

Ah yes Patryc, fancy seeing you here 🧐 what are the odds.

**Comment by de-robat** [comment] 2022-12-09 08:35
i expierienced a similar issue today, debugging showed that the runtime tries to autodetect the baseurl in the following way: if no public path has been set, then fetch all script tags from the document, get the src attribute of the last script tag you find and take its url to determine the base domain.

i now happen to have a inline scripttag as my last scripttag (injected script from my analytics tag manager) - therefore the error surfaced. the issue is, it sometime did load and it sometimes didn't as the injection was provoking a racecondition scenario. Just wanted to leave this hear, just in case it helps someone else

**Comment by xiongemi** [comment] 2023-04-14 00:40
closed this issue

**Closed by xiongemi** 2023-04-14 00:40 UTC
Labels: type: bug, scope: react

**Comment by JacobSiegle** [comment] 2023-04-19 22:08
In case anyone else ends up here due to publicPath make sure you are targeting ES2020! I was having issues where a remote MFE wouldn't load and it was b/c I was targeting ES2015 in one of my apps. ES2020 added support import.meta which is needed for public path to properly auto resolve.
