### ISSUE TITLE
Skipping migration for project XXX. Unable to determine 'tsconfig.json' file in workspace config.

### ISSUE THREAD

**Issue by abrahamsaanchez** [nrwl/nx#20172] opened 2023-11-10 07:36 UTC
### Current Behavior

When executing `nx migrate latest` and run the migrations to Angular 17 all my angular libraries failed with the message `Skipping migration for project XXX. Unable to determine 'tsconfig.json' file in workspace config.` and the migrations are not executed.

After all the error messages I get `✓  Updated Angular Material to version 17` and `✓  Updated Angular CDK to version 17` but no changes were made into my files.

I think there's a migration to migrate to the new's Angular control flow syntax, but it's not executed. Maybe is a configuration issue, but I can not fix it.

This is the `project.json` file from one of the Angular libraries,

```
{
    "$schema": "../../../../../../node_modules/nx/schemas/project-schema.json",
    "implicitDependencies": [
        "!core.ui.angular.storybook",
        "!testing.mocks.aggregate-root",
        "!testing.mocks.class",
        "!testing.mocks.commands.command",
        "!testing.mocks.commands.command-handler",
        "!testing.mocks.dependency-injection",
        "!testing.mocks.domain-events.domain-event",
        "!testing.mocks.domain-events.domain-event-failover-publisher",
        "!testing.mocks.domain-events.domain-event-subscriber",
        "!testing.mocks.entity",
        "!testing.mocks.express.express-http-server",
        "!testing.mocks.express.express-request",
        "!testing.mocks.express.express-response",
        "!testing.mocks.fastify.fastify-reply",
        "!testing.mocks.fastify.fastify-request",
        "!testing.mocks.logger",
        "!testing.mocks.queries.query",
        "!testing.mocks.queries.query-handler",
        "!testing.mocks.response",
        "!testing.mocks.translator",
        "!testing.mocks.ui.angular.components.search-bar-component",
        "!testing.mocks.ui.angular.messages-service",
        "!testing.mocks.ui.angular.navigation-service",
        "!testing.mocks.ui.angular.notifications-service",
        "!testing.mocks.ui.angular.translations-service",
        "!testing.mocks.websocket.websocket-message",
        "!testing.mocks.websocket.websocket-message-subscriber",
        "!testing.mothers.aggregate-root",
        "!testing.mothers.boolean",
        "!testing.mothers.date-range",
        "!testing.mothers.discounts",
        "!testing.mothers.email",
        "!testing.mothers.entity",
        "!testing.mothers.enum",
        "!testing.mothers.errors.authentication-error",
        "!testing.mothers.errors.invalid-argument-error",
        "!testing.mothers.errors.translatable-error",
        "!testing.mothers.float",
        "!testing.mothers.image",
        "!testing.mothers.integer",
        "!testing.mothers.message",
        "!testing.mothers.mongodb.mongodb-client-factory",
        "!testing.mothers.mongodb.mongodb-domain-event-failover-publisher",
        "!testing.mothers.mongodb.mongodb-environment-arranger",
        "!testing.mothers.name",
        "!testing.mothers.nif",
        "!testing.mothers.notification",
        "!testing.mothers.paragraph",
        "!testing.mothers.phone",
        "!testing.mothers.price",
        "!testing.mothers.rabbitmq.rabbitmq-configuration",
        "!testing.mothers.rabbitmq.rabbitmq-connection",
        "!testing.mothers.rabbitmq.rabbitmq-queue-name-formatter",
        "!testing.mothers.schedule",
        "!testing.mothers.time-range",
        "!testing.mothers.time-range.in-day-of-week",
        "!testing.mothers.timestamp",
        "!testing.mothers.translatable-string",
        "!testing.mothers.ui.angular.components.search-bar-component",
        "!testing.mothers.ui.angular.dialogs.dialog",
        "!testing.mothers.ui.shared.navigation-link",
        "!testing.mothers.url",
        "!testing.mothers.user",
        "!testing.mothers.uuid",
        "!testing.mothers.value-objects.day-of-week-value-object",
        "!testing.mothers.value-objects.iso-codes.iso-639-1-code-value-object",
        "!testing.mothers.value-objects.time-value-object",
        "!testing.mothers.value-objects.timestamp-value-object",
        "!testing.mothers.value-objects.uuid-value-object",
        "!testing.mothers.word",
        "!testing.utils.dependency-injection"
    ],
    "name": "core.ui.angular.components.alert",
    "prefix": "ditratec",
    "projectType": "library",
    "sourceRoot": "packages/core/ui/angular/components/alert/src",
    "tags": [],
    "targets": {
        "build": {
            "configurations": {
                "development": {
                    "tsConfig": "packages/core/ui/angular/components/alert/tsconfig.lib.json"
                },
                "production": {
                    "tsConfig": "packages/core/ui/angular/components/alert/tsconfig.lib.prod.json"
                }
            },
            "defaultConfiguration": "production",
            "executor": "@nx/angular:package",
            "options": {
                "project": "packages/core/ui/angular/components/alert/ng-package.json",
                "tailwindConfig": "packages/core/ui/angular/components/alert/tailwind.config.ts"
            },
            "outputs": ["{workspaceRoot}/dist/{projectRoot}"]
        },
        "lint": {
            "executor": "@nx/eslint:lint",
            "options": {
                "lintFilePatterns": [
                    "packages/core/ui/angular/components/alert/**/*.ts",
                    "packages/core/ui/angular/components/alert/package.json"
                ]
            },
            "outputs": ["{options.outputFile}"]
        },
        "publish": {
            "command": "ts-node packages/devkit/src/utils/script-runner --library=core.ui.angular.components.alert --script=packages/devkit/src/utils/scripts/library-publisher --version={args.semantic}"
        },
        "test": {
            "executor": "@nx/jest:jest",
            "options": {
                "jestConfig": "packages/core/ui/angular/components/alert/jest.config.ts",
                "passWithNoTests": false
            },
            "outputs": ["{workspaceRoot}/coverage/{projectRoot}"]
        }
    }
}
```

### Expected Behavior

I expect the migrations to run without an error.

### Steps to Reproduce

1. Having a NX 16 repo, execute `nx migrate latest`
2. Install the dependencies
3. Execute the migrations `nx migrate --run-migrations`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : linux-x64
   npm    : 10.1.0
   
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/esbuild        : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/node           : 17.1.1
   @nx/plugin         : 17.1.1
   @nx/storybook      : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.22
   @storybook/angular : 7.5.3
   ---------------------------------------
   Local workspace plugins:
         @ditratec/devkit
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'

    Skipping migration for project core.ui.angular.components.alert. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.drawer. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.fullscreen. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.language-selector. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.loader. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.loading-bar. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.logo. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.media-viewer. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.messages. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.notifications. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.search-bar. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.section. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.shortcuts. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.stepper. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.user-menu. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.confirmation. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.dialog. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.progress. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.directives.mat-vertical-stepper-scroller. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.icons. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.layout. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.navigation. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.pipes.date. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.pipes.humanize-milliseconds. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.scroll. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.services.media-watcher. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.shared.components.root. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.storybook. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.translations. Unable to determine 'tsconfig.json' file in workspace config.
    
      ✓  Updated Angular Material to version 17
    
    Skipping migration for project core.ui.angular.components.alert. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.drawer. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.fullscreen. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.language-selector. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.loader. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.loading-bar. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.logo. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.media-viewer. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.messages. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.notifications. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.search-bar. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.section. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.shortcuts. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.stepper. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.components.user-menu. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.confirmation. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.dialog. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.dialogs.progress. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.directives.mat-vertical-stepper-scroller. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.icons. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.layout. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.navigation. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.pipes.date. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.pipes.humanize-milliseconds. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.scroll. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.services.media-watcher. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.shared.components.root. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.storybook. Unable to determine 'tsconfig.json' file in workspace config.
    Skipping migration for project core.ui.angular.translations. Unable to determine 'tsconfig.json' file in workspace config.
    
      ✓  Updated Angular CDK to version 17
```

### Package Manager Version

10.1.0

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by evgenii-amber** [comment] 2023-11-10 09:04
Same problem. I'm aware of the workaround that involves exposing tsconfig through the build target, but is there another solution we could try?

**Comment by AdditionAddict** [comment] 2023-11-10 15:50
@evgenii-amber what's the workaround? Any idea if is works for non-buildable projects

**Comment by leosvelperez** [comment] 2023-11-13 10:03
Thanks for reporting this!

This is a known limitation. It's not something we can solve on the Nx side only, and it's down to how Angular migrations are written and the tooling used in Nx workspaces. We've been in contact with the Angular team to try to address this, but we don't have yet a solution.

You can see more context about the limitation/issue and workarounds in the following comment: https://github.com/nrwl/nx/issues/13733#issuecomment-1344466113.

@evgenii-amber there's no need to expose a tsconfig in build targets. This is only needed in test targets using Jest. Please see the comment linked above.

I'm going to close this since it's a known issue we can't address for the time being and there's a workaround. We'll continue looking for a solution for future releases. If you still have issues not described in the comment linked above, please feel free to reply here or create a separate issue with the specific details so we can troubleshoot it.

**Closed by leosvelperez** 2023-11-13 10:03 UTC
Labels: type: bug, scope: angular

**Comment by AdditionAddict** [comment] 2023-11-13 10:14
> Please note that in some cases, there's no real issue apart from the noisy logs. The runtime code of the non-buildable libs in an Nx workspace is actually processed as part of any app that consumes them. 

@leosvelperez the linked comment seems outdated - non buildable libs aren't being processed and I can't get the workarounds to work. 

Appreciate you're working with Angular behind the scenes and it's on them - perhaps an open issue on Angular issues would aid this? It's a blocking issue for me upgrading to v17

**Comment by leosvelperez** [comment] 2023-11-13 10:37
@AdditionAddict that comment is not outdated. It might seem old, but the situation hasn't changed. The runtime code of non-buildable libraries should be processed as long as they are imported by any application (all non-buildable libs should be imported by applications, otherwise, they should be independent publishable libs).

That said, if a specific migration from Angular does something differently than the rest of the migrations, then we need to identify that for sure. If this is not working for you, I'll need a reproduction so I can troubleshoot the issue. Please provide one with the details of which changes you're expecting to happen and the current outcome.

The issue is not on the Angular team alone. This is not an issue with Angular CLI projects because they write the migrations taking into account Angular CLI projects. Nx workspaces have some differences, and the migrations written by Angular are not flexible enough to handle that. It's a gray area whether they need to be or not. The migrations work for their tooling. That's why we've been in contact with them to see what can be done, but it's not as straightforward as we'd like it to be.

**Comment by muuvmuuv** [comment] 2023-11-20 11:52
Wouldn't it help if NX just temporarly adds a build target if it does not exist and removes it after migrations have run? Even if Angular has that limitation NX state to be an extension to Angular for monorepos so I expect a workaround/fix from NX. Or a generator that can add/remove the build target for the time beeing.

**Comment by muuvmuuv** [comment] 2023-11-20 12:51
For anyone that has a big project and needs a workaround, here is a workspace generator that adds a build target to all projects with a unique ID to remove it after the migration has run:

```ts
import {
  formatFiles,
  getProjects,
  ProjectConfiguration,
  Tree,
  updateProjectConfiguration,
} from "@nx/devkit"
import { gray, yellow } from "kleur/colors"

import { BuildTargetFixGeneratorSchema } from "./schema"

/** Unique tag to identify our change, must start with an `x-` as be XML schema. */
const SCHEMA_TAG = "x-g-by-btf"

function manipulateProjectTarget(tree: Tree, project: ProjectConfiguration, remove = false) {
  if (!tree.exists(project.root + "/tsconfig.json")) {
    console.error(gray(`[${project.root}]`), yellow(`Can't find tsconfig.json`))
    return
  }

  if (remove) {
    if (project.targets?.build && project.targets.build.options?.[SCHEMA_TAG]) {
      delete project.targets?.build
      console.log(gray(`[${project.root}]`), `Removed build target`)
    } else {
      console.log(gray(`[${project.root}]`), gray(`Skipping, not generated by us`))
    }
  } else {
    project.targets = project.targets || {}

    if (project.targets.build) {
      console.log(gray(`[${project.root}]`), gray(`Skipping, already exists`))
    } else {
      // Only add if not already exists
      project.targets = {
        build: {
          options: {
            tsConfig: project.root + "/tsconfig.json",
            [SCHEMA_TAG]: true,
          },
        },
        ...project.targets,
      }
      console.log(gray(`[${project.root}]`), `Added build target`)
    }
  }
}

export async function buildTargetFixGenerator(tree: Tree, options: BuildTargetFixGeneratorSchema) {
  const projects = getProjects(tree)

  for (const [name, project] of projects) {
    manipulateProjectTarget(tree, project, options.remove)
    updateProjectConfiguration(tree, name, project)
  }

  await formatFiles(tree)
}

export default buildTargetFixGenerator
```

**Comment by kuda1992** [comment] 2023-11-23 09:48
> For anyone that has a big project and needs a workaround, here is a workspace generator that adds a build target to all projects with a unique ID to remove it after the migration has run:
> 
> ```ts
> import {
>   formatFiles,
>   getProjects,
>   ProjectConfiguration,
>   Tree,
>   updateProjectConfiguration,
> } from "@nx/devkit"
> import { gray, yellow } from "kleur/colors"
> 
> import { BuildTargetFixGeneratorSchema } from "./schema"
> 
> /** Unique tag to identify our change, must start with an `x-` as be XML schema. */
> const SCHEMA_TAG = "x-g-by-btf"
> 
> function manipulateProjectTarget(tree: Tree, project: ProjectConfiguration, remove = false) {
>   if (!tree.exists(project.root + "/tsconfig.json")) {
>     console.error(gray(`[${project.root}]`), yellow(`Can't find tsconfig.json`))
>     return
>   }
> 
>   if (remove) {
>     if (project.targets?.build && project.targets.build.options?.[SCHEMA_TAG]) {
>       delete project.targets?.build
>       console.log(gray(`[${project.root}]`), `Removed build target`)
>     } else {
>       console.log(gray(`[${project.root}]`), gray(`Skipping, not generated by us`))
>     }
>   } else {
>     project.targets = project.targets || {}
> 
>     if (project.targets.build) {
>       console.log(gray(`[${project.root}]`), gray(`Skipping, already exists`))
>     } else {
>       // Only add if not already exists
>       project.targets = {
>         build: {
>           options: {
>             tsConfig: project.root + "/tsconfig.json",
>             [SCHEMA_TAG]: true,
>           },
>         },
>         ...project.targets,
>       }
>       console.log(gray(`[${project.root}]`), `Added build target`)
>     }
>   }
> }
> 
> export async function buildTargetFixGenerator(tree: Tree, options: BuildTargetFixGeneratorSchema) {
>   const projects = getProjects(tree)
> 
>   for (const [name, project] of projects) {
>     manipulateProjectTarget(tree, project, options.remove)
>     updateProjectConfiguration(tree, name, project)
>   }
> 
>   await formatFiles(tree)
> }
> 
> export default buildTargetFixGenerator
> ```

How do you even run this workaround, struggling to work it out

**Comment by lsonnenschein** [comment] 2023-11-24 14:54
Managed to run migrations with following steps, building upon that generator. I needed to add tsConfig to existing build targets where missing, too.

1) https://nx.dev/extending-nx/recipes/local-generators

Following this create a plugin if you don't have one. I called mine `tools`. Then create a generator I called mine `temporaryBuildTarget`

2) Replace generator.ts with 
```ts
import {
  formatFiles,
  getProjects,
  ProjectConfiguration,
  Tree,
  updateProjectConfiguration,
} from '@nx/devkit';

import { TemporaryBuildTargetGeneratorSchema } from './schema';

/** Unique tag to identify our change, must start with an `x-` as be XML schema. */
const SCHEMA_TAG = 'x-g-by-btf';
const TSCONFIG_TAG = 'x-g-by-btf-tsconfig';

function manipulateProjectTarget(
  tree: Tree,
  project: ProjectConfiguration,
  remove = false
) {
  const tsconfigPath = project.root + '/tsconfig.json';
  if (!tree.exists(tsconfigPath)) {
    console.error(`[${project.root}]`, `Can't find tsconfig.json`);
    return;
  }

  // Remove the build target or tsconfig if it exists and is tagged
  if (remove) {
    // Remove whole build target
    if (project.targets?.build && project.targets.build.options?.[SCHEMA_TAG]) {
      delete project.targets?.build;
      console.log(`[${project.root}]`, `Removed build target`);
    }
    // remove tsconfig only
    else if (project.targets?.build?.options?.[TSCONFIG_TAG]) {
      delete project.targets.build.options.tsConfig;
      delete project.targets.build.options[TSCONFIG_TAG];
      console.log(`[${project.root}]`, `Removed tsconfig.json`);
    }
    // Remove nothing
    else {
      console.log(
        `[${project.root}]`,
        `Skipping tsconfig removal, not tagged or does not exist`
      );
    }

    // Add build target or tsconfig if it doesn't exist and tag it for clean removal
  } else {
    project.targets = project.targets || {};

    // Build target exists already
    if (project.targets.build) {
      // Ts config mising
      if (!project.targets.build.options.tsConfig) {
        project.targets.build.options = {
          ...project.targets.build.options,
          tsConfig: tsconfigPath,
          [TSCONFIG_TAG]: true,
        };
        console.log(`[${project.root}]`, `Added tsconfig only`);
      } else {
        // Ts config exists, nothing to do
        console.log(`[${project.root}]`, `Skipping, already exists`);
      }
      // Add build target with tsconfig
    } else {
      project.targets = {
        build: {
          options: {
            tsConfig: tsconfigPath,
            [SCHEMA_TAG]: true,
          },
        },
        ...project.targets,
      };
      console.log(`[${project.root}]`, `Added build target`);
    }
  }
}

export async function temporaryBuildTarget(
  tree: Tree,
  options: TemporaryBuildTargetGeneratorSchema
) {
  const projects = getProjects(tree);

  for (const [name, project] of projects) {
    manipulateProjectTarget(tree, project, options.remove);
    updateProjectConfiguration(tree, name, project);
  }

  await formatFiles(tree);
}

export default temporaryBuildTarget;
```

schema.d.ts with 
```ts
export interface TemporaryBuildTargetGeneratorSchema {
  remove: boolean;
}
```
schema.json with 

```jsonschema
{
  "$schema": "http://json-schema.org/schema",
  "$id": "TemporaryBuildTarget",
  "title": "",
  "type": "object",
  "properties": {
    "remove": {
      "type": "boolean",
      "description": "",
      "$default": {
        "$source": "argv",
        "index": 0
      },
      "x-prompt": "Remove the build target?"
    }
  }
}
```

3) Run  `nx generate tools:temporary-build-target` (don't remove)

4) Run `nx migrate --run-migrations`

5) Run  `nx generate tools:temporary-build-target` (remove)


In my case migrations ran through successfully - without actually making any changes🥳. Exciting stuff. Ah well, at least I don't need to fomo now, I guess.

**Comment by kuda1992** [comment] 2023-11-25 22:08
Thanks, this worked.

**Comment by johngrimsey** [comment] 2023-12-16 14:44
Thanks @lsonnenschein !
