### ISSUE TITLE
Running migration update-angular-config-v12 results in Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by yharaskrik** [nrwl/nx#5655] opened 2021-05-13 20:10 UTC
## Current Behavior

Running migration `update-angular-config-v12` results in `Cannot read property 'startsWith' of undefined`

## Expected Behavior

migration succeeds

## Steps to Reproduce

`yarn nx migrate latest`
`yarn`
`yarn nx migrate --run-migrations`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

>  NX  Running migrations from 'migrations.json'
```
Running migration update-webpack-browser-config
Successfully finished update-webpack-browser-config
---------------------------------------------------------
Running migration update-storybook
Successfully finished update-storybook
---------------------------------------------------------
Running migration update-angular-eslint-rules
Successfully finished update-angular-eslint-rules
---------------------------------------------------------
Running migration update-angular-config-v12
Cannot read property 'startsWith' of undefined
/repo/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/cv/ryn9x0td5jd5dcmv6l2v8qn80000gn/T/tmp-7617-kbvcwfaGiqNx/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.handler (/repo/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:90:25)
    at Object.runCommand (/repo/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/repo/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/repo/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/repo/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (/repo/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7701,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```

>  NX  Report complete - copy this into the issue template

  Node : 12.20.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.3.1
  @nrwl/cli : 12.3.1
  @nrwl/cypress : 12.3.1
  @nrwl/devkit : 12.3.1
  @nrwl/eslint-plugin-nx : 12.3.1
  @nrwl/express : 12.3.1
  @nrwl/jest : 12.3.1
  @nrwl/linter : 12.3.1
  @nrwl/nest : 12.3.1
  @nrwl/next : Not Found
  @nrwl/node : 12.3.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.1
  @nrwl/web : 12.3.1
  @nrwl/workspace : 12.3.1
  @nrwl/storybook : 12.3.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

✨  Done in 0.85s.
```

**Comment by GeorgeKnap** [comment] 2021-05-13 20:15
Mine does the same after running `Running migration migration-v12-activated-route-snapshot-fragment`

**Comment by yharaskrik** [comment] 2021-05-13 20:16
As you submitted that comment that migration is running for me! Ill report back.

**Comment by yharaskrik** [comment] 2021-05-13 20:20
@GeorgeKnap it looks like yours happened during `Running migration update-jest-preset-angular-8-4-0` not `migration-v12-activated-route-snapshot-fragment`

**Comment by GeorgeKnap** [comment] 2021-05-13 20:21
@yharaskrik I guess yes, on router snapshot fragment it hangs a long time and then fails with the log above.

**Comment by yharaskrik** [comment] 2021-05-13 20:22
That is probably cause the snapshot one needs to traverse your whole repo to find all the places it needs to update then the next two are fast and the jest preset one fails fast.

**Comment by dean-g** [comment] 2021-05-13 20:38
Got the same issue. any luck. please advise 
![image](https://user-images.githubusercontent.com/12157452/118184661-3c072400-b401-11eb-985d-d392daa3cba8.png)

**Comment by dean-g** [comment] 2021-05-13 20:39
got into the same issue

Running migration update-angular-config-v12
Cannot read property 'startsWith' of undefined

**Comment by yharaskrik** [comment] 2021-05-13 20:45
Mine completed, the only one i had an issue with was the original one reported the same as @dean-g

**Comment by dean-g** [comment] 2021-05-13 20:48
@yharaskrik same here. looks like that is a very important step. 
{
      "version": "12.0.0-next.0",
      "factory": "./update-12/update-angular-config",
      "description": "Remove deprecated options from 'angular.json' that are no longer present in v12.",
      "package": "@angular/cli",
      "name": "update-angular-config-v12"
    },

**Comment by yharaskrik** [comment] 2021-05-13 20:49
I am running builds now and will keep track of the things I run into that i needed to change.

**Comment by dean-g** [comment] 2021-05-13 20:50
@brandonroberts @isaacplmann Can you please help me with this?

**Comment by yharaskrik** [comment] 2021-05-13 20:58
Ensure `aot` is either set to `true` or not set to `false` if `buildOptimizer` is true (default true I believe)

**Comment by dean-g** [comment] 2021-05-13 20:59
both my aot and buildOptimizer is set to true

**Comment by yharaskrik** [comment] 2021-05-13 21:01
Sorry that is just one of the things i think that migration takes care of that didnt for me since it failed.

**Comment by dean-g** [comment] 2021-05-13 21:18
my storybook is not working!. and the app became very slow. stuck with 'Generating browser application bundles (phase: building)..."

**Comment by dean-g** [comment] 2021-05-13 21:27
storybook compiled successfully but not showing up the URL, 

![image](https://user-images.githubusercontent.com/12157452/118189779-d79b9300-b407-11eb-8d37-aab71c9cbfbc.png)

**Comment by brandonroberts** [comment] 2021-05-13 21:27
@dean-g we're monitoring and looking into issues with migrations. If you can reproduce it outside your project, please file a bug.

**Comment by dean-g** [comment] 2021-05-13 21:34
@brandonroberts my app is not starting. it's got stuck with the following line, 

![image](https://user-images.githubusercontent.com/12157452/118190502-cf902300-b408-11eb-9af9-38f85b5639d6.png)

all those happening in my project not outside. I can't share those.

**Comment by brandonroberts** [comment] 2021-05-13 21:39
Are you using the @angular-devkit/build-angular for building/serving or a custom builder?

**Comment by dean-g** [comment] 2021-05-13 21:43
for build: 
"builder": "@angular-builders/custom-webpack:browser"
for serve: 
"builder": "ngx-build-plus:dev-server",

**Comment by dean-g** [comment] 2021-05-13 21:52
also getting wired warning: 
"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

**Comment by dean-g** [comment] 2021-05-13 22:00
also, getting an error for 'storybook-addon-designs' plugin. I gotta comment that to avoid an error. like I mentioned, the build got succeeded but never showing up the URL for storybook to render

**Comment by GeorgeKnap** [comment] 2021-05-14 05:31
When the migration fails whot should I do now?
Can I just undo all the changes made by the tool and try to run the upgrade later? 
 Or is it going to cause any inconsistent state and problems later?

**Comment by leosvelperez** [comment] 2021-05-14 09:30
> Running migration `update-angular-config-v12` results in `Cannot read property 'startsWith' of undefined`

@yharaskrik, @dean-g I've been trying to reproduce this issue and so far, I've only been able to reproduce it when there is a project with a target without an `executor|builder` specified in the workspace configuration.

Could you please make sure all your targets have a `builder|executor` property?

**Comment by leosvelperez** [comment] 2021-05-14 09:42
> for build:
> "builder": "@angular-builders/custom-webpack:browser"
> for serve:
> "builder": "ngx-build-plus:dev-server",

Angular 12 now needs Webpack 5. Those custom builders are still on Webpack 4 and don't support Webpack 5. You'd need to wait for them to support it. In the repo for the `@angular-builders/custom-webpack` there is this issue you can follow https://github.com/just-jeb/angular-builders/issues/972.

> also getting a wired warning:
> "BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

In Angular 12 there is a breaking change where schemas are validated again the [JSON Schema Draft 07](https://json-schema.org/draft-07/json-schema-release-notes.html). There is nothing for you to do here, but the above custom builders need to update their schema to meet the specs.

**Comment by dean-g** [comment] 2021-05-17 19:23
Thanks a lot, @leosvelperez. 

Do you have any suggestions towards replacing @angular-builders/custom-webpack builder? 

that builder is using customWebpackConfig config. not sure how to replace that with nrwl. please advise

**Comment by leosvelperez** [comment] 2021-05-18 08:20
> Do you have any suggestions towards replacing @angular-builders/custom-webpack builder?
> 
> that builder is using customWebpackConfig config. not sure how to replace that with nrwl. please advise

Keep an eye on https://github.com/nrwl/nx/pull/5609 where we are adding support for passing a custom Webpack config to the `@nrwl/angular:webpack-browser` executor. It should be merged soon and released on a patch version.

**Comment by leosvelperez** [comment] 2021-05-18 08:33
@yharaskrik could you please confirm if the issue was happening due to a target missing its `executor|builder` in your workspace configuration or if it's happening because of something else?

**Comment by yannickglt** [comment] 2021-05-18 12:02
The solution to me was to upgrade to Webpack 5 following the @leosvelperez advice.

Adding a migration step to ensure Webpack 5 is installed (and used in the `package.json`) would be safer.

**Comment by dean-g** [comment] 2021-05-19 14:31
@leosvelperez Do you have any advice toward replacing "builder": "ngx-build-plus:dev-server", with nrwl builders?

**Comment by dean-g** [comment] 2021-05-19 14:34
I took the latest version upgrade(12.3.4). Also replaced @angular-builders/custom-webpack with the @nrwl/angular:webpack-browser builder. but still, application build got stuck in the following line,  

⠴ Generating browser application bundles (phase: building)...

**Comment by leosvelperez** [comment] 2021-05-19 15:08
> @leosvelperez Do you have any advice toward replacing "builder": "ngx-build-plus:dev-server", with nrwl builders?

> I took the latest version upgrade(12.3.4). Also replaced @angular-builders/custom-webpack with the @nrwl/angular:webpack-browser builder. but still, application build got stuck in the following line,
> 
> ⠴ Generating browser application bundles (phase: building)...

We don't have a like-for-like replacement for those custom webpack builders. You might still need to wait for those third-party builders to update and support Webpack 5.

That said, you could have a setup with Nx core executors where things should work, but the development experience won't be exactly the same:
- For the `build` target, you could use the `@nrwl/angular:webpack-browser` executor which from the 12.3.4 version accepts a `customWebpackConfig` option.
- For the `serve` target, you could use the `@nrwl/web:file-server` executor specifying the `buildTarget`.

As I mentioned above, this is not a like-for-like replacement of what you have today. The `@nrwl/web:file-serve` is an executor we still need to polish and add features to be on par with other executors providing serving capabilities. It doesn't support all the functionalities the `ngx-build-plus:dev-server` or `@angular-devkit/build-angular:dev-server` do (e.g. it doesn't reload the page on change, it doesn't support SPA routes, etc.).

**Comment by dean-g** [comment] 2021-05-20 22:26
Thank a lot @leosvelperez 

I made my app running now. but my story book build is failing and not generating the URL to test. 

Here is the ERROR: 
NX   ERROR  Running target "stories:storybook" failed

![image](https://user-images.githubusercontent.com/12157452/119056520-70925700-b990-11eb-8d6b-bb772ceabce7.png)


@leosvelperez Can you please advise on my storybook?

**Comment by leosvelperez** [comment] 2021-05-21 08:57
@dean-g let's try to keep this thread focused on the original issue, otherwise is hard to track the different issues being discussed here 🙂 

For the Storybook issue, please, take a look at https://github.com/nrwl/nx/issues/5688 where there's already some good info about the issue and you can follow it for updates.

**Comment by un33k** [comment] 2021-06-02 18:42
I do have a bit of information that might help NX folks to combat this anomaly which happens on multiple versions of node. 

Here are some info:
```txt
node: v12.22.1
yarn: v1.22.10
nx: 12.3.6
```

Migration was moving from 11 to 12 and it failed ONLY on .. .
```json
    {
      "version": "12.0.0-next.0",
      "factory": "./update-12/update-angular-config",
      "description": "Remove deprecated options from 'angular.json' that are no longer present in v12.",
      "package": "@angular/cli",
      "name": "update-angular-config-v12"
    }
```

My recommendation is to remove the above and continue with your migration, but keep a copy of the above to be done later when we have a solution. 

My steps:

1 - Ran the migration which failed with an ambiguous message
```txt
Running migration update-angular-config-v12
Cannot read property 'startsWith' of undefined
.../node_modules/yargs/build/lib/yargs.js:1132
throw err;
```

2- Verified the configured npm proxy 
```bash
npm config get proxy
npm WARN invalid config proxy=""
npm WARN invalid config Must be a full url with 'http://'
null
```

3- Tried to ensure the command is not choking on a null proxy
```bash
npm config set proxy "http://registry.npmjs.org/"
```

4- Ran the migration command again 
```bash
yarn nx migrate --run-migrations=migrations.json    
yarn run v1.22.10
$ nx migrate --run-migrations=migrations.json
.../node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at taoPath (.../node_modules/@nrwl/workspace/src/command-line/nx-commands.js:320:21)
    at Object.handler (.../node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:19)
    at Object.runCommand (.../node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (.../node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (.../node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (.../node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (.../node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 44253,
  stdout: null,
  stderr: null
}
```

5- The error moved from `startWith` to another failure within nx cli
```txt
So, something is trying to access npm proxy during that step of the migration. Why?
```

*Please note*:  I don't have a valid proxy server , so the second error could be a legitimate fetch error of a package.

TODO:  Nx folks, the above info is the result of a bit of debugging, and I am hoping it gives you enough info to move forward.

**Comment by leosvelperez** [comment] 2021-06-04 09:44
@un33k thanks for spending some time to troubleshoot this.

Unfortunately, as you mentioned, that's not a valid proxy server (it's the actual registry url), so the error you got in step 4 is because the installation of the latest version of `nrwl/tao` failed, which is the first step of the migration process (you can locally try installing any package with that proxy and you'll see the failure). So, the error changed not because the initial error was fixed, but because it didn't even get to the point of running the migrations. That particular migration in itself doesn't fetch or install any package, you can see the migration source code [here](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/migrations/update-12/update-angular-config.ts)

Having the proxy set to an empty string is invalid. As shown in step 2, you'll get some warnings, but NPM will not use it when it's invalid and you can install packages as if it was not set. If you're not behind a proxy you can remove the warnings by running `npm config set proxy null`.

Regarding the issue in this thread, as I mentioned in [this comment](https://github.com/nrwl/nx/issues/5655#issuecomment-841129955), it seems it could be caused by having some targets in the workspace configuration without the `builder` or `executor` property. The migration assumes every target will always have a `builder` property (`executor` in the new workspace format by Nx, it gets translated when needed to `builder`) and calls `startsWith` on that property.

Please make sure all your targets have the `builder` or `executor` property specified. If that's not the case, or the problem still persists after this, I'll need a reproduction repo to troubleshoot it.

**Comment by un33k** [comment] 2021-06-04 15:27
@leosvelperez Yep, `npm config set proxy 'any string'` will remove the `startWith` error and `npm config rm proxy` will reintroduce the `startWith` error.  I happen to use the registry as `any string`, but it can be anything non-null string.

As far as the builder and executor, it would be great for `NX` to print a meaningful error message if possible.  This is due to the fact that `Nx` moves a lot of things around, to make things work, people or 3rd party packages recommend manual updates to angular.json, and it would be nice to see an error message if something is making `nx` unhappy.

**Comment by leosvelperez** [comment] 2021-06-04 17:05
> @leosvelperez Yep, `npm config set proxy 'any string'` will remove the `startWith` error and `npm config rm proxy` will reintroduce the `startWith` error. I happen to use the registry as `any string`, but it can be anything non-null string.

I'm not sure I understand what you mean here. Setting the proxy to any non-null string that's not a valid proxy will fail any package installation, regardless of if it's done by running migrations or by just installing a new package, that's just how NPM works. This particular issue doesn't relate to the presence of a proxy or not.

> As far as the builder and executor, it would be great for `NX` to print a meaningful error message if possible. This is due to the fact that `Nx` moves a lot of things around, to make things work, people or 3rd party packages recommend manual updates to angular.json, and it would be nice to see an error message if something is making `nx` unhappy.

I'm afraid we can't provide a better error message for this one. This particular migration is not an Nx migration. As you can see in the previous comment, where I shared a link to the migration source code, this is a migration from the `@schematics/angular` package which is authored by the Angular CLI team. The error that is being shown by Nx, is the error that is being thrown by that migration.

**Comment by un33k** [comment] 2021-06-04 22:09
@leosvelperez I think another repo out there with similar issue (& proxy fix) threw me off on a wrong path.  And you are right that a target is missing a builder and the issue is from the following line in ng upgrade ... Thx.

```javascript
 // update-angular-config.js
 for (const [, target] of workspace_1.allWorkspaceTargets(workspace)) {
   if (!(target === null || target === void 0 ? void 0 : target.builder.startsWith('@angular-devkit/build-angular'))) {
      continue;
   }
   // ...
 }
```

I hope someday angular publishes a `ng check angular.json` command so people can find out what is going on exactly.

**Comment by leosvelperez** [comment] 2021-06-05 12:24
For anyone arriving at this issue, please check your workspace config and make sure all your targets have a builder specified.

I'm closing this one since it's not an Nx issue and a solution has been found. Please feel free to reopen it if the provided solution doesn't work.

**Closed by leosvelperez** 2021-06-05 12:24 UTC
Labels: scope: angular, type: bug

**Comment by zoechi** [comment] 2021-12-10 07:19
@leosvelperez what if the target doesn't need a builder?
I have an angular library module that only contains styles.
It needs `architect.build.options.styles so that the styles can be used in other modules, but the other entries like 
builder, 
options { outputPath, index, main, tsConfig }
don't make any sense here

**Comment by leosvelperez** [comment] 2021-12-10 09:44
@zoechi as I mentioned before, that particular migration is from the `@schematics/angular` package, there's nothing we can do about it. I think your options are (in no particular order):

- Comment the library module configuration to run the migration and after is run, uncomment it again.
- Remove that particular migration.
- Create an issue on the Angular CLI repo to get it to handle your scenario.

If you don't have many projects with the issue, the first option might be the best one to unblock yourself and still get everything else migrated.

**Comment by zoechi** [comment] 2021-12-20 19:48
@leosvelperez thanks for looking into it 👍. I'll follow your suggestions
