### ISSUE TITLE
Fails to lint library

### ISSUE THREAD

**Issue by siberian-man** [nrwl/nx#3294] opened 2020-07-09 12:17 UTC
## Current Behavior

I have an Nx project (not an Angular one). And I have created a lib named 'api'. 

If I execute: `npm run lint api` it fails with the following error:

> Cannot find module '@angular-devkit/build-angular/package.json'

If I install `@angular-devkit/build-angular`, everything works as expected. 
But I suppose, it should be already installed by Nx. I don't think, it's correct if I install it by myself.

## Expected Behavior

It should successfully perform linting of my library.

I don't know whether it was working before, because I haven't used Nx before.

## Steps to Reproduce

Just create an Nx project (not an Angular one) and run aforementioned command.

### Failure Logs

```
npm run lint api

> nx workspace-lint && nx lint "api"


> nx run api:lint 
Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /Users/victor/Development/projects/healthy-intellect/hi/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /Users/victor/Development/projects/healthy-intellect/hi/node_modules/@angular-devkit/architect/node/index.js
- /Users/victor/Development/projects/healthy-intellect/hi/node_modules/@nrwl/tao/src/commands/run.js
- /Users/victor/Development/projects/healthy-intellect/hi/node_modules/@nrwl/tao/index.js
- /Users/victor/Development/projects/healthy-intellect/hi/node_modules/@nrwl/cli/lib/run-cli.js
```

### Environment

  @nrwl/angular : Not Found
  @nrwl/cli : 9.5.1
  @nrwl/cypress : Not Found
  @nrwl/eslint-plugin-nx : 9.5.1
  @nrwl/express : Not Found
  @nrwl/jest : 9.5.1
  @nrwl/linter : 9.5.1
  @nrwl/nest : 9.5.1
  @nrwl/next : Not Found
  @nrwl/node : 9.5.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.5.1
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3

**Comment by jdpearce** [comment] 2020-07-17 12:48
Thanks for raising this @siberian-man  - unfortunately I can't reproduce this issue. Can you provide a link to a repo where this happens? Or exact steps to reproduce?

I've tried the following steps but it works fine 🤷‍♀️ (this all results in an Nx report identical to yours)

- `npx create-nx-workspace test --preset=empty`
- `cd test`
- `npm i -D @nrwl/nest`
- `nx g @nrwl/nest:application api`
- `npm run lint api`

Was there something unusual about the way you created the workspace?

**Comment by bekos** [comment] 2020-09-14 11:46
@siberian-man thx for reporting, but I cannot reproduce the issue either 😕 I am going to close this now, as it is not actionable atm, but feel to to reopen if you have more info that will help us understand your case.

**Closed by bekos** 2020-09-14 11:46 UTC
Labels: blocked: repro needed, scope: linter, type: bug

**Comment by siberian-man** [comment] 2020-10-02 03:19
@jdpearce @bekos  Sorry for the long silence. I suppose, you were unable to reproduce because api is a library in my setup, not an application. I also can successfully lint applications. But it fails to lint library. 

A couple of additional notes:
- I migrated Nx to v 10.2 and the issue remains
- Bit locally and globally installed Nx fails to lint library:
nx lint api - fails
npm run nx lint api - fails

**Comment by michael-letcher** [comment] 2020-10-02 04:46
I'm running into this issue, it only has happened to a library that uses ES Lint rather than TS Lint. Not sure what Linter you are using @siberian-man

**Comment by bekos** [comment] 2020-10-02 06:48
@michael-letcher @siberian-man there are already major improvements for ESLint support in the upcoming 10.3 release, so probably this will not be an issue anymore. Nevertheless, if you can provide the reproduction steps, or even better a reproduction repository it will help us  jump right into the problem, debug and provide the fix. Otherwise, you understand that this is very difficult.

**Comment by michael-letcher** [comment] 2020-10-07 04:56
@bekos Tried out 10.3 and this fixed the issue.

**Comment by AmirAlOmari** [comment] 2020-12-16 13:44
Happens to me when scaffold workspace with an "empty" preset. Seems like there is no "lint" command at all

Doesn't happen when scaffold with an "angular-nest" preset. IMO, it also doesn't fail in any preset where angular included, didn't test them all, kinda idea 🤷 

Current `create-nx-workspace` version is 11.0.8
