### ISSUE TITLE
run target with multiple configuration profiles not supported

### ISSUE THREAD

**Issue by josketres** [nrwl/nx#10609] opened 2022-06-07 07:18 UTC
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

- Support for running a target with multiple configuration profiles. 
- `nx run my-app:build --configuration=production,theme-dark`

## Motivation

- The angular CLI `ng` supports this already.
- It is useful when doing multiple builds of the same project. In my case, I need to build the same app with multiple themes, which includes some file replacements.

## Suggested Implementation

- Merge the configuration options from all the given configuration profiles

**Comment by FrozenPandaz** [comment] 2022-06-07 19:58
This is a duplicate of https://github.com/nrwl/nx/issues/2839

Please read the discussion there and continue the discussion there.

**Closed by FrozenPandaz** 2022-06-07 19:58 UTC
Labels: type: feature
