### ISSUE TITLE
Cypress generator inconsistency

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#21881] opened 2024-02-20 09:49 UTC
### Current Behavior

When generating an application (i.e React), and choosing Cypress/Playwright for e2e, it will create 2 separate folders for the app and the e2e project (e.g. `todos` & `todos-e2e`).
However, when generating a Cypress/Playwright configuration for an existing project, it would create the configuration inside the application folder, even if a different directory is provided (e.g. `--directory=../todos-e2e`)

### Expected Behavior

The configuration generation should be consistent with the app generation.
Personally, I prefer 2 different folders 😉 

### Steps to Reproduce

1. Create an integrated repo with a React app and an e2e project
2. Now generate a React app without an e2e project (e.g. `todos`)
3. Generate an e2e project for this app (`nx g @nx/cypress:configuration --project=todos`)

### Nx Report

```shell
Node   : 20.11.0
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx (global)        : 18.0.4
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/linter         : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/workspace      : 18.0.4
   @nx/cypress        : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/playwright     : 18.0.4
   @nx/react          : 18.0.4
   @nrwl/tao          : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2024-02-20 11:44
Thanks for reporting this!

This is by design. The `configuration` generator just adds the needed configuration for an existing project. It's not a project generator. It's not meant to create new projects, and it doesn't prescribe/force you to have separate projects for e2e. If you want to have a separate project, you can first manually create a separate folder with a project.json and tsconfig.json file or create a simple generator to do so for you and then run the `configuration` generator.

On the other hand, the `application` generators from Nx Core plugins are a bit more opinionated and create a separate project (for the time being, at least). They do exactly what I mentioned above, create a new project first and then invoke the `configuration` generator. Please note that having separate e2e projects was more of a requirement before the introduction of [inputs](https://nx.dev/reference/inputs), but now, you can have them in the same project and still [fine-tune your inputs](https://nx.dev/recipes/running-tasks/configure-inputs) accordingly.

I'm going to close this since we're not planning to introduce project generators for e2e projects.

**Closed by leosvelperez** 2024-02-20 11:44 UTC
Labels: type: bug

**Comment by danr-za** [comment] 2024-02-20 11:48
@leosvelperez how about introducing a selection in application generators whether e2e will be generated in a separate project or not?

**Comment by leosvelperez** [comment] 2024-02-20 11:59
I think that has been discussed internally in the past, but don't know what the outcome was. Let me ask and I'll get back to you.

**Comment by leosvelperez** [comment] 2024-02-21 13:10
@danr-za I confirm we're not planning to make any changes to our current generators. There are no plans to generate applications with the e2e configuration in the same project. The intended DX to set up a separate E2E project for an existing application is to:

- generate a project with `@nx/js:library` or `@nx/workspace:library`
- run the Cypress/Playwright `configuration` generator for that new project

I'll check later whether we should better surface this information in the Cypress and Playwright plugin docs.
