### ISSUE TITLE
Package version in generated package.json of build step is not updated when running `nx release version`.

### ISSUE THREAD

**Issue by thdk** [nrwl/nx#20936] opened 2023-12-28 14:24 UTC
### Current Behavior

Context: 

I have new nx workspace. It contains a single package for a node cli application.

```
apps/cli/
  -package.json
  - src
      - cli.ts
```
I use the esbuild executor which produces:

```
dist/apps/cli/
- cli.js
- package.json
```

Both the `package.json` in  `apps/cli` folder and the `package.json` in the `dist/apps/cli` folder contains the **old** version number at this moment.

When running `nx release version`. Only the `package.json` in `apps/cli` folder is updated with the new version.

Now the publish part.

I spent some time to figure out if the publish command should be run from `dist/apps/cli` or from `apps/cli`. Depending on the choice here, I had to adjust the `outputPath` of the esbuild executor and assure the correct value for `packageRoot` option of the `release-publish` executor is  used. In case the `outputPath` of esbuild is set to `apps/cli` we can leave the default `{projectRoot}` but when `outputPath` is set to `dist/apps/cli`  then I thought the `packageRoot` should be set to `dist/apps/cli`. 
I went for the option to set `outputPath` to `dist/apps/cli` and so also the `packageRoot` to `dist/apps/cli` because I believe the workspace `dist` folder is a `nx` best practice and it also makes it easy to mark just a single folder as build artifacts in tools like gitlab.

So this issue is that for that setup, `nx release publish` will use the old version number while a new version was already available.

I see some options
1. run `npx release version` **before** `nx run cli:build` so that the `package.json`  in `dist/apps/cli` folder also gets the updated version number and at the end only run `nx release publish`.
2. Keep the default `{projectRoot}` as `packageRoot` so `apps/cli/package.json` is used to get the current version number. However, the generated `package.json` file from the `build` task is then ignored.
3. nx release version should also update the generate package.json file in `dist/apps/cli`

**nx.json**
```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": ["production", "^production"]
    },
  },
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/src/test-setup.[jt]s",
      "!{projectRoot}/test-setup.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js"
    ],
    "sharedGlobals": []
  },
  "release": {
    "projects": ["cli"],
    "projectsRelationship": "independent",
    "git": {
      "commit": true,
      "tag": true
    },
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag"
      }
    },
    "changelog": {
      "projectChangelogs": true
    }
  }
}
```

**project.json**
```json
{
  "name": "cli",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/cli/src",
  "projectType": "library",
  "targets": {
    "nx-release-publish": {    ---> is this the way we are supposed to add project specific options to the `nx release publish` command? 
      "executor": "@nx/js:release-publish",
      "options": {
        "packageRoot": "dist/apps/cli"  ---> default is `{projectRoot}`
      }
    },
    "build": {
      "executor": "@nx/esbuild:esbuild",
      "options": {
        "main": "apps/cli/src/cli.ts",
        "tsConfig": "apps/cli/tsconfig.lib.json",
        "outputPath": "dist/apps/cli"
      }
    }
  },
  "tags": []
}

```

**apps/cli/package.json**
```json
{
  "name": "@company/package",
  "version": "0.3.2",
  "bin": {
    "cli-tool": "./cli.js"   <--- for esbuild `outputPath`  `dist/apps/cli`  or ./dist/cli.js in case `outputPath` of esbuild is set to `apps/cli/dist`
  },
  "type": "module",
  "publishConfig": {
    "@company:registry": "https://company.jfrog.io/artifactory/api/npm/npm-local/"
  }
}
```

**apps/cli/tsconfig.lib.json (probably doesn't matter for this issue)**
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "declaration": true,
    "types": ["node"],
    "moduleResolution": "Bundler",
    "module": "ESNext",
    "target": "ESNext",
    "rootDir": "src"
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}

```
See output of `nx release --verbose` below. It starts ok by detecting the current version 0.3.2 from git tag and calculates the new version 0.3.3 correctly based on conventional commits.

However, at the end, the old version is still used when publishing to the npm registry. Therefore the publish command fails because the registry already contains an entry for that version.

```sh
$ npx nx release --yes --verbose
 >  NX   Running release version for project: cli
cli 🔍 Reading data for package "@company/package" from apps/cli/package.json
cli 📄 Resolved the current version as 0.3.2 from git tag "cli@0.3.2".
cli 📄 Resolved the specifier as "patch" using git history and the conventional commits standard.
cli ✍️  New version 0.3.3 written to apps/cli/package.json
UPDATE apps/cli/package.json
    "name": "@company/package",
-   "version": "0.3.2",
+   "version": "0.3.3",
    "bin": {
 >  NX   Staging changed files with git because --stage-changes was set
Staging files in git with the following command:
git add apps/cli/package.json
 >  NX   Generating an entry in apps/cli/CHANGELOG.md for cli@0.3.3
UPDATE apps/cli/CHANGELOG.md
+ ## 0.3.3 (2023-12-27)
+
+
+ ### 🩹 Fixes
+
+ - **cli:** sort files without date as oldest
+
+
+ ### ❤️  Thank You
+
+ - Thomas Dekiere
+
  ## 0.3.2 (2023-12-27)
 >  NX   Committing changes with git
Staging files in git with the following command:
git add apps/cli/CHANGELOG.md
Committing files in git with the following command:
git commit --message chore(release): publish --message - project: cli 0.3.3
 >  NX   Tagging commit with git
Tagging the current commit in git with the following command:
git tag --annotate cli@0.3.3 --message cli@0.3.3
 >  NX   Running target nx-release-publish for project cli:
    - cli
 
> nx run cli:nx-release-publish
Skipped package "@company/package" from project "cli" because v0.3.2 already exists in https://registry.npmjs.org/ with tag "latest"
 
 >  NX   Successfully ran target nx-release-publish for project cli
$ git push https://oauth2:$TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:$CI_DEFAULT_BRANCH -o ci.skip --follow-tags
To https://git.company.org/company/group/project.git
   fa6253e..0a4112e  HEAD -> main
 * [new tag]         cli@0.3.3 -> cli@0.3.3

```

### Expected Behavior

The right version should be used to publish to the npm registry.

### GitHub Repo

https://github.com/thdk/nx-release-repro

### Steps to Reproduce

The following script will setup a repro in a new folder: `nx-release-repro`
It requires to have:
 - `jq` installed (to make config changes to `nx.json`, `project.json`)
 - verdaccio local npm registry running (`npm i -g verdaccio && verdaccio`)

```sh
npx create-nx-workspace@latest nx-release-repro --preset ts

# open workspace
cd nx-release-repro

# init git
git init

# create publishable js library 'my-cli' using esbuild
npx nx@latest g @nx/js:lib cli \
  --publishable \
  --importPath=my-cli \
  --directory apps/cli \
  --projectNameAndRootFormat as-provided \
  --bundler esbuild \
  --unitTestRunner none \
  --linter none

# Add initial tag
git commit --allow-empty -m 'chore: create empty repo'
git tag cli@0.0.0

# Commit nx workspace with cli application
git add -A
git commit -m 'feat(cli): add cli app'

# Configure nx release
jq '.release = {
    "projects": ["cli"],
    "projectsRelationship": "independent",
    "git": {
      "commit": true,
      "tag": true
    },
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag"
      }
    },
    "changelog": {
      "projectChangelogs": true
    }
}' nx.json > temp.json && mv temp.json nx.json

git add nx.json
git commit -m 'ci: configure nx release'

## Use local verdaccio registry
npm config set --location project registry 'http://localhost:4873/'
git add .npmrc
git commit -m 'build: use local verdaccio registry'

npx nx build cli
npx nx release --verbose --yes --dry-run

#  >  NX   Running release version for project: cli

# cli 🔍 Reading data for package "my-cli" from apps/cli/package.json
# cli 📄 Resolved the current version as 0.1.0 from git tag "cli@0.1.0".
# cli 🚫 No changes were detected using git history and the conventional commits standard.
# cli 🚫 Skipping versioning "my-cli" as no changes were detected.


#  >  NX   No changes detected for changelogs

#    No changes were detected for any changelog files, so no changelog entries will be generated.


#  >  NX   Running target nx-release-publish for project cli:

#     - cli
   
#    With additional flags:
#      --dryRun=true

#  ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

# > nx run cli:nx-release-publish

# Waiting for the debugger to disconnect...
# Waiting for the debugger to disconnect...

# 📦  my-cli@0.0.1
# === Tarball Contents ===

# 116B README.md        
# 114B package.json     
# 672B project.json     
# 27B  src/index.ts     
# 50B  src/lib/cli.ts   
# 417B tsconfig.json    
# 231B tsconfig.lib.json
# === Tarball Details ===
# name:          my-cli                                  
# version:       0.0.1                                   
# filename:      my-cli-0.0.1.tgz                        
# package size:  998 B                                   
# unpacked size: 1.6 kB                                  
# shasum:        7bb191ca9b1f1f044fd76df167c9487dd2068b66
# integrity:     sha512-ERx4eXorpC46g[...]/VBC+lguWRdzg==
# total files:   7                                       
 
# Would publish to http://localhost:4873/ with tag "latest", but [dry-run] was set

## ====> Correct version here but it does not contain the actual files from `dist/apps/cli`

# set nx-release-publish packageRoot setting to dist/apps/cli
jq '.targets["nx-release-publish"] = {
          "executor": "@nx/js:release-publish",
          "options": {
            "packageRoot": "dist/apps/cli"
          }
        }' apps/cli/project.json > tmp.json && mv tmp.json apps/cli/project.json


## ====> Now try to release again

npx nx release --verbose --yes --dry-run

#  >  NX   Running release version for project: cli

# cli 🔍 Reading data for package "my-cli" from apps/cli/package.json
# cli 📄 Resolved the current version as 0.0.0 from git tag "cli@0.0.0".
# cli 📄 Resolved the specifier as "minor" using git history and the conventional commits standard.
# cli ✍️  New version 0.1.0 written to apps/cli/package.json

# UPDATE apps/cli/package.json [dry-run]

#     "name": "my-cli",
# -   "version": "0.0.1",
# +   "version": "0.1.0",
#     "dependencies": {},


#  >  NX   Staging changed files with git because --stage-changes was set

# Would stage files in git with the following command, but --dry-run was set:
# git add apps/cli/package.json

# NOTE: The "dryRun" flag means no changes were made.

#  >  NX   Previewing an entry in apps/cli/CHANGELOG.md for cli@0.1.0


# CREATE apps/cli/CHANGELOG.md [dry-run]
# + ## 0.1.0 (2023-12-28)
# +
# +
# + ### 🚀 Features
# +
# + - **cli:** add cli app
# +
# +
# + ### ❤️  Thank You
# +
# + - Thomas Dekiere


#  >  NX   Committing changes with git

# Would stage files in git with the following command, but --dry-run was set:
# git add apps/cli/CHANGELOG.md

# Would commit all previously staged files in git with the following command, but --dry-run was set:
# git commit --message chore(release): publish --message - project: cli 0.1.0

#  >  NX   Tagging commit with git

# Would tag the current commit in git with the following command, but --dry-run was set:
# git tag --annotate cli@0.1.0 --message cli@0.1.0

# NOTE: The "dryRun" flag means no changelogs were actually created.

#  >  NX   Running target nx-release-publish for project cli:

#     - cli
   
#    With additional flags:
#      --dryRun=true

#  ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

# > nx run cli:nx-release-publish


# 📦  my-cli@0.0.1
# === Tarball Contents ===

# 116B  README.md   
# 1.1kB index.cjs   
# 114B  package.json
# === Tarball Details ===
# name:          my-cli                                  
# version:       0.0.1                                   
# filename:      my-cli-0.0.1.tgz                        
# package size:  795 B                                   
# unpacked size: 1.3 kB                                  
# shasum:        ac459d53427fe7587cd41551fa1ca9c5dc040bf3
# integrity:     sha512-AJrDDlXzwKdL0[...]BZX74YVvpp+Tw==
# total files:   3                                       
 
# Would publish to http://localhost:4873/ with tag "latest", but [dry-run] was set

#  ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

#  >  NX   Successfully ran target nx-release-publish for project cli



# NOTE: The "dryRun" flag means no projects were actually published.


## ===> Here nx reports to publish version 0.1.0 while the actual version being published is 0.0.1 (taken from dist/apps/cli/package.json)
```

### Nx Report

```shell
❯ npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx             : 17.2.8
   @nx/js         : 17.2.8
   @nx/workspace  : 17.2.8
   @nx/devkit     : 17.2.8
   @nx/esbuild    : 17.2.8
   @nrwl/tao      : 17.2.8
   typescript     : 5.2.2
```

### Operating System

- [X] macOS

**Comment by nkalinov** [comment] 2024-02-02 16:21
This feels like a fundamental missing piece. Is there a known workaround @fahslaj @thdk ? Any plans, ETA for the fix?

**Comment by thdk** [comment] 2024-02-02 16:48
@nkalinov 

I think there are currently two workarounds for this. 

1. either run `npx nx release version` before you build your project so that the version in you `app/{project}/package.json` is already bumped and the generated `package.json` file in `dist/apps/{project}` will also contain this version. Next run `npx nx release changelog` and `npx release publish`.

2. or adopt the `outputPath` of your esbuild executor so that your output files are generated in `apps/{project}/dist`

```json

    "build": {
      "executor": "@nx/esbuild:esbuild",
      "options": {
        "main": "apps/{project}/src/cli.ts",
        "tsConfig": "apps/{project}/tsconfig.lib.json",
        "outputPath": "apps/{project}/dist"
      }
    },
```

This will create a folder structure: `apps/{project}

```
package.json <-- the package.json file used when running `npx nx release` commands. 
src/index.ts
dist/index.js
dist/package.json <-- the 'generated' package.json file, can be ignored here?
```

My `release` config in `nx.json` looks like this:

```
"release": {
    "projects": ["cli"],
    "projectsRelationship": "independent",
    "git": {
      "commit": true,
      "tag": true
    },
    "version": {
      "generatorOptions": {
        "specifierSource": "conventional-commits",
        "currentVersionResolver": "git-tag"
      }
    },
    "changelog": {
      "projectChangelogs": true
    }
  }
```

**Comment by fahslaj** [comment] 2024-02-02 19:07
Hi @nkalinov and @thdk, to change the directory that is published with `nx release publish`, you can override the `nx-release-publish` executor and specify the "packageRoot" in the options, just like is done in the project.json listed in the original issue.

For the version command, the packageRoot is configured via the generator options in `nx.json` or the project's `project.json`:
```
{
  "release": {
    "version": {
      "generatorOptions": {
        "packageRoot": "dist/packages/{projectName}"
      }
    }
  }
}
```

One thing to note is that the version command will only update a single package.json file per project, so if you are building to a dist directory, only the dist's versions will be updated. Because of this, we recommend using "file:../" links in the source package.json. Tracking version numbers actively in the source package.json while also tracking them in a separate dist/ directory is not currently supported.

**Comment by nkalinov** [comment] 2024-02-05 11:30
@fahslaj Can you please elaborate on your recommendation about using "file://"? If possible provide a full example (just written here) of the recommended flow **including a build step**. Thank you!

**Comment by nkalinov** [comment] 2024-02-05 14:40
> @nkalinov
> 
> I think there are currently two workarounds for this.
> 
> 1. either run `npx nx release version` before you build your project so that the version in you `app/{project}/package.json` is already bumped and the generated `package.json` file in `dist/apps/{project}` will also contain this version. Next run `npx nx release changelog` and `npx release publish`.
> 2. or adopt the `outputPath` of your esbuild executor so that your output files are generated in `apps/{project}/dist`
> 
> ```json
>     "build": {
>       "executor": "@nx/esbuild:esbuild",
>       "options": {
>         "main": "apps/{project}/src/cli.ts",
>         "tsConfig": "apps/{project}/tsconfig.lib.json",
>         "outputPath": "apps/{project}/dist"
>       }
>     },
> ```
> 
> This will create a folder structure: `apps/{project}
> 
> ```
> package.json <-- the package.json file used when running `npx nx release` commands. 
> src/index.ts
> dist/index.js
> dist/package.json <-- the 'generated' package.json file, can be ignored here?
> ```
> 
> My `release` config in `nx.json` looks like this:
> 
> ```
> "release": {
>     "projects": ["cli"],
>     "projectsRelationship": "independent",
>     "git": {
>       "commit": true,
>       "tag": true
>     },
>     "version": {
>       "generatorOptions": {
>         "specifierSource": "conventional-commits",
>         "currentVersionResolver": "git-tag"
>       }
>     },
>     "changelog": {
>       "projectChangelogs": true
>     }
>   }
> ```

Thanks @thdk trying workaround #1 but `npx nx release changelog` needs a positional [version] argument which doesn't make sense for independent releases. Will try to use it programattically.

What is your exact flow in a monorepo?

**Comment by fahslaj** [comment] 2024-05-14 20:53
Duplicate of #21855

**Comment by thdk** [comment] 2024-06-09 06:11
> Thanks @thdk trying workaround 1. but `npx nx release changelog` needs a positional [version] argument which doesn't make sense for independent releases. Will try to use it programattically.

I would have to check if this is still the case today. Maybe making this argument optional for configurations that rely on conventional commit strategy would be an improvement already.

> What is your exact release flow in a monorepo with CI and build step?

For now I'm only using nx release in a simple setup but I'm playing with the possibilities of nx with in sample workspaces/projects.

**Comment by fahslaj** [comment] 2024-06-23 21:43
For more details on specifying alternate package roots, see this doc - https://nx.dev/recipes/nx-release/publish-custom-dist-directory

**Closed** 2024-06-23 21:43 UTC
Labels: type: docs, scope: release
