### ISSUE TITLE
storybook breaks since updating to 12.8.0

### ISSUE THREAD

**Issue by JulienDemarque** [nrwl/nx#6873] opened 2021-08-27 15:15 UTC
## Current Behavior
All stories are showing the same error. 
![screen_shot_2021-08-26_at_10 45 54_am](https://user-images.githubusercontent.com/27313954/131149350-4f74010b-08eb-4bd9-b0e0-5e0e544972e8.png)

## Expected Behavior
Storybook would render normally before the nx update

## Steps to Reproduce

update to nx 12.8.0. see it break: https://ui.inv.tech/

### Failure Logs
```
vendors~main.d7a53030.iframe.bundle.js:2 Uncaught TypeError: Cannot read property 'name' of undefined
    at vendors~main.d7a53030.iframe.bundle.js:2
    at vendors~main.d7a53030.iframe.bundle.js:2
    at vendors~main.d7a53030.iframe.bundle.js:2
    at unboundStoryFn (vendors~main.d7a53030.iframe.bundle.js:2)
    at renderWithHooks (vendors~main.d7a53030.iframe.bundle.js:2)
    at mountIndeterminateComponent (vendors~main.d7a53030.iframe.bundle.js:2)
    at beginWork (vendors~main.d7a53030.iframe.bundle.js:2)
    at HTMLUnknownElement.callCallback (vendors~main.d7a53030.iframe.bundle.js:2)
    at Object.invokeGuardedCallbackDev (vendors~main.d7a53030.iframe.bundle.js:2)
    at invokeGuardedCallback (vendors~main.d7a53030.iframe.bundle.js:2)
 ```

### Environment

  Node : 12.18.1
  OS   : darwin x64
  pnpm : 6.14.3

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : 12.8.0
  @nrwl/node : 12.8.0
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by juristr** [comment] 2021-09-13 07:56
@JulienDemarque mentioned offline that this apparently happens due to the `storybook-addon-next-router`

```
import { withNextRouter } from 'storybook-addon-next-router'

export const decorators = [withNextRouter]
```

**Comment by mandarini** [comment] 2022-01-31 15:25
Hello @JulienDemarque ! Is this still an issue? Have you tried this with the latest version of Nx?

**Comment by mandarini** [comment] 2022-02-01 17:34
I will be closing this for now, since it seems that a number of things have changed in the meantime, which may have fixed this issue, and I cannot reproduce at the moment. Please let me know if I need to reopen! :)

**Closed by mandarini** 2022-02-01 17:34 UTC
Labels: type: bug, scope: nextjs, scope: storybook
