### ISSUE TITLE
[module-federation][angular-material] NullInjectorError: No provider for InjectionToken DocumentToken!

### ISSUE THREAD

**Issue by DamianTt** [nrwl/nx#11694] opened 2022-08-23 16:25 UTC
## Current Behavior
I get an error when trying to display a shared library component containing a component from Angular Material when rendering a remote application in a host application. To avoid error i need to directly import Angular Material modules in both: shell/app.module.ts and sharedUiLibrary.module.ts

## Expected Behavior
No need to import directly Angular Material modules inside shell/app.module.ts, because i already imported these modules in shared component library

## Steps to Reproduce
https://github.com/DamianTt/NxAngularModuleFederationDocker - Switch to a branch 'import-error'. Run `npm run dev`, navigate to `http://localhost:4200/`, then click 'App2' and you will see an error in console. 

Works correctly if you open remote on `http://localhost:4202/`

1. Create Nx workspace
2. Create Host application
3. Create Remote application
4. Create a new Library
5. Install Angular Material
6. Create new component inside library using some Angular Material component
7. Use created component in remote app

### Failure Logs
```ERROR Error: Uncaught (in promise): NullInjectorError: NullInjectorError: No provider for InjectionToken DocumentToken!
NullInjectorError: NullInjectorError: No provider for InjectionToken DocumentToken!
    at NullInjector.get (core.mjs:6368:27)
    at R3Injector.get (core.mjs:6795:33)
    at R3Injector.get (core.mjs:6795:33)
    at R3Injector.get (core.mjs:6795:33)
    at injectInjectorOnly (core.mjs:4779:33)
    at Module.ɵɵinject (core.mjs:4783:12)
    at Object.HighContrastModeDetector_Factory [as factory] (a11y.mjs:2406:1)
    at R3Injector.hydrate (core.mjs:6896:35)
    at R3Injector.get (core.mjs:6784:33)
    at R3Injector.get (core.mjs:6795:33)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26367:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
```

### Environment
```Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2

   nx : 14.5.8
   @nrwl/angular : 14.5.8
   @nrwl/cypress : 14.5.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.8
   @nrwl/eslint-plugin-nx : 14.5.8
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.8
   @nrwl/js : 14.5.8
   @nrwl/linter : 14.5.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.8
   @nrwl/workspace : 14.5.8
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by leosvelperez** [comment] 2022-09-02 14:27
Thanks for reporting this!

The issue here is not about importing Angular Material modules. The issue is that the `@angular/common` package is not automatically shared because is not directly used (it's not imported) by the `shell` source code.

This is by design, we automatically collect all the direct dependencies to share them with the Module Federation webpack plugin. The key here is the "direct dependencies" wording. For performance reasons, we don't recursively collect all dependencies from npm packages. We only collect the ones that your application source code is directly using. That is, for example:

```ts
import { BrowserModule } from '@angular/platform-browser';
```

If your application code has that import above, we do collect `@angular/platform-browser` but we don't collect `@angular/common` which is a dependency of the former.

The `DOCUMENT` injection token is exposed by `@angular/common`. To ensure a single definition of that token is used throughout your host and remotes, it needs to be shared. Since your `shell` app is not directly importing `@angular/common`, it's not being automatically shared and therefore the provided `DOCUMENT` token by the `shell` app would be a different `DOCUMENT` token that `app2` is trying to inject.

To solve this, you need to share that package on the `shell` app. You do that by adding the following to your `shell` app `module-federation.config.js` file:

```js
module.exports = {
  ...
  additionalShared: ['@angular/common'],
};
```

**Comment by leosvelperez** [comment] 2022-09-02 14:28
I'm going to close this issue since it's working as intended. Feel free to reply or reopen it if you think there's still an issue.

**Closed by leosvelperez** 2022-09-02 14:28 UTC
Labels: type: bug, scope: angular
