### ISSUE TITLE
19.5 does not work with angular 17 and module federation

### ISSUE THREAD

**Issue by lkleen-audi** [nrwl/nx#27508] opened 2024-08-19 12:29 UTC
### Current Behavior

RouterModule.forChild in a remote throws an NG0203 after migrating nx to 19.5. I had to roll back to 17.3 to fix that

### Expected Behavior

Frontend remote does not throw NG0203

### Steps to Reproduce

1. setup a monorepo with an angular 17 project with module federation and a host and remote application
2. upgrade nx (do not upgrade angular during interactive setup) to 19.5
3. remote application throws NG0203

### Nx Report

```shell
Node           : 20.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 8.15.4

nx (global)        : 19.5.6
nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/angular        : 19.5.6
@nx/cypress        : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/nest           : 19.5.6
@nx/node           : 19.5.6
@nrwl/tao          : 19.5.6
@nx/web            : 19.5.6
@nx/webpack        : 19.5.6
typescript         : 5.3.3
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
nx-cdktf                : 0.2.3
schematics-scss-migrate : 2.3.17
```

### Package Manager Version

pnpm 8.15.4

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment] 2024-08-19 13:54
Closing as duplicate of: https://github.com/nrwl/nx/issues/27162

**Closed by Coly010** 2024-08-19 13:54 UTC
Labels: type: bug, scope: angular, scope: module federation
