### ISSUE TITLE
create-nx-workspace doesn't work

### ISSUE THREAD

**Issue by HackPoint** [nrwl/nx#244] opened 2018-01-30 13:46 UTC
Angular CLI: 1.6.4
Node: 9.3.0
OS: darwin x64

Creating a sandbox with the CLI and Nx Schematics...
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
Cached binary found at /Users/xxx/.npm/node-sass/4.7.2/darwin-x64-59_binding.node
Binary found at /private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
added 1002 packages in 22.86s
ng new "predict" --collection=@nrwl/schematics
core_1.PriorityQueue is not a constructor
TypeError: core_1.PriorityQueue is not a constructor
    at new TaskScheduler (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular-devkit/schematics/src/engine/task.js:20:23)
    at SchematicEngine.createContext (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular-devkit/schematics/src/engine/engine.js:81:31)
    at SchematicImpl.call (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular/cli/tasks/init.js:71:33)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular/cli/commands/new.js:134:25)
    at resolve (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
child_process.js:614
    throw err;
    ^

Error: Command failed: /var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-34812y5Tj7KGTwww2/node_modules/.bin/ng new "predict" --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v9.3.0/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:40:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)

**Comment by jeffbcross** [comment] 2018-02-01 23:02
It looks to me like command line tools from Xcode need to be installed, probably gcc in particular. Can you go to developer.apple.com/downloads and install the appropriate version of XCode command line tools?

One of the issues will be fixed by #245 (or maybe it will fix all of your issues :))

**Comment by HackPoint** [comment] 2018-02-04 17:27
@jeffbcross not sure: see this;
`
create-nx-workspace alv 
Creating a sandbox with the CLI and Nx Schematics...
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
Cached binary found at /Users/genadyshmunik/.npm/node-sass/4.7.2/darwin-x64-59_binding.node
Binary found at /private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
added 1002 packages in 18.592s
ng new "alv" --collection=@nrwl/schematics
core_1.PriorityQueue is not a constructor
TypeError: core_1.PriorityQueue is not a constructor
    at new TaskScheduler (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular-devkit/schematics/src/engine/task.js:20:23)
    at SchematicEngine.createContext (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular-devkit/schematics/src/engine/engine.js:81:31)
    at SchematicImpl.call (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular-devkit/schematics/src/engine/schematic.js:35:38)
    at Promise (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular/cli/tasks/schematic-run.js:73:23)
    at new Promise (<anonymous>)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular/cli/tasks/schematic-run.js:72:16)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular/cli/tasks/init.js:71:33)
    at Class.run (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular/cli/commands/new.js:134:25)
    at resolve (/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
    at new Promise (<anonymous>)
child_process.js:614
    throw err;
    ^

Error: Command failed: /var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/tmp-54188LzUECeg6AbRf/node_modules/.bin/ng new "alv" --collection=@nrwl/schematics
    at checkExecSyncError (child_process.js:574:11)
    at Object.execSync (child_process.js:611:13)
    at Object.<anonymous> (/Users/genadyshmunik/.nvm/versions/node/v9.3.0/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:40:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)

`

And that's after I installed the xcode toolbox and tools

**Comment by HackPoint** [comment] 2018-02-04 17:44
`ng new "alv" --collection=@nrwl/schematics` this is the line that failes

**Comment by vsavkin** [comment] 2018-02-19 14:29
Duplicate of https://github.com/nrwl/nx/issues/239

**Closed by vsavkin** 2018-02-19 14:29 UTC
