### ISSUE TITLE
@nrwl/angular should expose some way to skip install phase.

### ISSUE THREAD

**Issue by saket-r** [nrwl/nx#5184] opened 2021-03-31 11:08 UTC
## Description

@nrwl/angular should expose some way to skip install phase.

## Motivation

if we want to create a publishable library and skip install phase, right now there is no way to achieve that

Actually there is an option from schema as `skipPackageJson` but will not be honored due to 
`!(options.publishable || options.buildable)` logic
and to skip installation we need one out of two things either `skipPackageJson`  or `skipInstall` to be configured

// code from @schematics/angular >
```
(_tree, context) => {
                if (!options.skipPackageJson && !options.skipInstall) {
                    context.addTask(new tasks_1.NodePackageInstallTask());
                }
            }
```

and since `skipPackageJson`  is not honored and `skipInstall` is not exposed we can not skip install phase.
```
schematics_1.externalSchematic('@schematics/angular', 'library', {
                name: options.name,
                prefix: options.prefix,
                style: options.style,
                entryFile: 'index',
                skipPackageJson: !(options.publishable || options.buildable),
                skipTsConfig: true,
            }),
```
## Suggested Implementation

// internally @nrwl/angular triggers @schematics/angular but restricts arguments
// code from @nrwl/angular schematic
```
schematics_1.externalSchematic('@schematics/angular', 'library', {
                name: options.name,
                prefix: options.prefix,
                style: options.style,
                entryFile: 'index',
                skipPackageJson: !(options.publishable || options.buildable),
                skipTsConfig: true
            }),
```

one way could be to expose `skipInstall` as follows:
            
```
schematics_1.externalSchematic('@schematics/angular', 'library', {
                name: options.name,
                prefix: options.prefix,
                style: options.style,
                entryFile: 'index',
                skipPackageJson: !(options.publishable || options.buildable),
                skipTsConfig: true,
                skipInstall: options.skipInstall 
            }),
```

## Alternate Implementations
or update condition to honor  `skipPackageJson` flag
```
schematics_1.externalSchematic('@schematics/angular', 'library', {
                name: options.name,
                prefix: options.prefix,
                style: options.style,
                entryFile: 'index',
                skipPackageJson:  options.skipPackageJson || !(options.publishable || options.buildable), <- some variant of this where skipPackageJson will have more precedence 
                skipTsConfig: true
            }),
```

**Comment by FrozenPandaz** [comment] 2021-03-31 23:07
This is a duplicate of https://github.com/nrwl/nx/issues/5018

Follow there for more updates.

It's actually a bug.. I tried to fix it.. but turns out it's more complicated than expected. :(

**Closed by FrozenPandaz** 2021-03-31 23:07 UTC
Labels: type: feature
