### ISSUE TITLE
After Upgrade to Angular 17 -> Projects/Applications are not found after reboot until project.json is "touched"

### ISSUE THREAD

**Issue by pkelleter** [nrwl/nx#22739] opened 2024-04-09 09:36 UTC
### Current Behavior

After Upgrading from Angular 16 to 17 via nx migrate after every reboot my applications can not be started anymore ("Cannot find project xyz") - they also do not show up in the "nx show projects" list.

When I "touch" a corresponding project.json (editing it in some way, saving, undoing the edit, saving again) it will immediately show up in the list afterwards and be able to be built.

I did not have any similar issues before the update.

### Expected Behavior

All projects should always be visible to nx, even after reboot.

### Steps to Reproduce

Unfortunately I have no idea how to reproduce this without sharing my company repo which I obviously can't. I just hope more people have the same issue and the Nrwl team has an idea on where this issue comes from.

### Nx Report

```shell
Node   : 20.12.1
OS     : win32-x64
npm    : 10.5.0

nx (global)        : 18.2.3
nx                 : 18.2.3
@nx/js             : 18.2.3
@nx/jest           : 18.2.3
@nx/linter         : 18.2.3
@nx/eslint         : 18.2.3
@nx/workspace      : 18.2.3
@nx/angular        : 18.2.3
@nx/devkit         : 18.2.3
@nx/eslint-plugin  : 18.2.3
@nrwl/tao          : 18.2.3
@nx/web            : 18.2.3
@nx/webpack        : 18.2.3
typescript         : 5.4.4
---------------------------------------
Community plugins:
@ngneat/transloco : 6.0.4
ng2-charts        : 6.0.0
```

### Failure Logs

```shell
NX   Cannot find project 'meeting-organizer'
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by FrozenPandaz** [comment] 2024-07-25 17:10
Projects should be able to be found anywhere, even outside of the normal workspaceLayout. It seems like you've fixed your issue so I'm going to close this issue. A new one can be opened if the workspaceLayout is indeed somehow affecting Nx's project detection.

**Closed by FrozenPandaz** 2024-07-25 17:10 UTC
Labels: type: bug, scope: core

**Comment by angelnikolov** [comment] 2024-08-05 20:38
Interestingly, I experience the exact same issue. Unless I change a line in `project.json` of my main app project, it keeps saying that it can't find it.

In CI, it happens 100% of the times. I even tried prefixing my build command with `nx reset` and it still can't find the project.

Anyone else experiencing this? @pkelleter Did you resolve your issue with the root directory name change?

**Comment by pkelleter** [comment] 2024-08-05 20:58
@angelnikolov yes, I renamed the root folder to "apps" and it always works since then. was the only fix i could come up with.

**Comment by angelnikolov** [comment] 2024-08-05 21:11
Thanks!
Weirdly enough, ours already is named "apps".. So will dig for another solution.
Maybe @FrozenPandaz has seen such an issue again in the wild?

**Comment by angelnikolov** [comment] 2024-08-06 11:02
Right, I tracked it down to this call here, but I couldn't debug further since it goes into Rust land. https://github.com/nrwl/nx/blob/a3869a814dcf0f4c3d6fc2d2662e970273ccdb03/packages/nx/src/utils/workspace-context.ts#L59
Basically, what happens there is that one of my apps is not found at all. Any guidance on how to debug this further?
I wonder if this is not caused by a corrupt file in that application's directory or something like it..
