### ISSUE TITLE
Cypress e2e does not work with Yarn berry (pnp)

### ISSUE THREAD

**Issue by unrealsolver** [nrwl/nx#19652] opened 2023-10-17 12:59 UTC
### Current Behavior

```
****@***** ~/d/n/****frontend > yarn nx e2e app-e2e -v

> nx run app-e2e:e2e -v

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.0.7:3000/
  ➜  Network: http://10.0.85.1:3000/
  ➜  Network: http://172.22.0.1:3000/
  ➜  Network: http://172.23.0.1:3000/
  ➜  Network: http://10.251.0.130:3000/
Your configFile is invalid: /home/***/dev/n***/***frontend/packages/app-e2e/cypress.config.ts

It threw an error when required, check the stack trace below:

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/***/dev/***/***frontend/packages/app-e2e/cypress.config.ts
    at new NodeError (node:internal/errors:372:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:21:20)
    at load$1 (file:///home/***/dev/***/***frontend/.pnp.loader.mjs:1456:12)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadFile (/home/***/.cache/Cypress/13.2.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:106:14)
    at async EventEmitter.<anonymous> (/home/***/.cache/Cypress/13.2.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:32)
```

### Expected Behavior

Yarn (non-pnp) or npm results:
```
***@*** ~/d/t/myapp> yarn nx e2e myapp-e2e

> nx run myapp-e2e:e2e

  ➜  Local:   http://localhost:4200/
================================================================================
  (Run Starting)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.3.1                                                                         │
  │ Browser:        Electron 114 (headless)                                                        │
  │ Node Version:   v16.15.1 (/home/***/.local/share/nvm/v16.15.1/bin/node)                     │
  │ Specs:          1 found (app.cy.ts)                                                            │
  │ Searched:       src/**/*.cy.{js,jsx,ts,tsx}                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  app.cy.ts
....
```

### Steps to Reproduce

```bash
yarn dlx create-nx-workspace@latest myapp
# Use React / Vite / Cypress. Other options for reference: regular monorepo, CSS, no caching
corepack enable
yarn set version stable
yarn config set nodeLinker pnp
yarn
yarn nx e2e myapp-e2e
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.15.1
   OS     : linux-x64
   yarn   : 3.6.4

   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nx/vite           : 16.10.0
   typescript         : 5.1.6
```
```


### Failure Logs

```shell
See actual/expected behavior.
```

### Package Manager Version

yarn@3.6.4 pnp-enabled

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is the most probably `cypress/e2e` executor issue. Yarn pnp uses different module resolution and probably the executor is not aware of it.

**Comment by unrealsolver** [comment] 2023-12-18 17:51
Nx v17 & Yarn v4 - no changes in behavior.

**Comment by leosvelperez** [comment] 2024-05-17 07:27
Thanks for reporting this!

This is an issue with Cypress that you can reproduce on a project without Nx. There are multiple issues on the Cypress repo about Yarn PnP. I suggest you follow those for a resolution. To point a few relevant to your issue:

https://github.com/cypress-io/cypress/issues/27450
https://github.com/cypress-io/cypress/issues/22747#issuecomment-1233654260
https://github.com/cypress-io/cypress/issues/25958

I'm closing this since the issue is not caused by Nx. Please follow the relevant issues in the Cypress repo.

**Closed by leosvelperez** 2024-05-17 07:27 UTC
Labels: type: bug, scope: testing tools
