### ISSUE TITLE
E2E tests can't be ran in parallel

### ISSUE THREAD

**Issue by BuckyMaler** [nrwl/nx#1604] opened 2019-07-20 22:19 UTC
## Expected Behavior

E2E tests can be ran in parallel.

## Current Behavior

E2E tests can't be ran in parallel. Different errors are thrown based on the test runner.

Cypress:

![Screen Shot 2019-07-20 at 4 23 32 PM](https://user-images.githubusercontent.com/14145352/61584696-f71a4b00-ab11-11e9-9e89-b0b7127dddf0.png)

Protractor:

![Screen Shot 2019-07-20 at 4 28 24 PM](https://user-images.githubusercontent.com/14145352/61584698-fe415900-ab11-11e9-89fc-37fe708763ac.png)

### Steps to Reproduce

1. Generate a Nx workspace
2. Generate either two Cypress or two Protractor projects
3. `npm run affected:e2e -- --all --parallel`

### Context

- version of Nx used 8.2.0

**Comment by elvirdolic** [comment] 2019-11-27 20:38
I would also like to run cypress e2e in parallel but adding following command

`yarn affected:e2e --base=origin/master --head=HEAD  --browser chrome --record --parallel --ci-build-id $BUILD_BUILDNUMBER --group "Azure CI"`

The result is following: 

```node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng e2e paldesk-e2e --browser=chrome --record=true --ci-build-id= --ciBuildId= --group=Azure CI
Unknown option: '--ci-build-id'
Unknown option: '--ciBuildId'
Unknown option: '--group'
Unknown option: 'CI'
error Command failed with exit code 1.```

In AzureDevops

**Comment by Cammisuli** [comment] 2020-02-20 15:19
This is interesting because of the way the `--parallel` flag works. 

It essentially creates new processes and lets them do their thing. It has no way of knowing the context of the process that should be spawned. In the case of Cypress (or anything else that could potentially spin up a server that listens on a port), all processes try to get access to the same port. 

We could potentially make the cypress builder a bit smarter and check to see if the port is available before starting it. 🤔

**Comment by FrozenPandaz** [comment] 2020-05-29 19:16
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by axelolsson** [comment] 2020-07-01 08:40
Bump.

**Comment by BrianVia** [comment] 2020-07-01 20:01
Just adding the piece of info that Cypress (with a paid plan) supports parallelization via the same `--parallel` flag
[Cypress docs](https://docs.cypress.io/guides/guides/parallelization.html#Turning-on-parallelization)

**Comment by mike-park** [comment] 2020-07-05 16:35
> Without having looked at it, this _may_ work though as it is right now.
> `nx affected:e2e --parallel --maxParallel=2 -- --parallel` where the second `--parallel` gets passed along to the individual cypress run for the affected application.

I can verify that this approach (adding `-- --parallel`) fixes our problems with the `--parallel` flag being eaten by nx, and not passed to cypress.

**Comment by BrianVia** [comment] 2020-07-12 20:18
@mike-park were you able to test this in a CI environment? And did you test with more than 1 app being affected?

**Comment by wimme** [comment] 2020-08-28 14:45
We would like to run multiple Cypress instances simultaneously on our CI environment to test different applications in the Nx workspace in parallel. But as described above, it fails when launching multiple as the port is already in use:

```
PS C:\MyApp> npx nx e2e myapp-e2e --headless

> ng run myapp-e2e:e2e --headless
Port 4200 is already in use. Use '--port' to specify a different port.
```

It says to specify a different port, but I don't get it to work:

```
PS C:\MyApp> npx nx e2e myapp-e2e --headless --port=0

> ng run myapp-e2e:e2e --headless --port=0 
Unknown option: '--port'
```

Is there any way to do this?

**Comment by elvirdolic** [comment] 2020-08-28 16:07
@wimme Each application should have it’s own localhost port If you create your apps with nx. You can than use affected command and parallel flag

**Comment by wimme** [comment] 2020-09-23 09:52
@elvirdolic Then it's still not possible to run multiple CI pipelines simultaneously launching the same Cypress tests of the same application, or am I missing something?

**Comment by elvirdolic** [comment] 2020-09-24 10:34
As far I know, that’s not possible.

**Comment by kpl1** [comment] 2021-04-01 15:12
Any news about this ?  
I have the issue.

**Comment by timroussel** [comment] 2021-04-27 15:46
Any news ? I use nrwl 12.0.6 and doesn't work

**Comment by cyrixmorten** [comment] 2021-08-19 17:21
Have spent quite some time trying to get E2E tests running in parallel using Cypress Dashboard.

It works for single project target, splitting specs over multiple machines, but anything taking more projects such as `affected:e2e` fails either due to port in use, discrepancy in the capabilities (browser, version specs) sent to Cypress, group being closed or some issue with ngcc.

Wonder if the --parallel flag should be removed from the e2e target until it is ready - otherwise at least some improvement of the docs would be nice to be clear exactly when and how it can be used.

**Comment by smasala** [comment] 2021-11-01 18:34
This is the error I get when running affected e2e tests with cypress

```
You passed the --parallel flag, but we do not parallelize tests across different environments.

This machine is sending different environment parameters than the first machine that started this parallel run.

The existing run is: https://dashboard.cypress.io/projects/xxxxxxx/runs

In order to run in parallel mode each machine must send identical environment parameters such as:

- specs
- osName
- osVersion
- browserName
- browserVersion (major)

This machine sent the following parameters:

{
  "osName": "linux",
  "osVersion": "Ubuntu - 20.04",
  "browserName": "Electron",
  "browserVersion": "93.0.4577.82",
  "specs": [
    ...
  ]
}
```

**Comment by EthanSK** [comment] 2021-11-15 13:58
any updates? I have this issue

**Comment by wrslatz** [comment] 2021-11-15 14:06
For Cypress I think https://github.com/nrwl/nx/issues/6835 would be a dependency.

But even then, the [Cypress docs](https://docs.cypress.io/guides/guides/parallelization#Overview) recommend not running multiple suites on the same machine (and I've seen issues across their different repos suggesting it doesn't work in some cases)
> While parallel tests can also technically run on a single machine, we do not recommend it since this machine would require significant resources to run your tests efficiently.

**Comment by kpl1** [comment] 2021-12-14 10:33
Hey there!
Same issue for me.

The only workaround I found is to add "-"
Instead of having " --parallel ", I have "-- -- --parallel".

**Comment by tomfordweb** [comment] 2022-01-18 18:39
I also had issues with this. I was able to use "dash dash" to pass parallel as params. My full command to running parallelized tests in gitlab CI is below.

```
 nx e2e mhvillage-e2e --record --key "${CYPRESS_DASHBOARD_TEST_SUITE_KEY}"  --ci-build-id "e2e-${CI_PIPELINE_ID}" -- --parallel
```

In my situation..In order to get parallel tests to work, I also had to pass the `--ci-build-id` by hand. It seems that NX is not allowing cypress to determine this automatically as discussed [here](https://docs.cypress.io/guides/guides/parallelization#CI-Build-ID-environment-variables-by-provider):

**Comment by barbados-clemens** [comment] 2022-02-18 20:51
semi-related #8286

for now, cypress doesn't know what ports are/aren't available as @Cammisuli  this might be something we can make the cypress executor look into. the safest way to prevent this is going to be running nx with --parallel=1 to prevent the processes from reaching for the same port. or to change the port in which the apps are served on in each project being used in cypress

as others have mentioned you can pass the `-- --parallel` flag to get that flag to cypress if needed. closing for now.

**Closed by barbados-clemens** 2022-02-18 20:51 UTC
Labels: type: bug, scope: testing tools
