### ISSUE TITLE
Add support for assets in @nrwl/angular:package executor

### ISSUE THREAD

**Issue by GrandSchtroumpf** [nrwl/nx#9197] opened 2022-03-04 17:02 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
Add support for assets in @nrwl/angular:package executor

## Motivation
This would help copying `.json` files. For example to copy builder.json or schematics.json files when building the angular library.

## Suggested Implementation
Add a `assets` option to the `@nrwl/angular:package` executor which would work like the `assets` in `@angular-devkit/build-angular:browser`

## Alternate Implementations
Maybe provide a `@nrwl/workspace:copy` executor that would work like the `assets` in `@angular-devkit/build-angular:browser`.

**Comment by leosvelperez** [comment] 2022-05-11 10:24
hey @GrandSchtroumpf!

The `@nrwl/angular:package` executor uses `ng-packagr` under the hood, so you can configure the `assets` property in the `ng-package.json` to get the assets copied. For reference https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md.

**Comment by leosvelperez** [comment] 2022-05-16 12:21
Going to close this since assets are already supported as explained in https://github.com/nrwl/nx/issues/9197#issuecomment-1123532454.

**Closed by leosvelperez** 2022-05-16 12:21 UTC
Labels: type: feature, scope: angular

**Comment by GrandSchtroumpf** [comment] 2022-05-16 13:02
Indeed I didn't know we could do that. Sorry for the issue & thanks for the reply.

**Comment by Azbesciak** [comment] 2022-11-09 10:47
Hello,
What with subentries? I have lib like this (every dir is another subentry).
````
lib (called my-lib, but nevermind)
- /base
-- /core
--- component
-- my-json.json
````
so `my-json.json` is on the same level as `core` dir, which is also a subentry; we have `@lib/my-lib/base/core` and `@lib/my-lib/base` entries.
Now, in component I want to import `my-json.json`.
I already have in the root `ng-package.json` (because in sub `ng-package.json` it is not used) 
````json
 "assets": [
    { "glob": "**/*.json", "input": "/", "ignore": ["**/ng-package.json", "*.json"], "output": "/" },
    "**/*.md"
  ],
````
and I see that that `my-json.json` is copied in the valid place in dist (if it compiles, but it does not because the reason later).
I have also in the `package.json` the following:
````json
"exports": {
    "./base/my-json.json": {
      "json": "./base/my-json.json",
      "default": "./base/my-json.json"
    }
  },
````
And the problem is that neither `@lib/my-lib/base/my-json.json` nor `../my-json.json` (lazy) import does not work; first because the `entry point does not exist`, the second because of the `rootDir`.

I think about the separate `index.ts` for it with reexport, but it is a bit complicated, because we transform json to ts actually.

Do you have any advice?
