### ISSUE TITLE
Support for Angular 19 LTS

### ISSUE THREAD

**Issue by nakash2050** [nrwl/nx#29028] opened 2024-11-21 18:39 UTC
### Discussed in https://github.com/nrwl/nx/discussions/29013

<div type='discussions-op-text'>

<sup>Originally posted by **MGREMY** November 20, 2024</sup>
I could be great to have support for the new angular version
![image](https://github.com/user-attachments/assets/98cff3c0-fa5f-485f-8498-ca5b175b8806)
</div>

**Comment by kbrilla** [comment] 2024-11-21 19:10
Already in progress: #28847

**Comment by leosvelperez** [comment] 2024-11-22 08:45
Closing it as a duplicate of the feature request at #29013.

**Comment by colinscz** [comment] 2024-11-25 10:22
@leosvelperez quick question regarding your PR
Will migrations to the new syntax also be included or will you provide some NX generators/commands/schematics which are optional so people could migrate their code.

The migration schematics/commands I am referring to are those:
- ng g @angular/core:control-flow (For the new template syntax control flow)
- ng update @angular/cli --name use-application-builder (If I recall there is already an nx migration build executor present, I guess it's this one here: https://nx.dev/nx-api/angular/executors/browser-esbuild)
- ng g @angular/core:inject-migration

**Comment by leosvelperez** [comment] 2024-11-25 12:38
hey @colinscz!

The `@angular/core:control-flow` and `@angular/core:inject-migration` can be run with Nx like any other schematics (`nx g ...`). If you find issues running them on an Nx workspace, please file a separate issue so we can review it and see if the Angular team can make it more generic or if it requires us to provide a similar generator to compensate.

We provide the [`@nx/angular:convert-to-application-executor`](https://nx.dev/nx-api/angular/generators/convert-to-application-executor) generator to do the same operations as the `use-application-builder` optional migration from the Angular CLI does.

**Comment by colinscz** [comment] 2024-11-26 15:32
hey @leosvelperez 
Thank you for the explanation. In the end I found the right command to execute the control-flow migration. 
`npx nx generate @angular/core:control-flow-migration`

If I run into any issue with the migration I'll file a new one separate from this. :)

**Comment by tejasv-tagline** [comment] 2024-12-02 10:38
Isn't angular 19 support available yet? Many users are waiting for that, can someone please look at the PR?

**Closed** 2024-12-02 16:43 UTC
Labels: type: feature, scope: angular

**Comment by BenSawary** [comment] 2024-12-03 09:14
Big Thanks, for the ng 19 support. However, my first installation fails on the npm peer deps check. The @nx/angular module still refers to the version of @angular-devkit/build-angular@">= 16.0.0 < 19.0.0

**Comment by leosvelperez** [comment] 2024-12-03 09:47
> Big Thanks, for the ng 19 support. However, my first installation fails on the npm peer deps check. The @nx/angular module still refers to the version of @angular-devkit/build-angular@">= 16.0.0 < 19.0.0

This will be addressed soon, alongside an extra migration that's also missing. The Nx v20.2.0 will contain the right peer dependencies.

**Comment by marc-wilson** [comment] 2024-12-03 17:51
> > Big Thanks, for the ng 19 support. However, my first installation fails on the npm peer deps check. The @nx/angular module still refers to the version of @angular-devkit/build-angular@">= 16.0.0 < 19.0.0
> 
> This will be addressed soon, alongside an extra migration that's also missing. The Nx v20.2.0 will contain the right peer dependencies.

Do you have a target date for nx v20.2.0?

**Comment by amazing4u** [comment] 2024-12-05 23:32
Version 20.2.0 is published now

**Comment by GlaucoGodoi** [comment] 2024-12-07 17:08
I still facing issues with the migrate command:

 code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @w8/source@0.0.1
npm error Found: @angular-devkit/build-angular@18.2.11
npm error node_modules/@angular-devkit/build-angular
npm error   dev @angular-devkit/build-angular@"19.0.4" from the root project
npm error   peer @angular-devkit/build-angular@">= 16.0.0 < 19.0.0" from @nx/angular@20.0.6
npm error   node_modules/@nx/angular
npm error     dev @nx/angular@"20.2.1" from the root project
npm error   1 more (jest-preset-angular)
npm error
npm error Could not resolve dependency:
npm error dev @angular-devkit/build-angular@"19.0.4" from the root project
npm error
npm error Conflicting peer dependency: @angular/compiler-cli@19.0.3
npm error node_modules/@angular/compiler-cli
npm error   peer @angular/compiler-cli@"^19.0.0" from @angular-devkit/build-angular@19.0.4
npm error   node_modules/@angular-devkit/build-angular
npm error     dev @angular-devkit/build-angular@"19.0.4" from the root project

Any suggestion on how to avoid or fix it?

**Comment by BDominik** [comment] 2024-12-19 12:15
I cannot install packages after running ``nx migrate latest``
![Image](https://github.com/user-attachments/assets/c162cb41-6c48-4cdf-ad0b-19b43980da2d)
Is manually fixing this is the only option?

**Comment by BDominik** [comment] 2024-12-21 08:34
Is there any progress on this topic?

**Comment by FabianGosebrink** [comment] 2024-12-21 11:40
I did update Angular in the Nx workspace semi-automatically by using `npx nx migrate @angular/core@latest` and `npx nx migrate @angular/cli@latest` like described here https://github.com/nrwl/nx/issues/17100#issuecomment-1555643177

**Comment by BDominik** [comment] 2024-12-22 07:57
Thanks for the info.
As soon as I run the first command and then npm i I got this error.
![Image](https://github.com/user-attachments/assets/f9aa51ac-814a-4b03-aa7e-9e2c2c19bec6)

**Comment by BDominik** [comment] 2024-12-25 08:10
So for me  the solution was to remove ngrx/signals and @angular-architects/ngrx-toolkit from package json.
then npm i was working with the updated versions.
After then I installed back ngrx/signals, but @angular-architects/ngrx-toolkit still can't install.
Also noticed that one of my signal featureStore  is broken, where I import computed into from the parent signal store.
but everything  else seems good.
