### ISSUE TITLE
Jest --watch does not considers test in lib folder

### ISSUE THREAD

**Issue by roger-gl** [nrwl/nx#2031] opened 2019-11-07 10:27 UTC
## Expected Behavior

jest --watch should run the same tests like jest without the watch flag

## Current Behavior

npm run test runs all test, but if I add the watch flag only tests in app folder are run.

**Comment by FrozenPandaz** [comment] 2019-12-06 22:12
`npm run test --watch` will run all projects with a `test` target serially.

This means that the first project (usually an app) will be the project run with `--watch` and it will wait until that finishes before moving onto the 2nd project and so forth.

Beacuse we actually run tests for each project, if you want to run tests with a watch mode, you should really run

```
npm run test my-lib --watch
```

I hope this answers your question.

Closing this issue as this is not the intended behavior.

**Closed by FrozenPandaz** 2019-12-06 22:12 UTC
Labels: scope: testing tools, type: question / discussion
