### ISSUE TITLE
Unable to load tsconfig-paths, workspace libraries may be inaccessible.

### ISSUE THREAD

**Issue by beeman** [nrwl/nx#19539] opened 2023-10-10 16:27 UTC
### Current Behavior

When running `nx serve` in my project, I get the following message:

```
Unable to load tsconfig-paths, workspace libraries may be inaccessible.
  - To fix this, install tsconfig-paths with npm/yarn/pnpm
``` 

However, the package `tsconfig-paths` is installed:

```
yarn why tsconfig-paths        
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "tsconfig-paths"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "tsconfig-paths@4.2.0"
info Has been hoisted to "tsconfig-paths"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@nx#js#tsconfig-paths"
   - Hoisted from "nx#tsconfig-paths"
   - Hoisted from "@nx#webpack#tsconfig-paths-webpack-plugin#tsconfig-paths"
info Disk size without dependencies: "432KB"
info Disk size with unique dependencies: "872KB"
info Disk size with transitive dependencies: "872KB"
info Number of shared dependencies: 3
=> Found "eslint-plugin-import#tsconfig-paths@3.14.2"
info This module exists because "eslint-plugin-import" depends on it.
info Disk size without dependencies: "436KB"
info Disk size with unique dependencies: "892KB"
info Disk size with transitive dependencies: "892KB"
info Number of shared dependencies: 4
✨  Done in 0.28s.

```

### Expected Behavior

The message should not appear when the package is installed.

### GitHub Repo

https://github.com/beeman/nx-app-warning-tsconfig-paths

### Steps to Reproduce

1. clone repo
2. run `nx serve app`
3. check the output

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin-arm64
   yarn   : 1.22.19
   
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nx/rollup         : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/web            : 16.10.0
   @nx/webpack        : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @parago/starter-anchor : 1.16.17
   @parago/starter-react  : 1.16.17
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I'm using a custom generator that wraps around the @nx/react generator. The source of the generator can be found [here](https://github.com/beeman/parago/blob/main/packages/starter-react/src/generators/application/generator.ts).

**Comment by enchorb** [comment] 2023-10-11 17:56
Maybe a duplicate of: https://github.com/nrwl/nx/issues/19460

**Comment by AgentEnder** [comment] 2023-10-12 20:55
I'm going to close this out since its a duplicate and the fix has landed on master. The fix should currently be available in the v17 betas.

**Closed by AgentEnder** 2023-10-12 20:55 UTC
Labels: type: bug
