### ISSUE TITLE
Upgrading from 14.7.5 to 14.7.6 causes environment variables to be undefined

### ISSUE THREAD

**Issue by benpsnyder** [nrwl/nx#12117] opened 2022-09-20 12:34 UTC
We were running 14.7.5 and after updating to 14.7.6 we can't read environment variables properly.

Change in `project.json` of our NestJS service
![image](https://user-images.githubusercontent.com/707567/191135599-0614837a-4d97-4f28-a47b-2315278cd3f5.png)

After building and executing the `main.js` with the `.env` set and checked to be valid:
![image](https://user-images.githubusercontent.com/707567/191135689-847ff03c-307b-4b5a-8b5e-d6dae9f3c1c8.png)

How the code looks
![image](https://user-images.githubusercontent.com/707567/191135766-c4aaae45-1fd8-4150-9033-6cb411ff50a0.png)

After reverting the `project.json` files and back to Nx 14.7.5, clearing `node_modules` and reinstalling via `pnpm install` got the ENV VARS reading again.
![image](https://user-images.githubusercontent.com/707567/191258587-0afbd8e5-d278-40a5-a1e3-9ba26dbb3947.png)

**Comment by Michsior14** [comment] 2022-09-20 16:06
Duplicate of #12108

**Comment by AgentEnder** [comment] 2022-09-23 21:38
Fixed in 14.7.9

**Closed by AgentEnder** 2022-09-23 21:38 UTC
Labels: type: bug
