### ISSUE TITLE
Invalid Version error while creating pruned lockfile

### ISSUE THREAD

**Issue by fguitton** [nrwl/nx#17026] opened 2023-05-15 14:11 UTC
### Current Behavior

Hello !

I hope you're having a marvellous day 🌴 

I am experiencing an issue with version resolution whereby package versions get resolved as their '_resolved_' URL instead of the proper semver string. Eventually the URL is pasted to `semver` which chokes on it and the command errors (see below)

I have looked in context at #16886 and decided to play with the `findVersion` function in `yarn-parser.ts` and after returning `snapshot.version` instead of `snapshot.resolved` the Invalid version error disappears down the line but a new problem shows in `findOriginalKeys`.

More investigation is needed I will see to provide more information if I find the time to dig into it further.

Thank you in advance for any help addressing this 🚀 

https://github.com/nrwl/nx/blob/d26f26a98b679c056109325dabce7a0cb757f3a5/packages/nx/src/plugins/js/lock-file/yarn-parser.ts#L144-L150

![image](https://github.com/nrwl/nx/assets/2495155/da91e5df-bb20-43d0-bab3-96b1c57e7a54)

```
 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.

Original error: Invalid Version: https://registry.yarnpkg.com/@octokit/rest/-/rest-19.0.7.tgz#d2e21b4995ab96ae5bfae50b4969da7e04e0bb70

```

### Expected Behavior

Version is resolved properly and the lockfile is generated correctly.

### Steps to Reproduce

1. Configure a project to build using `@nx/webpack:webpack` with `generateLockfile` and `generatePackageJson` set to `true`
2. Run `nx build project`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : win32 x64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/detox          : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/esbuild        : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/expo           : 16.1.0
   @nx/express        : 16.1.0
   @nx/next           : 16.1.0
   @nx/node           : 16.1.0
   @nx/react          : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/web            : 16.1.0
   @nx/webpack        : 16.1.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 3.0.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

At this point I am unable to move to Nx 16.1 as is has seemingly breaking changes having to do with ESM modules.

**Comment by cwoebker** [comment] 2023-05-15 15:55
We are facing the same issue now. Currently, we are trying to pinpoint internally when exactly this regression started to happen since we've already been using NX on version 16.1.1.

**Comment by cwoebker** [comment] 2023-05-15 16:30
@meeroslav I also just looked at the issue here and confirm we are still getting the following error on NX 16.1.4.

```
>  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable


   TypeError: findOriginalKeys is not a function or its return value is not iterable
```

I have to rather large yarn.lock files that I could share directly with you. The first working one, and the second one (some lock file maintenance via the renovate bot) where the error started to pop up.

```
 >  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native

   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/express        : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ionic/angular         : 7.0.6
   @ionic/angular-toolkit : 9.0.0
   @ngneat/spectator      : 14.0.0
   @ngrx/effects          : 15.4.0
   @ngrx/entity           : 15.4.0
   @ngrx/router-store     : 15.4.0
   @ngrx/store            : 15.4.0
   @ngrx/store-devtools   : 15.4.0
   ngx-toastr             : 16.2.0
   ngx-ui-loader          : 13.0.0
   ---------------------------------------
   Local workspace plugins:
   	 @remberg/remberg-nx-plugin

✨  Done in 3.53s.
```

**Comment by enchorb** [comment] 2023-05-16 20:09
Getting `TypeError: findOriginalKeys is not a function or its return value is not iterable` as well

**Comment by dalenguyen** [comment] 2023-05-17 09:33
Same issue in `16.1.4`

```
 >  NX   An error occured while creating pruned lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: findOriginalKeys is not a function or its return value is not iterable
```

nx report 

```
>  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin arm64
   yarn   : 1.22.19
   Hasher : Native
   
   nx                 : 16.1.4
   @nx/js             : 16.1.4
   @nx/jest           : 16.1.4
   @nx/linter         : 16.1.4
   @nx/workspace      : 16.1.4
   @nx/angular        : 16.1.4
   @nx/cypress        : 16.1.4
   @nx/devkit         : 16.1.4
   @nx/eslint-plugin  : 16.1.4
   @nx/nest           : 16.1.4
   @nx/node           : 16.1.4
   @nx/plugin         : 16.1.4
   @nx/storybook      : 16.1.4
   @nrwl/tao          : 16.1.4
   @nx/webpack        : 16.1.4
   nx-cloud           : 16.0.5
   typescript         : 4.7.4
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc    : 1.1.19
   @ngneat/spectator     : 11.3.0
   @ngneat/transloco     : 3.1.1
   @ngrx/component-store : 14.3.3
   @ngrx/data            : 14.0.0
   @ngrx/effects         : 14.0.0
   @ngrx/entity          : 14.0.0
   @ngrx/router-store    : 14.0.0
   @ngrx/schematics      : 14.0.0
   @ngrx/store           : 14.0.0
   @ngrx/store-devtools  : 14.0.0
   @storybook/angular    : 7.0.12
   ---------------------------------------
```

**Comment by meeroslav** [comment] 2023-05-20 09:02
This issue has been resolved. Please update to latest version.

**Comment by meeroslav** [comment] 2023-05-20 09:10
Sorry, read just the last message and closed it by mistake.

For everyone getting "findOriginalKeys is not a function or its return value is not iterable" please update to latest version. This should be fixed in v16.2.0.

Please note that there are no regression errors, but rather this error occurs when your packages get into state that previous code didn't resolve properly (which can happen with luck file changes).

I will investigate the original error reported here as soon as possible, as that should not be happening.

Unfortunately I'm away from computer until next Wednesday.

**Comment by fguitton** [comment] 2023-05-22 19:44
Hello @meeroslav,

Thank you for looking at this ! I've already sent the full file in a Slack DM, but for the record, the error above is triggered by the snippet below.

Happy to answer any other questions 😉 

```
"@octokit/request-error@^2.0.2", "@octokit/request-error@^2.0.5", "@octokit/request-error@^2.1.0", "@octokit/request-error@^3", "@octokit/request-error@^3.0.0", "@octokit/request-error@^3.0.3":
  version "3.0.3"
  resolved "https://registry.yarnpkg.com/@octokit/request-error/-/request-error-3.0.3.tgz#ef3dd08b8e964e53e55d471acfe00baa892b9c69"
  integrity sha512-crqw3V5Iy2uOU5Np+8M/YexTlT8zxCfI+qu+LxUB7SZpje4Qmx3mub5DfEKSO8Ylyk0aogi6TYdf6kxzh2BguQ==
  dependencies:
    "@octokit/types" "^9.0.0"
    deprecation "^2.0.0"
    once "^1.4.0"

"@octokit/request@^5.6.0", "@octokit/request@^5.6.3", "@octokit/request@^6", "@octokit/request@^6.0.0", "@octokit/request@^6.2.3":
  version "6.2.3"
  resolved "https://registry.yarnpkg.com/@octokit/request/-/request-6.2.3.tgz#76d5d6d44da5c8d406620a4c285d280ae310bdb4"
  integrity sha512-TNAodj5yNzrrZ/VxP+H5HiYaZep0H3GU0O7PaF+fhDrt8FPrnkei9Aal/txsN/1P7V3CPiThG0tIvpPDYUsyAA==
  dependencies:
    "@octokit/endpoint" "^7.0.0"
    "@octokit/request-error" "^3.0.0"
    "@octokit/types" "^9.0.0"
    is-plain-object "^5.0.0"
    node-fetch "^2.6.7"
    universal-user-agent "^6.0.0"

"@octokit/rest@^18.0.6", "@octokit/rest@^19", "@octokit/rest@^19.0.7":
  version "19.0.7"
  resolved "https://registry.yarnpkg.com/@octokit/rest/-/rest-19.0.7.tgz#d2e21b4995ab96ae5bfae50b4969da7e04e0bb70"
  integrity sha512-HRtSfjrWmWVNp2uAkEpQnuGMJsu/+dBr47dRc5QVgsCbnIc1+GFEaoKBWkYG+zjrsHpSqcAElMio+n10c0b5JA==
  dependencies:
    "@octokit/core" "^4.1.0"
    "@octokit/plugin-paginate-rest" "^6.0.0"
    "@octokit/plugin-request-log" "^1.0.4"
    "@octokit/plugin-rest-endpoint-methods" "^7.0.0"

"@octokit/types@^6.0.1", "@octokit/types@^6.0.3", "@octokit/types@^6.39.0", "@octokit/types@^6.40.0", "@octokit/types@^8.0.0", "@octokit/types@^9", "@octokit/types@^9.0.0":
  version "9.2.0"
  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-9.2.0.tgz#0358e3de070b1d43c5a8af63b9951c88a09fc9ed"
  integrity sha512-xySzJG4noWrIBFyMu4lg4tu9vAgNg9S0aoLRONhAEz6ueyi1evBzb40HitIosaYS4XOexphG305IVcLrIX/30g==
  dependencies:
    "@octokit/openapi-types" "^17.1.0"

"@octokit/webhooks-methods@^2.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/@octokit/webhooks-methods/-/webhooks-methods-2.0.0.tgz#1108b9ea661ca6c81e4a8bfa63a09eb27d5bc2db"
  integrity sha512-35cfQ4YWlnZnmZKmIxlGPUPLtbkF8lr/A/1Sk1eC0ddLMwQN06dOuLc+dI3YLQS+T+MoNt3DIQ0NynwgKPilig==

"@octokit/webhooks-types@5.8.0":
  version "5.8.0"
  resolved "https://registry.yarnpkg.com/@octokit/webhooks-types/-/webhooks-types-5.8.0.tgz#b76d1a3e3ad82cec5680d3c6c3443a620047a6ef"
  integrity sha512-8adktjIb76A7viIdayQSFuBEwOzwhDC+9yxZpKNHjfzrlostHCw0/N7JWpWMObfElwvJMk2fY2l1noENCk9wmw==

"@octokit/webhooks@^9.8.4":
  version "9.26.0"
  resolved "https://registry.yarnpkg.com/@octokit/webhooks/-/webhooks-9.26.0.tgz#cf453bb313da3b66f1a90c84464d978e1c625cce"
  integrity sha512-foZlsgrTDwAmD5j2Czn6ji10lbWjGDVsUxTIydjG9KTkAWKJrFapXJgO5SbGxRwfPd3OJdhK3nA2YPqVhxLXqA==
  dependencies:
    "@octokit/request-error" "^2.0.2"
    "@octokit/webhooks-methods" "^2.0.0"
    "@octokit/webhooks-types" "5.8.0"
    aggregate-error "^3.1.0"
```

**Comment by cwoebker** [comment] 2023-05-23 17:05
@meeroslav You are right the issue with `findOriginalKeys` was resolved after upgrading v16.2.1. Thanks a lot for the quick work there.

Unfortunately, we now encounter a different issue with the same yarn.lock file changes that I mentioned in my previous comment here: https://github.com/nrwl/nx/issues/17026#issuecomment-1548179924

We now get this error message during pruned lockfile generation:

```
> nx run PROJECT:build:production
 >  NX   An error occured while creating pruned lockfile
   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   To prevent the build from breaking we are returning the root lock file.
   
Original error: Cannot read properties of undefined (reading 'has')
   TypeError: Cannot read properties of undefined (reading 'has')
    at /builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:230:47
    at Map.forEach (<anonymous>)
    at mapSnapshots (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:221:17)
    at stringifyYarnLockfile (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:131:23)
    at createLockFile (/builds/PROJECT/node_modules/nx/src/plugins/js/lock-file/lock-file.js:132:60)
    at /builds/PROJECT/node_modules/@nx/webpack/src/plugins/generate-package-json-plugin.js:42:124
    at fn (/builds/PROJECT/node_modules/@nx/webpack/node_modules/webpack/lib/Compilation.js:479:10)
    at _next0 (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:65:1)
    at eval (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at eval (eval at create (/builds/PROJECT/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
chunk (runtime: main) main.js (main) 374 KiB [entry] [rendered]
webpack compiled successfully (830ea7ca5a366d2f)
```

I can create a new issue with more information if needed, and also share the two relevant lock files if this is helpful.

**Comment by dalenguyen** [comment] 2023-05-23 17:40
@cwoebker Same, I also have the same issue after migrating to 16.2.1.

**Closed** 2023-05-25 17:23 UTC
Labels: type: bug, scope: core

**Comment by cwoebker** [comment] 2023-05-31 12:44
> I mentioned the error @cwoebker is reporting in this PR: [#16886 (comment)](https://github.com/nrwl/nx/pull/16886#issuecomment-1548353780)
> 
> It is essentially the same problem, where
> 
> ```ts
> if (!existingKeys.get(packageName).has(normalizedKey)) {
>     keysSet.delete(key);
> }
> ```
> 
> fails when `packageName` contains `-cjs`

I have created a new issue for this error here: https://github.com/nrwl/nx/issues/17329
