### ISSUE TITLE
Can't use support file in cypress

### ISSUE THREAD

**Issue by KarmaCop213** [nrwl/nx#2739] opened 2020-03-27 15:25 UTC
## Expected Behavior

In cypress.json
replacing
`"supportFile": false,`
with
`"supportFile": "./src/support/index.ts",`

should be possible and spec files should be able to use the custom commands defined inside it.

## Current Behavior

Can't use the support file in cypress.

In cypress.json
replaced
`"supportFile": false,`
with
`"supportFile": "./src/support/index.ts",`

tests build but then hang after line
`Using 1 worker with 2048MB memory limit` 

cypress electron browser starts but is blank and stopped.

**Comment by FrozenPandaz** [comment] 2020-03-27 18:53
Hello, please provide the version of Nx that are you using.

This was fixed in version [8.12.0](https://github.com/nrwl/nx/releases/tag/8.12.0) in https://github.com/nrwl/nx/pull/2316. Please update to the latest version and check to see if the issue is resolved. 

If the issue was not resolved, please reopen this issue.

**Closed by FrozenPandaz** 2020-03-27 18:53 UTC

**Comment by KarmaCop213** [comment] 2020-03-28 16:19
Thank you very much!
