### ISSUE TITLE
Weird symbols in terminal when loosing focus to fast

### ISSUE THREAD

**Issue by ratatoeskr666** [nrwl/nx#22715] opened 2024-04-07 09:19 UTC
### Current Behavior

When executing an NX command like `nx serve <projectName>` and leaving the powershell/cmd to fast, weird symbols are being printed out and the execution pauses until I press enter:
![image](https://github.com/nrwl/nx/assets/3856060/8b94f147-6d5e-49f4-9b5f-bd63c7a3edaf)

It happens since an upgrade to NX 18.2.1 and NodeJS 20 LTS. 
Tested on two different windows machines. The application doesn't matter, I have the issue with Angular, NestJS and even with a custom command.

### Expected Behavior

The command is being executed even if I loose focus to the powershell/terminal shortly after

### Steps to Reproduce

1. Create an empty project with NX 18.2.1 
2. Create an application (e.g. angular)
3. Type `nx serve <appName>` into a powershell/terminal, submit with enter and quickly switch to another window (loose focus)

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.0
OS     : win32-x64
npm    : 9.7.1

nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/angular        : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/esbuild        : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/node           : 18.2.1
@nx/playwright     : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
---------------------------------------
Community plugins:
@ngneat/transloco : 6.0.4
ngx-build-plus    : 17.0.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by ratatoeskr666** [comment] 2024-04-13 09:09
The issue magically disappeared on both of my windows machines after a couple of days and restarts ¯\_(ツ)_/¯
I will close the issue since I can no longer reproduce the bug

**Comment by mandy8055** [comment] 2024-04-15 12:51
This issue persists for react standalone application as well. For me it occurred frequently when running `nx lint`

**Comment by ratatoeskr666** [comment] 2024-04-21 09:41
Aaaaand the issue is back. I have no idea why, nothing changed

**Comment by christianerbsmehl** [comment] 2024-04-22 11:39
Getting a similar output when simply executing `nx test` on Windows 11 / nx with @nx/anular 18.3.1 and node 20.12.2

```
>nx test

> nx run myapp:test

> jest

^[[7;1R
```

**Comment by devalimotahari** [comment] 2024-05-04 10:08
@christianerbsmehl  did you find any solution for that?

**Comment by christianerbsmehl** [comment] 2024-05-05 11:53
Still happens to me regularly. `nx reset` fixes it for a while until it appears again.

**Comment by AgentEnder** [comment] 2024-05-10 22:48
Closing this as a duplicate of #22358 - we are trying to get a solid fix for this.

**Closed by AgentEnder** 2024-05-10 22:48 UTC
Labels: type: bug, scope: core
