### ISSUE TITLE
Cannot read properties of undefined (reading 'endsWith') local plugin

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [nrwl/nx#11360] opened 2022-07-29 18:43 UTC
## Current Behavior

When I generate a local plugin and attempt to run it (or any Nx command), I get this error message
> Cannot read properties of undefined (reading 'endsWith')
## Expected Behavior

Nx commands should run and the local plugin should work as expected.
## Steps to Reproduce

1. Clone this github repo: https://github.com/AndrewOttavianoAbb/nx-plugin-test
2. Run any Nx command: `nx build test-lib`
3. Observe the error in the terminal

To create this repo, I generated it using version 13 (since we have a dependency on React 17 right now), generated a library, and then generated a plugin. I encountered the error after running an Nx command. This is an example repo of a bigger one that we created a while ago where I was trying to add a generator and ran into the same issue.

### Failure Logs

> NX   Cannot read properties of undefined (reading 'endsWith')
### Environment

```
   Node : 16.15.0
   OS   : win32 x64
   npm  : 8.0.0
   
   nx : 13.10.6
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.4.3
   @nrwl/eslint-plugin-nx : 13.10.6
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.6
   @nrwl/js : 13.10.6
   @nrwl/linter : 13.10.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.4.3
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.6
   typescript : 4.6.4
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by AgentEnder** [comment] 2022-08-02 14:13
Hey @AndrewOttavianoAbb, it may be unrelated, but some of your @nrwl/* packages don't line up with the version of `nx` you have installed. Aside from `@nrwl/nx-cloud`, all packages under the nrwl scope should generally be set up with the same version. 

Can you correct this and check that the issue still reproduces? An easy way to fix this would be to run `nx migrate {v}`, where `v` is the version of nx you have installed. Alternatively, updating to latest with `nx migrate latest` would also work.

**Comment by AndrewOttavianoAbb** [comment] 2022-08-02 18:20
I ran that migrate command to version `13.10.6` and here is the output
```
nx migrate 13.10.6
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@13.10.6
Fetching @nrwl/workspace@13.10.6

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'npm install'
- To learn more go to https://nx.dev/using-nx/updating-nx
- You may run 'npm run nx -- connect-to-nx-cloud' to get faster builds, GitHub integration, and more. Check out https://nx.app
```

The only change was that it added another new line at the end of my `package.json`. I looked at the deps and it looks like `@nrwl/nx-plugin` and `@nrwl/devkit` are the deps out of sync (that I was expecting the command to change). Are you asking that I try setting those to `13.10.6`?

**Comment by hmendezm** [comment] 2022-08-19 11:23
Hi everybody,

I have the same issue. Did someone find the solution?

```
   Node : 14.18.1
   OS   : win32 x64
   yarn : 1.22.5

   nx : 13.8.1
   @nrwl/angular : 13.10.6
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.10.6
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : undefined
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.10.6
   @nrwl/tao : 13.8.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.1
   typescript : 4.5.4
   rxjs : 7.5.6
   ---------------------------------------
   Community plugins:
         @angular-architects/module-federation: 14.0.2
         @angular/animations: 13.2.7
         @angular/cdk: 13.3.9
         @angular/common: 13.2.7
         @angular/compiler: 13.2.7
         @angular/core: 13.2.7
         @angular/forms: 13.2.7
         @angular/material: 13.3.9
         @angular/platform-browser: 13.2.7
         @angular/platform-browser-dynamic: 13.2.7
         @angular/router: 13.2.7
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.2.0
         @ngrx/entity: 13.2.0
         @ngrx/router-store: 13.2.0
         @ngrx/store: 13.2.0
         @ngrx/store-devtools: 13.2.0
         devextreme-angular: 21.2.9
         @angular-devkit/build-angular: 13.2.6
         @angular/cli: 13.2.6
         @angular/compiler-cli: 13.2.7
         @angular/language-service: 13.2.7
         @ngrx/schematics: 13.0.2
```

Best
HMendezM

**Comment by AgentEnder** [comment] 2022-08-19 14:00
You've got some packages at 13.10, and Nx migrate won't downgrade versions. I'd recommend running `nx migrate 13.10` at minimum, but if nothing is blocking you `nx migrate latest` would be preferred

**Comment by hmendezm** [comment] 2022-08-22 18:49
Thanks @AgentEnder

**Comment by pschnoop** [comment] 2022-10-25 07:16
Hi,
I'm still getting this error with nx 15.02 :/
Any updates on this?

**Comment by AgentEnder** [comment] 2022-10-25 16:21
@pschnoop Can you run `nx report`, and any command that throws the error like this: `NX_VERBOSE_LOGGING=true {command} --verbose`

**Comment by pschnoop** [comment] 2022-10-26 08:02
@AgentEnder I found another article which had the solution.
The problem is one of my plugins (nx-electron) is using an older version of nx.
I override this by setting the `resolutions` property in package.json.
```json
  "resolutions": {
    "@nrwl/devkit": "15.0.2",
    "@nrwl/workspace": "15.0.2"
  }
```

**Comment by fxck** [comment] 2022-10-27 09:40
Happens to be as well, I create a workspace using `npx create-nx-workspace` with an Angular app, everything works fine, I add another Angular app, everything still works fine, I add an Express.js app and it starts throwing ` >  NX   Cannot read properties of undefined (reading 'endsWith')` and no app can start anymore.

**Comment by AgentEnder** [comment] 2022-10-27 13:26
@fxck if you don't have a local plug-in this isn't the issue for you, I'd recommend opening a new one and including the outputs of `nx report`

**Comment by AgentEnder** [comment] 2022-10-27 13:27
I'm going to go ahead and close this one out, it looks like this 8s just an out of sync deps issue for those involved.

**Closed by AgentEnder** 2022-10-27 13:27 UTC
Labels: type: bug, scope: plugins
