### ISSUE TITLE
nx dep-graph not working with nx 12.5.7 and angular

### ISSUE THREAD

**Issue by autozoom** [nrwl/nx#6329] opened 2021-07-12 06:49 UTC
## Current Behavior
On a fresh nx 12.5.7 workspace with a new angular project, dependency graph doesn't work

## Expected Behavior
nx dep-graph should show the dependency graph
It works with nx 12.3.6

## Steps to Reproduce
npx create-nx-workspace --preset=angular (give any name you want)
cd <workspace folder>
nx dep-graph

### Failure Logs
see attached screenshot
![immagine](https://user-images.githubusercontent.com/15321669/125243174-00e47c80-e2ee-11eb-9e99-ec53d4da8c21.png)

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : 12.5.7
  @nrwl/cli : 12.5.7
  @nrwl/cypress : 12.5.7
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : 12.5.7
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : 12.5.7
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by Poccomaxazt** [comment] 2021-07-12 10:25
It's a duplicate of https://github.com/nrwl/nx/issues/6280

**Comment by autozoom** [comment] 2021-07-12 10:42
duplicate of #6280

**Closed** 2021-07-12 10:42 UTC
Labels: type: bug
