### ISSUE TITLE
angular-nest app does not build

### ISSUE THREAD

**Issue by tommck** [nrwl/nx#5874] opened 2021-06-03 12:57 UTC
## Current Behavior
When generating a brand new angular-jest project, the project gets build errors when running "npm run build"

## Expected Behavior
I would expect it to build properly

I have not tried this particular preset in the past, but I would expect this is a regression.

## Steps to Reproduce

The following steps will result in the failure listed below
```
C:\dev> npx create-nx-workspace
npx: installed 48 in 3.426s
√ Workspace name (e.g., org name)     · deleteme
√ What to create in the new workspace · angular-nest
√ Application name                    · delete
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No
...
C:\dev> cd .\deleteme\
C:\dev\deleteme [main]> npm run build
```

### Failure Logs
```
C:\dev\deleteme [main]> npm run build

> deleteme@0.0.0 build C:\dev\deleteme
> ng build


> nx run delete:build:production
- Generating browser application bundles (phase: setup)...(node:23412) UnhandledPromiseRejectionWarning: TypeError: webpack_1.node.NodeTargetPlugin is not a constructor
    at WebpackResourceLoader._compile (C:\dev\deleteme\node_modules\@ngtools\webpack\src\resource_loader.js:99:13)
    at WebpackResourceLoader.get (C:\dev\deleteme\node_modules\@ngtools\webpack\src\resource_loader.js:240:44)
    at Object.resourceHost.readResource (C:\dev\deleteme\node_modules\@ngtools\webpack\src\ivy\host.js:30:35)
    at AdapterResourceLoader.preload (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\resource\src\loader.js:88:39)
    at resolveStyleUrl (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:192:49)
    at C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:83
    at Array.map (<anonymous>)
    at ComponentDecoratorHandler.preanalyze (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:233:50)
    at _loop_1 (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:53)
    at TraitCompiler.analyzeClass (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:343:35)
    at visit (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:113:27)
    at visitNodes (C:\dev\deleteme\node_modules\typescript\lib\typescript.js:28217:30)
    at Object.forEachChild (C:\dev\deleteme\node_modules\typescript\lib\typescript.js:28456:24)
    at visit (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:115:20)
    at TraitCompiler.analyze (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:117:13)
    at TraitCompiler.analyzeAsync (C:\dev\deleteme\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:79:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
√ Browser application bundle generation complete.

Error: NormalModuleFactory.beforeResolve (NormalModuleReplacementPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.

Error: NormalModuleFactory.beforeResolve (NormalModuleReplacementPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.

Error: NormalModuleFactory.beforeResolve (NormalModuleReplacementPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.



———————————————————————————————————————————————

>  NX   ERROR  Running target "delete:build" failed

  Failed tasks:

  - delete:build:production

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deleteme@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deleteme@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tom.McKearney\AppData\Roaming\npm-cache\_logs\2021-06-03T12_52_08_696Z-debug.log
C:\dev\deleteme [main]>
```

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : 12.3.6
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by leosvelperez** [comment] 2021-06-03 16:15
Thanks for reporting this!

This is a duplicate of #5682. You can check [this comment](https://github.com/nrwl/nx/issues/5682#issuecomment-842320300) for an explanation and a solution.

Closing this.

**Closed by leosvelperez** 2021-06-03 16:15 UTC
Labels: type: bug

**Comment by tommck** [comment] 2021-06-03 18:29
@leosvelperez - thank you for the prompt response. Sorry I didn't find that other one when I searched.

**Comment by leosvelperez** [comment] 2021-06-03 18:35
@tommck no worries!
