### ISSUE TITLE
build error - ng build libs 

### ISSUE THREAD

**Issue by psumal** [nrwl/nx#1448] opened 2019-06-04 08:11 UTC
BUILD ERROR - Maximum call stack size exceeded

# Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Command :  ng build wf-core-libs

Result:
Building Angular Package
Building entry point '@wf-apps/wf-core-libs'
Compiling TypeScript sources through ngc

BUILD ERROR
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at MetadataBundler.convertValue (...\node_modules\@angular\compiler-cli\src\metadata\bundler.js:404:59)

package.json

 "dependencies": {
    "@nrwl/angular": "8.0.1",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "~8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ngrx/effects": "7.4.0",
    "@ngrx/entity": "7.4.0",
    "@ngrx/router-store": "7.4.0",
    "@ngrx/store": "7.4.0",
    "angular2-notifications": "^2.0.0",
    "bootstrap": "3.4.1",
    "buffer": "^5.2.1",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "mqtt": "^2.18.8",
    "process": "^0.11.10",
    "rxjs": "6.5.2",
    "three": "^0.104.0",
    "underscore": "^1.9.1",
    "xlsx": "^0.14.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@nrwl/workspace": "8.0.1",
    "@nrwl/jest": "8.0.1",
    "@nrwl/cypress": "8.0.1",
    "ts-jest": "24.0.0",
    "jest-preset-angular": "7.0.0",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "^8.0.0",
    "@angular-devkit/build-angular": "~0.800.0",
    "codelyzer": "^5.0.1",
    "@angular-devkit/build-ng-packagr": "~0.800.0",
    "@angular/cli": "8.0.1",
    "@ngrx/store-devtools": "^7.4.0",
    "@types/jest": "24.0.9",
    "@types/jquery": "3.3.6",
    "@types/node": "~8.9.4",
    "cypress": "3.1.0",
    "dotenv": "6.2.0",
    "jest": "24.1.0",
    "ng-packagr": "^5.2.0",
    "ngrx-store-freeze": "0.2.4",
    "prettier": "1.16.4",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "3.4.5"
  }

**Comment by psumal** [comment] 2019-06-04 08:36
with 
    "@nrwl/builders": "7.8.4",
    "@nrwl/schematics": "7.8.4",
and 
    "@nrwl/nx": "7.8.6",

it works.

**Comment by matheo** [comment] 2019-06-04 16:12
@psumal it doesn't work after you upgraded everything to `^8.0.0`?
no other library upgraded? any special processing inside `@wf-apps/wf-core-libs`?
your `tsconfig.json` would help too.

**Comment by psumal** [comment] 2019-06-04 16:50
it doesn't work after you upgraded everything to ^8.0.0? no other library upgraded? 
i have only nx updated. see attachment.

wf-core-libs(scss file, components, pipes, services, generated with nx)

(left work - right don't work)
nx-workspace - package.json 
![image](https://user-images.githubusercontent.com/16747485/58897271-3a526300-86f8-11e9-801a-a47b21a44608.png)

tsconfig from nx-workspace
![image](https://user-images.githubusercontent.com/16747485/58897535-d0868900-86f8-11e9-913e-750aa05e7873.png)

tsconfig from wf-core-libs
![image](https://user-images.githubusercontent.com/16747485/58897704-383cd400-86f9-11e9-8af0-5b21b56dd859.png)

**Comment by vsavkin** [comment] 2019-06-04 21:11
@psumal could you provide a repository reproducing the issue?

**Comment by psumal** [comment] 2019-06-05 06:05
yes I will prepare a repo.
i have removed one component after another from the index.js.
the problem is the following service. 

**my good old guid generator!**
**the question is why the build fails.**

@Injectable({
  providedIn: 'root'
})
export class WfGuidService {

  static generate() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      const r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }

  constructor() { }
}

**Comment by psumal** [comment] 2019-06-05 19:09
Repo 
https://github.com/psumal/nx-build-libs-error

The problem is the static function.
I think it is not correct if I called the static function without injector.
but i need the guid in an abstract class. 

![image](https://user-images.githubusercontent.com/16747485/58982554-05680e00-87d5-11e9-9349-29040bbf6998.png)

**Comment by psumal** [comment] 2019-06-06 10:43
Hello
Repos finished.

Mit freundlichen Grüßen
                       Sommer Patrik

 [NEUMAN Aluminium Strangpressen klein]
Neuman Aluminium Strangpresswerk
STA – Leitung  Automatisierung

Sommer Patrik
Werkstrasse 1 A-3182 Marktl Austria
Tel: +43 2762 500-483
Mobil: +43 664 24 00 363



Von: Victor Savkin <notifications@github.com>
Gesendet: Dienstag, 4. Juni 2019 23:11
An: nrwl/nx <nx@noreply.github.com>
Cc: Sommer Patrik <Patrik.Sommer@neuman.at>; Mention <mention@noreply.github.com>
Betreff: Re: [nrwl/nx] build error - ng build libs (#1448)


@psumal<https://github.com/psumal> could you provide a repository reproducing the issue?

**Comment by vsavkin** [comment] 2019-06-19 23:41
@psumal  It looks like an issue with the angular compiler itself. Can you reproduce this issue in a regular CLI project?

**Comment by vsavkin** [comment] 2019-12-05 14:18
I'm sorry, but I'm going to close this. If the problem persists, please reopen the issue.

**Closed by vsavkin** 2019-12-05 14:18 UTC
Labels: blocked: repro needed, blocked: third-party, type: bug
