### ISSUE TITLE
[WEBSTORM] wrong import

### ISSUE THREAD

**Issue by czaplej** [nrwl/nx#3467] opened 2020-08-04 08:14 UTC
After upgrade to nx 10.0.* webstorm start importing modules as below

## Current Behavior

![image](https://user-images.githubusercontent.com/29889157/89269816-b87f0200-d63a-11ea-8d39-6d85418a5147.png)
## Expected Behavior

![image](https://user-images.githubusercontent.com/29889157/89269858-c765b480-d63a-11ea-8b2c-0b1ebe96fcfb.png)

## Steps to Reproduce

Just create new workspace and use with webstorm

### Environment

nx version : 10.0.7
react

**Comment by zaunermax** [comment] 2020-08-04 08:25
That is something you have to configure in your IDE, not something that is actionable by the nx team. Maybe you have turned on the setting to always use relative imports.

**Comment by czaplej** [comment] 2020-08-04 08:32
@zaunermax it works before update nx. Nothing in the webstorm was changed

**Comment by nestorvanz** [comment] 2020-08-05 03:21
This is happening in VSCode too. Even after create the `tsconfig.json` in the root project.

**Comment by zaunermax** [comment] 2020-08-06 08:54
I think it depends on how you have your IDEs configured. If it is configured to search for a root tsconfig file, then this will break. Though most of the time (and also webstorm by default, I use 2020.2) IDEs will search for the most relevant and nearest tsconfig file. Due to the fact that every app and lib has a standard tsconfig in it's root, IDEs should handle that just fine. The tsconfig in the root of the apps and libs extends the base tsconfig.

**Comment by Cammisuli** [comment] 2020-08-07 13:33
If you're not on the latest version of Webstorm (as of this comment 2020.2) you might have to add `tsconfig.base.json` into your file types (`Settings > Editor > File Types`), like so:
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/4332460/89650809-f70dfa00-d890-11ea-855a-01c6e79c87c2.png">

Again, this should already be the default with the latest version of Webstorm (and even VS Code)

**Comment by vsavkin** [comment] 2020-08-07 19:33
Folks. I'm going to close this as the issue is the latest version of Webstorm and isn't actionable on the Nx side.

**Closed by vsavkin** 2020-08-07 19:33 UTC
Labels: type: question / discussion

**Comment by nhhockeyplayer** [comment] 2021-02-20 07:12
this is still an issue

front end apps import fine

BUT
node.js server apps are doing precisely the same problem 

Im unable to use my isomorphic interfaces and libs
