### ISSUE TITLE
[Module federation] Upgrade to NX 18 causes error duirng `nx serve`

### ISSUE THREAD

**Issue by vadjs** [nrwl/nx#21681] opened 2024-02-07 17:00 UTC
### Current Behavior

After upgrade to NX 18 all react host applications becomes faulty.
`Could not load /Users/vad-js/nebo/ui/monorepo/apps/backoffice/module-federation.config.ts. Was this project generated with "@nx/react:host"?`

### Expected Behavior

App should run.
Probably there should be a migration from NX v17 to NX v18.

### Steps to Reproduce

1. Generate react host & mfe projects using NX 17 according to this guide: https://nx.dev/concepts/module-federation/micro-frontend-architecture
2. nx migrate latest
3. nx serve <react-mfe-host-app>
4. get error

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : darwin-arm64
   npm    : 10.3.0

   nx (global)        : 18.0.2
   nx                 : 18.0.2
   @nx/js             : 18.0.2
   @nx/jest           : 18.0.2
   @nx/linter         : 18.0.2
   @nx/eslint         : 18.0.2
   @nx/workspace      : 18.0.2
   @nx/devkit         : 18.0.2
   @nx/eslint-plugin  : 18.0.2
   @nx/nest           : 18.0.2
   @nx/node           : 18.0.2
   @nx/playwright     : 18.0.2
   @nx/plugin         : 18.0.2
   @nx/react          : 18.0.2
   @nrwl/tao          : 18.0.2
   @nx/web            : 18.0.2
   @nx/webpack        : 18.0.2
   typescript         : 5.3.3
```

### Failure Logs

```shell
nx serve backoffice --verbose

> nx run backoffice:serve:development


 >  NX   Could not load /Users/vad-js/nebo/ui/monorepo/apps/backoffice/module-federation.config.ts. Was this project generated with "@nx/react:host"?

   See: https://nx.dev/concepts/more-concepts/faster-builds-with-module-federation

Error: Could not load /Users/vad-js/nebo/ui/monorepo/apps/backoffice/module-federation.config.ts. Was this project generated with "@nx/react:host"?
See: https://nx.dev/concepts/more-concepts/faster-builds-with-module-federation
    at getModuleFederationConfig (/Users/vad-js/nebo/ui/monorepo/node_modules/@nx/webpack/src/utils/module-federation/get-remotes-for-host.js:85:15)
    at moduleFederationDevServer (/Users/vad-js/nebo/ui/monorepo/node_modules/@nx/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.js:138:86)
    at moduleFederationDevServer.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/Users/vad-js/nebo/ui/monorepo/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/Users/vad-js/nebo/ui/monorepo/node_modules/nx/src/command-line/run/run.js:43:94)
    at /Users/vad-js/nebo/ui/monorepo/node_modules/nx/src/command-line/run/run.js:169:16
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handleErrors (/Users/vad-js/nebo/ui/monorepo/node_modules/nx/src/utils/params.js:9:16)
    at process.<anonymous> (/Users/vad-js/nebo/ui/monorepo/node_modules/nx/bin/run-executor.js:59:28)

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project backoffice failed

   Failed tasks:

   - backoffice:serve:development

   Hint: run the command with --verbose for more details.
```

### Package Manager Version

npm -v 10.3.0

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Aubrey-Russell** [comment] 2024-02-07 17:46
@vadjs I have also seen this error and have mentioned it here for reference:

https://github.com/nrwl/nx/issues/21633

**Comment by Aubrey-Russell** [comment] 2024-02-07 17:48
Maybe the problem is typescript vs js. I have js, module-federation.config.js, which seems to work. Try switching back to javascript and make sure to update all dependent files using this

**Comment by AgentEnder** [comment] 2024-02-07 23:38
Closing this in favor of https://github.com/nrwl/nx/issues/21633

**Closed by AgentEnder** 2024-02-07 23:38 UTC
Labels: type: bug

**Comment by vadjs** [comment] 2024-02-08 10:04
@Aubrey-Russell switch Webpack config to JS didn't change anything.
