### ISSUE TITLE
@typescript-eslint/parser peer dependency is not updated

### ISSUE THREAD

**Issue by hard-rox** [nrwl/nx#27630] opened 2024-08-24 23:50 UTC
### Current Behavior

In ```@nx/eslint-plugin ``` there is a peer dependency of ```@typescript-eslint/parser: ^6.13.2 || ^7.0.0``` which is preety backward since current ```@typescript-eslint/parser``` version is ```8.2.0```.
So current behavior of ```npm i``` is

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @nx/eslint-plugin@19.6.2
npm error Found: @typescript-eslint/parser@8.2.0
npm error node_modules/@typescript-eslint/parser
npm error   dev @typescript-eslint/parser@"^8.2.0" from the root project
npm error   peer @typescript-eslint/parser@"^8.0.0 || ^8.0.0-alpha.0" from @typescript-eslint/eslint-plugin@8.2.0
npm error   node_modules/@typescript-eslint/eslint-plugin
npm error     dev @typescript-eslint/eslint-plugin@"^8.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @typescript-eslint/parser@"^6.13.2 || ^7.0.0" from @nx/eslint-plugin@19.6.2
npm error node_modules/@nx/eslint-plugin
npm error   dev @nx/eslint-plugin@"19.6.2" from the root project
npm error   @nx/eslint-plugin@"19.6.2" from @nrwl/eslint-plugin-nx@19.6.2
npm error   node_modules/@nrwl/eslint-plugin-nx
npm error     @nrwl/eslint-plugin-nx@"19.6.2" from @nx/eslint-plugin@19.6.2
npm error
npm error Conflicting peer dependency: @typescript-eslint/parser@7.18.0
npm error node_modules/@typescript-eslint/parser
npm error   peer @typescript-eslint/parser@"^6.13.2 || ^7.0.0" from @nx/eslint-plugin@19.6.2
npm error   node_modules/@nx/eslint-plugin
npm error     dev @nx/eslint-plugin@"19.6.2" from the root project
npm error     @nx/eslint-plugin@"19.6.2" from @nrwl/eslint-plugin-nx@19.6.2
npm error     node_modules/@nrwl/eslint-plugin-nx
npm error       @nrwl/eslint-plugin-nx@"19.6.2" from @nx/eslint-plugin@19.6.2
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/2024-08-23T23_33_02_560Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-23T23_33_02_560Z-debug-0.log
Error: Process completed with exit code 1.
```

### Expected Behavior

```npm i``` success.

### GitHub Repo

https://github.com/nrwl/nx/tree/master/packages/eslint-plugin

### Steps to Reproduce

1. Install ```@typescript-eslint/parser```
2. Add ```@nx/eslint-plugin```
3. ```npm i```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.4.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.1

nx                 : 19.6.2
@nx/js             : 19.6.2
@nx/jest           : 19.6.2
@nx/linter         : 19.6.2
@nx/eslint         : 19.6.2
@nx/workspace      : 19.6.2
@nx/angular        : 19.6.2
@nx/cypress        : 19.6.2
@nx/devkit         : 19.6.2
@nrwl/devkit       : 19.5.3
@nx/eslint-plugin  : 19.6.2
@nx/storybook      : 19.6.2
@nrwl/tao          : 19.6.2
@nx/web            : 19.6.2
@nx/webpack        : 19.6.2
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core    : 2.4.3
@storybook/angular : 8.2.9
apollo-angular     : 7.1.2
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@19.5.3

To fix this, run `nx migrate nx@19.6.2`
```

### Failure Logs

```shell
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @nx/eslint-plugin@19.6.2
npm error Found: @typescript-eslint/parser@8.2.0
npm error node_modules/@typescript-eslint/parser
npm error   dev @typescript-eslint/parser@"^8.2.0" from the root project
npm error   peer @typescript-eslint/parser@"^8.0.0 || ^8.0.0-alpha.0" from @typescript-eslint/eslint-plugin@8.2.0
npm error   node_modules/@typescript-eslint/eslint-plugin
npm error     dev @typescript-eslint/eslint-plugin@"^8.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @typescript-eslint/parser@"^6.13.2 || ^7.0.0" from @nx/eslint-plugin@19.6.2
npm error node_modules/@nx/eslint-plugin
npm error   dev @nx/eslint-plugin@"19.6.2" from the root project
npm error   @nx/eslint-plugin@"19.6.2" from @nrwl/eslint-plugin-nx@19.6.2
npm error   node_modules/@nrwl/eslint-plugin-nx
npm error     @nrwl/eslint-plugin-nx@"19.6.2" from @nx/eslint-plugin@19.6.2
npm error
npm error Conflicting peer dependency: @typescript-eslint/parser@7.18.0
npm error node_modules/@typescript-eslint/parser
npm error   peer @typescript-eslint/parser@"^6.13.2 || ^7.0.0" from @nx/eslint-plugin@19.6.2
npm error   node_modules/@nx/eslint-plugin
npm error     dev @nx/eslint-plugin@"19.6.2" from the root project
npm error     @nx/eslint-plugin@"19.6.2" from @nrwl/eslint-plugin-nx@19.6.2
npm error     node_modules/@nrwl/eslint-plugin-nx
npm error       @nrwl/eslint-plugin-nx@"19.6.2" from @nx/eslint-plugin@19.6.2
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/2024-08-23T23_33_02_560Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-08-23T23_33_02_560Z-debug-0.log
Error: Process completed with exit code 1.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment] 2024-08-26 13:32
Duplicate of the pinned issue: https://github.com/nrwl/nx/issues/27451

**Closed by JamesHenry** 2024-08-26 13:32 UTC
Labels: type: bug
