### ISSUE TITLE
nx reset: please wait till nx/package.json exists

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#16667] opened 2023-05-01 12:41 UTC
Currently, when you run `nx reset && nx some-other-command` in a newly installed repo, the second command will fail:
```
 >  NX   ENOENT: no such file or directory, open '[..]/node_modules/nx/package.json'

   
   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Please make "nx reset" wait till `./node_modules/nx/package.json` exists before finishing.

## Motivation

This would let users run nx commands after `nx reset`, which is better to run if you reinstall the dependencies.

## Alternate Implementations

Right now I use command in `package.json`:
```
"wait-for-nx-file": "while ! [ -e ./node_modules/nx/package.json ]; do sleep 1; done ",
```
and the chain of commands is:
```
nx reset && yarn run wait-for-nx-file && nx some-other-command
```
Possibly, it's just some macOS-specific behavior, but still, this workaround helps a lot.

**Comment by AgentEnder** [comment] 2023-05-01 17:55
`nx reset` doesn't install or reinstall dependencies, it only does the following:
- Stop the daemon
- Clear your local cache

Can you provide `nx report`? Do you have a global Nx installation? If so, what version is it?

**Comment by e-oz** [comment] 2023-05-01 19:03
Sorry, I haven’t provide enough context.

Chain of the commands:

* remove node_modules
* install all the dependencies
* run `nx reset`
* run `nx some-other-command`

The last command will raise the error I’ve mentioned.


I suppose that because of some macOS-specific behavior, there is a race condition, and the last command runs faster than the file system detects that `./node_modules/nx/package.json` has been created.

**Comment by AgentEnder** [comment] 2023-08-17 04:38
Hey 👋, I'm going to close this out. I can't reproduce the issue on macos, and I'm not sure that it strictly makes sense to wait for the package.json to be present in this case anyways.

**Closed by AgentEnder** 2023-08-17 04:38 UTC
Labels: type: bug, scope: core
