### ISSUE TITLE
libraries in subfolders aren't properly spotted as dependencies to other apps/libs

### ISSUE THREAD

**Issue by kkoo95** [nrwl/nx#1093] opened 2019-02-21 11:20 UTC
## Expected Behavior

When generating a lib within a subdirectory (thanks to the interactive prompt), depency check/graph should work like a "regular" lib 

## Current Behavior

no link is found (in or out) between the deep lib and other libs/apps

### Context

All latest
* version of Nx used: 7.5.2
* version of Angular CLI used: ~7.2.2
* version of Angular DevKit used: ~0.11.2

**Comment by SebasG22** [comment] 2019-04-06 21:47
Can you explain more in details the expected result ?

**Comment by vsavkin** [comment] 2019-04-15 14:59
@kkoo95 could you provide a repro?

**Comment by zachnewburgh** [comment] 2019-05-29 14:34
I also came across this issue after moving shared libraries from libs into a common directory under libs. I've since decided to move those libraries up a level from the common directory, rather than resolve this issue on my own.

The issue, however, manifested after following these steps:

1) Generate a `react-ui` lib using `ng g lib react-ui --framework=react-ui`;
2) Create a `common` directory under libs;
3) Move the `react-ui` lib under `common` and update the root's angular.json, nx.json, tslint.json, as well as the `react-ui` lib's jest.config.js, tsconfig.json, tsconfig.lib.json, tsconfig.spec.json, and tslint.json.

After importing components from `react-ui`, the graph appears as expected when running yarn dep-graph. Once another lib is generated (`ng g lib other-lib`), the `react-ui` lib appears at the side of the graph without any mapped dependencies.

**Comment by vsavkin** [comment] 2019-05-31 13:27
@zachnewburgh this is interesting. Could you provide a repo reproducing the issue?

**Comment by zachnewburgh** [comment] 2019-05-31 13:55
Happy to - just created this [repo](https://github.com/zachnewburgh/nx-issue), which reproduces the error. The error started to manifest in commit 409d52fef78328bd3343e6bd544b6c0f19937a30.

Strangely, when I checked out earlier commits to take screenshots for you, the dependency graph error manifested there, too, even though it worked just fine in those previous commits.

**Comment by vsavkin** [comment] 2019-06-04 23:43
The issue is that the path mapping has to match the directory structure, so you have to have something like this:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@nx-issue/common/react-ui": [
        "libs/common/react-ui/src/index.ts"
      ],
      "@nx-issue/idea": [
        "libs/idea/src/index.ts"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "tmp"
  ]
}
```

With this tsconfig the graph will be computed correctly. We should update our algorithm to error when a mismatch is detected.

**Comment by zachnewburgh** [comment] 2019-06-11 17:30
@vsavkin Thanks for looking into this. Yes, but that's exactly what I was hoping to avoid. I was hoping to keep `@nx-issue/react-ui`, but map it to `libs/common/react-ui/src/index.ts`. Is there any way that that can be achieved?

**Comment by vsavkin** [comment] 2019-06-18 18:40
Unfortunately, currently it is not supported. We were thinking about using path mappings when resolving the dependency graph, which would have made this possible. We decided to delay this until we add support for bazel. Bazel generates the path mappings, so we want to make sure that whatever we do is bazel compatible.

**Comment by zachnewburgh** [comment] 2019-06-18 18:42
@vsavkin Good to know. Thanks for giving this a look!

**Closed** 2019-12-18 17:44 UTC
Labels: scope: core, type: feature

**Comment by JasonShin** [comment] 2022-07-14 22:48
If you are trying to import subdirectory of a module, please set an additional paths like following

```
"paths": {
      "@nx-issue/common/react-ui": [
        "libs/common/react-ui/src/index.ts"
      ],
     "@nx-issue/common/react-ui/*": [
        "libs/common/react-ui/src/*"
      ],
      "@nx-issue/idea": [
        "libs/idea/src/index.ts"
      ]
      "@nx-issue/idea/*": [
        "libs/idea/src/*"
      ]
    }
```
