### ISSUE TITLE
run-commands with nx command fails

### ISSUE THREAD

**Issue by rickvandermey** [nrwl/nx#5804] opened 2021-05-27 10:31 UTC
After updating from 12.0.8 to 12.3.4 the custom commands fail or doesnt return output.
Before the update it was working fine.

```
"build-ci": {
	"builder": "@nrwl/workspace:run-commands",
	"options": {
		"command": "nx build deals --configuration=$CONF --stats-json --ngsw-config-path=./ngsw-config.json"
	}
}
```

When we run the command `nx build deals --configuration=$CONF --stats-json --ngsw-config-path=./ngsw-config.json` from the cli it does work. When we run the command `CONF=uat nx run deals:build-ci` it doesnt generate any output:

```
nx run deals:build-ci 

> nx run deals:build:uat --statsJson --ngswConfigPath=./ngsw-config.json 
- Generating browser application bundles...

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build-ci" succeeded
```

When we change the command into NG instead of NX, we do get output.

```
"build-ci": {
	"builder": "@nrwl/workspace:run-commands",
	"options": {
		"command": "ng run deals:build --configuration=$CONF --stats-json --ngsw-config-path=./ngsw-config.json"
	}
},
```

This is the output:
```
nx run deals:build-ci 
- Generating browser application bundles...
✔ Browser application bundle generation complete.
- Copying assets...
✔ Copying assets complete.
- Generating index html...
✔ Index html generation complete.
- Generating service worker...
✔ Service worker generation complete.

Initial Chunk Files               | Names         |      Size
main.7e36e9388748d9ffae45.js      | main          | 425.59 kB
styles.52bfefb4fefa16c81a45.css   | styles        | 101.66 kB
polyfills.77bfd21324476b8dd94e.js | polyfills     |  64.91 kB
runtime.d95cbb82b613a0cd654e.js   | runtime       |   2.58 kB

| Initial Total | 594.74 kB

Lazy Chunk Files                  | Names         |      Size
32.617743c994ad5bfd850a.js        | -             |   7.68 kB

Build at: 2021-05-27T10:29:48.090Z - Hash: 47926c016bbd6ca271ce - Time: 26256ms

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build-ci" succeeded
```

It looks like NX isnt supported inside the builder `@nrwl/workspace:run-commands`

Report:
```
Node : 14.16.1
  OS   : darwin x64
  npm  : 7.12.0
  
  nx : Not Found
  @nrwl/angular : 12.3.4
  @nrwl/cli : 12.3.4
  @nrwl/cypress : 12.3.4
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : 12.3.4
  @nrwl/express : 12.3.4
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.4
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : 12.3.4
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
  ```

**Comment by leon** [comment] 2021-05-27 12:32
I have the same issue, but another use case.

We use firebase hosting for some things. I've added a custom deploy script to handle the firebase deploy.

```
"deploy": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      "nx run app:build:dev",
      "firebase deploy --project dev --only hosting:app"
    ],
    "parallel": false
  },
  "configurations": {
    "production": {
      "commands": [
        "nx run app:build:production",
        "firebase deploy --project prod --only hosting:app"
      ]
    }
  }
}
```

This has been working fine the last 6 months atleast.

We updated to angular 12 and nx 12.3 a couple of days ago and now our deploys are not working.

I'm getting this from the build

```
> nx run app:deploy 

> nx run app:build:dev 
- Generating browser application bundles...

=== Deploying to 'mysite-dev'...

i  deploying hosting

Error: Specified "public" directory "dist/apps/app" does not exist, can't deploy hosting to site "mysite-dev"
ERROR: Something went wrong in @nrwl/run-commands - Command failed: firebase deploy --project dev --only hosting:app

———————————————————————————————————————————————

>  NX   ERROR  Running target "app:deploy" failed

  Failed tasks:
  
  - app:deploy

```

It never outputs anything to the dist folder.


If i try running the build step alone
```
nx run app:build:dev 
```
the nx cloud kicks in and says

```
> nx run app:build:dev [existing outputs match the cache, left as is]
```
but the dist folder is still empty.

if I then run

```
nx run app:build:dev --skip-nx-cache
```

then it does a full build and outputs to the dist folder
and then if I run the deploy script it uses the nx cache and deploys.


## Workaround
use `--skip-nx-cache` and build first.

## Problem
it seems as if the run-commands is exiting early from the angular build, causing nx cloud to not output to dist, but think it has, and then it jumps to the firebase deploy, but since the dist folder is not there, it fails the whole thing.

**Comment by leosvelperez** [comment] 2021-05-27 12:37
Thanks for reporting this!

Could you please confirm what version of `@angular-devkit/build-angular` you have installed? If it's `12.0.1`, this is an existing issue and it's being tracked in https://github.com/nrwl/nx/issues/5729.

You can see in [this comment](https://github.com/nrwl/nx/issues/5729#issuecomment-848576765) a workaround until this gets properly fixed.

**Comment by rickvandermey** [comment] 2021-05-27 12:48
This is our version.
`@angular-devkit/build-angular: 12.0.1`

does this also means it affects the affected? because that's what hurting us the most right now.

**Comment by leon** [comment] 2021-05-27 12:49
I just updated to `"@angular-devkit/build-angular": "12.0.2"` but the problem is still present.

But as you wrote in #5729 we can downgrade and wait for a fix.

**Comment by leosvelperez** [comment] 2021-05-27 14:37
I'll close this one as it's a duplicate of #5729. Please follow that issue for updates.

**Closed by leosvelperez** 2021-05-27 14:37 UTC
Labels: type: bug

**Comment by tmtron** [comment] 2022-07-13 15:07
In my case I got this error when I followed the current [nx-docs](https://nx.dev/executors/run-commands-builder#2.-update-)
```json
{
  "executor": "nx:run-commands"
}
```
The solution is to change the execturo:
```json
{
  "executor": "@nrwl/workspace:run-commands"
}
```

**Comment by david-gonzalez-pnw** [comment] 2023-02-03 16:57
> In my case I got this error when I followed the current [nx-docs](https://nx.dev/executors/run-commands-builder#2.-update-)
> 
> ```json
> {
>   "executor": "nx:run-commands"
> }
> ```
> 
> The solution is to change the executor:
> 
> ```json
> {
>   "executor": "@nrwl/workspace:run-commands"
> }
> ```

For others that find this post, be warned that making this change might cause issues
```
@nrwl/workspace:run-commands is deprecated and will be removed in Nx 16. Please switch to nx:run-commands
```
