### ISSUE TITLE
@nrwl/angular - Missing customWebpackConfig with multiple configurations

### ISSUE THREAD

**Issue by jsaldanaperez** [nrwl/nx#9245] opened 2022-03-09 10:33 UTC
## Current Behavior
Currently I have a host app generated with the `--mfe` and `--mfeType=host` flags.
When adding a second configuration to the `build` target in `project.json` and then using them both in the `serve` target (`"browserTarget": "shell:build:development,custom"`), results in the following error:
`Cannot read properties of undefined (reading 'customWebpackConfig')`

## Expected Behavior
That both configurations are being ran.

## Steps to Reproduce
[Reproduction repo](https://github.com/jsaldanaperez/nx-extra-config-issue)

Let's assume the following `project.json` (note that several lines have been omitted for brevity):
```json
{
  "targets": {
    "build": {
      "executor": "@nrwl/angular:webpack-browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "customWebpackConfig": {
          "path": "apps/shell/webpack.config.js"
        }
      },
      "configurations": {
        "development": {
          "buildOptimizer": false,
          "optimization": false
        },
        "custom": {
          "extractLicenses": false
        }
      }
    },
    "serve": {
      "executor": "@nrwl/angular:webpack-server",
      "configurations": {
        "production": {
          "browserTarget": "shell:build:production"
        },
        "development": {
          "browserTarget": "shell:build:development,custom"
        }
      },
    }
  }
}
```

### Failure Logs
`nx serve`:
```
nx run shell:serve:development

Cannot read properties of undefined (reading 'customWebpackConfig')

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target "shell:serve" failed

   Failed tasks:
   
   - shell:serve:development
```

### Environment
```
   Node : 16.14.0
   OS   : win32 x64
   npm  : 8.5.1

  AND

   Node : 17.2.0
   OS   : darwin x64
   npm  : 8.5.3
   
   nx : 13.8.5
   @nrwl/angular : 13.8.5
   @nrwl/cli : 13.8.5
   @nrwl/cypress : 13.8.5
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.5
   @nrwl/eslint-plugin-nx : 13.8.5
   @nrwl/express : undefined
   @nrwl/jest : 13.8.5
   @nrwl/js : undefined
   @nrwl/linter : 13.8.5
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.5
   @nrwl/tao : 13.8.5
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.5
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular-architects/module-federation: 14.1.1
         @angular/animations: 13.2.5
         @angular/common: 13.2.5
         @angular/compiler: 13.2.5
         @angular/core: 13.2.5
         @angular/forms: 13.2.5
         @angular/platform-browser: 13.2.5
         @angular/platform-browser-dynamic: 13.2.5
         @angular/router: 13.2.5
         @angular-devkit/build-angular: 13.2.5
         @angular/cli: 13.2.5
         @angular/compiler-cli: 13.2.5
         @angular/language-service: 13.2.5
```

**Comment by FrozenPandaz** [comment] 2022-03-10 17:03
This is a duplicate of https://github.com/nrwl/nx/issues/2839

We're not sure if we want to support the combination of `configurations` via `config1,config2`. Please discuss on that thread.

**Closed by FrozenPandaz** 2022-03-10 17:03 UTC
Labels: type: bug
