### ISSUE TITLE
hostReportError.js,You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by tarangsachdev92** [nrwl/nx#2018] opened 2019-11-01 13:15 UTC
## Expected Behavior
Unit test should run without any error
I am following this tutorial
https://nx.dev/react/tutorial/02-add-e2e-test 
and it on run of `nx e2e todos-e2e --watch` should open up the browser with button run all specs
## Current Behavior
 `nx e2e todos-e2e --watch` gave me error

` /my-work-space/node_modules/rxjs/internal/util/hostReportError.js:4` 
`TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

## Failure Information (for bugs)

I have followed steps which are mentioned [here](https://nx.dev/react/tutorial/02-add-e2e-test) 
### Context

Please provide any relevant information about your setup:

 Nrwl : 8.7.0
 @nrwl/react : 8.7.0
 @nrwl/cypress : 8.7.0

## Other

this is my github repo
[Github Repo](https://github.com/tarangsachdev92/nrwl-nx-react-fullstack)

**Comment by brandonroberts** [comment] 2019-11-11 14:49
Closing as a duplicate of #2013, see https://github.com/nrwl/nx/issues/2013#issuecomment-551070792 for context. We are looking into solutions for the issue.

**Closed by brandonroberts** 2019-11-11 14:49 UTC
