### ISSUE TITLE
Cypress builder ignores baseUrl

### ISSUE THREAD

**Issue by ZachJW34** [nrwl/nx#3082] opened 2020-05-27 15:21 UTC
## Expected Behavior

Nx's Cypress builder should respect `baseUrl` passed in via command line/workspace.json

## Current Behavior

If `devServerTarget` is specified, the `baseUrl` outputted by the server builder is used and the inputted `baseUrl` value is ignored.

### Steps to Reproduce

1. npx create-nx-workspace@latest repro-workspace -> empty -> nx cli
2. cd repro-workspace
3. yarn add @nrwl/angular
4. nx g @nrwl/angular:app shell --routing
5. nx g @nrwl/angular:module sub-app --routing --route sub-app --module app.module.ts --project shell
6. nx e2e shell-e2e --baseUrl http://localhost:4200/sub-app

Cypress _should_ navigate to http://localhost:4200/sub-app and the sub-app component should render.

### Other

I'm guessing the options `devServerTarget` and `baseUrl` are mutually exclusive? I've got a use case to use both, and I'd be willing to submit a PR if the expected behavior is desired.

**Comment by FrozenPandaz** [comment] 2020-05-29 18:59
Hi, this is a duplicate of this issue: https://github.com/nrwl/nx/issues/1614

We'd welcome a PR to fix the issue :wink: from the community.

**Closed by FrozenPandaz** 2020-05-29 18:59 UTC
