### ISSUE TITLE
Nx Workspace Migration (9 -> 10) fails for projects created with `--cli=nx` (Proof inside)

### ISSUE THREAD

**Issue by georgiee** [nrwl/nx#3496] opened 2020-08-11 08:47 UTC
## Current Behavior
We have a project based on Nx v9 and using the Nx style CLI (`create-nx-workspace --cli=nx [....]` ). Running the migration will fail at many place. I provided a first comment on the underlying issue here https://github.com/nrwl/nx/issues/3464#issuecomment-669012951 and decided to raise a proper issue.

After migrations have been prepared and installed I run `yarn nx migrate --run-migrations=migrations.json` and it fails at the first `@angular/core` migration `@angular/core:migration-v10-missing-injectable`.

```
Running migration @angular/core:migration-v10-missing-injectable
Could not find any tsconfig file. Cannot add the "@Injectable" decorator to providers which don't have that decorator set.
```
Removing it will get me to the next core migration where it fails.

## Expected Behavior
All migrations should run through on a project I created with `create-nx-workspace`.

## Steps to Reproduce
I have an unrelated example repo for some other Nx issue which is based on Nx v9 too. I prepared the migrations, installed the packages and run the migrations. Try it yourself. I created a branch with all migrations ready to run:

```
git clone https://github.com/georgiee/nx-debug-nested-dep-graph
git checkout upgrade-nx-base
yarn install
yarn nx migrate --run-migrations=migrations.json
```

This should be perfectly reproducible. Here is the fixed branch where the migrations will run through

```
git clone https://github.com/georgiee/nx-debug-nested-dep-graph
git checkout upgrade-nx-base-fixed
yarn install
yarn nx migrate --run-migrations=migrations.json
```

Changes to fix it are simple:
1. Rename `workspace.json` to `angular.json`
2. Install angular cli to `yarn add @angular/cli`. It's not installed by default by `create-nx-workspace` (or it was fixed at some point of time? Then I think a migration might be missing? )

My conclusion: 
+ The `nx` CLI Integration fails to install Angular CLI
+ The workspace.json vs angular.json lefts me clueless. Should I rename it to angular.json by default? Is this part of the Nx CLI Integration or why was it named `workspace.json` in the first place? Can I safely rename it?

### Environment
That's where  I started with the upgrade process:

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.2.2
  @nrwl/cli : 9.2.2
  @nrwl/cypress : 9.2.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.2.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.2.2
  typescript : 3.8.3
```

**Comment by brandonroberts** [comment] 2020-08-14 13:07
This is a duplicate of https://github.com/nrwl/nx/issues/3464. Let's track there with this for reference

**Closed by brandonroberts** 2020-08-14 13:07 UTC
Labels: scope: angular, type: bug
