### ISSUE TITLE
eslint convert-to-inferred stopped working in 19.3

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#26775] opened 2024-07-01 09:07 UTC
### Current Behavior

when I try to run `nx g convert-to-inferred` it throw an error

### Expected Behavior

running it to work

### Steps to Reproduce

1. create a project using 19.1
2. update to 19.3 using `nx migrate latest`
3. run `nx g convert-to-inferred` and choose eslint

### Nx Report

```shell
Node   : 20.12.2
OS     : win32-x64
npm    : 10.5.0

nx (global)        : 19.1.1
nx                 : 19.3.2
@nx/js             : 19.3.2
@nx/jest           : 19.3.2
@nx/linter         : 19.3.2
@nx/eslint         : 19.3.2
@nx/workspace      : 19.3.2
@nx/angular        : 19.3.2
@nx/cypress        : 19.3.2
@nx/devkit         : 19.3.2
@nx/eslint-plugin  : 19.3.2
@nrwl/tao          : 19.3.2
@nx/web            : 19.3.2
@nx/webpack        : 19.3.2
typescript         : 5.4.5
```

### Failure Logs

```shell
nx g convert-to-inferred
 NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed
√ Which generator would you like to use? · @nx/eslint:convert-to-inferred

 NX  Generating @nx/eslint:convert-to-inferred


 NX   The nx plugin did not find a project inside libs/auth. File an issue at https://github.com/nrwl/nx with information about your project structure.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

it was working in 19.1, reverting this commit does make it work, nothing was updated in the upgrade other than `.nx/workspace-data` being ignored in git and prettier

**Comment by leosvelperez** [comment] 2024-07-19 13:26
This issue was fixed by https://github.com/nrwl/nx/pull/26638. Please update to Nx 19.4.4 or 19.5.0 or later. After migrating you might need to run `nx reset` to prevent pulling from a stale tasks cache.

**Comment by robertIsaac** [comment] 2024-07-19 16:11
hi @leosvelperez 
the issue still exists

**Comment by robertIsaac** [comment] 2024-07-19 16:13
Node   : 20.12.2
OS     : win32-x64
npm    : 10.5.0

nx (global)        : 19.5.1
nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin

**Comment by robertIsaac** [comment] 2024-07-19 23:00
even in a newly created angular application using nx it doesn't work
here is how I created it
```
npx create-nx-workspace@latest test-reprod
Need to install the following packages:
create-nx-workspace@19.5.1
Ok to proceed? (y) y


 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Which stack do you want to use? · angular
√ Integrated monorepo, or standalone project? · standalone
√ Which bundler would you like to use? · esbuild
√ Default stylesheet format · css
√ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
√ Test runner to use for end to end (E2E) tests · none
√ Which CI provider would you like to use? · skip
√ Would you like remote caching to make your build faster? · skip

 NX   Creating your v19.5.1 workspace.

✔ Installing dependencies with npm
✔ Successfully created the workspace: test-reprod.
```

here is how it stop working
```
F:\test-reprod git:[master]
nx lint

> nx run test-reprod:lint

Linting "test-reprod"...
✔ All files pass linting

———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 NX   Successfully ran target lint for project test-reprod (955ms)

F:\test-reprod git:[master]
nx g convert-to-inferred
√ Which generator would you like to use? · @nx/eslint:convert-to-inferred

 NX  Generating @nx/eslint:convert-to-inferred

UPDATE project.json
UPDATE nx.json
F:\test-reprod git:[master]
nx lint

 NX   Cannot find configuration for task test-reprod:lint
```

please reopen the issue @leosvelperez

**Comment by leosvelperez** [comment] 2024-07-22 10:02
@robertIsaac thanks for the detailed reproduction steps. The issue only occurs for standalone workspaces, which the original reproduction steps didn't mention. I've identified the issue now and I'll push a fix for it.

**Comment by robertIsaac** [comment] 2024-07-22 10:18
Thanks for the update 
I wasn't sure what was the root cause

**Comment by leosvelperez** [comment] 2024-07-22 10:23
No worries! Sometimes it's hard to know which little detail might cause an issue. This is why we detailed reproduction steps are so important to help us reproduce the issues. TBF, you always provide good information, so keep it up!

There was an issue for Windows and ESLint matching your original description that was addressed in the PR I linked before. That's why I thought it was already addressed.

**Closed** 2024-07-22 14:03 UTC
Labels: type: bug, scope: linter

**Comment by robertIsaac** [comment] 2024-07-25 06:22
Hi @leosvelperez 
The fix works, thank you so much 
I have another issue with inferred for jest
Do I need to file another issue for it?

**Comment by leosvelperez** [comment] 2024-07-25 06:42
@robertIsaac are the reproduction steps similar to the one you provided in https://github.com/nrwl/nx/issues/26775#issuecomment-2240524427? Either way, yes, go ahead and create a new issue. You can ping me and I'll take a look.

**Comment by leosvelperez** [comment] 2024-07-25 08:08
I can't reproduce any issue with the `@nx/jest:convert-to-inferred` using the same reproduction steps.

FWIW, the fix for ESLint should have addressed it for other plugins as well. The root cause of the issue was in a shared utility we use in all the `convert-to-inferred` generators. So, if there's an issue with the Jest one should be something else.

**Comment by robertIsaac** [comment] 2024-07-25 14:17
when I'm trying to make a reprod, it actually does work
I'm not sure why it's not working in my project
what I noticed is that the failed suits are more than what should be tested, so I guess it's trying to test all of the files in the project not the files related only to each project
