### ISSUE TITLE
JavaScript heap out of memory: --max_old_space_size not working with nx in my nextjs application

### ISSUE THREAD

**Issue by sumit-pandey** [nrwl/nx#6786] opened 2021-08-20 11:15 UTC

**Comment by amanintech** [comment] 2021-08-20 12:03
This issue related with https://github.com/nrwl/nx/issues/1110 and is apparently fixed in its angular counter part.
But we tried using it with Next and it still has the same issues.

Tried permutations of  -
1. Limiting the number of workers  `maxWorkers`
2. using the `memoryLimit`
3. Running only one app build / serially 
4. increasing the  `--max-old-space-size=8192`

**Comment by kirjai** [comment] 2021-09-03 12:57
unfortunately, there isn't enough information to action this issue at the moment, since this issue doesn't use the issue template. so please open a new issue with a proper description. *most importantly - include steps to reproduce the issue please*

**Closed by kirjai** 2021-09-03 12:57 UTC
Labels: type: bug, scope: nextjs
