### ISSUE TITLE
Not able to run react-native project for workspace 11.1.4

### ISSUE THREAD

**Issue by akhilvasudev-kiwi** [nrwl/nx#4735] opened 2021-02-08 13:06 UTC
## Current Behavior
Running React native app using  nx run-ios gives error on simulator

## Expected Behavior
Should run the app on IOS simulator - 

## Steps to Reproduce
npx create-nx-workspace@11.1.4 workspace --preset=empty 
npm  install --save-dev @nrwl/react-native
npx nx g @nrwl/react-native:app awesome-app
npx nx run-ios awesome-app

### Failure Logs
error: Error: Unable to resolve module ./LogBoxImages/close.png from Desktop/exapmles/nx latest/workspace/node_modules/react-native/Libraries/LogBox/UI/LogBoxNotification.js: ./LogBoxImages/close.png could not be found within the project.

### Environment
@nrwl/workspace - 11.1.4
@nrwl/react-native - 11.0.2

![Simulator Screen Shot - iPhone 8 - 2021-02-08 at 18 33 49](https://user-images.githubusercontent.com/31406608/107223441-371a8900-6a3c-11eb-83ec-139807666533.png)

**Comment by hanselabreu** [comment] 2021-02-09 15:58
This is happening to me as well.

I ran `nx migrate 11.2.9` to upgrade NX to the version `11.2.9` but now I am getting the following error:

![image](https://user-images.githubusercontent.com/27902567/107389913-32e67e00-6ac5-11eb-8ddf-c55445e93a07.png)

This [issue](https://github.com/nrwl/nx/issues/4656) seems like something similar and they suggest that `@nrwl/cli` might not be updated when running a migration, but I can confirm that's not my case, this is my `package.json`:

![image](https://user-images.githubusercontent.com/27902567/107390375-a2f50400-6ac5-11eb-93b1-44a01a141403.png)

**Comment by vsavkin** [comment] 2021-02-09 17:39
Duplicate of https://github.com/nrwl/nx/issues/4736

Thank you!

**Closed by vsavkin** 2021-02-09 17:39 UTC
Labels: scope: react, type: bug
