### ISSUE TITLE
nx graph not showing app <=> lib dependencies lines

### ISSUE THREAD

**Issue by urielzen** [nrwl/nx#18094] opened 2023-07-12 20:08 UTC
### Current Behavior

This is a follow up from the previous issue I had opened.

https://github.com/nrwl/nx/issues/17664

But this time I was able to create a repository that appears to have the issue consistently. Since I have tested it in different computers.

When running `nx graph`, the graphs shows like this:
![image](https://github.com/nrwl/nx/assets/7947179/7a339f06-07e7-4c24-9318-7b8af0f3025e)

### Expected Behavior

It used to show lines between projects and libraries to show the dependencies between them.

![image](https://github.com/nrwl/nx/assets/7947179/c264c385-36ce-4e58-a3b9-013abffa8b43)

### GitHub Repo

https://github.com/urielzen/nxgraphissue2

### Steps to Reproduce

`npx nx graph`

### Nx Report

```shell
Node   : 20.4.0
   OS     : win32-x64
   npm    : 9.8.0

   nx                 : 16.5.1
   @nx/js             : 16.5.1
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/angular        : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.5.1
   @nx/webpack        : 16.5.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/component-store            : 16.0.1
   @ngrx/store                      : 16.0.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

Please note that if I run this in github codespaces, it works for some reason. The only difference that I can see if I compare the reports, is that I am in windows and the codespace is in linux.

```
Node   : 20.3.0
   OS     : linux-x64
   npm    : 9.6.7
   
   nx                 : 16.5.1
   @nx/js             : 16.5.1
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/angular        : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.5.1
   @nx/webpack        : 16.5.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.13.0
   @ngrx/component-store            : 16.0.1
   @ngrx/store                      : 16.0.1
```

**Comment by urielzen** [comment] 2023-07-13 08:57
I found the cause that clearly is responsible for this... at least in my PC.

Originally my repo is in a folder like this:
![image](https://github.com/nrwl/nx/assets/7947179/68214f43-f292-4a59-86f3-86a9be6a23dd)

Note that in my `git` root folder I have an `nx` folder and a `api` folder. And in the `nx` folder is where I have the nx workspace.
In the `api` folder I have a backend project, but it does not seem to be affecting anything negatively.

With this folder setup described above. I get the **_incorrect_** `nx graph`.

But if I move the entire workspace to the *git* repo root folder, then the `nx graph` shows correctly.
![image](https://github.com/nrwl/nx/assets/7947179/7290da9b-00ec-40c1-b48f-5f20fefdec6c)

**Comment by urielzen** [comment] 2023-07-13 09:18
I can confirm that the relative location of the `.git` folder in reference to the workspace is the cause of the issue.

To reiterate, this is the folder structure that gives the incorrect nx graph.
![image](https://github.com/nrwl/nx/assets/7947179/4e2416f8-610d-4810-bc9d-9b3f4b79c57b)

And if I just delete the `.git` folder from there. Then delete the  `.cache/nx` from `node_modules` and recreate the graph. That also `fixes` the problem. But now I don't have a git repo :stuck_out_tongue_winking_eye:

Hopefully this information helps in any way.
Thanks!

**Comment by tt-Hars** [comment] 2023-07-13 11:23
In my case I did `nx init` and it downgraded the nx version from v16.4.0 to v16.2.1. The dependencies started to show up correctly.

**Comment by hewelt** [comment] 2023-08-22 18:42
Maybe it will help somebody:

```json
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": true
    }
  },
```

for me the problem was that the value was `false` if not specified, even though the docs state it's `true` by default (we don't have Lerna installed).

**Comment by urielzen** [comment] 2023-09-10 20:40
@hewelt Thanks for the suggestion, it did not work for my case.
Do you also have your nx workspace nested in a subfolder or is it in your git root folder?

**Comment by AgentEnder** [comment] 2023-10-23 15:36
Hey @urielzen 👋 

I've spent some time looking in to this and want to confer my findings:

The error appears to be related to the gitignore in the workspace root which ignores everything and then attempts to add things back in. Nx doesn't always handle that very well and I confirmed that on 16.5.0 (the version in the repro), commenting out that line in the gitignore fixes the problem. Additionally, on updating the repo to v17, without commenting out that line, your projects disappeared. 

I'd recommend removing that line from the gitignore, and specifically ignoring things which shouldn't be tracked by git. 

I'm going to close this out now, thanks for the report.

**Closed by AgentEnder** 2023-10-23 15:36 UTC
Labels: type: bug, scope: core, os: windows

**Comment by urielzen** [comment] 2023-10-24 06:53
@AgentEnder Thanks for the insight. I had found a different work around that also fixes the problem.... basically I just add an additional `.git` folder inside the `nx` (worspace) folder. This seems to trick Nx into thinking that `nx` folder is the git root and everything works correctly from there.
