### ISSUE TITLE
npx nx-ignore <app> not working on Vercel Build

### ISSUE THREAD

**Issue by NZaleski** [nrwl/nx#10642] opened 2022-06-08 20:28 UTC
## Current Behavior

I make a change to the `order-controller` app in our nx environment.  I can then run local commands `npx nx-ignore order-controller` and it returns  " ✅ - Build can proceed since order-controller is affected "

I commit my code to BitBucket and then Vercel starts to automatically build.  I added in `npx nx-ignore order-controller` command in the Vercel settings.  However, when this script is triggered in the Vercel build it skips over it and says "The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting."

The same is true if I try to use the shell script in the ignore build command. https://github.com/nrwl/nx/discussions/8448

## Expected Behavior

I expect it to build because that app was affected as I could see that it was affected locally.  I can also run `npx nx affected:apps --plain --base HEAD~1 --head HEAD` and that returns `order-controller`

## Steps to Reproduce

1. Create nx monorepo
3. Create two projects one `order-controller` and the other `dealer-portal`
4. Create Bitbucket Repo
5. Create Vercel Backend and link up Bitbucket for automatic builds
6. Add in `npx nx-ignore order-controller` 
7. Make a change in the `order-controller` app, commit changes locally
8. Test locally `nx affected:apps --plain --base HEAD~1 --head HEAD` to ensure `order-controller` has changed. Alternatively, you install `nx-ignore` and run `npx nx-ignore order-controller`. It should return that there are edits
9. Push to remote and check the logs.  When Vercel runs `npx nx-ignore order-controller` it cancels the deployment because it says the app was not affected

If nothing jumps out I can create a minimal Bitbucket repo. 

### Environment

```
Node : 16.15.0
   OS   : darwin x64
   pnpm : 7.1.3
   
   nx : 14.1.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : 14.1.5
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.8
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 14.1.5
   @nrwl/workspace : 14.1.5
   typescript : 4.4.4
   rxjs : Not Found
```

**Comment by Aiden-recovery** [comment] 2022-06-09 03:17
i faced same problem
if i run nx affected:apps on local development environmemt i can get affected app name i expected
but when it is building on vercel i got this message
🛑 - Build cancelled since zaza is not affected

**Comment by NZaleski** [comment] 2022-06-09 20:38
I wonder if it is something as simple as my nx cloud isn't connected to Vercel correctly?

**Comment by jaysoo** [comment] 2022-06-10 12:30
@NZaleski No, Nx Cloud  isn't needed  for this functionality. I'm taking a look at this today. Seems weird if it's specific to BitBucket since the only thing that matters is the previous git SHA (`HEAD^`) vs current SHA (`HEAD)`.

**Comment by jaysoo** [comment] 2022-06-10 13:42
@NZaleski Can you create a repro for this?

I tried it with BitBucket and Vercel, and it seems to be working for me.

https://vercel.com/jackhsu/issue-10642/JBK2beJfbh65z6KGY8WbyMQ7x6La

<img width="1063" alt="Screen Shot 2022-06-10 at 9 41 48 AM" src="https://user-images.githubusercontent.com/53559/173078617-4cc8512b-3f39-44f9-9098-1cb08debf685.png">

Also, I just released a new version of `nx-ignore` that takes `--verbose` option, can you try that? The logged info may help with debugging.

**Comment by nzaleski-kcd** [comment] 2022-06-10 19:34
@jaysoo well, it seems to be working now.  No idea what the problem was.  I have had a lot of moving pieces with migrating to nx.  

You `--verbose` flag you added is helpful.  That is what I was trying to see is the affected app on the Vercel build. 

Thanks again

**Comment by jaysoo** [comment] 2022-06-13 16:41
Great! I'll close this issue then. Re-open if you run into further issues.

**Closed by jaysoo** 2022-06-13 16:41 UTC
Labels: type: bug, blocked: repro needed, scope: misc

**Comment by seloner** [comment] 2022-06-24 15:45
I am facing the same issue.
I am using vercel too .

Remote

Cloning completed: 1.815s
--
18:42:42.702 | Running "npx nx-ignore hotel --verbose"
18:42:52.115 | ≫ Using Nx to determine if this project (hotel) is affected by the commit...
18:42:52.307 |  
18:42:52.307 | ≫ Comparing HEAD^...HEAD
18:42:52.308 |  
18:42:53.608 | ≫ Affected projects:
18:42:53.608 | -
18:42:53.608 |  
18:42:53.609 | 🛑 - Build cancelled since hotel is not affected
18:42:53.930 | The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting.

Local:
≫ Using Nx to determine if this project (hotel) is affected by the commit...

≫ Comparing HEAD^...HEAD

≫ Affected projects:
  - hotel

**Comment by NZaleski** [comment] 2022-06-24 15:56
One thing I think that I did that was wonky is when I would just update the root project, and expect all apps to get rebuilt, but I think what happens is it doesn't actually get rebuilt until I make an actual code change in that app.  

Maybe that is a problem you, or someone else, are/is facing

**Comment by seloner** [comment] 2022-06-24 16:01
I have a vercel.json file inside the app folder because I want to do some url rewrites.
I am changing the file then commit and push .
Vercel is canceling the deploy .
Maybe the issue is that the vercel.json is outside of source folder ? 
I dont think so because when using the command local it is working fine .
The issue is when is running on vercel.

**Comment by Yuripetusko** [comment] 2022-11-23 12:19
`npx nx-ignore <app-name>` did not detect a change to `yarn.lock` for me on Vercel
