### ISSUE TITLE
NX-application not loading in safari browser

### ISSUE THREAD

**Issue by bhargav1010** [nrwl/nx#16143] opened 2023-04-06 07:17 UTC
### Current Behavior

Hello Everyone,
Actually i'm facing an issue that my NX angular application is not opening in safari browser
Angular version : 13.3.3
Safari browser version : 16.4
Nx version 14.4.3
Java script also enabled in safari browser.
Network tab and everything working good.

### Expected Behavior

NX-application has to be open properly in safari browser

### Steps to Reproduce

After creating NX-application in angular framework

### Nx Report

```shell
A porblem repeatedly occurred with lcoalhost
```

### Failure Logs

```shell
Facing only two console errors:
Error: Shared Module is not available for eager consumption - polyfills.js.
SyntaxError: import.meta is only valid inside modules. - styles.js
```

### Additional Information

It is working in all other browsers like chrome,opera and firefox.

**Comment by leosvelperez** [comment] 2023-04-11 10:52
Thanks for reporting this!

This error "Error: Shared Module is not available for eager consumption - polyfills.js." indicates an issue with a Module Federation setup. The provided reproduction steps are scarce and don't seem to reflect the state of the workspace.

Please provide a repo where the issue can be reproduced so we can further troubleshoot it.

**Comment by leosvelperez** [comment] 2023-04-19 09:36
I'm closing this issue since it seems to be a runtime issue possibly caused by a misconfiguration. If you have further details that point to an issue with Nx, please feel free to leave a comment or open a new issue.

**Closed by leosvelperez** 2023-04-19 09:36 UTC
Labels: type: bug, blocked: repro needed, scope: angular
