### ISSUE TITLE
CLI commands fail when npm dependncy has the same name as a local namespaced library

### ISSUE THREAD

**Issue by YonatanKra** [nrwl/nx#3044] opened 2020-05-21 07:04 UTC
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When running a cli command to a lib with I've created for a certain namespace, it should perform that requested task, even though there's an npm dependncy with the same name (and different namespace).

## Current Behavior

The local library is replaced in the graph by the npm library - hence, when reaching the build/test phase, the type of the is set to npm and there's no `architect` property.

## Failure Information (for bugs)

```
TypeError: Cannot read property 'test' of undefined
at getOutputsForTargetAndConfiguration (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:44:42)
    at Object.getOutputs (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:40:12)
    at TaskOrchestrator.forkProcess (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:120:37)
    at takeFromQueue (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:48:26)
    at TaskOrchestrator.<anonymous> (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:69:27)
    at Generator.next (<anonymous>)
    at /Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:4:12)
    at TaskOrchestrator.runRest (/Users/yonatan.kr/Code/insights/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:40:16)
```

### Steps to Reproduce

1. Create a new project with some namespace
2. `yarn add presto-client`
3. Create a new library called `presto-client` (make sure it's setup in the namespace of the project)
4. Try to run: `nx test presto-client` or `nx build presto-client`
5. The error appears.

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)

 @nrwl/angular : Not Found
  @nrwl/cli : 9.2.3
  @nrwl/cypress : 9.2.3
  @nrwl/eslint-plugin-nx : 9.2.3
  @nrwl/express : 9.2.3
  @nrwl/jest : 9.2.3
  @nrwl/linter : 9.2.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 9.2.3
  @nrwl/react : 9.2.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.2.3
  @nrwl/web : 9.2.3
  @nrwl/workspace : 9.2.3
  typescript : 3.8.3

**Comment by YonatanKra** [comment] 2020-05-21 07:08
I believe I'll have time to write a fix next week but need to decide on the fix (either we prevent installing same-name libs/deps or use the namespace in the dep graph or anything else).

**Comment by FrozenPandaz** [comment] 2020-05-21 14:56
Closing this issue as a duplicate of https://github.com/nrwl/nx/issues/2396 which there is a PR #2997 to fix.

**Closed by FrozenPandaz** 2020-05-21 14:56 UTC
