### ISSUE TITLE
lockfile generation regression in 17.0.2 (from 16.10.0)

### ISSUE THREAD

**Issue by vicb** [nrwl/nx#20027] opened 2023-11-03 08:54 UTC
### Current Behavior

Error when trying to deploy my project:

```
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @types/geojson@7946.0.12 from lock file
```

### Expected Behavior

`@types/geojson@7946.0.12 from lock file` should be in the lock file

### GitHub Repo

https://github.com/vicb/flyxc

### Steps to Reproduce

1. `nx build fxc-server`
2. `npm ci` in `dist/apps/fxc-server`

### Nx Report

```shell
Node   : 20.9.0
   OS     : linux-x64
   npm    : 10.2.1
   
   nx (global)        : 17.0.2
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/express        : 17.0.2
   @nx/node           : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/vite           : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 5.1.0
```

### Failure Logs

```shell
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: @types/geojson@7946.0.12 from lock file
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This is a regression.

I already reported this bug in 
- https://github.com/nrwl/nx/issues/16047
- https://github.com/nrwl/nx/issues/15366

Thanks for having fixed this before but it looks like the same bug re-appeared.

**Comment by vicb** [comment] 2023-12-13 14:31
Any update on this issue.

I just updated to 17.2.3 and the issue still exists

**Comment by JamesHenry** [comment] 2024-05-17 19:40
Hi @vicb, I'm sorry for the delay in you receiving a response on this one.

I pulled down your repo and I am unable to reproduce with the latest Nx which is already in your repo (19.0.4).

Therefore I am going to close this one, please feel free to reopen if you have additional steps to reproduce.

P.S. It was a little fiddly to attempt the reproduction, I had to inspect your CI config to understand that I had to manually copy some TS files into place before running build. You may wish to consider wrapping that in an Nx target and then specifying it in the dependsOn of build.

**Closed by JamesHenry** 2024-05-17 19:40 UTC
Labels: type: bug, scope: js

**Comment by vicb** [comment] 2024-05-17 19:47
Yes, it seems to be working lately.

And yes, sorry for the file copy - it's a one time setup that I should move to a `.env` at some point...
