### ISSUE TITLE
 NX   (0 , next_1.default) is not a function

### ISSUE THREAD

**Issue by ab-etemadi** [nrwl/nx#17624] opened 2023-06-15 19:02 UTC
### Current Behavior

![image](https://github.com/nrwl/nx/assets/80175309/ea2632f0-cd70-4f3c-993f-cc362d65e647)

### Expected Behavior

I expect the Next.js app generated with `nx generate @nrwl/next:application` to run successfully.

### Steps to Reproduce

1.
create a next js app with these  Dependencies
```json 
    "@nrwl/cli": "15.2.1",
    "@nrwl/cypress": "15.2.1",
    "@nrwl/eslint-plugin-nx": "15.2.1",
    "@nrwl/jest": "15.2.1",
    "@nrwl/next": "15.2.1",
    "@nrwl/node": "15.2.1",
    "@nrwl/nx-cloud": "15.0.2",
    "@nrwl/react": "15.2.1",
    "@nrwl/web": "15.2.1",
    "@nrwl/workspace": "15.2.1",
    "@types/node": "16.11.7",
    "nx": "15.2.1",
    "typescript": "^5.1.3"
    "next": "^13.4.5",
    "next-language-detector": "^1.0.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
```

### Nx Report

```shell
{}
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by ndcunningham** [comment] 2023-06-15 19:57
Please update your dependencies to the latest version. This should solve your issue
dupe of: https://github.com/nrwl/nx/issues/16605

**Closed by ndcunningham** 2023-06-15 19:57 UTC
Labels: type: bug, scope: nextjs

**Comment by ab-etemadi** [comment] 2023-06-17 13:30
Thanks @ndcunningham
