### ISSUE TITLE
Nx reset required whenever changing project configuration files

### ISSUE THREAD

**Issue by Anyatsu** [nrwl/nx#26505] opened 2024-06-11 07:29 UTC
### Current Behavior

When modifying any project-related configuration file (project.json, next.config.js, etc.), nx fails to recognize the file, requiring an nx reset to run the project. This seems  to happen on any nx project regardless of how it was created

### Expected Behavior

Changing the configuration files shouldn't require running nx reset for the project to be useable again

### Steps to Reproduce

1. Change any configuration file

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.12.0
OS     : linux-x64
npm    : 10.5.0

nx                 : 19.2.3
@nx/js             : 19.2.3
@nx/jest           : 19.2.3
@nx/linter         : 19.2.3
@nx/eslint         : 19.2.3
@nx/workspace      : 19.2.3
@nx/devkit         : 19.2.3
@nx/eslint-plugin  : 19.2.3
@nx/next           : 19.2.3
@nx/react          : 19.2.3
@nrwl/tao          : 19.2.3
@nx/web            : 19.2.3
@nx/webpack        : 19.2.3
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
  ProjectsWithNoNameError: The projects in the following directories have no name provided:
    - apps/nx-turbo
      at validateAndNormalizeProjectRootMap (/home/yuval/projects/nx-turbo/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:449:15)
      at mergeCreateNodesResults (/home/yuval/projects/nx-turbo/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:325:9)
      at /home/yuval/projects/nx-turbo/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:266:85
      at async processFilesAndCreateAndSerializeProjectGraph (/home/yuval/projects/nx-turbo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:43)
      at async Timeout._onTimeout (/home/yuval/projects/nx-turbo/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:85:13)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Happens on WSL Fedora Remix 39.01

**Comment by Anyatsu** [comment] 2024-07-26 10:26
> How are you modifying the files? Is it in neovim by any chance?

Yes, I am using neovim. I tried doing the same things with vscode and it seems to be working properly. So looks like there's something about neovim that results in this problem...

**Comment by MaxKless** [comment] 2024-07-26 11:42
Ah that makes sense. It's a bug with the daemon and how it handles file updates. I'll close this as a duplicate of https://github.com/nrwl/nx/issues/20622, let's figure it out there :)

**Closed by MaxKless** 2024-07-26 11:42 UTC
Labels: type: bug, scope: core
