### ISSUE TITLE
Test failures in CI with shared cache (SyntaxError: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by minijus** [nrwl/nx#4472] opened 2021-01-08 15:52 UTC
## Current Behavior
The issue is similar to #4470, but occurs for `test` target instead of `lint`.

Using Jenkins as CI engine.
Using shared Nx cache directory (`/home/node/cache/nx`) in CI:
```bash
sed -i 's|./cache/nx|/home/node/cache/nx|' nx.json
```

With this setup running lint in distributed setup (very similar to one provided in [Nrwl example](https://github.com/nrwl/nx-jenkins-build)):
```bash
npx nx run-many --target=test --projects=redacted-projects-here --parallel
```

Getting same error on seemingly random projects. Failed projects change when re-running same CI jobs, but never fail when running without shared cache and never fail locally.

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJsonWithComments (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/utils/fileutils.js:44:17)
    at Object.readJsonFile (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/utils/fileutils.js:40:12)
    at Object.readCache (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/core/nx-deps/nx-deps-cache.js:36:67)
    at Object.createProjectGraph (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:13:232)
    at Object.<anonymous> (/home/jenkins/agent/workspace/redacted/node_modules/@nrwl/workspace/src/command-line/run-many.js:17:46)
    at Generator.next (<anonymous>)
    at fulfilled (/home/jenkins/agent/workspace/redacted/node_modules/tslib/tslib.js:111:62)
```

## Expected Behavior
It should be possible to set shared cache in CI environment without getting jobs failed.

## Steps to Reproduce
It might be difficult to recreate whole environment so the issue would be reproducible as it is not clear what causes it.
Please share any ideas what could be attempted to narrow down the root cause of this and I will give them a try.

### Failure Logs
See under "Current Behaviour".

### Environment
The report is from local development environment, but it is same Node.js version as on CI:
```
>  NX  Report complete - copy this into the issue template

  Node : 14.15.4
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.1
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : 11.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.1
  typescript : 4.0.3
```

**Comment by vsavkin** [comment] 2021-01-10 18:45
Hi there! Thank you for submitting the issue!

As you pointed out yourself, this is sort of a duplicate of 4470 (https://github.com/nrwl/nx/issues/4470). We can communicate in that issue in regards to both testing and linting, and I'm going to close this one. 

Thank you!

**Closed by vsavkin** 2021-01-10 18:45 UTC
Labels: type: bug

**Comment by minijus** [comment] 2021-01-11 07:30
> Hi there! Thank you for submitting the issue!
> 
> As you pointed out yourself, this is sort of a duplicate of 4470 (#4470). We can communicate in that issue in regards to both testing and linting, and I'm going to close this one.
> 
> Thank you!

Thanks! I've moved details for failed test runs to #4470.
