### ISSUE TITLE
Target `defaultConfiguration` should be passed to `dependsOn` targets

### ISSUE THREAD

**Issue by danielsharvey** [nrwl/nx#10868] opened 2022-06-23 14:24 UTC
## Current Behavior
I have an `update-config` target which is included using `dependsOn` as follows:
```json
"serve": {
  "dependsOn": [
    {
      "target": "update-config",
      "projects": "self"
    }
  ],
  ...
}
```

When called with an explicit configuration this is passed to the `update-config` target:
```sh
$ nx run dummy:serve:development

 >  NX   Running target serve for project dummy and 1 task(s) it depends on

> nx run dummy:update-config:development

> nx run dummy:serve:development

⠼ Generating browser application bundles (phase: building)...
```

When called without an explicit configuration this is **NOT** passed to the `update-config` target:
```sh
$ nx run dummy:serve

 >  NX   Running target serve for project dummy and 1 task(s) it depends on

> nx run dummy:update-config

> nx run dummy:serve:development

⠹ Generating browser application bundles (phase: building)...
```

## Expected Behavior

I expect that a call to `nx run dummy:serve` which utilises the `defaultConfiguration` of the `serve` target to also pass this configuration to the `dependsOn` targets.

## Steps to Reproduce

1. Clone the test repo: https://github.com/danielsharvey/nx-10868-dependson-test
2. Run `npm install`
3. Execute `nx run dummy:serve:development` and observe that the `development` configuration is passed to the `update-config` target.
4. Execute `nx run dummy:serve` and observe that the `development` configuration is **NOT** passed to the `update-config` target.

### Failure Logs
Not applicable.

### Environment
```sh
$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.12.1
   
   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.4
   ---------------------------------------
   Community plugins:
```

**Comment by danielsharvey** [comment] 2022-06-23 14:32
I'm happy to look at a PR, but would like confirmation on whether my expectation is correct.

**Comment by AgentEnder** [comment] 2022-06-23 16:25
I don't think this should be the expected behavior, since the defaultConfiguration for one project may not exist on its dependencies.

**Comment by danielsharvey** [comment] 2022-06-24 11:06
@AgentEnder Isn't that true for the case when the configuration _is_ specified? How is that different?

i.e. my example `nx run dummy:serve:development` passes the configuration through to the dependent target - should it not?

**Comment by AgentEnder** [comment] 2022-06-24 11:22
I can see how it could be confusing, but it feels like it makes sense that when manually specifying a configuration it's passed to all targets vs the default for each target being used otherwise.

I'm not sure on this, definitely wouldn't mind other options @FrozenPandaz

**Comment by danielsharvey** [comment] 2022-06-24 11:28
Fair, thanks. Perhaps, it could be an optional parameter when defining a default configuration? (whether it is propagated or not)

I am certainly liking the dependsOn feature - it has enabled me to remove multiple embedded `nx run ...` and rely on a single task graph.

**Comment by danielsharvey** [comment] 2022-09-14 00:50
Any updated thoughts on this @AgentEnder @FrozenPandaz?

**Comment by AadamZ5** [comment] 2022-12-24 20:25
Just ran into a similar issue. However, to solve this, I expected to be able to set the configuration using the familiar colon syntax in the `target` field. This doesn't work and silently fails.

```jsonc
"deploy": {
  "dependsOn": [{ "projects": "self", "target": "build:production" }]
  "executor": "nx:run-commands",
  "command": "some-deploy-script"
}
```

Just for clarification, the below will work, but builds the default configuration for the **build** target (usually _development_) when using shorthand `nx deploy my-app`
```jsonc
"deploy": {
  "dependsOn": [{ "projects": "self", "target": "build" }]
  "executor": "nx:run-commands",
  "command": "some-deploy-script"
}
```

Additionally, I tried to set configurations on this target, but that did not seem to propagate the `dependsOn` field. Notice in this example, the `dependsOn` target is just `"build"` (and I would like to specify `"build:production"`)
```jsonc
"deploy": {
  "defaultConfiguration": "production",
  "configurations": {
    "production": {
      "dependsOn": [{ "projects": "self", "target": "build" }] // Doesn't work in a target configuration
    },
    "development": {
    "dependsOn": [{ "projects": "self", "target": "build" }] // Maybe an extra field "configuration" could be added if
                                                             // implicit colon specification won't cut it?
    }
  },
  "executor": "nx:run-commands",
  "command": "some-deploy-script"
}
```

Not sure if this would address the original issue here, but putting it here nonetheless. 

### Version:
 - `"@nrwl/cli": "15.4.0"`
 - `"nx": "15.4.0"`
 - Other `@nrwl/*` packages at `15.4.0`

**Comment by AgentEnder** [comment] 2023-05-04 18:04
Hmmm, I still think this is the desired behavior. I'm going to close it out.

If you run with a specific configuration, it makes sense that everything would hit that. If you don't, it makes sense that everything would hit the respective defaults.

I think my general recommendation would be to have your build target's default to prod anyways, and specify the configuration to dev in your serve target's buildTarget option.

**Closed** 2023-05-04 18:04 UTC
Labels: type: bug, scope: core
