### ISSUE TITLE
Lib build fails after upgrade v12 => v13 (project_graph_1.createProjectGraph is not a function)

### ISSUE THREAD

**Issue by oco2000** [nrwl/nx#7898] opened 2021-11-26 09:01 UTC
## Current Behavior
Lib build fails

## Expected Behavior
Lib build passes

## Steps to Reproduce
Upgrade the existing project using standard migration procedure

### Failure Logs
```
> yarn nx build web-components
project_graph_1.createProjectGraph is not a function
```

### Environment
```
  Node : 14.17.0
  OS   : win32 x64
  yarn : 1.22.17

  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : 13.2.2
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.6
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/cli: 13.0.3
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/elements: 13.0.0
         @angular/forms: 13.0.0
         @angular/material: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @angular/service-worker: 13.0.0
         @ionic/angular: 5.9.1
         @ngneat/reactive-forms: 1.7.5
         @ngneat/transloco: 2.23.5
         @ngrx/component-store: 13.0.1
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @angular-builders/custom-webpack: 12.1.3
         @angular-devkit/build-angular: 13.0.3
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @ngneat/spectator: 8.3.2
         @ngrx/schematics: 13.0.1
         @ngrx/store-devtools: 13.0.1
         @nxext/stencil: 12.1.2
         @nxtend/capacitor: 11.1.1
         @nxtend/ionic-angular: 11.1.1
         @storybook/angular: 6.4.0-rc.3
         ng-mocks: 12.5.0
         nx-stylelint: 12.3.1
```

**Comment by leosvelperez** [comment] 2021-11-26 10:11
Thanks for reporting this!

The deprecated `createProjectGraph` function was removed in Nx v13. Therefore, no code within Nx invokes that function anymore. I see you are using several community plugins. Most likely one of those plugins you're using hasn't removed the usage of `createProjectGraph` and it's the cause of the issue.

Please check if there are updated versions of the plugins you're using, there might be updates for them already supporting the latest version of Nx.

If the problem persists, you can run `yarn nx build web-components --verbose` to see the stack trace of the error and locate which plugin is failing. Once identified, please open the issue on the plugin repository.

I'll close this since it seems an issue with a community plugin. Please feel free to reopen it if you think there's still an issue on Nx side.

**Closed by leosvelperez** 2021-11-26 10:11 UTC
Labels: type: bug

**Comment by oco2000** [comment] 2022-02-21 09:11
Thanks, it helped to locate the problem
