### ISSUE TITLE
Yargs processing mangles command line args passed into other tools

### ISSUE THREAD

**Issue by JakeGinnivan** [nrwl/nx#5710] opened 2021-05-19 08:53 UTC
## Description

Because NX parses the commands, then executes different commands it mangles the command line args for any plugins which wrap other CLI tools. By passing 

```
configuration: {
    "camel-case-expansion": false
}
```

To yargs in @nrwl/cli/lib/parse-run-one-options.js and possibly other places the NX cli becomes far more predicable

## Motivation

I have written a NX plugin which wraps the Pulumi CLI, which I would like to execute like this:

```
yarn nx up lambda-at-edge --yes --non-interactive  --stack lambda-at-edge.dev
```

Which is followed by: `nx run lambda-at-edge:up --yes --non-interactive --nonInteractive --stack=lambda-at-edge.dev`

Then:

```
Error: unknown flag: --nonInteractive
```

## Suggested Implementation

I'm on 12.0.8 and used patch-package to fix the issue for myself

``` patch
diff --git a/node_modules/@nrwl/cli/lib/parse-run-one-options.js b/node_modules/@nrwl/cli/lib/parse-run-one-options.js
index 67c1938..2d38f5d 100644
--- a/node_modules/@nrwl/cli/lib/parse-run-one-options.js
+++ b/node_modules/@nrwl/cli/lib/parse-run-one-options.js
@@ -63,6 +63,9 @@ function parseRunOneOptions(root, workspaceConfigJson, args) {
         alias: {
             c: 'configuration',
         },
+        configuration: {
+            "camel-case-expansion": false
+        }
     });
     if (parsedArgs['help']) {
         return false;
```

## Alternate Implementations

Open to suggestions

**Comment by FrozenPandaz** [comment] 2021-05-22 19:59
Please share your plugin so that we can reproduce the issue.

**Comment by JakeGinnivan** [comment] 2021-05-24 01:10
@FrozenPandaz plugin available at https://github.com/sevenwestmedia-labs/nx-plugins/tree/main/libs/pulumi

**Comment by JakeGinnivan** [comment] 2021-06-07 05:09
@FrozenPandaz just bumping this, have added the repro above

**Comment by JakeGinnivan** [comment] 2021-06-23 02:14
@FrozenPandaz sorry to keep bumping. Don't want this issue to go stale

**Comment by JakeGinnivan** [comment] 2021-06-23 02:15
@FrozenPandaz I can submit a pr if that would be handy?

**Comment by JakeGinnivan** [comment] 2021-07-12 02:25
Bumping again so issue doesn't go stale. 

FYI I am now doing this in my plugin to start working around the issue. It's a real pain :(

```
    // NX Mangles command line args. Let's fix them back.
    // https://github.com/nrwl/nx/issues/5710
    const pulumiArguments = process.argv.slice(4).map((args) => {
        if (args === '--disableIntegrityChecking') {
            return '--disable-integrity-checking'
        }
        if (args === '--nonInteractive') {
            return '--non-interactive'
        }
        if (args === '--targetDependents') {
            return '--target-dependents'
        }
        if (args === '--targetReplace') {
            return '--target-replace'
        }
        return args
    })
```

// @FrozenPandaz

**Comment by JakeGinnivan** [comment] 2021-07-28 23:20
Not stale

**Comment by kriswuollett** [comment] 2021-08-24 04:54
Not stale. I'd expect command line args to not be converted to camel case when using a library like `argparse` inside a target like:

```
        "execute": {
          "executor": "@nrwl/workspace:run-commands",
          "options": {
            "command": "node dist/apps/my_app/main.js"
          }
        },
```

**Comment by JakeGinnivan** [comment] 2021-09-25 02:22
Just a friendly bump to stop the issue going stale.

**Comment by kriswuollett** [comment] 2021-10-10 11:12
Not stale.

@FrozenPandaz here is a repo case so we can remove the `blocked: repo needed` label: https://github.com/kriswuollett/nx/tree/cli-args-mangled. Here is a summary of what I've found so far:

1. A single argument is being transformed as if it was a `boolean` argument, e.g., `-a` is mapped to `--a=true`.
2. Long form args that aren't joined with their value with an equals sign is forced into that format, e.g., `--an-arg 3` which should be two separate entries in `argv` is instead squashed into `--an-arg=3`.
3. Dashes are removed from argument names, and then the name is converted into camel case, e.g., `--another-arg=test` gets transformed into `--anotherArg=test`.
4. Argument processing does not handle free form arguments with equal signs, e.g., `--= foo` in an intermediate stage gets squashed to `--==foo` when the command is echoed, and then it gets processed again into two separate `argv` entries: `---==foo` and `--==foo`.

These are issues for me because if I want to write a utility that executes and manages some shell commands for which I want to directly pass the same arguments, I have no ability to know for sure what the original command line arguments that were provided on the command line.

**Comment by willyboy** [comment] 2021-10-20 13:50
For those landing on this because they hit the issue in 2 (below), you can get it to work by escaping the space. 
E.g. 
```
npx ng e2e --project=lib-e2e --headless --config\ video=false --env\  updateSnapshots=true 
```
that prevents the config from being merged to video.


> Not stale.
> 
> @FrozenPandaz here is a repo case so we can remove the `blocked: repo needed` label: https://github.com/kriswuollett/nx/tree/cli-args-mangled. Here is a summary of what I've found so far:
> 
> 1. A single argument is being transformed as if it was a `boolean` argument, e.g., `-a` is mapped to `--a=true`.
> 2. Long form args that aren't joined with their value with an equals sign is forced into that format, e.g., `--an-arg 3` which should be two separate entries in `argv` is instead squashed into `--an-arg=3`.
> 3. Dashes are removed from argument names, and then the name is converted into camel case, e.g., `--another-arg=test` gets transformed into `--anotherArg=test`.
> 4. Argument processing does not handle free form arguments with equal signs, e.g., `--= foo` in an intermediate stage gets squashed to `--==foo` when the command is echoed, and then it gets processed again into two separate `argv` entries: `---==foo` and `--==foo`.
> 
> These are issues for me because if I want to write a utility that executes and manages some shell commands for which I want to directly pass the same arguments, I have no ability to know for sure what the original command line arguments that were provided on the command line.

**Comment by JakeGinnivan** [comment] 2021-11-04 04:29
Not stale

**Comment by JakeGinnivan** [comment] 2021-11-10 06:11
The .net plugin also is affected by this issue

```
nx run api:serve --launchProfile=mac 
Executing Command: dotnet watch --project /Users/jakeginnivan/_code/project/apps/api/Api.csproj run --configuration Debug --launchProfile mac
```

--launchProfile is the wrong CLI command, so need can't use NX to run the serve command. Otherwise need to write code in the plugin to undo the mangling NX does

**Comment by JakeGinnivan** [comment] 2021-11-10 06:48
Yep, adding this to my package.json fixes it

```

  "pnpm": {
    "packageExtensions": {
      "@nx-dotnet": {
        "dependencies": {
          "@nrwl/tao": ">13"
        }
      }
    }
  }
```

**Comment by JakeGinnivan** [comment] 2021-11-10 06:51
This is my current `patch-package` approach to fix it

``` patch
# generated by patch-package 6.4.7 on 2021-11-10 14:51:17
#
# command:
#   npx patch-package @nrwl/tao
#
# declared package:
#   @nrwl/tao: 13.1.3
#
diff --git a/node_modules/@nrwl/tao/src/commands/run.js b/node_modules/@nrwl/tao/src/commands/run.js
index 35bfe0e..7af029a 100644
--- a/node_modules/@nrwl/tao/src/commands/run.js
+++ b/node_modules/@nrwl/tao/src/commands/run.js
@@ -12,7 +12,7 @@ function throwInvalidInvocation() {
     throw new Error(`Specify the project name and the target (e.g., nx run proj:build)`);
 }
 function parseRunOpts(cwd, args, defaultProjectName) {
-    const runOptions = params_1.convertToCamelCase(yargsParser(args, {
+    const runOptions = (yargsParser(args, {
         boolean: ['help', 'prod'],
         string: ['configuration', 'project'],
         alias: {

```

**Comment by smasala** [comment] 2022-02-06 19:06
Happens when using [prisma ](https://www.npmjs.com/package/@nx-tools/nx-prisma) and the push command when trying to pass `--force-reset`. The arg is changed to `--forceReset` which is an unknown command.

**Comment by JakeGinnivan** [comment] 2022-05-08 08:35
As a suggestion on how to proceed on this @AgentEnder @FrozenPandaz 

I think guidance needs to be written in the executor plugins documentation that argument pass-through is not supported because NX needs to understand the commands for each executor so it knows what args to pass to dependent targets etc. (I would need help writing the reasons).
This doco also needs to acknowledge that this means the NX command line arguments will not match the CLI tool the executor is wrapping, it also increases the effort for writing/maintaining plugins but the trade offs around NX understanding the args to be able to generate the UI in the console and other things is worth it.

I've noticed that this behavior has got worse in a recent version where arguments are missing entirely not just transformed.

I have updated one of my plugins https://github.com/sevenwestmedia-labs/nx-plugins/pull/76/files to try and resolve this issue finally for myself.

Thoughts on this resolution? And if you are in support the reasons to not support passthrough would be handy :)

**Comment by juristr** [comment] 2022-06-27 11:22
The camel-case expansion should work now as expected. Also, you can pass additional parameters after a `--` separator. That way they'd be forwarded as is

```
nx script someproj -- some jfjf -no-arg can be anything
```

If the `--` separator is not used, the args will be parsed and interpreted by Nx because we need to be able to split the Nx args from the executor args.

let us know how it works. Also, sorry for the super late update on this one 🙏

**Closed by juristr** 2022-06-27 11:22 UTC
Labels: type: bug, scope: core
