### ISSUE TITLE
Nextjs v13+ sharp package not included issue

### ISSUE THREAD

**Issue by astrodomas** [nrwl/nx#20866] opened 2023-12-20 14:12 UTC
### Current Behavior

Currently when deploying `nextjs` to `production` and leveraging the `image optimization` it is recommended to include `sharp` as a dependency. However, this dependency is `not referenced anywhere` in the `users nx monorepo source code` and thus - `not included in the dependency graph` when building nextjs application which means - generated `production package.json does not include the required dependency`.

The same issue is also for `experimental.optimizeCss` option which requires `critters` package as a dependency.

### Expected Behavior

When adding `sharp` and `critters` dependency it should also include these packages into nextjs application build. 
Another alternative would be to enable to provide extra dependencies inside `project.json` of `nx/next` configuration of the `package.json` to include additional dependencies.

### Steps to Reproduce

1. Create an nx/next project
2. Use <Image /> component from `next/image`
3. Build for production
4. Start production server
5. Get this warning: ` ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization. `
6. Add `sharp` as a dependency inside root `package.json`
7. Build for production
8. Start production server
9. Still get the same warning
10. Check `package.json` -> `sharp` not added.

`experimental.optimizeCss`
1. add an option at next.config.js `experimental: { optimizeCss: true }`
2. Build production
3. Start production
4. Get this Error when starting server: `Error: Cannot find module 'critters'`
5. Add `critters` as a dependency in root `package.json`
6. Build production
7. Start production
8. The same error occurs
9. Check `dist/apps/<app>/package.json` -> `critters` not added

**NOTE:** Serve production from inside `dist/apps/<app>` with `npm i` and `npm run start` performed.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.9.0
   OS     : win32-x64
   npm    : 9.5.1
   
   nx                 : 17.2.4
   @nx/js             : 17.2.4
   @nx/jest           : 17.2.4
   @nx/linter         : 17.2.4
   @nx/eslint         : 17.2.4
   @nx/workspace      : 17.2.4
   @nx/devkit         : 17.2.4
   @nx/eslint-plugin  : 17.2.4
   @nx/next           : 17.2.4
   @nx/react          : 17.2.4
   @nrwl/tao          : 17.2.4
   @nx/web            : 17.2.4
   typescript         : 5.2.2
```

### Failure Logs

```shell
> nx run next:serve:production

   ▲ Next.js 14.0.4
   - Local:        http://localhost:4200
 ✓ Ready in 293ms
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production

> nx run next:build:production

   ▲ Next.js 14.0.4
   - Experiments (use at your own risk):
     · optimizeCss
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
   Generating static pages (0/5) ...
   Generating static pages (1/5) 
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot find module 'critters'
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

## Current workaround:
```
const rootPackageJson = require('../package.json');
const nextBuildPackageJson = require('../dist/apps/web/package.json');
const { writeFileSync } = require('fs');

/**
 * Currently nx omits required dependencies from root package.json such as `sharp`, `critters`
 * This is a workaround to include this dependency into production build
 */
nextBuildPackageJson.dependencies.sharp = rootPackageJson.dependencies.sharp;
nextBuildPackageJson.dependencies.critters =
  rootPackageJson.dependencies.critters;

if (process.env.NODE_ENV !== 'production' && !process.env.CI) {
  nextBuildPackageJson.scripts.start =
    nextBuildPackageJson.scripts.start.concat(' -p 4200');
}

writeFileSync(
  __dirname + '/../dist/apps/web/package.json',
  JSON.stringify(nextBuildPackageJson, null, 4)
);

```

**Comment by supernaut** [comment] 2023-12-20 16:07
Not sure if this is a bug or working as intended, but the work around is to add a `package.json` in your add containing the missing packages and an empty version and they will be added with the version in the root `package.json`:

`apps/my-next-app/package.json`:
```json
{
  "dependencies": {
    "critters": "",
    "sharp": ""
  }
}
```

**Comment by astrodomas** [comment] 2023-12-21 10:18
> Not sure if this is a bug or working as intended, but the work around is to add a `package.json` in your add containing the missing packages and an empty version and they will be added with the version in the root `package.json`:
> 
> `apps/my-next-app/package.json`:
> 
> ```json
> {
>   "dependencies": {
>     "critters": "",
>     "sharp": ""
>   }
> }
> ```

Is there a reference to this in docs somewher because I couldn't find anything on this?

**Comment by supernaut** [comment] 2023-12-21 14:43
> Is there a reference to this in docs somewhere because I couldn't find anything on this?

Not that I know if, I was told this by someone on the Nx Discord if I recall correctly. Before finding this out we used a janky post-build script that did some manual npm installs of missing packages.

**Comment by ndcunningham** [comment] 2023-12-28 17:15
Thanks for describing and providing reproduction steps for this issue.
It will be fixed in the next release which should be `v17.2.9`

**Closed** 2023-12-28 17:33 UTC
Labels: type: bug, scope: nextjs

**Comment by astrodomas** [comment] 2023-12-29 08:25
@ndcunningham Also a quick question regarding 17.3.0-beta.1. I have tried creating an nx monorepo with `npx nx create-nx-workspace@17.3.0-beta.1` It got initialized and everything, but `nextjs` example does not work out of the box (gets `use client` directive error). Could You check it, am I setting up something wrong? My goal is to test `nx` with `nextjs + MUI` as latest `nx` does not support `nextjs@14.0.4`

**Comment by supernaut** [comment] 2023-12-29 08:28
I got Nextjs 14.0.4 to work in Nx after a lot of head butting. It needs `NODE_ENV` to be set to `development` for `nx serve` and production for `nx build`. I have solved with a `.env.build` and a `.env.serve` file in my project root to set the correct values.

**Comment by astrodomas** [comment] 2023-12-29 08:51
> I got Nextjs 14.0.4 to work in Nx after a lot of head butting. It needs `NODE_ENV` to be set to `development` for `nx serve` and production for `nx build`. I have solved with a `.env.build` and a `.env.serve` file in my project root to set the correct values.

Problem is not with `nextjs` itself but rather with `nx`. I get `'use client'` errors for some reason when importing from `@mui/material`

**Comment by ndcunningham** [comment] 2024-02-02 17:40
@astrodomas Sorry I didn't get back to you. 

That's strange can you try removing the `async` from `Index` and or open a new issue?
This should be changed in master shortly.
