### ISSUE TITLE
Error updating lock file with command 'pnpm install --lockfile-only'

### ISSUE THREAD

**Issue by dbudwin** [nrwl/nx#27238] opened 2024-07-31 15:46 UTC
### Current Behavior

We recently switch from NPM to PNPM.  When running the command `npx nx release --skip-publish --verbose;` I get an error updating the lockfie.

Running `pnpm install --lockfile-only` from the workspace root and it executed just fine.

I believe the issue is because the `execSync` command in `update-lock-file.ts` needs the params: `stdio: 'inherit'` and `shell: true`.  When I add these, it works.

### Expected Behavior

PNPM lockfile generation is successful when making a release.

### Steps to Reproduce

1. Make changes to a local package
2. Make a commit using conventional commits so it can know what version to use next
3. Run `npx nx release --skip-publish --verbose`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
pnpm   : 9.6.0

nx             : 19.5.2
@nx/js         : 19.5.2
@nx/jest       : 19.5.2
@nx/linter     : 19.5.2
@nx/eslint     : 19.5.2
@nx/workspace  : 19.5.2
@nx/cypress    : 19.5.2
@nx/devkit     : 19.5.2
@nx/storybook  : 19.5.2
@nrwl/tao      : 19.5.2
@nx/web        : 19.5.2
@nx/webpack    : 19.5.2
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/storybook/plugin
@nx/webpack/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
nx-stylelint : 17.1.5
```

### Failure Logs

```shell
NX   Updating pnpm lock file

Updating pnpm-lock.yaml with the following command:
pnpm install --lockfile-only

 NX   Error updating lock file with command 'pnpm install --lockfile-only'

Verify that 'pnpm install --lockfile-only' succeeds when run from the workspace root.
To configure a string of arguments to be passed to this command, set the 'release.version.generatorOptions.installArgs' property in nx.json.
To ignore install lifecycle scripts, set 'release.version.generatorOptions.installIgnoreScripts' to true in nx.json.
To disable this step entirely, set 'release.version.skipLockFileUpdate' to true in nx.json.


NX   Command failed: pnpm install --lockfile-only


Error: Command failed: pnpm install --lockfile-only
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at execLockFileUpdate (/Users/jsmith/code/platform/node_modules/@nx/js/src/generators/release-version/utils/update-lock-file.js:85:38)
    at updateLockFile (/Users/jsmith/code/platform/node_modules/@nx/js/src/generators/release-version/utils/update-lock-file.js:65:5)
```

### Package Manager Version

PNPM 9.6.0

### Operating System

- [X] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by codebysandeep** [comment] 2024-08-06 23:39
Hi,

I am encountering the same error when running `nx release --first-release` or  `nx release`.

For my project, I am using `pnpm` with Nx.

Here is a sample GitHub repository demonstrating the issue: [GitHub Repository](https://github.com/codebysandeep/delete-nx-release-poc)

**Error Message:**
```
 NX   Error updating lock file with command 'pnpm install --lockfile-only'

Verify that 'pnpm install --lockfile-only' succeeds when run from the workspace root.
To configure a string of arguments to be passed to this command, set the 'release.version.generatorOptions.installArgs' property in nx.json.
To ignore install lifecycle scripts, set 'release.version.generatorOptions.installIgnoreScripts' to true in nx.json.
To disable this step entirely, set 'release.version.skipLockFileUpdate' to true in nx.json.

 NX   Command failed: pnpm install --lockfile-only

Pass --verbose to see the stacktrace.
```

I checked `nx.json` and found that we can use `skipLockFileUpdate: true`, but I feel, it will not be a good solution.

Does anyone have suggestions on how to resolve this? Should we consider using npm instead of pnpm?

![Sample Image](https://github.com/user-attachments/assets/1e06dfda-a2f3-47a4-afc0-c67ba3132d59)

Thank you.

**Comment by leosvelperez** [comment] 2024-08-14 08:30
@codebysandeep are you also using pnpm v9?

I could reproduce the issue in your repo only when using pnpm v9. The issue happens because in pnpm v9 the [`link-workspace-packages`](https://pnpm.io/npmrc#link-workspace-packages) setting was changed to be disabled by default. This means that by default, dependencies will be linked from workspace packages only when they are specified using the [`workspace` protocol](https://pnpm.io/workspaces#workspace-protocol-workspace). So, the error that you're having is that pnpm is trying to fetch `util` from the registry instead of fetching it from the workspace. If you set `link-workspace-packages=true` in the `.npmrc` file, the `nx release` command succeeds.

@dbudwin could you please also check if this is the issue you're facing?

**Comment by dbudwin** [comment] 2024-08-14 13:15
@leosvelperez Yes--when I set `link-workspace-packages=true` I no longer get the error.  I guess I can work with that for now, but I should be able to customize my `.npmrc` settings how I like though.

**Comment by codebysandeep** [comment] 2024-08-15 21:03
@leosvelperez Yes, I’m using PNPM, and the `link-workspace-packages=true` setting in `.npmrc` is working. The **pnpm-lock.yaml** file is updating correctly after running `nx release`.

GitHub repo link:
https://github.com/codebysandeep/delete-nx-release-poc

**Comment by JamesHenry** [comment] 2024-08-25 14:57
@dbudwin @codebysandeep You don't need to use the file config, you can also customize the install command that Nx release runs behind the scenes:

```json
"generatorOptions": {
  "installArgs": "--link-workspace-packages"
 }
```

Having said that, I think that we can probably resolve this by checking for the version of pnpm and if `>= 9`, we pass `--link-workspace-packages` automatically (unless the users has set another value for it already in `installArgs`

**Comment by JamesHenry** [comment] 2024-08-26 13:35
Actually in practice I think the `.npmrc` file is probably better, because you would want it not just for your releases but also your local development.

I just ran into this myself personally: https://github.com/angular-eslint/angular-eslint/pull/2016

I didn't realize until an issue on a PR that I wasn't linking the packages locally.

I will increase the priority of supporting `workspace:` references in source package.json files without overwriting them (you can already use them if you publish your dist package.jsons), this would remove the requirement for this flag (although obviously it would always be an option)

**Comment by JamesHenry** [comment] 2024-09-10 08:59
https://github.com/nrwl/nx/pull/27787 is highly relevant here. It removes the need to worry about pnpm v9 linking local packages by semver numbers at all and will hopefully land very soon

**Comment by or-orchid** [comment] 2024-10-13 12:44
@JamesHenry Hey, was it introduced? I have migrated my monorepo to `20.0.0` and I face the same issue. Should I set `link-workspace-packages=true` in the `.npmrc` file although the PR you mentioned was merged?

**Comment by JamesHenry** [comment] 2024-10-15 18:34
@or-orchid Yes, it landed before v20, here I am using it https://github.com/angular-eslint/angular-eslint/commit/d793c6fe165716c49ead92ea0916edbfc3247660

The only thing keeping this issue open is needing a docs update to reflect this new capability, I will get to it soon

**Comment by JamesHenry** [comment] 2024-12-09 13:29
Hi Folks, I've documented version reference updates in greater detail here: https://github.com/nrwl/nx/pull/29259 including the `preserveLocalDependencyProtocols` option that is highly desirable when pnpm is the package manager (as used by me in angular-eslint as mentioned before https://github.com/angular-eslint/angular-eslint/commit/d793c6fe165716c49ead92ea0916edbfc3247660)

**Closed** 2024-12-10 11:19 UTC
Labels: type: bug, scope: release

**Comment by JamesHenry** [comment] 2024-12-10 12:44
The new docs are available here: https://nx.dev/recipes/nx-release/updating-version-references
