### ISSUE TITLE
Export DevkitTreeFromAngularDevkitTree for compatibility with angular-devkit Tree

### ISSUE THREAD

**Issue by jbjhjm** [nrwl/nx#12662] opened 2022-10-17 09:59 UTC
## Description

While docs state that angular-devkit will always be supported, all helper functions provided by nx require a Nx-Tree class instance. So using angular-devkit is pretty difficult as of now. Any generator relying on angular-devkit must be rewritten from scratch or do without support of any of the nx helper/utilities.

https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/invoke-nx-generator.ts#L75
contains a class "DevkitTreeFromAngularDevkitTree" which seems to be an adapter class allowing to instance a Nx-Tree in a angular-devkit-based generator.

But it is not exported and not documented.

## Suggested Implementation

By exporting this class (and making a note in documentation, e.g. on https://nx.dev/more-concepts/nx-devkit-angular-devkit),
devs working on angular-devkit based generators can make use of nx-tree-base utilities.

Due to the lack of export, I'm currently using a local copy of DevkitTreeFromAngularDevkitTree with a factory function like this:

```ts
// based on invokeNxGenerator - https://github.com/nrwl/nx/blob/master/packages/devkit/src/utils/invoke-nx-generator.ts#L59
export function createNxTreeFromAngularDevkitTree(tree: NgTree, context: SchematicContext, skipWritingConfigInOldFormat=false):Tree {

	const engineHost = (context.engine.workflow as any)?.engineHost || null;

	const root = engineHost?.paths
		? engineHost.paths[1]
		: tree.root.path;

	const adapterTree = new DevkitTreeFromAngularDevkitTree(
		tree,
		root,
		skipWritingConfigInOldFormat
	);

	return adapterTree
}
```

and it seems to work fine.
Think this should be an official feature!

**Comment by Coly010** [comment] 2022-10-18 18:33
Hey! Thanks for bringing this up! 

It looks like you have a good internal workaround that supports this idea for you which is awesome. However, it’s not something we would like to officially support, as it could lead to unexpected behaviors concerning syncing changes between the two trees. 

Angular Devkit and Nx Devkit follow slightly different paradigms and are not directly compatible.

What I would recommend is writing generators using Nx Devkit. Suppose you need to use a third-party Angular Schematic written with Angular Devkit. In that case, you can use the [`wrapAngularDevkitSchematic`](https://nx.dev/devkit/ngcli_adapter#wrapangulardevkitschematic) to turn that schematic into a function that can be used with an Nx Devkit generator. You can see an example of where we do that here for the component generator: https://github.com/nrwl/nx/blob/master/packages/angular/src/generators/component/component.ts#L20

As you have a current workaround and we’re not going to add this officially, I will close this issue. If you need any help writing Nx Devkit generators, feel free to reach out to me, and I will be happy to help where I can!

**Closed by Coly010** 2022-10-18 18:33 UTC
Labels: type: feature, scope: angular, scope: core
