### ISSUE TITLE
build error on upgrade to 13.5.3

### ISSUE THREAD

**Issue by zpydee** [nrwl/nx#8767] opened 2022-01-29 10:41 UTC
## Current Behavior
`Generating application shell...Unhandled Promise rejection: IDBIndex is not defined`

I upgraded from 13.3.2 -> 13.5.3 and a build error on my PWA was introduced. It still seems to occur after upgrade to 13.7.1 too.

no manual code changes affected. all changes via `nx migrate`.

## Expected Behavior
no build errors

## Steps to Reproduce
upgrade  13.3.2 -> 13.5.3 - 13.7.1 and build pwa at each stage...

### Failure Logs
```
⠙ Generating application shell...Unhandled Promise rejection: IDBIndex is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: IDBIndex is not defined
    at Object.44013 (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:62443)
    at __webpack_require__ (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:4508132)
    at Object.43692 (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:31960)
    at __webpack_require__ (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:4508132)
    at /Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5051688
    at /Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5140320
    at Object.<anonymous> (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5140552)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (/Users/zpydee/spawntech/papillio/node_modules/@nrwl/tao/src/compat/compat.js:13:40)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /Users/zpydee/spawntech/papillio/node_modules/@angular-devkit/build-angular/src/builders/app-shell/index.js:65:99
    at ZoneDelegate.invoke (/Users/zpydee/spawntech/papillio/node_modules/zone.js/bundles/zone.umd.js:400:30) ReferenceError: IDBIndex is not defined
    at Object.44013 (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:62443)
    at __webpack_require__ (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:4508132)
    at Object.43692 (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:31960)
    at __webpack_require__ (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:4508132)
    at /Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5051688
    at /Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5140320
    at Object.<anonymous> (/Users/zpydee/spawntech/papillio/dist/v3-ng-papillio-pwa/server/main.js:1:5140552)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (/Users/zpydee/spawntech/papillio/node_modules/@nrwl/tao/src/compat/compat.js:13:40)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /Users/zpydee/spawntech/papillio/node_modules/@angular-devkit/build-angular/src/builders/app-shell/index.js:65:99
    at ZoneDelegate.invoke (/Users/zpydee/spawntech/papillio/node_modules/zone.js/bundles/zone.umd.js:400:30)
✖ Application shell generation failed.
IDBIndex is not defined

```

### Environment
```
Node : 14.18.1
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 11.6.3
   @nrwl/angular : 13.7.1
   @nrwl/cli : 13.7.1
   @nrwl/cypress : 13.7.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.7.1
   @nrwl/eslint-plugin-nx : 13.7.1
   @nrwl/express : 13.7.1
   @nrwl/jest : 13.7.1
   @nrwl/js : undefined
   @nrwl/linter : 13.7.1
   @nrwl/nest : 13.7.1
   @nrwl/next : undefined
   @nrwl/node : 13.7.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.7.1
   @nrwl/tao : 13.7.1
   @nrwl/web : undefined
   @nrwl/workspace : 13.7.1
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.2.0
   	 @angular/cdk: 13.2.0
   	 @angular/common: 13.2.0
   	 @angular/compiler: 13.2.0
   	 @angular/core: 13.2.0
   	 @angular/fire: 7.2.0
   	 @angular/forms: 13.2.0
   	 @angular/material: 13.2.0
   	 @angular/platform-browser: 13.2.0
   	 @angular/platform-browser-dynamic: 13.2.0
   	 @angular/platform-server: 13.2.0
   	 @angular/pwa: 13.2.0
   	 @angular/router: 13.2.0
   	 @angular/service-worker: 13.2.0
   	 @ngrx/component-store: 13.0.1
   	 @ngrx/data: 12.5.1
   	 @ngrx/effects: 13.0.1
   	 @ngrx/entity: 13.0.1
   	 @ngrx/router-store: 13.0.1
   	 @ngrx/store: 13.0.1
   	 @ngrx/store-devtools: 13.0.1
   	 @nguniversal/express-engine: 12.1.0
   	 angular-calendar: 0.29.0
   	 @angular-devkit/architect: 0.1302.0
   	 @angular-devkit/build-angular: 13.2.0
   	 @angular/cli: 13.2.0
   	 @angular/compiler-cli: 13.2.0
   	 @angular/language-service: 13.2.0
   	 @ngrx/schematics: 13.0.1
   	 @nguniversal/builders: 11.2.0

```

**Comment by zpydee** [comment] 2022-02-14 07:19
Any help from anyone would be appreciated.
I've found some other references, but so far none are helping me.

https://github.com/angular/universal/issues/2475

**Comment by Coly010** [comment] 2022-02-14 17:01
Can you provide a minimal repro of this that we can use to investigate?

A quick guess from looking at the Issue you linked is that somewhere in your app, code that is expecting DOM APIs (such as IndexedDB) to be available is being run on the server, where those APIs do not exists. (Node.JS Context vs Browser Context).

If you use @angular/fire, then it's highly probable that the error is coming from there. I see others are having issues with it with SSR.

If you can provide a minimal repro, that would be super helpful as we could pinpoint the issue better :)

**Comment by zpydee** [comment] 2022-02-15 11:51
Hey @Coly010 ,

Mine is a client PWA, so I naturally do expect DOM APIs. The only "SSR" process is the generation of the app-shell, and there are no calls to DOM APIs there. My app architecture is also such that the root app is tiny - it literally just bootstraps the PWA and gives me my lighthouse score. Everything after that is a lazy load.

I do use angularfire and I too suspect the problem might be there. I wonder if the import of AppModule into AppServerModule is causing Firebase initialisation to fire these APIs without doing a browser check first?

I was wondering - Is it possible that any of your deps after `13.5.3` could cause the issue I'm experiencing? I am literally able to rollback to a working version, run `nx migrate` and it breaks - thus the question?

If only it were so easy to create "minimal repros" of massive repos in an attempt to replicate a single bug :-)

I suspect what I might need to do is turn off lazy modules to check if it still exists and then I could at least supply you with a smaller implementation. I'll probably wait a bit though cos I suspect the issues not in my code...

Any thoughts?

**Comment by Coly010** [comment] 2022-02-21 11:02
@zpydee When you roll back versions, what version of `@angular/fire` are you on? And what version is it after you migrate?

Also, could you share your version of `firebase` before and after?

**Comment by VictorienTardif** [comment] 2022-02-21 13:31
Hi, I have the exact same issue and for me neither `@angular/fire` nor `firebase` versions changed, it was `@angular/fire@7.2.0` and `firebase@9.6.1` before and after.

**Comment by zpydee** [comment] 2022-02-22 11:03
I was on `7.2.0` and `9.6.0` respectively (before and after). I normally isolate all nx migrates so this one was entirely on migrating `@nrwl/workspace`.

Sorry I cannot be of more help...

**Comment by zpydee** [comment] 2022-02-22 11:06
Is it possible that bootstrapping the app shell from AppServerModule is calling a constructor in the angular/fire init that's looking for the dom?

**Comment by Coly010** [comment] 2022-02-23 09:38
@zpydee it is possible. It would be worth looking at. As I don't have a reproduction, it's much harder for me to try investigate this currently

**Comment by VictorienTardif** [comment] 2022-02-23 13:37
> @VictorienTardif Are you able to provide a minimal reproduction? It would help me pinpoint where the error is coming from

I'm working on it

**Comment by VictorienTardif** [comment] 2022-02-23 14:16
So, here is the repro @Coly010: https://github.com/VictorienTardif/IDBIndex-not-defined-repro
Branch `master` is working, branch `upgrade-nx` is not.
You can see the diff here: https://github.com/VictorienTardif/IDBIndex-not-defined-repro/pull/1/files

How to check if it's working or not: 
```
yarn
yarn build
yarn build:ssr
yarn serve:ssr
```

**Comment by zpydee** [comment] 2022-02-27 15:09
anyone having any luck with this?

**Comment by jamesdaniels** [comment] 2022-02-28 20:19
FYI I believe this to be the root cause but it just may be the most obvious failure https://github.com/angular/universal/issues/2475#issuecomment-1054624298

**Comment by jamesdaniels** [comment] 2022-03-01 20:11
IMO we can close this as the root cause is not `nx`.

**Comment by Coly010** [comment] 2022-03-02 13:58
Based on @jamesdaniels comments and the following references:

- https://github.com/angular/universal/issues/2475#issuecomment-1054624298
- https://github.com/firebase/firebase-js-sdk/issues/6042

I'll close this issue as it is not related to Nx. Thanks everyone!

**Closed by Coly010** 2022-03-02 13:58 UTC
Labels: type: bug, blocked: repro needed, scope: angular
