### ISSUE TITLE
After upgrade to 13.x storybook fails to compile

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#8580] opened 2022-01-18 17:58 UTC
## Current Behavior
running nx storybook <project> errors in compilation with following error:

```
Error: C:\code\upgrade\upgradetest\apps\myapp\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C:\code\upgrade\upgradetest\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
    at processResult (C:\code\upgrade\upgradetest\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\code\upgrade\upgradetest\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\code\upgrade\upgradetest\node_modules\@ngtools\webpack\src\ivy\loader.js:60:17
```

## Expected Behavior
It should compile

## Steps to Reproduce
This can be reproduced by generating a new workspace with angular as the framework.  I then created a library and ran storybook configuration command.  I selected no when asked to create an e2e app.  Then I just run nx storybook <projectname>

### Failure Logs
```
Error: C:\code\upgrade\upgradetest\apps\myapp\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C:\code\upgrade\upgradetest\node_modules\@ngtools\webpack\src\ivy\loader.js:60:26
    at processResult (C:\code\upgrade\upgradetest\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\code\upgrade\upgradetest\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\code\upgrade\upgradetest\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\code\upgrade\upgradetest\node_modules\@ngtools\webpack\src\ivy\loader.js:60:17
```

### Environment
 Node : 14.17.0
  OS   : win32 x64
  npm  : 6.14.13

  nx : 13.4.5
  @nrwl/angular : 13.4.5
  @nrwl/cli : 13.4.5
  @nrwl/cypress : 13.4.5
  @nrwl/devkit : 13.4.5
  @nrwl/eslint-plugin-nx : 13.4.5
  @nrwl/express : undefined
  @nrwl/jest : 13.4.5
  @nrwl/linter : 13.4.5
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.5
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.5
  @nrwl/storybook : 13.4.5
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.2
         @angular/common: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/router: 13.1.2
         @angular-devkit/build-angular: 13.1.3
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
         @storybook/angular: 6.4.13

**Comment by maro1993** [comment] 2022-01-18 19:59
Facing the same issue

**Comment by jasedwards** [comment] 2022-01-18 20:03
I created a pull request showing this can be reproduced in nx-examples.  it is linked above

**Comment by AlenNS** [comment] 2022-01-18 20:27
I'm having the same issue and it looks like it should be fixed with the next release.
https://github.com/nrwl/nx/pull/8494

**Comment by jasedwards** [comment] 2022-01-18 22:30
following this [comment ](https://github.com/storybookjs/storybook/issues/16977#issuecomment-1010957495) fixes the issue

**Comment by jasedwards** [comment] 2022-01-19 22:37
It looks like 13.4.6 has a [fix ](https://github.com/nrwl/nx/issues/8494) for this.

**Comment by Coly010** [comment] 2022-01-21 10:19
Duplicate of #8527

13.4.6 has been released, so it'll be worth trying again with the latest version of Nx. 

I'm going to close this issue as it is a duplicate. If the issue persists, can you reply to the issue I've linked above so we can keep all conversations related to this issue in one place? 

Thank you!!

**Closed by Coly010** 2022-01-21 10:19 UTC
Labels: type: bug, scope: angular, scope: storybook

**Comment by mandarini** [comment] 2022-02-21 14:47
[New docs](https://github.com/nrwl/nx/pull/9057) for `styles` and `stylePreprocessorOptions`
