### ISSUE TITLE
[@nx/eslint-plugin] Bump @typescript-eslint/parser peer version to >=6

### ISSUE THREAD

**Issue by PupoSDC** [nrwl/nx#19316] opened 2023-09-24 20:50 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

When installing my repo I have this slightly inconvenient warning: 

```
 WARN  Issues with peer dependencies found
.
├─┬ @nx/eslint-plugin 16.9.0
│ ├── ✕ unmet peer @typescript-eslint/parser@^5.60.1: found 6.7.2
│ └─┬ @nrwl/eslint-plugin-nx 16.9.0
│   └─┬ @nx/eslint-plugin 16.9.0
│     └── ✕ unmet peer @typescript-eslint/parser@^5.60.1: found 6.7.2
```

The code seems to work just fine, so bumping the supported peer dependency should be just a formality to suppress an error.

## Motivation

Avoid having `nx` projects having to rely on a relatively old eslint parser version. 

## Suggested Implementation

Add `@typescript-eslint/parser` version 6 and above as a valid peer depedency

https://github.com/nrwl/nx/blob/master/packages/eslint-plugin/package.json#L27C5-L27C44

## Alternate Implementations

Maybe there is some more complex reason why this can't be "just done"

**Comment by CyanoFresh** [comment] 2023-10-05 12:13
Same for prettier:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nx/eslint-plugin@16.10.0
npm ERR! Found: eslint-config-prettier@9.0.0
npm ERR! node_modules/eslint-config-prettier
npm ERR!   dev eslint-config-prettier@"9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional eslint-config-prettier@"^8.1.0" from @nx/eslint-plugin@16.10.0
npm ERR! node_modules/@nx/eslint-plugin
npm ERR!   dev @nx/eslint-plugin@"16.10.0" from the root project
npm ERR!   @nx/eslint-plugin@"16.10.0" from @nrwl/eslint-plugin-nx@16.10.0
npm ERR!   node_modules/@nrwl/eslint-plugin-nx
npm ERR!     @nrwl/eslint-plugin-nx@"16.10.0" from @nx/eslint-plugin@16.10.0
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-config-prettier@8.10.0
npm ERR! node_modules/eslint-config-prettier
npm ERR!   peerOptional eslint-config-prettier@"^8.1.0" from @nx/eslint-plugin@16.10.0
npm ERR!   node_modules/@nx/eslint-plugin
npm ERR!     dev @nx/eslint-plugin@"16.10.0" from the root project
npm ERR!     @nx/eslint-plugin@"16.10.0" from @nrwl/eslint-plugin-nx@16.10.0
npm ERR!     node_modules/@nrwl/eslint-plugin-nx
npm ERR!       @nrwl/eslint-plugin-nx@"16.10.0" from @nx/eslint-plugin@16.10.0
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by meeroslav** [comment] 2023-10-05 13:40
Duplicate of https://github.com/nrwl/nx/issues/18641

**Closed by meeroslav** 2023-10-05 13:40 UTC
Labels: type: feature, scope: linter
