### ISSUE TITLE
@nrwl/esbuild watch mode does not output assets

### ISSUE THREAD

**Issue by DibyodyutiMondal** [nrwl/nx#12901] opened 2022-10-31 05:05 UTC
## Current Behavior
When using the @nrwl/esbuild:esbuild in normal mode, the assets are being added to the dist.
When using watch mode, the assets are not being added

## Expected Behavior
Assets should be getting added in watch mode as well

## Steps to Reproduce
I'll try to get one up asap and post back here

### Environment
Node : 16.17.0
   OS   : linux x64
   pnpm : 7.14.0

   nx : 15.0.4
   @nrwl/angular : 15.0.4
   @nrwl/cypress : 15.0.4
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/esbuild : 15.0.4
   @nrwl/eslint-plugin-nx : 15.0.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.4
   @nrwl/js : Not Found
   @nrwl/linter : 15.0.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : Not Found
   @nrwl/workspace : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:

**Comment by MaxKless** [comment] 2022-12-06 11:12
@jaysoo I'm getting the same issue. Check out this branch on the Nx Console repo for a reproduction:
https://github.com/nrwl/nx-console/tree/feat/cloud-onboarding-webview

`nx run vscode-nx-cloud-onboarding-view:build-webview-files` => everything bundled correctly in `dist/nx-cloud-onboarding-view`
`nx run vscode-nx-cloud-onboarding-view:watch-webview-files` => no assets are bundled

**Comment by DibyodyutiMondal** [comment] 2022-12-17 00:14
I came up with a custom executor that solves my problem.
1. If build is in watch mode, every time changes occur, copy assets, but the copying must not be in watch mode
2. If build is not in watch mode, delegate completely to the original `@nrwl/esbuild` executor
3. For the schema, I point it to the original's schema in node_module/@nrwl/esbuild

```typescript
import type { ExecutorContext } from '@nrwl/devkit';
import { copyAssets } from '@nrwl/js'
import { esbuildExecutor, EsBuildExecutorOptions } from '@nrwl/esbuild';

export default async function* myEsbuildExecutor(
  options: EsBuildExecutorOptions,
  context: ExecutorContext
) {

  if (options.watch) {
    for await (const result of esbuildExecutor(options, context)) {
      await copyAssets({
        assets: options.assets,
        outputPath: options.outputPath,
        watch: false
      }, context);
      yield result;
    }
  }
  else {
    return yield* esbuildExecutor(options, context);
  }
}
```

I hope it helps find out why the original is not working as intended.

---

On a completely side note, while building the executor, typescript complained about 
`node_modules/@nrwl/js/src/utils/schema.d.ts`
The original file started as:
```typescript
const { Linter } = require('@nrwl/linter');
```

To build my plugin, I had to change it to 
```typescript
import { Linter } from '@nrwl/linter';
```

I don't know if this is a problem with my typescript config or a problem with `@nrwl/js` typings. Thought you'd like to know.

**Comment by DibyodyutiMondal** [comment] 2023-01-28 15:23
I discovered something else: in watch mode, assets are not output on first build, but if we edit an asset, it's output into dist after saving.

Consequently, I came up with an even simpler temporary solution:
```typescript
import type { ExecutorContext } from '@nrwl/devkit';
import { copyAssets } from '@nrwl/js'
import { esbuildExecutor, EsBuildExecutorOptions } from '@nrwl/esbuild';

export default async function* customEsbuildExecutor(
  options: EsBuildExecutorOptions,
  context: ExecutorContext
) {

  await copyAssets({
    assets: options.assets,
    outputPath: options.outputPath,
    watch: false
  }, context);

  return yield* esbuildExecutor(options, context);
}
```

**Comment by gaurang171** [comment] 2023-01-30 02:21
@DibyodyutiMondal I am relatively new the builds. For me also assets and sourceMaps are generated. How to use the solution you mentioned earlier? i.e. in which file  the customEsbuildExecutor function go and how to reference that so my project can use it? any suggestion about why sourceMaps are not generated?

**Comment by DibyodyutiMondal** [comment] 2023-01-30 03:13
@gaurang171 In particular, you will be interested in:
https://nx.dev/recipes/executors/creating-custom-executors

and more documentation for creating plugins for internal use can be found here:
https://nx.dev/plugin-features/create-your-own-plugin

Following the example will create an `echoExecutor`.
All you need to do is replace that function, and do a little renaming of the files, and you're good to go.

One important difference from the example is that I am simply delegating, So I deleted schema.json. Instead, I reference the schema of the original @nrwl/esbuild, by copying the file from node_modules. 

As for sourcemaps, I have no idea how to fix that. Although set to true, they are not output in normal builds or watch builds.

**Comment by gaurang171** [comment] 2023-01-30 03:23
@DibyodyutiMondal thank you very much for the prompt response. this is very helpful. specially the links to the proper docs. 
for source map I created this issue. #14556  hopefully someone case help.

**Comment by DibyodyutiMondal** [comment] 2023-01-30 10:40
For some reason, the workarounds I presented above were not working consistently.
In the first workaround, assets would be copied twice on every file change - which is generally not ideal
In the second workaround, sometimes, assets would not be copied on start, but any edited asset would be copied. 

This is the third (and hopefully last) iteration

```typescript
import type { ExecutorContext } from '@nrwl/devkit';
import { copyAssets } from '@nrwl/js'
import { esbuildExecutor, EsBuildExecutorOptions } from '@nrwl/esbuild';

export default async function* customEsbuildExecutor(
  options: EsBuildExecutorOptions,
  context: ExecutorContext
) {

  if (options.watch) {
    let copied = false;

    for await (const result of esbuildExecutor(options, context)) {
      if (!copied) {
        await copyAssets({
          assets: options.assets,
          outputPath: options.outputPath,
          watch: false
        }, context);
        copied = true;
      }
      yield result;
    }
  }
  else
    return yield* esbuildExecutor(options, context);
}
```

**Comment by DibyodyutiMondal** [comment] 2023-02-01 04:12
@gaurang171 when I use esbuild options with the above custom executor, both sourcemaps and assets are being output in watch mode. Is that not the case for you?

**Comment by gaurang171** [comment] 2023-02-01 04:28
@DibyodyutiMondal I must be doing something wrong. I am not able to run custom executor. Getting this error 

```

✘ [ERROR] Cannot use "external" without "bundle"

XXXXXXXXXXXXXXXXXX/node_modules/@nrwl/esbuild/src/executors/esbuild/esbuild.impl.js:111
                const success = results.every((r) => { var _a; return ((_a = r.errors) === null || _a === void 0 ? void 0 : _a.length) === 0; }) && !hasTypeErrors;
                                                                               ^

TypeError: Cannot read properties of undefined (reading 'errors')
    at XXXXXXXXXXXXXXXXX/packages/esbuild/src/executors/esbuild/esbuild.impl.ts:166:34
    at Array.every (<anonymous>)
    at XXXXXXXXXXXXXXXXX//packages/esbuild/src/executors/esbuild/esbuild.impl.ts:166:19
    at Generator.next (<anonymous>)
    at fulfilled (XXXXXXXXXXXXXXXXX//node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.13.0
```

**Comment by DibyodyutiMondal** [comment] 2023-02-01 05:16
@gaurang171 I believe that this error is because of improper esbuild configuration. Could you share the target configuration that you are using?

**Comment by gaurang171** [comment] 2023-02-01 05:24
here is the project.json. Only esbuildOptions is added by me all else are generated with @nrwl/node:application
```
{
  "name": "sos",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "apps/sos/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@geniustic/builds:esbuild-custom",
      "outputs": ["{options.outputPath}"],
      "options": {
        "esbuildOptions": { "sourcemap":true },
        "outputPath": "dist/apps/sos",
        "format": ["cjs"],
        "main": "apps/sos/src/main.ts",
        "tsConfig": "apps/sos/tsconfig.app.json",
        "assets": [ "apps/sos/src/assets" ]
      }
    },
    "serve": {
      "executor": "@nrwl/js:node",
      "options": {
        "buildTarget": "sos:build"
      },
      "configurations": {
        "production": {
          "buildTarget": "sos:build:production"
        }
      }
    },
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["apps/sos/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nrwl/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "apps/sos/jest.config.ts",
        "passWithNoTests": true
      }
    }
  },
  "tags": []
}
```

**Comment by DibyodyutiMondal** [comment] 2023-02-01 05:45
Interesting. It looks ok to me.
Is the problem occurring for `nx build sos` or `nx serve sos` or both?

Does the custom executor modify the config? Could you share that as well?

**Comment by gaurang171** [comment] 2023-02-01 05:58
both build and serve gives error. not sure which config are you looking for.

`tsconfig.base.json`

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@geniustic-node/builds": ["libs/builds/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

`tsconfig.app.json`
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "module": "commonjs",
    "types": ["node"],
    "esModuleInterop": true
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

**Comment by DibyodyutiMondal** [comment] 2023-02-01 06:42
No, I meant the custom executor function

**Comment by gaurang171** [comment] 2023-02-01 13:32
@DibyodyutiMondal I create a new git repo to reproduce the same issue with clean install. https://github.com/gaurang171/node-nx

**Comment by DibyodyutiMondal** [comment] 2023-02-01 18:47
Simplest solution is to set `"bundle": true` in your build target options for the sos app.

In our case, the expected default value for 'bundle' is true, but the default value was never used because the schema was pointing to the generated schema, which was empty.

Thus, a better solution would be to go to `libs/builds/executors.json` and then change the schema reference:
```diff
{
  "$schema": "http://json-schema.org/schema",
  "executors": {
    "build": {
      "implementation": "./src/executors/build/executor",
-     "schema": "./src/executors/build/schema.json", 
+     "schema": "../../node_modules/@nrwl/esbuild/src/executors/esbuild/schema.json",
      "description": "build executor"
    }
  }
}
```

I faced something similar before, and it's easy to trip up on this, which is why I [mentioned earlier](https://github.com/nrwl/nx/issues/12901#issuecomment-1407930233):
>One important difference from the example is that I am simply delegating, So I deleted generated schema.json. Instead, I reference the schema of the original @nrwl/esbuild, by copying the schema.json file from node_modules.

Since we are not making any changes to the schema, referencing the schema from node_modules has 2 advantages:
1. You don't need to manually keep your plugin's schema up-to-date with @nrwl/esbuild.
2. If the original schema describes any default values, those defaults will be applied to your custom plugin as well. (I myself did not know this because I used the node_modules schema from the beginning so I never noticed this. I used to think the defaults would be set regardless)

**Comment by gaurang171** [comment] 2023-02-01 19:54
@DibyodyutiMondal  I can't thank you enough for guiding me through this. new commit is pushed. I am able to generate assets now.

However there is still an issue.  assets is not able to take the string array. if i pass `"apps/sos/src/assets"`,  following lines was not able to generate the files (array length 0)
https://github.com/nrwl/nx/blob/2876996a39751bb90b8e8d7608c1466852af77cf/packages/js/src/utils/assets/copy-assets-handler.ts#L115
to mitigate that I had to use glob. 
`        "assets": [{ "glob": "**/*", "input": "apps/sos/src/assets", "output": "assets"}]
`

Base on my Limited knowledge I think I found the root cause but not sure how to fix it. 
if you look at here. if options.watch is true, only watcher is started but ideally it should be copy and watch.
https://github.com/nrwl/nx/blob/422c8c735a8a4d7a7f343a176c1ca05ba2f12e98/packages/js/src/utils/assets/index.ts#L34

or may be `watchAndProcessOnAssetChange`. should copy before setting watcher.

**Comment by shellscape** [comment] 2023-02-21 16:00
@jaysoo another esbuild-related issue could use attention

**Comment by j1mmie** [comment] 2023-02-23 08:41
Related: https://github.com/nrwl/nx/issues/15105

@gaurang171, the creator of that issue came to the same conclusion. I wonder if `processAllAssetsOnce` should always be called. Then, only in the case where watch is true, call `watchAndProcessOnAssetChange` and return the dispose callback. For  example:


```
  try { 
    await assetHandler.processAllAssetsOnce(); 
  } catch { 
    return { success: false }; 
  } 

  if (options.watch) { 
    const dispose = await assetHandler.watchAndProcessOnAssetChange(); 
    return { 
      success: true, 
      stop: dispose, 
    }; 
  } else { 
    return { success: true }; 
  } 
```

**Comment by jaysoo** [comment] 2023-02-24 14:53
Fix is incoming, thanks @DibyodyutiMondal for the workaround. There was a regression caused by an update to the watcher. Previously it sent all assets on initial watch, but it is only reactive to updates now, so `processAllAssetsOnce` has to be called.

**Closed** 2023-02-24 15:54 UTC
Labels: type: bug, scope: bundlers
