### ISSUE TITLE
NextJS Vercel deployment fails

### ISSUE THREAD

**Issue by pitops** [nrwl/nx#5319] opened 2021-04-12 14:43 UTC
## Current Behavior
```

17:34:32.739 | Cloning github.com/pitops/el-castillo-vape-eshop (Branch: master, Commit: fe092bd)
-- | --
17:34:33.644 | Cloning completed: 904.913ms
17:34:33.670 | Analyzing source code...
17:34:35.375 | Installing build runtime...
17:34:39.165 | Build runtime installed: 3.790s
17:34:43.184 | Looking up build cache...
17:34:43.723 | Build cache not found
17:34:45.006 | Installing dependencies...
17:34:45.352 | yarn install v1.22.10
17:34:45.441 | [1/4] Resolving packages...
17:34:46.033 | [2/4] Fetching packages...
17:35:07.705 | info fsevents@2.3.2: The platform "linux" is incompatible with this module.
17:35:07.705 | info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
17:35:07.718 | info fsevents@1.2.13: The platform "linux" is incompatible with this module.
17:35:07.718 | info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
17:35:07.732 | [3/4] Linking dependencies...
17:35:07.742 | warning "@nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dependency "webpack@^4.18.1".
17:35:07.743 | warning "@nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
17:35:07.744 | warning " > @nrwl/next@12.0.1" has incorrect peer dependency "next@^10.1.2".
17:35:07.745 | warning "@nrwl/next > copy-webpack-plugin@6.0.3" has unmet peer dependency "webpack@^4.37.0 \|\| ^5.0.0".
17:35:07.745 | warning "@nrwl/next > url-loader@3.0.0" has unmet peer dependency "webpack@^4.0.0 \|\| ^5.0.0".
17:35:30.969 | [4/4] Building fresh packages...
17:35:47.012 | Done in 61.66s.
17:35:47.041 | Detected Next.js version: 10.0.9
17:35:47.223 | Running "npx nx build eshop --prod --outputPath=. && nx run eshop:postbuild"
17:35:47.792 | > nx run eshop:build:production --outputPath=.
17:35:49.308 | withNx() plugin: Detected Vercel build environment, applying "experimental-serverless-trace" target
17:35:49.628 | info  - Creating an optimized production build...
17:35:49.654 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
17:35:49.654 | This information is used to shape Next.js' roadmap and prioritize features.
17:35:49.654 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
17:35:49.654 | https://nextjs.org/telemetry
17:35:50.780 | info  - Using external babel configuration from /vercel/path0/babel.config.json
17:35:51.775 | info  - Using external babel configuration from /vercel/path0/apps/eshop/.babelrc
17:36:07.116 | Failed to compile.
17:36:07.116 | ./pages/styles.css
17:36:07.117 | TypeError: Cannot read property 'match' of undefined
17:36:07.117 | > Build failed because of webpack errors
17:36:07.165 | Error: Command "npx nx build eshop --prod --outputPath=. && nx run eshop:postbuild" exited with 1


```

After upgrading to v11.6.1 it started failing. Upgrades to v12 still the same. The error is cryptic and i have no idea what it means. Locally I can build fine.

Command used in Vercel
```
npx nx build eshop --prod --outputPath=. && nx run eshop:postbuild
```

### Environment
```
 Node : 12.20.2
  OS   : darwin x64
  yarn : 1.18.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.0.1
  @nrwl/cypress : 12.0.1
  @nrwl/devkit : 12.0.1
  @nrwl/eslint-plugin-nx : 12.0.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.0.1
  @nrwl/linter : 12.0.1
  @nrwl/nest : Not Found
  @nrwl/next : 12.0.1
  @nrwl/node : Not Found
  @nrwl/react : 12.0.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.0.1
  @nrwl/web : 12.0.1
  @nrwl/workspace : 12.0.1
  @nrwl/storybook : 12.0.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by kirjai** [comment] 2021-04-16 09:55
hey @pitops , a repro repo would help tremendously in identifying what the issue might be here, since, as you said, the error is quite generic

P.S. is this issue, by any chance, reproducible in the same repo as the one you invited me to in order to reproduce an issue a few weeks ago? 👀

**Comment by kirjai** [comment] 2021-04-20 14:23
so, i looked at the private repo that you shared with me from before. 
the issue seems to be in the tailwind config file. here's a diff of the change to `tailwind.config.js` that i had to do to make it work

```diff
+  purge: ['./apps/eshop/pages/**/*.{js,ts,jsx,tsx}', './apps/eshop/shared/**/*.{js,ts,jsx,tsx}'],
-  purge: [
-   {
-     enabled: process.env.NODE_ENV === 'production',
-     content: [
-       './pages/**/*.{js,ts,jsx,tsx}',
-       './shared/**/*.{js,ts,jsx,tsx}',
-     ],
-   },
- ],
```
and from what i can see in the output - it actually purges the classes correctly

give this a try and let me know how it goes!

**Comment by pitops** [comment] 2021-04-20 21:09
Hey @kirjai thanks for taking a look! It seems that was it. It still is weird though something must have changed as this config has not been changed in the last month (last tailwind config change was 16th of march) and the latest working deployment 1st of April

**Comment by kirjai** [comment] 2021-04-21 09:40
great that it works!
could be that some of the dependencies have changed between then and now that started causing this. 

i'll close the issue if it's fixed 👍

**Closed by kirjai** 2021-04-21 09:40 UTC
Labels: scope: nextjs, type: bug
