### ISSUE TITLE
@angular/compiler@"16.0.0" peer dependencies error

### ISSUE THREAD

**Issue by nosaku** [nrwl/nx#16933] opened 2023-05-11 07:13 UTC
### Current Behavior

npm ERR! Found: @angular/compiler@16.0.0
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"16.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"16.0.1" from @angular/compiler-cli@16.0.1
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~16.0.0" from the root project
npm ERR!   peer @angular/compiler-cli@"^16.0.0" from @angular-devkit/build-angular@16.0.1
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~16.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Expected Behavior

npm install should work normally

### Steps to Reproduce

1. npm install

### Nx Report

```shell
NA
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nosaku** [comment] 2023-05-11 07:22
Removing ~ seems to wrok

"@angular-devkit/build-angular": "16.0.0",

**Comment by leosvelperez** [comment] 2023-05-11 07:41
Thanks for reporting this!

It looks like you might have a mix of pinned and non-pinned versions there. According to the posted failure logs, in the `package.json` you have:

- `"@angular-devkit/build-angular": "~16.0.0"`
- `"@angular/compiler-cli": "~16.0.0"`
- `"@angular/compiler": "16.0.0"`

It's recommended to have them aligned. You can either pin them or have the same range. If after doing so, you still have issues, you might need to delete your `package-lock.json` file and install the packages again.

As a recommendation for future issues, please consider providing more detailed reproduction steps. `npm install` is only the command that throws the error, but before that, there are other steps that need to be done to get to the state where running that command throws. Without that information, we can only guess or ask for more info which delays the issue resolution.

I'm closing this since it seems to be an issue with misaligned Angular package versions. If after aligning their versions you still have an issue, please feel free to leave a comment and we can take a look.

**Closed by leosvelperez** 2023-05-11 07:41 UTC
Labels: type: bug

**Comment by nosaku** [comment] 2023-05-11 07:50
@leosvelperez Yeah correct... sorry for the confusion.
