### ISSUE TITLE
Multiple source tags for enforce-module-boundaries

### ISSUE THREAD

**Issue by blessanm86** [nrwl/nx#13751] opened 2022-12-11 17:41 UTC
In our monorepo all of our apps have the tag `type:frontend` and most of our libs have the tag `type:lib`.
There are some libs from a specific team that we only want to be used in some apps.

It would be good if we good specify multiple tags for an app like `tags: ["type:frontend", "scope:eo"]`.
And the lib from the `eo` team could have the tag `tags: ["type:lib", "scope:eo"]`

I would like to specify rules like

```
"depConstraints": [
  {
    "sourceTag": "type:frontend",
    "onlyDependOnLibsWithTags": ["type:lib"],
    "notDependOnLibsWithTags": ["scope:eo"]
  },
  {
    "sourceTag": ["type:frontend", "scope:eo"],
    "onlyDependOnLibsWithTags": ["type:lib"]
  },
```

This sorta reads as projects of `type:frontend` can depend on `type:lib` but not `scope:eo`.
project of type `type:frontend and scope:eo` can depend on `type:lib`.

Right now I have to make a specified tag for some apps, and make rules specific to them.

**Comment by meeroslav** [comment] 2022-12-13 21:28
This is a duplicate of https://github.com/nrwl/nx/issues/12871. Closing this one if favor of the existing one.

**Closed by meeroslav** 2022-12-13 21:28 UTC
Labels: type: feature, scope: linter
