### ISSUE TITLE
Cannot create workspace using pnpm

### ISSUE THREAD

**Issue by nandorpal** [nrwl/nx#23463] opened 2024-05-17 07:35 UTC
### Current Behavior

Whenever I am trying to create a new workspace using pnpm as package manager, the workspace creation fails.
![image](https://github.com/nrwl/nx/assets/90823299/03fee8b7-ea52-435c-8637-d307306b4ab5)

### Expected Behavior

To correctly create the workspace just as with npm.

### Steps to Reproduce

1.
Run command 
```
npx create-nx-workspace@latest nx-angular-monorepo --pm pnpm
``` 
or 
```
npx create-nx-workspace@latest nx-angular-monorepo --preset=angular-monorepo --pm pnpm
```

### Nx Report

```shell
-
```

### Package Manager Version

9.1.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2024-05-17 08:28
Closing as duplicate of https://github.com/nrwl/nx/issues/20222.

**Closed by leosvelperez** 2024-05-17 08:28 UTC
Labels: type: bug
