### ISSUE TITLE
componentGenerator is not exported in @nrwl/angular/generators

### ISSUE THREAD

**Issue by muuvmuuv** [nrwl/nx#10955] opened 2022-06-30 07:41 UTC
## Current Behavior

I cannot build a generator with a standalone component because the `componentGenerator` is not exported from `@nrwl/angular/generators`.

## Expected Behavior

Export `componentGenerator` in `@nrwl/angular/generators`.

## Steps to Reproduce

- Generate a workspace generator
- import `import { componentGenerator } from "@nrwl/angular/generators"`
- See error...

### Failure Logs

When importing it from `src` I get:

```ts
import { componentGenerator } from "@nrwl/angular/src/generators/component/component"
```

```
Package subpath './src/generators/component/component' is not defined by "exports" in /Users/marvin/Development/app/node_modules/@nrwl/angular/package.json
```

### Environment

<details>
<summary>Details</summary>

```
   Node : 17.9.1
   OS   : darwin arm64
   pnpm : 7.4.0

   nx : 14.3.6
   @nrwl/angular : 14.3.6
   @nrwl/cypress : 14.3.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.6
   @nrwl/eslint-plugin-nx : 14.3.6
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.6
   @nrwl/js : 14.3.6
   @nrwl/linter : 14.3.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.6
   @nrwl/web : 14.3.6
   @nrwl/workspace : 14.3.6
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @ionic/angular: 6.1.11
   	 @ngneat/transloco: 4.1.0
   	 ngx-extended-pdf-viewer: 14.0.4
   	 @compodoc/compodoc: 1.1.19
   	 @ionic/angular-toolkit: 6.1.0
   	 @nxtend/capacitor: 13.0.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @testing-library/angular: 12.0.2
   	 nx-stylelint: 13.5.0
```

</details>

**Comment by leosvelperez** [comment] 2022-06-30 15:38
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/10861 and it was fixed in https://github.com/nrwl/nx/pull/10883. Keep an eye on the releases, it should be released soon.

**Closed by leosvelperez** 2022-06-30 15:38 UTC
Labels: type: bug

**Comment by savvyshell** [comment] 2022-06-30 18:20
@muuvmuuv In the mean time while you wait for the release, you can use npm `patch-package` and just manually export it from `src/generators` in `generators.d.ts` for a temporary fix so you can get to work
