### ISSUE TITLE
Default generator options for @nrwl/js:library are not taken into account by the VS Code's extension v18.17.0

### ISSUE THREAD

**Issue by zilia-gmethot** [nrwl/nx#22462] opened 2024-03-22 18:10 UTC
### Current Behavior

When definining options for the `@nrwl/js:library` generator in the Nx configuration file, using the VS Code's Nx extension to generate a new library does not use these options.

### Expected Behavior

When definining options for the `@nrwl/js:library` generator in the Nx configuration file, when using the VS Code's Nx extension to generate a new library, the configured options shoud be pre-configured properly.

### Steps to Reproduce

In the `nx.json` file, under the `generators` key, add the following content:
```
"@nrwl/js:library": {
  "setParserOptionsProject": true
}
```

In VS Code, right-click on the `libs` directory and select the `Nx generate` option. A tab labeled `Generate UI` should open. Notice that the `setParserOptionsProject` isn't checked.

### Nx Report

```shell
Node : 18.18.2
   OS   : linux x64
   npm  : 9.8.1
   
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/angular           : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngrx/component-store    : 15.3.0
   @ngrx/effects            : 15.3.0
   @ngrx/router-store       : 15.3.0
   @ngrx/store              : 15.3.0
   ng2-charts               : 4.1.1
   @ngrx/schematics         : 15.3.0
   @ngrx/store-devtools     : 15.3.0
   @testing-library/angular : 14.5.1
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The Nx Console extension is at version v18.17.0

**Comment by MaxKless** [comment] 2024-03-28 09:51
Hey! Thanks for the report @zilia-gmethot. I'm aware of this and will push a fix next week :)
I'll close this as a duplicate of https://github.com/nrwl/nx-console/issues/1964

**Closed by MaxKless** 2024-03-28 09:51 UTC
Labels: type: bug, scope: console
