### ISSUE TITLE
Any docs on the purpose/usecases tools directory?

### ISSUE THREAD

**Issue by matthewharwood** [nrwl/nx#673] opened 2018-08-07 15:50 UTC
I'm just curious, I see this directory `tools` now and I really don't know how or when to use it?  Are there any docs on how/when/what I should use it for?

**Comment by FrozenPandaz** [comment] 2018-08-07 16:02
Closing as duplicate of https://github.com/nrwl/nx/issues/581. I will elaborate on the current responses there.

**Closed by FrozenPandaz** 2018-08-07 16:02 UTC
Labels: type: question
