### ISSUE TITLE
Module Federation SSR error: "Shared module is not available for eager consumption"

### ISSUE THREAD

**Issue by AlbertoBasalo** [nrwl/nx#14428] opened 2023-01-17 15:07 UTC
### Current Behavior

Following https://blog.nrwl.io/setting-up-module-federation-with-server-side-rendering-for-angular-66bae10ead2d from @colum
In a _host/remotes_ scenario (`dashboard/login`), 
When serving the _host_ with  **SSR**
`npx nx serve-ssr dashboard`
got the error:
 `if(typeof factory !== "function") throw new Error("Shared module is not available for eager consumption: " + id);`
thown at `dist/apps/login/server/main.js`
Also got the same when running: `npx nx serve-ssr login` and when running `npx nx serve login`
But, works well when running `npx nx serve dashboard`

### Expected Behavior

Be able to run a host/remotes module federation with SSR

### Steps to Reproduce

1. npx create-nx-workspace@latest myorg
2. npm install @nrwl/angular
3. npx nx g host dashboard --remotes=login --ssr
4. npx nx serve-ssr dashboard

### Nx Report

```shell
Node : 18.12.1
   OS   : win32 x64
   npm  : 8.6.0

   nx : 15.5.1
   @nrwl/angular : 15.5.1
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nguniversal/express-engine: 15.0.0
         @nguniversal/builders: 15.0.0
```

### Additional Information

Module federation works as expected with non-SSR apps. 
This problem only arises with SSR.
So, it is more related to SSR than to Module Federation.
Thanks

**Comment by goughjo03** [comment] 2023-02-01 15:14
I think I fixed this error by modifying `main.server.tsx`

The existing script was importing and rendering `App` synchronously.

I lazy loaded the App and then rendered it in a Suspense. It seems to have removed the warning / error. like this

```
const LazyApp = lazy(() => import('./app/app'));
```

```
  const stream = ReactDOMServer.renderToPipeableStream(
      <StaticRouter location={req.originalUrl}>
        <Suspense fallback={null}>
          <LazyApp />
        </Suspense>
      </StaticRouter>,
//... other options
)
```

**Comment by leosvelperez** [comment] 2023-02-02 09:19
Thanks for reporting this!

Unfortunately, I couldn't reproduce the issue following the provided reproduction steps. Could you provide a repo where the issue can be reproduced?

Please note that this error normally comes up when a shared module is consumed eagerly (synchronously) and it depends on your application code and MF shared module setup.

**Comment by Coly010** [comment] 2023-02-15 14:26
@delairec here's a link to a working repository that uses mf + ssr with Angular
https://github.com/Coly010/nx-angular-mf-ssr-example

**Comment by Coly010** [comment] 2023-02-23 10:37
Can you run `npm ls @module-federation/node`

**Comment by Coly010** [comment] 2023-02-24 10:46
I've seen the error you mentioned come up every so often, but not often enough that it can be reproducible and it originates from the `@module-federation/node` package.

I'd suggest removing node_modules and your package-lock.json file or yarn.lock file, clearing your npm cache, and trying to run install again.

I'll reach out to the maintainers of the `@module-federation/node` package for further information on this problem

**Comment by Coly010** [comment] 2023-03-01 00:35
Hi @delairec 

There is an issue to track this on the Module Federation side here: https://github.com/module-federation/universe/issues/604

**Comment by ktordoff13** [comment] 2023-04-05 14:13
@delairec 
I was able to resolve the "Shared module is not available for eager consumption" error by doing the following steps below. 

1. click on the `consumes:146` it should take to the logic of this function.  The id `4409` points to some package that isn't being shared. In that file, search for that id `4409` and see what package is the the problem.  In my case it was '@angular/core', '@angular/common', '@angular/router'.
2. I added those to the `additionalShared` in the module-federation.config.js

```javascript
module.exports = {
  name: 'myapp',
  remotes: [],
  additionalShared: ['@angular/core', '@angular/common', '@angular/router']
};
```

I'm on Angular/NX v14.8.6
I hope this helps you.

**Comment by ktordoff13** [comment] 2023-04-06 19:01
@delairec I did this on MacOS  I'm unsure about the SSR portion of your question.

**Comment by LadaBr** [comment] 2023-05-25 14:08
> 

I have same issue even with repo you provided. Currently a blocker for our project. :(

**Comment by vaclav-antosik** [comment] 2023-05-29 11:51
Any progress on this one? We are getting into exactly same problem using Windows machines.
![image](https://github.com/nrwl/nx/assets/8505433/9ae3a74c-11de-4ced-b666-1a3b069be204)

**Comment by cooleso** [comment] 2023-06-12 08:57
Hello! I have same issue in clear  project generated NX from guide here: https://nx.dev/recipes/module-federation/module-federation-with-ssr.
Actually Nx SSR + MFE setup does not work. :(.
```
   Node   : 18.16.0
   OS     : win32 x64
   yarn   : 1.22.10
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.0.2
   @nguniversal/common         : 16.0.2
   @nguniversal/express-engine : 16.0.2
```

**Comment by dontbeev1l** [comment] 2023-06-20 15:49
@AlbertoBasalo, @cooleso i solved problem using modified solution by @ktordoff13 
```javascript
// module-federation.config.js
module.exports = {
  name: 'shell-app',
  remotes: [],
  shared: (libraryName, sharedConfig) => {
    if (libraryName.match('@angular')) { return {
      singleton: true,
      strictVersion: true,
      eager: true,
    }}
    return sharedConfig;
  }
};
```
Works for me on Windows

**Comment by wannnwdooo** [comment] 2023-07-29 13:41
@dontbeev1l ty bro, work in ubuntu

**Comment by Mylonymus** [comment] 2023-11-10 18:35
I founded a solution to this error, from the file main.ts, I changed the file to this:

`import('./bootstrap').catch((err) => console.error(err));`

All working now ;)

**Comment by rengthp** [comment] 2023-12-18 21:30
I am still facing this issue in Nx 16.5.2. Any idea if any permanent fix out for this issue. Even I tried eager set to false for all modules. But end up in a new issue.

**Comment by Coly010** [comment] 2024-05-10 09:30
This remains an issue with how `@module-federation/node` changes the compilation output and is therefore out of our hands. 

There is a workaround provided here that works so I'm going to close this issue

**Closed by Coly010** 2024-05-10 09:30 UTC
Labels: type: bug, blocked: third-party, scope: angular
