### ISSUE TITLE
Expo logs with nx is not visible

### ISSUE THREAD

**Issue by RealOFF** [nrwl/nx#12056] opened 2022-09-17 13:21 UTC
## Current Behavior

When I try to run an expo app, I don't see the expo logs with QR code.

## Expected Behavior

Expo logs should be visible.

## Steps to Reproduce

```
1) clone repo https://github.com/RealOFF/bookup
2) yarn 
3)yarn nx run mobile-customer:start
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

Logs with nx:
```
> nx run mobile-customer:start

Starting project at /Users/Gimpe/Documents/code/do/myapp/apps/mobile-customer
Starting Metro Bundler
Waiting on http://localhost:8081
Logs for your project will appear below.
```
Logs without nx:
```
Starting project at /Users/Gimpe/Documents/code/do/myapp/apps/mobile-customer
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▀ ██▀▀ ▄▀▀▄█▀█ ██ ▄▄▄▄▄ █
█ █   █ █▄▀█████▀ ▄ ▀ █▄███ █   █ █
█ █▄▄▄█ █ ▄ █ ▀▀ ███▀▀ ▀▄▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄█▄▀▄█▄▀▄▀ █▄▄▄▄▄▄▄█
█▄ █ ▀▀▄ ▀▀█▄█▄█▄▄▀▄▄▀ █▄ ▀ ▄▄█  ▀█
█ ▄▀▀█▄▄  ▀▀█▄▀▀███▀ █ ▀█▀██▀█ ▄█▄█
█ ▄▀▀▄▄▄█▄▀▄▄█▄ █▀   █▄▀▄ █ ▄▀ ▀█▀█
█▄█▄██▀▄▄▀▄  ▄▀▀▀█▀ ▀▀▀█ ▄▄▄▀ █▄▀██
█▀▄ ▄ ▀▄▄ ▄ ▀█▀▄▄▄███▄▄▄▀▀▀▄▄▄██▄▄█
██ █▀▀▀▄█▄█ ▀▄█▄▀▀▀ ▀▄▀▄█▀▄▄▄ ▄▄▄▄█
█▄  ▄█ ▄▀█ ███ ▀██▀▄█  ██  ▀██▀██ █
█▄ ▀ ▀▀▄█▀▀▀██  █▀█▀ █▀ █ █ ▄ ▀▄█ █
█▄█▄██▄▄█▀█ ▀  ▄▀▄  ▀▀▄▀  ▄▄▄  █▄ █
█ ▄▄▄▄▄ █▄ █▄█ ▄█▄▀▄█  ██ █▄█  ▄ ▀█
█ █   █ █▀ █▀█▀▄█▄███▀  ▀▄▄   ▄▀ ▀█
█ █▄▄▄█ █▀  ▀▀▄▄▀█ █▀▀▀▀   ██▄▀█▄▄█
█▄▄▄▄▄▄▄█▄█▄▄▄▄██▄█▄▄█▄▄█▄█▄▄█▄█▄██

› Metro waiting on exp+myapp://expo-development-client/?url=http%3A%2F%2F192.168.100.2%3A8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Stopped server
```

**Comment by xiongemi** [comment] 2022-10-28 00:13
i could not reproduce this issue. The log appears for me. coud you try again?

**Comment by YDrogen** [comment] 2022-11-17 08:42
Same issue here.
You can create a new repo with `npx create-nx-workspace@latest expo-issue --preset=expo --interactive=false --appName=expo-issue --nxCloud=false` then run `npx nx serve`.
It works when running `npx expo start` from the `apps/expo-issue` folder itself

**Comment by xiongemi** [comment] 2023-04-25 21:19
i tried latest and expo logs shows up for me:
```
emilyxiong@Emilys-MBP-2 nx-expo-monorepo % nx start cats          

> nx run cats:start

Packager is ready at http://localhost:8081
Starting project at /Users/emilyxiong/Code/nx-expo-monorepo/apps/cats
Starting Metro Bundler
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▀ ██▄█ ▄█ ▄▄▄▄▄ █
█ █   █ █▄▀██▀█▄▀ █ █   █ █
█ █▄▄▄█ █ ▄ █ ▄█ ██ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄█▄█▄▄▄▄▄▄▄█
█▄▄▀▄██▄ █▀█  ▄▀▄▄▀  ▄▀▄▄▀█
█  ▄▄ ▀▄▀█▀▀  ▀ ▀█▄▀ ▀▀█▄▄█
██▀ ▄█▄▄▀▄▀▄ █  █▀█ ▄█ ██▀█
█▄▀▀▄ ▄▄ ▀▀▄ █▀██ ▄▄ ▀▀██▄█
█▄▄▄█▄▄▄▄▀ ██ ▀▄  ▄▄▄ █ ▄ █
█ ▄▄▄▄▄ █▄▀▄▄ █▄  █▄█  ▀ ▄█
█ █   █ █▀▄▀▀▄▄▀▀▄ ▄▄ █▀▄██
█ █▄▄▄█ █▀▄ ██  █  █▄  ▄█▄█
█▄▄▄▄▄▄▄█▄█▄██▄▄█▄███▄▄█▄▄█

› Metro waiting on exp://192.168.0.196:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Web is waiting on http://localhost:8081

› Press a │ open Android
› Press i │ open iOS simulator
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.

```

closing this issue

**Closed by xiongemi** 2023-04-25 21:19 UTC
Labels: type: bug, scope: react-native
