### ISSUE TITLE
Make e2e utils publicly available

### ISSUE THREAD

**Issue by dmitry-stepanenko** [nrwl/nx#14826] opened 2023-02-06 17:03 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

`e2e/utils/index.ts` contains a lot of useful functions that can be used in e2e tests for nx plugins. Such as: `promisifiedTreeKill`, `killPorts`, `runCommandUntil`, `expectJestTestsToPass`, etc.

 Would be awesome to be able to import it from `@nrwl/nx-plugin/testing`, right now I have to just copy-paste them.

**Comment by AgentEnder** [comment] 2023-02-07 18:51
Hey @dmitry-stepanenko! This would be a welcome contribution if you have the time to work on it? @nrwl/nx-plugin's testing utils should have been kept in sync with the shared utils a bit better, but they have grown apart a bit as things have progressed.

**Comment by dmitry-stepanenko** [comment] 2023-02-07 18:58
Sure thing @AgentEnder ! Just to clarify: it would be expected to copy them over, right? From what I see, e2e utils tend to not reuse code from packages

**Comment by AgentEnder** [comment] 2023-05-05 22:04
Hey, I'm going to close this out as a duplicate of #10992. We are working on this area soon, stay tuned. 📺

**Closed by AgentEnder** 2023-05-05 22:04 UTC
Labels: type: feature, scope: plugins
