### ISSUE TITLE
Error when nx migrate latest

### ISSUE THREAD

**Issue by conioX** [nrwl/nx#17119] opened 2023-05-20 08:12 UTC
### Current Behavior

my project not running when i run serve and give this error : 

Watch error: Daemon closed the connection
(node:9732) Warning: Closing file descriptor 4 on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9732) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
(node:9732) Warning: Closing file descriptor 3 on garbage collection

Error when connecting to Nx Cloud. Code: ERR_BAD_REQUEST. Error: This workspace is more than a week old and is unclaimed. Workspaces must be claimed within 7 days of creation..

my node js version v20

### Expected Behavior

running well

### Steps to Reproduce

1. run migrate latest

### Nx Report

```shell
- Error when connecting to Nx Cloud. Code: ERR_BAD_REQUEST. Error: This workspace is more than a week old and is unclaimed. Workspaces must be claimed within 7 days of creation..
```

### Failure Logs

```shell
(node:9732) Warning: Closing file descriptor 4 on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9732) [DEP0137] DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection.
(node:9732) Warning: Closing file descriptor 3 on garbage collection
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by conioX** [comment] 2023-05-20 08:23
and also my nest js downgrade from 9.4.0 to 9.1.1 when i run nx migrate latest

**Comment by sebastianhaberey** [comment] 2023-05-22 13:25
I had the same problem until I discovered that a recent Nx migration (15 to 16) modified the `tasksRunnerOptions` in my `nx.json` to use the runner `nx-cloud`. I restored the old state:

```
  ...
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "test"]
      }
    }
  },
  ...
  ```

**Comment by C0920G1-NguyenQuangHoaiLinh** [comment] 2023-05-23 08:14
"ssl": false

**Comment by StalkAltan** [comment] 2023-05-23 17:01
Hi there!

You have two options here:

1) From @sebastianhaberey:
> I had the same problem until I discovered that a recent Nx migration (15 to 16) modified the tasksRunnerOptions in my nx.json to use the runner nx-cloud. I restored the old state: (see the rest of his comment above)

We prompt you to enable Nx Cloud between major versions. This is something you must answer YES to for it to take effect. If you enabled Nx Cloud and don't want it anymore, you can use his example to remove it from your project (remove the access token and set your `runner` to `nx/tasks-runners/default`)

2) You would like to continue using Nx Cloud
You need to go to cloud.nx.app, create an account, and claim your workspace through the UI.

Closing as this is not a bug.

**Closed by StalkAltan** 2023-05-23 17:01 UTC
Labels: type: bug, scope: nx-cloud
