### ISSUE TITLE
lint errors when using generated libraries in standalone node app

### ISSUE THREAD

**Issue by gioragutt** [nrwl/nx#15469] opened 2023-03-06 13:41 UTC
### Current Behavior

I wanted to test the new changes to @nrwl/node, and came across the following error when trying to use a generated library inside the standalone app code:

```
Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@node-test-1/lib-1"eslint[@nrwl/nx/enforce-module-boundaries](file:///)
```

![image](https://user-images.githubusercontent.com/13711224/223126306-9e26ef15-af2d-43a9-be24-d5a69c7c9604.png)

### Expected Behavior

No errors should happen when referencing libraries

### Steps to Reproduce

1. `npx create-nx-workspace@latest node-test-1 --packageManager=pnpm`
2. `cd node-test-1`
3. `npx nx generate @nrwl/js:library lib-1`
4. add `import { lib1 } from '@node-test-1/lib-1';` to `src/main.ts`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 14.19.3
   OS   : darwin x64
   pnpm : 7.29.0
   
   nx                      : 15.8.5
   @nrwl/js                : 15.8.5
   @nrwl/jest              : 15.8.5
   @nrwl/linter            : 15.8.5
   @nrwl/workspace         : 15.8.5
   @nrwl/cli               : 15.8.5
   @nrwl/devkit            : 15.8.5
   @nrwl/esbuild           : 15.8.5
   @nrwl/eslint-plugin-nx  : 15.8.5
   @nrwl/node              : 15.8.5
   @nrwl/tao               : 15.8.5
   @nrwl/webpack           : 15.8.5
   typescript              : 4.9.5
```

**Comment by gioragutt** [comment] 2023-03-06 13:51
When changing to a relative import, you get another lint error:

![image](https://user-images.githubusercontent.com/13711224/223128873-6cc89173-e108-4eb5-b268-33dadfd50323.png)

**Comment by gioragutt** [comment] 2023-03-06 14:22
I generated another app (with `@nrwl/node:application`), and got the following error when trying to reference the library:

![image](https://user-images.githubusercontent.com/13711224/223136743-8b620539-036b-4f88-a3a3-508d52f6be79.png)

**Comment by meeroslav** [comment] 2023-03-20 09:00
Thank you, @gioragutt, for reporting the issue.

**Comment by meeroslav** [comment] 2023-03-21 13:44
Unfortunately, I could not reproduce this with 15.8.5, nor latest 15.8.7.

If you can provide a repo where this is reproducible I would gladly reopen this issue.

Closing it for now.

**Closed by meeroslav** 2023-03-21 13:44 UTC
Labels: type: bug, scope: linter
