### ISSUE TITLE
--browser command line option for cypress is ignored

### ISSUE THREAD

**Issue by geetikasharma26** [nrwl/nx#2717] opened 2020-03-24 22:34 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation (nx.dev) and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

The command line --browser option should launch the specified browser

## Current Behavior

--browser option is ignored completely.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

npm run e2e --browser firefox command opens the default browser electron for cypress.

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment] 2020-03-27 14:46
Your `--browser` flag was swallowed by npm before it could reach nx.

`npm` requires a delimiting `--` to pass options to the command being run. https://docs.npmjs.com/cli/run-script

This command should work `npm run e2e -- --browser firefox`.

Closing this issue as the issue is not with Nx. Please reopen if you continue having trouble.

**Closed by FrozenPandaz** 2020-03-27 14:46 UTC
