### ISSUE TITLE
15.7.1 breaks build of apps (Cannot read properties of undefined (reading 'data'))

### ISSUE THREAD

**Issue by Inoir** [nrwl/nx#15055] opened 2023-02-16 14:20 UTC
### Current Behavior

with 15.7.1 the build of some apps breaks cause of some dependency issues?!

so some package json has as a dependency version "^8.3.1" defined. "8.3.2" got installed. but still looking for an entry with "^8.3.1". there is only an entry for "8.3.2". so no current defined.

in my case i used "download" npm package with "got": "^8.3.1" as dependency. some other lib has "got": "11.8.3" as dependency. now for the 8.3.1 a version 8.3.2 is installed. this new code cant find "^8.3.1" cause the entry is "8.3.2"

seems to be new implemented code in 15.7.1. doesnt exist in 15.6.3. on 15.6.3 the build is working

![Screenshot 2023-02-16 at 15 10 47](https://user-images.githubusercontent.com/5294072/219388238-604f7367-3455-4756-aef0-f30e2829b1a2.png)

### Expected Behavior

builds same app without changes on 15.7.1

### Steps to Reproduce

1. use nx with i.e "download" npm package
2. install "got" version 11.x
3. use download in some library
4. use lib in some app
5. use "got" v11 in app
6. serve or build app

### Nx Report

```shell
Node : 18.12.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.7.1
   @nrwl/jest              : 15.7.1
   @nrwl/linter            : 15.7.1
   @nrwl/workspace         : 15.7.1
   @nrwl/cli               : 15.7.1
   @nrwl/devkit            : 15.7.1
   @nrwl/eslint-plugin-nx  : 15.7.1
   @nrwl/js                : 15.7.1
   @nrwl/nest              : 15.7.1
   @nrwl/node              : 15.7.1
   @nrwl/nx-plugin         : 15.7.1
   @nrwl/react             : 15.7.1
   @nrwl/tao               : 15.7.1
   @nrwl/webpack           : 15.7.1
   typescript              : 4.9.5
```

### Additional Information

works on 15.6.3

**Comment by Inoir** [comment] 2023-02-16 14:46
seems there is a manipualtion in there on the keys. i made some console log:

![Screenshot 2023-02-16 at 15 45 29](https://user-images.githubusercontent.com/5294072/219396853-7f7b8855-c2ae-48d0-a5c0-92100a5a77d9.png)

![Screenshot 2023-02-16 at 15 46 19](https://user-images.githubusercontent.com/5294072/219396970-11e8fa9a-d3a6-4a96-be1b-42c869024e5d.png)

so there is a correct entry on some logs, but later on the version vanishes

**Comment by meeroslav** [comment] 2023-02-16 19:44
Duplicate of https://github.com/nrwl/nx/issues/15019

**Closed by meeroslav** 2023-02-16 19:44 UTC
Labels: type: bug, scope: core
