### ISSUE TITLE
Assets not being requested for angular esbuild compared to angular webpack

### ISSUE THREAD

**Issue by hernebrink** [nrwl/nx#19330] opened 2023-09-25 20:55 UTC
### Current Behavior

For angular project using esbuild, assets added to project.json e.g. 
```json
"assets": [
    {
        "glob": "**/*",
        "input": "./node_modules/ids-enterprise-wc/themes",
        "output": "/themes"
     }
]
```
are not being requested (available?) as opposed to the same application using webpack.

![image](https://github.com/nrwl/nx/assets/4176143/60a022fa-0fc6-449b-9b03-7d3c99cf4fac)

### Expected Behavior

Expect to get the assets needed when using esbuild.

### GitHub Repo

https://github.com/hernebrink/esbuild-assets-issue

### Steps to Reproduce

1. Clone repo and install dependencies.
2. Run `npm run start1` (this will run/open an angular application using webpack - everything looks as it should)
3. Run `npm run start2` (this will run/open an angular application using esbuild - assets/themes are not requested)
4. See difference between the webpack and esbuild version applications.

### Nx Report

```shell
Node   : 18.18.0
   OS     : darwin-x64
   npm    : 9.8.1
   
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/webpack        : 16.8.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Webpack:
![image](https://github.com/nrwl/nx/assets/4176143/409a3175-c22d-470f-8bba-a488f98abb54)

vs

Esbuild
![image](https://github.com/nrwl/nx/assets/4176143/04f8f292-746c-42c3-9bd8-44dc46f14476)

**Comment by leosvelperez** [comment] 2023-11-14 11:04
Thanks for reporting this!

This is an issue with the Angular CLI's `browser-esbuild` builder. It can be reproduced in an Angular CLI repo where there's no Nx installed (I was able to reproduce it also in Angular v17). The Angular CLI repo would be a better place to report this and get it addressed (better to provide an Angular CLI workspace as a reproduction).

I'm closing this since the issue is not caused by Nx. If you still think there's an issue related to Nx, feel free to leave a comment and we can reopen the issue.

**Closed by leosvelperez** 2023-11-14 11:04 UTC
Labels: type: bug, scope: angular

**Comment by whernebrink** [comment] 2023-11-14 13:40
> Thanks for reporting this!
> 
> This is an issue with the Angular CLI's `browser-esbuild` builder. It can be reproduced in an Angular CLI repo where there's no Nx installed (I was able to reproduce it also in Angular v17). The Angular CLI repo would be a better place to report this and get it addressed (better to provide an Angular CLI workspace as a reproduction).
> 
> I'm closing this since the issue is not caused by Nx. If you still think there's an issue related to Nx, feel free to leave a comment and we can reopen the issue.

Thanks for looking into it!
