### ISSUE TITLE
Storybook build cache not restored after deleting dist folder and trying to run command second time

### ISSUE THREAD

**Issue by pumano** [nrwl/nx#18494] opened 2023-08-04 15:01 UTC
### Current Behavior

Storybook build cache not restored after deleting dist folder and trying to run command second time

### Expected Behavior

Storybook build cache should restore all files to dist folder when cache exists but dist folder not present (angular app cache restored successfully, but not storybook build cache for dedicated library)

### Steps to Reproduce

1. create library and blank storybook for that library
2. add cache step to nx.json: build-storybook
3. build storybook and check files exist in dist/storybook
4. delete dist folder
5. run build-storybook again 

expected result: cached files should be restored in dist/storybook folder

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   yarn   : 3.6.0
   
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/angular        : 16.6.0
   @nx/cypress        : 16.6.0
   @nx/devkit         : 16.6.0
   @nrwl/devkit       : 16.5.1
   @nx/eslint-plugin  : 16.6.0
   @nx/storybook      : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @ngneat/transloco     : 4.3.0
   @ngrx/component-store : 16.1.0
   @ngrx/effects         : 16.1.0
   @ngrx/entity          : 16.1.0
   @ngrx/eslint-plugin   : 16.1.0
   @ngrx/router-store    : 16.1.0
   @ngrx/schematics      : 16.1.0
   @ngrx/store           : 16.1.0
   @ngrx/store-devtools  : 16.1.0
   @storybook/angular    : 7.2.1
   nx-stylelint          : 15.0.0
   ---------------------------------------
```

### Failure Logs

```shell
nx run ui-kit:build-storybook  [existing outputs match the cache, left as is]

info => Cleaning outputDir: /dist/storybook/ui-kit
info => Loading presets
WARN The "@storybook/addon-mdx-gfm" addon is meant as a migration assistant for Storybook 7.0; and will likely be removed in a future version.
WARN It's recommended you read this document:
WARN https://storybook.js.org/docs/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm
WARN 
WARN Once you've made the necessary changes, you can remove the addon from your package.json and storybook config.
info => Building manager..
info => Manager built (92 ms)
info => Compiling preview..
info => Copying static files: /Users/user/projects/front-web/node_modules/@storybook/manager/static at /Users/user/projects/front-web/dist/storybook/ui-kit/sb-common-assets
info Addon-docs: using MDX2
info => Using implicit CSS loaders
info => Using angular browser target options from "ui-kit:build:production"
info => Using angular project with "tsConfig:libs/ui-kit/.storybook/tsconfig.json"
WARN No story files found for the specified pattern: libs/ui-kit/src/lib/**/*.stories.mdx
info => Using default Webpack5 setup
info => Copying static files: /Users/user/projects/front-web/libs/ui-kit/assets at /Users/user/projects/front-web/dist/storybook/ui-kit/
info => Preview built (26 s)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets: 
WARN   static/media/button-slide-9.2a0b6fc9.svg (281 KiB)
WARN   static/media/input-slide-4.1425df95.svg (416 KiB)
WARN   static/media/input-slide-6.a78a6c4d.svg (268 KiB)
WARN   static/media/input-slide-7.0413d7eb.svg (397 KiB)
WARN   static/media/popover-slide-3.e6aee61f.svg (1.01 MiB)
WARN   static/media/select-slide-10.8de744ff.svg (618 KiB)
WARN   static/media/select-slide-11.72787db2.svg (340 KiB)
WARN   static/media/select-slide-17.501f965a.svg (308 KiB)
WARN   static/media/select-slide-6.6127257a.svg (268 KiB)
WARN   static/media/notification-slide-2.339bbe41.svg (313 KiB)
WARN   static/media/notification-slide-4.7fef6a86.svg (248 KiB)
WARN   2180.d9b70125.iframe.bundle.js (968 KiB)
WARN   9504.784c6a89.iframe.bundle.js (583 KiB)
WARN   2631.1cc557bc.iframe.bundle.js (2.06 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (2.17 MiB)
WARN       runtime~main.bb08c851.iframe.bundle.js
WARN       2631.1cc557bc.iframe.bundle.js
WARN       main.css
WARN       main.3570512f.iframe.bundle.js
WARN 
info => Output directory: /Users/user/projects/front-web/dist/storybook/ui-kit
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment] 2023-08-08 10:02
Hi there @pumano ! I unfortunately could not reproduce your issue! Here's a video: https://www.youtube.com/watch?v=PQumSMkYJiU

I can normally build locally, delete dist folder, rebuild and result is fetched from the cache. 

For the record, there's no need to manually add anything to your nx.json. Here's my repo:https://github.com/mandarini/storybook-cache-example, you can check out the `nx.json` and see if there's any differences with yours. I did not add ANYTHING manually in my `nx.json`, our generators do everything automatically!

**Comment by pumano** [comment] 2023-08-08 11:46
@mandarini you use vite but I dont mention I use angular.

**Comment by mandarini** [comment] 2023-08-08 13:12
@pumano same behaviour for Angular, as well! See this vid: https://youtu.be/HKcCXp8TR2s, I also updated my repo to add the Angular app with Storybook. Cache is restored successfully. Let me know if you manage to reproduce, and send me the reproduction so that I can look into it. I think maybe you edited something in your nx.json in a way that caused an issue with the cache?

**Comment by pumano** [comment] 2023-08-08 17:13
@mandarini in your videos you not check existing files inside dist folder after "restoring cache". But I create fresh project and it works properly. But inside my project cache is not stored properly. Outputs folder is just empty but console outputs are the same as in fresh project.

<img width="300" alt="Screenshot 2023-08-08 at 20 10 28" src="https://github.com/nrwl/nx/assets/17675259/121b1222-6e97-48ad-967b-5fb99cdb85cc">

I will try to investigate more about how to reproduce it.

**Comment by pumano** [comment] 2023-08-09 13:25
@mandarini I try it, it not helps. Strange behaviour, I will continue to investigate

**Comment by pumano** [comment] 2023-08-10 23:47
https://github.com/nrwl/nx/issues/18532 looks like same behaviour, but not for storybook

**Comment by SnakeSVx** [comment] 2023-08-30 08:43
Had this issue as well and it was caused by an incorrect value for "outputs".
Outputs was set to ["{options.outputPath}"] but in the options below it there is no outputPath option, it is called outputDir instead.

After changing the outputs to "{options.outputDir}" it seemed like it started working again.

**Comment by mandarini** [comment] 2023-08-30 12:22
Thanks for this @SnakeSVx ! I'll look into it!

**Comment by pumano** [comment] 2023-09-15 13:58
@SnakeSVx I test it right now and confirm! After I change it from `{options.outputPath}` to  `options.outputDir}` it works perfectly well!

**Comment by mandarini** [comment] 2023-10-18 14:08
I will close this since indeed it seems that some renaming during migrations must have gone wrong. For the record, we are doing that renaming indeed: https://github.com/nrwl/nx/blob/master/packages/storybook/src/migrations/update-15-4-6/refactor-executor-options.ts#L47C74-L47C74
so maybe that migration failed on your end for some reason.

If this issue comes up again, I'll be happy to look into it again!

Thank you both for the detailed reports! They were super helpful!

**Closed by mandarini** 2023-10-18 14:08 UTC
Labels: type: bug, scope: storybook
