### ISSUE TITLE
Angular esbuild: Dynamic require of "./app.module-CHKXMOKU.js" is not supported

### ISSUE THREAD

**Issue by Burgov** [nrwl/nx#20204] opened 2023-11-13 08:53 UTC
### Current Behavior

I'm crossposting this from https://github.com/angular/angular-cli/issues/26332 because I'm really stuck with this and I don't really know where to turn. This is happening in my nx workspace, but I'm unable to reproduce it in any other scenario:

I've been trying to migrate to esbuild for a while now, but I keep getting stuck on this issue: everything builds fine, but any require statement in my code (for example for lazy loaded routes) results in the following error:

Dynamic require of "./category-page.module-7XEIW7T3.js" is not supported
For this particular error, the piece of code in my source that causes the issue is:

```
  {
    path: 'category',
    loadChildren: () => import('./category/category-page/category-page.module').then(m => m.CategoryPageModule),
  },
```

And it happens when I try to navigate to the /category route.

In my tsconfig, I have the following settings (among other):

```
    "target": "ES2022",
    "module": "esnext",
    "moduleResolution": "node",
```

and I don't really know what else to look at.

There's clearly some setting wrong, because I'm unable to reproduce this in any other scenario.

### Expected Behavior

-

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.17.1
   OS     : darwin-arm64
   npm    : 9.8.1
   
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nx/nest           : 17.1.1
   @nx/node           : 17.1.1
   @nx/storybook      : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @datorama/akita                  : 7.1.1
   @fortawesome/angular-fontawesome : 0.14.0
   @ngneat/hot-toast                : 6.0.1
   @ngneat/input-mask               : 6.1.0
   @ngneat/reactive-forms           : 2.0.0
   @storybook/angular               : 7.5.3
```

### Failure Logs

```shell
sentry-angular.js:150 Error: Dynamic require of "./category-page.module-QZ6YLQSX.js" is not supported
    at :4200/chunk-42E2GJCJ.js:29:9 [angular]
    at :4200/main.js:1323:64 [angular]
    at Object.onInvoke (core.mjs:14702:33) [angular]
    at :4200/polyfills.js:2519:28 [angular]
    at :4200/@fs/Users/bart/workspace/sfindr/.angular/cache/17.0.0/vite/deps/chunk-YR2ZP4BI.js?v=99b77f60:9060:49 [angular]
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14376:36) [angular]
    at Object.onInvokeTask (core.mjs:14689:33) [angular]
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-11-13 11:16
Thanks for reporting this!

The Angular CLI repo seems the right place to continue tracking this. The implementation of the build pipeline with esbuild is part of the `@angular-devkit/build-angular` package, which is part of that repo. This could still be an issue with Nx if our generators were to generate a wrong configuration causing the issue, but given you mentioned you're unable to reproduce it, this seems unlikely.

I'm closing this in favor of the issue you already opened in the Angular CLI repo, but if you think the issue is caused by Nx, please provide a reproduction so we can troubleshoot this and we'll reopen the issue. Without a reproduction, it's hard to troubleshoot this and we'd be just blind-guessing things.

**Closed by leosvelperez** 2023-11-13 11:16 UTC
Labels: type: bug, scope: angular
