### ISSUE TITLE
 Can not create an application

### ISSUE THREAD

**Issue by DUBANGARCIA** [nrwl/nx#1103] opened 2019-02-23 21:45 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

The workspace is successfully created but when I run "ng generate application app" it gives an error when it asks "Which tags would you like to add to the application? (Used for linting)"

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

- create-nx-workspace examples-apps --yarn --skipGit --style scss --verbose
- ng generate application example --routing --prefix examples-apps --style scss --tags "examples, example"

### Context

Please provide any relevant information about your setup:

- version of Nx used:   7.6.2
- version of Angular CLI used: 7.3.3
- `angular.json` configuration:

`{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 1,
	"newProjectRoot": "",
	"projects": {},
	"cli": {
		"warnings": {
			"typescriptMismatch": false,
			"versionMismatch": false
		},
		"defaultCollection": "@nrwl/schematics",
		"packageManager": "yarn"
	},
	"schematics": {
		"@nrwl/schematics:application": {
			"style": "scss",
			"unitTestRunner": "jest",
			"e2eTestRunner": "cypress"
		},
		"@nrwl/schematics:library": {
			"style": "scss",
			"unitTestRunner": "jest"
		},
		"@nrwl/schematics:node-application": {
			"framework": "express"
		},
		"@schematics/angular:component": {
			"styleext": "scss"
		}
	}
}
`

- version of Angular DevKit used: 0.13.3
- and most importantly - a use-case that fails

- create-nx-workspace examples-apps --yarn --skipGit --style scss --verbose
- ng generate application example --routing --prefix examples-apps --style scss --tags "examples, example"
In which directory should the application be generated? 
Which tags would you like to add to the application? (used for linting) "example,examples-app"

**Comment by FrozenPandaz** [comment] 2019-02-24 02:07
`Nx 7.6.2` should have `@angular/cli` locked to `7.3.1`. `@angular/cli@7.3.3` has a breaking change so please make sure to lock it to `7.3.1`.

Duplicate of #1096

**Closed by FrozenPandaz** 2019-02-24 02:07 UTC
