### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by manndave** [nrwl/nx#455] opened 2018-05-03 13:36 UTC
Whenever I try to add a new package via `yarn add xxxx` I see two warnings in the console:

`warning "@nrwl/schematics > @schematics/angular@0.4.6" has incorrect peer dependency "@angular-devkit/core@0.4.6".`
`warning "@nrwl/schematics > @schematics/angular@0.4.6" has incorrect peer dependency "@angular-devkit/schematics@0.4.6".`

Environment:

- angular/cli: 1.7.4
- nrwl/schematics: 1.0.3
- angular-devkit/core: 0.4.6
- angular-devkit/schematics: 0.4.6

I just nuked node_modules and did a clean `yarn` to see if it was just a corruption issue.  No dice.

I realize they're just "warnings" but they're driving my OCD crazy.  Any ideas how to fix?

Thanks!

**Comment by manndave** [comment] 2018-05-03 13:47
**More Info:**

Angular CLI: 1.7.1
Node: 8.9.4
OS: win32 x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

angular/cli: 1.7.1
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.4.9
angular-devkit/schematics: 0.4.9
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.10.1
schematics/angular: 0.4.6
typescript: 2.6.2
webpack: 3.11.0

**Comment by jeffbcross** [comment] 2018-05-10 21:36
You shared two different versions of angular-devkit (0.4.6 first then 0.4.9 in your second example). Seems like that's probably the cause. I'll close this for now, but if that doesn't solve it, could you create a reproduction on Github that we could pull down and test, and open a new issue? Thanks!

**Closed by jeffbcross** 2018-05-10 21:36 UTC

**Comment by manndave** [comment] 2018-05-10 21:46
I think that's just a typo.  I'll close this, though, as I can't reproduce.  I did notice, however, that my angular-devkit/core is now reporting **0.3.2**.  I have no idea how it got set back so far...it's been a crazy week.  If it pops up again, I'll open a new issue with a repro.

Thanks!

**Comment by jeffbcross** [comment] 2018-05-10 21:52
Ha, sounds good
