### ISSUE TITLE
workspace builder schematic

### ISSUE THREAD

**Issue by cladera** [nrwl/nx#2231] opened 2019-12-22 08:40 UTC
## Expected Behavior

The same way there is a `workspace-schematic` schematic I would expect to be a `workspace-builder` schematic that generates and configures a custom builder into `tools` directory.

## Current Behavior

There is no such schematic in workspace collection.

## Other

Creating builders it not perhaps a task that one would do on a daily basis and creating a built-in schematic might be not justified. That's what I thought few months ago when we decided to migrate our projects to monorepo managed by `nx`. Today we've already got a collection of 13 custom builders and there are more in our backlog to be implemented. 

When creating builders became regular we created a workspace schematic to generate them. 

I believe it would be a good addition to `nx` so I would like to post a PR. As I said, I already implemented this schematic in our project so it would be quite easy for me to share it with you.

**Comment by Hotell** [comment] 2020-01-02 16:26
I guess this is duplicate of https://github.com/nrwl/nx/issues/2211 ?

**Comment by FrozenPandaz** [comment] 2020-01-17 19:22
Closing in favor of https://github.com/nrwl/nx/issues/2211

**Closed by FrozenPandaz** 2020-01-17 19:22 UTC
Labels: scope: misc, type: feature
