### ISSUE TITLE
Vite Builder not copying external packages to package.json

### ISSUE THREAD

**Issue by nvitaterna** [nrwl/nx#13992] opened 2022-12-22 19:40 UTC
### Current Behavior

1. Package.json is copied from the root instead of the library (this looks like it has been fixed in this PR (https://github.com/nrwl/nx/pull/13854) though)
2. After copying the fix from above, no dependencies are copied to the package.json like other builders, regardless if they are declared as external or not in the vite.config.ts file.

### Expected Behavior

The "compiled" package.json file should include external dependencies as defined in the vite.config.ts file. Other builders (js, for example) automatically include dependencies in package.json. Without these dependencies included, the library is broken and will not be able to run.

### Github Repo

https://github.com/nvitaterna/nx-vite-bug

### Steps to Reproduce

1. Clone repo.
2. Run `yarn`
3. Run `yarn nx build test-lib`
4. Open `dist/libs/test-lib/package.json` - there are no dependencies.

### Nx Report

```shell
Node : 18.12.1
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nrwl/vite: 15.3.3
```

### Additional Information

I've also tested this with the latest RC (15.4.0-rc.1). The first issue is fixed but the second one is still there.

**Comment by mandarini** [comment] 2023-01-03 16:41
Can you please retry with latest?

**Comment by nvitaterna** [comment] 2023-01-04 19:24
I've retried with the latest version. Building the library still results in a package.json without lodash specified in the dependencies even though it is not bundled with the library.

**Comment by mandarini** [comment] 2023-01-19 08:45
@ndcunningham adding you to this conversation!

**Comment by ndcunningham** [comment] 2023-01-19 19:28
Duplicate of https://github.com/nrwl/nx/issues/13880
You can continue your conversation there. Closing this.

**Closed by ndcunningham** 2023-01-19 19:28 UTC
Labels: type: bug, scope: bundlers
