### ISSUE TITLE
schematic @nrwl/angular:application: newProjectRoot is non-blank in angular.json, results in ng g app failure

### ISSUE THREAD

**Issue by dherges** [nrwl/nx#1987] opened 2019-10-24 08:32 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

```bash
$ ng g app visual-tests --dry-run
? Would you like to configure routing for this application? Yes
...
NOTE: The "dryRun" flag means no changes were made.
$ echo $?
0
```

## Current Behavior

When `newProjectRoot` is configured to a non-blank value in `angular.json`, `ng g app` fail

```bash
$ ng g app visual-tests --dry-run
? Would you like to configure routing for this application? Yes
Path "/projects/visual-tests-e2e/src/app.e2e-spec.ts" does not exist.
$ echo $?
1
```

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
..
}
```

## Failure Information (for bugs)

By setting `"newProjectRoot": ""` to the empty string, the `ng g app` (schematic `@nrwl/angular:application`) will run.

### Steps to Reproduce

see above

### Context

```bash
$ node_modules/.bin/nx --version 
8.6.0

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.14
Node: 10.16.0
OS: linux x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.14
@angular-devkit/build-optimizer   0.803.14
@angular-devkit/build-webpack     0.803.14
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.0.1
@angular/cli                      8.3.14
@ngtools/webpack                  8.3.14
@schematics/angular               8.3.14
@schematics/update                0.803.14
ng-packagr                        5.7.0
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

### Failure Logs

n/a

## Other

n/a

**Comment by FrozenPandaz** [comment] 2019-11-01 21:25
The root of the issue is this line: https://github.com/nrwl/nx/blob/44c8d17cdd26a48bb862a3db1ca365ee91d3e39a/packages/angular/src/schematics/application/application.ts#L661

This should probably be changed to:
```ts
      ? `${workspaceJson.newProjectRoot}/${options.name}/e2e`
```

However doing so, creates other errors. If someone from the community would be interested in taking a look, we'd be happy to accept PRs to fix this issue!

**Comment by jdgarvey** [comment] 2020-02-19 23:05
Would a similar type of error be causing https://github.com/nrwl/nx/issues/1008?
I know that one is closed but it is basically the exact same behavior for libs.

**Comment by DenysVuika** [comment] 2020-10-02 11:24
Spent a lot of time troubleshooting the nx generate library command before narrowing down and eventually coming across this issue. This should be fixed asap as for me as it breaks the compatibility with Angular CLI

**Comment by mehrad-rafigh** [comment] 2021-01-10 15:27
Hi guys, are you still experiencing the issue? If so I would try to create a PR to fix this

**Comment by brandonroberts** [comment] 2021-02-05 14:37
I believe this is resolved when running `ng add @nrwl/workspace` or `ng add @nrwl/workspace --preserveAngularCLILayout`. If you add the `@nrwl/angular` package manually, then `newProjectRoot` will have to be set to an empty string. Closing this with the note for reference.

**Closed by brandonroberts** 2021-02-05 14:37 UTC
Labels: community, scope: angular
