### ISSUE TITLE
Not possible to import something from a custom TS paths inside a Nest project going from `10.0.7` to `10.2.1`

### ISSUE THREAD

**Issue by maxime1992** [nrwl/nx#3795] opened 2020-09-23 12:45 UTC
## Current Behavior

I have a Nest server that imports a few libraries using TS custom paths defined in `tsconfig.base.json`.

This is working just fine using `@nrwl/*` with the version `10.0.7`.

I just tried to upgrade to `10.2.1` following the doc here: https://nx.dev/angular/workspace/update

After the update, I can run `ng serve` for that app to dev locally but I cannot build my Nest server anymore.

I'm not sure but I'd bet it'd be related to https://github.com/nrwl/nx/pull/3545 and maybe https://github.com/nrwl/nx/issues/3625 (?)

I get an error saying `Module not found: Error: Can't resolve @myorg/my-lib`

**Note:**

Those I think all of the libs I've tried with where created with the angular library schematic :thinking: Maybe it's related.

## Expected Behavior

Being able to use custom TS paths within a Nest app

## Steps to Reproduce

```
yarn create nx-workspace
ng generate @nrwl/nest:application --name=app-debug --no-interactive
ng generate @nrwl/angular:library --name=lib-debug --style=scss --buildable --no-interactive
```

Add one function that you export from that new library, for example

```ts
export const debugFn = () => 'hello';
```

And import it within the `app-debug` app with the TS custom path `@yourWorkspaceName/lib-debug`.  
`ng serve` should work, but trying to build it will error.

That said, maybe it is just a bad practice to import an angular library from a Nest server and apparently a simple `@nrwl/angular - library` does work. But it broke during the update so I'm wondering what's the best approach.

Note: We're also using the `--with-deps` flag so I'm not sure that transforming our angular libs into `@nrwl/workspace - library` would help on that side as the `@nrwl/workspace - library` cannot be built with the `--with-deps` flag.

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

```
  nx : Not Found
  @nrwl/angular : 10.2.1
  @nrwl/cli : 10.2.1
  @nrwl/cypress : 10.2.1
  @nrwl/eslint-plugin-nx : 10.2.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.2.1
  @nrwl/linter : 10.2.1
  @nrwl/nest : 10.2.1
  @nrwl/next : Not Found
  @nrwl/node : 10.2.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.2.1
  @nrwl/web : 10.2.1
  @nrwl/workspace : 10.2.1
  typescript : 3.9.7
```

**Comment by maxime1992** [comment] 2020-09-24 09:11
I gave it a go by creating an empty workspace instead of within our own repo with : 

```
yarn create nx-workspace
yarn add -E --dev @nrwl/node
yarn nx generate @nrwl/node:library --name=debug-lib-1 --buildable --no-interactive
yarn nx generate @nrwl/node:library --name=debug-lib-2 --buildable --no-interactive
```

Unfortunately after importing a function from `debug-lib-2` into `debug-lib-1` everything works as expected :( 

Not sure what broke during the update on our repo...

**Comment by Cammisuli** [comment] 2020-09-25 13:12
Hi @maxime1992 how do your tsconfigs look like? Specifically the nest server one that's not working?

**Comment by maxime1992** [comment] 2020-09-25 14:15
For the server:

**tsconfig.json**

```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "module": "commonjs",
    "types": ["node", "jest"],
    "resolveJsonModule": true
  },
  "include": [],
  "exclude": ["**/*.spec.ts", "**/*.test.ts", "**/*.e2e.ts"],
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

**tsconfig.app.json**
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node"]
  },
  "exclude": ["**/*.spec.ts", "**/*.e2e.ts", "**/*.test.ts", "**/*.test-helper.ts"],
  "include": ["**/*.ts"]
}
```

**Comment by Cammisuli** [comment] 2020-09-25 14:55
hmm. Do you mind creating a reproduction so that I can take a look?

**Comment by maxime1992** [comment] 2020-09-25 15:07
> Do you mind creating a reproduction so that I can take a look?

I tried and failed :s https://github.com/nrwl/nx/issues/3795#issuecomment-698221009

I may have another go at this a bit later on but didn't manage to get one the first time (which I understand make it hard for you to help me :+1:)

**Comment by Cammisuli** [comment] 2021-01-18 19:59
I think it may have to do with the version of Nx. I recently saw that some issues were happening on the v10.x.x line that were fixed with v11.

I'm going to close this in the mean time, because again, everything is working on the latest version. If you're still having issues with the latest version, please feel free to open a new issue. 

Thank you!

**Closed by Cammisuli** 2021-01-18 19:59 UTC
Labels: scope: node, type: bug
