### ISSUE TITLE
Improve documentation for DataPersistence operators run function state parameter 

### ISSUE THREAD

**Issue by robinpellegrims** [nrwl/nx#8033] opened 2021-12-07 08:38 UTC
## Description

The run function inside the options parameter of the datapersistence operators (fetch, optimisticUpdate, pessimisticUpdate) as described in the docs on https://nx.dev/l/a/guides/misc-data-persistence accepts a second parameter `state?: T`. The value of this state parameter is always undefined unless you use the (older, maybe soon deprecated?) DataPersistence service or provide the state yourself by using a selector manually.

## Motivation

In our monorepo, we removed all usages of the DataPersistence service and `NxModule.forRoot()` in favor of the DataPersistence operators. We didn't notice at first that in the few cases that the state parameter was used, this migration introduced runtime errors due to the state parameter being `undefined`. We only found out why this happened after looking into the nx code.
The issue will also be present when users auto-generate the `run` function using IDE auto-completion and then want to use the state parameter. 

## Suggested Implementation

At least mention this behavior in the docs so people can easily find it and know they need to provide the state themselves. It also might be a good idea to add an example of combining the operators with a selector to provide the state argument. We solved the issues in our monorepo by using a selector like this:

```typescript
 this.actions$.pipe(
      ofType(MyAction),
      concatLatestFrom(() => this.store$.select(stateSelector)),
      fetch({
        run: (action, state) => {
```

## Alternate Implementations

Depending on future plans with this DataPersistence functionality in Nx, maybe this run function should be redesigned. It seems a bit weird to have a parameter that is undefined unless you add an extra operator before. Using typescript typings, it might be possible to have a compile error when using the run function with a state parameter without providing it.

**Comment by Coly010** [comment] 2022-01-17 10:46
Hi, thanks for the issue! 

If you're up for it, feel free to open a PR that adds this to the docs 🙂 

After looking over our docs however, our guide on using `DataPersistence` is showing examples of the `operator` only, and not a service. 

This issue may have been caused by lack of documentation at the time operators were preferred, but moving forward, having docs on the usage of the service may be outdated. 

For this reason, I'm going to close this issue.


Thank you for raising it however!

**Closed by Coly010** 2022-01-17 10:46 UTC
Labels: type: feature, scope: angular
