### ISSUE TITLE
Error when trying to generate new lib using `nx` command

### ISSUE THREAD

**Issue by Edouardbozon** [nrwl/nx#2013] opened 2019-10-31 15:39 UTC
## Current Behavior

Hi folks, :hand: 

I'm facing a cryptic error when trying to generate new lib in a Nx repository. I'm running the command `yarn nx generate lib my-lib` which unexpectedly fails and gives the following output: 

```
>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
error Command failed with exit code 1.
```

I tried to directly use the `ng` command like `yarn ng generate lib my-lib` and it works well. That's why I'm opening the issue here.

## Expected Behavior

I would like to generate new library using the `nx` command.

### Steps to Reproduce

Simply run `yarn nx generate lib my-lib` will throw the error. I tried with a fresh new Nx installation and I ran into the same problem.

If you're willing I can investigate to fix this error.

**Comment by bcabanes** [comment] 2019-11-01 20:00
Hi @Edouardbozon!
I wasn't able to reproduce the error by doing `yarn nx generate lib my-lib`. Are you using the latest version of Nx? Can you provide a repository containing a minimal project reproducing the error?

Thank you!

**Comment by Edouardbozon** [comment] 2019-11-06 15:25
Hi @bcabanes, I'm using the latest version of Nx. I'm not able to isolate and reproduce this error in a minimal project. However the project where the error occurs is available [here](https://github.com/jscutlery/http-ext). It's a simple Nx repository that only contain one Angular app and one publishable library.

I compared file per file with a fresh new Nx installation but I found nothing suspicious.

**Comment by jdpearce** [comment] 2019-11-07 13:05
Hi @Edouardbozon - this is down to an incompatibility between your local version of RxJS and the Angular CLI version of RxJS.

Your `package.json` has `~6.5.0` whereas the Angular CLI version you have installed requires `6.4.0`. This bug only manifests when running `nx` because then it will use the version of RxJS in your `package.json` _not_ the internal version that Angular CLI installs.

If you downgrade your version of RxJS it will work correctly.

**Comment by Edouardbozon** [comment] 2019-11-07 18:37
@jdpearce, you're right it's due to a RxJS version mismatch, thanks! I'm willing to submit a PR to bump RxJS, would you accept that?

**Comment by jdpearce** [comment] 2019-11-08 13:03
@Edouardbozon I haven't explored this beyond your repro repo. Can you replicate this with a clean Nx workspace?

Bumping the RxJS version that Nx depends on wouldn't help as it's the Angular CLI that's pinned to 6.4.0 - we would have to pin ours to the same version.

What we _could_ do is change the way that we call into the Angular CLI though...

**Comment by FrozenPandaz** [comment] 2019-12-06 20:49
This is fixed with https://github.com/nrwl/nx/pull/2046

**Closed by FrozenPandaz** 2019-12-06 20:49 UTC
Labels: blocked: repro needed
