### ISSUE TITLE
Migration from 12.9 -> 13.4: MiniCssExtractPlugin is not a constructor

### ISSUE THREAD

**Issue by hevans90** [nrwl/nx#8541] opened 2022-01-14 19:11 UTC
## Current Behavior
After migrating from 12.9 to 13.4, `nx serves` or `nx builds` of my react application throw the following error:

![image](https://user-images.githubusercontent.com/12142999/149571603-7ac999c5-3b1d-4260-91aa-f748149996b4.png)

## Expected Behavior
Serves/Builds work as usual.

## Steps to Reproduce
Migrate from 12.9 to 13.4 and then serve a react application.

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : darwin x64
  yarn : 1.22.17

  nx : 13.4.4
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.4
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : 13.4.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : 13.4.4
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.3.5
  rxjs : 6.6.7
  ---------------------------------------
  Community plugins:

(node:49971) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/harrisonevans/source/idle-game/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by JuliusKoronci** [comment] 2022-01-14 20:42
I can confirm..even following the basic tutorial doesnt work

**Comment by xanol** [comment] 2022-01-14 20:46
Same here, using a fresh nx 13.4.4 workspace and empty react project.

**Comment by FrozenPandaz** [comment] 2022-01-14 21:06
I am actively addressing this issue. This is a duplicate of https://github.com/nrwl/nx/issues/8540 and will be solved by the same PR.

**Closed by FrozenPandaz** 2022-01-14 21:06 UTC
Labels: type: bug
