### ISSUE TITLE
bug(@nrwl/angular): v15 migration not migrating unit tests

### ISSUE THREAD

**Issue by AlixRoyere** [nrwl/nx#15138] opened 2023-02-20 18:41 UTC
### Current Behavior

Migration scripts from @nrwl/angular@14.8.6 to 15.7.2, are not migrating tests files (spec.ts), when other files are migrated without error nor warning (examples: modules.ts and component.ts).

The script updating the files:
```
Ran migration-v15 from @angular/material
  Updates the Angular Material to v15
  // Some files are updated

Running 'npm install' to make sure necessary packages are installed

changed 1 package in 2m

202 packages are looking for funding
  run `npm fund` for details

 >  NX   Successfully finished running migrations from 'migrations.json'. This workspace is up to date!

```

### Expected Behavior

Nx scripts should update spec.ts files, as angular is doing properly when there is not nx.

Examples of imports that have been correctly updated by angular script on a non nx project:
```
import { MatLegacyFormFieldHarness as MatFormFieldHarness } from "@angular/material/legacy-form-field/testing";
import { MatLegacyInputHarness as MatInputHarness } from "@angular/material/legacy-input/testing";
import { MatLegacySelectHarness as MatSelectHarness } from "@angular/material/legacy-select/testing";
import { MatLegacyError as MatError, MatLegacyLabel as MatLabel } from "@angular/material/legacy-form-field";
import { MatLegacySlideToggle as MatSlideToggle } from "@angular/material/legacy-slide-toggle";
import {
  MAT_LEGACY_DIALOG_DATA as MAT_DIALOG_DATA,
  MatLegacyDialogActions as MatDialogActions,
  MatLegacyDialogClose as MatDialogClose,
  MatLegacyDialogContent as MatDialogContent,
  MatLegacyDialogRef as MatDialogRef,
  MatLegacyDialogTitle as MatDialogTitle,
} from "@angular/material/legacy-dialog";
import { MatLegacyCheckbox as MatCheckbox } from "@angular/material/legacy-checkbox";
import { MatLegacyDialog as MatDialog } from "@angular/material/legacy-dialog";
import { MatLegacyButton as MatButton } from "@angular/material/legacy-button";
```
Or at least nx scripts should display a warning or an error when something goes wrong.

### Steps to Reproduce

1. nx migrate latest
2. npm install
3. nx migrate --run-migrations

### Nx Report

```shell
Node : 16.14.2
   OS   : win32 x64
   npm  : 8.5.0
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/webpack           : 15.7.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/spectator : 14.0.0
   ng-mocks          : 14.6.0
   ngx-build-plus    : 15.0.0
```

### Additional Information

How to fix my half migrated project? :cry:

**Comment by leosvelperez** [comment] 2023-02-20 19:07
Thanks for reporting this!

This is a know issue and a duplicate of https://github.com/nrwl/nx/issues/13733. There's more context on the issue and a suggested workaround for migrating tests in https://github.com/nrwl/nx/issues/13733#issuecomment-1344466113.

I'm closing this one as a duplicate. Please follow the conversation in the linked issue.

**Closed by leosvelperez** 2023-02-20 19:07 UTC
Labels: type: bug
