### ISSUE TITLE
Strange chars "^[[8;1R" blocks executing nx commands after update to NX 18.1.3

### ISSUE THREAD

**Issue by gtteamamxx** [nrwl/nx#22514] opened 2024-03-26 12:15 UTC
### Current Behavior

When I'm starging my angular application using NX 18.1.3, I need to press enter twice before execue every command.
It started after upgrading nx to the latest version.

```
Executing task: npx nx run cmms-web:serve 


> nx run my-app-web:serve

^[[6;1R           <------ this is shwoing, now I need to press enter

> nx run my-app-web:prepare-translations

^[[8;1R          <------- showing again

> @company/source@0.0.0 transloco:extract-scoped-libs

... and all is working
```

### Expected Behavior

These chars will not ne showed and It will not stop executing commands.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 20.11.0
OS     : win32-x64
npm    : 10.2.4

nx (global)        : 18.1.1
nx                 : 18.1.3
@nx/js             : 18.1.3
@nx/jest           : 18.1.3
@nx/linter         : 18.1.3
@nx/eslint         : 18.1.3
@nx/workspace      : 18.1.3
@nx/angular        : 18.1.3
@nx/cypress        : 18.1.3
@nx/devkit         : 18.1.3
@nrwl/devkit       : 17.0.2
@nx/eslint-plugin  : 18.1.3
@nx/storybook      : 18.1.3
@nrwl/tao          : 18.1.3
@nx/web            : 18.1.3
@nx/webpack        : 18.1.3
typescript         : 5.3.3
---------------------------------------
Community plugins:
@ngneat/transloco                    : 6.0.4
@nx-dotnet/core                      : 2.1.2
@progress/kendo-angular-buttons      : 15.3.0
@progress/kendo-angular-dateinputs   : 15.3.0
@progress/kendo-angular-dialog       : 15.3.0
@progress/kendo-angular-dropdowns    : 15.3.0
@progress/kendo-angular-excel-export : 15.3.0
@progress/kendo-angular-filter       : 15.3.0
@progress/kendo-angular-grid         : 15.3.0
@progress/kendo-angular-icons        : 15.3.0
@progress/kendo-angular-inputs       : 15.3.0
@progress/kendo-angular-intl         : 15.3.0
@progress/kendo-angular-l10n         : 15.3.0
@progress/kendo-angular-label        : 15.3.0
@progress/kendo-angular-layout       : 15.3.0
@progress/kendo-angular-navigation   : 15.3.0
@progress/kendo-angular-pdf-export   : 15.3.0
@progress/kendo-angular-popup        : 15.3.0
@progress/kendo-angular-progressbar  : 15.3.0
@progress/kendo-angular-treelist     : 15.3.0
@progress/kendo-angular-treeview     : 15.3.0
@progress/kendo-angular-utils        : 15.3.0
@storybook/angular                   : 7.6.10
---------------------------------------
The following packages should match the installed version of nx
  - @nrwl/devkit@17.0.2

To fix this, run `nx migrate nx@18.1.3`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Migration from 17.2.8 to 18.1.4

**Comment by dmcweeney** [comment] 2024-03-26 17:45
Also happening on 18.1.2

**Comment by JelleBruisten** [comment] 2024-03-26 17:49
Might be a duplicate of #22358

**Comment by FrozenPandaz** [comment] 2024-03-27 17:46
Closing as a duplicate of https://github.com/nrwl/nx/issues/22358

**Closed by FrozenPandaz** 2024-03-27 17:46 UTC
Labels: type: bug
