### ISSUE TITLE
nest + angular schematics now working

### ISSUE THREAD

**Issue by sivanisentinel** [nrwl/nx#5712] opened 2021-05-19 09:01 UTC
## Current Behavior
the out of the box project in not running. getting this error:

 Generating browser application bundles...(node:19521) UnhandledPromiseRejectionWarning: TypeError: webpack_1.node.NodeTargetPlugin is not a constructor
    at WebpackResourceLoader._compile (/Users/sivani/dev/example/node_modules/@ngtools/webpack/src/resource_loader.js:83:13)
    at WebpackResourceLoader.get (/Users/sivani/dev/example/node_modules/@ngtools/webpack/src/resource_loader.js:210:44)
    at Object.resourceHost.readResource (/Users/sivani/dev/example/node_modules/@ngtools/webpack/src/ivy/host.js:30:35)
    at AdapterResourceLoader.preload (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/resource/src/loader.js:88:39)
    at resolveStyleUrl (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:192:49)
    at /Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:233:83
    at Array.map (<anonymous>)
    at ComponentDecoratorHandler.preanalyze (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:233:50)
    at _loop_1 (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:321:53)
    at TraitCompiler.analyzeClass (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:343:35)
    at visit (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:113:27)
    at visitNodes (/Users/sivani/dev/example/node_modules/typescript/lib/typescript.js:28217:30)
    at Object.forEachChild (/Users/sivani/dev/example/node_modules/typescript/lib/typescript.js:28456:24)
    at visit (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:115:20)
    at TraitCompiler.analyze (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:117:13)
    at TraitCompiler.analyzeAsync (/Users/sivani/dev/example/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:79:25)
(node:19521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

webpack_1.util.cleverMerge is not a function

## Steps to Reproduce
 npx create-nx-workspace@latest
 
 choose nest + angular 

I use mac if it makes any difference 

thanks 🙏

**Comment by leosvelperez** [comment] 2021-05-19 09:08
Thanks for reporting this!

Please note this is a duplicate of #5682. I'm going to close this issue in favor of that one. Please follow that issue for a solution.

**Closed by leosvelperez** 2021-05-19 09:08 UTC
Labels: type: bug
