### ISSUE TITLE
bug(nx-plugin):  e2e tests fail for new plugin workspace

### ISSUE THREAD

**Issue by AdditionAddict** [nrwl/nx#15891] opened 2023-03-25 13:27 UTC
### Current Behavior

Creating a new plugin workspace and running e2e test fails.
There's also a jest coverageDirectory validation warning.

### Expected Behavior

e2e run and pass without warnings / warning if I'm putting wrong settings for create-nx-plugin

### Steps to Reproduce

1.  `npx create-nx-plugin extruda-nx --pluginName=workspace --packageManager=pnpm`
2.  `cd extruda-nx`
3.  (added Nx Cloud DTE)
4.  `pnpm exec nx run workspace-e2e:e2e --verbose`

### Nx Report

```shell
Node : 16.17.1
   OS   : win32 x64
   pnpm : 7.5.2

   nx                      : 15.8.9
   @nrwl/js                : 15.8.9
   @nrwl/jest              : 15.8.9
   @nrwl/linter            : 15.8.9
   @nrwl/workspace         : 15.8.9
   @nrwl/devkit            : 15.8.9
   @nrwl/eslint-plugin-nx  : 15.8.9
   @nrwl/nx-plugin         : 15.8.9
   @nrwl/nx-cloud          : 15.3.2
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @extruda-nx/workspace
```

### Failure Logs

```shell
C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx>pnpm exec nx run workspace-e2e:e2e --verbose

 >  NX   RunStart


{
  "meta": {
    "nxCloudVersion": "^15.3.2"
  },
  "branch": null,
  "runGroup": "c721a9f8bea7f7a673b62cd98b84c4d891995bdc",
  "ciExecutionId": null,
  "ciExecutionEnv": "",
  "hashes": [
    "8f3f63c2728d6e53c4e11c26ad421b2aec2ddc8659b43d1d9c97b6b23faa6117"
  ]
}

RunStart duration: 229

 >  NX   Nx Cloud: Cache miss 8f3f63c2728d6e53c4e11c26ad421b2aec2ddc8659b43d1d9c97b6b23faa6117.


> nx run workspace-e2e:e2e

Compiling TypeScript files for project "workspace"...
Done compiling TypeScript files for project "workspace".
● Validation Warning:

  Unknown option "coverageDirectory" with value "../../coverage/e2e/workspace-e2e" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

 FAIL   workspace-e2e  e2e/workspace-e2e/tests/workspace.spec.ts (58.192 s)
  workspace e2e
    × should create workspace
    --directory
      × should create src in the specified directory (1 ms)
    --tags
      × should add tags to the project

  ● workspace e2e › should create workspace

    Command failed: node C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx\node_modules\.pnpm\nx@15.8.9_cuaypwimdup25vwsqc5i3ttbya\node_modules\nx\bin\nx.js new proj --nx-workspace-root=C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

      15 |   // are not dependant on one another.
      16 |   beforeAll(() => {
    > 17 |     ensureNxProject('@extruda-nx/workspace', 'dist/packages/workspace');
         |                    ^
      18 |   });
      19 |
      20 |   afterAll(() => {

      at runNxNewCommand (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at newNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)
      at ensureNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at Object.<anonymous> (tests/workspace.spec.ts:17:20)

  ● workspace e2e › --directory › should create src in the specified directory

    Command failed: node C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx\node_modules\.pnpm\nx@15.8.9_cuaypwimdup25vwsqc5i3ttbya\node_modules\nx\bin\nx.js new proj --nx-workspace-root=C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

      15 |   // are not dependant on one another.
      16 |   beforeAll(() => {
    > 17 |     ensureNxProject('@extruda-nx/workspace', 'dist/packages/workspace');
         |                    ^
      18 |   });
      19 |
      20 |   afterAll(() => {

      at runNxNewCommand (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at newNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)
      at ensureNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at Object.<anonymous> (tests/workspace.spec.ts:17:20)

  ● workspace e2e › --tags › should add tags to the project

    Command failed: node C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx\node_modules\.pnpm\nx@15.8.9_cuaypwimdup25vwsqc5i3ttbya\node_modules\nx\bin\nx.js new proj --nx-workspace-root=C:\Users\andrewa\Documents\ProofOfConceptApps\extruda-nx/tmp/nx-e2e --no-interactive --skip-install --collection=@nrwl/workspace --npmScope=proj --preset=empty

      15 |   // are not dependant on one another.
      16 |   beforeAll(() => {
    > 17 |     ensureNxProject('@extruda-nx/workspace', 'dist/packages/workspace');
         |                    ^
      18 |   });
      19 |
      20 |   afterAll(() => {

      at runNxNewCommand (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:15:18)
      at newNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:72:3)
      at ensureNxProject (../../node_modules/.pnpm/@nrwl+nx-plugin@15.8.9_4oval3qowh5egelb4ssmepz5cm/packages/nx-plugin/src/utils/testing-utils/nx-project.ts:86:3)
      at Object.<anonymous> (tests/workspace.spec.ts:17:20)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        62.788 s, estimated 214 s
Ran all test suites.

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target e2e for project workspace-e2e failed

   Failed tasks:

   - workspace-e2e:e2e

   Hint: run the command with --verbose for more details.

   View structured, searchable error logs at https://nx.app/runs/EqNvMgoyY5
```

### Additional Information

I get the same issue with creating a plugin in the same workspace as I want to use.

**Comment by AdditionAddict** [comment] 2023-03-25 14:02
https://github.com/nrwl/nx/issues/15263 suggests issue is yarn berry specific but I'm using pnpm. Not sure if duplicate

**Comment by AdditionAddict** [comment] 2023-03-26 09:54
Tested v15.3.3 and this passes

**Comment by tinesoft** [comment] 2023-03-26 10:08
For info, i'm having also the same issue, using a [workspace managed with Yarn 2](https://github.com/tinesoft/nxrocks/actions), with latest Nx `v15.8.9`. 
It appeared all the sudden after migrating to Nx v15.8.0 and has been present ever since.

**Comment by opfx** [comment] 2023-03-31 20:17
Yarn fails when a new project mock project is created by ensureNxProject. The function call newNxProject function, which executes yarn to install the mock project's dependencies. Before invoking yarn the cwd is set to the mock project's directory. This causes yarn to fail with the following error:

`Usage Error: The nearest package directory (/workspace-path/tmp/nx-e2e/proj) doesn't seem to be part of the project declared in /workspace-path.`

    
A possible workaround is to add `/tmp/nx-e2e/*` to the workspace package.json

```
{

"workspaces": [
"tmp/nx-e2e/*"
], 

}
```

**Comment by AgentEnder** [comment] 2023-04-26 22:44
This is a duplicate of #15263, so I'm going to close it.

**Closed** 2023-04-26 22:44 UTC
Labels: type: bug, scope: plugins
