### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by cwqt** [nrwl/nx#4712] opened 2021-02-05 12:39 UTC
## Current Behavior

`nx serve` throws the following error:

```
> cross-env NODE_ENV=development && nx serve backend --configuration=development
> nx run backend:serve:development 
Class extends value undefined is not a constructor or null
```

Initially I thought this was to do with my code & some circular import but after removing everything and having just a `console.log` in the `index.ts` the error still happens.

## Expected Behavior

Should run the application - I have reverted to `nx@10.4.12` which stops the error from happening.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

* Create new express project
* Add `console.log('hello world');` to `index.ts`
* Run with `nx serve app`
* Throws `Class extends value undefined is not a constructor or null`

### Failure Logs

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.5.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'run',
0 verbose cli   'backend'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/cass/Code/redacted/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/cass/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session b8c428efbaea8791
20 timing npm:load Completed in 13ms
21 timing command:run-script Completed in 1443ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1063:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
23 verbose pkgid redacted-core@0.0.1
24 verbose cwd /Users/cass/Code/redacted
25 verbose Darwin 19.6.0
26 verbose argv "/usr/local/Cellar/node/15.5.0/bin/node" "/usr/local/bin/npm" "run" "backend"
27 verbose node v15.5.0
28 verbose npm  v7.3.0
29 error code 1
30 error path /Users/cass/Code/redacted
31 error command failed
32 error command sh -c cross-env NODE_ENV=development && nx serve backend --configuration=development
33 verbose exit 1
```

### Environment

```
  Node : 15.5.0
  OS   : darwin x64
  npm  : 7.3.0
  
  nx : 11.2.10
  @nrwl/angular : 11.2.7
  @nrwl/cli : 11.1.5
  @nrwl/cypress : 11.1.5
  @nrwl/devkit : 11.2.7
  @nrwl/eslint-plugin-nx : 11.1.5
  @nrwl/express : 11.1.5
  @nrwl/jest : 11.1.5
  @nrwl/linter : 11.2.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.1.5
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.5
  @nrwl/web : Not Found
  @nrwl/workspace : 11.1.5
  typescript : 4.0.5
```

**Comment by Akxe** [comment] 2021-03-08 14:01
This started to happen to me now too. I am no version `11.4.0`

**Comment by bekos** [comment] 2021-03-13 16:58
@cwqt I'm a bit confused about the steps that  reproduce the issue. Can you please elaborate on this? Even better if you can provide a repo that reproduces the issue 😃 
Generating an express application with `nx generate @nrwl/express:application` doesn't produce any `index.ts` file 🤔

**Comment by bekos** [comment] 2021-03-22 14:29
Closing as I cannot understand/reproduce the issue, but feel free to reopen in case you think this is still relevant and have more info about it.

**Closed by bekos** 2021-03-22 14:29 UTC
Labels: scope: node, type: bug

**Comment by OysteinAmundsen** [comment] 2022-02-16 11:31
I've managed to narrow it down. I updated the following group of packages in order, building my app for each new group of upgrade (_that killed a lot of time, I can tell you..._):
```json
    "@angular/cdk":                      "13.1.3", => "13.2.2"
    "@angular/material":                 "13.1.3", => "13.2.2"

    "@angular/common":                   "13.1.3", => "13.2.2"
    "@angular/compiler":                 "13.1.3", => "13.2.2"
    "@angular/core":                     "13.1.3", => "13.2.2"
    "@angular/forms":                    "13.1.3", => "13.2.2"

    "@angular/animations":               "13.1.3", => "13.2.2"
    "@angular/platform-browser":         "13.1.3", => "13.2.2"
    "@angular/platform-browser-dynamic": "13.1.3", => "13.2.2"

    "@angular/router":                   "13.1.3", => "13.2.2"
    "@angular/service-worker":           "13.1.3", => "13.2.2"

    "@angular/elements":                 "13.1.3", => "13.2.2"
    "@angular/cli":                      "13.1.4", => "13.2.3"

    "@angular/compiler-cli":             "13.1.3", => "13.2.3

    "@angular/language-service":         "13.1.3", => "13.2.2"

    "@typescript-eslint/eslint-plugin":  "5.10.1", => "5.10.2"
    "@typescript-eslint/parser":         "5.10.1", => "5.10.2"

    "@nrwl/angular":                     "13.5.2"  => "13.8.1"
    "@nrwl/cli":                         "13.5.2", => "13.8.1"
    "@nrwl/cypress":                     "13.5.2", => "13.8.1"
    "@nrwl/devkit":                      "13.5.2", => "13.8.1"
    "@nrwl/eslint-plugin-nx":            "13.5.2", => "13.8.1"
    "@nrwl/jest":                        "13.5.2", => "13.8.1"
    "@nrwl/linter":                      "13.5.2", => "13.8.1"
    "@nrwl/storybook":                   "13.5.2", => "13.8.1"
    "@nrwl/tao":                         "13.5.2", => "13.8.1"
    "@nrwl/workspace":                   "13.5.2", => "13.8.1"
```
It breaks only when I upgrade this package:
```json
    "@angular-devkit/build-angular":     "13.1.4", => "13.2.3"
```
When I reset to the previous version, all builds fine. So I guess the problem resides in this package. It seems as the package starts breaking from version "13.2.0".

**Comment by stefanmatar** [comment] 2022-03-10 12:42
Changing

    "@angular-devkit/build-angular":  "13.2.6", => "13.1.4"

Fixed it for us also

**Comment by OysteinAmundsen** [comment] 2022-03-17 09:47
I ended up with creating a new project from scratch (with the exact same name but in a different folder), generated all my apps and libs as they were in the old project and installed the same dependencies. 

The main difference between the two projects, were that angular.json moved from version 1 to version 2 (with individual project.json files for each app/lib). There were also some differences in tsconfig files and jest.config files and minor changes to other configs.

I still don't know why my project yielded the error message above, but after this exercise, all my dependencies are now up to date.

**Comment by batnyu** [comment] 2022-10-07 15:03
I was having the same problem. It was due to the package-lock.json still having webpack 4. So I deleted the file and npm install again.

**Comment by borserog** [comment] 2022-10-31 13:31
I was having this issue as well. I couldn't downgrade `"@angular-devkit/build-angular":     "13.1.4"` because it caused a compilation error regarding some deprecated functionality (`extractCss`).

Updating webpack to v5.74.0 did the trick for me.
