### ISSUE TITLE
nx lint doesn't expect trailing commas when parsing tsconfig.json 

### ISSUE THREAD

**Issue by Samuel-Beslogic** [nrwl/nx#10236] opened 2022-05-10 15:42 UTC
## Current Behavior
linting crashes when there's a trailing comma in tsconfig.json

## Expected Behavior
Support trailing commas in tsconfig.json. Neither TypeScript nor ESLint have issues with it

## Steps to Reproduce
Add a trailing coma in tsconfig.json. ie:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "target": "es2017",
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
    ],
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "types": [
      "jasmine",
      "node",
    ],
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictTemplates": true,
    "strictInputAccessModifiers": true,
    "strictDomEventTypes": false,
  },
}
```

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
Running `nx lint`:
```
nx.js run [project][:target][:configuration] [_..]

Run a target for a project
(e.g., nx run myapp:serve:production).

You can also use the infix notation to run a target:
(e.g., nx serve myapp --configuration=production)

You can skip the use of Nx cache by using the --skip-nx-cache option.

Options:
      --version        Show version number                                                                                                 [boolean]
      --prod           Use the production configuration                                                                   [boolean] [default: false]
  -c, --configuration  Target configuration                                                                                                 [string]
      --project        Target project                                                                                                       [string]
      --output-style   Defines how Nx emits outputs tasks logs                          [string] [choices: "dynamic", "static", "stream", "compact"]

{
  stack: 'Error: ValueExpected in C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\tsconfig.json at position 323\n' +
    '    at parseJson (C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\utils\\json.js:30:15)\n' +
    '    at readJsonFile (C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\utils\\fileutils.js:26:37)\n' + 
    '    at readRootTsConfig (C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\project-graph\\build-project-graph.js:233:45)\n' +
    '    at C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\project-graph\\build-project-graph.js:40:30\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\tslib\\tslib.js:117:75\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.__awaiter (C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\tslib\\tslib.js:113:16)\n' +
    '    at buildProjectGraphUsingProjectFileMap (C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\project-graph\\build-project-graph.js:34:20)\n' +
    '    at C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\node_modules\\nx\\src\\daemon\\server\\project-graph-incremental-recomputation.js:145:126',
  message: 'ValueExpected in C:\\Users\\SamuelTherrien\\Projects\\Beslogic.Activities.FrontEnd\\tsconfig.json at position 323\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}
```
Running `eslint` with `@nrwl/nx/enforce-module-boundaries` rule:
```
Oops! Something went wrong! :(

ESLint: 8.12.0

Error: Error while loading rule '@nrwl/nx/enforce-module-boundaries': ValueExpected in JSON at position 323
Occurred while linting C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\decorate-angular-cli.js
    at parseJson (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\nx\src\utils\json.js:30:15)
    at TargetProjectLocator.getRootTsConfig (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\nx\src\utils\target-project-locator.js:137:42)
    at new TargetProjectLocator (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\nx\src\utils\target-project-locator.js:19:30)
    at create (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\@nrwl\eslint-plugin-nx\src\rules\enforce-module-boundaries.js:106:43)
    at Object.create (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\@typescript-eslint\utils\dist\eslint-utils\RuleCreator.js:42:20)
    at createRuleListeners (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\eslint\lib\linter\linter.js:922:21)
    at C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\eslint\lib\linter\linter.js:1104:31
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\eslint\lib\linter\linter.js:1041:34)
    at Linter._verifyWithoutProcessors (C:\Users\SamuelTherrien\Projects\Beslogic.Activities.FrontEnd\node_modules\eslint\lib\linter\linter.js:1389:31)
```

### Environment
```
   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.4.1

   nx : 14.1.4
   @nrwl/angular : 14.1.4
   @nrwl/cypress : 14.1.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.4
   typescript : 4.4.4
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
         @ngneat/transloco: 2.23.5
```

**Comment by AgentEnder** [comment] 2022-05-10 19:00
I assigned this to `scope:linter` since its cropping up during the lint rule validation, but, this is caused by us using native JSON.parse from `node` to read in JSON. Since trailing commas are not supported in the json spec, similar to single quotes, we don't currently support. them.

If a tool such as JSON5 gets more support, or gets native implementations, or just overall gets a bit faster we may reevaluate at that time. In the meantime, this isn't really a bug with our implementation, so I'm going to close it out.

**Closed by AgentEnder** 2022-05-10 19:00 UTC
Labels: type: bug, scope: linter

**Comment by Samuel-Beslogic** [comment] 2022-05-12 17:05
Understandable. As long as this as been brought to your attention and this can be re-evaluated later as technology moves forward :)

**Comment by ehaynes99** [comment] 2022-07-31 22:39
See my comment here: https://github.com/nrwl/nx/issues/10393#issuecomment-1200514804

Since TS does supply a parser, I'm not sure that it's accurate to say that it isn't a bug with the implementation.

**Comment by Zamiell** [comment] 2022-07-31 22:45
> this isn't really a bug with our implementation

If you are parsing a file called "tsconfig.json" as JSON, then **it is** a bug in the implementation, because it is not a JSON file! (Contrary to what the ".json" extension would have you believe... but blame Microsoft for that. =p)
