### ISSUE TITLE
Cannot migrate to Angular 12 from 11 due to 'webpack-browser'

### ISSUE THREAD

**Issue by roddc** [nrwl/nx#5937] opened 2021-06-09 09:14 UTC
## Current Behavior

I am trying to update Angular from 11 to 12, and I ran  `nx migrate latest # same as nx migrate @nrwl/workspace@latest`, then `npm i` && `nx migrate --run-migrations=migrations.json`, but I got two errors related to webpack-browser:

- Running migration update-webpack-browser-config
 Cannot convert undefined or null to object
- Running migration convert-webpack-browser-build-target-to-delegate-build
Cannot convert undefined or null to object
I am using `@angular-builders/custom-webpack` as builder.

**Comment by leosvelperez** [comment] 2021-06-09 09:56
Thanks for reporting this!

I'll close this one since it's a duplicate of https://github.com/nrwl/nx/issues/5706. You can see [this comment](https://github.com/nrwl/nx/issues/5706#issuecomment-843975879) for the cause of the issue and a resolution.

**Closed by leosvelperez** 2021-06-09 09:56 UTC
Labels: type: bug
