### ISSUE TITLE
After Nx18 upgrade, our custom plugins runs in infinite loop.

### ISSUE THREAD

**Issue by rexkenley** [nrwl/nx#22443] opened 2024-03-21 18:13 UTC
### Current Behavior

When I run our custom plugins, it gets stuck in an infinite loop and consoles out this strange message. We have applied both useInferencePlugins: false and .env NX_ADD_PLUGINS=false

![image](https://github.com/nrwl/nx/assets/10548251/7218a3fb-4106-477e-87f4-aadcc390340c)

### Expected Behavior

Execute the plugin successfully to the end.

### Steps to Reproduce

I am looking for advice on how to troubleshoot this issue. I couldn't find any on the web.

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 10.2.4
 
nx                 : 18.1.2
@nx/js             : 18.1.2
@nx/jest           : 18.1.2
@nx/linter         : 18.1.2
@nx/eslint         : 18.1.2
@nx/workspace      : 18.1.2
@nx/cypress        : 18.1.2
@nx/devkit         : 18.1.2
@nx/eslint-plugin  : 18.1.2
@nx/express        : 18.1.2
@nx/next           : 18.1.2
@nx/node           : 18.1.2
@nx/react          : 18.1.2
@nx/rollup         : 18.1.2
@nx/storybook      : 18.1.2
@nrwl/tao          : 18.1.2
@nx/web            : 18.1.2
@nx/webpack        : 18.1.2
typescript         : 5.4.3
---------------------------------------
Community plugins:
@hcltech/powerplatform-catalog      : 2.2.0
@hcltech/powerplatform-dataverse    : 2.7.1
@hcltech/powerplatform-init         : 3.0.0
@hcltech/powerplatform-pac          : 3.0.0
@hcltech/powerplatform-pcf          : 3.2.3
@hcltech/powerplatform-react        : 1.0.1
@hcltech/powerplatform-solution     : 3.1.0
@hcltech/powerplatform-web-resource : 3.0.3
```

### Failure Logs

```shell
Are there any logs that would capture that weird text?
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by saltman424** [comment] 2024-03-21 20:56
I have the same behavior with the `@angular-devkit/build-angular` executor also with `useInferencePlugins: false` and on Windows

The result is inconsistent but generally gets stuck in an infinite loop and logging a very similar message `;[[14;1R`

**Comment by ComradeCow** [comment] 2024-03-22 22:15
We've seen the same symptom with `@nx/vite:test`, and a custom executor in our plugin from users on Windows.

**Comment by FrozenPandaz** [comment] 2024-03-27 19:04
This is unrelated to the plugins. Closing this issue as a duplicate of https://github.com/nrwl/nx/issues/22358. Please follow there for updates.

**Closed** 2024-03-27 21:28 UTC
Labels: type: bug
