### ISSUE TITLE
TypeError: validator is not a function

### ISSUE THREAD

**Issue by Teebo** [nrwl/nx#17839] opened 2023-06-28 17:05 UTC
### Current Behavior

Running an Angular app in the workspace using `nx serve app_name`

```
/Users/user/angular_app/node_modules/@angular-devkit/architect/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

TypeError: validator is not a function
    at /Users/user/angular_app/node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:219:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project app_name failed

   Failed tasks:
   
   - app_name:serve:development
```

### Expected Behavior

The application be served

### Steps to Reproduce

1. After moving my workspace from an Ubuntu to a Mac device
2. Upgrade NodeJS from v14 to v16
3. Installed workspace packages
4. Run `nx serve app_name`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.20.1
   OS   : darwin x64
   npm  : 8.19.4
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/angular           : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/nest              : 15.8.7
   @nrwl/node              : 15.8.7
   @nrwl/storybook         : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @datorama/akita             : 7.1.1
   @nguniversal/express-engine : 15.2.0
   schematics-scss-migrate     : 1.3.15
   @nguniversal/builders       : 15.2.0
   @storybook/angular          : 6.5.16
```

### Failure Logs

```shell
/Users/user/angular_app/node_modules/@angular-devkit/architect/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

TypeError: validator is not a function
    at /Users/user/angular_app/node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:219:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project app_name failed

   Failed tasks:
   
   - app_name:serve:development
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This issue could be caused package version conflicts or something else.
I am posting here in case someone can help.
I am stuck.

**Comment by leosvelperez** [comment] 2023-06-29 08:39
Thanks for reporting this!

Could you run `npm ls @angular-devkit/architect` and share the output here? As you guessed, this looks like a version conflict between that package and the rest of the `@angular-devkit/*` packages. It normally happens when using other packages that might depend on it as well and the package manager ends up resolving a different version. The issue is most likely resolved by adding `@angular-devkit/architect` to your `devDependencies` with the correct version.

**Comment by Teebo** [comment] 2023-06-29 09:14
Hi, 

Thanks for the comment. Please see output for `npm ls @angular-devkit/architect` below

├─┬ @angular-devkit/build-angular@15.2.4
│ ├── @angular-devkit/architect@0.1502.4
│ └─┬ @angular-devkit/build-webpack@0.1502.4
│   └── @angular-devkit/architect@0.1502.4
├─┬ @angular/cli@14.1.3
│ └── @angular-devkit/architect@0.1401.3
├─┬ @nguniversal/builders@15.2.0
│ └── @angular-devkit/architect@0.1502.9
└─┬ @storybook/angular@6.5.16
  └── @angular-devkit/architect@0.1601.2

**Comment by leosvelperez** [comment] 2023-06-29 09:33
This is probably the culprit:

```
└─┬ @storybook/angular@6.5.16
└── @angular-devkit/architect@0.1601.2
```

Could you try adding `"@angular-devkit/architect": "0.1502.4"` to your `devDependencies` and run the migrations again?

If that doesn't work, could you paste your `package.json` contents? At least the `dependencies` and `devDependencies`? I might be able to reproduce the issue with that.

**Comment by Teebo** [comment] 2023-06-29 10:21
@leosvelperez thanks 🙏  a lot that did the trick.
Out of curiosity, from your experience, what would be something to try to lock the dependencies such that we have fewer npm/packages issue like these? Just in general

**Comment by leosvelperez** [comment] 2023-06-29 10:31
I'm glad you solved your issue 👍🏻 

> Out of curiosity, from your experience, what would be something to try to lock the dependencies such that we have fewer npm/packages issue like these? Just in general

It's something we've considered doing (we provide migrations for it), but we ultimately decided not to add it to the `package.json` because that package is considered "internal" by the Angular team and most of the time, the package managers resolve the correct version.

That said, it's not set in stone and it's definitely something we keep evaluating and we might change that in the future.

**Closed by leosvelperez** 2023-06-29 10:31 UTC
Labels: type: bug, blocked: more info needed, scope: angular
