### ISSUE TITLE
nx g component v14.0.3 doesn't work

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10040] opened 2022-04-28 12:54 UTC
## Current Behavior
> nx g c test
`Cannot read properties of undefined (reading 'exists')`

## Expected Behavior
a new shiny component should be generated

### Environment

Node : 18.0.0
OS   : darwin arm64
npm  : 8.7.0
nx : 14.0.3
@nrwl/angular : 14.0.3
@nrwl/cypress : 14.0.3
@nrwl/devkit : 13.1.3
@nrwl/eslint-plugin-nx : 14.0.3
@nrwl/jest : 14.0.3
@nrwl/linter : 14.0.3
@nrwl/nx-cloud : 14.0.0
@nrwl/storybook : 14.0.3
@nrwl/workspace : 14.0.3
typescript : 4.6.3
rxjs : 8.0.0-alpha.3

Community plugins:
     @ngrx/component-store: 13.1.0
     @ngrx/effects: 13.1.0

**Comment by leosvelperez** [comment] 2022-04-28 13:03
Thanks for reporting this!

Please note this is a duplicate of https://github.com/nrwl/nx/issues/9869 which has already been fixed on https://github.com/nrwl/nx/pull/10038. Keep an eye on the releases to know when the fix is out.

In the meantime, you can run `nx g component test` instead of `nx g c test`.

**Closed** 2022-04-28 13:03 UTC
Labels: type: bug, status: closed / duplicate

**Comment by e-oz** [comment] 2022-04-28 13:08
Thanks for a quick reply!

I've tried `nx g component test`:
```bash
oz@Avalon uml-canvas % nx g component test            
      
Error: Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.
    at findModule (/Users/oz/repos/scs/model-designer-ui/node_modules/@schematics/angular/utility/find-module.js:76:11)
    at findModuleFromOptions (/Users/oz/repos/scs/model-designer-ui/node_modules/@schematics/angular/utility/find-module.js:25:38)
    at /Users/oz/repos/scs/model-designer-ui/node_modules/@schematics/angular/component/index.js:104:66
Could not find an NgModule. Use the '--skip-import' option to skip importing in NgModule.

oz@Avalon uml-canvas % nx g component test --skip-import

'skipImport' is not found in schema

oz@Avalon uml-canvas % nx g component test --skip-import=true

'skipImport' is not found in schema
```

**Comment by leosvelperez** [comment] 2022-04-28 13:16
Could you provide a repo with a minimal reproduction of that issue? Or at least some reproduction steps?

I ran `nx g component test` on a fresh Nx workspace and it generated the component successfully.

**Comment by e-oz** [comment] 2022-04-28 13:18
I think it's because you are not following the “scam” approach in that repo :) 

No, sorry, have no time right now. And I mostly use nx g scam anyway :)
