### ISSUE TITLE
"implicitDependencies" option adds every project as implicit dependency

### ISSUE THREAD

**Issue by JesseZomer** [nrwl/nx#23868] opened 2024-05-21 13:39 UTC
### Current Behavior

As of Nx version 18.3.0 I used to be able to set the option `implicitDependencies` in `project.json` and do 
```
  "implicitDependencies": ["!project-Z"],
``` 
However since Nx version 19 this adds all other unrelated projects as an implicit dependency. See the example repo for an minimal reproduction

### Expected Behavior

Setting  `"implicitDependencies": ["!project-Z"]` should not add every other library as an implicit dependency

### GitHub Repo

https://github.com/JesseZomer/nx-implicit-deps-bug

### Steps to Reproduce

1. run nx-graph
2. see that there is an implicit dependency on "unrelated-library-2"

that's not supposed to be there because the setting is as follows: `  "implicitDependencies": ["!unrelated-libary-1"],`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.13.1
OS     : darwin-arm64
npm    : 10.5.2

nx (global)        : 19.0.4
nx                 : 19.0.4
@nx/js             : 19.0.4
@nx/jest           : 19.0.4
@nx/linter         : 19.0.4
@nx/eslint         : 19.0.4
@nx/workspace      : 19.0.4
@nx/angular        : 19.0.4
@nx/devkit         : 19.0.4
@nx/eslint-plugin  : 19.0.4
@nx/playwright     : 19.0.4
@nrwl/tao          : 19.0.4
@nx/web            : 19.0.4
@nx/webpack        : 19.0.4
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

with   "implicitDependencies": ["!unrelated-libary-1"],
<img width="483" alt="image" src="https://github.com/nrwl/nx/assets/738579/c1e67a75-e487-4887-ac6a-91c915f258da">

without implicitDependencies option:
<img width="845" alt="image" src="https://github.com/nrwl/nx/assets/738579/4abd484d-3505-43be-b6f8-0697b1848fe9">

**Comment by FrozenPandaz** [comment] 2024-05-21 21:32
This is a duplicate of https://github.com/nrwl/nx/issues/23458 the fix will be released soon.

**Closed by FrozenPandaz** 2024-05-21 21:32 UTC
Labels: type: bug
