### ISSUE TITLE
Throws an error `Cannot read property 'schematics' of undefined` when extended by a custom schematics

### ISSUE THREAD

**Issue by adrianbarwicki** [nrwl/nx#3497] opened 2020-08-11 10:01 UTC
## Current Behavior
NX workspace schematics `@nrwl/schematics@8.12.11` throws the following error when it is extended by a custom schematics installed in node_modules:
```
Cannot read property 'schematics' of undefined
```

## Expected Behavior
We expect that the schematics correctly generates the default files for an NX lib.

## Steps to Reproduce
I created a minimal wrapper around the schematics ( a custom schematics extending the  `@nrwl/schematics`).
https://github.com/adrianbarwicki/mvp-buggy-lib-schematics

You can see that the custom schematics does nothing else but just calls the nrwl schematics here:
https://github.com/adrianbarwicki/mvp-buggy-lib-schematics/blob/master/mvp-buggy-lib-schematics/index.js#L16

Then, in this repo, the above schematics is installed as an npm module:
https://github.com/adrianbarwicki/mvp-buggy-starterkit

When running `ng g mvp-buggy-lib-schematics:mvp-buggy-lib` you will see the following error:
```
Cannot read property 'schematics' of undefined
```

More exact steps are described in the example repos above.

### Environment

```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 8.11.1
  @nrwl/cli : 8.12.11
  @nrwl/cypress : 8.11.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.1
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 8.12.11
  @nrwl/web : Not Found
  @nrwl/workspace : 9.5.1
  typescript : 3.5.3
```

### Related
A similar issue has been created here https://github.com/nrwl/nx/issues/3118#issue-631498358 by @philly-vanilly.

**Comment by adrianbarwicki** [comment] 2020-08-11 10:25
The fix for this behaviour is to remove `workspace.json`.

**Comment by vsavkin** [comment] 2020-08-13 19:19
Although not strictly speaking, I think this is a duplicate of https://github.com/nrwl/nx/issues/3118#issue-631498358. I'm going to reference the issue there.

I'm going to close this one cause fixing #3118 will fix this one as well.

**Closed by vsavkin** 2020-08-13 19:19 UTC
Labels: type: bug
