### ISSUE TITLE
Angular language service in vscode not working with nx 17.1

### ISSUE THREAD

**Issue by atsjo** [nrwl/nx#20163] opened 2023-11-09 20:42 UTC
### Current Behavior

After upgrading to nx 17.1.1 the Angular language service extension stopped working. The issue seems to be with typescript 5.2.2, as it works if downgrading to ts 5.1.6. However, the language service extension works fine with a clean cli project and typescript 5.2.2, so the issue is somehow related to the way nx organizes the projects...

The same goes for nx 17.0.x, so this problem was probably not introduced with nx 17.1 (except from the typescript migration itself)

### Expected Behavior

Angular language service works with nx and latest typescript...

### Steps to Reproduce

1. Upgrade to typescript 5.2.2 (or just migrate to latest nx) in a monorepo with angular
2. Try using Angular language service when editing a template

### Nx Report

```shell
Node   : 20.9.0
   OS     : win32-x64
   pnpm   : 8.10.2
   
   nx                 : 17.1.1
   @nx/js             : 17.1.1
   @nx/jest           : 17.1.1
   @nx/linter         : 17.1.1
   @nx/eslint         : 17.1.1
   @nx/workspace      : 17.1.1
   @nx/angular        : 17.1.1
   @nx/cypress        : 17.1.1
   @nx/devkit         : 17.1.1
   @nx/esbuild        : 17.1.1
   @nx/eslint-plugin  : 17.1.1
   @nrwl/tao          : 17.1.1
   @nx/web            : 17.1.1
   @nx/webpack        : 17.1.1
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   angular-calendar : 0.31.0
```

### Failure Logs

```shell
[Error - 9:27:22 PM] No config file for d:/repos/teve-no/task4s/libs/teve/angular/src/lib/components/calendar-integration/calendar-integration.component.html
[Error - 9:27:22 PM] No config file for d:/repos/teve-no/task4s/libs/teve/angular/src/lib/components/calendar-integration/calendar-integration.component.html
[Error - 9:27:22 PM] No config file for d:/repos/teve-no/task4s/libs/teve/angular/src/lib/components/calendar-integration/calendar-integration.component.html
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

https://github.com/angular/vscode-ng-language-service/issues/1959

**Comment by atsjo** [comment] 2023-11-11 00:44
will be fixed by https://github.com/angular/vscode-ng-language-service/pull/1972

**Comment by leosvelperez** [comment] 2023-11-13 09:05
Thanks for reporting this!

I'm going to close this issue since it's an issue with the actual Language Service, and it's not caused by Nx. Please follow the fix in the Language Service repo for updates.

**Closed by leosvelperez** 2023-11-13 09:05 UTC
Labels: type: bug, scope: angular
