### ISSUE TITLE
Update to expo 49 / react-native 0.72

### ISSUE THREAD

**Issue by sem4phor** [nrwl/nx#17981] opened 2023-07-06 06:57 UTC
## Description
When using nx expo I want to use the latest expo version which is from today 49 and react native 0.72.
I guess the peer dependencies have to be upgraded and react native 72 introduced some monorepo featues maybe some things in the plugin need to be refactored because of that...

Maybe it is also worth considering adding expo-router v2 to the app (its the recommended routing solution for expo now) generator which was also released today.

## Motivation
Because expo 48 will be deprecated in 3 months and RN 72 solves huge performance issues and adds new monorepo features.

**Comment by enchorb** [comment] 2023-07-17 20:32
+1 Any ETA here? RN 0.72 also fixes performance regressions in 0.71

**Comment by necmettindev** [comment] 2023-07-18 16:05
up

**Comment by Eirmas** [comment] 2023-07-18 19:22
+1 bump

**Comment by Bengejd** [comment] 2023-07-28 16:17
+1 bumped

**Comment by triptu** [comment] 2023-08-03 08:12
This seems to be closed now with #17810 (released in 16.6.0).

**Comment by xiongemi** [comment] 2023-09-21 20:57
closing this issue since the upgrade is done in 16.6.0

**Closed by xiongemi** 2023-09-21 20:57 UTC
Labels: type: feature, scope: react-native
