### ISSUE TITLE
Migration fails with Provide the correct package name and version.

### ISSUE THREAD

**Issue by heddendorp** [nrwl/nx#6567] opened 2021-07-31 18:09 UTC
## Current Behavior

When running `nx migrate` from vs code it fails with a cryptic message

## Expected Behavior

The command works

## Steps to Reproduce

1. Clone https://github.com/heddendorp/tumi-app/tree/refactor/nx
2. install deps
3. run `nx migrate`

### Failure Logs

```
> Executing task: nx migrate <

Provide the correct package name and version. E.g., @nrwl/workspace@9.0.0.
C:\Users\hedde\code\tumi-app\node_modules\yargs\build\lib\yargs.js:1132
                throw err;
                ^

Error: Command failed: C:\Users\hedde\AppData\Local\Temp\tmp-17592-JTAriy8Bc3w6\node_modules\.bin\tao migrate
    at checkExecSyncError (child_process.js:643:11)
    at Object.execSync (child_process.js:679:15)
    at Object.handler (C:\Users\hedde\code\tumi-app\node_modules\@nrwl\workspace\src\command-line\nx-commands.js:89:25)
    at Object.runCommand (C:\Users\hedde\code\tumi-app\node_modules\yargs\build\lib\command.js:196:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\hedde\code\tumi-app\node_modules\yargs\build\lib\yargs.js:1043:55)
    at Object.get [as argv] (C:\Users\hedde\code\tumi-app\node_modules\yargs\build\lib\yargs.js:986:25)
    at Object.initLocal (C:\Users\hedde\code\tumi-app\node_modules\@nrwl\cli\lib\init-local.js:25:79)
    at Object.<anonymous> (C:\Users\hedde\code\tumi-app\node_modules\@nrwl\cli\bin\nx.js:43:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12548,
  stdout: null,
  stderr: null
}
```

### Environment

```
>  NX  Report complete - copy this into the issue template

  Node : 14.17.3
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.6.2
  @nrwl/cli : 12.6.2
  @nrwl/cypress : 12.6.2
  @nrwl/devkit : 12.6.2
  @nrwl/eslint-plugin-nx : 12.6.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.2
  @nrwl/linter : 12.6.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.6.3
  @nrwl/nx-cloud : 12.3.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.2
  @nrwl/storybook : 12.6.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment] 2021-08-02 15:21
Thanks for reporting this!

This is the expected behavior. As the error message says, you have to provide the package name and version. This can be done by running the migration with one of the following options:
- The version you want to migrate to (e.g. `nx migrate latest` or `nx migrate 12.6.3`). With this, the package will default to `@nrwl/workspace`, effectively running a migration for you whole workspace.
- The package (e.g. `nx migrate @nrwl/workspace`). With this, the version will default to `latest`.
- The package and the version (e.g. `nx migrate @nrwl/workspace@12.6.3`).

Closing this since it is working as expected.

**Closed by leosvelperez** 2021-08-02 15:21 UTC
Labels: type: bug
