### ISSUE TITLE
 Unable to create nodes for app using plugin @nx/webpack/plugin

### ISSUE THREAD

**Issue by JoelDigbeu** [nrwl/nx#22016] opened 2024-02-27 13:12 UTC
### Current Behavior

I get the following error when i try to build my app using nx/webpack locally and in my Github Action jobs:

` Inner Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (node:internal/validators:162:11)
      at Object.join (node:path:1175:7)`

`Unable to create nodes for apps/gateway/webpack.config.js using plugin @nx/webpack/plugin. `

### Expected Behavior

I expect a successful build in order to complete my github action job using `@nx-tools/nx-container:build`

### Steps to Reproduce

1. Generate Nestjs app using nx/nest plugin
2. Update your generated app `project.json`

> project.json

```
{
    //...
    //...
    //...
   target: [
      "container": {
      "executor": "@nx-tools/nx-container:build",
      "dependsOn": ["build"],
      //...options
      }
    }
   ]

}

```
3. Add a basic webpack config

> webpack.config.js

```const { NxWebpackPlugin } = require('@nx/webpack')
const { join } = require('path')

module.exports = {
	output: {
		path: join(__dirname, '../../dist/apps/your-app-name'),
	},
	plugins: [
		new NxWebpackPlugin({
			target: 'node',
			compiler: 'tsc',
			main: './src/main.ts',
			tsConfig: './tsconfig.app.json',
			assets: ['./src/assets'],
			optimization: false,
			outputHashing: 'none',
			generatePackageJson: true,
		}),
	],
}
```

4. Update nx.json for inferred task
> nx.json
```
{
//...options,
plugins: [
     {
      "plugin": "@nx/webpack/plugin",
      "options": {
        "buildTargetName": "build",
        "serveTargetName": "serve",
        "previewTargetName": "preview"
      }
    },
 ]
}

```

5. Run  `(yarn | npm | pnpm) nx appName:container`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : linux-x64
pnpm   : 8.15.3

nx                 : 18.0.5
@nx/js             : 18.0.5
@nx/jest           : 18.0.5
@nx/linter         : 18.0.5
@nx/eslint         : 18.0.5
@nx/workspace      : 18.0.5
@nx/devkit         : 18.0.5
@nx/eslint-plugin  : 18.0.5
@nx/nest           : 18.0.5
@nx/node           : 18.0.5
@nx/playwright     : 18.0.5
@nx/react          : 18.0.5
@nx/remix          : 18.0.5
@nrwl/tao          : 18.0.5
@nx/vite           : 18.0.5
@nx/web            : 18.0.5
@nx/webpack        : 18.0.5
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-tools/nx-container : 5.2.0
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by WarrenBuffering** [comment] 2024-02-28 17:21
I just ran into this when using npx to generate the project (i.e. `npx nx g @nx/expo:app test-app`) but tried generating without npx (`pnpm nx g @nx/expo:app test-app`) and now the expo app is building just fine.

**Comment by gabrielbryk** [comment] 2024-03-04 22:17
I am also having this issue but its only happening when i try running nx commands from within a target
` "serve-with-env": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          {
            "command": "./runEnv.sh"
          },
          {
            "command": "nx serve frontend"
          }
        ],
        "parallel": false,
        "cwd": "apps/frontend/"
      }
    },`

**Comment by martialanouman** [comment] 2024-03-06 16:50
Hi, 
still no update on this issue?

**Comment by smasala** [comment] 2024-03-06 23:53
Happens sporadically for me `pnpm nx reset` fixes it locally but not for the CI

**Comment by smasala** [comment] 2024-03-07 22:14
The error can be fixed by updating all `webpack.js` and `webpack.config.ts` accordingly (depending on the project configurations you have).

1. setup a clean repo add create apps with the desired nx plugins (react, nest etc)
2. copy the contents of each `webpack.config.ts` and extend as needed.
    - for react applications extend `withNx` function in the webpack config with the required `tsConfig` path option
  
  ```typescript
  withNx({
    tsConfig: './tsconfig.app.json',
  }),
  ```
3. sync the `project.json` files with those out of the new repo, specifically the `build` and `serve` targets
4. same goes for any `webpack.config.js` files if you've got apps that use the `@nx/js:node` plugin

Notes:

- The error is occuring at: https://github.com/nrwl/nx/blob/46592d79128b14ca3e98d62fe78be6aed4633505/packages/webpack/src/plugins/nx-webpack-plugin/lib/compiler-loaders.ts#L57 where `options.tsConfig` is occasionally `undefined`.

**Comment by francisco-sanchez-molina** [comment] 2024-04-09 10:34
Hello! I've been investigating this problem; we have both React and Next.js applications, and the Next.js applications fail in CI. I've managed to replicate it locally with Docker, and I'm not sure if it's related to this:

https://github.com/nrwl/nx/blob/32144bb702b07eddf29ed70055dfbcbcc0f4b11c/packages/nx/src/project-graph/project-graph.ts#L303

By setting "useDaemonProcess": false in nx.json, I've made it also fail locally. However, with "useDaemonProcess": true in CI, I haven't been able to get it to work.

**Comment by Coly010** [comment] 2024-06-07 08:40
Hi all, there seems to be a mix of different issues being reported here.

Node/Nest/Express projects do not currently support Inferred Tasks with Project Crystal. That was the original issue here.
As it is not a supported feature, at least yet, I'm going to close this issue.

If others are still experiencing issues with React + Next, please open a new issue with a reproduction to allow us to investigate further.

Thank you!

**Closed by Coly010** 2024-06-07 08:40 UTC
Labels: type: bug, scope: bundlers
