### ISSUE TITLE
Library dependencies need restarting VSCode

### ISSUE THREAD

**Issue by manoharnikkam** [nrwl/nx#4351] opened 2020-12-18 22:36 UTC
## Current Behavior
I've created a 
1. empty workspace
2. create Angular UI project
3. create Angular library for material
4. verified tsconfig.base.json has the library listed in "paths"
5. imported library from step 3 into the UI, created in step 1.
6. create a component, try adding markup in HTML file of the component. Material components get wiggly lines. The lines disappear if I close VS Code and reopen
![image](https://user-images.githubusercontent.com/8573069/102663851-3d306f80-4147-11eb-84a9-62f5ae3fc388.png)
![image](https://user-images.githubusercontent.com/8573069/102666981-dd899280-414d-11eb-8778-8dc04a1b7a43.png)

## Expected Behavior

names should resolve.

## Steps to Reproduce

Create a 
1. empty workspace
`npx create-nx-workspace@latest --linter=eslint --style=scss --no-nx-cloud`
2. add Angular UI project
`nx generate @nrwl/angular:application --name=customer-portal --style=scss --linter=eslint --routing --strict --tags=customerfacing`
3. add Angular library for material
`nx generate @nrwl/angular:library --name=material --style=scss --linter=eslint --tags=material --export`
4. verify tsconfig.base.json has the library listed in "paths"
5. imported library from step 3 into the UI, created in step 1 and add following markup. You will notice wiggly lines alerting about adding "CUSTOM_ELEMENTS_SCHEMA" to the current module.
`<mat-card>Simple card</mat-card>`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 15.4.0
  OS   : darwin x64
  npm  : 7.0.15
  
  nx : Not Found
  @nrwl/angular : 11.0.9
  @nrwl/cli : 11.0.9
  @nrwl/cypress : 11.0.9
  @nrwl/devkit : 11.0.9
  @nrwl/eslint-plugin-nx : 11.0.9
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.9
  @nrwl/linter : 11.0.9
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.9
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.9
  typescript : 4.0.5

**Comment by vsavkin** [comment] 2020-12-19 18:28
Thank you for submitting the issue.

Unfortunately, there is not much we can do about this as this is an issue with the typescript language service. You don't have to restart VSCode though, you can open a command pallet and run "restart language service". This should do the trick.

I'm going to close this cause there is nothing we can do. The issue isn't unique to Nx--it's the same for everyone who is adding path mappings. And we've already let the typescript team know about this.

**Closed by vsavkin** 2020-12-19 18:28 UTC
Labels: type: bug

**Comment by manoharnikkam** [comment] 2020-12-19 20:25
Thank you @vsavkin. I'm newbie to this. I'm enjoying learning and exploring Nx.
