### ISSUE TITLE
NestJS: Provide builders for ts-node (serve) and standard tsc (build) - options to exclude webpack

### ISSUE THREAD

**Issue by iangregsondev** [nrwl/nx#1230] opened 2019-04-05 06:06 UTC
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

Hi, I wonder if its possible to provide builders for the following scenerios.

NG SERVE - using ts-node, currently libraries added via external tsconfig paths are not able to be debugged using vs code for example - ts node supports use of tsconfig paths and i have another project - non nx - and debuggging seems to work there. I also think it would be easier for debugging nestjs applications. Retaining full use of the NG CLI but underneath running ts-node.

NG BUILD - using standard TSC to build the projest into the dist, so you end up with multiple .js files - not a bundle. I having quite a few issues with the project working once its built and working from the dist directory. Having separate files would make it easy to debug and understand. In the bundle I dont know whats been added or not. I have an open issue on nest for a similar problem.  https://github.com/nestjs/nest/issues/1937

I just thinking giving these options to developers would be the icing on the cake :-) Nestjs using ts-node while NG SERVE and using standard tsc (typescript compiler) to multiple files on NG BUILD

## Current Behavior

Everythingis bundled into a bundle file, works great for angular but nestjs would benefit from the above.

### Context

Please provide any relevant information about your setup:

- version of Nx used 7.7

u.

**Comment by FrozenPandaz** [comment] 2019-04-05 21:32
> currently libraries added via external tsconfig paths are not able to be debugged using vs code for example

Can you elaborate on this?

We can create these, however, I think webpack offers some other features such as replacements, working with other types of files.

**Comment by appsolutegeek** [comment] 2019-04-06 10:35
Sure .... so I have some external libraries that I publish to a private npm repository... They are in a different location. While I am developing, I use tsconfig paths so I can test my libraries integrating with nest. So I attach a vs code debugger i.e

```
  "configurations": [
    {
      "type": "node",
      "request": "attach",
      "name": "Vault-API",
      "port": 5880,
      "sourceMaps": true,
      "cwd": "${workspaceFolder}/vault-api",
      "restart": true
    }
  ]
```

and sure enough, i can place break points in my code that is under the api/apps.

I also place a breakpoint in one of my libraries located under nest-common, at run time, i can debug my ts files but when it gets to the libraries then(nest-common) then the JS file is being debugged not the TS file.

I hope that makes sense. here is the example directory structure

![image](https://user-images.githubusercontent.com/2370364/55668288-28735180-5868-11e9-935d-9f83fd9a4de0.png)

and here is my main tsconfig, as you can see i am pointing one of the libs with scope PRIME to nest-common, this is temporary while i develop it

```
 "paths": {
      "*": ["./@types/*"],
      "@vault-ws/feature/health": ["libs/feature/health/src"],
      "@prime/nest-correlation": ["../nest-common/libs/nest-correlation/src/index.ts"],
      "@vault-ws/feature/security": ["libs/feature/security/src"],
```

Maybe its because it can't find the sourcemaps at runtime ?

Not sure.

**Comment by xmlking** [comment] 2019-04-09 17:11
@FrozenPandaz offering `ts-node/TSC` based `builders`  will fulfill needs for most of the nodeJS frameworks. we still love   `replacements` for config. i guess we can get this capability without WebPack.  bundling can be opt-in option, if developers want to bundle with `webpack` or `rollup`

**Comment by abdoolly** [comment] 2019-10-25 04:04
Hello guys I think I have made just the package that you needed 
This is a builder that uses ts-node , nodemon , and tsc to give you two type of builders for dev and production checkout it out here
https://www.npmjs.com/package/ts-node-builder/v/1.0.2

Thanks and hope it helps :D

**Comment by dopsonbr** [comment] 2020-01-08 01:50
@abdoolly  I appreciate your work and thanks for providing the alternate builder.

@vsavkin @FrozenPandaz 
Has there been any progress on allowing tsc based builders? I can make my project work using the alternate builder but it feels like this functionality really belongs in the NX builder.

My use case is NX workspace with an Angular frontend and NestJS backend. Both applications must be deployed to an on-prem installation of Pivotal CloudFoundry. I also must use the nodejs buildpack and cannot supply a custom docker image.

The issue is the webpack based builder is incompatible with Cloudfoundry's nodejs buildpack.
I have tried every combination of tsconfig settings and the modules will not load properly [1]. I would be happy to try another combination if you have any suggestions. But AFAIK the tsc compiler must have these options [2] and the webpack builder disabled.

When testing a project that uses only the nest-cli, the webpack based build can easily be disabled and everything "just works". Providing the ability to select NestJS's tsc builder provides a much better developer experience compared to installing the alternate builder.

 The example based on the NestJS cli monorepo config can be found [here](https://github.com/dopsonbr/nestjs-monorepo-cloudfoundry-example.git)
 and the nx workspace using the ts-node-builder is [here](https://github.com/dopsonbr/nx-workspace-nestjs-cloudfoundry-example.git).

1. webpack based NestJS startup error
```
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR internal/modules/cjs/loader.js:800
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     throw err;
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     ^
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR Error: Cannot find module '/home/vcap/app/dist/apps/hello/main.js'
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR     at internal/main/run_main_module.js:17:11 {
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR   code: 'MODULE_NOT_FOUND',
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR   requireStack: []
   2020-01-07T18:54:34.00-0500 [APP/PROC/WEB/0] ERR }
```
2. tsconfig.json
``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "esModuleInterop": true,
    ...
    }
}
```

**Comment by gperdomor** [comment] 2020-02-07 02:31
@vsavkin @FrozenPandaz any progress or plan to include this kind of builder in NX?, exists some problems with NestJS + TypeORM and webpack, like https://github.com/nrwl/nx/issues/803 and https://github.com/nrwl/nx/issues/1393 for example

**Comment by ashbrener** [comment] 2020-03-13 15:34
This is also a critical requirement for modules that dynamically import the contents of entire directories ... example node express with routing-controllers

**Comment by khayalan-mathew** [comment] 2020-03-28 21:23
Having similar issues using dynamic imports in Node.js applications. Using webpack causes an insane amount of issues, due to replacing imports with his own internal methods. A more simplistic TSC based builder would be really nice, like it is available for the library schematic, just for applications with devmode, inspect, etc.

**Comment by abdoolly** [comment] 2020-03-29 02:26
Hello @khayalan-mathew 
you can check out my builder  [here](https://github.com/abdoolly/ts-node-builder) made exactly for the issue you are having
and if you find anything missing or not working as expected please raise me an issue,
Thanks.

**Comment by vladimir-barsuchenko** [comment] 2020-05-22 10:59
@FrozenPandaz @xmlking @iangregsondev 

It could be related, but is there any chance to use `.ts` extension for  `"customServerPath": "next.server.ts"` instead of `.js`
to make it work?

**Comment by studds** [comment] 2020-05-27 06:25
For what it's worth, I've had success using [run-commands](https://nx.dev/angular/workspace/builders/run-commands-builder) with [ts-node-dev](https://github.com/whitecolor/ts-node-dev), or tsc directly. At least in some use cases, I haven't felt the need for a specialised builder. This might be an option that works in some cases, although I'm not denying the ergonomics of specialised builders.

Example:

```
    ...
    "serve": {
        "builder": "@nrwl/workspace:run-commands",
        "options": {
            "parallel": false,
            "commands": [
                {
                    "command": "npm run ts-node-dev apps/demo/src/app/main.ts"
                }
            ]
        }
    }
   ...
```

And in package.json, for convenience:

```json
{
    "scripts": {
        "ng": "ng",
        "ts-node-dev": "TS_NODE_PROJECT=tsconfig.node.json ts-node-dev -r tsconfig-paths/register"
    }
}
```

tsconfig.node.json contains:

{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true
    }
}

**Comment by tonivj5** [comment] 2021-02-03 10:24
Up

**Comment by tonivj5** [comment] 2021-03-29 15:16
> Up

**Comment by tonivj5** [comment] 2021-12-05 08:07
> > Up
> 
>

**Comment by alexbatis** [comment] 2022-03-05 01:39
+1 for the option to build/run/serve node projects without webpack.

including my workaround for anyone who may find it useful.
 - @ashbrener, @iammathew  - this solved the dynamic imports problem for me
 -  @tonivj5 kudos for keeping this topic from going stale, hope this helps

1.) specify new outdir for projects to be built with tsc. for my app (named backend - `apps/backend/tsconfig.app.json`) 
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist-tsc",  // new dist directory
    ...
  },
...
}

```

2.) install [tsconfig-replace-paths](https://github.com/jonkwheeler/tsconfig-replace-paths)

3.) Build & Start server with tsc
`apps/backend/project.json`
```
    "replacePaths": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          {
            "command": "npx tsconfig-replace-paths --project tsconfig.base.json -o dist-tsc -s ./"
          }
        ]
      }
    },
    "buildTsc": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "parallel": false,
        "commands": [
          {
            "command": "npx tsc --incremental --project ./apps/backend/tsconfig.app.json"
          },
          {
            "command": "npx nx run backend:replacePaths"
          }
        ]
      }
    },
    "startTsc": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "parallel": false,
        "commands": [
          {
            "command": "node dist-tsc/apps/backend/src/main.js"
          }
        ]
      }
    },
```

**Comment by AgentEnder** [comment] 2022-06-10 16:46
I'm going to close this one out, since @nrwl/js provides a tsc executor and a serve executor that fulfill its requirements. If anyone has concerns with this, I'd recommend opening a new issue that provides the context of what is not functioning as expected with the new executors.

**Closed by AgentEnder** 2022-06-10 16:46 UTC
Labels: type: feature, scope: node

**Comment by b3nab** [comment] 2022-07-25 21:40
@AgentEnder sorry, I cannot find the serve executor for @nrwl/js package, the docs doesn't refer to this https://nx.dev/packages/js. Where can I find more information on what you're talking?

**Comment by AgentEnder** [comment] 2022-07-25 21:52
`@nrwl/node:node`, it moved.

**Comment by b3nab** [comment] 2022-07-25 22:49
Still not clear to me, I think docs are more confusing.
I cannot pass parameter `--config=npm-scripts` to `@nrwl/node:app` generator and it's also not clear how to run ES Modules in node. :thinking:

**Comment by nshimiye** [comment] 2022-08-03 00:09
@AgentEnder here is a scenario that i would expect to work but it fails

**Scenario**

I have a node app that import a library

The node app uses
- `@nrwl/node:node` to serve (during development)
- `@nrwl/js:tsc` to build the output (during production deployment)

I would like to run `node dist/packages/demoapp/src/main.js` in prodution environment

**Outcome**

- `npx nx serve demoapp --watch=false` produces expected result
<img width="708" alt="image" src="https://user-images.githubusercontent.com/2660614/182497014-53e96bc3-bf1c-40a3-87a8-36d980adbd3c.png">

- `node dist/packages/demoapp/src/main.js` produces unexpected result

<img width="464" alt="image" src="https://user-images.githubusercontent.com/2660614/182497122-22cc33ab-414b-44c7-8e23-84d78954f7f6.png">

My expectation is that those two commands should produce similar result

**What would you recommend as a fix ?**

Here is a link to the sample code

**Comment by AgentEnder** [comment] 2022-08-03 13:24
`@nrwl/node:node` updates node's resolver to find the dist files for your library. Running `node` directly on the output is fine. You'll need to move some things around... Generally speaking, this could look something like this:

- nx build my-app
- mkdir dist/my-app/node-modules
- cp -r dist/some-dependency dist/my-app/node_modules

The alternative to this **_is_** bundling, which we provide `@nrwl/node:webpack` for

**Comment by kodeine** [comment] 2022-10-25 03:07
maybe this will help someone,
