### ISSUE TITLE
Incremental builds are much slower since upgrade from 11 to 12

### ISSUE THREAD

**Issue by StefanKoenen** [nrwl/nx#5455] opened 2021-04-24 09:05 UTC
## Current Behavior
The incremental builds are a lot slower since upgrade from 11.

**Before upgrade**
```
Build at: 2021-04-24T08:59:15.050Z - Hash: a356ef5598ef050a34e7 - Time: 1361ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:59:18.267Z - Hash: a356ef5598ef050a34e7 - Time: 1324ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:59:21.166Z - Hash: a356ef5598ef050a34e7 - Time: 1177ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:59:23.602Z - Hash: a356ef5598ef050a34e7 - Time: 1153ms

√ Compiled successfully.
```

**After upgrade**
```
Build at: 2021-04-24T08:57:31.018Z - Hash: 462867d1884ceef336ce - Time: 5843ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:57:38.120Z - Hash: 462867d1884ceef336ce - Time: 3652ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:57:50.391Z - Hash: 462867d1884ceef336ce - Time: 3854ms

√ Compiled successfully.
√ Browser application bundle generation complete.

24 unchanged chunks

Build at: 2021-04-24T08:58:02.523Z - Hash: 462867d1884ceef336ce - Time: 3615ms

√ Compiled successfully.
```

## Expected Behavior
The build times should not increase/decrease this much.

### Failure Logs
No failure logs.

### Environment

**Before upgrade**
```
  Node : 15.10.0
  OS   : win32 x64
  pnpm : 6.0.2

  nx : 12.0.8
  @nrwl/angular : 11.2.10
  @nrwl/cli : 11.2.10
  @nrwl/cypress : 11.2.10
  @nrwl/devkit : Not Found
  @nrwl/eslint-plugin-nx : 11.2.10
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.10
  @nrwl/linter : 11.2.10
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.10
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.10
  typescript : 4.0.5
```

**After upgrade**

```
Node : 15.10.0                    
OS   : win32 x64                  
pnpm : 6.0.2                      
                                  
nx : 12.0.8                       
@nrwl/angular : 12.0.8            
@nrwl/cli : 12.0.8                
@nrwl/cypress : 12.0.8            
@nrwl/devkit : Not Found          
@nrwl/eslint-plugin-nx : 12.0.8   
@nrwl/express : Not Found         
@nrwl/jest : 12.0.8               
@nrwl/linter : 12.0.8             
@nrwl/nest : Not Found            
@nrwl/next : Not Found            
@nrwl/node : Not Found            
@nrwl/react : Not Found           
@nrwl/schematics : Not Found      
@nrwl/tao : 12.0.8                
@nrwl/web : Not Found             
@nrwl/workspace : 12.0.8          
@nrwl/storybook : Not Found       
@nrwl/gatsby : Not Found          
typescript : 4.1.4                
```

**Comment by vsavkin** [comment] 2021-04-24 14:57
Thank you for submitting the issue. Could you provide a gihub repo with a repro?

**Comment by StefanKoenen** [comment] 2021-04-25 08:11
I will try to do that today.

One thing I saw is that one of my css (I use scss) files was much bigger on V12.
The difference is the sourcemapping in the end of the file, in V12 i get this:

```
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uXFwuLlxcL
.... very long base64 string ....

/*# sourceMappingURL=app.css.map*/
```

but in V11 I only get
```
/*# sourceMappingURL=app.css.map*/
```

By removing one import (a file which includes a lot of css) in the scss file the speed is about the same again, so I think it's related to this sourcemaps. Is there anything changed in this part?

**Comment by jredl-va** [comment] 2021-04-25 15:21
While not related to this issue and my apologies for piling on but incremental builds unusably slow. I'm going to try downgrading to 11 and see if I also see the differences in above: https://github.com/nrwl/nx/issues/5324

**Comment by StefanKoenen** [comment] 2021-04-25 18:35
@vsavkin I Created the repo [here](https://github.com/StefanKoenen/NX-5455), there are 2 branches, one for V11 and one for V12.

**Comment by leosvelperez** [comment] 2021-04-30 11:05
> @vsavkin I Created the repo [here](https://github.com/StefanKoenen/NX-5455), there are 2 branches, one for V11 and one for V12.

@StefanKoenen, thanks for sharing a repro!

I had a look at it, and I was able to track down the issue to the `@angular-devkit/build-angular` package. By updating it to version `0.1102.11`, the perf issue when rebuilding is gone. It seems the Angular CLI had a perf regression at some point, but at least on that version (which is the last 11.2.x version) is solved.

Please note, the repo you shared is not decorating the Angular CLI with Nx, so all commands are run using the Angular CLI and not Nx.

> My apologies for piling onto this issue but incremental builds are unusably slow. I'm going to try downgrading to 11 and see if I also see the differences in the timings posted above: #5324

@jredl-va this particular issue is not related to Nx incremental builds. This one is about the default Angular CLI (Webpack) incremental builds. I'll try and have a look at your issue.

**Comment by leosvelperez** [comment] 2021-04-30 11:06
I'm closing this issue since it's not related to Nx itself. If you feel this is still an issue, please feel free to reopen it.

**Closed by leosvelperez** 2021-04-30 11:06 UTC
Labels: scope: angular, type: bug
