### ISSUE TITLE
Running latest create-nx-workspace@12.0.2 throws exception

### ISSUE THREAD

**Issue by HymanZHAN** [nrwl/nx#5329] opened 2021-04-13 03:34 UTC
## Current Behavior

Running `npx create-nx-workspace` throws an exception.

## Expected Behavior

No errors.

Yes, this is a regression. I tried `npx create-nx-workspace@12.0.0` and `npx create-nx-workspace@12.0.1` and both commands were successful.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

- Run `npx create-nx-workspace@12.0.2` in the terminal.

### Failure Logs

```shell
~/Development/Projects took 10s 
> npx create-nx-workspace
npx: installed 38 in 4.359s
✔ Workspace name (e.g., org name)     · frontend
✔ What to create in the new workspace · empty
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.


>  NX   ERROR  Something went wrong! v12.0.2

(node:93812) UnhandledPromiseRejectionWarning: Error: Command failed: npm install --silent
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at createSandbox (/home/xzhan/.npm/_npx/93812/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:417:21)
    at /home/xzhan/.npm/_npx/93812/lib/node_modules/create-nx-workspace/bin/create-nx-workspace.js:112:24
    at Generator.next (<anonymous>)
    at fulfilled (/home/xzhan/.npm/_npx/93812/lib/node_modules/create-nx-workspace/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:93812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:93812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nickroberts** [comment] 2021-04-13 03:47
I was trying to migrate an existing project, and it tries to install packages with versions of `12.99.0`. Really weird.

```
➜ npx nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed.

Command failed: npm install --legacy-peer-deps @nrwl/workspace@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/jest@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@nrwl/workspace'
npm ERR! notarget
```
I think because it is asynchronous, it fails at different times. I tried again, and it tried to install `@nrwl/devkit@12.99.0`. Really weird.

**Comment by nickroberts** [comment] 2021-04-13 03:52
Most likely a duplicate of https://github.com/nrwl/nx/issues/5327

**Comment by HymanZHAN** [comment] 2021-04-13 03:52
Yeah, I suspect the version `.99` is for internal testing dependencies and somebody accidentally put it in the prod release.

**Comment by HymanZHAN** [comment] 2021-04-13 03:54
Ah, you are right. I wasn't paying attention to the detailed discussion under that issue. If the Nx devs follow up on that one I will close mine.

**Comment by FrozenPandaz** [comment] 2021-04-13 14:55
Sorry all,

12.0.3 was published to resolve the issue.

12.0.2 was mispublished so I deprecated it and you should use 12.0.3 or 12.0.1 instead.

I am also going to close this issue as it is a duplicate of https://github.com/nrwl/nx/issues/5327.

Please continue discussing there if you still have issues.

**Closed by FrozenPandaz** 2021-04-13 14:55 UTC
Labels: type: bug
