### ISSUE TITLE
Angular & Module Federation: NG0912 Component ID generation collision detected.

### ISSUE THREAD

**Issue by rainerhahnekamp** [nrwl/nx#19198] opened 2023-09-15 18:07 UTC
### Current Behavior

In my NX-powered Angular application, I use module federation.

With `gridstack`, I have a very "special" library that requires two imports:

```typescript
import {GridstackModule} from "gridstack/dist/angular";
import {GridStackOptions} from "gridstack";
```

If I use the app of the remote, there is no problem. As soon as the remote is accessed via the host, I get the following message:

```
NG0912: Component ID generation collision 
detected. Components 'NxWelcomeComponent' and
'NxWelcomeComponent' with selector
'test-nx-mf-nx-welcome' generated the same
component ID. To fix this, you can change the
selector of one of those components or add an
extra host attribute to force a different
ID. Find more at https://angular.io/errors/NG0912
```
My guess is that the sharing of dependencies does not work correctly.

### Expected Behavior

The library gridstack should only be loaded once, hence no error message should be shown.

### GitHub Repo

https://github.com/rainerhahnekamp/nx-mf-shared

### Steps to Reproduce

1. Clone the repo
2. Run `npx nx serve dashboard`
3. Run `npx nx serve shell`
4. Open `http://localhost/4200` and click on dashboard
5. You should see the warning in the console

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   npm    : 9.5.1
   
   nx                 : 16.8.1
   @nx/js             : 16.8.1
   @nx/jest           : 16.8.1
   @nx/linter         : 16.8.1
   @nx/workspace      : 16.8.1
   @nx/angular        : 16.8.1
   @nx/cypress        : 16.8.1
   @nx/devkit         : 16.8.1
   @nx/eslint-plugin  : 16.8.1
   @nrwl/tao          : 16.8.1
   @nx/web            : 16.8.1
   @nx/webpack        : 16.8.1
   nx-cloud           : 16.4.0
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-09-25 14:21
Thanks for reporting this!

The specific error you're reporting is not caused by importing from `gridstack`. As the error mentions, two different components have the same "ID". This is because the placeholder `NxWelcomeComponent` the Nx application generator generates is the same in every application. You can do a number of things to solve this:

- Delete the `NxWelcomeComponent`. It's only a placeholder meant to provide some initial guidance. Your application shouldn't need it.
- Change the component selectors so they are unique.
- Add some extra metadata to the component, like a host attribute.

You can read more about the error at https://angular.io/errors/NG0912.

I'm closing this since the reported error is not related to the dependencies and it's an expected runtime error caused by a component that shouldn't be used in production apps. Please follow one of the suggestions mentioned above to address it.

**Closed by leosvelperez** 2023-09-25 14:21 UTC
Labels: type: bug, scope: angular
