### ISSUE TITLE
e2e execution error

### ISSUE THREAD

**Issue by FallenRiteMonk** [nrwl/nx#339] opened 2018-03-19 13:59 UTC
Using version 0.9.0 when i try to run ```ng e2e --app admin``` I get the following error: ```Please provide the app name using --app or -a.```. It only works if I run the following command: ```ng e2e --app=admin```
(Equal sign required)

This is strange because ```ng serve --app admin``` works just fine

**Comment by jschwarty** [comment] 2018-03-19 15:35
Was able to reproduce. Looks like this message is coming from Nx code here: https://github.com/nrwl/nx/blob/fcec9dc1c0468514b4a8f05f1c83bc59c6f14778/packages/schematics/src/utils/cli-config-utils.ts#L22

TODO: Need to update [`findAppArg`](https://github.com/nrwl/nx/blob/fcec9dc1c0468514b4a8f05f1c83bc59c6f14778/packages/schematics/src/utils/cli-config-utils.ts#L36) to support no equals

**Comment by FrozenPandaz** [comment] 2018-03-20 15:10
I can take this

**Comment by FrozenPandaz** [comment] 2018-04-25 03:37
This should be fixed as of `0.10.0`. Let me know if there are any issues with this.

**Closed by FrozenPandaz** 2018-04-25 03:37 UTC
Labels: type: bug
