### ISSUE TITLE
Angular build -- buildable libs -- swalloved warnings

### ISSUE THREAD

**Issue by montella1507** [nrwl/nx#8165] opened 2021-12-14 16:05 UTC
Hi, could you please check this issue:
https://github.com/angular/angular-cli/issues/22346

there is small minimal-reproduction repository. The problem is NX build swallows important warnings like:

WARNING: Cannot call a namespace ('moment')

which can lead to hard to debug issues occuring only during PROD BUILD (not serve).

Why NX doesnt show any warning, while NG build does? Is it possible to be more verbose about possible issues? Thank you

**Comment by Coly010** [comment] 2022-01-17 12:57
I cannot reproduce with latest Nx. I'm getting correct error. 

Thanks for raising this! I'll close the issue for now :)

**Closed by Coly010** 2022-01-17 12:57 UTC
Labels: type: bug, scope: angular
