### ISSUE TITLE
I'm trying to run nx serve <project> and get: NX Cannot read properties of undefined

### ISSUE THREAD

**Issue by aclarturocastro** [nrwl/nx#8968] opened 2022-02-14 19:24 UTC
## Current Behavior
Migration to v13. After that, when running "nx serve <project>" I got: `NX Cannot read properties of undefined ('reading endsWith')`

Also: 
`NX As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.`

Running "nx format": 

          NX   Affected criteria defaulted to --base=main --head=HEAD
          NX   Nx Daemon was not able to compute the project graph.
             Log file with the error: /Users/Arturo/aclprojects/acl-customers/node_modules/.cache/nx/d/daemon-error.log
             Please file an issue at https://github.com/nrwl/nx
             Nx Daemon is going to be disabled until you run "nx reset".
          
          NX As of Nx 13, project configuration should be moved from nx.json to workspace.json/project.json. Please run "nx format" to fix this.
          NX   Cannot read properties of undefined (reading 'endsWith')`

## Expected Behavior
My service running

## Steps to Reproduce

nx serve <project> after migration to v13.
nx format

### Failure Logs

[daemon-error.log](https://github.com/nrwl/nx/files/8063397/daemon-error.log)
[daemon.log](https://github.com/nrwl/nx/files/8063398/daemon.log)

### Environment

          NX   Report complete - copy this into the issue template
      
          Node : 16.13.1
          OS   : darwin x64
          yarn : 1.22.15
         
          nx : 13.8.1
         @nrwl/angular : 13.8.1
         @nrwl/cli : 13.8.1
         @nrwl/cypress : 13.8.1
         @nrwl/detox : undefined
         @nrwl/devkit : 13.8.1
         @nrwl/eslint-plugin-nx : 13.8.1
         @nrwl/express : undefined
         @nrwl/jest : 13.8.1
         @nrwl/js : undefined
         @nrwl/linter : 13.8.1
         @nrwl/nest : undefined
         @nrwl/next : undefined
         @nrwl/node : undefined
         @nrwl/nx-cloud : undefined
         @nrwl/react : undefined
         @nrwl/react-native : undefined
         @nrwl/schematics : undefined
         @nrwl/storybook : 13.8.1
         @nrwl/tao : 13.8.1
         @nrwl/web : undefined
         @nrwl/workspace : 13.8.1
         typescript : 4.5.5
         rxjs : 7.5.4
         ---------------------------------------
         Community plugins:
   	 @angular/animations: 13.2.2
   	 @angular/cdk: 13.2.2
   	 @angular/common: 13.2.2
   	 @angular/compiler: 13.2.2
   	 @angular/core: 13.2.2
   	 @angular/forms: 13.2.2
   	 @angular/material: 13.2.2
   	 @angular/platform-browser: 13.2.2
   	 @angular/platform-browser-dynamic: 13.2.2
   	 @angular/router: 13.2.2
   	 angular-datatables: 13.0.1
   	 ngx-spinner: 13.1.1
   	 @angular-devkit/build-angular: 13.2.3
   	 @angular/cli: 13.2.3
   	 @angular/compiler-cli: 13.2.2
   	 @angular/language-service: 13.2.2

          (node:18220) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/Arturo/aclprojects/acl-customers/node_modules/tslib/package.json.
          Update this package.json to use a subpath pattern like "./*".
          (Use `node --trace-deprecation ...` to show where the warning was created)`

**Comment by FrozenPandaz** [comment] 2022-02-14 23:13
Sorry, could you please provide a repo that the team can use to reproduce the issue.

**Comment by aclarturocastro** [comment] 2022-03-01 15:41
Hey Jason

I provided a couple of weeks ago a private repo... were you able to review
it?
Arturo Castro

**Comment by sins629** [comment] 2022-03-08 18:34
@aclarturocastro did you find a way to fix this? I have run into the exact same issue after doing the v13 migration and then running `nx format'

**Comment by amakhrov** [comment] 2022-03-09 01:39
Same here. Migrating to v13, running `nx format`, getting the error
```
TypeError: Cannot read property 'endsWith' of undefined\n" +
    '    at createProjectRootMappings (<root>/node_modules/@nrwl/workspace/src/core/file-map-utils.js:12:38)\n' +
    '    at createProjectFileMap (<root>/node_modules/@nrwl/workspace/src/core/file-map-utils.js:27:33)\n' +
    '    at <root>/node_modules/@nrwl/workspace/src/core/project-graph/daemon/server/project-graph-incremental-recomputation.js:92:85\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (<root>/node_modules/@nrwl/workspace/node_modules/tslib/tslib.js:114:62)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
  message: "Cannot read property 'endsWith' of undefined\n" 
```

**Comment by amakhrov** [comment] 2022-03-09 01:43
Ok, I got it.

I tried to commit after each step of nx migrate.
We also have a pre-commit hook, that runs `nx format:write`.
This hook fails if I try to commit changes after installing new packages but before running `--run-migrations`

**Comment by nevzatopcu** [comment] 2022-03-14 23:39
We are just waiting for the solution to upgrade our project to nx and ng v13.

**Comment by leosvelperez** [comment] 2022-03-15 16:46
Thanks for reporting this!

I had a look at the stack traces shared by @amakhrov [here](https://github.com/nrwl/nx/issues/8968#issuecomment-1062466772) and the one in the daemon.log file shared by @aclarturocastro. Checking the source code, it looks like you might have a project in your configuration with no value specified for the `root` property. That property is required and therefore, it would cause issues when it's not present.

Please make sure that all projects always have a `root` property set in the configuration.

I'll close this issue since it seems to be caused by an invalid configuration and in some cases seem to be because the migrations were not run. Please feel free to reopen this if the above doesn't fix the issue.

**Closed by leosvelperez** 2022-03-15 16:46 UTC
Labels: type: bug, blocked: repro needed, scope: angular

**Comment by alo** [comment] 2022-04-06 08:04
Hi guys! 

Same problem here. 

@leosvelperez this is not my case, I don't have a project in my configuration with no value specified for the root property.
@sins629 did you find a solution? 

Thanks.

**Comment by ivaylozhekov** [comment] 2022-04-07 15:13
Hi @alo,

I hit the same issue. I debugged a little bit and found out that in nx.json, the 'root' property for each projects object should be present /as @leosvelperez suggested/

nx.json:
...
"projects": {
        "your-lib-name-1": {
            "tags": [],
            "root": "<the root of the lib>" <<<--- same root listed for the lib in angular.json
        },
        ...
}
...

after this, you may need to run the `nx format` command
I hope this helps

**Comment by alo** [comment] 2022-04-08 09:19
Thanks @ivaylozhekov, it worked!

Have a nice day!

**Comment by will-hu-0** [comment] 2022-04-22 06:57
Thanks @ivaylozhekov , it resolved my issue as well.

**Comment by nelboullon** [comment] 2022-05-02 20:58
I just deleted all the libs in `projects` key on `nx.json` and ran `nx-format`. It worked for me

Saw this [nx.json](https://github.com/nrwl/nx-examples/blob/master/nx.json) example

Hope it works for you!

**Comment by nguyenhy** [comment] 2022-05-10 03:37
hope this [answer](https://stackoverflow.com/a/72180446/8332986) help someone

**Comment by tunecino** [comment] 2022-06-17 18:36
Exact same issue here: `Cannot read property 'endsWith' of undefined\n"...`
I don't have the "root" key as I am using nx-electron, and for some reasons its schematic is removing them.
In my case, just running `npm install` fixed it. Still not sure what happened but it worked. Hope it helps.

**Comment by fplusf** [comment] 2022-08-11 14:37
After updating NX from 12 to 13 ran into the same issues, now getting this error on running any commands like serve, build etc. Any suggestions from the above did not work unfortunately 
` NX   Cannot read property 'endsWith' of undefined`
