### ISSUE TITLE
Angular incremental build performance problems for existing (or larger apps)

### ISSUE THREAD

**Issue by tomastrajan** [nrwl/nx#8369] opened 2022-01-04 13:02 UTC
## Current Behavior

It seems to be the case that when enabling incremental build for Angular apps (following this guide https://nx.dev/l/a/ci/setup-incremental-builds-angular) and especially using `"builder": "@nrwl/angular:webpack-browser",` the build performance is degraded when compared to using default `"builder": "@angular-devkit/build-angular:browser",` for a specific scenario of migrating of existing app into NX workspace:

* the application is relatively large and uses lazy loaded routes (modules)
* not many libraries were extracted yet

It seems to be the case that using `@nrwl/angular:webpack-browser` leads to re-build of entire SPA for ANY change in the SPA which is much slower compared to re-building of lazy bundles (for lazy features) which contain the change

Based on this observation, it seems nx incremental build should NOT be used during app migration to NX (or  app with some size) and only make sense when app is just a empty shell (eg end stage of migration to nx or for a green field projects)

## Expected Behavior

Would it be possible to preserve Angular CLI (`@angular-devkit/build-angular:browser`) build optimizations (eg only rebuild affected lazy bundles, note NOT nx affected, jsut standard Angualr CLI behavior) together with incremental build which would enable smoother migration to nx workspace ?

## Steps to Reproduce

1. create nx workspace with Angular app and buildable lib
2. generate 1 lazy route in the Angular app (inline) to simulate migration of already existing Angular SPA into nx workspace
3. try to make changes in eager (vs lazy part of the SPA) and see build output (from `serve`) that it only rebuilds lazy feature 
4. follow steps in the official guide to enable incremental build  https://nx.dev/l/a/ci/setup-incremental-builds-angular
5. make changes in lazy route in SPA, the build log should show full build (eg rebuilding of whole SPA if we only change source of lazy feature

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : linux x64
  npm  : 6.14.11

  nx : 13.4.1
  @nrwl/angular : 13.4.1
  @nrwl/cli : 13.4.1
  @nrwl/cypress : 13.4.1
  @nrwl/devkit : 13.4.1
  @nrwl/eslint-plugin-nx : 13.4.1
  @nrwl/express : undefined
  @nrwl/jest : 13.4.1
  @nrwl/linter : 13.4.1
  @nrwl/nest : 13.4.1
  @nrwl/next : undefined
  @nrwl/node : 13.4.1
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.1
  @nrwl/web : 13.4.2
  @nrwl/workspace : 13.4.1
  @nrwl/storybook : 13.4.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.1
         @angular/cdk: 13.1.1
         @angular/common: 13.1.1
         @angular/compiler: 13.1.1
         @angular/core: 13.1.1
         @angular/forms: 13.1.1
         @angular/material: 13.1.1
         @angular/platform-browser: 13.1.1
         @angular/platform-browser-dynamic: 13.1.1
         @angular/router: 13.1.1
         @ngrx/component-store: 13.0.2
         @ngrx/effects: 13.0.2
         @ngrx/entity: 13.0.2
         @ngrx/router-store: 13.0.2
         @ngrx/store: 13.0.2
         @ngrx/store-devtools: 13.0.2
         @angular-devkit/build-angular: 13.1.2
         @angular/cli: 13.1.2
         @angular/compiler-cli: 13.1.1
         @angular/language-service: 13.1.1
         @ngrx/schematics: 13.0.2
         @ngrx/store-devtools: 13.0.2

**Comment by Coly010** [comment] 2022-01-17 12:58
Duplicate of https://github.com/nrwl/nx/issues/5324

**Closed by Coly010** 2022-01-17 12:58 UTC
Labels: type: bug, scope: angular
