### ISSUE TITLE
Storybook with Angular Universal

### ISSUE THREAD

**Issue by maxisam** [nrwl/nx#7165] opened 2021-09-28 21:46 UTC
## Current Behavior
if there is a service in one of the dependency package that has import like 

`import { Request } from 'express';`

Generally it happens in a HttpInterceptor

It doesn't throw error but the whole project can't load properly.

Like you are targeting project B but depending on project A with certain things. If project A has something like above code. (basically anything related to nodejs)

The whole story doesn't work

## Expected Behavior

At least throw an error or something. 

## Steps to Reproduce

import anything related to nodejs

### Environment
  Node : 14.17.1
  OS   : win32 x64
  yarn : 1.22.5
  
  nx : 12.9.0
  @nrwl/angular : 12.9.0
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by mandarini** [comment] 2022-01-15 09:58
Hi there @maxisam ! Can you please let me know if this issue still exists? If yes, can you please provide a reproduction repository? Also, do you think that this could be something you could help with? I mean, help us throw an error message, like you suggested?

Thank you! :)

**Comment by mandarini** [comment] 2022-01-31 15:30
I will close this, since I received no reply. If this comes up again, please write a comment here and I will reopen the issue! :)

**Closed by mandarini** 2022-01-31 15:30 UTC
Labels: type: bug, blocked: repro needed, scope: storybook
