### ISSUE TITLE
`affected` logic bug for Storybook enabled projects

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#19886] opened 2023-10-26 19:09 UTC
### Current Behavior

Setup - all angular 15.2+:

I have a lib `shared-ui` that contains a Storybook setup and stories for its components.
I have multiple other libs that import components from `shared-ui`.

If I change code on one of the stories of `shared-ui` the `affected` command (`nx show projects --affected`) reports that projects that were importing `shared-ui` have been also affected.

The Storybook related change in no way affects the validity of the components inside the `shared-ui` nor of the other libs that import it.

### Expected Behavior

I would expect that only the project with the Storybook integration is reported as affected and all the other Storybook related projects that maybe compose on that - in case multiple Storybooks are combined into one.

In reality the Storybook part should be considered independent to the implementation of the lib itself.

Storybook is affected by component logic changes.
But  Storybook changes do not affect component logic.

### Steps to Reproduce

All libs in Angular
1. Create a `shared-ui` lib with a shared component(s) and Storybook integration
2. Create other libs that import components from the `shared-ui` - no Storybook setu in these
3. Make a change to a story in `shared-ui`
4. Run the affected command `nx show projects --affected`

### Nx Report

```shell
Nx 16.5.1
Angular 15.2.9
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by gkamperis** [comment] 2023-11-04 10:50
@AgentEnder not sure how you classify the issues but to me it seems the issue is with the `affected` computation logic and not with Storybook itself.

**Comment by gkamperis** [comment] 2023-11-18 10:39
any feedback on this? in a large repo this causes a lot of unwarranted builds and delays

**Comment by gkamperis** [comment] 2023-12-09 13:24
anyone?

**Comment by mandarini** [comment] 2023-12-20 16:39
Looking into it @gkamperis . I would be inclined to say "use .nxignore" (https://nx.dev/reference/nxignore) but maybe this is too "aggressive", it will completely ignore `.stories.*`, and I guess you do want nx to take into account `stories.` when you're building & rebuilding Storybook.

**Comment by mandarini** [comment] 2023-12-20 17:35
You say that it causes extra builds in your repository and delays. However, in my repo: https://github.com/mandarini/storybook-affected-nx I do not see this. What I mean is that if I change a story, I do not see build being retriggered, I see it getting fetched from cache.

Can you please provide a simple reproduction repository?

**Comment by gkamperis** [comment] 2023-12-21 16:16
@mandarini thanks for getting back to me.

Your example repo is not in the "classic" structure of the previous Nx versions.
Our repo has the apps and libs structure - maybe it matters - maybe it does not - just thought I should mention this :)

Regarding the cache, I am not sure if you mean the Nx cloud cache, but we do not have this enabled as we are not allowed.

I can confirm that 

after changing something in the `some-component.stories.ts` - just a simple string change in the description let's say 
then after running 
`nx affected:test ....`
`nx affected:build ....`
etc

the whole chain of tasks is re-run.

This triggers tests, build (apps), lint on all the libs that reference the ui lib that contains the story.

So if you have this reference chain

UI Lib (with story) -> Client UI Lib A 
UI Lib (with story) -> Client UI Lib B 
UI Lib (with story) -> Client UI Lib C 
UI Lib (with story) -> Client UI Lib D 
UI Lib (with story) -> App A 

All tasks of this chain are calculated as affected.
The builds are not a huge time slice.
But the tests are.
Picture 100+libs with *many* 100s of tests each.
All this because I changed a string in a story....

Even if the cache is enabled I will still argue that changing a story should not be considered as affecting the libs.
Stories live in "parallel" to the UI lib.
Stories are clients of the UI.
The UI is unrelated to the stories.
So the UI should be reported as affected because a story changed.

Thanks again for looking into this.

**Comment by mandarini** [comment] 2023-12-21 17:13
By cache I don't mean the Nx Cloud, no. Just the Nx cache.

I agree that the logic is flawed but I am not sure what we can do atm. I will tag some of my colleagues, maybe they have a better idea here, but since it's holiday season time, expect any update mid-January the earliest 😅, thanks for understanding.

Tagging @isaacplmann again, and maybe @meeroslav and @AgentEnder ?

I agree that changing a story should not show dependent projects as affected, because stories indeed live in parallel to the projects.

In my case however, I must note again that in the repo I shared, build is NOT ran again, it's fetched from the cache, so a repro on your side would be helpful here. It does not matter what the layout of the workspace is (apps/libs folders etc).

Thanks again!

**Comment by gkamperis** [comment] 2023-12-21 17:26
@mandarini thanks again for the reply.

Maybe locally the Nx cache works for the builds.
Maybe it will work even for the tests if they were ever run for the full repo.

Usually devs will work and run on sub-projects so the accumulated cache will be mostly different.

However, the PR change needs to run in the the CI environment.
That triggers the process, and the workspace is fresh every time.

So the cache is always empty :(

**Comment by FrozenPandaz** [comment] 2024-05-15 21:16
I'm going to close this issue as the intended behavior at the moment.

Affected is at the project level. When files are touched anywhere within a project, projects which consume touched projects are affected. Yes, this does indeed cause more tasks to be run than perhaps necessary.

As @mandarini explained, caching significantly mitigates re-running things unnecessarily.

On CI, Nx Cloud is the solution to caching in CI. There are many [pricing tiers](https://nx.app/pricing) including free tiers. If something is preventing you from using Nx Cloud, please let us know.

It may be possible to change this behavior, but it would be more of a rework of how affected works rather than fixing the way it works now.

**Closed by FrozenPandaz** 2024-05-15 21:16 UTC
Labels: type: bug, scope: core, scope: storybook

**Comment by gkamperis** [comment] 2024-05-16 06:17
@FrozenPandaz thanks for the feedback but I do not agree with the explanation. 

Apps are composed of libs. When you touch the apps the libs are not marked as affected. 

Storybook is a top level app. 
The Storybook dependency tree is independent of the other apps' tree.

Touched libs should affect Storybook apps.
Storybook apps only affect other Storybook apps.

There should be a way to exclude stories from the determination of what has been affected.
