### ISSUE TITLE
[critical][next.js] withNx plugin required in production dependencies with all its Nx dependencies

### ISSUE THREAD

**Issue by ild0tt0re** [nrwl/nx#16392] opened 2023-04-19 07:54 UTC
### Current Behavior

The `const withNx = require('@nrwl/next/plugins/with-nx')` import in `next.config.js` file of **next.js** app, force me to install `@nrwl/next` modules with all its dependencies also in production.

Run 
```sh
$ nx build <next-app-name>
```

If I remove it this happen:
https://github.com/nrwl/nx/issues/15794

### Expected Behavior

Nx should not force me to install all its dev dependencies only to support the build of Next.js
NOTE:
Since `next.config.js` is copied as is in production by design, Nx should not add its stuff to avoiding to pollute the node_modules

### Steps to Reproduce

1. `nx build <next-app-name>`
2. `install only production dependencies`
3. run the app in production fail because withNx deps is missing

### Nx Report

```shell
Node : 18.15.0
   OS   : darwin arm64
   pnpm : 8.1.1

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/next              : 15.9.2
   @nrwl/nx-plugin         : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/rollup            : 15.9.2
   @nrwl/storybook         : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/web               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @jscutlery/semver : 2.29.3
   ngx-deploy-npm    : 5.2.0
   ---------------------------------------
   Local workspace plugins:
   	 @cloudacademy/nx-plugin
```

### Failure Logs

```shell
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by mandarini** [comment] 2023-04-19 08:22
Possibly related? https://github.com/nrwl/nx/issues/15931

**Comment by jaysoo** [comment] 2023-04-21 15:46
This is a duplicate of https://github.com/nrwl/nx/issues/15931

Will close this to keep the discussion there.

**Closed by jaysoo** 2023-04-21 15:46 UTC
Labels: type: bug, scope: nextjs
