### ISSUE TITLE
Linting --with-deps does not work on Nx 12.8

### ISSUE THREAD

**Issue by ashwinGokhale** [nrwl/nx#6922] opened 2021-09-03 02:37 UTC
## Current Behavior

Linting a project and all its dependencies does not work.

## Expected Behavior

Linting a project and all its dependencies should work. I believe this is a regression. Even if --with-deps is deprecated, it should still work until Nx 14.

## Steps to Reproduce

1. Clone [nx-examples repo](https://github.com/nrwl/nx-examples)
2. Run `yarn`
3. `yarn nx lint cart --with-deps`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
$ nx lint cart --with-deps

DEPRECATION WARNING: --with-deps is deprecated and it will be removed in v14.
Configure target dependencies instead: https://nx.dev/latest/angular/core-concepts/configuration#target-dependencies.


>  NX  Running target lint for project cart and 8 task(s) that it depends on.


———————————————————————————————————————————————

> nx run shared-jsxify:lint

Linting "shared-jsxify"...

All files pass linting.


> nx run shared-product-types:lint

Linting "shared-product-types"...

All files pass linting.

Unexpected error:
TypeError: Cannot read property 'tags' of undefined
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:16:75
    at Array.map (<anonymous>)
    at C:\Users\agokhale\source\nx-examples\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:16:44
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\agokhale\source\nx-examples\node_modules\tslib\tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```
  Node : 14.16.1
  OS   : win32 x64
  yarn : 1.22.5

  nx : Not Found
  @nrwl/angular : 12.8.0
  @nrwl/cli : 12.8.0
  @nrwl/cypress : 12.8.0
  @nrwl/devkit : 12.8.0
  @nrwl/eslint-plugin-nx : 12.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.8.0
  @nrwl/linter : 12.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : 12.3.10
  @nrwl/react : 12.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.8.0
  @nrwl/web : 12.8.0
  @nrwl/workspace : 12.8.0
  @nrwl/storybook : 12.8.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by leosvelperez** [comment] 2021-09-03 08:40
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/6760. Please note a fix has been merged in https://github.com/nrwl/nx/pull/6875 and it will be released soon, keep an eye on the releases.

**Closed by leosvelperez** 2021-09-03 08:40 UTC
Labels: type: bug

**Comment by pranav-js** [comment] 2021-12-28 12:49
I still get this error with https://github.com/ionic-team/stencil-eslint extension with stencil-library setup in nx. Had to install with ```--legacy-peer-deps``` option though because it used lower version of eslint. 

Now I get

```sh
Invalid lint configuration. Nothing to lint. Please check your lint target pattern(s).
Error: Invalid lint configuration. Nothing to lint. Please check your lint target pattern(s).
    at /Users/pranav.sarda/Documents/GitHub/zwitch-frontend/packages/linter/src/executors/eslint/lint.impl.ts:98:11
    at Generator.next (<anonymous>)
    at fulfilled (/Users/pranav.sarda/Documents/GitHub/zwitch-frontend/node_modules/tslib/tslib.js:114:62)
```
