### ISSUE TITLE
Error when creating project graph with pnpm configured as `node-linker=hoisted`

### ISSUE THREAD

**Issue by jiby-aurum** [nrwl/nx#15448] opened 2023-03-04 21:04 UTC
### Current Behavior

Any nx command fails with the below error, when pnpm is configured with `node-linker-hoisted`
Everything works when with `shamefully-hoist=true`.

### Expected Behavior

nx commands should work as expected when pnpm is configured via `node-linker-hoisted` as well.

### Steps to Reproduce

Currently it happens only in a specific project, I add below additional information from the little debugging I did, if it does not help, I can try to setup a minimal repro

### Nx Report

```shell
also fails to run
```

### Failure Logs

```shell
[NX Daemon Server] - 2023-03-04T20:50:49.786Z - Error detected when creating a project graph: Cannot convert undefined or null to object
[NX Daemon Server] - 2023-03-04T20:50:49.786Z - [REQUEST]: Responding to the client with an error. Error when preparing serialized project graph. Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getHoistedVersion (/Users/jibyjose/Projects/aurum-one/node_modules/nx/src/lock-file/pnpm-parser.js:74:28)
    at addNodes (/Users/jibyjose/Projects/aurum-one/node_modules/nx/src/lock-file/pnpm-parser.js:59:36)
    at parsePnpmLockfile (/Users/jibyjose/Projects/aurum-one/node_modules/nx/src/lock-file/pnpm-parser.js:14:5)
    at parseLockFile (/Users/jibyjose/Projects/aurum-one/node_modules/nx/src/lock-file/lock-file.js:72:52)
    at /Users/jibyjose/Projects/aurum-one/node_modules/nx/src/project-graph/build-project-graph.js:63:62
    at Generator.next (<anonymous>)
    at /Users/jibyjose/Projects/aurum-one/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/jibyjose/Projects/aurum-one/node_modules/tslib/tslib.js:114:16)
```

### Additional Information

I tried to debug it a bit, and it happens while trying to get the hoisted version of a package, which in this case was an optional package that did not get installed. nx tries to read the version from `hoistedDependencies` property in `node_modules/.modules.yaml`. However there is no such property in `node_modules/.modules.yaml` when pnpm is configured with `node-linker-hoisted`.

**Comment by jiby-aurum** [comment] 2023-03-04 21:08
adding a check in `getHoistedVersion` for `hoistedDependencies` being `undefined` and returning version `undefined` seems to fix it. However I am not sure if it has other consequences

**Comment by jiby-aurum** [comment] 2023-03-04 21:19
and now for whatsoever reason after reverting the change I made, I cannot reproduce anymore. Feel free to close if the issue does not make much sense.

**Comment by 5o50** [comment] 2023-03-06 13:10
I'm encountering the same issue, it's blocking all commands

nx 15.8.5
pnpm 7.29.0 with `node-linker=hoisted`

```
> app@0.0.0 nx /home/john/workspace/app
> nx "show" "projects"

nx.js show <object>

Show information about the workspace (e.g., list of projects)

Positionals:
  object  What to show (e.g., projects)                                                                                 [required] [choices: "projects"]

Options:
  --help     Show help                                                                                                                         [boolean]
  --version  Show version number                                                                                                               [boolean]

{
  stack: 'TypeError: Cannot convert undefined or null to object\n' +
    '    at Function.keys (<anonymous>)\n' +
    '    at getHoistedVersion (/home/john/workspace/app/node_modules/nx/src/lock-file/pnpm-parser.js:72:28)\n' +
    '    at addNodes (/home/john/workspace/app/node_modules/nx/src/lock-file/pnpm-parser.js:58:36)\n' +
    '    at parsePnpmLockfile (/home/john/workspace/app/node_modules/nx/src/lock-file/pnpm-parser.js:14:5)\n' +
    '    at parseLockFile (/home/john/workspace/app/node_modules/nx/src/lock-file/lock-file.js:72:52)\n' +
    '    at /home/john/workspace/app/node_modules/nx/src/project-graph/build-project-graph.js:63:62\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/john/workspace/app/node_modules/tslib/tslib.js:167:75\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.__awaiter (/home/john/workspace/app/node_modules/tslib/tslib.js:163:16)',
  message: 'Cannot convert undefined or null to object\n' +
    '\n' +
    'Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.\n' +
    'If the error persists, please run "nx reset".'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by 5o50** [comment] 2023-03-06 13:26
As @jiby-aurum noticed adding  `?? {}` on the following line : 

`const key = Object.keys(hoistedDependencies ?? {}).find((k) => k.startsWith(`/${packageName}/`));`

of this function
```
function getHoistedVersion(hoistedDependencies, packageName) {
    let version = (0, package_json_1.getHoistedPackageVersion)(packageName);
    if (!version) {
        const key = Object.keys(hoistedDependencies ?? {}).find((k) => k.startsWith(`/${packageName}/`));
        if (key) {
            version = key.slice(key.lastIndexOf('/') + 1).split('_')[0];
        }
        else {
            // pnpm might not hoist every package
            // similarly those packages will not be available to be used via import
            return;
        }
    }
    return version;
}
```
from this file `node_modules/nx/src/lock-file/pnpm-parser.js` seems to be enough to run the commands again.
However I could not say if it's working as intended without side-effects.

**Comment by jiby-aurum** [comment] 2023-03-10 08:05
@meeroslav @FrozenPandaz would the rather naive fix I proposed make sense, if so and if its easier for you I can create a PR.

**Comment by meeroslav** [comment] 2023-03-10 12:23
Thank you @jiby-aurum for reporting this and feel free to create a PR with fix. If possible it would be nice to have test, but I can do that once you have the PR ready.

**Comment by jiby-aurum** [comment] 2023-03-10 12:46
@meeroslav cool, I will try to have a look it I can already create a test case

**Comment by etkachev** [comment] 2023-03-13 16:14
We are also running into this issues in our pipelines for build and deploy. I will keep an eye on this issue, and when a fix will be released with new version of nx. Hoping to get our workspace updated soon, but this is a blocker at the moment.

**Closed** 2023-03-14 11:01 UTC
Labels: type: bug, scope: core
