### ISSUE TITLE
@nrwl/webpack:webpack `tsPlugins` options removed in version 15

### ISSUE THREAD

**Issue by dan-cooke** [nrwl/nx#12966] opened 2022-11-03 13:08 UTC
After running migrations from v14 to v15.

My webpack build target that uses `tsPlugins` fails

```json
"targets": {
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "dependsOn": [
        "type-util:build"
      ],
      "outputs": [
        "{options.outputPath}"
      ],
      "options": {
        "outputPath": "dist/apps/api",
        "main": "apps/api/src/main.ts",
        "generatePackageJson": true,
        "tsConfig": "apps/api/tsconfig.app.json",
        "tsPlugins": [
          {
            "name": "@nestjs/graphql/plugin",
            "options": {
              "introspectComments": true,
              "typeFileNameSuffix": [
                ".input.ts",
                ".args.ts",
                ".entity.ts",
                ".model.ts"
              ]
            }
          }
        ],
        "target": "node",
        "compiler": "tsc"
      },
```

**Comment by nartc** [comment] 2022-11-03 14:23
Hi @dan-cooke, the `tsPlugins` has been renamed to `transformers` and we must have overlooked a migration for it. However, `tsPlugins` is still in the `aliases` array of `transformers` option so not sure how that stopped working for you. 

For now, you can use `transformers` instead. https://github.com/nrwl/nx/blob/master/packages/webpack/src/executors/webpack/schema.json#L186

**Comment by dan-cooke** [comment] 2022-11-03 14:34
@nartc thank you! I was just about to downgrade to 14.x 

Is it possible to get the migrations updated to prevent other users encountering this issue?

**Comment by nartc** [comment] 2022-11-03 14:53
Oh if that's the case, please share with me a reproduce, I can try digging with you on that.

**Comment by dan-cooke** [comment] 2022-11-03 16:03
@nartc i haven’t got the time to create a repo at the moment, but it’s easily reproducible by bootstrapping a new NX NestJs workspace.

installing @nestjs/graphql plugin

and then copying my snippet from the original post

**Comment by jaysoo** [comment] 2023-02-24 15:45
I couldn't reproduce the problem, but I was able to use the `transformers` option successfully. See here: https://github.com/jaysoo/issue-12966

Closing this issue but please re-open if you have a reproduction ready.

**Closed by jaysoo** 2023-02-24 15:45 UTC
Labels: type: bug, scope: bundlers
