### ISSUE TITLE
Ionic project not building after migrating to v11

### ISSUE THREAD

**Issue by nrcaz** [nrwl/nx#4714] opened 2021-02-05 16:10 UTC
Ionic CLI not building after migrating to v11
```js
function runCommand(projectsToRun, projectGraph, { nxJson, workspaceResults }, nxArgs, overrides, reporter, initiatingProject) {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        const { tasksRunner, runnerOptions } = getRunner(nxArgs, nxJson);
        // we have to special parallel because they can be overwritten in nx.json
        setParallelDefaults(runnerOptions);
        reporter.beforeRun(projectsToRun.map((p) => p.name), nxArgs, overrides);
```
stack trace `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined`
log `projectsToRun` => `[undefined]`
```js
function runOne(opts) {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        const { nxArgs, overrides } = utils_1.splitArgsIntoNxArgsAndOverrides(Object.assign(Object.assign({}, opts.parsedArgs), { configuration: opts.configuration, target: opts.target }), 'run-one');
        yield prompt_for_nx_cloud_1.promptForNxCloud(nxArgs.scan);
        const projectGraph = project_graph_1.createProjectGraph();
        const { projects, projectsMap } = getProjects(projectGraph, nxArgs.withDeps, opts.project, opts.target);
        const env = file_utils_1.readEnvironment(opts.target, projectsMap);
        const reporter = nxArgs.withDeps
            ? new (require(`../tasks-runner/run-one-reporter`).RunOneReporter)(opts.project)
            : new empty_reporter_1.EmptyReporter();
        run_command_1.runCommand(projects, projectGraph, env, nxArgs, overrides, reporter, opts.project);
    });
}
exports.runOne = runOne;
function getProjects(projectGraph, includeDeps, project, target) {
    let projects = [projectGraph.nodes[project]];
    let projectsMap = {
        [project]: projectGraph.nodes[project],
    };
    if (includeDeps) {
        const s = require(`../core/project-graph`);
        const deps = s.onlyWorkspaceProjects(s.withDeps(projectGraph, projects))
            .nodes;
        const projectsWithTarget = Object.values(deps).filter((p) => project_graph_utils_1.projectHasTarget(p, target));
        return {
            projects: projectsWithTarget,
            projectsMap: deps,
        };
    }
    else {
        return { projects, projectsMap };
    }
}
```
the variable `projectsToRun` from `let projects = [projectGraph.nodes[project]]` return `[undefined]` because `projectGraph.nodes['app']` does not exist in our projects in nx.json

this is due to Ionic cordova executing `ng run app:ionic-cordova-serve` and not `ng run [app_name_in_nx_json]:ionic-cordova-serve`. I did not find any way to configure this with the Ionic CLI, it will always use `app:`.

It worked fine in the v10. It seems the task runner was not running when building with ionic prior to v11.

Any workaround to deactivate the task runner when building with Ionic CLI ? Or to fix the `app` problem in Ionic CLI ?

**Comment by FrozenPandaz** [comment] 2021-02-05 21:33
Hi, can you please provide a repo that will help us reproduce the issue?

**Comment by nrcaz** [comment] 2021-02-08 09:30
I finally found a way for the Ionic cli to use the correct app name specified in nx.json

I had to set defaultProject in `ionic.config.json`
```js
{
  "defaultProject": "[app_name_in_nx_json]",
}
```

**Comment by vsavkin** [comment] 2021-02-09 17:33
@nrcaz are you able to resolve your issue? Could you provide a repro if you haven't resolved it.

**Comment by vsavkin** [comment] 2021-02-22 18:46
Folks, I'm going to close this issue. If the issue isn't resolved, could you please reopen it.

Thank you!

**Closed by vsavkin** 2021-02-22 18:46 UTC
Labels: blocked: repro needed, scope: misc, type: bug
