### ISSUE TITLE
build-storybook missing project storybooks

### ISSUE THREAD

**Issue by allpwrfulroot** [nrwl/nx#2485] opened 2020-02-14 16:29 UTC
## Expected Behavior

When I run the script "build:storybook": "build-storybook", I would expect all underlying storybooks to be included in a static build (the generator itself added both root and project .storybook)

## Current Behavior

The build completes, but none of the underlying storybook components are included? The built site just hangs.

## Failure Information (for bugs)

No console logs or other information available 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create a storybook as instructed: nx g @nrwl/react:storybook-configuration shared-components (for libs/shared-components)
2. Add button story to storybook, confirm on localhost
3. add script to package.json: "build:storybook": "build-storybook"
4. yarn build:storybook
5. open static build

### Context

- version of Nx used 
@nrwl/next : 9.0.0, etc
- 3rd-party libraries and their versions
storybook ^5.3

**Comment by maxigimenez** [comment] 2020-02-17 10:22
We got similar issue for angular projects, it always tries to compile the `defaultProject`, not the selected one.

**Comment by isaacplmann** [comment] 2020-02-21 18:50
Can someone provide a reproduction of this issue?

@maxigimenez how are you specifying the selected project?

**Comment by maxigimenez** [comment] 2020-02-21 19:32
@isaacplmann Yes, we run `nx run application storybook` and it always pick the defaultProject.
We found a workaround creating a library call `storybook` on angular.json with build configuration.

**Comment by jerryorta-dev** [comment] 2020-06-12 19:57
Add this to your `package.json` scripts:

```
"build-storybook": "nx run storybook:build-storybook"
```

then run:

```
yarn build-storybook 
```

**Comment by mandarini** [comment] 2020-07-29 16:04
Hi there! I am closing this issue since it seems to be solved with the solution provided by @jerryorta-dev !

**Closed by mandarini** 2020-07-29 16:04 UTC
Labels: scope: storybook, type: bug
