### ISSUE TITLE
Caret (^) dependency identification not working

### ISSUE THREAD

**Issue by vacodoceo** [nrwl/nx#13414] opened 2022-11-25 18:39 UTC
### Current Behavior

I have a monorepo with 2 apps and 1 lib. Each app has the lib path registered in its `tsconfig.json` as follow:

```json
{
  ...
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      ...
      "@some/lib/*": ["../../libs/somelib/*"]
    }
  }
}
```

And I'm importing lib resources from the apps as follow:

```typescript
import { sum } from '@some/lib/math/sum';
```

Everything works right except for the dependency from both apps to the lib. When running `nx graph` there isn't any dependency, and when the lib is modified, `nx affected target=build` command won't run on any app even though build target has `["production", ^production"]` as input.

### Expected Behavior

lib dependency from apps should be identified automatically when importing lib resources from apps

### Steps to Reproduce

See current behavior

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   npm  : 7.24.2
   
   nx : 15.2.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.1
   @nrwl/js : 15.2.1
   @nrwl/linter : 15.2.1
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.2.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.1
   @nrwl/workspace : 15.2.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by FrozenPandaz** [comment] 2022-11-25 19:18
So you have `app1/tsconfig.json` and `app2/tsconfig.json` each with the same paths defined?

If you break out the paths into a `tsconfig.base.json` in the root, the graph should be correct and it should be easier to maintain.

**Comment by vacodoceo** [comment] 2022-11-28 01:18
That works for the graph, but I also have "internals" paths in each `app1/tsconfig.json`. My paths for app1 are:

```
"paths": {
  "@domain/*": ["src/domain/*"],
  "@data/*": ["src/data/*"],
  "@presentation/*": ["src/presentation/*"],
  ...

  "@some/lib/*": ["../../libs/somelib/*"]
}
```

In theory, I could define all those "internals" path in the `tsconfig.base.json`, but I'd prefer to avoid that if possible.

**Comment by vacodoceo** [comment] 2022-11-28 01:27
Also, I just found a workaround for this. I added my lib path to the `tsconfig.base.json` in root using the same path alias:

```
// tsconfig.base.json
{
  ...
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@some/lib/*": ["libs/somelib/*"]
    }
  }
}
```

And the graph started working without affecting any app (because each app has its own `paths` overwriting this). Probably not the best solution, but I think I'm sticking with that.

**Comment by AgentEnder** [comment] 2023-05-04 18:51
Yeah, this is the expected behavior. Nx only looks at the root tsconfig for paths to avoid dramatically overcomplicating some sections of our codebase. I'm going to close this out, since it has been answered.

**Closed by AgentEnder** 2023-05-04 18:51 UTC
Labels: type: bug, scope: core
