### ISSUE TITLE
Adding an angular library fails with: 'style' is not found in schema

### ISSUE THREAD

**Issue by heddendorp** [nrwl/nx#8528] opened 2022-01-14 11:45 UTC
## Current Behavior

Running `nx g @nrwl/angular:library apply --lazy --parentModule .\apps\tumi-app\src\app\app.module.ts --routing`  fails with `'style' is not found in schema`

## Expected Behavior

A new library should be generated

## Steps to Reproduce

1. Clone https://github.com/heddendorp/tumi-app
2. Run `nx g @nrwl/angular:library apply --lazy --parentModule .\apps\tumi-app\src\app\app.module.ts --routing`

It happens in my repo https://github.com/heddendorp/tumi-app

### Failure Logs

`'style' is not found in schema`

### Environment

```
 NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : win32 x64
  yarn : 1.22.17

  nx : 13.4.4
  @nrwl/angular : 13.4.4
  @nrwl/cli : 13.4.4
  @nrwl/cypress : 13.4.4
  @nrwl/devkit : 13.4.4
  @nrwl/eslint-plugin-nx : 13.4.4
  @nrwl/express : undefined
  @nrwl/jest : 13.4.4
  @nrwl/linter : 13.4.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.4
  @nrwl/nx-cloud : 13.0.2
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.4
  @nrwl/web : undefined
  @nrwl/workspace : 13.4.4
  @nrwl/storybook : 13.4.4
  @nrwl/gatsby : undefined
  typescript : 4.5.4
  rxjs : 7.5.2
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.1.2
         @angular/cdk: 13.1.2
         @angular/common: 13.1.2
         @angular/compiler: 13.1.2
         @angular/core: 13.1.2
         @angular/forms: 13.1.2
         @angular/material: 13.1.2
         @angular/material-luxon-adapter: 13.1.2
         @angular/platform-browser: 13.1.2
         @angular/platform-browser-dynamic: 13.1.2
         @angular/platform-server: 13.1.2
         @angular/router: 13.1.2
         @angular/service-worker: 13.1.2
         @auth0/auth0-angular: 1.8.2
         @ngneat/tailwind: 7.0.3
         @nguniversal/express-engine: 13.0.1
         apollo-angular: 2.6.0
         @angular-devkit/architect: 0.1301.3
         @angular-devkit/build-angular: 13.1.3
         @angular/cli: 13.1.3
         @angular/compiler-cli: 13.1.2
         @angular/language-service: 13.1.2
         @nguniversal/builders: 13.0.1

(node:26896) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\hedde\code\tumi-app\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by FrozenPandaz** [comment] 2022-01-15 00:40
Duplicate of https://github.com/nrwl/nx/issues/8252 which has been fixed.

Yes, please remove the `"style": "scss"` from `nx.json`. There will be a migration for this.

**Closed by FrozenPandaz** 2022-01-15 00:40 UTC
Labels: type: bug

**Comment by CutieDaisy** [comment] 2022-05-16 22:24
I have the same error " 'styles' is not found in schema" but my nx.json doesn't have `"style": "scss"` and yet it does work
