### ISSUE TITLE
Broken migration step

### ISSUE THREAD

**Issue by BedfordPeterson** [nrwl/nx#5772] opened 2021-05-25 13:17 UTC
## Current Behavior
When running nx migrate --run-migrations=migrations.json, migration step "update-angular-config-v12" throws the following.

![image](https://user-images.githubusercontent.com/1258403/119500313-a7bc8b80-bd35-11eb-8380-05c73b3a88d0.png)

## Expected Behavior
Expect to run all the migration steps without generating an error.

## Steps to Reproduce

1. Run `nx migrate latest`
2. Run `npm install`
3. Run `nx migrate --run-migrations=migrations.json`

If I remove `update-angular-config-v12` step from the migrations.json file, all the other steps complete without an issue.

But then my angular project will not compile.

## Additional info
I went through the migrate process several times.  My starting version was nx@11.6.1 and I'm trying to get to 12.3.4.

The first time I just ran `nx migrate latest`.  When that failed as described above, I ran `git reset --hard` and deleted the migrations.json file.

The next time I ran `nx migrate 11.6.3` and ran `npm install`.  A migrations.json file was not created.  Then I ran `nx migrate 12.3.4`, `npm install`, and `nx migrate --run-migrations=migrations.json`.  And I got the same error as described above.

**Comment by leosvelperez** [comment] 2021-05-25 13:29
I'll close this one since it is a duplicate of https://github.com/nrwl/nx/issues/5655. Please follow that other issue for updates.

In [this comment](https://github.com/nrwl/nx/issues/5655#issuecomment-841129955) you can check a possible cause to why the issue is happening.

**Closed by leosvelperez** 2021-05-25 13:29 UTC
Labels: type: bug
