### ISSUE TITLE
NX Storybook Error: "Jest Encountered An Unexpected Token"

### ISSUE THREAD

**Issue by ashblue** [nrwl/nx#12465] opened 2022-10-07 19:20 UTC
## Current Behavior

With the default Storybook generated Jest config. It fails to detect TypeScript errors and cannot import enums when running tests. This results in the Jest error `Jest Encountered An Unexpected Token`.

## Expected Behavior

Errors should be picked up when running tests for typings and enums should import just fine.

## Steps to Reproduce

Create an enum in a library outside of Storybook.

```typescript
export enum MyEnum {
  A
}
```

Import the enum into the Storybook file.

```typescript
import { MyEnum } from '@name/data';

export function FormFields {
  const myImport = MyEnum.A;
}

export default FormFields;
```

Then run the following command and you will get a jest cannot import token error.

```bash
nx test --project=storybook
```

This can be fixed by replacing the `jest.config.ts` with the latest auto generated library version.

```typescript
/* eslint-disable */
export default {
  displayName: 'ui',
  preset: '../../jest.preset.js',
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
    },
  },
  transform: {
    '^.+\\.[tj]sx?$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  coverageDirectory: '../../coverage/libs/ui',
  coverageThreshold: {
    '*/**': {
      branches: 20,
      functions: 20,
      lines: 20,
      statements: 20,
    },
  },
};
```

### Failure Logs

```
Jest Encountered An Unexpected Token
```

### Environment

```
   Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx : 14.7.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.7.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.8
   @nrwl/eslint-plugin-nx : 14.7.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.8
   @nrwl/js : 14.7.8
   @nrwl/linter : 14.7.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.7.8
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.8
   @nrwl/web : 14.7.8
   @nrwl/workspace : 14.7.8
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by mandarini** [comment] 2022-10-11 09:43
Hi there @ashblue ! Unfortunately I could not reproduce your issue. Here is my [reproduction repository](https://github.com/mandarini/jest-issue).

As you suggested:
1. I created a React app with Storybook
2. I created a library with an `enum`
3. I imported that `enum` both in a React component in a `.stories.ts` file.
4. I ran `nx test` to test my app
5. Everything works as expected and the tests pass.

Can you please take a look at my repository, and try to create a reproduction repository for the issue you are facing, so that I can help?

Thank you!

**Comment by ashblue** [comment] 2022-10-12 17:05
Taking a look here. I'll cross compare some files to see what may have caused it on my end.

**Comment by ashblue** [comment] 2022-10-12 17:14
Okay it looks like the babel compiler is being used which we had to change in Storybook. I think the enum has to be imported as `Data.A` to trigger the broken compilation instead of `Data['A']`. If that doesn't trigger it feel free to close. We can always re-open if other people run into the same issue again later.

https://github.com/mandarini/jest-issue/blob/main/apps/web/src/app/kater/kater.tsx#L7

**Comment by mandarini** [comment] 2022-10-13 08:52
Hi @ashblue ! I [changed `Data['A']` to `Data.A`](https://github.com/mandarini/jest-issue/blob/main/apps/web/src/app/kater/kater.tsx#L7) and the tests still pass... I will close this for now, but please if you manage to reproduce this, can you share the repository with me so that I can look into it? It's very important for us to offer the best experience possible! 

Thank you very much for looking into this!

**Closed by mandarini** 2022-10-13 08:52 UTC
Labels: type: bug, blocked: repro needed, scope: storybook
