### ISSUE TITLE
Generated `tsconfig.lib.json`, `tsconfig.spec.json` misses `composite: true`

### ISSUE THREAD

**Issue by jindong-zhannng** [nrwl/nx#20957] opened 2023-12-30 17:58 UTC
### Current Behavior

1. Vitest generator generated `tsconfig.spec.json` file and @nx/js:lib generated `tsconfig.lib.json` don't set `compilerOptions.composite` to true. As [Typescript's document](https://www.typescriptlang.org/docs/handbook/project-references.html#composite) says "Referenced projects must have the new composite setting enabled", tsc will also report error.

2. Once `compilerOptions.composite` is set, Typescript normally also complains `File '/.../some-src-code.ts' is not listed within the file list of project '/.../tsconfig.spec.json'. Projects must list all files or use an 'include' pattern.` when a test file imports a source code file. This because `tsconfig.spec.json` only includes test file without source files.

### Expected Behavior

1. Set `compilerOptions.composite` to true by default.
2. No errors when importing src code in test files

### Steps to Reproduce

1. `nx generate vitest ...`
2. Write some codes and tests

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin-x64
   pnpm   : 8.13.1
   
   nx (global)        : 17.2.6
   nx                 : 17.2.7
   @nx/js             : 17.2.7
   @nx/linter         : 17.2.7
   @nx/eslint         : 17.2.7
   @nx/workspace      : 17.2.7
   @nx/eslint-plugin  : 17.2.7
   @nrwl/tao          : 17.2.6
   @nx/vite           : 17.2.7
   typescript         : 5.3.3
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

For issue 2, I am not sure what's the best practice, but add a project reference to `tsconfig.lib.json` in `tsconfig.spec.json` can solve it.

But after that the dependency graph between tsconfig files will be:

```
tsconfig.json  ---->  tsconfig.lib.json
      |                    ↑
      |                    |
      └-------------> tsconfig.spec.json                                 
```

Not sure if it's a good practice.

**Comment by jindong-zhannng** [comment] 2024-01-01 05:11
Actually I found I don't quite understand why these project references are laid out like this in generated tsconfigs.

In my understanding, a `tsconfig.json` normally means an entry point to an independent project. And project dependencies will be expressed explicitly by `references` option in each projects' `tsconfig.json`. Just like [this demo](https://github.com/RyanCavanaugh/project-references-demo) shows: `animals` depends on `core`, so animals' `tsconfig.json` also references core's `tsconfig.json`. **It's straightforward.**

However for nx generated tsconfigs,
1. Project-level tsconfigs don't reference each other at all, even through they have dependencies.
2. Inside each project, seams there are another two sub-projects, i.e., `tsconfig.lib.json` for source codes and `tsconfig.spec.json` for test codes. Both of them are referenced by project's `tsconfig.json`. But again, they don't reference each other even through they have dependencies (typically tests depend on sources).

It's quite hard to understand for me. What's the reason of such layout? And how typescirpt compiler works under this structure?

**Comment by Hotell** [comment] 2024-01-02 09:13
AFAIK this works as expected. 

nx projects are using TS solution config. learn more here https://github.com/microsoft/fluentui/blob/master/rfcs/shared/build-system/02-solution-style-ts-configs.md#detailed-design-or-proposal

**Comment by jindong-zhannng** [comment] 2024-01-03 03:17
Thanks for your info @Hotell . I checked the document you referred. It's interesting but I noticed this doc were written 3 years ago. 

I'm not sure if it's still up-to-date, but I'm pretty sure `composite: true` is necessary now.

Here is a reproduction: https://stackblitz.com/edit/stackblitz-starters-ctswtp?file=tsconfig.spec.json. You can run `npm run build` to see error outputs like:

```
tsconfig.json:6:5 - error TS6306: Referenced project '/home/projects/stackblitz-starters-ctswtp/tsconfig.lib.json' must have setting "composite": true.

6     {
      ~
7       "path": "./tsconfig.lib.json"
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8     },
  ~~~~~

tsconfig.json:9:5 - error TS6306: Referenced project '/home/projects/stackblitz-starters-ctswtp/tsconfig.spec.json' must have setting "composite": true.

 9     {
       ~
10       "path": "./tsconfig.spec.json"
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11     }
   ~~~~~
```

**Comment by jaysoo** [comment] 2024-01-09 18:39
As @Hotell mentioned, this is by design and no a bug per-se. You are free to add `composite: true` after the generator runs. Adopting proper project references is a larger design change that affects all Nx workspaces, not just vitest.

Closing for now, but feel free to open a [discussion](https://github.com/nrwl/nx/discussions) on this topic.

**Closed by jaysoo** 2024-01-09 18:39 UTC
Labels: type: bug, scope: js
