### ISSUE TITLE
Error: Unable to resolve @nrwl/node:execute.

### ISSUE THREAD

**Issue by icastillejogomez** [nrwl/nx#9168] opened 2022-03-03 04:10 UTC
## Current Behavior
I'm receiving this error after clean express template created:

```
❯ npx create-nx-workspace
npx: instaló 48 en 13.442s
✔ Workspace name (e.g., org name)     · bullflix-nx
✔ What to create in the new workspace · express
✔ Application name                    · api
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

 >  NX   Nx is creating your v13.8.4 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace.
❯ cd bullflix-nx/
❯ nx run api:serve
Error: Unable to resolve @nrwl/node:execute.
Cannot find executor 'execute' in /Users/nacho/Code/bullflix-nx/node_modules/@nrwl/node/executors.json.
    at Workspaces.readExecutor (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/tao/src/shared/workspace.js:92:19)
    at getExecutorForTask (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22)
    at getCustomHasher (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)
    at TasksSchedule.<anonymous> (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/nacho/Code/bullflix-nx/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/nacho/Code/bullflix-nx/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
Unexpected error:
Error: Unable to load hasher for task "api:serve"
    at getCustomHasher (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:145:15)
    at TasksSchedule.<anonymous> (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)
    at Generator.next (<anonymous>)
    at /Users/nacho/Code/bullflix-nx/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/nacho/Code/bullflix-nx/node_modules/tslib/tslib.js:113:16)
    at TasksSchedule.hashTask (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:113:38)
    at TasksSchedule.<anonymous> (/Users/nacho/Code/bullflix-nx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:58:24)
    at Generator.next (<anonymous>)
    at /Users/nacho/Code/bullflix-nx/node_modules/tslib/tslib.js:117:75
```

## Expected Behavior
Start the server

## Steps to Reproduce
Run `npx create-nx-workspace` or `npx create-nx-workspace@latest` and the run `nx serve api` or `nx run api:serve`

Repo example(https://github.com/icastillejogomez/bullflix-nx)

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Environment
MacOS with the latest os version.

```
❯ node -v
v16.13.1
❯ npm -v
6.14.15
❯ yarn -v
1.22.11
```

**Comment by dayanandgarg** [comment] 2022-03-03 06:46
This is the issue with latest version, working fine in @nrwl packages versions 13.4.1

**Comment by tanyudii** [comment] 2022-03-03 08:11
Same problem with version 13.8.4.
Rollback to version 13.8.3 and working fine

**Comment by clementguillot** [comment] 2022-03-03 08:21
The issue also affects existing repo and `nx build ...` command.

**Comment by Michsior14** [comment] 2022-03-03 09:16
Same with `@nrwl/node:package` on 13.8.4.

**Comment by AliYusuf95** [comment] 2022-03-03 10:21
This happened in the latest release 13.8.4.
@jaysoo I think migrations in #9086 prepared for 13.9.0 but it got released before that.

**Comment by Jeffrey-Zutt** [comment] 2022-03-03 10:37
We're experiencing the same problem after upgrading from 13.8.3 to 13.8.4.

**Comment by clementguillot** [comment] 2022-03-03 14:21
@AliYusuf95 I confirm that the issue is fixed once executers are patched. Thanks!

**Comment by icastillejogomez** [comment] 2022-03-03 18:34
Great! Should generate a new versión without errors. Thank you so much mates!

**Comment by ChristianMatthias** [comment] 2022-03-04 10:10
I encountered this issue too.
Replacing all occurrences of 
`"executor":"@nrwl/node:execute"`  
with  
`"executor": "@nrwl/node:node"`
in the project.json file (just make a project-wide search for the string "node:execute" and you should find it).

**Comment by teklakct** [comment] 2022-03-04 11:30
here you will find all the changes and motivation for making them https://github.com/nrwl/nx/pull/9086

**Comment by vecernik** [comment] 2022-03-04 13:12
shouldn't be this a part of a migration?

**Closed** 2022-03-04 13:15 UTC
Labels: type: bug, scope: node

**Comment by tanyudii** [comment] 2022-03-04 13:42
> @icastillejogomez To fix the issue just replace the following executers:
> 
> * `"executor": "@nrwl/node:execute"` -> `"executor": "@nrwl/node:node"`
> * `"executor": "@nrwl/node:build"` -> `"executor": "@nrwl/node:webpack"`

Its stil not working for build Nest.js Application

> Error: Unable to resolve @nrwl/node:package.

**Comment by icastillejogomez** [comment] 2022-03-04 13:44
I didn't tried with Nest lib. I'm using Next.js, express, react and some node in-house libs.

**Comment by beeman** [comment] 2022-03-04 14:55
> shouldn't be this a part of a migration?

It looks like the migration is there but won't be triggered until Nx 13.9.0

**Comment by bennycode** [comment] 2022-03-09 17:22
I upgraded from v13.8.3 to v13.8.5 which got me this error:

> Error: Unable to resolve @nrwl/node:build

Will try to replace `"executor": "@nrwl/node:build"` with `"executor": "@nrwl/node:webpack"`...

**Comment by anandsathe67** [comment] 2022-03-11 12:37
With 13.8.5 - still having trouble:
`Error: Unable to resolve @nrwl/node:package.
Cannot find executor 'package' in /Users/anand/GitHub/xxx/node_modules/@nrwl/node/executors.json.
    at Workspaces.readExecutor (/Users/anand/GitHub/xxx/node_modules/@nrwl/tao/src/shared/workspace.js:92:19)
    at getExecutorForTask (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22)
    at getCustomHasher (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25)
    at TasksSchedule.<anonymous> (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)`

**Comment by AlexLeung** [comment] 2022-03-15 09:05
> @icastillejogomez To fix the issue just replace the following executers:
> 
> * `"executor": "@nrwl/node:execute"` -> `"executor": "@nrwl/node:node"`
> * `"executor": "@nrwl/node:build"` -> `"executor": "@nrwl/node:webpack"`

They need to stop making these breaking changes in non major upgrades

**Comment by anandsathe67** [comment] 2022-03-17 06:36
> With 13.8.5 - still having trouble: `Error: Unable to resolve @nrwl/node:package. Cannot find executor 'package' in /Users/anand/GitHub/xxx/node_modules/@nrwl/node/executors.json. at Workspaces.readExecutor (/Users/anand/GitHub/xxx/node_modules/@nrwl/tao/src/shared/workspace.js:92:19) at getExecutorForTask (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22) at getCustomHasher (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25) at TasksSchedule.<anonymous> (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)`
Issue still exists in 13.9.1 - this is pretty vexing. Was hoping i wouldnt have to patch n but I guess fixing this doesnt seem to be a priority. Thanks @AlexLeung @tanyudii

**Comment by jberrydev** [comment] 2022-03-24 22:53
Yea what should we change `node:package` to? `node:webpack`?

**Comment by jaypersanchez** [comment] 2022-03-26 00:17
> * @nrwl/node

I 

> > With 13.9.2 - still having trouble: `Error: Unable to resolve @nrwl/node:package. Cannot find executor 'package' in /Users/anand/GitHub/xxx/node_modules/@nrwl/node/executors.json. at Workspaces.readExecutor (/Users/anand/GitHub/xxx/node_modules/@nrwl/tao/src/shared/workspace.js:92:19) at getExecutorForTask (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22) at getCustomHasher (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25) at TasksSchedule.<anonymous> (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)`
> > Issue still exists in 13.9.1 - this is pretty vexing. Was hoping i wouldnt have to patch nrwl but I guess fixing this doesn't seem to be a priority. Thanks @AlexLeung @tanyudii



> > With 13.9.2 - still having trouble: `Error: Unable to resolve @nrwl/node:package. Cannot find executor 'package' in /Users/anand/GitHub/xxx/node_modules/@nrwl/node/executors.json. at Workspaces.readExecutor (/Users/anand/GitHub/xxx/node_modules/@nrwl/tao/src/shared/workspace.js:92:19) at getExecutorForTask (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:22) at getCustomHasher (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:25) at TasksSchedule.<anonymous> (/Users/anand/GitHub/xxx/node_modules/@nrwl/workspace/src/tasks-runner/tasks-schedule.js:114:62)`
> > Issue still exists in 13.9.1 - this is pretty vexing. Was hoping i wouldnt have to patch nrwl but I guess fixing this doesn't seem to be a priority. Thanks @AlexLeung @tanyudii

  I have NX version 13.9.5 and I still get the error above.  My DevDependencies in package.json for "@nrwl" is on 13.3.6.  This is all on Windows 10.  Everything is fine on my MacOS with NX version 13.3.6. So I am trying to downgrade the NX version on the Windows laptop from 13.9.5 to 13.3.6 but I'm not having any luck.

**Comment by jaypersanchez** [comment] 2022-03-26 00:17
I have NX version 13.9.5 and I still get the error above.  My DevDependencies in package.json for "@nrwl" is on 13.3.6.  This is all on Windows 10.  Everything is fine on my MacOS with NX version 13.3.6. So I am trying to downgrade the NX version on the Windows laptop from 13.9.5 to 13.3.6 but I'm not having any luck.

**Comment by jedihacks** [comment] 2022-04-05 13:46
> * `"executor": "@nrwl/node:node"`

Maybe I'm missing something here - but I generated a brand new nx project and doing a **find all** for "executor": "@nrwl/node:node" doesn't yield any results.   I tried adding it in both workspace.json and angular.json (just in case) but neither made a difference.

I originally generated the project with the latest nx for angular (13.9.6) and then I've been slowly downgrading to try to get back to where it works.  I think perhaps similar issue to @jaypersanchez 

`TypeError: Cannot read property 'split' of undefined
    at getExecutorForTask (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:129:49)
    at getCustomHasher (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:135:25)
    at TaskOrchestrator.<anonymous> (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:304:62)
    at Generator.next (<anonymous>)
    at /Users/jedidiahweller/development/Startup-Wars-App/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/tslib/tslib.js:113:16)
    at TaskOrchestrator.hashTask (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:303:38)
    at /Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:216:56
    at Array.map (<anonymous>)
Unexpected error:
Error: Unable to load hasher for task "services:build"
    at getCustomHasher (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/utils.js:140:15)
    at TaskOrchestrator.<anonymous> (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:304:62)
    at Generator.next (<anonymous>)
    at /Users/jedidiahweller/development/Startup-Wars-App/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/tslib/tslib.js:113:16)
    at TaskOrchestrator.hashTask (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:303:38)
    at /Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:216:56
    at Array.map (<anonymous>)
    at TaskOrchestrator.<anonymous> (/Users/jedidiahweller/development/Startup-Wars-App/node_modules/@nrwl/workspace/src/tasks-runner/task-orchestrator.js:216:37)`

**Comment by alexeagleson** [comment] 2022-04-22 02:24
I am getting this issue with `13.10.3`

**Comment by MartinMuzatko** [comment] 2022-05-10 07:45
I'm on a fresh installation (nx 14.1.4) and follow instructions from here: https://nx.dev/getting-started/nx-and-typescript#create-a-typescript-based-application

With a fresh nx monorepo, I still get this error:

```
Unable to resolve @nrwl/node:app.
Cannot find module '@nrwl/node/package.json'
Require stack:
- /home/martin/dev/test/rpctest/node_modules/nx/src/utils/nx-plugin.js
- /home/martin/dev/test/rpctest/node_modules/nx/src/config/workspaces.js
- /home/martin/dev/test/rpctest/node_modules/nx/src/command-line/generate.js
- /home/martin/dev/test/rpctest/node_modules/nx/src/command-line/nx-commands.js
- /home/martin/dev/test/rpctest/node_modules/nx/bin/init-local.js
- /home/martin/dev/test/rpctest/node_modules/nx/bin/nx.js
- /usr/lib/node_modules/nx/bin/nx.js
```

**Comment by vytautas-pranskunas-** [comment] 2022-05-11 10:44
I am in situaton similar to @MartinMuzatko

**Comment by integrateddigital** [comment] 2022-05-20 19:36
This breaks the tutorial https://nx.dev/getting-started/nx-and-typescript

**Comment by Signaturo** [comment] 2022-05-20 20:25
Ran into this issue while running a nest api application. The following solutions helped me:

> > @icastillejogomez To fix the issue just replace the following executers:
> > 
> > * `"executor": "@nrwl/node:execute"` -> `"executor": "@nrwl/node:node"`
> > * `"executor": "@nrwl/node:build"` -> `"executor": "@nrwl/node:webpack"`
> 

Configuration:

```
"@nrwl/cli": "13.4.6",
"@nrwl/nest": "14.1.7",
"@nrwl/workspace": "14.1.7"
```

**Comment by nhhockeyplayer** [comment] 2022-06-13 08:38
this is still happening on fresh project generations

all executors are in order

```
meanstack02@admin meanstacknh % nx report                                        

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin x64
   yarn : 1.22.18
   
   nx : 14.2.4
   @nrwl/angular : 14.2.4
   @nrwl/cypress : 14.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.4
   @nrwl/eslint-plugin-nx : 14.2.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.4
   @nrwl/js : 14.2.4
   @nrwl/linter : 14.2.4
   @nrwl/nest : 14.2.4
   @nrwl/next : Not Found
   @nrwl/node : 14.2.4
   @nrwl/nx-cloud : 14.0.8
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.4
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.4
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @ngrx/component-store: 13.2.0
   	 @ngrx/effects: 13.2.0
   	 @ngrx/entity: 13.2.0
   	 @ngrx/router-store: 13.2.0
   	 @ngrx/store: 13.2.0
   	 @nxtend/ionic-angular: 13.1.0
   	 @ngrx/schematics: 13.2.0
   	 @ngrx/store-devtools: 13.2.0
   	 @nxpm/stack: 4.21.0
```

**Comment by esantelmo** [comment] 2022-06-16 12:44
> this is still happening on fresh project generations
> 
> all executors are in order
> 
> ```
> meanstack02@admin meanstacknh % nx report                                        
> 
>  >  NX   Report complete - copy this into the issue template
> 
>    Node : 16.15.1
>    OS   : darwin x64
>    yarn : 1.22.18
>    
>    nx : 14.2.4
>    @nrwl/angular : 14.2.4
>    @nrwl/cypress : 14.2.4
>    @nrwl/detox : Not Found
>    @nrwl/devkit : 14.2.4
>    @nrwl/eslint-plugin-nx : 14.2.4
>    @nrwl/express : Not Found
>    @nrwl/jest : 14.2.4
>    @nrwl/js : 14.2.4
>    @nrwl/linter : 14.2.4
>    @nrwl/nest : 14.2.4
>    @nrwl/next : Not Found
>    @nrwl/node : 14.2.4
>    @nrwl/nx-cloud : 14.0.8
>    @nrwl/nx-plugin : Not Found
>    @nrwl/react : Not Found
>    @nrwl/react-native : Not Found
>    @nrwl/schematics : Not Found
>    @nrwl/storybook : 14.2.4
>    @nrwl/web : Not Found
>    @nrwl/workspace : 14.2.4
>    typescript : 4.7.3
>    ---------------------------------------
>    Community plugins:
>    	 @ngrx/component-store: 13.2.0
>    	 @ngrx/effects: 13.2.0
>    	 @ngrx/entity: 13.2.0
>    	 @ngrx/router-store: 13.2.0
>    	 @ngrx/store: 13.2.0
>    	 @nxtend/ionic-angular: 13.1.0
>    	 @ngrx/schematics: 13.2.0
>    	 @ngrx/store-devtools: 13.2.0
>    	 @nxpm/stack: 4.21.0
> ```

Same here in June 16th 2022

**Comment by crowmagnumb** [comment] 2022-06-24 19:05
Mine were in a different section...
```
        "serve": {
          "builder": "@nrwl/node:execute",
        },
```
But yes changing from `node:execute` to `node:node` fixed it.

**Comment by ldco2016** [comment] 2022-09-08 19:51
@crowmagnumb 

Not sure why this was closed because I upgraded to Nx `14.6.4` and Angular 14 and I am still getting the error when I run:

`nx serve <project-name> --configuration=development --open --aot --watch`

```bash
 NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin x64
   yarn : 1.22.19

   nx : 14.6.4
   @nrwl/angular : 14.6.4
   @nrwl/cypress : 14.6.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.4
   @nrwl/eslint-plugin-nx : 14.6.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.4
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.6.4
   @nrwl/nest : 14.6.4
   @nrwl/next : Not Found
   @nrwl/node : 14.6.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.4
   @nrwl/web : 14.6.4
   @nrwl/workspace : 14.6.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by HopeKenga** [comment] 2022-09-27 13:16
I am facing the same issue even after an upgrade . 

```
 NX   Report complete - copy this into the issue template

   Node : 18.8.0
   OS   : darwin arm64
   npm  : 8.18.0
   
   nx : 14.7.13
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : Not Found
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by crowmagnumb** [comment] 2022-09-27 16:23
@ldco2016 Not sure why you replied that to me. I didn´t close the issue.  :)

**Comment by akumbhani66** [comment] 2023-01-17 12:15
> I'm on a fresh installation (nx 14.1.4, using the typescript preset) and follow instructions from here: https://nx.dev/getting-started/nx-and-typescript#create-a-typescript-based-application
> 
> With a fresh nx monorepo, I still get this error:
> 
> ```
> Unable to resolve @nrwl/node:app.
> Cannot find module '@nrwl/node/package.json'
> Require stack:
> - /home/martin/dev/test/rpctest/node_modules/nx/src/utils/nx-plugin.js
> - /home/martin/dev/test/rpctest/node_modules/nx/src/config/workspaces.js
> - /home/martin/dev/test/rpctest/node_modules/nx/src/command-line/generate.js
> - /home/martin/dev/test/rpctest/node_modules/nx/src/command-line/nx-commands.js
> - /home/martin/dev/test/rpctest/node_modules/nx/bin/init-local.js
> - /home/martin/dev/test/rpctest/node_modules/nx/bin/nx.js
> - /usr/lib/node_modules/nx/bin/nx.js
> ```

@MartinMuzatko , Not sure if this issue is still persist for you. I had same issue and able to resolve it by `npm i @nrwl/node`

**Comment by dotmantosh** [comment] 2023-02-05 08:11
> The issue also affects existing repo and `nx build ...` command.

has this issue been resolved please?

**Comment by integrateddigital** [comment] 2023-02-05 08:49
Yes with rm -fr *nx*
