### ISSUE TITLE
Cannot `nx serve` @nx/node app with @nx/js library. "Cannot find module '...libname'" 

### ISSUE THREAD

**Issue by lsonnenschein** [nrwl/nx#18490] opened 2023-08-04 13:28 UTC
### Current Behavior

Serving a newly created node-app results in error 'module not found' when trying to serve after importing a library generated with @nx/js:library generator.

### Expected Behavior

App is served without error, or descriptive error message pointing out the configuration issue.

### GitHub Repo

https://github.com/lsonnenschein/module-not-found-repro

### Steps to Reproduce

1. npx create-nx-workspace@latest module-not-found-repro
√ Which stack do you want to use? · node
√ What framework should be used? · none
√ Integrated monorepo, or standalone project? · integrated
√ Application name · failing-nx-serve
√ Would you like to generate a Dockerfile? [https://docs.docker.com/] · No
√ Enable distributed caching to make your CI faster · No
2. `npx nx generate @nx/js:library util --unitTestRunner=jest --no-interactive` 
3. import util from '@module-not-found-repro/util' in main.ts
4. `nx serve module-not-found-repro` 

### Nx Report

```shell
Node   : 18.17.0
   OS     : win32-x64
   npm    : 9.6.7

   nx (global)        : 16.6.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/esbuild        : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/node           : 16.6.0
   @nrwl/tao          : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @module-not-found-repro/util
```

### Failure Logs

```shell
Error: Cannot find module '/module-not-found-repro/dist/libs/util'
Require stack:
- C:\module-not-found-repro\dist\apps\module-not-found-repro\apps\module-not-found-repro\src\main.js
- C:\module-not-found-repro\dist\apps\module-not-found-repro\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename (C:\module-not-found-repro\tmp\module-not-found-repro\main-with-require-overrides.js:41:36)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.Module._load (C:\module-not-found-repro\node_modules\@nx\js\src\executors\node\node-with-require-overrides.js:15:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\module-not-found-repro\apps\module-not-found-repro\src\main.ts:1:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The problem seems to be similar to [#16884](https://github.com/nrwl/nx/issues/16884), but the setup in my case is slightly different.

In this project, the nx graph command correctly identifies the dependency on the util library. Furthermore, libraries and applications seem to build as expected - the relevant files do exist in the /module-not-found-repro/dist/libs/util directory.

I originally ran into this issue in an older nx workspace, specifically version 15.9.2.

I've been adviced to `npm cache verify` and `npm ci`, but that fails to resolve the issue.

Please let me know if additional information is needed or if there are suggested steps to further troubleshoot this issue.

**Comment by lsonnenschein** [comment] 2023-08-22 07:40
As a temporary workaround, I've found that I can run `nx build {project}` first, and then nx serve runs without any errors.

Contrary to my initial belief, it appears that the source code is not successfully built when using nx serve. Even with the workaround, file changes do not trigger a rebuild. As a result, I have to manually run nx build {project} for every change, which severely impacts the DevX.

**Comment by victormf2** [comment] 2023-09-03 14:08
I'm having probably the same issue. I added `runBuildTargetDependencies` to my node serve target, and it seems to work. But I don't know if it's expected behavior, and the docs are not much clear about why this happens.

```json
// ...
   "serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "org-api:build",
        "runBuildTargetDependencies": true // add this
      },
      "configurations": {
        "development": {
          "buildTarget": "org-api:build:development"
        },
        "production": {
          "buildTarget": "org-api:build:production"
        }
      }
    }
// ...
```

**Comment by julesgabriel** [comment] 2023-11-15 12:26
When running npx nx serve backend (which is my app):

{
  "name": "backend",
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "backend/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nx/esbuild:esbuild",

I have the same issue there but even with the runBuildTargetDependencies it does not work:

Error: Cannot find module 'models'


I have a lib called "models"

`{
  "name": "models",
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "sourceRoot": "models/src",
  "projectType": "library",
  "targets": {
    "lint": {
      "executor": "@nx/eslint:lint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["models/**/*.ts"]
      }
    },
    "test": {
      "executor": "@nx/jest:jest",
      "outputs": ["{workspaceRoot}/coverage/{projectRoot}"],
      "options": {
        "jestConfig": "models/jest.config.ts"
      }
    },
    "build": {
      "executor": "@nx/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/models",
        "main": "models/src/index.ts",
        "tsConfig": "models/tsconfig.lib.json"
      }
    }
  },
  "tags": []
}
`

The "build" process has been added because i did not had it, but even without my models cannot be found (i'm running through npx nx serve backend)

Can someone help me please ?

**Comment by ndcunningham** [comment] 2024-06-07 22:20
Sorry for the late response. `runBuildTargetDependencies` is what you need here is the ref: https://nx.dev/nx-api/js/executors/node#runbuildtargetdependencies

@julesgabriel if you did not have the `build` target then you generated that library without setting a compiler. If you manually do this you need to also manually add the missing files that the generator would've added.

Closing as the OP issue has been addressed. Thanks!

**Closed by ndcunningham** 2024-06-07 22:20 UTC
Labels: type: bug, scope: node
