### ISSUE TITLE
The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'

### ISSUE THREAD

**Issue by playground** [nrwl/nx#311] opened 2018-03-07 02:26 UTC
I have been running on these versions and things have been working fine until today.
Angular CLI: 1.6.6
Node: 9.4.0
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.1.0
@angular/cli: error
@angular/material: 5.1.0
typescript: 2.6.2
webpack: error

The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Error: Cannot find module '@angular/compiler-cli'
    at Object.CompilerCliIsSupported (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/ngtools_api.js:25:15)
    at new AotPlugin (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:28:23)
    at _createAotPlugin (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/models/webpack-configs/typescript.js:92:16)
    at Object.getAotConfig (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/models/webpack-configs/typescript.js:129:19)
    at NgCliWebpackConfig.buildConfig (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/models/webpack-config.js:40:37)
    at Class.run (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/tasks/build.js:31:92)
    at Class.run (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/commands/build.js:250:40)
    at resolve (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@angular/cli/ember-cli/lib/models/command.js:261:20)
 
 Just upgraded to the latest Nx and cli and still get the same errors
Angular CLI: 1.7.2
Node: 9.4.0
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.1.0
@angular/cli: error
@angular/material: 5.1.0
typescript: 2.6.2
webpack: error

**Comment by playground** [comment] 2018-03-07 14:14
After I deleting node_modules and reinstalling everything again those errors went away but now I am getting different errors about our shared modules, I think this is more of a cli question at this point.

Module build failed: Error: /myproj/node_modules/@scope/shared-module/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile

**Comment by ThomasBurleson** [comment] 2018-03-07 16:13
@playground - are you using the latest v0.8.0 install of `@nrwl/nx` ?

**Comment by playground** [comment] 2018-03-07 18:36
@ThomasBurleson my existing project workspace is on "@nrwl/nx": "0.7.0-beta.2" not sure how to upgrade yet.

However, I've upgraded to latest of nx v0.8.0 @nrwl/schematics@0.8.0
When I tried to create a new workspace "create-nx-workspace me-test-workspace --directory=me-test --npm-scope=me"

```
Creating a sandbox with the CLI and Nx Schematics...
[fsevents] Success: "/private/var/folders/q_/kmwx1rtn5qz98_3v_jn32xl80000gn/T/tmp-78016m91yLEpP1Oz/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
Cached binary found at /Users/ljeff/.npm/node-sass/4.7.2/darwin-x64-59_binding.node
Binary found at /private/var/folders/q_/kmwx1rtn5qz98_3v_jn32xl80000gn/T/tmp-78016m91yLEpP1Oz/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine
added 1057 packages from 716 contributors in 23.813s
ng new "me-test-workspace" "--directory=me-test" "--npm-scope=me" --collection=@nrwl/schematics
  create me-test/README.md (1854 bytes)
  create me-test/.angular-cli.json (736 bytes)
  create me-test/.editorconfig (245 bytes)
  create me-test/.gitignore (516 bytes)
  create me-test/apps/.gitkeep (1 bytes)
  create me-test/karma.conf.js (1105 bytes)
  create me-test/libs/.gitkeep (0 bytes)
  create me-test/package.json (2044 bytes)
  create me-test/protractor.conf.js (886 bytes)
  create me-test/test.js (1033 bytes)
  create me-test/tsconfig.json (465 bytes)
  create me-test/tsconfig.spec.json (343 bytes)
  create me-test/tslint.json (2240 bytes)
Project 'me-test-workspace' successfully created.
child_process.js:614
    throw err;
    ^

Error: spawnSync /bin/sh ENOENT
    at _errnoException (util.js:1003:13)
    at Object.spawnSync (internal/child_process.js:963:20)
    at spawnSync (child_process.js:560:24)
    at Object.execSync (child_process.js:606:13)
    at Object.<anonymous> (/Users/ljeff/.nvm/versions/node/v9.4.0/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js:68:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by ThomasBurleson** [comment] 2018-03-09 14:07
@playground - yes, unfortunately there seems to be an issue with `create-nx-workspace`. Refs #232 .

**Comment by FrozenPandaz** [comment] 2018-04-02 03:38
I believe this should be fixed in extension of #232. I can no longer reproduce this with the latest version of @nrwl/schematics (v0.9.1). If no one else can either, we should be able to close this.

**Comment by ThomasBurleson** [comment] 2018-04-02 17:56
@FrozenPandaz - which SHA resolved this ?

**Comment by FrozenPandaz** [comment] 2018-04-02 18:00
Supposedly this one https://github.com/nrwl/nx/commit/da9310e9dbb4eb3294200ca72bfa70b14faec2c2; it was the fix to https://github.com/nrwl/nx/issues/232

**Comment by playground** [comment] 2018-04-02 22:50
I confirm that v0.9.1 works.

**Comment by FrozenPandaz** [comment] 2018-04-13 20:01
Closing this as it is confirmed as working.

**Closed by FrozenPandaz** 2018-04-13 20:01 UTC
Labels: blocked: more info needed
