### ISSUE TITLE
Jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG

### ISSUE THREAD

**Issue by dean-g** [nrwl/nx#8646] opened 2022-01-21 17:33 UTC
Both my jest & lint fails with the following ERROR: NX   ERROR  spawn E2BIG

this is happening only on the CI pipeline. but the same works well in my local machine. 

```
$ yarn affected:test 

yarn run v1.22.5
$ ./node_modules/.bin/nx affected:test --base=origin/test-code --parallel --detectOpenHandles --forceExit
>  NX   ERROR  spawn E2BIG
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by Jeffrey-Zutt** [comment] 2022-01-22 09:30
## Current Behavior
We are running into the same issue after updating from `13.4.5` to `13.4.6`.
Locally everything works just fine, but on our CI pipelines (gitlab) we're getting the following error:

```
$ npx nx affected:lint --base=origin/master
>  NX   ERROR  spawn E2BIG
```

## Expected Behavior

No E2BIG errors on `affected` commands.

## Steps to Reproduce

- Upgrade from `13.4.5` to `13.4.6`. 
- Run a `affected` command in a gitlab pipeline.

I will try to make a clean repository which reproduces this issue.

### Failure Logs
`>  NX   ERROR  spawn E2BIG`

### Environment
  NX  Report complete - copy this into the issue template
  Node : 16.13.2
  OS   : linux x64
  yarn : 1.22.15
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : 13.4.6
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.5.5
  rxjs : 6.6.7

**Comment by Jeffrey-Zutt** [comment] 2022-01-22 14:33
OK.  After some debugging I was able to resolve the issue in our repo.
I'll try to explain the solution, hopefully its useful for others as well.

Also: Thank you for building NX! It's an awesome tool and we love using it.

# Our setup:

## 1. We specify cypress cache folder:
```
variables:
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
```

## 2. We specify a cache object:
```
.cache_deps: &cache_deps
  key:
    files:
      - yarn.lock
  paths:
    - cache/Cypress
    - node_modules
```

## 3. We have an 'install' job.
```
install:
  image: node:lts-slim
  cache:
    <<: *cache_deps
    policy: push
  script:
    - yarn install --frozen-lockfile
```

_Note: cypress cache-folder amounts to almost 26.000 (!) files._

## 4. We have a 'lint' job.
```
lint:
  image: node:lts
  cache:
    <<: *cache_deps
    policy: pull
  script:
    - npx nx affected:lint --base=origin/master
```

Result:
```
$ npx nx affected:lint --base=origin/master
>  NX   ERROR  spawn E2BIG
```

# The solution:

Cypress cache is adding ~26.000 files which all are checked in the `affected`  command.
In our case, adding `/cache` (our custom cypress cache location) to `.gitignore` notifies NX to ignore all of these files. 

The `affected:lint` command to now run smoothly again for us.

**Comment by dean-g** [comment] 2022-01-24 14:50
Thanks a lot, @Jeffrey-Zutt. that worked for me!

**Comment by vinothvk** [comment] 2022-01-24 22:02
this issue happens for me after i upgrade from 13.4.4 to 13.4.6
since i am using default cacheDirectory the solution doesn't apply. If i revert back the upgrade everything works fine
it is reproducible only in our Jenkins Linux env not in Mac OS locally
unfortunately i can not provide any reproducible repo since it is a private project

**Comment by atomicrobokid** [comment] 2022-01-25 09:26
Exactly the same happens for me on `13.4.6` - downgrading to `13.4.4` solves the issue

**Comment by FrozenPandaz** [comment] 2022-01-29 00:40
This is likely a real issue. We'll investigate it.

**Comment by dennisluitwieler** [comment] 2022-02-04 21:49
We're currently also experiencing this (still running the 13.4.5-beta.7 versions of @nrwl packages), but I have seen it work in our setup when linting only a few libraries. When we started linting + reports all of our ~60 libraries, we ran into this issue.

Unfortunately this is also a private repository, so I can't give you a repo to reproduce it.

@FrozenPandaz  Is there any information you need about our setup to help figure out where the problem is at?

**Comment by dennisluitwieler** [comment] 2022-02-04 21:58
I don't fully understand the explanation of @Jeffrey-Zutt but in our case I believe cypress isn't involved because it isn't executed yet in the step where we're encountering this problem.

However, he mentioned the problem of their cypress cache files being a problem and we do have a dist/ folder and test coverage/ folder full of generated files when this linter process is being executed. Not sure if that is relevant since we are not using the nx affected commands here.

**Comment by dennisluitwieler** [comment] 2022-02-04 23:29
I found found a solution that seems to work.
I added these folders to my .gitignore file:

.angular    # angular caching ?
dist            # output folder for the build
lint-report # our folder with lint report (json) files 
coverage  # our code coverage results folder
jest_rt       # unknown, something jest created in our pipeline while running the tests with code coverage

This last one is created when jest is running with code coverage and that folder will contain A LOT of data.

**Comment by muuvmuuv** [comment] 2022-02-07 12:51
Experiencing this with `nx build` and v13.7.3. BitBucket Pipelines failing with E2BIG. Already allocated `size: 2x` for more memory, unsuccessfully. We put all cache stuff from nx and angular into `.cache` but even this (is ignored) does not work. Cypress also lies in .cache.

**Comment by muuvmuuv** [comment] 2022-02-07 13:51
Did a `git status` before the crash and found out that I had `.pnpm-store` not added to .gitignore... fixed ^^

**Comment by vinothvk** [comment] 2022-02-07 23:11
> Did a `git status` before the crash and found out that I had `.pnpm-store` not added to .gitignore... fixed ^^

Adding .pnpm-store to git ignore resolved build issue for me in Jenkins. Thanks

**Comment by doppeldenken** [comment] 2022-02-11 09:47
This is happening to me too, using GitLab's Auto DevOps.

When running `/bin/herokuish buildpack test` on the `test` job, it fails with:

```
> nx run-many --all --target=test
 >  NX   spawn E2BIG
```

`nx` version: `13.8.0`

Downgrading to `13.4.4` fixes the issue.

**Comment by rubiagatra** [comment] 2022-02-14 08:27
Yep I am facing this is an issue also with freshly apps workspace and adding new node app using `@nrwl/node` generator

```
yarn run v1.22.17
$ nx serve

 >  NX   spawn E2BIG


error Command failed with exit code 1.
```

which version that is working properly?

**Comment by jlp0328** [comment] 2022-02-23 20:21
We are running into this issue at my organization and have tried all of the above suggestions including updating our `.gitignore`. Ultimately, we had to downgrade to 13.4.4 (from 13.8.2) because this is blocking a release for our product after an Angular 13 upgrade. 

On our side, I'm not sure what could possibly be causing this error. We will be on the lookout for further updates. 

Thank you!

**Comment by dfeyer** [comment] 2022-02-25 22:56
We just merge a medium size NextJS app to our monorepos and face the same error, during built, link or write check (NX 13.8.3)

**Comment by dfeyer** [comment] 2022-02-27 16:24
> We just merge a medium size NextJS app to our monorepos and face the same error, during built, link or write check (NX 13.8.3)

In our case we can limit the impact of the bug by updating the .gitignore in the docker container to skip some files and lower the uncommited changes. We never commit from the container so it's not a big issue ... but feel a bit bad to have this workaround in place.

**Closed** 2022-03-01 16:45 UTC
Labels: type: bug, scope: core

**Comment by barinascode** [comment] 2022-05-09 14:02
nx serve 
   spawn E2BIG
