### ISSUE TITLE
After nx upgrade I start to get error in storybook ReactDOM.render is no longer supported in React 18

### ISSUE THREAD

**Issue by ofirrifo** [nrwl/nx#10541] opened 2022-06-01 13:20 UTC
## Current Behavior
I get this error `ReactDOM.render is no longer supported in React 18` in story book after I used this commands
`nx migrate latest`
and then
`nx migrate --run-migrations`

## Expected Behavior
I expected that if I'm using the command for upgrade nx project in my example
it update react from 17 to 18 and update the story book as well it should work without error  about 
ReactDOM.render is no longer supported in React 18

## Steps to Reproduce
- Take an nx project with react version 17.x.x and has story book
- execute this command `nx migrate latest`
- execute this command `nx migrate --run-migrations`
- execute this command `nx run <project name>:storybook`
- open chrome dev tools and you will see 
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

### Failure Logs

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by gperdomor** [comment] 2022-06-01 18:23
Same here

**Comment by jaysoo** [comment] 2022-06-08 14:28
Looks like the issue is on the storybook side. If you only see the error once, then it is supposed to be fine. 

https://github.com/storybookjs/storybook/issues/17831#issuecomment-11

Closing this since the issue is somewhat resolved, and remaining problem with Storybook Manager is something that needs to be done on their end.

**Closed by jaysoo** 2022-06-08 14:28 UTC
Labels: type: bug, scope: storybook

**Comment by mandarini** [comment] 2022-06-08 14:36
Thank you @jaysoo for helping out, here!
