### ISSUE TITLE
Nx fresh setup using the CLI with Next.js but the Fast Refresh is not working

### ISSUE THREAD

**Issue by romshiri** [nrwl/nx#9782] opened 2022-04-11 10:21 UTC
## Current Behavior
I created a fresh Nx workspace including a Next.JS app, following the guide in the documentation. 
Everything works as expected beside the Fast Refresh/Hot Reload - when changing one of the .tsx files - it doesn't reflected in the browser automatically - you have to manually refresh the page.

I haven't changed anything in the code, just use everything as-is from the generator. 
Tried the same with React app (not next.js) and it worked fine.
Not sure what I'm missing..

## Expected Behavior
Changing one of the files in the project (say, the welcome text in the index.ts) should trigger fast reload.

## Steps to Reproduce
1. Install the Nx CLI (npx create-nx-workspace@latest).
2. Create a Nx workspace with Next.js included.
3. Run `nx run serve`
4. Change a text in apps/<app-name>/pages/index.ts.
5. Hot reload/fast refersh not working.

<img width="758" alt="Screen Shot 2022-04-11 at 12 14 23" src="https://user-images.githubusercontent.com/1813531/162720580-d7e0b219-5e6c-4e8c-a55c-4729ed695383.png">

You can find a sample project here:
https://github.com/romshiri/monorepo-with-nx

### Failure Logs
No failure logs. In fact, the logs do show that fast refresh is supposed to work.

### Environment
`
 >  NX   Report complete - copy this into the issue template

   Node : 16.9.1
   OS   : darwin x64
   npm  : 8.6.0
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : 13.10.1
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : 13.10.1
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
`

**Comment by romshiri** [comment] 2022-04-11 10:49
Was able to fix it by bumping Next.js package to "next": "12.1.4" (from 12.1.2).
FYI.

**Comment by alesma** [comment] 2022-04-15 15:41
I also reproduced this issue and managed to solve it by updating the nextjs version.

**Comment by ndcunningham** [comment] 2022-05-26 20:18
It looks like we have a way to handle this. So I am going to go ahead and close it. 
Feel free to open an issue if this is still occurring with the latest version of Nx.

**Closed by ndcunningham** 2022-05-26 20:18 UTC
Labels: type: bug, scope: nextjs
