### ISSUE TITLE
Nestjs serve crash after "File change detected. Restarting..."

### ISSUE THREAD

**Issue by thenglong** [nrwl/nx#17208] opened 2023-05-25 07:41 UTC
### Current Behavior

Serve command throw error `Command failed: taskkill`

### Expected Behavior

Serve command should not throw error `Command failed: taskkill`

### Steps to Reproduce

1. Init project with `npx create-nx-workspace@latest sample-nx` and select integrated nestjs app
2. Serve the nestjs app in development (Not error yet)
3. Make the code in main.ts error
4. correct it
5. Boom💥Command failed: taskkill /pid

### Nx Report

```shell
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.5.1
   Hasher : Native

   nx (global)        : 16.2.2
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Failure Logs

```shell
# nx run api:serve

> nx run api:serve:development

[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG [NestFactory] Starting Nest application...
[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG [InstanceLoader] AppModule dependencies initialized +7ms
[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG [RoutesResolver] AppController {/api}: +13ms
[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG [RouterExplorer] Mapped {/api, GET} route +1ms
[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 16848  - 05/25/2023, 2:19:18 PM     LOG 🚀 Application is running on: http://localhost:3000/api

>  NX  File change detected. Restarting...


> nx run api:build:development

chunk (runtime: main) main.js (main) 2.77 KiB [entry] [rendered]
ERROR in ./apps/api/src/app/app.controller.ts:11:28
TS2551: Property 'getDasta' does not exist on type 'AppService'. Did you mean 'getData'?
     9 |   @Get()
    10 |   getData() {
  > 11 |     return this.appService.getDasta();
       |                            ^^^^^^^^
    12 |   }
    13 | }
    14 |
webpack compiled with 1 error (96bc2f0837570737)



 >  NX   Running target build for project api failed

   Failed tasks:

   - api:build:development

   Hint: run the command with --verbose for more details.


Build failed, waiting for changes to restart...

>  NX  File change detected. Restarting...

node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: taskkill /pid 14736 /T /F
ERROR: The process "14736" not found.

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128,
  killed: false,
  signal: null,
  cmd: 'taskkill /pid 14736 /T /F'
}

Node.js v18.16.0

 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project api failed

   Failed tasks:

   - api:serve:development

   Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment] 2023-05-25 12:44
I can't reproduce this on `macOS`, so it seems limited to a windows issue.

**Comment by Leccho** [comment] 2023-06-01 03:01
Got the same problem, as soon as it compile with errors. Have you fix this @thenglong ?

## Nx Report
```
Node   : 18.16.0
   OS     : win32 x64
   npm    : 9.6.7
   Hasher : Native

   nx                 : 16.3.0
   @nx/js             : 16.3.0
   @nx/jest           : 16.3.0
   @nx/linter         : 16.3.0
   @nx/workspace      : 16.3.0
   @nx/angular        : 16.3.0
   @nx/cypress        : 16.3.0
   @nx/devkit         : 16.3.0
   @nx/eslint-plugin  : 16.3.0
   @nx/nest           : 16.3.0
   @nx/node           : 16.3.0
   @nrwl/tao          : 16.3.0
   @nx/webpack        : 16.3.0
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
```

## Error message
```
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: taskkill /pid 5388 /T /F
ERROR: The process "5388" not found.

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128,
  killed: false,
  signal: null,
  cmd: 'taskkill /pid 5388 /T /F'
}

Node.js v18.16.0
```

**Comment by thenglong** [comment] 2023-06-01 08:35
@Leccho I ended up reverting and downgrading to v16.1.4.

**Comment by Quraian** [comment] 2023-06-01 14:42
I'm having a similar issue, it seems this appeared after I upgraded 16.3.
I'll try to give more info later when I can.

**Comment by driley-abbvie** [comment] 2023-06-06 16:59
I had a similar issue and downgrading fixed

**Comment by zub0r** [comment] 2023-06-13 17:21
This issue is not windows specific - It's happening on mac and linux too.
Tracking it here: https://github.com/nrwl/nx/issues/17070

**Comment by meeroslav** [comment] 2023-06-30 11:57
Closing this in favor of #17070

**Closed by meeroslav** 2023-06-30 11:57 UTC
Labels: type: bug, scope: node, os: windows
