### ISSUE TITLE
Migrating from v13 to v14 breaks import for `react-hook-form`

### ISSUE THREAD

**Issue by mauris** [nrwl/nx#10043] opened 2022-04-28 13:49 UTC
## Current Behavior

After performing a migration from v13 to v14 using `nx migrate` command, the bundle and build commands for my `react-native` app failed with the error:

```
Error: While trying to resolve module `react-hook-form` from file `<workspaceRoot>\packages\ui\src\lib\login\login.tsx`, the package `<workspaceRoot>\node_modules\react-hook-form\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`<workspaceRoot>\node_modules\react-hook-form\dist\index.cjs.js`. Indeed, none of these files exist:        

  * <workspaceRoot>\node_modules\react-hook-form\dist\index.cjs.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * <workspaceRoot>\node_modules\react-hook-form\dist\index.cjs.js\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  <stacktrace as follow>
```

The `metro.config.js` (specifically `sourceExts`) was not modified from default generated. 

Things I have tried, but did not work:
- Downgrading `react-hook-form` to `7.29.0`
- Downgrading `metro` (and related dependencies) to `0.66` or `0.67`
- Removing `node_modules` entirely and reinstalling dependencies using `yarn`
- Perform `nx reset`
- Clear metro cache in temp dir

The only way to make it work:
- Reverting my monorepo to the commit prior to `nx migrate` (i.e. downgrading back to `nx@13`)

## Expected Behavior

I expect to be able to bundle and build without module resolution errors.

## Steps to Reproduce

I have a monorepo at `nx@13.10.2`. After migrating to v14 using `nx migrate`, the build and bundle commands failed for `react-native` app.

### Failure Logs

Nil

### Environment

```
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : win32 x64
   yarn : 1.22.18

   nx : 13.10.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.2
   @nrwl/detox : 13.10.2
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.2
   @nrwl/express : 13.10.3
   @nrwl/jest : 13.10.2
   @nrwl/js : 13.10.2
   @nrwl/linter : 13.10.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.10.2
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.3
   @nrwl/react-native : 13.10.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : 13.10.2
   @nrwl/workspace : 13.10.2
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:
```

**Comment by mauris** [comment] 2022-04-29 01:02
cc @bluebill1049 for awareness. this is likely a `nx@14` issue since `react-hook-form@7.30.0` was working in `nx@13`

**Comment by bluebill1049** [comment] 2022-04-29 01:09
Let us know if there is anything we would need to adjust.

**Comment by xiongemi** [comment] 2022-04-29 19:09
@mauris so it is not a defect?

I think for the metro.config, it has
```
blacklistRE: exclusionList([/\.\/dist\/.*/]),
```

**Comment by mauris** [comment] 2022-05-01 13:43
@xiongemi it's not. 

I have another issue though with `react-native`'s build being conflicted with `express`'s build. 

- `express` build produces files in `dist/`, which also builds project dependencies from `packages/*` into `dist/packages/*`. I have `generatePackageJson` set to `true`
- `react-native` build will fail due to `package.json` files having the same name, one in `packages/*`, the other in `dist/packages/*`

My current workaround is to manually delete `dist/` folder before I `build-android` or `run-android` on the `react-native` package.

**Comment by xiongemi** [comment] 2022-05-01 19:39
how about 
`blacklistRE: exclusionList([/\.\/dist\/.*/]),`

regex should only exclude file has './dist/` only dist under workspace root?

**Comment by xiongemi** [comment] 2022-05-05 03:34
closing issue since it is not caused by nx 14

**Closed by xiongemi** 2022-05-05 03:34 UTC
Labels: type: bug, scope: react-native
