### ISSUE TITLE
Interpolated environment variables keep their initial value from root .env file

### ISSUE THREAD

**Issue by seliceantitus** [nrwl/nx#23221] opened 2024-05-07 16:09 UTC
### Current Behavior

Environment variables which contain interpolation and are processed by `dotenv-expand` don't contain the value from the `.env.[task-configuration]` file, but only the initial one, from the files loaded by default (e.g. `.env`).

With the following setup:

.env
```
VITE_TEST="123"
VITE_TEST2="${VITE_TEST}_local"
VITE_NO_INTERPOLATION="local"
``` 

.env.production
```
VITE_TEST="123"
VITE_TEST2="${VITE_TEST}_prod"
VITE_NO_INTERPOLATION="prod"
``` 

After `nx run my-app:serve --configuration=production` is ran, `import.meta.env` will contain:

```
VITE_TEST: "123"
VITE_TEST2: "123_local"
VITE_NO_INTERPOLATION: "prod"
``` 

### Expected Behavior

The env var values from the `.env.[task-configuration]` should have priority over the default ones defined in `.env` or `.env.local`

With the same setup as above, after `nx run my-app:serve --configuration=production` is ran, `import.meta.env` should contain:

```
VITE_TEST: "123"
VITE_TEST2: "123_prod"
VITE_NO_INTERPOLATION: "prod"
``` 

### GitHub Repo

https://github.com/seliceantitus/nx-env-interpolation

### Steps to Reproduce

1. Inspect `.env` and `.env.production`
2. Check `project.json` for correct serve and build configurations
3. Run `nx run test-vite:serve --configuration=production`
4. Inspect contents of `import.meta.env`

### Nx Report

```shell
Node   : 18.18.0
OS     : darwin-arm64
npm    : 9.8.1

nx                 : 19.0.0
@nx/js             : 19.0.0
@nx/linter         : 19.0.0
@nx/eslint         : 19.0.0
@nx/workspace      : 19.0.0
@nx/cypress        : 19.0.0
@nx/devkit         : 19.0.0
@nx/eslint-plugin  : 19.0.0
@nx/react          : 19.0.0
@nrwl/tao          : 19.0.0
@nx/vite           : 19.0.0
@nx/web            : 19.0.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/cypress/plugin
```

### Package Manager Version

9.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Version 18.3.4 is also affected by this. I added some logs to `nx/src/task-runners/task-env.js` and `dotenv-expand` bundled files and this is the output:

<details>
<summary>Logs</summary>

`myEnv` is the result of `dotenv.config` and `expandedEnv` is the result of `dotenv-expand.expand`

```
 *  Executing task: npx nx run my-project:serve --configuration=production 

dotenv-expand::Checking VITE_BASE_APP_URL
dotenv-expand::Checking VITE_APP_1_URL
dotenv-expand::Checking VITE_APP_2_URL
Trace: dotenv-expand::Returning {
  parsed: {
    VITE_BASE_APP_URL: 'http://localhost',
    VITE_APP_1_URL: 'http://localhost:4200/',
    VITE_APP_2_URL: 'http://localhost:4300/',
  }
}
    at expand (/<PROJECT-PATH>/node_modules/dotenv-expand/lib/main.js:81:13)
    at loadRootEnvFiles (/<PROJECT-PATH>/node_modules/nx/src/utils/dotenv.js:19:36)
    at main (/<PROJECT-PATH>/node_modules/nx/bin/nx.js:30:39)
    at Object.<anonymous> (/<PROJECT-PATH>/node_modules/nx/bin/nx.js:218:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47
task-env.js [
  '<MONOREPO-APP-PATH>/.env.serve.production',
  '<MONOREPO-APP-PATH>/.env.production',
  '<MONOREPO-APP-PATH>/.serve.production.env',
  '<MONOREPO-APP-PATH>/.production.env',
  '<MONOREPO-APP-PATH>/.env.serve',
  '<MONOREPO-APP-PATH>/.serve.env',
  '<MONOREPO-APP-PATH>/.env.local',
  '<MONOREPO-APP-PATH>/.local.env',
  '<MONOREPO-APP-PATH>/.env',
  '.env.serve.production',
  '.env.production',
  '.serve.production.env',
  '.production.env',
  '.env.serve',
  '.serve.env',
  '.local.env',
  '.env.local',
  '.env'
]
task-env.js::File <MONOREPO-APP-PATH>/.env.serve.production skipped
task-env.js::File <MONOREPO-APP-PATH>/.env.production skipped
task-env.js::File <MONOREPO-APP-PATH>/.serve.production.env skipped
task-env.js::File <MONOREPO-APP-PATH>/.production.env skipped
task-env.js::File <MONOREPO-APP-PATH>/.env.serve skipped
task-env.js::File <MONOREPO-APP-PATH>/.serve.env skipped
task-env.js::File <MONOREPO-APP-PATH>/.env.local skipped
task-env.js::File <MONOREPO-APP-PATH>/.local.env skipped
task-env.js::File <MONOREPO-APP-PATH>/.env skipped
task-env.js::File .env.serve.production skipped
dotenv-expand::Checking VITE_BASE_APP_URL
dotenv-expand::Checking VITE_APP_1_URL
dotenv-expand::Checking VITE_APP_2_URL
Trace: dotenv-expand::Returning {
  parsed: {
    VITE_BASE_APP_URL: '<PROD-URL>',
    VITE_APP_1_URL: '<PROD-URL>/app-1',
    VITE_APP_2_URL: '<PROD-URL>/app-2',
  },
  ignoreProcessEnv: true
}
    at expand (/<PROJECT-PATH>/node_modules/dotenv-expand/lib/main.js:81:13)
    at loadDotEnvFilesForTask (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-env.js:122:62)
    at getTaskSpecificEnv (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-env.js:20:11)
    at TaskOrchestrator.processScheduledTask (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:87:67)
    at TaskOrchestrator.processAllScheduledTasks (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:110:54)
    at TaskOrchestrator.scheduleNextTasks (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:372:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.run (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:45:9)
    at async defaultTasksRunner (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/default-tasks-runner.js:18:16)
    at async anyFailuresInPromise (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/run-command.js:227:26)
task-env.js::File .env.production loaded myEnv = {
  VITE_BASE_APP_URL: '<PROD-URL>',
  VITE_APP_1_URL: '<PROD-URL>/app-1',
  VITE_APP_2_URL: '<PROD-URL>/app-2',
}, expandedEnv = {
  VITE_BASE_APP_URL: '<PROD-URL>',
  VITE_APP_1_URL: '<PROD-URL>/app-1',
  VITE_APP_2_URL: '<PROD-URL>/app-2',
}
task-env.js::File .serve.production.env skipped
task-env.js::File .production.env skipped
task-env.js::File .env.serve skipped
task-env.js::File .serve.env skipped
task-env.js::File .local.env skipped
task-env.js::File .env.local skipped
dotenv-expand::Checking VITE_BASE_APP_URL
dotenv-expand::Checking VITE_APP_1_URL
dotenv-expand::Checking VITE_APP_2_URL
Trace: dotenv-expand::Returning {
  parsed: {
    VITE_BASE_APP_URL: 'http://localhost',
    VITE_APP_1_URL: 'http://localhost:4200/',
    VITE_APP_2_URL: 'http://localhost:4300/',
  },
  ignoreProcessEnv: true
}
    at expand (/<PROJECT-PATH>/node_modules/dotenv-expand/lib/main.js:81:13)
    at loadDotEnvFilesForTask (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-env.js:122:62)
    at getTaskSpecificEnv (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-env.js:20:11)
    at TaskOrchestrator.processScheduledTask (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:87:67)
    at TaskOrchestrator.processAllScheduledTasks (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:110:54)
    at TaskOrchestrator.scheduleNextTasks (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:372:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.run (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/task-orchestrator.js:45:9)
    at async defaultTasksRunner (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/default-tasks-runner.js:18:16)
    at async anyFailuresInPromise (/<PROJECT-PATH>/node_modules/nx/src/tasks-runner/run-command.js:227:26)
task-env.js::File .env loaded: myEnv = {
  VITE_BASE_APP_URL: 'http://localhost',
  VITE_APP_1_URL: 'http://localhost:4200/',
  VITE_APP_2_URL: 'http://localhost:4300/',
}, expandedEnv = {
  VITE_BASE_APP_URL: 'http://localhost',
  VITE_APP_1_URL: 'http://localhost:4200/',
  VITE_APP_2_URL: 'http://localhost:4300/',
}
task-env.js::Returning {
  VITE_BASE_APP_URL: '<PROD-URL>',
  VITE_APP_1_URL: 'http://localhost:4200/',
  VITE_APP_2_URL: 'http://localhost:4300/',
}
``` 

</details>

**Comment by Coly010** [comment] 2024-05-07 18:26
Closing as duplicate of https://github.com/nrwl/nx/issues/22347

**Closed by Coly010** 2024-05-07 18:26 UTC
Labels: type: bug
