### ISSUE TITLE
Vite: The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#19149] opened 2023-09-13 15:56 UTC
### Current Behavior

I have a library, which can no longer be generated with Webpack, that consumes a custom npm package, and when building it, it fails with the following message

```ts
>  NX   Failed to resolve entry for package "@our-custom/ui-components". The package may have incorrect main/module/exports specified in its package.json.

```

I have also [reported it to Vite](https://github.com/vitejs/vite/issues/12446), but haven't had a chance, as of yet, to create a reproducible example.

At the moment, the library's package.json defines both main and module properties
```ts
    "main": "dist/index.js",
    "module": "dist/index.modern.js",
```

where the first one's content looks as if it was transpiled for ie5
```ts
'use strict';

var React$1 = require('react');
var reactUse = require('react-use');
...
```

and the second one for the modern browsers
```ts
import * as React$1 from 'react';
import React__default, { useContext, useMemo, useState, useCallback, useRef, useLayoutEffect, useEffect, forwardRef, createRef, createContext } from 'react';
import { useGetSet } from 'react-use';
...
```

### Expected Behavior

It should work.

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.15.0
   OS     : linux-x64
   yarn   : 3.6.1
   
   nx                 : 16.5.3
   @nx/js             : 16.5.3
   @nx/jest           : 16.5.3
   @nx/linter         : 16.5.3
   @nx/workspace      : 16.5.3
   @nx/cypress        : 16.5.3
   @nx/eslint-plugin  : 16.5.3
   @nx/react          : 16.5.3
   @nx/webpack        : 16.5.3
   typescript         : 5.1.6
```

### Package Manager Version

yarn

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nemonemi** [comment] 2023-09-14 09:18
Removing the "module" property resolves the issue, but I'm not sure if that's the desired approach, since one might not have the control over the library they consume.

**Comment by steven10172** [comment] 2023-09-19 02:28
Related to https://github.com/nrwl/nx/issues/18492#issuecomment-1691942830

**Comment by toddbaert** [comment] 2023-09-29 01:38
> Removing the "module" property resolves the issue, but I'm not sure if that's the desired approach, since one might not have the control over the library they consume.

@nemonemi @AgentEnder 

If I'm understanding you correctly, I think I may be having the same issue. It seems to be related to the fix for this issue: https://github.com/nrwl/nx/issues/18912

**Comment by teofilomonteiro** [comment] 2023-10-03 11:52
@barbados-clemens left a comment that makes me very unhappy. This sounds like a breaking change release and not a feature release. It breaks the behaviour that it was before. Especially when migrating should keep everything working. Is there a workaround that doesn't involve changing the behaviour of the npm base repo?

**Comment by teofilomonteiro** [comment] 2023-10-03 11:57
I will add more, the solution suggested just causes another issue. If you make changes to the lib, this will not trigger a reload of the app or a rebuild of the lib/app.

**Comment by joeldbirch** [comment] 2023-10-25 23:51
I'm getting the same issue using yarn workspaces.

**Comment by teofilomonteiro** [comment] 2024-01-02 10:50
I think another solution for this is to prevent the migration to use the `import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin'; Something is missing on this plugin that makes it break. 

If I still use `vite-tsconfig-paths` everything works as it should. 

So the question now is, what does `nxViteTsPaths` try to solve?

**Comment by fsgreco** [comment] 2024-01-07 01:31
Hello @teofilomonteiro I've just found a new solution for this, explained everything in detail here: https://github.com/nrwl/nx/issues/21030 

TL;DR: you can change the paths alias inside the `tsconfig.base.json`, as long as it does not match the name of the custom package/library (its name inside its `package.json` it will work fine). I still repute it a bug but at least this is an easy and not invasive solution.

**Comment by teofilomonteiro** [comment] 2024-02-09 09:04
@fsgreco I don't think we can use your solution because we are publishing packages. And from what I understood from your suggestion you need to rename the package. Is that correct?

**Comment by MBelniak** [comment] 2024-04-03 15:06
Maybe this will help? https://github.com/nrwl/nx/issues/18931#issuecomment-2034872283

**Comment by fsgreco** [comment] 2024-04-03 15:46
@teofilomonteiro actually you can change the strategy and rename the exports instead. The package will still have it's name, but you have to rename the pathname on the `tsconfig`file*. As long as they don't match it should work 👍🏽  

Ps: let me know how it goes, it's been a couple of months since I create this issue and found the solution.

`*` and with that also every import inside the app on the monorepo that consume them but that could be done with a general search and replace

**Comment by Coly010** [comment] 2024-05-16 10:58
Closing as duplicate of https://github.com/nrwl/nx/issues/20520
Which also has a better reproduction.

Thanks everyone for chiming in here, this is all valuable information

**Closed by Coly010** 2024-05-16 10:58 UTC
Labels: type: bug, scope: bundlers
