### ISSUE TITLE
create-nx-workspace fails due to --ci=github option

### ISSUE THREAD

**Issue by DanielGiljam** [nrwl/nx#17401] opened 2023-06-03 08:24 UTC
### Current Behavior

I ran `pnpm create nx-workspace --allPrompts` and answered this to the prompts:

```
 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · test-workspace
✔ Which stack do you want to use? · none
✔ Package-based or integrated? · package-based
✔ Which package manager to use          · pnpm
✔ Main branch name                    · main
✔ Enable distributed caching to make your CI faster · Yes
✔ CI workflow file to generate?       · github
```

The command failed when generating CI workflow.

### Expected Behavior

The command would run successfully given those answers to the prompts.

### Steps to Reproduce

1. Run `pnpm create nx-workspace --allPrompts` using PNPM v8.6.0.
2. Answer this to the prompts:
   ```
    >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]
   
   ✔ Where would you like to create your workspace? · test-workspace
   ✔ Which stack do you want to use? · none
   ✔ Package-based or integrated? · package-based
   ✔ Which package manager to use          · pnpm
   ✔ Main branch name                    · main
   ✔ Enable distributed caching to make your CI faster · Yes
   ✔ CI workflow file to generate?       · github
   ```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin x64
   pnpm   : 8.6.0
   Hasher : Native

   nx         : 16.3.2
   @nrwl/tao  : 16.3.2
   nx-cloud   : 16.0.5
```

### Failure Logs

```shell
>  NX   Unable to resolve @nx/workspace:ci-workflow.

   unable to find tsconfig.base.json or tsconfig.json
   Pass --verbose to see the stacktrace.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment] 2023-10-23 15:42
Hello @DanielGiljam ! Thanks for filing an issue! Unfortunately I could not reproduce your issue with the latest version of Nx, here's my output:

```
pnpm create nx-workspace@latest --allPrompts
.../Library/pnpm/store/v3/tmp/dlx-39085  |  +67 +++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/fileas/Library/pnpm/store/v3
  Virtual store is at:             ../../../Library/pnpm/store/v3/tmp/dlx-39085/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-39085  | Progress: resolved 67, reused 66, downloaded 1, added 67, done

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · katerina
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based
✔ Which package manager to use · pnpm
✔ Main branch name · main
✔ Enable distributed caching to make your CI faster · Yes
✔ CI workflow file to generate?       · github

 >  NX   Creating your v17.0.1 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "pnpm install" several times. Please wait.

✔ Installing dependencies with pnpm
✔ Successfully created the workspace: kkak.
✔ NxCloud has been set up successfully
✔ CI workflow has been generated successfully

 >  NX   Distributed caching via Nx Cloud has been enabled

   In addition to the caching, Nx Cloud provides config-free distributed execution,
   UI for viewing complex runs and GitHub integration. Learn more at https://nx.app

   Your workspace is currently unclaimed. Run details from unclaimed workspaces can be viewed on cloud.nx.app by anyone
   with the link. Claim your workspace at the following link to restrict access.

   https://cloud.nx.app/orgs/workspace-setup?accessToken=ODRmMjI4YjctMzdiNC00NjVhLWE2NmQtMjAwNjU2MzA4YTBkfHJlYWQtd3JpdGU=


 ———————————————————————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/getting-started/tutorials/package-based-repo-tutorial

```

Here's my Nx report:
```
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : darwin-arm64
   pnpm   : 8.6.11

   nx             : 17.0.1
   @nx/js         : 17.0.1
   @nx/workspace  : 17.0.1
   @nx/devkit     : 17.0.1
   @nrwl/tao      : 17.0.1
   typescript     : 5.2.2

```

Can you please retry this with the latest version, and let me know if you faced the same issue?

**Comment by mandarini** [comment] 2023-10-24 12:52
I will be closing this, since it seems to be outdated. If you do try it with the latest version, and the error still shows up, please feel free to ping me here, and I will reopen and try to figure out what the problem may be!

Thank you for filing this issue!

**Closed by mandarini** 2023-10-24 12:52 UTC
Labels: type: bug, blocked: repro needed, blocked: retry with latest, scope: misc
