### ISSUE TITLE
return of Running any nx cli command fails with the following output: Original error: Failed to convert napi

### ISSUE THREAD

**Issue by kokokenada** [nrwl/nx#20808] opened 2023-12-17 02:19 UTC
### Current Behavior

running nx commands

```
npx nx run db:prisma-push
npx nx run server:serve
```
or whatever (probably) results in:

```

 >  NX   Daemon process terminated and closed the connection

   Please rerun the command, which will restart the daemon.
   If you get this error again, check for any errors in the daemon process logs found in: /home/kenono/apps/huumans/quota3/.nx/cache/d/daemon.log

```

and the log file:

```
[NX Daemon Server] - 2023-12-17T02:11:39.994Z - Started listening on: /tmp/e9d8c2dc3c2e3805f69d/d.sock
[NX Daemon Server] - 2023-12-17T02:11:39.995Z - [WATCHER]: Subscribed to changes within: /home/kenono/apps/huumans/quota3 (native)
[NX Daemon Server] - 2023-12-17T02:11:39.999Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2023-12-17T02:11:40.000Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2023-12-17T02:11:40.002Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2023-12-17T02:11:40.003Z - [REQUEST]: Updated workspace context based on watched changes, recomputing project graph...
[NX Daemon Server] - 2023-12-17T02:11:40.003Z - [REQUEST]: 
[NX Daemon Server] - 2023-12-17T02:11:40.003Z - [REQUEST]: 
[NX Daemon Server] - 2023-12-17T02:11:40.075Z - [REQUEST]: Responding to the client. project-graph
[NX Daemon Server] - 2023-12-17T02:11:40.076Z - Time taken for 'total for creating and serializing project graph' 72.59322202205658ms
[NX Daemon Server] - 2023-12-17T02:11:40.076Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2023-12-17T02:11:40.076Z - Done responding to the client project-graph
[NX Daemon Server] - 2023-12-17T02:11:40.077Z - Handled REQUEST_PROJECT_GRAPH. Handling time: 73. Response time: 2.
/home/kenono/apps/huumans/quota3/node_modules/nx/src/hasher/native-task-hasher-impl.js:23
        this.planner = new native_1.HashPlanner(nxJson, this.projectGraphRef);
                       ^

Error: Given napi value is not an array
    at new NativeTaskHasherImpl (/home/kenono/apps/huumans/quota3/node_modules/nx/src/hasher/native-task-hasher-impl.js:23:24)
    at new InProcessTaskHasher (/home/kenono/apps/huumans/quota3/node_modules/nx/src/hasher/task-hasher.js:47:15)
    at handleHashTasks (/home/kenono/apps/huumans/quota3/node_modules/nx/src/daemon/server/handle-hash-tasks.js:18:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleResult (/home/kenono/apps/huumans/quota3/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (/home/kenono/apps/huumans/quota3/node_modules/nx/src/daemon/server/server.js:84:9)
    at async /home/kenono/apps/huumans/quota3/node_modules/nx/src/daemon/server/server.js:45:9 {
  code: 'InvalidArg'
}
```

 
 

### Expected Behavior

does not crash

### Steps to Reproduce

1.

### Nx Report

```shell
as reported above
```

### Package Manager Version

npm --version 8.19.4

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

a comment in https://github.com/nrwl/nx/issues/17412 said to nuke node_modules and packag-json.lock which I did but the error keeps happening.

Another comment in that thread requests the package-lock.json.  attached is that and the package.json
[package.json](https://github.com/nrwl/nx/files/13694485/package.json)
[package-lock.json](https://github.com/nrwl/nx/files/13694486/package-lock.json)

**Comment by kokokenada** [comment] 2023-12-17 02:48
I figured it out.  I had copied a workspaceLayout from another project using nx v16 and had:
```
  "workspaceLayout": {
    "appsDir": "packages",
    "libsDir": "packages"
  },
```
changing it to: (guessing, I didn't see anything helpful in https://nx.dev/reference/nx-json)
```
    "workspaceLayout": ["packages", "packages"],
```

fixed the crash.  

A helpful error message or docs on workspaceLayout would have saved me a couple of hours.

Thanks for super cool product.

**Comment by paulcarroll** [comment] 2024-03-13 05:57
Ok, following up on my issue from above...
As I mentioned, this is pretty deep down in the Rust code. Eventually I had some time to come back and take a look at this project and basically the issue is (for me anyway) that `@nx/nx-darwin-arm64` was still at v16 instead of v18. Once I updated it everything was working again

**Comment by MaxKless** [comment] 2024-05-14 10:26
Thanks for looking into it @kokokenada & @paulcarroll!
It sounds like your figured it out and fixed the problems yourselves. 
I'll close this issue, if there's any other error I've missed please let me know.

**Closed by MaxKless** 2024-05-14 10:26 UTC
Labels: type: bug, scope: core
