### ISSUE TITLE
[@nx/eslint-plugin] Incompatibility with @typescript-eslint/eslint-plugin and @typescript-eslint/parser 6.x

### ISSUE THREAD

**Issue by throrin19** [nrwl/nx#20026] opened 2023-11-03 08:35 UTC
### Current Behavior

Actually, I can't upgrade @typescript-eslint/eslint-plugin and @typescript-eslint/parser from version `5.62.0` to version `6.9.1`

When I try to do that, I have this error : 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nx/eslint-plugin@17.0.2
npm ERR! Found: @typescript-eslint/parser@6.9.1
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"6.9.1" from the root project
npm ERR!   peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.9.1
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"6.9.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^5.60.1" from @nx/eslint-plugin@17.0.2
npm ERR! node_modules/@nx/eslint-plugin
npm ERR!   dev @nx/eslint-plugin@"17.0.2" from the root project
npm ERR!   @nx/eslint-plugin@"17.0.2" from @nrwl/eslint-plugin-nx@17.0.2
npm ERR!   node_modules/@nrwl/eslint-plugin-nx
npm ERR!     @nrwl/eslint-plugin-nx@"17.0.2" from @nx/eslint-plugin@17.0.2
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/parser@5.62.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^5.60.1" from @nx/eslint-plugin@17.0.2
npm ERR!   node_modules/@nx/eslint-plugin
npm ERR!     dev @nx/eslint-plugin@"17.0.2" from the root project
npm ERR!     @nx/eslint-plugin@"17.0.2" from @nrwl/eslint-plugin-nx@17.0.2
npm ERR!     node_modules/@nrwl/eslint-plugin-nx
npm ERR!       @nrwl/eslint-plugin-nx@"17.0.2" from @nx/eslint-plugin@17.0.2
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /builds/renovate/renovate-config/renovate/cache/others/npm/_logs/2023-11-02T17_07_07_054Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /builds/renovate/renovate-config/renovate/cache/others/npm/_logs/2023-11-02T17_07_07_054Z-debug-0.log
```

### Expected Behavior

I can upgrade @typescript-eslint/eslint-plugin and @typescript-eslint/parser

### Steps to Reproduce

1.

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-x64
   npm    : 9.8.1
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/node           : 17.0.2
   @nx/plugin         : 17.0.2
   @nrwl/tao          : 17.0.2
   typescript         : 5.2.2
   ---------------------------------------
   Local workspace plugins:
         local-plugins
```

### Failure Logs

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nx/eslint-plugin@17.0.2
npm ERR! Found: @typescript-eslint/parser@6.9.1
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"6.9.1" from the root project
npm ERR!   peer @typescript-eslint/parser@"^6.0.0 || ^6.0.0-alpha" from @typescript-eslint/eslint-plugin@6.9.1
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     dev @typescript-eslint/eslint-plugin@"6.9.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^5.60.1" from @nx/eslint-plugin@17.0.2
npm ERR! node_modules/@nx/eslint-plugin
npm ERR!   dev @nx/eslint-plugin@"17.0.2" from the root project
npm ERR!   @nx/eslint-plugin@"17.0.2" from @nrwl/eslint-plugin-nx@17.0.2
npm ERR!   node_modules/@nrwl/eslint-plugin-nx
npm ERR!     @nrwl/eslint-plugin-nx@"17.0.2" from @nx/eslint-plugin@17.0.2
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/parser@5.62.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   peer @typescript-eslint/parser@"^5.60.1" from @nx/eslint-plugin@17.0.2
npm ERR!   node_modules/@nx/eslint-plugin
npm ERR!     dev @nx/eslint-plugin@"17.0.2" from the root project
npm ERR!     @nx/eslint-plugin@"17.0.2" from @nrwl/eslint-plugin-nx@17.0.2
npm ERR!     node_modules/@nrwl/eslint-plugin-nx
npm ERR!       @nrwl/eslint-plugin-nx@"17.0.2" from @nx/eslint-plugin@17.0.2
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /builds/renovate/renovate-config/renovate/cache/others/npm/_logs/2023-11-02T17_07_07_054Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /builds/renovate/renovate-config/renovate/cache/others/npm/_logs/2023-11-02T17_07_07_054Z-debug-0.log
```

### Package Manager Version

NPM 9.8.1

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by AgentEnder** [comment] 2023-11-03 20:12
Closing as a duplicate of #18641 - it'll be released soon™️

**Closed by AgentEnder** 2023-11-03 20:12 UTC
Labels: type: bug
