### ISSUE TITLE
"nx migrate" produces invalid dependencies versions that are different from "npx create-nx-workspace"

### ISSUE THREAD

**Issue by zilia-gmethot** [nrwl/nx#15841] opened 2023-03-23 03:07 UTC
### Current Behavior

I have a NX workspace containing an Angular version 12 application. According to the [Nx and Angular Version Compatibility Matrix](https://nx.dev/packages/angular/documents/angular-nx-version-matrix#nx-and-angular-version-compatibility-matrix), I should update Nx version 14.1.19 in order to migrate Angular to version 13. By doing so, the versions to which my dependencies are updated to are not the same as when I use the npx create-nx-workspace@14.1.9 to create a similar workspace. For instance, here are some differences:

Here is some content of my `package.json` prior to migrating my existing workspace:
```
{
  "dependencies": {
    "@angular/core": "^12.2.0",
    "rxjs": "~6.6.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "~4.33.0",
    "@typescript-eslint/parser": "~4.33.0"
  }
}
```

Here is some content of my `package.json` after migrating my existing workspace:
```
{
  "dependencies": {
    "@angular/core": "13.3.12",
    "rxjs": "~6.6.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "~4.33.0",
    "@typescript-eslint/parser": "~4.33.0"
  }
}
```

And here is some content of the `package.json` of a newly generated Nx workspace containing an Angular app:
```
{
  "dependencies": {
    "@angular/core": "~13.3.0",
    "rxjs": "~7.4.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "~5.18.0",
    "@typescript-eslint/parser": "~5.18.0"
  }
}
```

By running `npm install` in my existing workspace post-migration, I get the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: zilia-ocular-frontend@0.0.0
npm ERR! Found: @typescript-eslint/parser@4.33.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"~4.33.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"~5.18.0" from @nrwl/eslint-plugin-nx@14.1.9
npm ERR! node_modules/@nrwl/eslint-plugin-nx
npm ERR!   dev @nrwl/eslint-plugin-nx@"14.1.9" from the root project
```

There are actually multiple issues with the migration process. First, `rxjs` [should have been migrated to version 7.4](https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296) but wasn't. Second, `@typescript-eslint` related packages were not updated at all, causing the dependencies installation to fail. Third, the Angular related packages versions are different.

It seems that the dependencies versions in the newly created workspace are the correct ones. If that is the case, why are the ones resulting from the migration process different?

### Expected Behavior

- Dependencies versions produced by `nx migrate` should be valid
- Dependencies versions produced by `nx migrate` and `npx create-nx-workspace` should be the same
- If manual steps are required after running `nx migrate`, they should be documented clearly

### Steps to Reproduce

1. Generate a Nx@13.1.4 workspace containing an Angular@12.2.0 application by running `npx create-nx-workspace@13.1.4 my-workspace --appName=my-app --preset=angular --style=scss --nx-cloud=false `
2. Migrate to Angular 13 by running `npx nx migrate 14.1.9`
3. Install dependencies by running `npm install` and notice the errors
4. Create a Nx@14.1.9 workspace by running `npx create-nx-workspace@14.1.9 my-other-workspace --appName=my-other-app --preset=angular --style=scss --nx-cloud=false`
5. Compare both workspaces and note the differences in dependencies versions

### Nx Report

```shell
Node : 16.19.0
OS   : linux x64
npm  : 8.19.3

nx : 13.1.4
@nrwl/angular : 13.1.4
@nrwl/cli : 13.1.4
@nrwl/cypress : 13.1.4
@nrwl/devkit : 13.1.4
@nrwl/eslint-plugin-nx : 13.1.4
@nrwl/express : Not Found
@nrwl/jest : 13.1.4
@nrwl/linter : 13.1.4
@nrwl/nest : Not Found
@nrwl/next : Not Found
@nrwl/node : Not Found
@nrwl/nx-cloud : Not Found
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 13.1.4
@nrwl/web : Not Found
@nrwl/workspace : 13.1.4
@nrwl/storybook : 13.1.4
@nrwl/gatsby : Not Found
typescript : 4.3.5
```

**Comment by AgentEnder** [comment] 2023-03-27 21:02
The goal behind "nx migrate" is to migrate your app to the latest and greatest, without breaking it. For RxJS 6, this means leaving it at v6 since there are no migrations to the next version, and you likely also have libraries installed which use v6.

Also, RxJS v13 **_doesnt_** exist. Its latest is currently 7.8.0, though I believe 8 should be out relatively soon. Check the version share: https://www.craigory.dev/npm-burst/?package=rxjs

You'll note most people are still on 6, and this is why we can't automigrate existing workspaces to 7+. 

Regarding the other contents of your package.json, it does surprise me that the typescript-eslint stuff didn't get bumped. I'll send this to the angular vertical folk, as they should have more context on that.

**Comment by zilia-gmethot** [comment] 2023-03-28 02:33
@AgentEnder Thanks for your time. I fixed my original comment because I meant RxJS version 7.4, which is now the default for new apps using Angular 13. As pointed out in the Angular blog post, people do have to manually update RxJS. Therefore, I'm assuming that the Angular migration tool, which is probably used under the hood by the Nx migration tool, does not take care of it. I now consider I was wrong and that it's a non-issue.

I'm also confused by the issue regarding `@typescript-eslint` related packages because the migration seems to be working in brand new repos, but not in ours. Please let me know if I can provide any more information that could help finding the cause.

Finally, and that is the point I am most confused about, I still wonder why the pinned versions of most packages post-migration are different from the ones used when generating a new application.

**Comment by leosvelperez** [comment] 2023-05-09 14:16
Hey @zilia-gmethot!

Do you still have an issue with the `@typescript-eslint/*` packages when migrating? I can't reproduce that issue following the steps you outlined. Those packages are correctly updated, and I can't think of any reason they wouldn't. If you're still having issues, we will need a reproduction for further troubleshooting.

The other mentioned issues have been covered in these comments: https://github.com/nrwl/nx/issues/15841#issuecomment-1485857316 and https://github.com/nrwl/nx/issues/15841#issuecomment-1523195394. In summary:

- The RxJs version is not automatically updated because it contains some breaking changes that can't be solved in an automated way.
- The migrations update packages versions to the latest version that's valid for the version range defined in the migration package update (defined by plugin authors). A newly created workspace just sets the range in the `package.json` instead of resolving the latest valid version. This is by design.

I understand you were probably more concerned about differences between the `@typescript-eslint/*` packages. As mentioned above, we're gonna need a reproduction to be able to help because we can't reproduce it.

**Comment by zilia-gmethot** [comment] 2023-05-09 19:02
Here is a repository that is similar to the issue I'm experiencing: https://github.com/zilia-gmethot/reproduce-nx-issue-15841

I would have liked to share a StackBlitz but I was unable to configure something that would work out of the box. Here is how you can reproduce the issue:

1. Clone the repository
2. Install dependencies by running `npm i`
3. Create migration files by running `npx nx migrate 14.1.9`
4. Install dependencies by running `npm i`

You should obtain the following stack trace:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-workspace@0.0.0
npm ERR! Found: @typescript-eslint/parser@4.33.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"~4.33.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"~5.18.0" from @nrwl/eslint-plugin-nx@14.1.9
npm ERR! node_modules/@nrwl/eslint-plugin-nx
npm ERR!   dev @nrwl/eslint-plugin-nx@"14.1.9" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by leosvelperez** [comment] 2023-05-10 08:40
@zilia-gmethot thanks for the repro!

The issue happens because you don't have `@nrwl/linter` in your `package.json`. That's the plugin that handles the ESLint-related packages. You must have it as a dependency so the relevant packages are updated accordingly.

I'm closing this since the issue it's caused by a bad setup. Please add the `@nrwl/linter` package to your dependencies to solve it.

**Closed by leosvelperez** 2023-05-10 08:40 UTC
Labels: type: bug, scope: angular

**Comment by zilia-gmethot** [comment] 2023-05-10 18:32
> @zilia-gmethot thanks for the repro!
> 
> The issue happens because you don't have `@nrwl/linter` in your `package.json`. That's the plugin that handles the ESLint-related packages. You must have it as a dependency so the relevant packages are updated accordingly.
> 
> I'm closing this since the issue it's caused by a bad setup. Please add the `@nrwl/linter` package to your dependencies to solve it.

We are indeed missing a package. Thanks for your help. Even though it is unlikely to happen, a mechanism to detect such missing packages would be appreciated.
