### ISSUE TITLE
Dist folder not restored if no changes

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#8614] opened 2022-01-20 13:47 UTC
## Current Behavior
On our CI if a build is kicked off with no changes (actually even with a change in a scss file in one case) then the dist folder is not restored.  You get a message that "Nx read the output from cache instead of running the command for 1 out of 1 tasks".  For our case the CI shares a cache directory but pulls down a brand new instance of our repo each time.  Because of this there is no output folder and the post build steps fail (we zip up the app from dist) since not dist folder exists.  Previous versions of nx (< 13) still created the dist folder.

## Expected Behavior
output is built even if it is just copied from cache.

## Steps to Reproduce
just create a new repo with an app.  Build, delete dist folder and then build again.

### Environment
 Node : 14.17.0                              
 OS   : win32 x64                            
 npm  : 6.14.13                              
                                             
 nx : 13.4.5                                 
 @nrwl/angular : 13.4.5                      
 @nrwl/cli : 13.4.5                          
 @nrwl/cypress : 13.4.5                      
 @nrwl/devkit : 13.4.5                       
 @nrwl/eslint-plugin-nx : 13.4.5             
 @nrwl/express : undefined                   
 @nrwl/jest : 13.4.5                         
 @nrwl/linter : 13.4.5                       
 @nrwl/nest : undefined                      
 @nrwl/next : undefined                      
 @nrwl/node : undefined                      
 @nrwl/nx-cloud : undefined                  
 @nrwl/react : undefined                     
 @nrwl/react-native : undefined              
 @nrwl/schematics : undefined                
 @nrwl/tao : 13.4.5                          
 @nrwl/web : undefined                       
 @nrwl/workspace : 13.4.5                    
 @nrwl/storybook : 13.4.5                    
 @nrwl/gatsby : undefined                    
 typescript : 4.4.4                          
 rxjs : 7.4.0                                
 ---------------------------------------     
 Community plugins:                          
        @angular/animations: 13.1.2          
        @angular/common: 13.1.2              
        @angular/compiler: 13.1.2            
        @angular/core: 13.1.2                
        @angular/forms: 13.1.2               
        @angular/platform-browser: 13.1.2    
        @angular/platform-browser-dynamic: 13
        @angular/router: 13.1.2              
        @angular-devkit/build-angular: 13.1.3
        @angular/cli: 13.1.3                 
        @angular/compiler-cli: 13.1.2        
        @angular/language-service: 13.1.2    
        @storybook/angular: 6.4.13

**Comment by jasedwards** [comment] 2022-01-20 16:38
One update on above.  I mentioned that at one point it did not generate the dist folder even though I changed an scss file.  this part was fixed by adding the libs/styles folders to implicit dependencies in nx.json.  so it appears this is just a problem if there were no changes.

**Comment by jasedwards** [comment] 2022-02-01 16:38
I just updated to latest and the fix for #8504 does appear to have fixed this as well.

**Comment by mszmida** [comment] 2022-04-29 18:09
The problem still exists in **v14.0.3**.

**Comment by GrandSchtroumpf** [comment] 2022-05-16 09:57
I updated to latest and cache restoration is still not working.
Here is my config: 
```
Node : 16.14.0
OS   : win32 x64
npm  : 8.5.2

nx : 14.1.5
@nrwl/angular : 14.1.5
@nrwl/cypress : 14.1.5
@nrwl/devkit : 14.1.5
@nrwl/eslint-plugin-nx : 14.1.5
@nrwl/jest : 14.1.5
@nrwl/js : 14.1.5
@nrwl/linter : 14.1.5
@nrwl/node : 14.1.5
@nrwl/nx-cloud : 14.0.3
@nrwl/storybook : 14.1.5
@nrwl/workspace : 14.1.5
typescript : 4.5.5
```

**Comment by Nodonisko** [comment] 2022-06-27 17:05
Hi,
I created new project with nx version `14.3.6` and it seems problem is still here. If I delete folder and run build again with nx, it's not restored until some changes are made. This will cause dependent tasks fail.

**Comment by Nodonisko** [comment] 2022-06-27 17:30
I did also experiment with remote cache, I cleaned whole project with `git clean -dfx` then run nx and I got green for all build tasks with message `[remote cache]`, but folder is not restored so dependent tasks fails.

**Comment by charlesvg** [comment] 2022-08-13 13:09
As a workaround I added the `dist` folder to the inputs, basically telling NX that it should consider the dist folder (but not its contents) when determining whether or not something has changed.

This will cause a cache miss; causing a rebuild; causing the dist folder to appear.

`  "nx": {
    "namedInputs": {
      "default": [
        "{projectRoot}/**/*",
        "{projectRoot}/dist"
      ]
    },
    "targets": {
      "build": {
        "inputs": [
          "default"
        ]
      }
    }
  }`

**Comment by sheakelly** [comment] 2022-09-30 06:19
I am experiencing this issue on version 14.8.1

**Comment by dewiktor2** [comment] 2022-10-12 10:19
Have same issue on version 14.8.3,  dist folder not created when using nx-cloud and nothing has changed.

**Comment by royi-frontegg** [comment] 2022-11-02 08:42
have the same issue in 15.0.4

**Comment by kraklin** [comment] 2022-11-15 14:27
same here - `15.0.13` 🤷‍♂️

**Comment by GrandSchtroumpf** [comment] 2022-11-16 14:43
It does feel like a big bug no? It means that we cannot use nx-cloud as the outcome of the distributed cache is not written in the dist folder...

**Comment by matthias-ccri** [comment] 2023-02-07 23:43
We encountered this issue, and found a resolution. We were using `namedInputs` to define keys for use in `inputs` and `outputs`, but it turns out these keys are not valid in `outputs`. Removing `namedInputs` keys from `outputs` seemed to resolve our issues.

**Comment by FrozenPandaz** [comment] 2023-02-28 23:09
This usually happens if your outputs are not specified correctly. If this is the case, then Nx will believe that nothing is cached and there is nothing to restore.

Can someone please provide a repo where this issue can be reproduced?

**Comment by colinparker-er** [comment] 2023-03-08 16:19
I'm using 14.8.4 and am also seeing this. While I don't have a full repo to share at the moment, the configuration we are using outputs the build artifacts to a folder we use to deploy many things from, which is outside of the workspace. Here's a sample from a project.json in the workspace:
```
"outputs": ["{options.outputPath}"],
"options": {
    "outputPath": "../content/apps/test-app",
```
The non-cached builds work fine and output to the folder, but restoring from cache does not despite indicating that it read from cache. The behavior is similar to this feature issue:
https://github.com/nrwl/nx/issues/5433

**Comment by talzach** [comment] 2023-03-09 07:38
Was able to fix the issue by specifying the outputs directly to the project root dist folder in the `nx.json` file:
```
"targetDefaults": {
     "build": {
      "dependsOn": ["^build"],
      "outputs": ["{projectRoot}/dist"]
    }
}
```
nx v15.8.5

**Comment by damiangreen** [comment] 2023-03-21 10:07
Getting this on 15.8.6

**Comment by damiangreen** [comment] 2023-04-06 08:27
not stale still an issue

**Comment by neilsoult** [comment] 2023-04-20 17:06
> This usually happens if your outputs are not specified correctly. If this is the case, then Nx will believe that nothing is cached and there is nothing to restore.
> 
> Can someone please provide a repo where this issue can be reproduced?

can you give us instructions on how to correctly specify outputs?

**Comment by vglazov-tulaco** [comment] 2023-04-25 04:30
> This usually happens if your outputs are not specified correctly. If this is the case, then Nx will believe that nothing is cached and there is nothing to restore.
> 
> Can someone please provide a repo where this issue can be reproduced?

It would be great to see at least one example of a properly configured output.

**Comment by tonivj5** [comment] 2023-05-10 08:24
Up

**Comment by scarryaa** [comment] 2023-05-16 13:13
I just started getting this issue as well. In my case at least, when I run "server", it builds the server files correctly. But when I run "serve-ssr" after, it is deleting the dist directory along with the server folder, which seems like it's resulting in the error.

**Comment by tonivj5** [comment] 2023-05-31 05:38
> Up

**Comment by tonivj5** [comment] 2023-06-15 05:55
> > Up
> 
>

**Comment by Nodonisko** [comment] 2023-06-21 12:36
Up

**Comment by alexandersels** [comment] 2023-07-03 23:49
Same for nx 15.9.4

**Comment by tonivj5** [comment] 2023-07-18 00:49
> > > Up
> > 
> > 
> 
>

**Comment by anishmiviewis** [comment] 2023-07-21 17:59
Any thing on this yet? We are also facing same issue in 16

**Comment by tonivj5** [comment] 2023-08-05 09:44
> > > > Up
> > > 
> > > 
> > 
> > 
> 
>

**Comment by Pho3niX90** [comment] 2023-08-09 07:42
Same issue.

Recently switched to NX, hoping to increase my build times by leveraging the caching, and getting rid of github artifacts, only now to realize it doesn't actually product the dist folder when cache hit, defeating the purpose all together.

**Comment by daelmaak** [comment] 2023-08-12 05:40
How is this still not addressed? This is such a basic issue which makes task caching unusable for me always when I need the real output.

So when I do release for instance, I have to skip the cache to be sure I get the outputs.
```sh
yarn build --skip-nx-cache
```

**Comment by skoropadas** [comment] 2023-08-22 11:05
For me, it didn't work because of an incorrect `output` value, probably because of a lot of migration something went wrong, so I just updated `output` property like this:

```json
"outputs": ["{workspaceRoot}/dist/{projectRoot}"]
```

And now everything works fine

**Comment by hewelt** [comment] 2023-08-22 11:08
@daelmaak Check where do you [output built files](https://nx.dev/reference/project-configuration#outputs). NX should automatically re-create the files if you put it in `build`, `dist` or `public`. If it's something custom, you need to specify it in `nx.json` (globally) or in `project.json` (only for one project)

nx.json example:
```json
"build": {
      "dependsOn": ["^build"],
      "inputs": ["sharedGlobals", "productionFiles"],
      "outputs": ["lib"]
    },
``` 

Here `lib` is a custom output directory name, so I had to add it to the `outputs` array.

**Comment by tonivj5** [comment] 2023-09-06 08:10
> > > > > Up

**Comment by Nodonisko** [comment] 2023-09-12 06:31
Still an issue for me

**Comment by daelmaak** [comment] 2023-09-12 07:25
> @daelmaak Check where do you [output built files](https://nx.dev/reference/project-configuration#outputs). NX should automatically re-create the files if you put it in `build`, `dist` or `public`. If it's something custom, you need to specify it in `nx.json` (globally) or in `project.json` (only for one project)
> 
> nx.json example:
> 
> ```json
> "build": {
>       "dependsOn": ["^build"],
>       "inputs": ["sharedGlobals", "productionFiles"],
>       "outputs": ["lib"]
>     },
> ```
> 
> Here `lib` is a custom output directory name, so I had to add it to the `outputs` array.

I actually use the default `dist`, so it's even weirder that it doesn't work as expected.

**Comment by tonivj5** [comment] 2023-09-27 14:43
> > > > > > Up
> 
>

**Comment by FrozenPandaz** [comment] 2023-10-23 19:29
Hi all,

I think this issue is too broad to be actionable. I am going to close it in favor of new issues.

As I said before, sometimes this is the behavior you might see if your outputs are not specified properly. Please read [this guide](https://nx.dev/core-features/cache-task-results#finetune-caching-with-inputs-and-outputs) and double check your outputs.

With the latest versions of Nx, if you run `nx build app1 --graph stdout` you will see a JSON object be output. If you check the value of `outputs` in the task, it will show a path relative from the workspace root. Please make sure that path is correct.

If the path is correct and this is still not working for you, please open a new issue with more specific details.

**Closed by FrozenPandaz** 2023-10-23 19:29 UTC
Labels: type: bug, blocked: repro needed, scope: core
