### ISSUE TITLE
No matching version found for @nrwl/tao@12.99.0

### ISSUE THREAD

**Issue by memee** [nrwl/nx#5333] opened 2021-04-13 06:52 UTC
## Current Behavior

npm install -g nx
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.

## Steps to Reproduce

npm install -g nx

### Failure Logs

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by TristanTouchain** [comment] 2021-04-13 07:23
Same here with an `yarn global add @nrwl/cli`

**Comment by vltansky** [comment] 2021-04-13 08:02
Same here for `@nrwl/cli@12.99.0` and `@nrwl/devkit@12.99.0` running `nx migrate latest`:

```
nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest

 ERROR  The migrate command failed.

Command failed: npm install --legacy-peer-deps @nrwl/workspace@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/cli@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nrwl/workspace'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vltansky/.npm/_logs/2021-04-13T07_55_22_874Z-debug.log

Run migrate with --to="package1@version1,package2@version2"
/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-9997U1QB3T12fAQ/node_modules/.bin/tao migrate latest
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/home/vltansky/bll-ui/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:80:25)
    at Object.runCommand (/home/vltansky/bll-ui/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/vltansky/bll-ui/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/home/vltansky/bll-ui/node_modules/@nrwl/cli/bin/nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1020,
  stdout: null,
  stderr: null
}
```

also for: 
`nx migrate @nrwl/workspace@12.0.2`

```
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@12.0.2

 ERROR  The migrate command failed.

Command failed: npm install --legacy-peer-deps @nrwl/workspace@12.0.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/devkit@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@nrwl/workspace'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vltansky/.npm/_logs/2021-04-13T07_58_55_782Z-debug.log

Run migrate with --to="package1@version1,package2@version2"
/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /tmp/tmp-1067ohdgxYHBWf15/node_modules/.bin/tao migrate @nrwl/workspace@12.0.2
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.handler (/home/vltansky/bll-ui/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:80:25)
    at Object.runCommand (/home/vltansky/bll-ui/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/home/vltansky/bll-ui/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/home/vltansky/bll-ui/node_modules/@nrwl/cli/lib/init-local.js:23:13)
    at Object.<anonymous> (/home/vltansky/bll-ui/node_modules/@nrwl/cli/bin/nx.js:42:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1088,
  stdout: null,
  stderr: null
}
```

**Comment by TristanTouchain** [comment] 2021-04-13 08:34
Related to this issue: #5327 
downgrade to 12.0.1 for the moment

**Comment by lucianlature** [comment] 2021-04-13 08:43
Getting the same problem when trying to install older versions

`npm install -g nx@11.2.10` will fail giving me

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Simon-Hayden-iteratec** [comment] 2021-04-13 08:53
This also happens with `npx create-nx-workspace`. Due to the `npm install --silent` it took some digging, but after removing the `--silent` flag from the code (locally) I get the following error:

````
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nrwl/workspace@12.99.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
````

**Comment by Raju-N** [comment] 2021-04-13 10:17
Replace `npm install -g nx@11.2.10` with `npm install -g @nrwl/cli@11.2.10`.

Since nx is alias to @nrwl/cli.

**Comment by Raju-N** [comment] 2021-04-13 10:21
> Getting the same problem when trying to install older versions
> 
> `npm install -g nx@11.2.10` will fail giving me
> 
> ```
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.


Try with `npm install -g @nrwl/cli@11.2.10` instead `npm install -g nx@11.2.10`.

Since nx is alias to @nrwl/cli.

**Comment by ddingel** [comment] 2021-04-13 11:33
> > Getting the same problem when trying to install older versions
> > `npm install -g nx@11.2.10` will fail giving me
> > ```
> > npm ERR! code ETARGET
> > npm ERR! notarget No matching version found for @nrwl/tao@12.99.0.
> > npm ERR! notarget In most cases you or one of your dependencies are requesting
> > npm ERR! notarget a package version that doesn't exist.
> > ```
> 
> Try with `npm install -g @nrwl/cli@11.2.10` instead `npm install -g nx@11.2.10`.

Tried in a fresh docker container:
```
npx create-nx-workspace --preset=angular
✔ Workspace name (e.g., org name)     · hans
✔ Application name                    · hans
✔ Default stylesheet format           · css
✔ Default linter                      · eslint
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No

>  NX  Nx is creating your workspace.

  To make sure the command works reliably in all environments, and that the preset is applied correctly,
  Nx will run "npm install" several times. Please wait.


>  NX   ERROR  Something went wrong! v12.0.2

node:child_process:707
    err = new Error(msg);
          ^

Error: Command failed: npm install --silent
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at createSandbox (/root/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:417:21)
    at /root/.npm/_npx/d2207cf76adb22dc/node_modules/create-nx-workspace/bin/create-nx-workspace.js:112:24
    at Generator.next (<anonymous>)
    at fulfilled (/root/.npm/_npx/d2207cf76adb22dc/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 103,
  stdout: null,
  stderr: null
}
```

Before running that command we installed nrwl/cli and nrwl/workspace with a specific version, as we can check:
```
root@a06f6aac5674:/# npm list -g --depth=0
/usr/local/lib
+-- @nrwl/cli@12.0.1
+-- @nrwl/workspace@12.0.1
+-- npm@7.7.6
`-- prettier@2.2.1

```

> 
> Since nx is alias to @nrwl/cli.

Is it, as far is I can tell from npmjs.com [nx](https://www.npmjs.com/package/nx/v/12.0.1) is not just a alias to [nrwl/cli](https://www.npmjs.com/package/@nrwl/cli/v/12.0.1) but, because of different number of files and different package size, a different package.

**Comment by cyrus-za** [comment] 2021-04-13 13:40
I solved this by adding yarn resolutions, but this is solved in 12.0.3 anyways

**Comment by FrozenPandaz** [comment] 2021-04-13 14:54
Sorry all,

12.0.3 was published to resolve the issue.

12.0.2 was mispublished so I deprecated it and you should use 12.0.3 or 12.0.1 instead.

I am also going to close this issue as it is a duplicate of https://github.com/nrwl/nx/issues/5327.

Please continue discussing there if you still have issues.

**Closed by FrozenPandaz** 2021-04-13 14:54 UTC
Labels: type: bug

**Comment by minijus** [comment] 2021-04-14 18:22
Same issue with 12.0.5

**Comment by jbistis** [comment] 2021-12-21 11:42
Same issue with 12.2.6

**Comment by mokipedia** [comment] 2022-01-27 14:20
Having a similar issue with @nrwl/web@13.5.3
`npm ERR! notarget No matching version found for postcss-discard-comments@^5.0.2.`
