### ISSUE TITLE
Using yarn@berry?

### ISSUE THREAD

**Issue by PepijnSenders** [nrwl/nx#2177] opened 2019-12-11 20:03 UTC
## Description

The next yarn comes with a lot of workspace tooling basically out of the box. Maybe nx.dev could be a plugin inside the new yarn?

https://next.yarnpkg.com/

**Comment by FrozenPandaz** [comment] 2019-12-12 01:47
Hi, thank you for the suggestion.

From what I can see, yarn worktrees and Nx solve different problems.

I think yarn v2 will make it a lot easier to develop packages but not really help much for application development.

With Nx, we generally recommend there be only `package.json` which means yarn workspaces offers very little to an Nx workspace.

Plug and play, no installs, and offline support will yield benefits that are orthogonal to Nx.

Perhaps I'm missing something. Could you please add more specific details about how you think Nx can work better with yarn v2?

**Comment by PepijnSenders** [comment] 2019-12-13 17:07
Sorry for being a bit vague, but that's exactly why I thought it would be cool for nx.dev to integrate it. Why was the decision currently made to just have one package.json?

**Comment by vsavkin** [comment] 2019-12-19 15:40
@PepijnSenders we embrace the single-version policy (as do google, facebook etc). The easiest way to achieve this is to have a single node_modules folder at the root. You can of course have more than one node_modules folder with Nx and use something like `yarn workspaces` or `lerna` to manage it. It works, but goes against the single-version policy, so we don't recommend it unless you **have to** do it.

The problem is that the words like 'workspace' or 'monorepo' are used in different context and different people mean very different things when using them. For instance, `yarn workspaces` and `nx` have nothing to do with each other and can be used together. 

I'm going to close this issue. If you have some conrete ideas on how these tools can be used together, please open another issue!

Thank you!

**Closed by vsavkin** 2019-12-19 15:40 UTC
Labels: blocked: more info needed, scope: misc, type: question / discussion
