### ISSUE TITLE
nx:run-commands runtime input is broken

### ISSUE THREAD

**Issue by deser** [nrwl/nx#18432] opened 2023-08-02 00:20 UTC
### Current Behavior

Whenever I want to create a non-cacheable target using `"inputs": [{ "runtime": "date +%s" }]` pattern it is doesn't work on the latest NX (16.6.0). It did work on 15.7.0 though.
What I mean by it doesn't work - a command having such inputs is cacheable anyway.

### Expected Behavior

Whenever command has runtime input which is changing it's value every run - command should not be cached. 

### Steps to Reproduce

1. Create a react integrated repo (build will be by default cacheable target)
2. Create an app or lib there.
3. Use this build target:
```
"build": {
      "executor": "nx:run-commands",
      "defaultConfiguration": "development",
      "inputs": [{
        "runtime": "date +%s"
      }],
      "options": {
        "cwd": "../..",
        "parallel": false
      },
      "configurations": {
        "development": {
          "commands": ["echo $(date)"]
        }
      }
    }
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.16.0
   OS     : darwin-arm64
   npm    : 8.11.0
   
   nx (global)        : 16.5.0
   nx                 : 16.6.0
   @nx/js             : 16.6.0
   @nx/jest           : 16.6.0
   @nx/linter         : 16.6.0
   @nx/workspace      : 16.6.0
   @nx/devkit         : 16.6.0
   @nx/eslint-plugin  : 16.6.0
   @nx/node           : 16.6.0
   @nx/react          : 16.6.0
   @nrwl/tao          : 16.6.0
   @nx/web            : 16.6.0
   @nx/webpack        : 16.6.0
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   nx-stylelint : 14.0.2
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

In addition if I want to use input outside of nx monorepo - it doesn't work as well (changes in those source files are not tracked so cached result is taken). Would be good to make it work as well.

Example:
```
"build": {
      "executor": "nx:run-commands",
      "defaultConfiguration": "development",
      "inputs": ["{workspaceRoot}/../../buddy/**/*"],
      "options": {
        "cwd": "../..",
        "parallel": false
      },
      "configurations": {
        "development": {
          "commands": ["echo $(date)"]
        }
      }
    }
```

**Comment by mattjquinn** [comment] 2023-09-13 14:51
Also having this issue when trying to write an e2e target that is run whenever the sha256sum of external files changes:

```
"targets": {
    "e2e": {
      "executor": "nx:run-commands",
      "inputs": [
        { "runtime": "./apps/ui-e2e/e2e-hash-backend.sh" }
      ],
      "options": {
        "commands": [
          {
            "command": "./apps/ui-e2e/e2e-start.sh",
            "forwardAllArgs": true
          }
        ],
        "parallel": false
      }
    },
```

If I change any of the files hashed by the script, I can verify that the hash output by the script changes, but subsequent runs of the e2e task for this app don't run.

**Comment by AgentEnder** [comment] 2023-10-23 15:03
Hey 👋  - this is caused by the daemon caching the result of the runtime input. In practice this means that on CI the target would not be cacheable, but locally you may see some cache hits.

If you truly don't want the target to be cacheable, you should set `cache: false` for the target. If you need it for DTE or similar, the runtime input with the time should work, just be aware of the daemon caching the result as I mentioned.

This is to avoid rerunning potentially heavy commands multiple times within the same task graph. Some fixes have been done in this area recently.

I'm going to close this out as it is a known issue / behavior of the daemon, feel free to ask for more info if there is anything unclear.

**Closed by AgentEnder** 2023-10-23 15:03 UTC
Labels: type: bug, scope: core
