### ISSUE TITLE
Cache folder created in node_modules/.cache/ despite configuring it differently

### ISSUE THREAD

**Issue by damiangreen** [nrwl/nx#16506] opened 2023-04-24 15:18 UTC
### Current Behavior

With an nx.json as follows:
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test"],
        "cacheDirectory": "nxCache"
      }
    }
  },

  "targetDefaults": {
    "build": {
      "inputs": ["!{projectRoot}/**/*.md"]
    }
  }
}

Run 
`rm node_modules/.cache/nx`

run our build script.
` npx nx run-many --target=build,test --projects=* --exclude front-end-ui`
Have a look in the old default folder
`ls node_modules/.cache/nx`

Contains 
d/  lockfile.hash  nxdeps.json  run.json

### Expected Behavior

shoudlnt cache anything in node_modules

### Steps to Reproduce

1.
With an nx.json as follows:
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test"],
        "cacheDirectory": "nxCache"
      }
    }
  },

  "targetDefaults": {
    "build": {
      "inputs": ["!{projectRoot}/**/*.md"]
    }
  }
}

2. rm node_modules/.cache/nx
3. build  the packages.
4. See that files are created in node_modules again

### Nx Report

```shell
Node : 18.16.0
   OS   : win32 x64
   pnpm : 7.29.2

   nx                      : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   typescript              : 5.0.4
```

**Comment by AgentEnder** [comment] 2023-04-24 15:38
Can you run `nx reset` and see if this clears up? Its possible the daemon is writing info to where the cache directory was set when it was launched - not 100% sure.

**Comment by aparij** [comment] 2023-04-25 15:06
Having the same issue, moved from NX 12 (where it worked) to NX 15. Also it looks like it creates both and only some packages are put in the default .cache

**Comment by AgentEnder** [comment] 2023-04-26 22:30
These entries are not related to cache outputs, but rather related to the project graph. They are not controlled via the cacheDir property as that is frequently used to store the cache in a shared area. The project graph cache **_should not_** be treated this way, as it can cause issues with multiple copies of Nx writing / reading it at various times.

If you really want to move them, you can do so with the `NX_PROJECT_GRAPH_CACHE_DIRECTORY` environment variable.

**Comment by AgentEnder** [comment] 2023-04-26 22:35
Since this **_is_** working as intended (verified against this repo and another) I'm going to close this out.

**Closed by AgentEnder** 2023-04-26 22:35 UTC
Labels: type: bug, scope: core

**Comment by damiangreen** [comment] 2023-04-27 08:03
is it not possible to configure NX_PROJECT_GRAPH_CACHE_DIRECTORY  in nx.,json? It has to be an env variable?

**Comment by damiangreen** [comment] 2023-04-27 09:24
I created a file called .monorepo.env
with 
`NX_PROJECT_GRAPH_CACHE_DIRECTORY=nxGraphCache` in it

ran
 env-cmd -f .monorepo.env npx nx run-many --target=build,test --projects=* --exclude front-end-ui
 
then 
`ls node_modules/.cache`
and an `nx` folder has reappeared in here.. Albeit empty
