### ISSUE TITLE
@nrwl/workspace:move doesn't fix project name in jest.config.js

### ISSUE THREAD

**Issue by troywweber7** [nrwl/nx#6543] opened 2021-07-29 23:11 UTC
## Current Behavior

running `@nwrl/workspace:move ...` fixes imports and changes project name in most all configuration files, but doesn't do so for `jest.config.js`.

## Expected Behavior

The above, but it should fix `jest.config.js` as well.

## Steps to Reproduce

1. create lib
2. rename lib
3. observe `jest.config.js`

### Failure Logs

NA

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.17.3
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 11.3.1
  @nrwl/cli : 11.3.1
  @nrwl/cypress : 11.3.1
  @nrwl/devkit : 11.3.1
  @nrwl/eslint-plugin-nx : 11.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 11.3.1
  @nrwl/linter : 11.3.1
  @nrwl/nest : 11.3.1
  @nrwl/next : Not Found
  @nrwl/node : 11.3.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 11.3.1
  typescript : 4.1.5

**Comment by mandarini** [comment] 2021-07-30 13:15
Hi there @troywweber7 ! 
I know what the issue is, and I know how it can be fixed, but I am not 100% sure it should be fixed. 

So, in order to make sure this should be fixed, can you please show me how your root `jest.config.js` looks like?

**Comment by mandarini** [comment] 2021-07-30 13:18
Related PRs/Issues:
https://github.com/nrwl/nx/pull/6323
https://github.com/nrwl/nx/pull/6313
https://github.com/nrwl/nx/issues/6303

**Comment by mandarini** [comment] 2021-07-30 15:44
So, my bad, I just saw that you're on Nx `11.3.1`. This issue was a known issue, but it was fixed in the MR posted above. So if you update Nx to the latest version, you should not be experiencing this issue any more! :) I will close this issue now, but if your problem persists, or you need help with upgrading, just let me know!

Thanks @troywweber7

**Closed by mandarini** 2021-07-30 15:44 UTC
Labels: scope: core, type: bug
