### ISSUE TITLE
Broken link in https://nx.dev/recipes/recipes/generators

### ISSUE THREAD

**Issue by deepa** [nrwl/nx#13213] opened 2022-11-16 23:28 UTC
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/recipes/generators
https://nx.dev/recipes/executors

### Additional context or description

Many/all of the pages liked in recipes/generators and recipes/executors return 404.
Here are some examples: 
https://nx.dev/recipes/recipes/generators/local-generators
https://nx.dev/recipes/recipes/executors/use-executor-configurations

**Comment by AgentEnder** [comment] 2022-11-17 15:01
Closing as duplicate of 13181

**Closed by AgentEnder** 2022-11-17 15:01 UTC
Labels: type: docs
