### ISSUE TITLE
Fail to run update-16-0-0-add-nx-packages when migrating

### ISSUE THREAD

**Issue by jingfee** [nrwl/nx#16628] opened 2023-04-28 06:44 UTC
### Current Behavior

I get the following error when trying to migrate to Nx 16.0.0

`Cannot parse node_modules/resolve/test/resolver/malformed_package_json/package.json: CloseBraceExpected in JSON at 2:1`

The file in question looks like this

`{
`

Tried with both pnpm and npm and same error occurs. No issues when I migrated to 15.9.2 a couple of weeks ago.

### Expected Behavior

nx migrate should work without any errors

### Steps to Reproduce

node @ 18.16.0
npm @ 9.5.1 or pnpm @ 8.3.1

npx migrate latest
npm isntall
npx migrate --run-migrations

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : linux x64
   npm    : 9.5.1
   Hasher : Native
   
   nx                      : 16.0.0
   @nx/js                  : 16.0.0
   @nrwl/js                : 16.0.0
   @nx/jest                : 16.0.0
   @nrwl/jest              : 16.0.0
   @nx/linter              : 16.0.0
   @nrwl/linter            : 16.0.0
   @nx/workspace           : 16.0.0
   @nrwl/workspace         : 16.0.0
   @nx/angular             : 16.0.0
   @nrwl/angular           : 16.0.0
   @nx/cypress             : 16.0.0
   @nrwl/cypress           : 16.0.0
   @nx/devkit              : 16.0.0
   @nrwl/devkit            : 16.0.0
   @nx/eslint-plugin       : 16.0.0
   @nrwl/eslint-plugin-nx  : 16.0.0
   @nx/storybook           : 16.0.0
   @nrwl/storybook         : 16.0.0
   @nrwl/tao               : 16.0.0
   @nx/webpack             : 16.0.0
   @nrwl/webpack           : 16.0.0
   @nrwl/nx-cloud          : 16.0.5
   nx-cloud                : 16.0.5
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco  : 4.2.6
   ng2-charts         : 4.1.1
   @ngneat/spectator  : 14.0.0
   @storybook/angular : 7.0.7
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run update-16-0-0-add-nx-packages from @nrwl/workspace. This workspace is NOT up to date!


 >  NX   Cannot parse node_modules/resolve/test/resolver/malformed_package_json/package.json: CloseBraceExpected in JSON at 2:1

     1 | {
   > 2 | 
       | ^
   

Error: Cannot parse node_modules/resolve/test/resolver/malformed_package_json/package.json: CloseBraceExpected in JSON at 2:1
  1 | {
> 2 | 
    | ^

    at readJson (/home/a/node_modules/nx/src/generators/utils/json.js:20:15)
    at updateJson (/home/a/node_modules/nx/src/generators/utils/json.js:45:34)
    at /home/a/node_modules/@nx/devkit/src/utils/replace-package.js:22:9
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:30:13)
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:33:13)
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:33:13)
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:33:13)
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:33:13)
    at visitNotIgnoredFiles (/home/a/node_modules/@nx/devkit/src/generators/visit-not-ignored-files.js:33:13)
    at replacePackageInDependencies (/home/a/node_modules/@nx/devkit/src/utils/replace-package.js:18:56)
Command failed: npx nx _migrate --run-migrations --verbose

 >  NX   Command failed: npx nx migrate --run-migrations --verbose


Error: Command failed: npx nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (/tmp/tmp-18787-cVpJmuZw4g8c/node_modules/nx/src/utils/child-process.js:26:34)
    at /tmp/tmp-18787-cVpJmuZw4g8c/node_modules/nx/src/command-line/migrate.js:946:43
    at Generator.next (<anonymous>)
    at /tmp/tmp-18787-cVpJmuZw4g8c/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/tmp/tmp-18787-cVpJmuZw4g8c/node_modules/tslib/tslib.js:163:16)
    at runMigrations (/tmp/tmp-18787-cVpJmuZw4g8c/node_modules/nx/src/command-line/migrate.js:939:20)
Command failed: /tmp/tmp-18787-cVpJmuZw4g8c/node_modules/.bin/nx _migrate --run-migrations --verbose
```

**Comment by leosvelperez** [comment] 2023-04-28 08:42
Thanks for reporting this!

It looks like your `node_modules` folder is being processed. This shouldn't happen if the folder is correctly ignored in the `.gitignore` file. Nx workspaces are generated with that in place.

Please ensure you have a `.gitignore` file at the root of your workspace and that it's ignoring `node_modules`.

I'm closing this issue since it looks like a wrong setup. If you have `.gitignore` configured correctly and still have the issue, please leave a comment with a repo where the issue can be reproduced so we can troubleshoot it.

**Closed by leosvelperez** 2023-04-28 08:42 UTC
Labels: type: bug

**Comment by jingfee** [comment] 2023-04-28 09:37
You were right, I didn't have a `.gitignore` in the root of the Nx workspace. In our repo, the Nx workspace is part of a repo which also consists of .NET-applications, so the Nx workspace is in a subfolder and the `.gitignore` is located in the root of the repo. After creating a `.gitignore` in the Nx workspace root as well, the issue was resolved.

**Comment by mwamufiya** [comment] 2023-05-05 11:55
I'm running into this same issue, but I don't use git as source control. I use mercurial, which has a corresponding `.hgignore`. 

to date I have had no problems upgrading to various version of nx, with mercurial. but based on @leosvelperez response, this seems to suggests nx is speicifically looking for `.gitignore`.

is this true?
