### ISSUE TITLE
Workspace generator ignore the first argument

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#12981] opened 2022-11-03 20:09 UTC
## Current Behavior

`workspace-generator` ignore the first argument.
Given the following command:
`nx workspace-generator my-lib --name=foo`, it will produce the following error:
`Not enough non-option arguments: got 0, need at least 1`

But if I run `nx workspace-generator my-lib my-lib --name=foo` (notice the generator name provided twice) everything works as expected.

We upgraded from 14.5.10 so I am not sure in which version it broke.

## Expected Behavior

Workspace generator should respect the first argument.

## Steps to Reproduce
* Create a repo
* Create a workspace-generator
* Try to run it as instructed in the _Current Behavior_

### Failure Logs

```sh
nx workspace-generator my-lib (options)

Options:
  --help     Show help                                                                                                                                                                                 [boolean]
  --version  Show version number                                                                                                                                                                       [boolean]
  --name     The name of the library directory (will contain common, desktop, and ios libraries)                                                                                                        [string]

Find more information and examples at https://nx.dev/nx/workspace-generator

Not enough non-option arguments: got 0, need at least 1

```

### Environment
```sh
  Node : 16.16.0
   OS   : darwin arm64
   yarn : 3.2.4
   
   nx : 15.0.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.7
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.7
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.7
   @nrwl/js : 15.0.7
   @nrwl/linter : 15.0.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.0.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.7
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.7
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.7
   @nrwl/web : 15.0.7
   @nrwl/webpack : 15.0.7
   @nrwl/workspace : 15.0.7
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         rxjs: 6.6.7
         nx-stylelint: 14.0.2

```

**Comment by FrozenPandaz** [comment] 2022-11-03 20:26
This is a duplicate of https://github.com/nrwl/nx/issues/12677 and a version will be published soon.

**Closed** 2022-11-03 20:26 UTC
Labels: type: bug, scope: core
