### ISSUE TITLE
NX   Failed to process the project graph with "nx-js-graph-plugin".

### ISSUE THREAD

**Issue by TriPSs** [nrwl/nx#18435] opened 2023-08-02 07:31 UTC
### Current Behavior

We are getting errors on anything NX related (See below)

### Expected Behavior

That everything keeps running

### GitHub Repo

https://github.com/TriPSs/nestjs-query/tree/feature/update-deps

### Steps to Reproduce

See https://github.com/TriPSs/nestjs-query/actions/runs/5718976612/job/15495973398?pr=160

### Nx Report

```shell
>  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.

Original error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2


   Error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2
    at ProjectGraphBuilder.addDependency (/GITGithub/nestjs-query/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
    at ProjectGraphBuilder.addStaticDependency (/GIT/Github/nestjs-query/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at /Users/GIT/Github/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:174:41
    at Array.forEach (<anonymous>)
    at /Users/GIT/Github/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:170:49
    at Array.forEach (<anonymous>)
    at /Users/GIT/Github/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:168:72
    at Array.forEach (<anonymous>)
    at /Users/GIT/Github/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:165:26
    at Array.forEach (<anonymous>)


 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

### Failure Logs

```shell
>  NX   Failed to parse yarn lockfile

   Please open an issue at `https://github.com/nrwl/nx/issues/new?template=1-bug.yml` and provide a reproduction.
   
Original error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2


   Error: Target project does not exist: npm:react-loadable@ct-loadable@npm:5.5.2
    at ProjectGraphBuilder.addDependency (/home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
    at ProjectGraphBuilder.addStaticDependency (/home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
    at /home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:174:41
    at Array.forEach (<anonymous>)
    at /home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:170:49
    at Array.forEach (<anonymous>)
    at /home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:168:72
    at Array.forEach (<anonymous>)
    at /home/runner/work/nestjs-query/nestjs-query/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:165:26
    at Array.forEach (<anonymous>)


 >  NX   Failed to process the project graph with "nx-js-graph-plugin".

   The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
```

### Operating System

- [x] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ajwootto** [comment] 2023-08-02 21:36
seeing this as well, in my case the specific entry its choking on is:
`Original error: Target project does not exist: npm:class-validator@lidator@npm:0.13.4`

**Comment by AgentEnder** [comment] 2023-08-11 18:49
Hey, to troubleshoot this error we'll need your package.json + lockfile. Can yall provide that?

**Comment by TriPSs** [comment] 2023-08-15 07:54
@AgentEnder see the repo I provided (https://github.com/TriPSs/nestjs-query/tree/feature/update-deps)

**Comment by meeroslav** [comment] 2023-08-16 10:13
Duplicate of #18409

**Closed by meeroslav** 2023-08-16 10:13 UTC
Labels: type: bug, blocked: more info needed, scope: core

**Comment by AlexDeineha** [comment] 2023-08-16 13:33
Hello everybody,
I have the same error)
Please tell me how to fix it
```Original error: Target project does not exist: npm:nx-cloud@16.2.0
#11 2.858 
#11 2.858 
#11 2.858    Error: Target project does not exist: npm:nx-cloud@16.2.0
#11 2.858     at ProjectGraphBuilder.addDependency (/app/node_modules/nx/src/project-graph/project-graph-builder.js:180:19)
#11 2.858     at ProjectGraphBuilder.addStaticDependency (/app/node_modules/nx/src/project-graph/project-graph-builder.js:80:14)
#11 2.858     at /app/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:164:41
#11 2.858     at Array.forEach (<anonymous>)
#11 2.858     at /app/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:160:49
#11 2.858     at Array.forEach (<anonymous>)
#11 2.858     at /app/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:158:72
#11 2.858     at Array.forEach (<anonymous>)
#11 2.858     at /app/node_modules/nx/src/plugins/js/lock-file/yarn-parser.js:155:26
#11 2.858     at Array.forEach (<anonymous>)
#11 2.858 
#11 2.860 
#11 2.860  >  NX   Failed to process the project graph with "nx-js-graph-plugin".```

**Comment by meeroslav** [comment] 2023-08-17 09:40
@AlexDeineha you have to wait for this PR https://github.com/nrwl/nx/pull/18646 and next version of Nx
