### ISSUE TITLE
Can't import library from tools (generator)

### ISSUE THREAD

**Issue by kerosin** [nrwl/nx#4801] opened 2021-02-16 09:50 UTC
## Current Behavior

If I import a library from my workspace (e.g. `@my-workspace/utils`) on my generator

*my-generator.ts*
```
import { Tree } from '@nrwl/devkit';
import { sayHello } from '@my-workspace/utils';

export default async function (host: Tree, schema: any) {
  console.log(sayHello(schema.name));
}
```

 I get an error:
```
Cannot find module 'C:\src\nx-pnpm\dist\out-tsc\generators\my-generator'
Require stack:
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\commands\generate.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\index.js
```

## Expected Behavior
I'm able to import a library to a generator without receiving an error

## Steps to Reproduce
- git clone https://github.com/kerosin/nx-pnpm
- execute `nx workspace-generator my-generator test`

### Failure Logs
```
nx workspace-generator my-generator test --verbose

Warning: Fell back to using 'fs' to identify tools/tsconfig.generated.json as deleted. Please open an issue at https://github.com/nrwl/nx so we can investigate.
Cannot find module 'C:\src\nx-pnpm\dist\out-tsc\generators\my-generator'
Require stack:
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\commands\generate.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\index.js
Error: Cannot find module 'C:\src\nx-pnpm\dist\out-tsc\generators\my-generator'
Require stack:
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\shared\workspace.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\commands\generate.js
- C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at Module.require (C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at require (node:internal/modules/cjs/helpers:92:18)
    at implementationFactory (C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\shared\workspace.js:87:32)
    at Object.<anonymous> (C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\@nrwl\tao\11.2.12\node_modules\@nrwl\tao\src\commands\generate.js:171:40)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\nx-pnpm\node_modules\.pnpm\registry.npmjs.org\tslib\2.1.0\node_modules\tslib\tslib.js:114:62)

```

### Environment
```
 Node : 15.8.0
  OS   : win32 x64
  pnpm : 4.7.1

  nx : Not Found
  @nrwl/angular : 11.2.12
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 11.2.12
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : Not Found
  @nrwl/workspace : 11.2.12
  typescript : 4.0.7
```

**Comment by FrozenPandaz** [comment] 2021-02-17 20:15
https://github.com/nrwl/nx/issues/2536 has more details about this issue.

It's still open and we will look at it when we get a chance.

Closing this issue as a duplicate of https://github.com/nrwl/nx/issues/2536.

**Closed by FrozenPandaz** 2021-02-17 20:15 UTC
Labels: type: bug
