### ISSUE TITLE
Lint check is broken after using @nx/eslint:convert-to-flat-config

### ISSUE THREAD

**Issue by julienvonoetinger-eaton** [nrwl/nx#26586] opened 2024-06-18 08:22 UTC
### Current Behavior

I have tried to run the eslint migration to flat config using the following command:

`nx g @nx/eslint:convert-to-flat-config`

Then I have tried to check if the migration worked by using the following command:

`nx run blui-react-components-example:lint`

But I get an error:

`ENOENT: no such file or directory, stat 'C:\Users\e0636834\Documents\repositories\C:\Users\e0636834\Documents\repositories\explore-web-components\apps\blui-react-components-example\eslint.config.js'`

As you can see there is twice the path when trying to reach `eslint.config.js` but I have no idea why I have this.

### Expected Behavior

The linting commands works correctly after migration.

### Steps to Reproduce

1. Execute the script to migrate eslint to flat config: `nx g @nx/eslint:convert-to-flat-config`
2. Run lint check command: `nx run <project>:lint`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.20.0
OS     : win32-x64
yarn   : 1.22.22

nx (global)        : 19.3.0
nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/angular        : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nx/react          : 19.3.0
@nx/rollup         : 19.3.0
@nrwl/tao          : 19.3.0
@nx/vite           : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/webpack/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nx/vite/plugin
@nx/rollup/plugin
```

### Failure Logs

```shell
$ nx run blui-react-components-example:lint --verbose

> nx run blui-react-components-example:lint

Linting "blui-react-components-example"...
 NX   ENOENT: no such file or directory, stat 'C:\Users\e0636834\Documents\repositories\C:\Users\e0636834\Documents\repositories\explore-web-components\apps\blui-react-components-example\eslint.config.js'
Error: ENOENT: no such file or directory, stat 'C:\Users\e0636834\Documents\repositories\C:\Users\e0636834\Documents\repositories\explore-web-components\apps\blui-react-components-example\eslint.config.js'
```

### Operating System

- [ ] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

I have create my project recently using only the NX CLI.

**Comment by IgorVyatkin** [comment] 2024-06-18 13:01
Looks like it's a duplicate of #26424

**Closed** 2024-06-26 14:19 UTC
Labels: type: bug, scope: linter
