### ISSUE TITLE
NX error after updating to 19.5.3

### ISSUE THREAD

**Issue by Aubrey-Russell** [nrwl/nx#27198] opened 2024-07-29 22:46 UTC
### Current Behavior

Unable to compile federated types, Error: compile TS failed, the original command is 'npx tsc --project ...\node_modules\.federation\tsconfig.11a9cb42-e0ab-4650-9dbd-e50a75fd14d6.json'
Error: ENOENT: no such file or directory, open '...\dist\@mf-types.zip'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at _GenerateTypesPlugin.<anonymous> (...\node_modules\@module-federation\dts-plugin\dist\index.js:2470:140)
    at Generator.next (<anonymous>)
    at fulfilled (...\node_modules\@module-federation\dts-plugin\dist\index.js:54:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '...\\dist\\@mf-types.zip'
}

### Expected Behavior

Error should not occur

### Steps to Reproduce

1. Install a micro front end with a shell and federated module
2. yarn nx serve shell

### Nx Report

```shell
Node   : 21.1.0
OS     : win32-x64
yarn   : 4.3.1

nx (global)        : 19.1.1
nx                 : 19.5.3
@nx/js             : 19.5.3
@nx/jest           : 19.5.3
@nx/linter         : 19.5.3
@nx/eslint         : 19.5.3
@nx/workspace      : 19.5.3
@nx/cypress        : 19.5.3
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.3
@nx/node           : 19.5.3
@nx/react          : 19.5.3
@nrwl/tao          : 19.5.3
@nx/web            : 19.5.3
@nx/webpack        : 19.5.3
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
```

### Package Manager Version

yarn 4.3.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by Aubrey-Russell** [comment] 2024-07-30 02:55
Here's what seems to be happening--some MFEs seem to have an extracted zip folder while others have a zip folder with contents. The ones that are already extracted cause the problem

**Comment by jame-earnin** [comment] 2024-08-05 14:40
I have the same issue.
```
  [ Module Federation Manifest Plugin ]: Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
  Unable to compile federated types, Error: compile TS failed, the original command is 'npx tsc --project /home/runner/_work/web-app-frontend/web-app-frontend/apps/earnin-app/node_modules/.federation/tsconfig.7309c320-88f2-42dc-ac1d-628451765d5c.json'
  Error: ENOENT: no such file or directory, open '/home/runner/_work/web-app-frontend/web-app-frontend/apps/earnin-app/dist/@mf-types.zip'
      at Object.openSync (node:fs:581:18)
      at Object.readFileSync (node:fs:457:35)
      at _GenerateTypesPlugin.<anonymous> (/home/runner/_work/web-app-frontend/web-app-frontend/node_modules/@module-federation/dts-plugin/dist/index.js:2470:140)
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/_work/web-app-frontend/web-app-frontend/node_modules/@module-federation/dts-plugin/dist/index.js:54:24)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/runner/_work/web-app-frontend/web-app-frontend/apps/earnin-app/dist/@mf-types.zip'
  }
  ```

**Comment by Aubrey-Russell** [comment] 2024-08-05 19:38
@jame-earnin Any chance you are using shared libs as part of your MFE repo? Is this repo you have here shareable?

**Comment by OlgaShishka** [comment] 2024-08-06 08:36
I have the same issue

does anyone understand why nx tries to compile federated types and put them into @mf-types.zip inside every /[APP]/dist folder?
should it now work like that? I haven't found anything about that in the docs or in the Release notes.

**Comment by madangryscientist** [comment] 2024-08-06 10:24
I am also experiencing flaky builds due to this.

**Comment by iconag-bbasmer** [comment] 2024-08-06 12:36
I have the same issue.

**Comment by tbhag** [comment] 2024-08-06 14:32
I also have the same issue unforunately

**Comment by vadimka123** [comment] 2024-08-07 11:49
I have the same issue.

**Comment by Aubrey-Russell** [comment] 2024-08-07 18:50
@OlgaShishka its a good question. Why was this broken feature stealth released randomly with no explanation and no notes? It isn't helpful either and it clutters the heck out of the dist folder when the zip folder is expanded. Furthermore, if you try to delete the dist folder it slows things down massively. 

The rationale for this design is totally baffling to me. The way it worked before seemed perfect--now we've downgraded to this bizarre zipped type folder thing. I don't want a bunch of junk type files everwhere, and I don't see even any theoretical benefits for such a solution.

**Comment by iconag-bbasmer** [comment] 2024-08-08 06:03
@Aubrey-Russell I totally agree and speaking of slowing down things: I just upgraded to the latest version and my builds are now significantly slower than before. Didn't have much time yet to have a deeper look but I guess I have to (try to) investigate soon.

**Comment by Coly010** [comment] 2024-08-08 09:13
Hey everyone!

The Federated Types Plugin is a feature of the `@module-federation/enhanced` package.

This package is where all development of Module Federation itself (not owned by us) is now taking place by Zack Jackson (https://x.com/ScriptedAlchemy) and the ByteDance team (https://x.com/ByteDanceTalk).

We switched to this package because it is a drop in replacement for Webpack’s native Module Federation, and includes all the latest bug fixes, improvements and features of Module Federation.

You can learn more about it here: https://module-federation.io

This wasn’t simply a quick change to what package we used. This has been planned for months, and I tested as many scenarios as I could before we merged the change. We even have e2es testing Module Federation setups.

All that is to say, that this choice to use the new package was made to allow everyone using Module Federation with Nx to continue to receive the best Module Federation support from the people actively working on Module Federation as well as providing access to the new features.

The purpose of the Federated Types Plugin is that it will create typings for remotes that may not actually live in the same repository as other parts of your MFE architecture, covering cases where our typing support is unable to because we don’t have any information about these remotes.

Now back to the issue at hand.

I will investigate this to determine if it’s an issue with `@module-federation/enhanced` package solely, or if it’s related to it being used in an Nx workspace.

I understand that this is incredibly frustrating, but @Aubrey-Russell a clear reproduction with each step defined makes reproducing issues like this much easier. 

Simply stating install mfe and a federated module is not overly helpful because it doesn’t tell me the steps you took that resulted in seeing the error and it is also ambiguous over tech stack (React/Angular), SPA or SSR, static federation or dynamic federation, if you’re federating a module from a library, or if it’s just a standard remote, etc.

To speed this along, if you could provide a minimal reproduction repo that I can clone, it would be very much appreciated.

**Comment by Coly010** [comment] 2024-08-08 09:54
A workaround for now would be to turn off the `dts` plugin (https://module-federation.io/configure/dts.html) by adding the following to your `withModuleFederation()` in the `webpack.config` file:

```js
withModuleFederation(config, { dts: false })
```

**Comment by madangryscientist** [comment] 2024-08-08 10:29
> A workaround for now would be to turn off the `dts` plugin (https://module-federation.io/configure/dts.html) by adding the following to your `withModuleFederation()` in the `webpack.config` file:
> 
> ```js
> withModuleFederation(config, { dts: false })
> ```

Thanks that works for me.

**Closed** 2024-08-14 13:14 UTC
Labels: type: bug, scope: module federation

**Comment by rbirkgit** [comment] 2024-09-04 14:48
This update also broke all our MFE remotes. none of them are loading anymore. I see no errors.

It seems it all changed very drastically. Ports etc all changed. I find it strange this big change was done in a point release without much info.

**Comment by scott-gmr** [comment] 2024-09-18 17:51
Maintaining an Nx repo with module federation is turning out to be a huge pain overall, and I feel like an alpha tester for these features at this point. Apparently I can expect my whole module federation to completely change with no release notes and no major package upgrade, but since I have to migrate all Nx packages together I can't upgrade for other reasons with other packages without expecting to wrangle with this now. I'm going to be wary of any upgrade at this point. There's just too much magic being involved with everything.

**Comment by Aubrey-Russell** [comment] 2024-09-18 17:57
There has got to be some test cases that ensure basic module federation with remote apps work. I'd be happy to give some example repos that would allow the nx team to test remote module cases such as this one which showcased a different error:

https://github.com/Aubrey-Russell/grommet-react-mfe-issue-example

I created this one a while back. I can create another example with maybe 5-10 apps and a shell in react. That way as part of a new release the NX team can ensure that remote federated modules don't break

**Comment by iconag-bbasmer** [comment] 2024-09-19 06:23
I have updated my NX version to 19.7.3 and have found this blog entry that showed me how to setup the module federation with NX and RSBuild: https://blog.soumyanildas.com/nx-rspack-micro-frontend

I was able to make it work, even with dynamic module federation, which has some special twists coming with it, but anyway. 
Also these 2 videos helped me a lot with the setup:
https://www.youtube.com/watch?v=oJY92rZV8NE
https://www.youtube.com/watch?v=VE1FWi2L_-g

I'm still struggling with using css modules and rspack, though. But that's a different story.

**Comment by iconag-bbasmer** [comment] 2024-09-23 11:29
Ok, I have now also figured out how the (s)css modules have to be integrated with Rspack and Nx. 
I updated to Nx 19.7.4 and you can find my setup for Nx with Rspack including module federation, handling of parths in tsconfig and css / scss modules handling [here](https://stackoverflow.com/questions/79005653/setup-css-modules-with-rspack-using-nx-monorepo-and-react).

I hope this helps anymore.
