### ISSUE TITLE
Shared assets are copied into Next public folder during development (not ignored)

### ISSUE THREAD

**Issue by ShadiBlitz** [nrwl/nx#14421] opened 2023-01-17 11:36 UTC
### Current Behavior

After updating NX from version `14.4.2` to `15.5.1`, every time I run a NextJS app, the shared assets library content is copied to the running NextJS app public folder (not detected by git ignore). This case didn't happen before, the assets content where copied only during the build time for production.

The following changes were applied during the update migration on the project JSON file configurations: 
![Screenshot from 2023-01-17 13-28-54](https://user-images.githubusercontent.com/101566855/212888636-397b054a-703a-4c6f-9d10-822861f5db42.png)

And this is how we currently make the shared assets library accessible through a global path
![Screenshot from 2023-01-17 13-29-51](https://user-images.githubusercontent.com/101566855/212888885-037215c6-616a-4f65-8e4f-9c5e9698d56f.png)
: 

### Expected Behavior

The assets shouldn't be copied (or ignored) during development.

### Steps to Reproduce

1. Make a shared library with a global path
2. Run the project locally

### Nx Report

```shell
Node : 16.15.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 15.5.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.5.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.5.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.5.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.5.1
   @nrwl/js : 15.5.1
   @nrwl/linter : 15.5.1
   @nrwl/nest : Not Found
   @nrwl/next : 15.5.1
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.5.1
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.5.1
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.5.1
   @nrwl/web : 15.5.1
   @nrwl/webpack : 15.5.1
   @nrwl/workspace : 15.5.1
   @nrwl/vite : 15.5.1
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by ShadiBlitz** [comment] 2023-03-21 14:19
Any updates on this @FrozenPandaz ?

**Comment by jaysoo** [comment] 2023-04-26 20:47
After further discussion with the team, this is deemed as not a bug. 

The reason it worked previously in Nx 14 is because we run our own Express server and provided a static serve of the "public" folder that assets are copied to. See: https://github.com/nrwl/nx/blob/14.5.x/packages/next/src/executors/server/lib/default-server.ts#L23

There is an ongoing effort to not deviate too much from the standard Next.js setup, which means we do not want to bring the custom static serve back. The reason to not deviate too much is to support CLI flags like `--turbo` better, which is currently very hard without extra instrumentation logic on Nx's side.

This means that moving forward, you should be adding these entries to `.gitignore` to avoid them from being committed. Next.js only allows assets to be served from `public` folder so we need to add them there. This [Next.js example](https://github.com/vercel/next.js/blob/b6e0c350edd70d6d6deb490538b1b69256a94ad3/examples/with-ionic-typescript/next.config.js#L4) shows the same setup with `copy-webpack-plugin`.

You can open a [discussion topic](https://github.com/nrwl/nx/discussions) to discuss this further. We are looking at enhancements for our Next.js integration after Nx 16, so we can circle back on this then.

**Closed by jaysoo** 2023-04-26 20:47 UTC
Labels: type: bug, scope: nextjs
