### ISSUE TITLE
create-nx-workspace issues with "--cli=nx" argument

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#10241] opened 2022-05-11 11:10 UTC
run: 
```
npx create-nx-workspace@latest new-workspace --preset=angular --allPrompts=true --appName=example --cli=nx --name=new-workspace --nxCloud=true --packageManager=yarn
```

issues:
* will create README.md for React-based apps
* will not add "packageManager" value to nx.json
* will not create angular.json
* will not create decorate-angular-cli.js (and related code to "postinstall")
* will not add angularCompilerOptions to tsconfig.base.json

Issue happens because of "--cli=nx". It would explain issues #3 and #4, but not others

### Environment
create-nx-workspace v14.1.4, Node v18.1.0, npm v8.9.0

**Comment by AgentEnder** [comment] 2022-05-11 19:15
Hey, I'm assigning this to the angular scope since it looks like most of these are questions that would be best answered by those folks. In general though, here's my take on them:

- This is expected behavior, readme's per app give a good spot for some general notes.
- This isn't needed for Nx workspaces, since we infer the package manager based on which lockfiles are present.
- This is expected, --cli=nx generates `workspace.json` instead.
- This is expected, --cli=nx tells us that you will use `nx` instead of `ng`, so we don't need to decorate it.
- We set angularCompilerOptions on the individual apps layer, since workspaces may contain a mixture of frameworks and they don't need to be present in the tsconf for others.

If you have any further questions, or feel something needs to be addressed, I can reopen this. For now, I'm going ahead and closing it since things are working as we'd expect.

**Closed by AgentEnder** 2022-05-11 19:15 UTC
Labels: type: bug, scope: angular

**Comment by e-oz** [comment] 2022-05-12 06:19
> --preset=angular
and README for React. Expected behavior? Ok then :)

**Comment by AgentEnder** [comment] 2022-05-12 14:30
It sounded like the issue you noted was that readme's were getting generated for react based apps, not that the angular app you generated contained a readme formatted for react. I'll look into this.
