### ISSUE TITLE
Error while creating a new library inside a Next.js monorepo

### ISSUE THREAD

**Issue by GuiMoraesDev** [nrwl/nx#22598] opened 2024-04-01 12:42 UTC
### Current Behavior

After creating a fresh Next.js monorepo, I've tried to init a new lib using the command `pnpm nx g @nx/next:lib configs --verbose`, but it throws the following error
```
NX   Failed to process project graph. See errors below.

Failed to process project graph.
  The "@nx/jest/plugin" plugin threw an error while creating nodes from apps/conne-xtend/jest.config.ts:
    ● Validation Error:
    
      Module @nx/react/plugins/jest in the transform option was not found.
             <rootDir> is: /Users/guimoraesdev/Documents/Dev/Personal/conne-xtend/apps/conne-xtend
    
      Configuration Documentation:
      https://jestjs.io/docs/configuration
```

### Expected Behavior

Expecting to see the lib wizard.

### Steps to Reproduce

1. Init a Next.js preset monorepo
2. Run the following command `pnpm nx g @nx/next:lib configs --verbose`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 20.11.1
OS     : darwin-arm64
pnpm   : 8.15.5

nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/cypress        : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/next           : 18.2.1
@nrwl/tao          : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

### Package Manager Version

pnpm   : 8.15.5

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I was able to solve it by installing the package `"@nx/react": "18.2.1"`
It should be installed by default.

**Comment by eyea** [comment] 2024-04-07 09:36
Some here :(

I found the fast solution is give the comment in file **jest.config.ts**

```
export default {
  // ...
  transform: {
    // '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nx/react/plugins/jest',
  },
 // ...
};
```

but then, there has anothor issue about tailwind if you use tailwindcss
https://github.com/nrwl/nx/issues/22475

**Comment by ndcunningham** [comment] 2024-04-09 18:37
Can you try using `canary` or can you provide a repo of this i can't seem to reproduce it on my end.
I tried `v18.2.3`, `canary` & `v18.2.1`.

**Comment by THMKAE** [comment] 2024-04-12 13:28
Same on our end, we are using some scripts to implement a fresh workspace with next.js and some default libraries.
Version `17.3.2` is the last version without issues on our end.
Version `18.2.3` or `18.2.4` have the same issue.
The `canary` version does work for installation, but does not create any `targets` in the `project.json` files.

We are using the following to generate
the workspace:
```shell
npx create-nx-workspace@18.2.4 my-workspace \
    --preset=apps \
    --pm=yarn \
    --skipGit=true
```
the app:
```shell
yarn add --dev @nx/next@18.2.4
## followed by ...
nx g @nx/next:app my-app --appDir=false --style=@emotion/styled --src=false --directory=apps/my-app --projectNameAndRootFormat=as-provided --e2eTestRunner=cypress
```
and for libraries, we use our own custom generator:
```typescript
import { Tree, formatFiles } from '@nx/devkit';
import { libraryGenerator } from '@nx/next';
import { Schema } from './schema';
import { Linter } from '@nx/linter';

export default async function (tree: Tree, schema: Schema) {
  await libraryGenerator(tree, {
    ...schema,
    component: false,
    style: 'none',
    unitTestRunner: 'jest',
    linter: Linter.EsLint,
  });
  await formatFiles(tree);
}
```
But even if we are using the default library generator, the same (error) result is achieved, similar to the one below or the one mentioned by the OP

```shell
 NX  Generating @my-workspace/tools:lib

In Nx 19, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/next:library my-app-my-feature --directory libs/my-app/my-feature
In Nx 19, generating projects will no longer derive the name and root.
Please provide the exact project name and root in the future.
Example: nx g @nx/react:library my-app-my-feature --directory libs/my-app/my-feature
UPDATE .gitignore
UPDATE package.json
CREATE libs/my-app/my-feature/project.json
CREATE libs/my-app/my-feature/.eslintrc.json
CREATE libs/my-app/my-feature/README.md
CREATE libs/my-app/my-feature/src/index.ts
CREATE libs/my-app/my-feature/tsconfig.lib.json
CREATE libs/my-app/my-feature/tsconfig.json
CREATE libs/my-app/my-feature/jest.config.ts
CREATE libs/my-app/my-feature/tsconfig.spec.json
UPDATE nx.json
UPDATE tsconfig.base.json
CREATE libs/my-app/my-feature/src/server.ts
CREATE libs/my-app/my-feature/src/lib/hello-server.tsx

 NX   Failed to process project graph.
```

**Comment by ndcunningham** [comment] 2024-04-23 14:08
from @GuiMoraesDev 
> I was able to solve it by installing the package "@nx/react": "18.2.1"
It should be installed by default.

Yes, it should be if you could provide a repo of this where it does not get installed by default we could address it.
On our end this does not happen. I'll close the issue since you have solved it.

@THMKAE if you haven't already, can you open a new issue thanks.

**Closed by ndcunningham** 2024-04-23 14:08 UTC
Labels: type: bug, blocked: repro needed, scope: nextjs

**Comment by THMKAE** [comment] 2024-04-25 16:10
> from @GuiMoraesDev
> 
> > I was able to solve it by installing the package "@nx/react": "18.2.1"
> > It should be installed by default.
> 
> Yes, it should be if you could provide a repo of this where it does not get installed by default we could address it. On our end this does not happen. I'll close the issue since you have solved it.
> 
> @THMKAE if you haven't already, can you open a new issue thanks.

Will do when I find the time, in the meantime I'll give newer version a try as well.
