### ISSUE TITLE
ng generate gives maximum call stack size exceeded

### ISSUE THREAD

**Issue by BhaskaranR** [nrwl/nx#1067] opened 2019-02-09 01:56 UTC
-  I am running the latest version
-  I checked the documentation and found no answer
-  I checked to make sure that this issue has not already been filed

getting Maximum call stack size exceeded

```
ng generate @nrwl/schematics:library feature-restaurant-profile --parentModule=apps/web-kmeal-restaurant/src/app/app.module.ts --routing --lazy --dry-run --no-interactive
```

**Comment by FrozenPandaz** [comment] 2019-02-12 15:32
Is it possible for you to provide a minimal repro to help us debug?

Have you been able to make the issue go away by changing something? Perhaps 1 of the following?
[ ] Removing the `--lazy` flag
[ ] Removing the `--routing` and `--lazy` flag

**Comment by rolandoldengarm** [comment] 2019-04-10 00:03
I have the same problem, it's not always reproducable though. One one client it works fine, on another one it fails.

I've attached a debugger and I can see where it gets into an infinite loop:

![image](https://user-images.githubusercontent.com/14539000/55842363-3fc37f00-5b87-11e9-9ee9-d66dbb85808b.png)

While it's in an Angular CLI file, the issue only occurs when I enable @nrwl/schematics in angular.json. If I remove it, and use the stock Angular CLI schematics it works fine.

To debug: 

```node --inspect --debug-brk .\node_modules\@angular\cli\bin\ng g application test2```

Looking at the stacktrace, it's getting in an infinite loop. 

I'm on Windows Server 2012.

I just run: ```ng g application test1234```


```
λ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.4
Node: 10.15.3
OS: win32 x64
Angular: 7.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.4
@angular-devkit/build-angular      0.10.4
@angular-devkit/build-ng-packagr   0.10.4
@angular-devkit/build-optimizer    0.10.4
@angular-devkit/build-webpack      0.10.4
@angular-devkit/core               7.1.3
@angular-devkit/schematics         7.1.3
@angular/cdk                       7.3.3
@angular/cli                       7.0.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.4
@schematics/angular                7.0.4
@schematics/update                 0.10.4
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.1.3
webpack                            4.19.1
```
How can we make sure this issue is resolved?

**Comment by vsavkin** [comment] 2019-04-15 15:14
@rolandoldengarm the move operation in the angular cli had some issues. Do you have the same issue if you use the 7.3x version of the CLI?

**Comment by vsavkin** [comment] 2019-12-04 20:44
I'm going to close this issue. If the problem is still present, could you reopen it with a repro?

**Closed by vsavkin** 2019-12-04 20:44 UTC
Labels: blocked: repro needed, type: bug
