### ISSUE TITLE
Can't use separate builder versions across the same workspace

### ISSUE THREAD

**Issue by boxmein** [nrwl/nx#15042] opened 2023-02-16 09:25 UTC
### Current Behavior

If you have a Nx workspace with multiple packages, e.g.:

```
applications/
   app1/
   app2/
libraries/
   lib1/
```

Then it is not possible to use Yarn workspaces to set different versions of `@nrwl/angular` for app1 and app2, because `@nrwl/angular` will be resolved from the root workspace.

**What we were trying to do:**

* Create 4 package.json files: a root package.json with `"workspaces": ["applications/*", "libraries/*"]`, and sub-package.json for each app and library.
* Set `app1` to use `@nrwl/angular@11` and `app2` to use `@nrwl/angular@12`
* Both `app1` and `app2` would import `lib1`
* `lib1` compilation would fail with a compiler error

**What we diagnosed the root cause to be:**

* Since `app1` and `app2` use differing versions of `@nrwl/angular`, they also by extension use differing versions of Angular
* Yarn is free to decide which version ends up in the top-level node modules directory
* `@nrwl/nx` imports `@nrwl/angular` starting with the project root directory
* It's not deterministic which `@nrwl/angular` version will be loaded to compile `lib1`
* A compiler error occurs

### Expected Behavior

In the case of `@nrwl/angular` it is tightly coupled to the Angular version and therefore there's currently no way to have independently versioned Nx apps with Angular.

### Steps to Reproduce

* [Create 2 applications that depend on different versions of Angular similar to this project tree](https://github.com/nrwl/nx/issues/1777#issuecomment-1240440653)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 16.19.0
   OS   : darwin x64
   npm  : 8.19.3

   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.6.3
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.9.5
   ---------------------------------------
   Local workspace plugins:
         @qminder/one-specific-old-builder-thing
   ---------------------------------------
   Community plugins:
         apollo-angular: 1.10.0
```

### Additional Information

Previous discussion occurred under the other issue:

* https://github.com/nrwl/nx/issues/1777#issuecomment-1240440653
* https://github.com/nrwl/nx/issues/1777#issuecomment-1284980280
* https://github.com/nrwl/nx/issues/1777#issuecomment-1285077951
* https://github.com/nrwl/nx/issues/1777#issuecomment-1287659967
* https://github.com/nrwl/nx/issues/1777#issuecomment-1287661186
* https://github.com/nrwl/nx/issues/1777#issuecomment-1400454481
* https://github.com/nrwl/nx/issues/1777#issuecomment-1427656290
* https://github.com/nrwl/nx/issues/1777#issuecomment-1431945933

**Comment by AgentEnder** [comment] 2023-02-16 19:16
This isn't really a bug, Nx plugins are installed in the root. Its not picking up your @nrwl/angular package because its not in the root. This is expected behavior.

Additionally, even if it was to pick it up it would likely fail. Nx + @nrwl/* packages are generally required to be at the same version in a workspace, since they are developed together in the same monorepo. We make no promises about compatibility between differing versions, and see a good deal of issues opened that are fixed by syncing them back up.

That said, in v15.7 we launched broader support for LTS versions of angular. See: https://www.youtube.com/watch?v=IStJODzZSoc&t=155s

**Closed by AgentEnder** 2023-02-16 19:16 UTC
Labels: type: question / discussion, scope: core

**Comment by boxmein** [comment] 2023-02-20 08:13
> This isn't really a bug, Nx plugins are installed in the root. Its not picking up your @nrwl/angular package because its not in the root. This is expected behavior.

I was requested to track it as a separate issue by @meeroslav [here](https://github.com/nrwl/nx/issues/1777#issuecomment-1427656290).

> Additionally, even if it was to pick it up it would likely fail. Nx + @nrwl/* packages are generally required to be at the same version in a workspace, since they are developed together in the same monorepo. We make no promises about compatibility between differing versions, and see a good deal of issues opened that are fixed by syncing them back up.

As `@nrwl/angular` requires `@angular/compiler-cli` what you're saying is that you can't use separate library versions across the workspace?

This is a major caveat for the [package-based repos](https://nx.dev/concepts/integrated-vs-package-based#package-based-repos) support. In essence you can have package-based repos... but not for Angular :upside_down_face:

**Comment by meeroslav** [comment] 2023-02-20 10:41
@boxmein, what @AgentEnder was saying is that up until now the `@angular/compiler-cli` was part of the `@nrwl/angular` so you could not diverge from the version set by it.

Since v15.7.0 we no longer have a strict dependency on Angular. You can/should still have just one `@nrwl/angular` installed in the root.

Perhaps @Coly010 @leosvelperez can provide more info.

**Comment by Coly010** [comment] 2023-02-20 10:52
@boxmein 

Let me try to address some of your concerns :)

Package Based Repos are not being phased out. However, they interact differently with Nx Plugins and that's something to be carefully considered before choosing a Package Based Repo. You can still use an Integrated Repo and publish packages. Just an FYI.

Nx + `@nrwl/*` packages should be considered dev tools, and dev tools only. Since v15.7.0, we no longer depend on `@angular/*` packages. This means you can use `@nrwl/angular@15.7.0` with Angular 14 and 15. These are currently the only two versions that we can guarantee support for.

Your `nx` and `@nrwl/*` packages should be aligned on versions, and they should live at the root of your repo.

Your packages should then be able to define the version of Angular + Angular Devkit they depend on within their own package.json files.

When you run `nx build package-a` it _should_ use the correct version of Angular to build your package.

If it doesn't, please let me know. We may need to do additional work to support Yarn Workspaces with Multiple Angular Support

**Comment by boxmein** [comment] 2023-03-21 10:02
@meeroslav 

> Since v15.7.0 we no longer have a strict dependency on Angular. You can now target different Angular versions in your projects. At the moment this supports only v14 and v15.

This is a welcome change :) 

> You can/should still have just one @nrwl/angular installed in the root.

I agree with the sentiment behind the statement, but it wouldn't have saved us from paying the cost of converting our "package-based repo" to an "integrated repo". 

We ended up having to convert to integrated repo, because otherwise we were unable to use "Nx library projects" to share code between two frontend app projects.

@Coly010 Also thanks for your input, it is highly valued as we are navigating integrating Nx deeper in our monorepo.

> Package Based Repos are not being phased out. However, they interact differently with Nx Plugins and that's something to be carefully considered before choosing a Package Based Repo. You can still use an Integrated Repo and publish packages. Just an FYI.

The thing we were looking for is "isolating frontend apps from breaking each other when updating deps"  and "smaller, more focused package.json files". However, we ripped out the "package based" setup and use an "integrated repo" setup and everyone shares the dep versions.

> This means you can use @nrwl/angular@15.7.0 with Angular 14 and 15. These are currently the only two versions that we can guarantee support for.

That's understandable and logical, but likely wouldn't have helped us in the scenario that 2 frontend app projects had diverging versions of Angular (which one would `@nrwl/angular` use to compile the library project?). We ended up downgrading the newer project to match the older project, and converting to an integrated repo.

> Your packages should then be able to define the version of Angular + Angular Devkit they depend on within their own package.json files.

I'm not sure I follow this - won't one angular be hoisted higher than the other in a package based monorepo, therefore it being up to the `require()` implementation to determine which is loaded? Based on current workdir if I remember correctly?

**Comment by boxmein** [comment] 2023-03-21 10:04
> If it doesn't, please let me know. We may need to do additional work to support Yarn Workspaces with Multiple Angular Support

Our project is already on integrated mode, but likely it is still a bug:

* If you have a yarn workspaces based monorepo, you can use a different version of Angular for each application project
* Yarn will likely hoist one version of Angular to the "root node_modules" 
* If `@nrwl/angular` is also hoisted to "root node_modules", then it will likely load the hoisted version of Angular (because of the way `require()` works)
* Wouldn't `@nrwl/angular` always load the hoisted version of Angular, not the version that corresponds to the application project?
