### ISSUE TITLE
Lib with collection of styled-components work with console errors in next.js app. Related to babel config

### ISSUE THREAD

**Issue by dsm23** [nrwl/nx#2573] opened 2020-02-27 17:07 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behaviour

I would expect the styled-components library to adopt the same babel config as the next.js application. Especially since the ssr option prevents the issue where className may change between server and client.

https://codesandbox.io/s/next-styled-components-working-y7r68

## Current Behaviour

It is very noticeable that the classNames of the rendered components in dev mode do not include their file names and their display names

https://github.com/mcastro84/styled-components-issue

## Failure Information (for bugs)

Often (admittedly, not all browser refreshes) will produce a console error

```
Warning: Prop `className` did not match. Server: "someClassName" Client: "someOtherClassName"
```

### Steps to Reproduce

https://github.com/mcastro84/styled-components-issue

```
yarn start
```

### Context

Please provide any relevant information about your setup:

We have multiple next.js apps in the nx monorepo and would like to share components between the two. We started off with styled-components before adopting next.js apps so we have a lot of legacy components that we would like to use

As you can see, I have implemented the code from the styled-components next.js example so that is not the issue: https://github.com/zeit/next.js/tree/canary/examples/with-styled-components

**Comment by paulius1990** [comment] 2020-10-14 05:51
@vsavkin @jdpearce @dsm23 I have the same issue on my dev environment. Does this issue solved?

**Comment by atligudl** [comment] 2020-12-07 12:14
Running into this issue as well, has anyone found a solution?

**Comment by Epenance** [comment] 2021-02-19 09:21
Still haven't found a solution to this issue :(

Currently preventing me from starting a new project using Nx

**Comment by LuckeeDev** [comment] 2021-02-21 17:07
Had the same issue and after investigating for a bit it turned out it was a problem in my Babel configuration.
By default, after bootstrapping an nx workspace with nextjs and styled-components, the `.babelrc` looks like this:
```json
"plugins": [
    ["styled-components", { "pure": true, "ssr": true }]
]
```
But it should look like this to make it work properly:
```json
"plugins": [
    ["babel-plugin-styled-components", { "pure": true, "ssr": true }]
]
```

Seems like there's an error in the way the nx cli bootstraps the project. Thoughts on this?

_Originally posted by @LuckeeDev in https://github.com/nrwl/nx/issues/4573#issuecomment-782889860_

**Comment by funwhilelost** [comment] 2021-03-01 02:16
Also causing me a lot of headaches.  The styled-components work fine with either `style-components` or `babel-plugin-styled-components` in the `.babelrc` file of both the application and the offending library when you first start the server.  I can also refresh from this state many times with no warnings and no issues.

It seems to be introduced for me _once there is a hot reload of any part of the app_.  The console shows `hot-dev-client.js` says:
```
[Fast Refresh] rebuilding
[Fast Refresh] done
```

If any part of the app hot reloads then a browser refresh will have broken styles and the console error.  If you change the page contents and cause a hot reload the the page component then the styles will stay broken on the shared component.  But if you change the styles on an individual styled-component then its styles seem to be reloaded fine.

Hopefully that's a couple more angles on the problem.  It seems like the hot module reloading really needs to do the whole `_document` file again, to get all the new styled-components classNames app-wide.

**Comment by jaysoo** [comment] 2021-03-03 17:30
A workaround is outlined here: https://github.com/nrwl/nx/issues/4611#issuecomment-788990096

The issue is that the root `babel.config.json` and additional `babelrc` files aren't being picked up. This will be fixed in the next version, but you can use the workaround above for now.

**Comment by funwhilelost** [comment] 2021-03-04 02:06
Thanks @jaysoo - I was able to update the `babel.config.json` file, then add the preset to my `.babelrc` files in the libraries, then update the `next.config.js` file.  Unfortunately setting the "rootMode" property to 'upward' causes a compile-time error:

```
Module parse failed: Unexpected token (12:9)
File was processed with these loaders:
 * ../../node_modules/next/node_modules/@next/react-refresh-utils/loader.js
 * ../../node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
| _c = StyledFooter;
| export function Footer(props) {
>   return <StyledFooter>
|       <Wrapper>
|         <h1>Welcome to Footer!</h1>
```

next.config.js:
```
// eslint-disable-next-line @typescript-eslint/no-var-requires
const withNx = require('@nrwl/next/plugins/with-nx');

module.exports = withNx({
  webpack: (config, { defaultLoaders }) => {
    defaultLoaders.babel.options.babelrc = true;
    defaultLoaders.babel.options.rootMode = 'upward';
    return config;
  },
});
```

.babelrc
```
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true, "displayName": true, "preprocess": false }]]
}
```

**Comment by jaysoo** [comment] 2021-03-08 20:14
@funwhilelost Yeah it'll load the root babel config and the app's babelrc file, as well as any other babelrc belonging to libs. Each library is supposed to provide their own babelrc that is separate from the app's.

**Comment by jaysoo** [comment] 2021-03-08 20:30
Here's an example of the workaround
 https://github.com/jaysoo/acme-next

**Closed** 2021-03-10 13:36 UTC
Labels: scope: nextjs, type: bug
