### ISSUE TITLE
ESLint treats imported functions/types as 'any' despite valid type definitions

### ISSUE THREAD

**Issue by lucas-barake** [nrwl/nx#22620] opened 2024-04-02 14:53 UTC
### Current Behavior

When importing a library, such as React, and using its functions or types, ESLint raises several type-safety related warnings. For example, if I import React and use the `useState` hook like this:

```tsx
import React from "react";

const [value, setValue] = React.useState<string>("");
```

ESLint reports the following errors:

- "Unsafe assignment of an `any` value." (@typescript-eslint/no-unsafe-assignment)
- "Unsafe call of an `any` typed value." (@typescript-eslint/no-unsafe-call)
- "Unsafe member access .useState on an `any` value." (@typescript-eslint/no-unsafe-member-access)

These warnings occur not only for React, but for other shared libraries as well, when importing and using their types or functions.

### Expected Behavior

When importing a library and using its functions or types, ESLint should correctly recognize and infer the types of the imported elements based on the library's type definitions. It should not raise type-safety related warnings if the usage of the imported elements is correct according to the library's types.

### Steps to Reproduce

1. I have this root `.eslintrc.json` file:

```json
{
 "root": true,
 "ignorePatterns": ["**/*"],
 "plugins": ["@nx"],
 "overrides": [
   {
     "files": ["*.js", "*.jsx"],
     "rules": {
       // ...
     }
   },
   {
     "files": ["*.ts", "*.tsx"],
     "extends": [
       "plugin:@nx/typescript",
       "plugin:@typescript-eslint/recommended-type-checked",
       "plugin:@typescript-eslint/stylistic-type-checked",
       "plugin:react/recommended",
       "plugin:react-hooks/recommended"
     ],
     "settings": {
       "react": {
         "version": "detect"
       }
     },
     "parserOptions": {
       "project": "./tsconfig.base.json"
     },
     "plugins": ["@typescript-eslint", "eslint-plugin-react", "import", "jsx-a11y"],
     "rules": {
       // ...
     }
   }
 ]
}
```

2. This is my `tsconfig.base.json` file:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "allowJs": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "noPropertyAccessFromIndexSignature": false,
    "strictNullChecks": true,
    "baseUrl": ".",
    "paths": {
      "@sainapsis/api-client": ["libs/api-client/src/index.ts"],
      "@sainapsis/aws-amplify": ["libs/aws-amplify/src/index.ts"],
      "@sainapsis/gql": ["libs/gql/src/index.ts"],
      "@sainapsis/gql-generated": ["libs/gql-generated/src/index.ts"],
      "@sainapsis/web-components": ["libs/web-components/src/index.ts"],
      "@sainapsis/zustand-stores": ["libs/zustand-stores/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

3. My apps just extend the base `.eslintrc.json` file:

```json
{
  "extends": ["plugin:@nx/react", "../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}
```

This is the `tsconfig.json` file for one of my apps:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "strict": true,
    "types": ["vite/client", "vitest"]
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "extends": "../../tsconfig.base.json"
}
```

4. These are my installed ESLint dependencies:

```json
    "@typescript-eslint/eslint-plugin": "7.5.0",
    "@typescript-eslint/parser": "7.5.0",
    "typescript": "^5.4.3",
    "@nx/eslint": "18.2.1",
    "@nx/eslint-plugin": "18.2.1",
    "@typescript-eslint/eslint-plugin": "7.5.0",
    "@typescript-eslint/parser": "7.5.0",
    "eslint": "8.57.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-import": "2.27.5",
    "eslint-plugin-jsx-a11y": "6.7.1",
    "eslint-plugin-react": "7.32.2",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-tailwindcss": "^3.15.1",
```

### Nx Report

```shell
Node   : 20.11.1
OS     : linux-x64
yarn   : 4.1.1

nx (global)        : 18.0.8
nx                 : 18.2.1
@nx/js             : 18.2.1
@nx/jest           : 18.2.1
@nx/linter         : 18.2.1
@nx/eslint         : 18.2.1
@nx/workspace      : 18.2.1
@nx/detox          : 18.2.1
@nx/devkit         : 18.2.1
@nx/eslint-plugin  : 18.2.1
@nx/expo           : 18.2.1
@nx/react          : 18.2.1
@nrwl/tao          : 18.2.1
@nx/vite           : 18.2.1
@nx/web            : 18.2.1
@nx/webpack        : 18.2.1
typescript         : 5.4.3
```

### Failure Logs

```shell
Linting "web-chat"...

/home/lucas/src/lucas-sainapsis/sainapsis-monorepo/apps/web-chat/src/features/chat-page/sidebar/chat-list/chat-list.tsx
   8:9   warning  Unsafe assignment of an `any` value                                     @typescript-eslint/no-unsafe-assignment
   8:43  warning  Unsafe call of an `any` typed value                                     @typescript-eslint/no-unsafe-call
   8:49  warning  Unsafe member access .useState on an `any` value                        @typescript-eslint/no-unsafe-member-access
  19:72  warning  Unsafe argument of type `any` assigned to a parameter of type `string`  @typescript-eslint/no-unsafe-argument
  26:11  warning  Unsafe call of an `any` typed value                                     @typescript-eslint/no-unsafe-call

/home/lucas/src/lucas-sainapsis/sainapsis-monorepo/apps/web-chat/src/features/chat-page/sidebar/chat-list/chat-row/chat-row.tsx
  11:9   warning  Unsafe assignment of an `any` value                                     @typescript-eslint/no-unsafe-assignment
  11:23  warning  Unsafe call of an `any` typed value                                     @typescript-eslint/no-unsafe-call
  11:28  warning  Unsafe member access .Messages on an `any` value                        @typescript-eslint/no-unsafe-member-access
  12:34  warning  Unsafe member access .endUserReadTimestamp on an `any` value            @typescript-eslint/no-unsafe-member-access
  34:27  warning  Unsafe call of an `any` typed value                                     @typescript-eslint/no-unsafe-call
  34:32  warning  Unsafe member access .EndUser on an `any` value                         @typescript-eslint/no-unsafe-member-access
  39:55  warning  Unsafe member access .EndUser on an `any` value                         @typescript-eslint/no-unsafe-member-access
  42:49  warning  Unsafe argument of type `any` assigned to a parameter of type `string`  @typescript-eslint/no-unsafe-argument
  42:61  warning  Unsafe member access .createdAt on an `any` value                       @typescript-eslint/no-unsafe-member-access
  48:89  warning  Unsafe member access .message on an `any` value                         @typescript-eslint/no-unsafe-member-access

/home/lucas/src/lucas-sainapsis/sainapsis-monorepo/apps/web-chat/src/features/chat-page/sidebar/chat-list/chat-search/chat-search.tsx
  26:13  warning  Unsafe call of an `any` typed value  @typescript-eslint/no-unsafe-call

/home/lucas/src/lucas-sainapsis/sainapsis-monorepo/apps/web-chat/src/lib/components/layouts/session-loader-spinner/session-loader-spinner.tsx
  24:3  warning  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return

/home/lucas/src/lucas-sainapsis/sainapsis-monorepo/apps/web-chat/src/lib/components/misc/update-session.tsx
  11:9   warning  Unsafe assignment of an `any` value                @typescript-eslint/no-unsafe-assignment
  11:23  warning  Unsafe call of an `any` typed value                @typescript-eslint/no-unsafe-call
  11:29  warning  Unsafe member access .useRef on an `any` value     @typescript-eslint/no-unsafe-member-access
  13:3   warning  Unsafe call of an `any` typed value                @typescript-eslint/no-unsafe-call
  13:9   warning  Unsafe member access .useEffect on an `any` value  @typescript-eslint/no-unsafe-member-access
  15:22  warning  Unsafe member access .current on an `any` value    @typescript-eslint/no-unsafe-member-access
  16:19  warning  Unsafe member access .current on an `any` value    @typescript-eslint/no-unsafe-member-access

✖ 24 problems (0 errors, 24 warnings)
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by fahslaj** [comment] 2024-04-04 15:43
Hi @lucas-barake , it looks like this is caused by the inclusion of `plugin:@typescript-eslint/recommended-type-checked` from the `@typescript-eslint` plugin. I would suggest instead extending Nx-provided configurations [outlined in the docs here](https://nx.dev/nx-api/eslint-plugin/documents/overview).

**Comment by lucas-barake** [comment] 2024-04-04 17:12
Hey @fahslaj, thanks for the prompt response!

I removed the `@typescript-eslint` extended plugins and replaced them with the Nx-provided ones as you recommended. Unfortunately, the issue still persists.

I created a minimal reproduction of the issue in a separate repository: https://github.com/lucas-barake/nx-eslint-bug

![image](https://github.com/nrwl/nx/assets/86905052/0e264ec9-f14f-4a6a-a043-2a442cd3b500)

Please let me know if you notice anything I might be doing wrong or if you need any additional information. Thanks again for your help!

**Comment by meeroslav** [comment] 2024-04-05 08:11
Hi @lucas-barake,

Thank you for reporting this.

The issue you are experiencing is not coming from Nx but rather a result of your ESlint configuration. If you run plain `eslint .` in your app, you will get the same errors.

The preferred way to import react functions is using named imports:
```JS
// This works fine as it imports functions directly
import { useState } from 'react'; 

// This imports everything and uses TS namespace to get types - `@typescript/eslint` will complain
import React from 'react'; complain
```

This is the trio in your `.eslintrc.json` that is throwing those errors:
```JSON
        "@typescript-eslint/no-unsafe-assignment": "error",
        "@typescript-eslint/no-unsafe-member-access": "error",
        "@typescript-eslint/no-unsafe-call": "error"
 ```

I recommend opening this issue on the `@typescript-eslint` side since the `getConstrainedTypeAtLocation` all these are using is returning `any` when parsing `React`, which is incorrect.

I will close this issue as it should be solved elsewhere.

cc @JamesHenry

**Closed by meeroslav** 2024-04-05 08:11 UTC
Labels: type: bug, blocked: third-party, scope: linter
