### ISSUE TITLE
VSCode Reports "Problems" in default NX Angular project

### ISSUE THREAD

**Issue by gavindoughtie** [nrwl/nx#2669] opened 2020-03-15 16:09 UTC
I'm running the latest NX, VSCode 1.43.0 on OSX 10.15.3

## Expected Behavior

No problems reported with default config in IDE

## Current Behavior

In the "Problems" pane of the IDE I see:

```
app.spec.ts

  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    apps/bug-demo-e2e/src/integration/app.spec.ts:4:20 - error TS2304: Cannot find name 'cy'.

    4   beforeEach(() => cy.visit('/'));
                         ~~
    apps/bug-demo-e2e/src/integration/app.spec.ts:8:5 - error TS2304: Cannot find name 'cy'.

    8     cy.login('my-email@something.com', 'myPassword');
          ~~
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    apps/bug-demo-e2e/src/integration/app.spec.ts:4:20 - error TS2304: Cannot find name 'cy'.

    4   beforeEach(() => cy.visit('/'));
                         ~~
    apps/bug-demo-e2e/src/integration/app.spec.ts:8:5 - error TS2304: Cannot find name 'cy'.

    8     cy.login('my-email@something.com', 'myPassword');
          ~~

app.component.spec.ts

Error: Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js"
(repeated 3 times)
```

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce
Starting with a default NX workspace

```
npx create-nx-workspace@latest myworkspace

? What to create in the new workspace angular           [a workspace with a single Angular application]
? Application name                    bug-demo
? Default stylesheet format           CSS

~/Projects/ $ cd myworkspace/
~/Projects/myworkspace (master) $ code .
```

Look at the "Problems" pane in VSCode

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context

Please provide any relevant information about your setup:

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : 9.1.2
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5

My globally-installed TypeScript is 3.8.3

```
$ nx run bug-demo:test
> ng run bug-demo:test
 PASS  apps/bug-demo/src/app/app.component.spec.ts
  AppComponent
    ✓ should create the app (82ms)
    ✓ should have as title 'bug-demo' (46ms)
    ✓ should render title (24ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        2.377s
Ran all test suites.
gavin@MacC02WC1L9G8WL ~/Projects/myworkspace (master) $ nx run bug-demo-e2e:e2e
> ng run bug-demo-e2e:e2e

chunk {main} main.js, main.js.map (main) 24.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.7 MB [initial] [rendered]
Date: 2020-03-15T16:08:35.231Z - Hash: e7a4b972cd810b8d4863 - Time: 3732ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.1.0                                                                              │
  │ Browser:    Electron 78                                                                        │
  │ Specs:      1 found (app.spec.ts)                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  app.spec.ts                                                                     (1 of 1)

Warning: Cypress can only record videos of Electron when running headlessly.

You have set the Electron browser to run headed.

A video will not be recorded when using this mode.
Starting type checking service...
Using 1 worker with 2048MB memory limit
Starting type checking service...
Using 1 worker with 2048MB memory limit


  bug-demo
    ✓ should display welcome message (491ms)


  1 passing (514ms)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     app.spec.ts                                                                      │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  app.spec.ts                              511ms        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        511ms        1        1        -        -        -

```

And tests all run correctly from the NX VSCode plugin as well.

**Comment by gavindoughtie** [comment] 2020-03-15 21:15
Follow-on; this appears to be related to configuring https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest; disabling that extension entirely removes the problems display.

**Comment by vsavkin** [comment] 2020-03-16 14:08
Thank you for reporting this issue.

tsconfig.json files list all the globals available in the corresponding projects. If the vscode extension doesn't use the proper tsconfig (for instance it only use the root one), you might see issues like that. Not much we could do on our side. 

You could add the cypress types to the global tsconfig. This will likely resolve the editor errors you are seeing, but it's not ideal and might result in other issues.

I'm going to close this issue because it looks like the problem is with the extension.

**Closed by vsavkin** 2020-03-16 14:08 UTC
