### ISSUE TITLE
Failure when running storybook configuration for a react library

### ISSUE THREAD

**Issue by bleakcon** [nrwl/nx#4854] opened 2021-02-21 17:56 UTC
## Current Behavior
- When running: nx generate storybook-configuration app-menu on windows 10 I get a stack trace:
- stack trace appears, detailed in failure log

## Expected Behavior
I expect to have a storybook configured for that library

## Steps to Reproduce
run nx generate storybook-configuration app-menu in windows 10 
stack trace appears as shown below, looks to be a missing file?

### Failure Logs

Error: Cannot find module '@nrwl/workspace/src/utilities/run-tasks-in-serial'
Require stack:
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\storybook\src\generators\configuration\configuration.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\src\commands\generate.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\index.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\cli\lib\init-local.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\cli\bin\nx.js
- C:\Users\bamsl\AppData\Roaming\npm\node_modules\nx\node_modules\@nrwl\cli\bin\nx.js
- C:\Users\bamsl\AppData\Roaming\npm\node_modules\nx\bin\nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.require (C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at Module.require (C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\storybook\node_modules\@nrwl\tao\src\compat\compat.js:7:40)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\storybook\src\generators\configuration\configuration.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\storybook\\src\\generators\\configuration\\configuration.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@angular-devkit\\schematics\\tools\\export-ref.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@angular-devkit\\schematics\\tools\\index.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\tao\\src\\commands\\ngcli-adapter.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\tao\\src\\commands\\generate.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\tao\\index.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\cli\\lib\\init-local.js',
    'C:\\Users\\bamsl\\workspace\\ts\\bleakcon\\node_modules\\@nrwl\\cli\\bin\\nx.js',
    'C:\\Users\\bamsl\\AppData\\Roaming\\npm\\node_modules\\nx\\node_modules\\@nrwl\\cli\\bin\\nx.js',
    'C:\\Users\\bamsl\\AppData\\Roaming\\npm\\node_modules\\nx\\bin\\nx.js'
  ]
}
Cannot find module '@nrwl/workspace/src/utilities/run-tasks-in-serial'
Require stack:
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\storybook\src\generators\configuration\configuration.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\src\commands\ngcli-adapter.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\src\commands\generate.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\tao\index.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\cli\lib\init-local.js
- C:\Users\bamsl\workspace\ts\bleakcon\node_modules\@nrwl\cli\bin\nx.js
- C:\Users\bamsl\AppData\Roaming\npm\node_modules\nx\node_modules\@nrwl\cli\bin\nx.js
- C:\Users\bamsl\AppData\Roaming\npm\node_modules\nx\bin\nx.js

### Environment

  Node : 14.15.4
  OS   : win32 x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.12
  @nrwl/cypress : 11.2.12
  @nrwl/devkit : 11.2.12
  @nrwl/eslint-plugin-nx : 11.2.12
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.12
  @nrwl/linter : 11.2.12
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.12
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.12
  @nrwl/web : 11.2.12
  @nrwl/workspace : 11.2.7
  typescript : 4.0.7

**Comment by ThomasGHenry** [comment] 2021-02-22 11:59
similar error on macos 10.15 running ` nx generate @nrwl/gatsby:application name`

**Comment by ccarstens** [comment] 2021-02-22 14:31
similar error on macOS 10.15 running `nx g @nrwl/react:application name`

**Comment by peb7268** [comment] 2021-02-22 19:40
Same issue, Angular on Mac 10.15.7.
Angular CLI: 11.0.7

**Comment by FrozenPandaz** [comment] 2021-02-22 20:03
> @nrwl/react : 11.2.12
@nrwl/web : 11.2.12
@nrwl/workspace : 11.2.7

This is caused by misaligned versions of `@nrwl/react` and `@nrwl/workspace`. Please align the versions and the issue should be fixed. I'll add a dependency so that this isn't an issue in the future.

**Comment by bleakcon** [comment] 2021-02-22 20:22
@FrozenPandaz thankyou for your response, it seems like you also must keep the storybook install aligned as well, it appears, if you run the yarn command in your documentation it looks to install ^11.3.1 of "@nrwl/storybook" when I needed 11.2.12 for it to work.

Thank you for the solution

**Closed** 2021-02-22 20:32 UTC
Labels: scope: storybook, type: bug
