### ISSUE TITLE
Can libs reference scripts?

### ISSUE THREAD

**Issue by Nxt3** [nrwl/nx#600] opened 2018-06-22 18:55 UTC

**Comment by thelgevold** [comment] 2018-06-25 12:17
Hi. Can you please include more details about what you are trying to do?

**Comment by thelgevold** [comment] 2018-06-25 12:19
Closing as this is a duplicate of https://github.com/nrwl/nx/issues/601

**Closed by thelgevold** 2018-06-25 12:19 UTC
Labels: blocked: more info needed

**Comment by Nxt3** [comment] 2018-06-25 13:30
In Angular 5, you could do this in `.angular-cli.json`:

```
    {
      "name": "logger-lib",
      "root": "libs/logger-lib/src",
      "test": "../../../test.ts",
      "scripts": ["../../../node_modules/js-logger/src/logger.min.js"],
      "tsconfig": "tsconfig.app.json",
      "tags": []
    }
```

but there doesn't seem to be an equivalent now--unless I'm missing something.
