### ISSUE TITLE
[storybook] no .stories generated?

### ISSUE THREAD

**Issue by EvtK** [nrwl/nx#2121] opened 2019-11-30 18:51 UTC
## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior
Running:
```
 npm run nx g @nrwl/angular:storybook-configuration shared-components
```

or 

```
ng g stories shared-components
```
should generate .stories files for my (ui)-components.

What is the current behavior?

When running the first command: no stories are generated and when running the second command afterwards I receive:

```
Nothing to be done.
```

### Context

- I'm running the latest NX (8.8.3) nothin fancy here.
- Library contains simple ui-components, but styling or styleUrls is included (don't know if that may play a part)

**Comment by isaacplmann** [comment] 2019-12-02 17:09
What `*.module.ts` files are in the root level of that library?  The stories schematic is currently dumbly taking the first `*.module.ts` file it finds and looking for a `declarations` array on it.

I'd like to add an optional parameter to specify the module file manually.

**Comment by EvtK** [comment] 2019-12-04 08:07
ahhh that explains. We don't work with root modules, but instead libraries export multiple modules.

I suppose a search for any .module.ts file in the lib should be the way to have this fixed.

**Comment by tommyc38** [comment] 2020-01-21 07:55
I fixed this by simply adding `declarations: []` to my lib module that doesn't have any declarations.

**Comment by FrozenPandaz** [comment] 2020-03-27 17:47
Closing as I believe this issue is fixed with #2583. Please reopen this issue if this is not the case.

**Closed by FrozenPandaz** 2020-03-27 17:47 UTC
Labels: scope: storybook, type: bug

**Comment by EvtK** [comment] 2020-03-29 09:51
Yeah I haven't found time to try the StoryBook implementation for our NX Repo once more. I guess it will be fixed, will report back if I stumble upon this issue again.

**Comment by danielquintero** [comment] 2020-04-03 15:27
![Screen Shot 2020-04-03 at 17 24 00](https://user-images.githubusercontent.com/4777384/78377592-1558a600-75d0-11ea-816d-018521412e78.png)

I can confirm this is not working (no `.stories` files created), we have a root level `.module.ts` that looks like:
```
	declarations: [
		SidebarComponent,
		SidebarSecondaryComponent,
		NotificationsComponent,
		SearchInputComponent,
		ModalComponent,
		HeaderComponent
	],

```
just migrated workspace to latest 9.2.1 successfully
