### ISSUE TITLE
Server Side Rendering Error

### ISSUE THREAD

**Issue by shanieMoonlight** [nrwl/nx#17704] opened 2023-06-21 12:31 UTC
### Current Behavior

I've set up Server Side Rendering using the procedure described here: https://nx.dev/packages/angular/generators/setup-ssr.
Everything seems to be set up properly and the code compiles .

_Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200/, open your browser on http://localhost:4200/ **
Angular is running in development mode._

When I open it in the browser I get a TypeError (document.documentElement.setAttribute is not a function).
The browser just shows a print out of the stacktrace.

This happens with all my applications.
I have generated new applications (using generate -> application ) and added nothing else to make sure it wasn't any of my library code causing the error, but the error still occurs.

I have created a brand new workspace and it seems to work, so it's probably due to something in this workspace but I don't know what. 
It would take me a long time to recreate it with all the libs and secondary entry points, so I'm hoping there is some way around it.

### Expected Behavior

I expected the app to prerendered and served.

### Steps to Reproduce

1. Set up SSR for a project.
2. Serve the project in Development mode (nx run ssr-test:serve-ssr:development)
3. Open the browser at http://localhost:4200/

### Nx Report

```shell
TypeError: document.documentElement.setAttribute is not a function
at createDocument (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:517:30)
at (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:1119:22)
at Generator.next ()
at asyncGeneratorStep (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
at _next (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:22:1)
at executor (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:1)
at ZoneAwarePromise (./node_modules/zone.js/dist/zone-node.js:1268:25)
at (./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:19:1)
at process (./node_modules/@nguniversal/common/node_modules/critters/dist/critters.mjs:1143:19)
at (./node_modules/@nguniversal/common/fesm2022/tools.mjs:138:40)
Angular is running in development mode.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-06-21 13:11
Thanks for reporting this!

Unfortunately, we need a way to reproduce this so we can help. As you mentioned, it can't be reproduced with new workspaces, so we can't see what's wrong and could be related to your specific setup/environment. Please provide a repo where the issue can be reproduced or at least some detailed reproduction steps so we can troubleshoot the issue.

**Comment by KeithGillette** [comment] 2023-06-22 00:47
This may be unrelated, but upon updating an `nx@16.1.4`† workspace  to Angular `16.1.2`, `nx build` fails for the Angular project target with the same `document.documentElement.setAttribute is not a function` (`✖ Index html generation failed`). The `nx build` succeeds with Angular `16.0.6` and earlier.

†We are stuck at `nx@16.1.4` due to issue #17070.

**Comment by leosvelperez** [comment] 2023-06-22 11:20
@KeithGillette Angular 16.1 is still not officially supported by Nx so issues can be expected. We're adding support for it on https://github.com/nrwl/nx/pull/17155 which has taken longer than expected due to Cypress not supporting Angular 16.1.

**Comment by leosvelperez** [comment] 2023-06-30 09:39
@shanieMoonlight this seems to be an issue with a transitive dependency from the `@angular-devkit/build-angular` package https://github.com/angular/angular-cli/issues/25419.

Looking through the comments in that issue, it seems to be caused by conflicting versions of the `domhandler` package being installed. In Angular 16.1.0, the `critters` package was updated to a newer version that depends on that package. This comment https://github.com/angular/angular-cli/issues/25419#issuecomment-1604383624 mentions a workaround you can try.

I'm closing this issue since it's not caused by Nx. Please follow the linked issue in the Angular CLI repo for updates.

**Closed by leosvelperez** 2023-06-30 09:39 UTC
Labels: type: bug, blocked: repro needed, scope: angular

**Comment by shanieMoonlight** [comment] 2023-07-02 11:10
Ok, I'll check it out. 
Thanks.

**Comment by EliotBrown** [comment] 2023-07-12 07:48
> @shanieMoonlight this seems to be an issue with a transitive dependency from the `@angular-devkit/build-angular` package [angular/angular-cli#25419](https://github.com/angular/angular-cli/issues/25419).
> 
> Looking through the comments in that issue, it seems to be caused by conflicting versions of the `domhandler` package being installed. In `@angular-devkit/build-angular@16.1.0`, the `critters` dependency was updated to a newer version that depends on that package. This comment [angular/angular-cli#25419 (comment)](https://github.com/angular/angular-cli/issues/25419#issuecomment-1604383624) mentions a workaround you can try.
> 
> I'm closing this issue since it's not caused by Nx. Please follow the linked issue in the Angular CLI repo for updates.

Thanks! I had the same issue, installing domhandler separately fixed the problem.
