### ISSUE TITLE
Jest tests fail after upgrading v12 => v13 (Cannot use import statement outside a module)

### ISSUE THREAD

**Issue by oco2000** [nrwl/nx#7895] opened 2021-11-26 08:32 UTC
## Current Behavior
Jest tests fail, all the tests fail with the same error.

## Expected Behavior
Jest tests pass

## Steps to Reproduce
Upgrade the existing project using standard migration procedure

### Failure Logs
```
FAIL shared-data-access-data-access-core libs/shared/data-access/data-access-core/src/lib/scheduler/scheduler-core.facade.spec.ts
  ? Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
    By default "node_modules" folder is ignored by transformers.
    Here's what you can do:
     � If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     � If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     � To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     � If you need a custom transformation specify a "transform" option in your config.
     � If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation
    Details:
    /build/node_modules/@angular/core/fesm2015/testing.mjs:7
    import * as i0 from '@angular/core';
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module
      at Runtime.createScriptFromCode (../../../../../../../../build/node_modules/jest-runtime/build/index.js:1728:14)
```

### Environment
```  Node : 14.17.0
  OS   : win32 x64
  yarn : 1.22.17

  nx : 13.2.2
  @nrwl/angular : 13.2.2
  @nrwl/cli : 13.2.2
  @nrwl/cypress : 13.2.2
  @nrwl/devkit : 13.2.2
  @nrwl/eslint-plugin-nx : 13.2.2
  @nrwl/express : 13.2.2
  @nrwl/jest : 13.2.2
  @nrwl/linter : 13.2.2
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.2.2
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.2
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.2
  @nrwl/storybook : 13.2.2
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.6.6
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.0
         @angular/cdk: 13.0.0
         @angular/cli: 13.0.3
         @angular/common: 13.0.0
         @angular/compiler: 13.0.0
         @angular/core: 13.0.0
         @angular/elements: 13.0.0
         @angular/forms: 13.0.0
         @angular/material: 13.0.0
         @angular/platform-browser: 13.0.0
         @angular/platform-browser-dynamic: 13.0.0
         @angular/router: 13.0.0
         @angular/service-worker: 13.0.0
         @ionic/angular: 5.9.1
         @ngneat/reactive-forms: 1.7.5
         @ngneat/transloco: 2.23.5
         @ngrx/component-store: 13.0.1
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @angular-builders/custom-webpack: 12.1.3
         @angular-devkit/build-angular: 13.0.3
         @angular/compiler-cli: 13.0.0
         @angular/language-service: 13.0.0
         @ngneat/spectator: 8.3.2
         @ngrx/schematics: 13.0.1
         @ngrx/store-devtools: 13.0.1
         @nxext/stencil: 12.1.2
         @nxtend/capacitor: 11.1.1
         @nxtend/ionic-angular: 11.1.1
         @storybook/angular: 6.4.0-rc.3
         ng-mocks: 12.5.0
         nx-stylelint: 12.3.1
```

**Comment by leosvelperez** [comment] 2021-11-26 09:44
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/7844. I'll close this one in favor of that one. Please follow it for updates.

**Closed by leosvelperez** 2021-11-26 09:44 UTC
Labels: type: bug
