### ISSUE TITLE
 Can't host on AWS Amplify, can't locate @myproject/components lib

### ISSUE THREAD

**Issue by reeslabree** [nrwl/nx#11666] opened 2022-08-22 14:11 UTC
## Current Behavior
`nx run myProject:build --prod` fails with error when deploying remotely with AWS Amplify

## Expected Behavior
Should compile my NextJS app successfully.

## Steps to Reproduce
_Note_ Running `nx run puppy-client:build --prod` works fine on my machine, as well as `nx build puppy-client --prod`, `nx run puppy-client:build:production`.

AWS Amplify > Host Web App > Edit Build File
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 16.13.2
        - npm i -g nx
        - pwd
        - yarn install
    build:
      commands:
        - nx run puppy-client:build --prod --verbose
  artifacts:
    baseDirectory: dist/apps/puppy-client/.next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Failure Logs
```
NX_VERBOSE_LOGGING=true to see the error.
2022-08-22T13:48:17.049Z [INFO]: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2022-08-22T13:48:17.062Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-08-22T13:48:17.062Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2022-08-22T13:48:17.096Z [INFO]: info  - Checking validity of types...
2022-08-22T13:48:21.149Z [WARNING]: Failed to compile.
2022-08-22T13:48:21.150Z [WARNING]: ./pages/_app.tsx:10:3
                                    Type error: Module '"@puppy/components"' has no exported member 'Navbar'.
                                    [0m [90m  8 | [39m[36mimport[39m [32m'./styles.css'[39m[33m;[39m[0m
                                    [0m [90m  9 | [39m[36mimport[39m { [0m
                                    [0m[31m[1m>[22m[39m[90m 10 | [39m  [33mNavbar[39m[33m,[39m[0m
                                    [0m [90m    | [39m  [31m[1m^[22m[39m[0m
                                    [0m [90m 11 | [39m  [33mNavbarProps[39m[33m,[39m [0m
                                    [0m [90m 12 | [39m  [33mFooter[39m [0m
                                    [0m [90m 13 | [39m} from [32m'@puppy/components'[39m [0m
2022-08-22T13:48:21.168Z [INFO]: 
2022-08-22T13:48:21.169Z [INFO]: 
                                 >  NX   Running target "puppy-client:build" failed
                                 Failed tasks:
                                 
                                 - puppy-client:build:production
                                 
                                 Hint: run the command with --verbose for more details.
2022-08-22T13:48:21.188Z [ERROR]: !!! Build failed
2022-08-22T13:48:21.188Z [ERROR]: !!! Non-Zero Exit Code detected
2022-08-22T13:48:21.188Z [INFO]: # Starting environment caching...
2022-08-22T13:48:21.188Z [INFO]: # Environment caching completed
```

### Environment
```
>  NX   Report complete - copy this into the issue template
                               Node : 16.13.2
                               OS   : linux x64
                               yarn : 1.22.0
                               
                               nx : 14.4.3
                               @nrwl/angular : Not Found
                               @nrwl/cypress : 14.4.3
                               @nrwl/detox : Not Found
                               @nrwl/devkit : 14.4.3
                               @nrwl/eslint-plugin-nx : 14.4.3
                               @nrwl/express : Not Found
                               @nrwl/jest : 14.4.3
                               @nrwl/js : 14.4.3
                               @nrwl/linter : 14.4.3
                               @nrwl/nest : 14.5.2
                               @nrwl/next : 14.4.3
                               @nrwl/node : 14.5.1
                               @nrwl/nx-cloud : Not Found
                               @nrwl/nx-plugin : Not Found
                               @nrwl/react : 14.4.3
                               @nrwl/react-native : Not Found
                               @nrwl/schematics : Not Found
                               @nrwl/storybook : 14.4.3
                               @nrwl/web : 14.4.3
                               @nrwl/workspace : 14.4.3
                               typescript : 4.7.4
```

**Comment by jaysoo** [comment] 2022-08-24 15:38
I think the issue is on Amplify's end, but there seems to be some workarounds.

https://github.com/aws-amplify/amplify-hosting/issues/2377#issuecomment-1087398969

**Comment by reeslabree** [comment] 2022-08-24 15:43
> I think the issue is on Amplify's end, but there seems to be some workarounds.
> 
> [aws-amplify/amplify-hosting#2377 (comment)](https://github.com/aws-amplify/amplify-hosting/issues/2377#issuecomment-1087398969)

Hi jaysoo, apologies, I heard back from support at AWS and they said they have this same ticket in their backlog. Sounds like the big issue is that Amplify can't figure out how to host something if the build directory is outside of the app directory (among other things including apps not having their own `package.json`.

Would you like me to close this issue?

**Comment by jaysoo** [comment] 2022-08-24 15:45
Yeah we can close this issue if are able to use the workaround.

If there's anything we can do on our end to help fix the platform issue we can do that. I'll reach out to the Amplify team.

**Closed** 2022-08-24 15:58 UTC
Labels: type: bug, scope: nextjs
