### ISSUE TITLE
Playwright: @nx/playwright --configuration differs from generation a new app with playwright

### ISSUE THREAD

**Issue by the-ult** [nrwl/nx#19336] opened 2023-09-26 08:47 UTC
### Current Behavior

```
npx nx generate @nx/angular:application --name=foo --directory=apps --e2eTestRunner=playwright --projectNameAndRootFormat=as-provided --no-interactive
```

Results in:
- apps
   - foo
   - foo-e2e 

However:
```
npx nx generate @nx/playwright:configuration --project=expo --no-interactive
```
results in:

- apps
   - foo
      - e2e
      

What is the correct result? 
(_I kinda like the `e2e` within the app folder_)

### Expected Behavior

I would expect the behavior to be the same with both generators

### Steps to Reproduce

1. create an app without e2e
2. add playwright configuration to the app
3. create a different app WITH playwright e2e

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : win32-x64
   npm    : 10.1.0

   nx                 : 16.9.1
   @nx/js             : 16.9.1
   @nx/jest           : 16.9.1
   @nx/linter         : 16.9.1
   @nx/workspace      : 16.9.1
   @nx/angular        : 16.9.1
   @nx/cypress        : 16.9.1
   @nx/devkit         : 16.9.1
   @nx/eslint-plugin  : 16.9.1
   @nx/playwright     : 16.9.1
   @nrwl/tao          : 16.9.1
   @nx/web            : 16.9.1
   @nx/webpack        : 16.9.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 14.3.0
```

### Package Manager Version

npm 10.1.0

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-12-19 17:26
Thanks for reporting this!

This is the intended behavior. Please note the `@nx/playwright:configuration` is not a project generator. It's a generator to set up the Playwright required configuration for a project previously created. It doesn't deal with creating a separate project. It will be up to you if you want to set it up in a separate project or not.

Historically, we've recommended having e2e in separate projects so affected commands & caching can be better utilized, but with [`inputs`](https://nx.dev/recipes/running-tasks/customizing-inputs#finetuning-caching-with-inputs) you can have e2e tests in the same project and fine-tune which files affect what more accurately.

The application generators still create a separate project, but this is something we might look into changing in the future.

I'm going to close this since it's working as designed.

**Closed by leosvelperez** 2023-12-19 17:26 UTC
Labels: type: bug, scope: testing tools
