### ISSUE TITLE
NX spawns additional terminal windows with message [process exited with code 1]

### ISSUE THREAD

**Issue by LuckeeDev** [nrwl/nx#9671] opened 2022-04-03 16:16 UTC
## Current Behavior

Running `nx serve project` with a NextJS project spawns additional terminal windows with the text `[process exited with code 1]`, but works fine apart from this (i.e: no errors in the original console).

## Expected Behavior

The process should exit if an error happens instead of spawning new console windows.

## Steps to Reproduce

The issue arises even in any repo with a NextJS project.

To see an example, you can clone [this repo](https://github.com/LuckeeDev/csl), run `yarn install` and `yarn dev web`.

### Failure Logs

```
[process exited with code 1]
```

### Environment

```
Node : 16.13.1
OS   : win32 x64
yarn : 1.22.18

nx : 13.9.6
@nrwl/angular : Not Found
@nrwl/cypress : 13.9.6
@nrwl/detox : Not Found
@nrwl/devkit : 13.9.6
@nrwl/eslint-plugin-nx : 13.9.6
@nrwl/express : Not Found
@nrwl/jest : 13.9.6
@nrwl/js : 13.9.6
@nrwl/linter : 13.9.6
@nrwl/nest : Not Found
@nrwl/next : 13.9.6
@nrwl/node : 13.9.6
@nrwl/nx-cloud : Not Found
@nrwl/nx-plugin : Not Found
@nrwl/react : 13.9.6
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 13.9.6
@nrwl/web : 13.9.6
@nrwl/workspace : 13.9.6
typescript : 4.6.3
rxjs : 6.6.6
---------------------------------------
Community plugins:
     @jscutlery/semver: 2.21.6
```

**Comment by Ionaru** [comment] 2022-04-08 23:43
Duplicate of https://github.com/nrwl/nx/issues/8902

**Closed** 2022-04-09 06:13 UTC
Labels: type: bug, scope: nextjs
