### ISSUE TITLE
adding gateway produces malformed file name

### ISSUE THREAD

**Issue by nhhockeyplayer** [nrwl/nx#4130] opened 2020-11-22 08:39 UTC
I thought the schematic could be a little more intuitive and coaching when fields are omitted to allow it to ask/pick

Im just feeling out where it will go

and this is where it went for this instance

1. I created a workspace named portal
2. I installed all relevant packages that would be needed for this to complete using YARN
3. I generated a front end APP named dashboard.  `nx g @nrwl/angular:app`
4. I generated a back end Nest APP named micro-root  `nx generate @nrwl/nest:app micro-root --frontend-project dashboard `

all is well from here builds runs fine

this is where the issue arises

`nx generate @nrwl/nest:gateway`

I had hoped the schematicx would prompt me but it didnt and bypassed dry-run and populated the following file into the micro-root project

    -dry-run.gateway.ts

```
import { SubscribeMessage, WebSocketGateway } from '@nestjs/websockets';

@WebSocketGateway()
export class –dryRunGateway {
  @SubscribeMessage('message')
  handleMessage(client: any, payload: any): string {
    return 'Hello world!';
  }
}

```

**Comment by mandarini** [comment] 2020-11-24 11:20
Hi there @nhhockeyplayer ! Thanks for filing an issue!

I could not reproduce your issue, unfortunately... :( 

<img width="554" alt="Screenshot 2020-11-24 at 1 06 33 PM" src="https://user-images.githubusercontent.com/6603745/100086292-e2606c80-2e55-11eb-84cd-d083b5a79cea.png">

When I run the `nx generate @nrwl/nest:gateway` schematic, I get prompted to provide a name. 
<img width="627" alt="Screenshot 2020-11-24 at 1 07 25 PM" src="https://user-images.githubusercontent.com/6603745/100086375-015efe80-2e56-11eb-810f-3e38c36a6d0c.png">

It also works fine with the `--dry-run` flag.

I thought that maybe you missed something, and you accidentally provided `--dry-run` as the name for the gateway. So, I tried to reproduce your case by providing as the name of the gateway a number of combinations like `-dry-run`, `--dry-run`, `--dryRun`, `-dryRun`, `---dry-run`. With `-dry-run` provided as *name* I did get the `-dry-run.gateway.ts`, but none of my combinations/trials produced a class name with a dash at the front (`–dryRunGateway`).
<img width="448" alt="Screenshot 2020-11-24 at 1 10 29 PM" src="https://user-images.githubusercontent.com/6603745/100086694-6f0b2a80-2e56-11eb-8508-d03c34cd6eb3.png">
<img width="467" alt="Screenshot 2020-11-24 at 1 10 39 PM" src="https://user-images.githubusercontent.com/6603745/100086712-73cfde80-2e56-11eb-8874-86e6ae019d09.png">

Let me see how I can help:
1. Can you please try it once more, maybe with the latest version of Nx, and let me know where it failed?
2. Can you please let me know what steps you followed to create your nx workspace? 
    a. Run `npx create-nx-workspace@latest portal`
    b. Choose ` angular           [a workspace with a single Angular application]`
        <img width="632" alt="Screenshot 2020-11-24 at 1 13 52 PM" src="https://user-images.githubusercontent.com/6603745/100087101-e6d95500-2e56-11eb-98f6-d82f3e84af67.png">
        or did you choose `angular-nest      [a workspace with a full stack application (Angular + Nest)]`
        <img width="678" alt="Screenshot 2020-11-24 at 1 14 27 PM" src="https://user-images.githubusercontent.com/6603745/100087171-fbb5e880-2e56-11eb-910c-1f522f064fbf.png">
        (not much of a difference there, I just want to make sure that we're on the same page)
    c. I assume you chose the first (` angular           [a workspace with a single Angular application]`) and then did 
       `yarn add -D @nrwl/nest`
    d. Then `nx generate @nrwl/nest:app micro-root --frontend-project dashboard`

Up until that point it's pretty clear.
But then, did you run
a. `nx generate @nrwl/nest:gateway` and provided a name, or failed to provide a name and got an error?
b. `nx generate @nrwl/nest:gateway --dry-run` and the schematic did not ask you to provide a name?
c. `nx generate @nrwl/nest:gateway` and you accidentally provided `-dry-run` as the name?

On my side, it asked me to provide a name every time, whether I added the `--dry-run` flag on the command or not.

Please let me know of the exact steps you followed so that I can help!

**Comment by mandarini** [comment] 2020-11-24 11:26
Hmmm, I just saw [your other issue here](https://github.com/nrwl/nx/issues/4131). So, I understand that the schematic worked fine for you in the end, but it's just the `--dry-run` flag that's not working properly. :) Well, I will close this issue now, since I see that it's working on your side! :) Please try to close the issues that are not issues after all! I will look into the other issue now! :)

**Comment by mandarini** [comment] 2020-11-24 14:00
Reopening, because I found the case where your issue fails. Looking into it. Referencing [this issue here](https://github.com/nrwl/nx/issues/4130) too.

Please, @nhhockeyplayer , confirm that your workspace was setup like this:
* empty workspace
* `CLI to power the Nx workspace       (Use arrow keys)`
    `❯ Nx           [Recommended for all applications (React, Node, etc..)]`
Resulting that you have a `workspace.json` file and NOT a `angular.json` file.

<img width="880" alt="Screenshot 2020-11-24 at 3 59 19 PM" src="https://user-images.githubusercontent.com/6603745/100103768-04fe7f80-2e6e-11eb-9a0e-360698315e0a.png">

**Comment by mandarini** [comment] 2021-03-18 10:28
This has now been fixed! Closing this issue!

**Closed by mandarini** 2021-03-18 10:28 UTC
Labels: scope: node, type: bug
