### ISSUE TITLE
Cannot generate a new app

### ISSUE THREAD

**Issue by jdk339** [nrwl/nx#720] opened 2018-08-20 15:34 UTC
Running 

`ng g app my-app`

gives

`ENOENT: no such file or directory, stat '/Users/user/workspace/node_modules/.bin/in-install'`

I have run and re-run npm install multiple times after deleting 'node_modules'

Partial `package.json`:

```
{
  "dependencies": {
    "@angular/animations": "6.0.1",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "6.0.1",
    "@angular/compiler": "6.0.1",
    "@angular/core": "6.0.1",
    "@angular/forms": "6.0.1",
    "@angular/http": "5.2.7",
    "@angular/material": "^5.2.5",
    "@angular/platform-browser": "6.0.1",
    "@angular/platform-browser-dynamic": "6.0.1",
    "@angular/router": "6.0.1",
    "@angular/service-worker": "^5.2.10",
    "@ngrx/effects": "6.0.1",
    "@ngrx/entity": "^4.1.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@ngrx/store-devtools": "6.0.1",
    "@nrwl/nx": "6.0.2",
    "@okta/okta-angular": "^1.0.2",
    "@swimlane/ngx-datatable": "^11.3.2",
    "core-js": "^2.5.4",
    "moment": "^2.22.1",
    "ng2-file-upload": "^1.3.0",
    "ngx-chips": "^1.8.0",
    "npm": "^5.8.0",
    "rxjs": "6.0.0",
    "web-request": "^1.0.7",
    "zone.js": "^0.8.26",
    "rxjs-compat": "6.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cli": "6.0.1",
    "@angular/compiler-cli": "6.0.1",
    "@angular/language-service": "6.0.1",
    "@nrwl/schematics": "^6.2.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "0.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "^0.2.2",
    "prettier": "1.10.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^2.9.2"
  }
}
```

**Comment by bcabanes** [comment] 2018-10-04 18:15
Hi,

Closing the issue, this corresponds to an older version of Nx, could not reproduce on latest Nx version.

**Closed by bcabanes** 2018-10-04 18:15 UTC
