### ISSUE TITLE
Storybook - forward Storybook's native parameters in CLI

### ISSUE THREAD

**Issue by danr-za** [nrwl/nx#7531] opened 2021-10-27 05:40 UTC
## Description

Storybook supports various parameters such as `output-dir` (which is for example needed by Chromatic), log-level, opening the browser, ssl and others. 
It would be helpful to simply forward them when using nx storybook cli. 

## Motivation

Native Storybook support

**Comment by cakeinpanic** [comment] 2022-01-09 14:16
Hi, are there any updates on it?

**Comment by danr-za** [comment] 2022-01-11 22:43
any feedback will be appreciated 🙃  @mandarini

**Comment by mandarini** [comment] 2022-01-12 08:09
Hi there! No news on that yet. It's a feature request, and we're prioritizing bugs at the moment. I will let you know. However, in the meantime, if any of you would like to give this a shot, let me know, and I can help you! :)

**Comment by danr-za** [comment] 2022-01-13 09:30
Sure thing.
I'll try to submit a PR by the weekend or so.
Thanks!

**Comment by mandarini** [comment] 2022-03-09 11:41
Hi there, on second thoughts, I think that the native parameter forwarding should work as it is now. They may not appear in our schema, but I think they are forwarded. @danr-za can you give it a try and let me know? I mean, just pass the parameters as you would normally, and observe if they work or not..

**Comment by mandarini** [comment] 2022-03-17 10:06
Hi there! :) I am in the process of changing our `storybook` executor for Angular, from our custom one to the native Storybook one. This should mean that it also supports any other params. Do you want to give this a shot? Here's the PR: https://github.com/nrwl/nx/pull/9332

**Comment by mandarini** [comment] 2022-03-18 14:42
@danr-za  Oh, also, btw, did you try adding these options in the `project.json`, under the `storybook` target `options`? Anything in that `options` object gets passed down, as a Storybook CLI option.

**Comment by danr-za** [comment] 2022-03-22 07:41
@mandarini nope, just in the cli (but I guess both should be supported)

**Comment by mandarini** [comment] 2022-04-12 18:11
Hi @danr-za ! I checked today, and I could not reproduce. I mean, I tried passing a number of parameters (either them being in our schema or not) and they all worked, except the `--open` one (because we hard-code `ci: true` but that's another story). I mean, can you send me a repo where you tried adding params through the CLI and they did not work? I mean, repo + commands!

**Comment by danr-za** [comment] 2022-04-13 10:45
ye, hope I can take it this week.

**Comment by mandarini** [comment] 2022-04-13 16:46
Perfect, thanks! :)

**Comment by mandarini** [comment] 2022-04-13 17:10
I'm linking this [PR](https://github.com/nrwl/nx/pull/9827) here since it's related (only for the `--open` flag).

**Comment by mandarini** [comment] 2022-05-19 13:14
I am closing this, since I am 99.9% sure that it works as expected with all the latest changes. Please feel free to reopen, after you test with latest version of Nx! 

Thank you all!

**Closed by mandarini** 2022-05-19 13:14 UTC
Labels: type: feature, scope: storybook

**Comment by janeklb** [comment] 2022-09-16 20:52
Hi @mandarini 

I don't believe this is working as expected -- unless, of course, we expect different things :)

For example, if you have the following script in your `package.json`
```json
{
  "scripts": {
    "build-storybook": "nx build-storybook my-app",
  }
}
```

and you run 
```shell
npm run build-storybook -- --webpack-stats-json
```

The `@nrwl/storybook:build` executor will not forward the cli arg (`--webpack-stats-json`) to the storybook builder.

We are able to work around it by adding the necessary config (`webpackStatsJson: true`) to the executor's `options` in `project.json` (what you mentioned [here](https://github.com/nrwl/nx/issues/7531#issuecomment-1072477716)); however, it introduces some very brittle coupling between our `project.json` and the process that invokes the `build-storybook` command: [chromaui/action](https://github.com/chromaui/action) ([chromatic](https://chromatic.com/)'s Github Action).

The `chromaui/action` action runs the following command
```shell
npm run --silent build-storybook -- --output-dir /tmp/chromatic--1761-OSRHsIVpk1KR --webpack-stats-json /tmp/chromatic--1761-OSRHsIVpk1KR
```

but then spits out a warning saying that the storybook did not get built in the expected `/tmp/chromatic--1761-OSRHsIVpk1KR` directory (it is instead built in the directory specified the executor's options in`project.json` etc.)

I believe this qualifies as unexpected behaviour - would you agree?

**Comment by mandarini** [comment] 2022-09-21 12:38
Hey @janeklb sorry just seeing this. I promise to look into it this week!

**Comment by jaknas** [comment] 2022-09-23 11:23
> @danr-za @cakeinpanic Oh, also, btw, did you try adding these options in the `project.json`, under the `storybook` target `options`? Anything in that `options` object gets passed down, as a Storybook CLI option.

Could NX make it visible in the documentation for the executor? This behavior is not obvious.

**Comment by mandarini** [comment] 2022-09-23 15:29
Sure, I'll make sure to update it next week. Thanks for the feedback!

**Comment by mandarini** [comment] 2022-09-26 14:01
@janeklb I pushed a fix (we're not overriding `output-dir` any more). I think that should fix the issues you are having, and it makes sense, too. Thanks for pointing it out.

I will eventually fix the docs with some examples.

**Comment by janeklb** [comment] 2022-09-28 21:39
Thanks @mandarini!

The fix (#12238) doesn't seem to enable _all_ CLI arguments to be passed to the storybook builder. It does solve my specific problem; however, I'm now just curious if this is intentional or simply just not something that's been worked out?

**Comment by mandarini** [comment] 2022-09-29 07:38
Oh @janeklb you see these two arguments are the only ones we override. All the rest we are passing them as they are!

**Comment by mandarini** [comment] 2022-09-29 07:41
@janeklb if you look at the [same file](https://github.com/nrwl/nx/blob/master/packages/storybook/src/executors/build-storybook/build-storybook.impl.ts#L54), a few lines above:

```
function storybookOptionMapper(
  builderOptions: StorybookBuilderOptions,
  frameworkOptions: any,
  context: ExecutorContext
) {
  const storybookOptions = {
    ...builderOptions,
    ...resolveCommonStorybookOptionMapper(
      builderOptions,
      frameworkOptions,
      context
    ),
    mode: builderOptions?.['mode'] ?? 'static',
    outputDir:
      (builderOptions?.['outputDir'] || builderOptions?.['output-dir']) ??
      builderOptions.outputPath,
  };

  return storybookOptions;
}
```

take note at:

```
  const storybookOptions = {
    ...builderOptions,
```
We are passing all the builder options as they are. No changes.

However, below, we are were overriding `outputDir` with `outputPath` and `mode` with `static`. This is what I fixed. First check if there is `outputDir` or `mode` already passed as options, if they are not, write them, if they are there, don't touch them!

**Comment by janeklb** [comment] 2022-10-01 16:52
Thank you for taking the time to explain - much appreciated :)

**Comment by mandarini** [comment] 2022-10-03 08:03
:D
