### ISSUE TITLE
It would be nice to have an alternative to `runExecutor` that runs deps too

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#10343] opened 2022-05-17 11:56 UTC
- [X] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Currently, the most common way of automatically running an executor from another executor is using the `runExecutor` function from `@nrwl/devkit`.
This:
1. requires too much boilerplate for the calling executor to trigger a target as they have to somehow fetch the configuration from the `project.json` configuration before calling `runExecutor` etc...
2. calling executor has to trigger the deps, otherwise, this causes issues similar to these: https://github.com/nrwl/nx/issues/9260 https://github.com/nrwl/nx/issues/5803

It would help if we could find an alternative way to programmatically trigger a target using `@nrwl/devkit` and without having to run an nx command in another process.

## Motivation

This would fix issues like this https://github.com/nrwl/nx/issues/9260 https://github.com/nrwl/nx/issues/5803
It would also avoid common boilerplate like this:
https://github.com/nrwl/nx/blob/0c8eade82e4c3a4d555f7407c0a324d982bcbd59/packages/cypress/src/executors/cypress/cypress.impl.ts#L133-L153

## Suggested Implementation
While adding a `withDeps` option to `runExecutor` is tempting, I don't think that is the right solution.
`runExecutor` is a low level function that should be stateless (i.e. configuration agnostic). 
We need a higher level function like `runTask` that uses the target's options, runs deps, enjoys caching etc...

This function probably already exists somewhere in nx. 
Maybe it's just a thin layer above [`createTask`](https://github.com/nrwl/nx/blob/0c8eade82e4c3a4d555f7407c0a324d982bcbd59/packages/nx/src/tasks-runner/run-command.ts#L302)  that creates the task and give it to the task runner.

## Alternate Implementations
Run an nx command in another process.

**Comment by yjaaidi** [comment] 2022-05-17 11:56
cc. @edbzn

**Comment by simonme** [comment] 2023-01-24 08:30
This would still be awesome! Current workaround is to call `nx` cli via `execa`, which isn't optimal.

**Comment by quicksilverr** [comment] 2023-01-31 06:12
This would definitely be a great feature! @vsavkin @Coly010

**Comment by cameron-jf-gray** [comment] 2023-03-09 21:41
I would also love to see this feature. Currently calling nx via exec for things that require deps.

**Comment by simonme** [comment] 2023-11-15 13:09
This would still be really nice to have!

**Comment by AgentEnder** [comment] 2024-01-28 22:22
I'm going to move forward with closing this out, partially as a duplicate of #7560 (which I also just closed).

**Closed** 2024-01-28 22:33 UTC
Labels: type: feature, scope: core
