### ISSUE TITLE
Parallel options nx.json tasksRunnnerOptions are Ignored in Nx 16

### ISSUE THREAD

**Issue by pumano** [nrwl/nx#16662] opened 2023-04-30 17:54 UTC
### Current Behavior

nx run-many --exclude=some-libs --target=lint --quiet run only 3 parallel default jobs

### Expected Behavior

run parallel jobs based on information from nx.json tasksRunnerOptions (I have 6)

workaround: add `--parallel=6` manually to command

### Steps to Reproduce

1. nx 16
2. angular 16

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin arm64
   yarn   : 3.5.0
   Hasher : Native
   
   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/angular        : 16.0.1
   @nx/cypress        : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nx/storybook      : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/webpack        : 16.0.1
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @ngneat/transloco     : 4.2.6
   @ngrx/component-store : 15.4.0
   @ngrx/effects         : 15.4.0
   @ngrx/entity          : 15.4.0
   @ngrx/router-store    : 15.4.0
   @ngrx/store           : 15.4.0
   @ngrx/store-devtools  : 15.4.0
   @ngneat/spectator     : 14.0.0
   @ngrx/eslint-plugin   : 15.4.0
   @ngrx/schematics      : 15.4.0
   @storybook/angular    : 7.0.7
   nx-stylelint          : 15.0.0
```

### Additional Information

<img width="436" alt="Screenshot 2023-04-30 at 20 53 08" src="https://user-images.githubusercontent.com/17675259/235368522-e45abc90-d70e-4d09-ab29-253f17366722.png">
only 3 jobs in parallel

That is regression previous versions works good

previous bug #10756

**Comment by jsaguet** [comment] 2023-05-01 21:12
I'm seeing the same issue.

It looks like this behavior was introduced in #13837

It seems to me that the expected behavior should be to use the runner parallel option when `--parallel` flag is provided without a value or not provided at all instead of forcing it to 3.
It means the above PR should be reverted but it would bring back the old behavior described in #13782

I could open a PR to fix this but I'm not sure what the expected solution is.

**Comment by pumano** [comment] 2023-05-02 06:46
Looks like #13782 about when is not set default should be 1, but works when change it to another value. Looks like 1 (sequentional running) is very slow when you processing large amount of libs, and it's bad as defaults. More over 3 is really bad too. Maybe use 6 as default (mostly modern CPU provide 6+  cores) or maybe when create project check available cores and provide better values or check when running and tell if user can use more cores for it.

But my bug about I can't set parallel from nx.json

**Comment by AgentEnder** [comment] 2023-05-02 20:59
This is fixed by: https://github.com/nrwl/nx/pull/16707

**Closed by AgentEnder** 2023-05-02 20:59 UTC
Labels: type: bug, scope: core
