### ISSUE TITLE
Support indexFileTransformer in @nx/angular:browser-esbuild executor

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#20477] opened 2023-11-29 17:27 UTC
### Current Behavior

After updating to beta version and started using the @nx/angular:browser-esbuild I have the following issues:

1. Schema error when using "executor": "@nx/angular:browser-esbuild":

**Data path "" must NOT have additional properties(indexFileTransformer).**

2. Running nx build production:

**Error: NX 'indexFileTransformer' is not found in schema**

3. Warnings:

**Project 'ui' contains extension with invalid name ($schema).
Project 'ui' contains extension with invalid name (tags).**__

### Expected Behavior

It should work without errors

### Steps to Reproduce

Update to latest beta version and use the `@nx/angular:browser-esbuild` executor with `indexFileTransformer`

### Nx Report

```shell
none
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2023-11-30 09:45
> 3. Warnings:
> 
> **Project 'ui' contains extension with invalid name ($schema).**
> **Project 'ui' contains extension with invalid name (tags).**

I haven't been able to reproduce this. Could you provide a repo so I can reproduce it and troubleshoot it?

**Comment by leosvelperez** [comment] 2023-11-30 10:00
> It's only supported when using the builder programmatically.
> 
> That said, we can add support for it similar to how we added it to the `@nx/angular:webpack-browser`.

I correct myself. The `@angular-devkit/build-angular:browser-esbuild` builder doesn't support providing an index.html transformer function at all. Not even when using the programmatic API. It's only supported by the `@angular-devkit/build-angular:dev-server` builder. This is different than the `@angular-devkit/build-angular:browser` builder which does accept providing the transformer when using it programmatically.

This blocks us from adding support for it to the `@nx/angular:browser-esbuild` executor. I'll ping the Angular team on this to see if we can unblock this.

**Comment by ArielGueta** [comment] 2023-11-30 11:37
I see that you removed the comments where you said that it will be supported

**Comment by leosvelperez** [comment] 2023-11-30 11:49
> I see that you removed the comments where you said that it will be supported.

Sorry, I'm unsure what you refer to. I didn't remove any comments. I only corrected myself saying we can't support it if the underlying Angular CLI builder doesn't allow to provide it.

> The weird thing is that when I comment the Angular schema protection it does work. I put a log in the transformer file and I see it.

Are you referring the `serve` target works? That's expected because the `dev-server` uses the build target `indexFileTransformer` and process it. What I was referring above is that, while serving your application would transform the `index.html` correctly, building the application won't, because the builders use for building the application don't support providing such transformer.

**Comment by ArielGueta** [comment] 2023-11-30 12:04
Sorry, my bad!

See here https://github.com/nrwl/nx/pull/20311#issuecomment-1819304419

**Comment by ArielGueta** [comment] 2023-11-30 12:06
So you're saying that only the dev-server supports it? If we can use it also for the build it's pretty redundant for the dev server.

**Comment by leosvelperez** [comment] 2023-11-30 12:14
Oh, that comment. I wrongly didn't check that the builder didn't support it when you asked in that other issue. My bad. I didn't remove it though 😅 

Anyways, answering the question more accurately, the `dev-server` does support build targets specifying the `indexFileTransformer` option, but the Angular CLI `browser-esbuild` builder doesn't allow providing it. Therefore, it can't be supported until the Angular CLI builder supports it.

I already pinged the Angular team on this. I'm unsure whether the idea is to use esbuild plugins for that or if they'll continue supporting a specific index.html tranformer function. I'm working on adding support for esbuild plugins, and that should allow you to transform your index.html contents if the transformer is not available.

**Comment by leosvelperez** [comment] 2023-11-30 14:42
BTW, I was able to reproduce the warnings you mentioned. That'll be fixed by https://github.com/nrwl/nx/pull/20499.

**Comment by r-LaForge** [comment] 2023-11-30 17:09
To make this issue easier to find, and it appears to be specifically about the `indexFileTransformer` option, would the title be more appropriately worded as "@nx/angular:browser-esbuild executor does not support indexFileTransformer" or something similar?

This is something I'm very interested in watching for my own team's use-case as well.

**Comment by leosvelperez** [comment] 2023-12-01 09:30
Quick update:

Support for ESBuild plugins being added in https://github.com/nrwl/nx/pull/20504. In the absence of a specific `indexFileTransformer` option, a simple plugin can be written to perform the transformations you need.

I'm still waiting on feedback from the Angular team on this matter. If it takes too long or it doesn't move forward, we could look into supporting it ourselves by passing it along to the underlying Angular CLI builder as a plugin we create on the fly that executes the developer-provided transformation function.

**Comment by leosvelperez** [comment] 2023-12-18 09:22
FYI: this is coming in Angular 17.2.0: https://github.com/angular/angular-cli/commit/66edac4bbd6f5d9325cf254189db7da32eec883a. Once it's released and we release the support for that Angular version (we're already working on it), you'll be able to use it.

**Comment by leosvelperez** [comment] 2024-01-31 08:52
This was added in https://github.com/nrwl/nx/pull/21026 and released in Nx 17.3.0.

**Closed by leosvelperez** 2024-01-31 08:52 UTC
Labels: type: feature, blocked: third-party, scope: angular
