### ISSUE TITLE
Next.js : Generate component with style SASS Error : Global CSS cannot be imported from files other than your Custom <App>

### ISSUE THREAD

**Issue by msreekm** [nrwl/nx#3980] opened 2020-10-27 14:53 UTC
## Current Behavior
CLI command nx g component (next.js) produce the wrong files-

when selecting sass for styling while generating a component-
nx g component PartyPopper --project=demo --style=scss
it generates - component with 
 import './party-popper.scss'; inside components!
This give error -Global CSS cannot be imported from files other than your Custom <App>

## Expected Behavior
Next.js only allow importing css/sass directly inside apptsx ,inside other components it has to use modules.

CLI should generate a component with styles in the file party-popper.module.scss
and inside component, import like so, import styles from './party-popper.module.scss';

## Steps to Reproduce
run nx g component PartyPopper --project=demo --style=scss. (next.js)

### Failure Logs
Global CSS cannot be imported from files other than your Custom <App>

### Environment
All

**Comment by mandarini** [comment] 2020-10-29 09:10
Hi @msreekm ! Thanks for filing an issue. I think this is a duplicate of [#3803](https://github.com/nrwl/nx/issues/3803)?

**Closed** 2020-10-31 15:55 UTC
Labels: type: bug
