### ISSUE TITLE
Allow an application to have two e2e test applications

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx#1595] opened 2019-07-18 21:49 UTC
Right now if you have an e2e test suite which ends in the suffix `-e2e` and there is not a corresponding application whose name is the same but without the suffix, NX errors out and dies.

As a workaround, you can change the type of project from 'application' to 'library' to get around the error. None the less, this limitation is annoying and the workaround is not obvious and probably has caveats

**Comment by FrozenPandaz** [comment] 2019-07-27 03:43
This should not fail. No dependency should be inferred for this project and the user should instead utilize `implicitDependencies` to create the dependency.

@wesleygrimes Can you take a look please?

**Comment by vsavkin** [comment] 2019-12-05 14:56
Duplicate of this: https://github.com/nrwl/nx/issues/987

**Closed** 2019-12-05 14:56 UTC
