### ISSUE TITLE
ngrx schematic silently fails

### ISSUE THREAD

**Issue by emilio-martinez** [nrwl/nx#1016] opened 2019-01-20 01:19 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior

ngrx schematic should generate an output.

## Current Behavior

ngrx schematic fails silently, regardless of `--dry-run` flag. In interactive mode it will display the appropriate prompts, but in non-interactive it will simply not do anything (as long as the minimum requirements are met, of course, i.e., `name`.

## Failure Information (for bugs)

I was able to get an error by calling the schematic in debug mode:

```sh
$ npx -p '@angular-devkit/schematics' -p '@angular-devkit/schematics-cli' -c 'schematics @nrwl/schematics:ngrx bla --module=libs/my-lib/src/lib/my-lib.module.ts --facade --debug --dry-run --verbose'

? Is this the root state of the application? No

An error occured:
Error
    at insertAfterLastOccurrence (/path/to/project/node_modules/@schematics/angular/utility/ast-utils.js:160:15)
    at Object.insertImport (/path/to/project/node_modules/@schematics/angular/utility/ast-utils.js:69:12)
    at Object.addImport (/path/to/project/node_modules/@nrwl/schematics/src/collection/ngrx/rules/add-imports-to-module.js:14:32)
    at /path/to/project/node_modules/@nrwl/schematics/src/collection/ngrx/rules/add-imports-to-module.js:63:27
    at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (/path/to/project/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/path/to/project/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/path/to/project/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/path/to/project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/path/to/project/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/path/to/project/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
```

### Steps to Reproduce

Simply calling the schematic, e.g.,

```sh
ng generate @nrwl/schematics:ngrx bla --module=libs/my-lib/src/lib/my-lib.module.ts --facade --dry-run
```

This will correctly, for example, ask for the desired `root` param and skip the `facade` prompt. Result is the same regardless of whether `--dry-run` is provided or not. Additionally, removing and reinstalling `node_modules` did not change anything. I was able to reproduce this on a blank project (after scaffolding a lib to generate into).

### Context

Please provide any relevant information about your setup:

- `@nrwl/schematics@7.4.1`
- `@angular/cli@7.1.4`
- `@angular-devkit/schematics@7.1.4`
- `node@8.11.4`

### Failure Logs

Included above

**Comment by rweng** [comment] 2019-02-08 16:59
I have the same problem with generate application

**Comment by abos** [comment] 2019-02-11 21:46
Similar problem here but not sure the issue is identical.
Typescript 3.3 or 3.2 makes no difference and @nrwl/schematics is 7.5.1.
I was not able to produce any debug output. 

Following command fails: 

    ng g lib welcome --debug --verbose --unit-test-runner jest --routing --lazy --directory=pages --module=true --prefix cc

but works if I remove "--routing  --lazy".

**Comment by ccpony** [comment] 2019-03-13 03:19
I can confirm this exact problem.  Lib gen fails silently when using --routing.

"@nrwl/nx": "^7.6.2"
"@nrwl/builders": "^7.6.2"
"@nrwl/schematics": "^7.6.2"
"@angular/cli": "^7.3.5"
"@angular/compiler-cli": "^7.2.9"

**Comment by brassfiddle3** [comment] 2019-06-20 20:39
I encountered this issue without realizing that the --routing option was the problem and, unfortunately, Google searches such as "ng generate app not working in Nx monorepo" and "ng generate app fails to output" did not land me here until a colleague happened to select "no" for routing and the generate worked.  I encountered the problem with the following:

 @nrwl/nx": "7.6.2"
 @nrwl/builders": "7.6.2"
 @nrwl/schematics": "7.6.2"

And ng --version output of:

@angular-devkit/architect		0.13.1
@angular-devkit/build-angular	0.13.1
@angular-devkit/build-optimizer	0.13.1
@angular-devkit/build-webpack	0.13.1
@angular-devkit/core			7.3.1
@angular-devkit/schematics		7.3.9
@angular/cdk				        7.3.7
@angular/cli				        7.3.9
@angular/flex-layout			7.0.0-beta.24
@ngtools/webpack			        7.3.1
@schematics/angular			7.3.9
@schematics/update			0.13.9
rxjs					                6.4.0
typescript				        3.1.6

However, I had a separate monorepo with the following versions where the issue did not show up:

@nrwl/nx: not installed
@nrwl/schematics: 7.8.6
@angular/cli: 7.3.1
@angular-devkit/architect	0.13.1
@angular-devkit/core		7.3.1
@angular-devkit/schematics	7.3.1
@angular/cli			        7.3.1
@schematics/angular		7.3.1
@schematics/update		0.13.1
rxjs					        6.3.3
typescript				3.2.2

As rweng suggested, I tried updating typescript from 3.1.6 to 3.2.4 in the first repo and it resolved the issue.  I could then generate apps and libraries with or without the --router option.  For reference, I was using NodeJS 10.15.3 (npm 6.4.1).

**Comment by brandonroberts** [comment] 2019-08-09 14:52
Is this still an issue in Nx 8.x?

**Comment by emilio-martinez** [comment] 2019-08-10 23:49
Not sure! A lot has changed in Nx since then, of course, but also I stopped using this schematic altogether because a) it didn't work for me and b) the schematics from the actual ngrx org got better since then. The main gap is perhaps generating a facade, but that's relatively easy to do manually.

**Comment by brandonroberts** [comment] 2019-08-12 12:49
Thanks @emilio-martinez. If its no longer an issue, you can close the issue.

**Closed** 2019-08-18 10:46 UTC
Labels: needs: retry with latest, ngrx, type: bug
