### ISSUE TITLE
12.6.5 added -verbose option for nx run web:deploy-web, which can break builds

### ISSUE THREAD

**Issue by jbarmash** [nrwl/nx#6644] opened 2021-08-07 19:26 UTC
## Current Behavior

run-commands 
adds `--verbose=false` option, which breaks docker build.  

Inside Github Actions: 

`nx run web:deploy-web` 

in project.json

 "deploy-web": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "nx build web",
          "docker build -f ./apps/web/Dockerfile . -t web"
        ],
        "parallel": false
      }
    },

This is the error message: 

```
unknown flag: --verbose
See 'docker build --help'.
ERROR: Something went wrong in @nrwl/run-commands - Command failed: docker build -f ./apps/web/Dockerfile . -t web --verbose=false

```
I believe this commit may be the culprit:  

https://github.com/nrwl/nx/commit/ffcd28348b85f91822681e453ad97e7ccddca974?branch=ffcd28348b85f91822681e453ad97e7ccddca974&diff=split

## Expected Behavior

as of 12.5.3, this behavior worked fine. 

## Steps to Reproduce

`nx run web:deploy-web`

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

```
unknown flag: --verbose
See 'docker build --help'.
ERROR: Something went wrong in @nrwl/run-commands - Command failed: docker build -f ./apps/web/Dockerfile . -t web --verbose=false

```

### Environment

  Node : 14.17.4
  OS   : darwin arm64
  npm  : 6.14.14

  nx : Not Found
  @nrwl/angular : 12.6.5
  @nrwl/cli : 12.6.5
  @nrwl/cypress : 12.6.5
  @nrwl/devkit : 12.6.5
  @nrwl/eslint-plugin-nx : 12.6.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.5
  @nrwl/linter : 12.6.5
  @nrwl/nest : 12.6.5
  @nrwl/next : Not Found
  @nrwl/node : 12.6.5
  @nrwl/nx-cloud : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.5
  @nrwl/storybook : 12.6.5
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by leosvelperez** [comment] 2021-08-09 09:30
Thanks for reporting this!

This is a duplicate of #6606. Please note this issue has already been fixed in #6607 and it should be released in the next patch version. Keep an eye on the releases to get the fix.

**Closed by leosvelperez** 2021-08-09 09:30 UTC
Labels: type: bug
