### ISSUE TITLE
ensureNxProject doesn't link together sub dependencies from the same (self) Nx project.

### ISSUE THREAD

**Issue by Brian-McBride** [nrwl/nx#5639] opened 2021-05-12 15:52 UTC
## Current Behavior
In a plugin mono repo, I have a published package `@anatine/esbuild-decorators` and then a second package `@anatine/esbuildnx` that requires it. 

When running the e2e tests utilizing the devkit tools `ensureNxProject` will result in the `@anatine/esbuild-decorators` not being found. 

## Expected Behavior
The `ensureNxProject` should properly link up all dependences within the monorepo. That or the docs should specify commands that will link these all properly.

## Steps to Reproduce
You can check out the test:
https://github.com/anatine/esbuildnx/blob/main/e2e/esbuildnx-e2e/tests/esbuildnx.spec.ts

## TEMP FIX
For now, I've been using the `fs-extra` lib to create a symbolic link then removing it. Not ideal, but it works most of the time. 

```typescript
  const projectRoot = `${process.cwd()}/tmp/nx-e2e/proj`;
  const esbuildnxPluginModules = `${process.cwd()}/dist/packages/esbuildnx/node_modules`;
  const esbuildnxDecoratorsPlugin = `${process.cwd()}/dist/packages/esbuild-decorators`;

  beforeAll(() => {
    ensureNxProject('@anatine/esbuildnx', 'dist/packages/esbuildnx');
    ensureDirSync(esbuildnxPluginModules);
    ensureSymlinkSync(
      esbuildnxDecoratorsPlugin,
      `${esbuildnxPluginModules}/@anatine/esbuild-decorators`
    );
  });

  afterAll(() => {
    removeSync(esbuildnxPluginModules);
  });
```

### Environment
  Node : 16.0.0
  OS   : darwin x64
  npm  : 7.10.0
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.2.0
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : 12.2.0
  @nrwl/next : Not Found
  @nrwl/node : 12.2.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by ronnetzer** [comment] 2021-12-19 12:46
Facing the same problem, 
I was able to overcome it by using `patchPackageJsonForPlugin` and `runPackageManagerInstall` after `ensureNxProject`

**Comment by tinesoft** [comment] 2021-12-19 14:18
Hi @ronnetzer 

Can you elaborate your solution?
Because `ensureNxProject` internally called `newNxProject` which in turn, does already call `patchPackageJsonForPlugin` followed by `runPackageManagerInstall`. So I'm wondering  why/how  does your workaround work...🤔

**Comment by ronnetzer** [comment] 2021-12-21 05:32
@tinesoft Sure,

I was using the patch and install methods to add the dependent packages after the ensure.

So first you have the `ensureNxProject` for the package you want to test,

Then `patchPackageJsonForPlugin` to add the missing dependent package and ending with `runPackageManagerInstall` to install that added package.

It works a little weird as you'll see the npm install running twice, and throws warning for the missing dependent package for the first run (by `ensureNxProject`)

**Comment by AgentEnder** [comment] 2022-02-22 22:06
This issue is a duplicate of #4851, so I'm going to close it. There is some good info here but the link should still show 👍. I'm going to check on this stuff after working on local plugin support.

**Closed by AgentEnder** 2022-02-22 22:06 UTC
Labels: type: bug, scope: plugins
