### ISSUE TITLE
Angular Storybook build fails when setting "allowJs": true in tsconfig

### ISSUE THREAD

**Issue by pkirchniawy** [nrwl/nx#7825] opened 2021-11-20 19:31 UTC
## Current Behavior
When building storybook for an Angular app while setting the compilerOption `"allowJs": true` in the `tsconfig.base.json`, the build fails.

## Expected Behavior
The build should not fail.

## Steps to Reproduce
1. Create a fresh nx workspace with angular preset
2. Run `ng generate @nrwl/angular:storybook-configuration` for an angular project 
3. Set the compilerOption `"allowJs"`: true in the `tsconfig.base.json` of the repo
4. Run `yarn nx run myapp:build-storybook`

Link to reproduction in the nx-example repo:
https://github.com/nrwl/nx-examples/pull/177

### Failure Logs
```
ERR! => Failed to build the preview
ERR! ERROR in undefined(undefined,undefined):
ERR! TS5055: Cannot write file '/Users/philipp/Code/allowjs/.storybook/main.js' because it would overwrite input file.
ERR! ERROR in undefined(undefined,undefined):
ERR! TS5055: Cannot write file '/Users/philipp/Code/allowjs/apps/myapp/.storybook/main.js' because it would overwrite input file.
ERR! ERROR in undefined(undefined,undefined):
ERR! TS5055: Cannot write file '/Users/philipp/Code/allowjs/apps/myapp/.storybook/preview.js' because it would overwrite input file.
```

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : darwin arm64
  npm  : 8.1.0
  
  nx : 13.2.1
  @nrwl/angular : 13.2.1
  @nrwl/cli : 13.2.1
  @nrwl/cypress : 13.2.1
  @nrwl/devkit : 13.2.1
  @nrwl/eslint-plugin-nx : 13.2.1
  @nrwl/express : undefined
  @nrwl/jest : 13.2.1
  @nrwl/linter : 13.2.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.2.1
  @nrwl/storybook : 13.2.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @storybook/angular: 6.4.0-rc.5
        ```

**Comment by pkirchniawy** [comment] 2021-11-20 19:41
While searching for a solution i found, that the tsconfig.json inside the .storybook folder does not have a `outDir` property, like all other generated Typescript projects.

The docs (https://www.typescriptlang.org/tsconfig#outDir) say: 

> If not specified, .js files will be emitted in the same directory as the .ts files they were generated from.

So, when the outDir is missing, the js files are getting placed inside the directory and get build again, when having "allowJs" set to true.

When setting  `outDir: '../../../dist/out-tsc'` in the `/apps/myapp/.storybook/tsconfig.json` file, the build works fine.

If this is the proper solution, this would mean to add this line to the @nrwl/angular storybook generator.

This would be my first Issue and PR but I could take this issue and try to submit a PR. :smile:

**Comment by johngrimsey** [comment] 2021-12-12 15:05
@pkirchniawy Thanks man this workaround saved me!

**Comment by mandarini** [comment] 2022-02-01 10:51
Hi @pkirchniawy ! I am so so sorry that I did not get into this sooner! There were so many other issues that were pressing in the meantime, and it had been a very busy period.

Thank you very much for submitting an issue AND a PR to fix it!! :) :) That's amazing!!!! :) And your PR is exemplary! Tests, migrations, perfect!! :)

**Comment by mandarini** [comment] 2022-02-01 11:01
The thing is @pkirchniawy something must have changed in the meantime, because now I cannot reproduce your issue. I just generated an Angular Nx workspace, followed the steps you suggested (generated Storybook configuration for the Angular app), then `nx build-storybook my-app` and the build succeeds. Can you please try again, and let me know if your error persists?

Again, I am so sorry for not looking into this earlier, and I strongly hope it does not discourage you from contributing to Nx in the future! :) :)

**Comment by mandarini** [comment] 2022-02-08 11:59
I will be closing this, since it's not reproducible any more and I got no answer for a week. If it comes up again, or @pkirchniawy if you ever see this, reply here and I'll get back to it! :) 🙏

**Closed by mandarini** 2022-02-08 11:59 UTC
Labels: type: bug, blocked: repro needed, scope: storybook

**Comment by pkirchniawy** [comment] 2022-02-09 07:04
@mandarini Hey there :) Thank you for looking into the issue and pr. That's really interesting, I couldn't reproduce the error either now. It must have been an issue with one of the packages, that got updated in the meantime.

Even if the error disappeared, the question is, if it's ok that a tsconfig.json does not have an outdir, like every other one in an nx monorepo. What do you think?

**Comment by mandarini** [comment] 2022-02-11 14:33
Hi there @pkirchniawy ! We discussed your PR and we decided not to merge it. :( I'm sorry.. The reason is the following: Usually, indeed, tsconfig would have the outdir param. But we don’t think it's needed in the case of Storybook. We don’t really run the tsc compiler on top of it but rather the tsconfig is fed into the underlying webpack Typescript plugin. It's not that it would break things if it were there, of course, but it's not needed, either. So we decided to avoid adding the extra logic.I believe the default Angular Storybook setup doesn’t have it either. I hope this makes sense to you, and again I am sorry we did not get to this earlier! 

Thanks for contributing to Nx! :)
