### ISSUE TITLE
@nrwl/node:lib won't resolve tsconfig path aliases

### ISSUE THREAD

**Issue by TheMeteoRain** [nrwl/nx#7123] opened 2021-09-24 08:10 UTC
## Current Behavior
I am using path aliases in tsconfig.json in my generated @nrwl/node:lib.

Let's say tsconfig.json paths looks like this
`
"paths": {
      "@test": ["src/lib/index.ts"],
}
`

And let's say I use it like this in the code
`import something from '@test'`

## Expected Behavior
When I build my library the code should look something like this
`import something from '../../i/am/relative/path/to/the/right/place'`

Instead it still looks like this
`import something from '@test'`

## Steps to Reproduce
`nx g @nrwl/node:lib name --buildable`
Add path alias to tsconfig.json
`nx build name`

Compare imports from the source files and the dist.

## Site note
This same configuration works for @nrwl/react:lib but not for this @nrwl/node:lib

### Environment
```
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.8.0
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.9.0
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

**Comment by linbudu599** [comment] 2021-09-24 10:08
You will need [tsconfig-paths](https://github.com/dividab/tsconfig-paths) for executing built file with path mapping configurated.

**Comment by TheMeteoRain** [comment] 2021-09-25 01:16
I thought there might be something wonky with the underlying implementation in the @nrwl:node. If it's not that, then it's kinda strange that the same principle is not same between libs.

I will try that and post back here what kind of hurdles I had to do. It's a familiar tool, so I don't expect anything too difficult.

**Comment by TheMeteoRain** [comment] 2021-09-26 18:40
@linbudu599 There is no way to modify webpack or rollup config (whichever @nrwl/node:package uses). So basically there is no way of using tsconfig-paths. At least not in a way I know of. 

I can switch to @nrwl/node:build where I can modify webpack config, but the output is single file. I bet it's used for express etc. applications. I want to keep the file structure, which @nrwl/node:package did kept. Shouldn't @nrwl/node:package understand tsconfig paths out of the box? Or at least expose the config.

**Comment by linbudu599** [comment] 2021-09-27 07:13
Sorry, my explanation is not very detailed, let me carefully list the questions in the above conversation:

- `@nrwl/node:build` uses Webpack under the hood(as well as `@nrwl/web:build`), so it does understand path alias and replace `@test/test.ts` with `./relative/path/test.ts`.
- `@nrwl/node:package` uses TypeScript compiler directly, so it's not changing path alias(but it will include aliased path to build)
- Why I'm saying  `You will need tsconfig-paths for executing built file with path mapping configurated.` is that I thought you wants to execute built file but facing the `cannot find module @tests/test` error.
- If you just want alias path to be replaced correctly in compiled file, you will need to handle it yourself for now, as `tsconfig-paths` works at run-time intead of compile-time, it cannot solve your problem either.
- I've searched for and found something may fits you well: [tscpaths](https://github.com/joonhocho/tscpaths/blob/master/src/index.ts), which works at compile-time and will change your alias path.
- To intergate this tool with your workflow, I'd like to suggest that it your target lib has no workspace package dependencies, it's ok to use `@nrwl/workspace:run-commands` and commands like `['tsc --options', 'tscpaths --options']`. Otherwise it's getting more complicated, you need to copy source code of `@nrwl/node:package` executor and add your own codes..., but I will do this thing soon in [nx-plugin-workspace](https://github.com/LinbuduLab/nx-plugins/tree/main/packages/nx-plugin-workspace).

**Comment by TheMeteoRain** [comment] 2021-09-27 12:57
Thank you for some clarifications. And yes my problem is that the compiled output in the dist folder still has wrong paths.

I actually ditched all `@nrwl` executors since non of them match my needs. I ended up with result where all the path aliases resolved correctly and the folder structure was kept intact. I do not want to compile all my code to single file. It actually harms my use case a lot when importing said library.

I can post my codes later this week. They might help you with the plugin or with some help I can write the plugin. But let's see once you see the code.

**Comment by vugar005** [comment] 2022-02-03 14:11
Right now the only way resolve this is to add paths to `tsconfig.base.json` on root which is not good.
```
  "paths": {
      "@core/*": ["apps/mfe1/src/app/core/*"]
    }
```

**Comment by islami00** [comment] 2022-02-20 16:28
@TheMeteoRain  I'm not sure how helpful this is, but I had a similar problem with nx not picking up path aliases.
What I did notice was that if I imported index it resolved just fine. Hence, I tried reexporting the default exports I was referencing from root in the index file and it works. 
It's a workaround, but that's the only export that is being recognised right now

**Comment by simonbergstrom** [comment] 2022-04-11 13:36
> 

UPDATE: 
Changing path works if node_modules is already installed. If I delete node_modules after change path name the same error as described in this issue is back again.

**Comment by mmaterowski** [comment] 2022-04-28 08:03
### **My problem was transitioning from existing angular CLI project to nx. During that process nx renames:**
`tsconfig.json` to ->  `tsconfig.base.json `

and that's what vscdoe didn't handle very well. Event after restarting TS server, changing paths, deep-diving into extending process

After investigating multiple approaches it turns out that while running `tsc --traceResolution` all modules and imports were resolved as expected. I renamed tsconfig.base.json to tsconfig.json and everything was working again @vsavkin is it a known issue?

@vugar005 configuration is the right one, what's maybe worth mentioning is that in _tsconfig.json_ I set baseUrl to "."
```
{
...
"baseUrl": "."
}
```
Works without any extra mapping configurations or packages. Also with es-lint.

**Comment by roddc** [comment] 2022-07-06 05:56
I overwrite the `paths` in  `my-lib/tsconfig.json` :

```
"paths": { "@/*":["libs/my-lib/src/*"]}
``` 
but I got an error saying `Cannot resolve module @/lib/test/index.tsx` from compiler
I don't want to import module from relative path e.g. `../../../test`. How do I overwrite the path alias in lib folder

**Comment by michelepatrassi** [comment] 2022-08-09 13:07
May be helpful: **tsconfig paths in rollup don't work for JS file**. 

To solve, just convert your JS files to TS

**Comment by melalj** [comment] 2022-08-16 23:12
I'm facing a similar issue with my current setup:
```
apps
  | - my-app
libs
  | - common
  | - my-client
```

The libs are being published on npm after the deployment under the names of `@my-org/my-client` and `@my-org/common`, while I'm defining the following path alias (on `tsconfig.conf`) to use them directly on `my-app` code:
```
"paths": {
      "@my-org/my-client": ["libs/my-client/src/index.ts"],
      "@my-org/common": ["libs/common/src/index.ts"]
}
```

The issue is that `my-app` is using an external package `another-external-package` that depends on `@my-org/common` (it's importing with its published version).

When I import `@my-org/common` on `my-app`, it seems that it's picking up the peer dependency `@my-org/common` (from `another-external-package`) and not from the alias that is defined on `tsconfig.conf`.
This happens only when we build for production but not in the dev environment.

Any idea on how to tell nx/tsc to pick the library instead of the published package?

@linbudu599 @TheMeteoRain

**Comment by bezvrednyy** [comment] 2022-08-21 19:41
What about `@nrwl/next:build`? It looks like there's a problem with `paths aliases` there too. I was able to get typescript to make the path see by renaming `tsconfig.base.json` to `tsconfig.json`. But when I try run `nx build someapp`, I get _Error: PropertyNameExpected in C:\Repositories\repo\tsconfig.json at position 576_

**Comment by budiadiono** [comment] 2022-12-18 15:12
I'm having similar issue, but it's on **@nrwl/webpack:webpack**

Here is my paths alias in `tsconfig.base.json`:

```
"paths": {
      "@bf/auth": ["libs/bf-auth/src/index.ts"],
      "@bf/database": ["libs/bf-database/src/index.ts"],
      "@myorg/core/api": ["libs/core/core-api/src/index.ts"]
}
```

After build, the "@bf/auth" and  "@bf/database" always recognized as external packages. Customizing webpack config using `tsconfig-paths-webpack-plugin` did not work for me either.

Then tried to make all aliases with a same prefix (my root package.json name is "@myorg") like these:

```
"paths": {
      "@myorg/auth": ["libs/bf-auth/src/index.ts"],
      "@myorg/database": ["libs/bf-database/src/index.ts"],
      "@myorg/core/api": ["libs/core/core-api/src/index.ts"]
 }
```

surprisingly it's working! 

So I tried another workaround my workaround by put slash right after `@` sign like this:

```
"paths": {
      "@/bf/auth": ["libs/bf-auth/src/index.ts"],
      "@/bf/database": ["libs/bf-database/src/index.ts"],
      "@myorg/core/api": ["libs/core/core-api/src/index.ts"]
}
```

and it's working too!

But still I think this is not a good solution -- just in case one day I want to publish @bf/auth and @bf/database on npm, I should only need to rid of the `paths` from tsconfig and add those packages to my projects.

**Comment by lafbelmonte** [comment] 2023-02-17 01:54
If you're using [nrwl/js:tsc](https://nx.dev/packages/js/executors/tsc), you can use [typescript-transform-paths](https://github.com/LeDDGroup/typescript-transform-paths) and pass it in transformers parameter.
E.g. `project.json`
```
...
  "targets": {
    "build": {
      "executor": "@nrwl/js:tsc",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/e-api",
        "main": "apps/e-api/src/index.ts",
        "tsConfig": "apps/e-api/tsconfig.lib.json",
        "assets": ["apps/e-api/*.md"],
        "transformers": [
          { 
            "name": "typescript-transform-paths/nx-transformer"
          }
        ]
      }
    },
...
```

**Comment by quicksilverr** [comment] 2023-04-27 07:57
Thanks @lafbelmonte, This solution [works](https://github.com/nrwl/nx/issues/7123#issuecomment-1433984949).

**Comment by mandarini** [comment] 2023-10-24 12:54
Hello all! Thank you for digging into this issue and coming up with solutions! I will be closing this issue now for two reasons:
1. It seems that there are working workarounds
2. The initial report is outdated, and lots has changed since then.

I hope that these comments help whoever may come up with something similar, but if you do find an issue that you think is not yet covered by Nx natively, please open a new issue on Nx, and tag me, and I will look into it!

Again, THANK you everyone!!

**Closed by mandarini** 2023-10-24 12:54 UTC
Labels: type: bug, scope: node
