### ISSUE TITLE
Inconsistency in the path of tsconfig when generating a publishable library

### ISSUE THREAD

**Issue by kristofdegrave** [nrwl/nx#2164] opened 2019-12-09 08:33 UTC
_[Please make sure you have read the submission guidelines before posting an issue](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md#-submitting-issue)_

# Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation (nx.dev) and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to React, Angular or any dependency)

## Expected Behavior

When running the following command `ng @nrwl/angular:library test -- publishable --directory=core`, I would expect the following results:

angular.json
```
{
  "version": 1,
  "projects": {
        ....
      "core-test": {
         "projectType": "library",
         "root": "libs/core/test",
         "sourceRoot": "libs/core/test/src",
         "prefix": "myLib",
         ...
     }
  }
}
```
tsconfig.json
```
{
  ...
  "paths": {
    "@myLib/core-test": ["libs/core/test/src/index.ts"]
  }
}
```
libs/shared/test/package.json
```
{
  "name": "@myLib/core-test",
  "version": "0.0.1",
  ...
}
```

## Current Behavior

When running the following command `ng @nrwl/angular:library test -- publishable --directory=core`, I get the following result:

tsconfig.json
```
{
  ...
  "paths": {
    "@myLib/core/test": ["libs/core/test/src/index.ts"]
  }
}
```

## Failure Information (for bugs)

The path generated and added in the paths variable of the tsconfig.json file, isn't consistent with the npm naming. This way the import becomes dependent on the way I handle the package. If I would use it as an npm package, I would need to reference `@myLib/core-test`, but if I use the same package as a local dependency I would need to reference `@myLib/core/test`. This means if I would move the package to an other repo in the future, I would need to change all the imports, or fix it in the paths variable 

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `npx create-nx-workspace@latest repro-workspace`
2. `ng @nrwl/angular:library test -- publishable --directory=core`

### Context

Please provide any relevant information about your setup:

  @nrwl/angular : 9.0.0-beta.3
  @nrwl/cli : 9.0.0-beta.3
  @nrwl/cypress : 9.0.0-beta.3
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.0.0-beta.3
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.0.0-beta.3
  @nrwl/web : Not Found
  @nrwl/workspace : 9.0.0-beta.3
  typescript : 3.6.4

  @angular/core: 9.0.0-rc.5

### Failure Logs

Please include any relevant log snippets or files here.

## Other

Any other relevant information that will help us help you.

This is more a CR, but it would be great to have control on the package name. Currently the name is the substitution of the the library name and the directory path. If it is a publishable package, it would be great to pass the lib name as an optional parameter.

**Comment by FrozenPandaz** [comment] 2019-12-10 15:46
Thanks for reporting this issue!

This is complex because `npm` package names cannot contain more than 1 `/` other than the one after the scope.

Closing this as a duplicate of https://github.com/nrwl/nx/issues/930 since it has more context.

**Closed by FrozenPandaz** 2019-12-10 15:46 UTC

**Comment by kristofdegrave** [comment] 2019-12-12 07:40
@FrozenPandaz I have taken a look at the other issue, but that is about the fact that you should map to the dist folder or not. This is not the thing I want to discuss. 

What I originally requested is that the path in the tsconfig should be the same as the one in the npm package (with the dashes). So you get the following:
````
{
  ...
  "paths": {
    "@myLib/core-test": ["libs/core/test/src/index.ts"]
  }
}
```
I would like to have this, to make refactoring the publishable packages into a seperate repo easier. In that case I can just leave `import {} from '@myLib/core-test'` in my code. In the current scenario I have to replace  `import {} from '@myLib/core/test'` with  `import {} from '@myLib/core-test'` if I do the refactoring.

So my concrete question was, if you create a library with the `--publishable` option, can the path mapping in the tsconfig.json be:
````
{
  ...
  "paths": {
    "@myLib/core-test": ["libs/core/test/src/index.ts"]
  }
}
```
Maybe this is more a Feature Request than a Bug :)
