### ISSUE TITLE
`@nrwl/angular` incorrectly appearing as peerDependency in published `package.json`

### ISSUE THREAD

**Issue by MysticEarth** [nrwl/nx#10529] opened 2022-05-31 11:13 UTC
## Current Behavior
When publishing our UI library the `package.json` in dist includes an incorrect peerDependency to `@nrwl/angular`.

```json
{
  "peerDependencies": {
    "@angular/core": "^13.0.0 || ^14.0.0-0",
    "@angular/common": "^13.0.0 || ^14.0.0-0",
    "@angular/material": "^13.0.0 || ^14.0.0-0",
    "@angular/cdk": "^13.0.0 || ^14.0.0-0",
    "@angular/router": "^13.0.0 || ^14.0.0-0",
    "rxjs": "^6.5.3 || ^7.4.0",
    "@angular/platform-browser": "13.3.3",
    "@angular/forms": "13.3.3",
    "@nrwl/angular": "13.10.3", // <!-- should not be here
  },
}
```

We are using Tailwind CSS in the UI library with the config below, which might explain the dependency:
```js
const { join } = require('path');

const { createGlobPatternsForDependencies } = require('@nrwl/angular/tailwind');
//                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

const tailwindConfigPreset = require('../styling/tailwind.config.js');

module.exports = {
  presets: [tailwindConfigPreset],
  content: [join(__dirname, 'src/**/!(*.stories|*.spec).{ts,html}'), ...createGlobPatternsForDependencies(__dirname)],
};
```

## Expected Behavior
We expect the peerDependency from `tailwind.config.js` not to be in the distributable package.json.

## Steps to Reproduce
- Create a new NX workspace
- Add a lib (or app, same behaviour) and add Tailwind
- Publish the lib/app and check the `package.json`

### Environment

```bash
>  NX   Report complete - copy this into the issue template

   Node : 16.13.1
   OS   : darwin x64
   npm  : 8.1.2
   
   nx : 13.10.3
   @nrwl/angular : 13.10.3
   @nrwl/cypress : 13.10.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.3
   @nrwl/eslint-plugin-nx : 13.10.3
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.3
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.3
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.3
   typescript : 4.6.3
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @compodoc/compodoc: 1.1.19
         @jscutlery/semver: 2.22.0
         @nx-plus/docusaurus: 13.0.0
         @storybook/angular: 6.4.22
         @testing-library/angular: 11.0.4
         @twittwer/compodoc: 1.7.0
```

**Comment by AgentEnder** [comment] 2022-05-31 15:08
You should be able to add @nrwl/angular to the devDependencies of the package.json in your library to have Nx remove it from the generated output

**Comment by MysticEarth** [comment] 2022-05-31 18:27
That seems to fix the issue. But, is this intended behaviour that it should manually be added to `devDependencies`?

**Comment by AgentEnder** [comment] 2022-05-31 18:40
No, not necessarily. @nrwl/angular is different from other nx plugins in that it also provides some runtime utilities (for NgRx).

When generating package.json file, Nx looks at the dep-graph and sees the import to @nrwl/angular, but doesn't know if what you are importing is run-time or dev-time. To better understand this, Nx looks at where the dependency is located. If the dep is in devDependencies, we know it shouldn't be propagated to end-users. If it's in dependencies, it's more likely that it is needed.

**Comment by leosvelperez** [comment] 2022-06-01 10:34
I'm going to close this since it's working as intended. As @AgentEnder explained [here](https://github.com/nrwl/nx/issues/10529#issuecomment-1142519460), Nx relies on where the dependency is located in the root `package.json`.

You can move the offending package to `devDependencies` if that makes sense in your case or you could also opt-out of the automatic `package.json` generation if you need to have more control over it by setting `updateBuildableProjectDepsInPackageJson: false` in your target configuration.

**Closed by leosvelperez** 2022-06-01 10:34 UTC
Labels: type: bug, scope: angular
