### ISSUE TITLE
NX  ERROR spawn E2BIG  when building

### ISSUE THREAD

**Issue by atomicrobokid** [nrwl/nx#8684] opened 2022-01-25 10:55 UTC
## Current Behavior
When running `nx build-storybook app-name` the build fails with the error: `NX   ERROR  spawn E2BIG`

## Steps to Reproduce
New nx angular app, version 13.4.6, build storybook as per instructions

Similar issue: https://github.com/nrwl/nx/issues/8646

This issue may not be prioritized if details are not provided to help us reproduce the issue.

This happens both locally and in CI environment

### Failure Logs
```
#15 0.858 > nx build-storybook test-app
#15 0.858 
#15 3.099 
#15 3.099 >  NX   ERROR  spawn E2BIG
#15 3.100 
#15 3.100 
#15 ERROR: executor failed running [/bin/sh -c npm run storybook-build]: exit code: 1
```
### Environment
local & ci

---
Downgrading all packages from `13.4.6` to `13.4.4` fixes it, so it is something that was introduced in those patch versions. 

Similar issue raised by someone else trying to test, downgrading also fixed it for them so is not an isolated incident:
https://github.com/nrwl/nx/issues/8646

**Comment by yharaskrik** [comment] 2022-01-26 01:40
I am seeing this as well. Just on the `yarn nx format:write` command instead.

**Comment by FrozenPandaz** [comment] 2022-01-29 00:40
https://github.com/nrwl/nx/issues/8646 is likely a real issue. I'm going to close this issue as a duplicate of that one as it has more details. Thanks for raising it again!

**Closed by FrozenPandaz** 2022-01-29 00:40 UTC
Labels: type: bug
