### ISSUE TITLE
e2e not using cached builds

### ISSUE THREAD

**Issue by stramel** [nrwl/nx#3604] opened 2020-08-25 16:17 UTC
## Current Behavior

When running the production e2e tests, it currently builds/rebuilds the application every time the command is invoked.

## Expected Behavior

When running the production e2e tests, I would expect it to be able to use the cached / previously built application unless the `skip-nx-cache` flag is passed or the caching is disabled for build.

## Steps to Reproduce

- Run build
- Run build (Observe cached application build used)
- Run e2e with prod flag (Observe re-built application)
- Run serve production build (Observe re-built application)

### Environment

```
❯ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : 9.1.2
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : 9.1.2
  @nrwl/nest : Not Found
  @nrwl/next : 9.1.2
  @nrwl/node : Not Found
  @nrwl/react : 9.1.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : 9.1.2
  @nrwl/workspace : 9.1.2
  typescript : 3.9.3
```

**Comment by webberwang** [comment] 2020-08-30 19:47
Do you have the build output log showing that it doesn't pick up cache?

**Comment by vsavkin** [comment] 2020-09-03 15:50
Hi there!

Thanks for submitting the issue.

The cypress and protractor builders invoke "serve". The implementation of "serve" provided by core plugins isn't cacheable. It's possible to make it cacheable by doing something like this https://github.com/nrwl/nx-incremental-large-repo, but it has other tradeoffs.

To support it we need to replace webpack for development which is something we are looking into .

I'm going to close this as it works as intended.

**Closed by vsavkin** 2020-09-03 15:50 UTC
Labels: type: feature
