### ISSUE TITLE
Local executor changes not affects consumers

### ISSUE THREAD

**Issue by de-don** [nrwl/nx#27148] opened 2024-07-26 13:24 UTC
### Current Behavior

I have plugin with one executor, that adds target with this executor to some project.

If I change executor source code, none of caches invalidates, so I can't normally test my changes.

How could I add executor sources to list of inputs only for local development (not to ship it to library users).

### Expected Behavior

Source sode of executors automatically adds to inputs

### Steps to Reproduce

1. Create local executor
2. Use this executor in some target for project
3. Change executor code.
4. Check that result of target run will be fetched from cache.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node   : 18.18.2
OS     : darwin-arm64
npm    : 9.8.1

nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/playwright     : 19.5.1
@nx/plugin         : 19.5.1
@nx/storybook      : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
nx-cloud           : 19.0.0
typescript         : 5.1.6
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@front/nx-i18n
@front/nx-linters
@front/nx-css-utils
---------------------------------------
Community plugins:
@front/angular-builder : 16.2.0
@storybook/angular     : 7.6.20
nx-stylelint           : 17.1.5
---------------------------------------
Local workspace plugins:
         @front/nx-css-utils
         @front/nx-linters
         @front/nx-i18n
         @mono/generators
         @mono/executors
         @mono/utils
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by de-don** [comment] 2024-07-26 13:26
I found my old issue about this https://github.com/nrwl/nx/issues/20980

I solved this with implicitDependencies, but now I am publishing this code, so this solution looks wrong.

**Comment by FrozenPandaz** [comment] 2024-07-26 17:31
This is a duplicate of https://github.com/nrwl/nx/issues/18540. Please track that issue for more information.

**Closed by FrozenPandaz** 2024-07-26 17:31 UTC
Labels: type: bug
