### ISSUE TITLE
Resource integrity settings blocks downloading resources

### ISSUE THREAD

**Issue by zmara** [nrwl/nx#20487] opened 2023-11-30 07:02 UTC
### Current Behavior

Setting subresourceIntegrity: true in project.json results to generating resourceIntegrity attributes but those lead to errors below

```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/styles.css' with computed SHA-384 integrity 'f0aME4iVaWgxQuL2LvpOwlAjE1726oDdO4e9hasZgwo3EfhBj/q1HvdCHUaad4DR'. The resource has been blocked.
:4200/:91 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/runtime.js' with computed SHA-384 integrity 'BomQKl7d9Kuc9xuS5Cxh6TG06erSpJVAMdJcv3+PK4PsoOPj7VLGyUZ8/q/pR8xI'. The resource has been blocked.
:4200/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/scripts.js' with computed SHA-384 integrity 'KifPd8D9x/rMGhFqKKk1o7Guhs84f7NKzU6Df/h0g8yyhI19w+fRJ8TAQQB1qbY1'. The resource has been blocked.
:4200/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/polyfills.js' with computed SHA-384 integrity 'fuAP5sEfaSqEQZ9vlK/98occFXpDNSM7mjucKZPY5dN21WA40fnAGdKORhcpo5p1'. The resource has been blocked.
:4200/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/styles.js' with computed SHA-384 integrity 'VtelYtnat4f3z5ArUbgECtwy0y1hcfLcRwzf+kC/9H0DgXEwwRWUockyGZOhRQoN'. The resource has been blocked.
:4200/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/main.js' with computed SHA-384 integrity '7o2lFscWc3ThPF8GGbVjZhNWa2Mx5384SNs6fDVPxAC6J/rCniEMzp3cb0Cs4kjd'. The resource has been blocked.
:4200/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:4200/vendor.js' with computed SHA-384 integrity 'GWqLOlnnYp0U3eKi40so6Ank/S8KAjiNK/wpf6qjaTtqCB6UyW2l6lFUHMFlz3Es'. The resource has been blocked.
```

Example of generated integrity:
```
<script src="runtime.js" type="module" crossorigin="anonymous" integrity="sha384-OrwYDyxM716nV8UznBVyoKEyN8UbE3IivHmNZ006nukLZHAJYDj07kSyH78zvC2V"></script>
<script src="polyfills.js" type="module" crossorigin="anonymous" integrity="sha384-DjMu8ZS+tmYbn3vUWtWZuotsr4h6c4blbK9/KZm3Z7uuHCafieOj7ySueXKLdm7v"></script>
<script src="styles.js" defer="" crossorigin="anonymous" integrity="sha384-SdmF/cEpwCYKIfe5VIvG4ghoBgzShlFb3ALYkY6RXjThRj3vNoqgH4cDal3WeyFH"></script>
<script src="scripts.js" defer="" crossorigin="anonymous" integrity="sha384-RnyaDRb3YeOXWcagiLWRyloGj7OakyreyfeAukIIIUzwyX5w0gChCMmJDchb4eP5"></script>
<script src="vendor.js" type="module" crossorigin="anonymous" integrity="sha384-XI++GyGAi/Ri1itcbmCrFeSz1DmRer9YsmyPyqXT3DbNzKxOwNvVoxDFhLYbx/2i"></script>
<script src="main.js" type="module" crossorigin="anonymous" integrity="sha384-1kbRc7PPe1gtZmcHOFQYaE4tcTeTqdivUnqDL1iX3o3fqcj02KO4V20KlF5lHo9I"></script>

```
### Expected Behavior

By setting subresourceIntegrity: true in project.json should generate integrity attribute and application resources should be downloaded fine.

### Steps to Reproduce

1. Create NRWL NX project with dependencies nx 16.4.3, angular 16.1.3
2. Set subresourceIntegrity: true in project.json
3. npx nx serve the application

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.16.1
   OS     : win32-x64
   npm    : 9.5.1
   
   nx                 : 16.4.3
   @nx/js             : 16.4.3
   @nx/jest           : 16.2.2
   @nrwl/linter       : 16.4.3
   @nx/workspace      : 16.4.3
   @nx/angular        : 16.4.3
   @nx/cypress        : 16.4.3
   @nx/devkit         : 16.4.3
   @nx/eslint-plugin  : 16.4.3
   @nrwl/tao          : 16.4.3
   @nx/webpack        : 16.4.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc   : 1.1.21
   @ngneat/transloco    : 4.3.0
   @ngrx/data           : 16.0.1
   @ngrx/effects        : 16.0.1
   @ngrx/entity         : 16.0.1
   @ngrx/router-store   : 16.0.1
   @ngrx/schematics     : 16.0.1
   @ngrx/store          : 16.0.1
   @ngrx/store-devtools : 16.0.1
   @nrwl/builders       : 7.8.7
   @rx-angular/cdk      : 16.0.0
   angular-calendar     : 0.31.0
   ---------------------------------------
```

### Package Manager Version

npm version 9.5.1

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment] 2024-02-12 11:57
Thanks for reporting this!

This is not caused by Nx. The issue is reproducible in an Angular CLI workspace (no Nx). Setting `sourceMap: false` in the `development` configuration of your build target fixes it, but having `optimization: true` (or not set to `false`) breaks it (production configuration).

I'm going to close the issue since it's not caused by Nx and comes from the upstream Angular CLI dep. Please raise an issue in the Angular CLI repo if you feel the behavior is wrong.

**Closed by leosvelperez** 2024-02-12 11:57 UTC
Labels: type: bug, scope: angular
