### ISSUE TITLE
 Nx failed to create a workspace if global git user and email config is not set

### ISSUE THREAD

**Issue by bosycom** [nrwl/nx#8183] opened 2021-12-15 09:55 UTC
## Current Behavior
Nx fails to create a workspace if git global user is not set, quitting with `NX   ERROR  Nx failed to create a workspace.  Exit code: 1` on console.

## Expected Behavior
Nx will not exit with error message

## Impact of bug
Low impact, because fix is mentioned in logs, but fixing this issue would increase dev experience.

## Steps to Reproduce
1. Clear/Reset your global git config for user and email
2. Create a nx workspace such as `npx create-nx-workspace@latest stores --preset=react`

### Failure Logs
```
*** Please tell me who you are.
Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'redacted@redacted.(none)')
128
```

**Comment by Matrix89** [comment] 2021-12-18 16:53
Had the same issue, since nx creates a new git repository on init, I think It shouldn't be too unresonable to prompt the user to fill out their global config or if they don't want to, prompt for the repository specific email/username.

**Comment by mandarini** [comment] 2021-12-20 12:55
Hi there @bosycom ! Thanks for filing an issue. I agree with @Matrix89 that this is not a bug, since we're initialising a git repo. I will close this for now, and let me know if you think it should reopen, but maybe as a feature request?

**Comment by bothema** [comment] 2021-12-22 22:15
@mandarini agrees with @Matrix89 that this issue is not a bug, but I cannot see anywhere in @Matrix89 comment that @Matrix89  would not consider this a bug, so I wonder what this "agree to" is based on. This issue is returning an error and so it strongly strikes me as a bug, but in the end I don't care much. Just thought the developers would be interested in improving/fixing their product.

**Comment by mandarini** [comment] 2021-12-23 11:37
Hi @bothema ! Being kind does not hurt :) I am trying my best to help our users make the best out of our product. Thank you for the constructive feedback.

**Closed** 2021-12-23 17:10 UTC
Labels: type: bug
