### ISSUE TITLE
Problem with BaseClassComponent

### ISSUE THREAD

**Issue by morbargig** [nrwl/nx#11910] opened 2022-09-07 10:07 UTC
## Current Behavior

when I was update nx and angular from nx 14.5.8 => 14.6.5
and angular from 14.1.1 => 14.2.0

base component cause errors
on Lazy Chunk Load 
```typescript 
import { Routes } from '@angular/router';

export const ROUTES: Routes = [
  {
    path: '',
    title: 'Change CC',
    loadChildren: () =>
      import('./modules/change-credit-card/change-credit-card.module').then(
        (m) => m.ChangeCreditCardModule
      ),
  },
];
```

base component exam
this sit as an abstract directive on some angular lib

```typescript 
import {
  Directive,
  HostListener,
  Input,
  OnDestroy,
  OnInit,
} from '@angular/core';
import { AbstractControl, FormArray, FormGroup } from '@angular/forms';
import { debounceTime, takeWhile } from 'rxjs/operators';
import {
  BaseFieldData,
  Field,
  FieldConfigObj,
  FiledParentControl,
} from '../interfaces/field-config';

@Directive()
export abstract class BaseFieldComponentDirective<
  T = any,
  D extends BaseFieldData<T, K> = BaseFieldData<T>,
  K extends keyof { [key in keyof T]: any } = keyof { [key in keyof T]: any },
  A extends AbstractControl = AbstractControl,
  P extends FormGroup | FormArray = FormGroup | FormArray,
  G extends FiledParentControl<T, P, A> = FiledParentControl<T, P, A>
> implements Field<T, D, K, A, P, G>, OnDestroy, OnInit
{
  @Input() public config: FieldConfigObj<T, D, K>;
  @Input() public parentForm: G;
  @Input() public id: string;
  protected isActive = true;

  protected _control: A;
  public get control(): A {
    return this._control;
  }
  @Input() public set control(v: A) {
    this._control = v;
  }

  public get data(): D {
    return this.config.data;
  }

  @HostListener('click') private onClick() {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-extra-non-null-assertion
    this?.config?.onClick!?.(this.control);
  }

  public ngOnInit(): void {
    if (this.config?.onChange) {
      this.control?.valueChanges
        ?.pipe(
          takeWhile(() => this.isActive),
          debounceTime(100)
        )
        .subscribe((x) => {
          this.config?.onChange?.({
            currentValue: x,
            control: this.control,
          });
        });
    }
  }

  public ngOnDestroy() {
    this.isActive = false;
  }
}
```

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/51287453/188849882-5539bca0-e707-41be-a2a5-61f9adcc9288.png">

some error appears on angular storybook, but this is less important for me at Last

## Expected Behavior

I want the BaseComponent to keep working as expected, this is a bug as I can tell.
If there is any other solution, I will do it also.

## Steps to Reproduce

I think there is some problem when I use the base component
like he can realize it like I should declare about it somewhere, but I can because it is an abstract class
and it needs to use angular features, so I add directive decorator

https://github.com/morbargig/nx

After this command
```base
npx nx migrate latest
```
Should be the above errors

**Comment by Coly010** [comment] 2022-09-13 08:49
Can you provide a minimal repository that showcases this issue? It's hard to know where something could be going wrong without being able to investigate and debug the issue. 

Thanks!

**Comment by morbargig** [comment] 2022-09-15 07:11
> Can you provide a minimal repository that showcases this issue? It's hard to know where something could be going wrong without being able to investigate and debug the issue.
> 
> Thanks!

Added Thanks

**Comment by leosvelperez** [comment] 2022-09-16 10:51
hey @morbargig! The provided repo has `@nrwl/*` packages on `14.1.9` and Angular packages on `13.3.x` which doesn't correlate with the provided info in the OP:

> when I was update nx and angular from nx 14.5.8 => 14.6.5
> and angular from 14.1.1 => 14.2.0

That said, the error is a legitimate one and it arises because you have circular dependencies between your files:

- form-array.component.ts => base-field.directive.ts => field-config.ts => base-field.directive.ts
- There are other combinations of these circular deps between those files (and there might be other circular deps, I didn't check everything).

Please note, that this is not an Nx issue. The error is not thrown by Nx nor caused by Nx setup. This is a runtime error. The runtime of your application is ultimately generated by the Angular compiler and regardless of using Nx or the Angular CLI, you'd get the same error.

For your particular use case, I solved it in your repo by changing:

```ts
// base-field.directive.ts
...
import {
  BaseFieldData,
  Field,
  FieldConfigObj,
  FiledParentControl,
} from '../interfaces/field-config';
...
```

To:

```ts
// base-field.directive.ts
...
import type {
  BaseFieldData,
  Field,
  FieldConfigObj,
  FiledParentControl,
} from '../interfaces/field-config';
...
```

For some reason, the Angular compiler is not stripping the import to `../interfaces/field-config` from the runtime code and that causes the circular dependency error to arise in your runtime app. By adding the `type` modifier you help the compiler to know that's only type, so it's not needed by your runtime.

That said, it's always best to remove any sort of circular dep to avoid potential issues like this one.

I'm closing this issue since it's not a problem caused by Nx. Feel free to reply if you still think there's an issue with Nx.

**Closed by leosvelperez** 2022-09-16 10:51 UTC
Labels: type: bug, blocked: repro needed, scope: angular

**Comment by morbargig** [comment] 2022-09-16 16:48
I didn't can tell, what cause the problem but look like you are right that it's an angular problem.
I will check your solution and will update if it works in Sunday.

Yes the repo is a little different from the description 
Because this is the company property and the repo I send is the POC that us nothings to do with the business.

Thank you and thanks for teaching me a new thing "import type"

**Comment by morbargig** [comment] 2022-09-16 16:50
Do you might thing this is angular bug who might be fixed?

Should I open a bug?
Because in the previous version it works in the some circular dependency code.
