### ISSUE TITLE
update @typescript-eslint/* to v6

### ISSUE THREAD

**Issue by robertIsaac** [nrwl/nx#19922] opened 2023-10-29 15:36 UTC
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))
Actually I have a branch for it, but I couldn't complete it, there are test failing
https://github.com/robertIsaac/nx/tree/update-typescript-eslint-to-v6

## Description
update @typescript-eslint to v6

## Motivation
we can use the new features

## Suggested Implementation
the problem in updating it is this issue
https://github.com/typescript-eslint/typescript-eslint/issues/7284
I tried to change the tsconfig as suggested, but there are a lot of unit test failing so I gave up since I don't understand why they are failing

## Alternate Implementations
to allow peer dependency to be v6 while nx uses v5
I tested it in one project and it's working fine

**Comment by AgentEnder** [comment] 2023-10-31 21:41
Closing as a duplicate of #18641

**Closed by AgentEnder** 2023-10-31 21:41 UTC
Labels: type: feature, scope: linter
