### ISSUE TITLE
Cyclic build when serving incremental builds

### ISSUE THREAD

**Issue by evgeniyefimov** [nrwl/nx#4497] opened 2021-01-11 11:46 UTC
## Current Behavior

For some reasons we have to build our application inside app's www folder. So our output path is like (apps/test-app/www) When the app is served with incremental build the changes put to www folder and build is run again.

## Expected Behavior

As I understand the issue is that builder watches the whole folder and built files run process again and again. Settings to ignore specific folders will fix the issue.

## Steps to Reproduce

Repo to reproduce is here: [https://github.com/evgeniyefimov/cyclic-nx-serve](https://github.com/evgeniyefimov/cyclic-nx-serve). Just run `nx serve`.

### Environment

  Node : 12.19.0
  OS   : win32 x64
  npm  : 6.14.9

  nx : Not Found
  @nrwl/angular : 11.1.1
  @nrwl/cli : 11.1.1
  @nrwl/cypress : 11.1.1
  @nrwl/devkit : 11.1.1
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.1.1
  @nrwl/linter : 11.1.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.1.1
  @nrwl/web : 11.1.1
  @nrwl/workspace : 11.1.1
  typescript : 4.0.5

**Comment by evgeniyefimov** [comment] 2021-01-12 12:58
I think it would be great if incremental serve ignores files from .gitignore.

**Comment by vsavkin** [comment] 2021-02-11 17:02
Hi there!

Thanks for submitting the issue. The build ignores files in .gitignore. If I add `/apps/test-app/www` to the gitignore file in your repro, it no longer results in a cyclic build. 

Do you still have the issue if you add `/apps/test-app/www` to the gitignore file?

**Comment by evgeniyefimov** [comment] 2021-02-15 11:52
Hi, @vsavkin!

Thank you for your response. Yes, `/apps/test-app/www` pattern works well. But if I use `www/` pattern to ignore all files in any directory named www the cyclic build is still there. Is it ok?

**Comment by vsavkin** [comment] 2021-02-22 18:39
@evgeniyefimov I think the issue is that www/ will ignore every file in www/ but I believe the whole dir is being recreated, so the hash of the task is the same, but node-watch still detects an update. If you change it from `www/` to `www`, it will fix the issue.

**Comment by vsavkin** [comment] 2021-03-08 15:19
I'm going to close this. If your issue isn't fixed by the comment above, please reopen it and I'll take a look.

Thank you!

**Closed by vsavkin** 2021-03-08 15:19 UTC
Labels: blocked: more info needed, scope: angular, type: bug
