### ISSUE TITLE
Migration from 15.3 to 16 with nx migrate latest fails

### ISSUE THREAD

**Issue by abf7d** [nrwl/nx#16835] opened 2023-05-06 16:10 UTC
### Current Behavior

I have an Angular Nx 15.3 project and I'm trying to upgrade. I ran: `nx migrate latest` then ran `npm install`.
I get the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: critical-pass@0.0.0
npm ERR! Found: typescript@5.0.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"5.0.4" from the root project
npm ERR!   peer typescript@">=4.4" from jest-preset-angular@13.0.0
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.8.2 <4.9" from @angular/compiler-cli@15.0.4
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~15.0.0" from the root project
npm ERR!   peer @angular/compiler-cli@">=13.0.0 <16.0.0" from jest-preset-angular@13.0.0
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"13.0.0" from the root project
npm ERR!   1 more (@angular-devkit/build-angular)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\afrie\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

### Expected Behavior

I expect the packages to install without any conflicts so I can continue to migrate to version 16.

### GitHub Repo

https://github.com/abf7d/critical-pass/tree/cypress-tests

### Steps to Reproduce

1. Clone the repo
2. run `npm install`
3. run `nx migrate latest`
4. run `npm install`

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2

   nx : 15.3.0
   @nrwl/angular : 15.3.0
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: critical-pass@0.0.0
npm ERR! Found: typescript@5.0.4
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"5.0.4" from the root project
npm ERR!   peer typescript@">=4.4" from jest-preset-angular@13.0.0
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=4.8.2 <4.9" from @angular/compiler-cli@15.0.4
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~15.0.0" from the root project
npm ERR!   peer @angular/compiler-cli@">=13.0.0 <16.0.0" from jest-preset-angular@13.0.0
npm ERR!   node_modules/jest-preset-angular
npm ERR!     dev jest-preset-angular@"13.0.0" from the root project
npm ERR!   1 more (@angular-devkit/build-angular)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\afrie\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```
```


### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by ddubrava** [comment] 2023-05-07 16:30
Hey! I have the same question: why does `nx migrate latest` ignore `@angular/core packages`? I found an issue where it is said that `nx migrate latest` should update `@angular/core packages` (https://github.com/nrwl/nx/issues/5648), but I also found another issue where it is said that it shouldn't (https://github.com/nrwl/nx/issues/4632). Can you provide some information on how to migrate an Angular workspace from version 15 to version 16? 

If I run `nx migrate latest` and then run `nx migrate @angular/core`, it won't update all Angular packages, such as `@angular/cli` and `@angular-devkit/core`.

**Comment by leosvelperez** [comment] 2023-05-08 08:29
Thanks for reporting this!

The root cause of this issue is the same as https://github.com/nrwl/nx/issues/16794, and it'll be resolved in https://github.com/nrwl/nx/pull/16852. I'm going to close this as a duplicate. Please monitor the other issue to know when it's fixed.

In the meantime, if you can't wait, you could run `npm install --legacy-peer-deps` as a workaround.

**Closed by leosvelperez** 2023-05-08 08:29 UTC
Labels: type: bug
