### ISSUE TITLE
be able to extend schema.json

### ISSUE THREAD

**Issue by dmitry-stepanenko** [nrwl/nx#16484] opened 2023-04-23 06:28 UTC
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

Sometimes there's a need to have generator to extend other generators. There're few even in nx repo, when generators are reused for specific purpose, e.g. host/remote generators for react and angular, that call `application` generator under the hood and use the same options as a base one. 

It creates an additional maintenance point when base generator is updated, as it's needed to always apply schema updates to all implementations and keep them in sync without any validations of the process.

## Suggested Implementation

I was thinking about the possibility to extend schema.json with a deep merge of properties field and an ability to omit some of them (might be handy if specific properties are set internally by derived generator)

**Comment by AgentEnder** [comment] 2023-04-24 15:41
We are looking at solutions for this, stay tuned 📺

**Comment by AgentEnder** [comment] 2023-04-28 14:10
Hey @dmitry-stepanenko! I'm going to close **_this_** issue out, because it is a duplicate of https://github.com/nrwl/nx/issues/10890. We'll track this there.

**Closed by AgentEnder** 2023-04-28 14:10 UTC
Labels: type: feature, scope: core
