### ISSUE TITLE
Cannot run ng cli in newly created workspace

### ISSUE THREAD

**Issue by eiswind** [nrwl/nx#15631] opened 2023-03-13 14:00 UTC
### Current Behavior

run

```
npx create-nx-workspace@latest --preset=angular-monorepo
``` 
cd into the new project

run
```
ng test appname
```

Fails with

```
Error: This command is not available when running the Angular CLI outside a workspace.
```

### Expected Behavior

ng should be working.

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 18.13.0
   OS   : linux x64
   npm  : 9.3.1
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/angular           : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
```

**Comment by leosvelperez** [comment] 2023-03-13 14:49
Thanks for reporting this!

We recently stopped patching the Angular CLI to redirect to Nx for new workspaces. Please run `nx test appname` in the example you mentioned.

All we were doing when patching the Angular CLI was precisely running `nx` instead of `ng`. Nx workspaces use the Nx CLI, not the Angular CLI and any new workspace should run any command with the Nx CLI directly.

I'm closing this since it's the expected behavior for new workspaces.

**Closed by leosvelperez** 2023-03-13 14:49 UTC
Labels: type: bug
