### ISSUE TITLE
Running `yarn nx migrate latest` when migrating from `v12.2.0` to `v12.3.1`

### ISSUE THREAD

**Issue by kmaraz** [nrwl/nx#5661] opened 2021-05-14 09:14 UTC
## Current Behavior

I run command `yarn nx migrate latest` and it fails with message:
```
project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: yarn
    at checkExecSyncError (node:child_process:690:11)
    at Object.execSync (node:child_process:727:15)
    at taoPath (project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:320:21)
    at Object.handler (project/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:89:19)
    at Object.runCommand project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (project/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (project/node_modules/@nrwl/cli/lib/init-local.js:26:79)
    at Object.<anonymous> (project/node_modules/@nrwl/cli/bin/nx.js:43:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5595,
  stdout: null,
  stderr: null
}
```

## Expected Behavior

Working migrations.

### Environment
I have tested it with LTS Node and with latest Node, previously on those version everything worked as expected.
yarn is in version 1.22.10

Everything stayed the same from the last migration with this command.

Thank you.

**Comment by saeidzebardast** [comment] 2021-05-14 09:37
Same problem on macOS.

nx 12.2.0
node 15.3.0
yarn 1.22.5

**Comment by leosvelperez** [comment] 2021-05-14 09:53
Thanks for reporting this!

Could you please check if it's the same issue as https://github.com/nrwl/nx/issues/5655?

**Comment by kmaraz** [comment] 2021-05-14 09:55
@leosvelperez it is not the same issue. For me even running `yarn nx migrate` ends with this error. So I am not even after the first step. In the issue #5655 it looks like the author of the issue was successful in the first few steps.

**Comment by leosvelperez** [comment] 2021-05-14 10:14
@kmaraz I see. From the error you shared, it seems to be failing on an installation step we run to grab the latest version of the cli to run the migration. Unfortunately, I don't have enough info to know why that happens, I can't reproduce it myself. Would you be able to create a repro repo and share the results of running `yarn nx report`?

**Comment by kmaraz** [comment] 2021-05-14 10:23
@leosvelperez 
```
 yarn nx report
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 15.12.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 12.2.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

Done in 0.25s.
```

**Comment by leosvelperez** [comment] 2021-05-14 11:03
Thanks for sharing that. I was able to reproduce it and I found the issue to be that [Angular requires an active or maintenance LTS version of Node.js](https://angular.io/guide/setup-local#prerequisites). Angular packages effectively require Node version to be `^12.14.1 || ^14.0.0`, so the installation fails due to an incompatible Node engine since you have 15.12.0.

**Comment by leosvelperez** [comment] 2021-05-14 11:12
Closing as this is not an Nx issue. If you still think it's, please feel free to reopen this issue.

**Closed by leosvelperez** 2021-05-14 11:12 UTC
Labels: type: bug
