### ISSUE TITLE
DataPersistence.navigation is called while the parent component has not been activated yet.

### ISSUE THREAD

**Issue by sukei** [nrwl/nx#258] opened 2018-02-06 15:18 UTC
I have the following route configuration:

```typescript
const ROUTES = [
  {
    path: '',
    component: ContainerComponent,
    children: [
      { path: 'home', component: HomePageComponent }
    ],
    canActivate: [UserConnectedGuard]
  }
]
```

and the following effect:

```typescript
@Effect()
loadProtectedData = this._dataPersistence.navigation(HomePageComponent, {
  run: (route: ActivatedRouteSnapshot, state: AppState) => {
    return this._backend.getProtectedData().pipe(
      map((data) => ({
        type: 'DATA_LOADED',
        payload: data
      }))
    );
  },

  onError: (route: ActivatedRouteSnapshot, error) => {}
});
```

When navigating to `/home`, the effect `loadProtectedData` is called while the `UserConnectedGuard` has not yet been resolved. Is that the expected behavior or do I miss something? Does anybody have an idea about the ideal architecture to solve that kind of dependency?

BTW, great work so far! Thanks guys.

**Comment by vsavkin** [comment] 2018-03-09 16:05
`DataPersistence.navigation` relies on the NgRx router integration. The integration dispatches the navigation event before the preactivation phase (Guards and Resolvers) executes, and that's why you are seeing the issue. 

Could you submit an issue to https://github.com/ngrx/platform? I'll fix it in the NgRx repo.

Since the problem is caused by NgRx, I'm closing this issue.

**Closed by vsavkin** 2018-03-09 16:05 UTC
Labels: type: bug

**Comment by russoturisto** [comment] 2018-04-17 15:47
Just run into this issue.  I searched ngrx bugs bug couldn't find an entry there, opening one up using the information in this thread.

Thanks, :)

**Comment by zbarbuto** [comment] 2019-09-05 07:33
For anyone who happens to find this issue via Google (like me) the solution to stop this from happening is to update your `StoreRouterConnectingModule` as follows:


```ts
    StoreRouterConnectingModule.forRoot({
      navigationActionTiming: NavigationActionTiming.PostActivation
    })
```

This ensures that the `ROUTER_NAVIGATION` actions that Nx looks for are only dispatched after guards have resolved.
