### ISSUE TITLE
 nx reset --only-workspace-data (nx 9.2.x - 9.5.1) => Failed to reset the Nx workspace

### ISSUE THREAD

**Issue by omishyn-dm** [nrwl/nx#27006] opened 2024-07-19 13:39 UTC
### Current Behavior

Resetting:

- Workspace data directory

 NX   Failed to reset the Nx workspace.

Failed to clean up the workspace data directory.

### Expected Behavior

nx reset

 >  NX   Resetting the Nx workspace cache and stopping the Nx Daemon.

   This might take a few minutes.

 >  NX   Daemon Server - Stopped

 >  NX   Successfully reset the Nx workspace.

### Steps to Reproduce

1. create angular app with nx 9.1.2
2. nx build app
3. nx reset
4. nx migrate @nx@latest
5. nx build app
6. nx reset

### Nx Report

```shell
Node   : 20.11.1
OS     : win32-x64
npm    : 9.7.2

nx (global)        : 19.1.2
nx                 : 19.5.1
@nx/js             : 19.5.1
@nx/jest           : 19.5.1
@nx/linter         : 19.5.1
@nx/eslint         : 19.5.1
@nx/workspace      : 19.5.1
@nx/angular        : 19.5.1
@nx/cypress        : 19.5.1
@nx/devkit         : 19.5.1
@nx/eslint-plugin  : 19.5.1
@nx/plugin         : 19.5.1
@nrwl/tao          : 19.5.1
@nx/web            : 19.5.1
@nx/webpack        : 19.5.1
typescript         : 5.5.3
---------------------------------------
Community plugins:
@compodoc/compodoc   : 1.1.19
@ngneat/spectator    : 6.1.3
@ngrx/effects        : 18.0.1
@ngrx/router-store   : 18.0.1
@ngrx/schematics     : 18.0.1
@ngrx/store          : 18.0.1
@ngrx/store-devtools : 18.0.1
ngx-build-plus       : 16.0.0
---------------------------------------
⚠️ Unable to construct project graph.
EPERM: operation not permitted, open 'D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\.nx\workspace-data\d\daemon.log'
Error: EPERM: operation not permitted, open 'D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\.nx\workspace-data\d\daemon.log'
    at Object.writeFileSync (node:fs:2352:20)
    at createFileSync (D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\node_modules\nx\node_modules\fs-extra\lib\ensure\file.js:60:6)
    at DaemonClient.startInBackground (D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\node_modules\nx\src\daemon\client\client.js:363:39)
    at DaemonClient.sendMessageToDaemon (D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\node_modules\nx\src\daemon\client\client.js:316:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\proj_dm\3_adfree\00_18_nf\servers\gui\adfree\node_modules\nx\src\utils\promised-based-queue.js:19:21
```

### Package Manager Version

npm --version 9.7.2

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

nx 9.5.1
![no_security](https://github.com/user-attachments/assets/b511f387-2998-42f8-9955-f5b6be285af3)

nx 9.1.2
![with_security](https://github.com/user-attachments/assets/3c215fbf-8c70-4ada-8205-643a5217d0aa)

**Comment by LightBulbIdea** [comment] 2024-07-19 22:01
I am also experiencing this issue with Nx version 19.5.1. 

![image](https://github.com/user-attachments/assets/136f0fae-5e88-447e-af14-a84c0d3b9312)


After running that command in VS Code I can't do anything else but close VS Code via the Task Manager so I can start using npx commands again.

![image](https://github.com/user-attachments/assets/f3efd616-1f7a-4ff7-9c61-f38c8184a030)


This is what I get when I try open the file that is locking VS Code from doing anything.
![image](https://github.com/user-attachments/assets/d1cdd2ce-830d-4427-ad45-e594f11ca7ac)

I am an admin on this computer. So permissions is not an issue. I also have another Angular app running on Nx version 19.3.0 and I am not getting this error.

**Comment by dadfarjs** [comment] 2024-07-20 17:03
End task "Node.js" OR "VSCode" OR "Git" in Task Manager

**Comment by LightBulbIdea** [comment] 2024-07-20 17:51
@dadfarjs Is that the solution? Why is this happening in the first place?

To your point it works again after killing all VS Code instances via the Task Manager. But the second you run "npx nx reset" it glitches again.

**Comment by instantgis** [comment] 2024-07-21 09:23
I am also experiencing this issue with Nx 9.5.1. I tried downgrading to 9.5.0 the lowest version that supports Angular 18 and is not beta. Same thing. This is a show stopper for me just at the time that I wanted to migrate to Nx. My bad luck. Hopefully this gets resolved quickly.

**Comment by dadfarjs** [comment] 2024-07-21 13:21
> @dadfarjs Is that the solution? Why is this happening in the first place?
> 
> To your point, it works again after killing all VS Code instances via the Task Manager. But the second you run "npx nx reset" it glitches again.



If there is a problem in one of the programs of your project and the nx serve app-name command is executed. This information will be placed in the workspace.
At first, the problem in the program should be resolved and all node.js and vscode processes should be the end task.
Then run nx reset.
I haven't found a better way yet

You can use this command to see the program's problems in the terminal output:
nx g @nx/workspace:fix-configuration
OR
nx g @nx/workspace:fix-configuration --verbose

**Comment by dadfarjs** [comment] 2024-07-21 13:22
> @dadfarjs Is that the solution? Why is this happening in the first place?
> 
> To your point, it works again after killing all VS Code instances via the Task Manager. But the second you run "npx nx reset" it glitches again.




If there is a problem in one of the programs of your project and the "nx serve app-name" command is executed. This information will be placed in the workspace.
At first, the problem in the program should be resolved and all node.js and vscode processes should be the end task.
Then run "nx reset".
I haven't found a better way yet

You can use this command to see the program's problems in the terminal output:
nx g @nx/workspace:fix-configuration
OR
nx g @nx/workspace:fix-configuration --verbose

**Comment by omishyn-dm** [comment] 2024-07-22 08:34
I checked nx by versions
19.1.2, 19.2.3, 19.3.2, 19.4.4 - worked good
19.5.0, 19.5.1 - Failed to reset the Nx workspace

**Comment by Veskel01** [comment] 2024-07-22 09:21
I have the same problem. Unfortunately - this is another bug that makes work terribly unpleasant. It has been practically constant for some time. I hope Team NX will improve the flow of releasing new versions, because it is getting worse and worse

**Comment by MaxKless** [comment] 2024-07-24 09:12
Hey! It might be a bug in Nx Console, the vscode extension. Can you close all instances of vscode & make sure processes are dead. 
Then run an nx command & nx reset in the terminal.
Is the behaviour the same? Is the `daemon.log` file still locked?

**Comment by omishyn-dm** [comment] 2024-07-24 11:11
I checked witout any IDE, only from cmd

npx create-nx-workspace myng
cd myng
npx nx build
npx nx reset

![image](https://github.com/user-attachments/assets/95569a2d-009d-4e53-af54-f5b2c4bb3851)
![image](https://github.com/user-attachments/assets/cb5e9553-5470-45bc-a1ee-559891377d06)

Failed to reset the Nx workspace.

**Comment by omishyn-dm** [comment] 2024-07-24 11:13
![image](https://github.com/user-attachments/assets/97f4c26b-bfcd-4002-b4c2-0174cc65dee0)
nx report

 NX   Report complete - copy this into the issue template

Node   : 20.15.1
OS     : win32-x64
npm    : 10.7.0

nx (global)        : 19.4.4
nx                 : 19.5.2
@nx/js             : 19.5.2
@nx/jest           : 19.5.2
@nx/linter         : 19.5.2
@nx/eslint         : 19.5.2
@nx/workspace      : 19.5.2
@nx/angular        : 19.5.2
@nx/devkit         : 19.5.2
@nx/eslint-plugin  : 19.5.2
@nrwl/tao          : 19.5.2
@nx/web            : 19.5.2
@nx/webpack        : 19.5.2
typescript         : 5.5.4
---------------------------------------
⚠️ Unable to construct project graph.
EPERM: operation not permitted, open 'D:\proj_nx\myng\.nx\workspace-data\d\daemon.log'
Error: EPERM: operation not permitted, open 'D:\proj_nx\myng\.nx\workspace-data\d\daemon.log'
    at Object.writeFileSync (node:fs:2368:20)
    at createFileSync (D:\proj_nx\myng\node_modules\nx\node_modules\fs-extra\lib\ensure\file.js:60:6)
    at DaemonClient.startInBackground (D:\proj_nx\myng\node_modules\nx\src\daemon\client\client.js:363:39)
    at DaemonClient.sendMessageToDaemon (D:\proj_nx\myng\node_modules\nx\src\daemon\client\client.js:316:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\proj_nx\myng\node_modules\nx\src\utils\promised-based-queue.js:19:21

**Comment by mr-dugr** [comment] 2024-07-24 16:15
I did some digging in the codebase and PRs introduced between versions 19.4.4 (that works ok) and 19.5.0 and it seems that the problem is with this PR: https://github.com/nrwl/nx/pull/26888 
Don't see any description of that feature in the PR, but it enables plugin isolation by default in 19.5.0+ versions and causes the issue described by @omishyn-dm .

Also, checking Task Manager processes you can see that there are extra 4 node processes started and not killed after running e.g. `npx nx report` command (4x node.exe with cmd ...\node_modules\nx\src\project-graph\plugins\isolation\plugin-worker ...) and only killing them gives back access to debug.log file and running again 'npx nx reset' or any other nx command.

Setting env variable mentioned in the PR to false makes all work ok again, i.e. setting NX_ISOLATE_PLUGINS=false e.g. in .env file of your repo.

So either that PR should be reverted and previous default for plugin isolation used (i.e. not to use that plugin isolation), or there is a need of fixing internal logic of plugin isolation feature that currently makes versions 19.5.0+ completely unusable (at least on Windows).

**Comment by henke443** [comment] 2024-07-24 16:32
I also experienced this issue on 19.5.2

**Comment by henke443** [comment] 2024-07-24 16:33
Error: EPERM: operation not permitted, open 'C:\Users\henke\Documents\prog\decentralized_backup\desto\.nx\workspace-data\d\daemon.log'
Restarting the computer kills the daemon so that I can delete the file, but weirdly when running both `nx daemon` and `pnpm nx daemon` while the issue is occurring they say that the dameon is not running

**Comment by mfundoshabalala** [comment] 2024-07-25 10:09
I encountered the same issue, but I managed to resolve it by following these steps:

- Navigate to the workspace root directory.
- Ensure that all running processes, including nx serve, are stopped.

After performing these steps, the issue was resolved.

**Comment by MaxKless** [comment] 2024-07-26 13:33
Thanks everyone for helping out and investigating here. The issue seems to be plugin isolation. We now spawn an isolated worker process for each plugin during project graph creation. 
Something is going on on windows which is leading to some of those plugin instances not being shut down properly as they should on windows.
We're investigating further, if anyone has any more insights feel free to share them. The relevant code should be somewhere around here [`packages/nx/src/project-graph/plugins/isolation/plugin-pool.ts`](https://github.com/nrwl/nx/blob/master/packages/nx/src/project-graph/plugins/isolation/plugin-pool.ts#L59) or in `plugin-worker.ts`

**Comment by MaxKless** [comment] 2024-07-29 12:08
While there's still no fix: you can disable plugin isolation for now using `NX_ISOLATE_PLUGINS=false` and it should work again while we find a proper fix. @omishyn-dm @henke443 @mfundoshabalala @instantgis

**Comment by MaxKless** [comment] 2024-07-31 11:17
hey everyone! Just wanted to let you know that we've disabled plugin isolation on windows by default with `19.5.4` until we find a proper fix for this issue :)

**Comment by omishyn-dm** [comment] 2024-07-31 11:36
Thank you, 19.5.4 works!

**Comment by beaussan** [comment] 2024-08-01 14:37
Hey @MaxKless, I wanted to chime in, I have the same issue on Mac so it's not only related to widows. Disabling plugin isolation fixes the issue also on my side.

I have both local nx plugins (aka ts files in the repo, referenced with a path in nx.json) and plugins loaded via npm (`@nx/vite/plugin` for ex)

Let me know if there is some way I can help on this issue

**Comment by AgentEnder** [comment] 2024-08-09 18:44
This should be fixed by https://github.com/nrwl/nx/pull/27317, which was just merged. A new canary will go out tonight, if a few folks could try it and make sure things are working that would be appreciated. 

I'm going to preemptively close this out since the PR has been merged. If it is still broken, please let us know here or by opening a new issue. Thanks for the cooperation everyone :)

**Closed by AgentEnder** 2024-08-09 18:44 UTC
Labels: type: bug, scope: core
