### ISSUE TITLE
   Cannot read properties of undefined (reading 'xxx:lint')

### ISSUE THREAD

**Issue by Anderman** [nrwl/nx#11879] opened 2022-09-05 20:17 UTC
## Current Behavior
Error when run `npx nx print-affected --base=origin/master~1 --target=lint --verbose`

## Expected Behavior
no error

14.5.9 was wroking but bot in 14.6.4

## Steps to Reproduce

run `npx nx print-affected --base=origin/master~1 --target=lint --verbose`

### Failure Logs

```
   TypeError: Cannot read properties of undefined (reading 'shared-util-report-model:lint')
    at allDeps (C:\IT\ItZHMW\Web\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:33:36)
    at C:\IT\ItZHMW\Web\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:10:30
    at Generator.next (<anonymous>)
    at fulfilled (C:\IT\ItZHMW\Web\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
 cause context.taskGraph = {} on line 12 in hasher.js

### Environment

 >  NX   Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : win32 x64
   yarn : 3.2.3

   nx : 14.6.4
   @nrwl/angular : 14.6.4
   @nrwl/cypress : 14.6.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.4
   @nrwl/eslint-plugin-nx : 14.6.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.4
   @nrwl/js : 14.6.4
   @nrwl/linter : 14.6.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.4
   @nrwl/web : 14.6.4
   @nrwl/workspace : 14.6.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         angular-auth-oidc-client: 13.1.0

**Comment by cppmx** [comment] 2022-09-07 13:01
I have the same issue.

OS: RHE 8.0
Node: 14.18.0
npm: 6.14.15
nx: 14.6.4

The `npx nx affected --base=origin/master --target=lint` command works fine but it fails if you try to print the affected apps.

**Comment by lurock** [comment] 2022-09-08 19:06
I am having the same issue with @nrwl version 14.6.5.

**Comment by labeled** [comment] 2022-09-08 20:35
+1 same issue on 14.6.5
I dug into it a little and it looks like the "taskGraph" property in the "context" is always an empty object yet it is looking for 
![image](https://user-images.githubusercontent.com/17855377/189220548-a44a9581-27ea-46a7-8064-a3a9e08bfa42.png)
For myself I was trying to print affected lint projects. Here is the stack trace from verbose.
```
 >  NX   There was a critical error when running your command

   Cannot read properties of undefined (reading 'challenges-entry-dropdown-data-access:lint')
   
   TypeError: Cannot read properties of undefined (reading 'challenges-entry-dropdown-data-access:lint')
    at allDeps (C:\PIT\Repos\altec.voyager.14\Altec.Voyager\altec.voyager.web-ui\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:34:36)
    at C:\PIT\Repos\altec.voyager.14\Altec.Voyager\altec.voyager.web-ui\node_modules\@nrwl\linter\src\executors\eslint\hasher.js:11:22
    at Generator.next (<anonymous>)
    at fulfilled (C:\PIT\Repos\altec.voyager.14\Altec.Voyager\altec.voyager.web-ui\node_modules\tslib\tslib.js:115:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mbarzda** [comment] 2022-09-09 06:53
The issue started with this change https://github.com/nrwl/nx/commit/a3126116826b4bc8d492341e2b2b02daa4b2195e#diff-08499af12ca814c9328ed32c05086090b6bc8b64681bb9e7d67600990eb64209R74

An empty object is set as `taskGraph`. I'd recommend downgrade to 14.5.10

**Comment by labeled** [comment] 2022-09-09 12:08
> The issue started with this change [a312611#diff-08499af12ca814c9328ed32c05086090b6bc8b64681bb9e7d67600990eb64209R74](https://github.com/nrwl/nx/commit/a3126116826b4bc8d492341e2b2b02daa4b2195e#diff-08499af12ca814c9328ed32c05086090b6bc8b64681bb9e7d67600990eb64209R74)
> 
> An empty object is set as `taskGraph`. I'd recommend downgrade to 14.5.10

I can try and to back but I don't think there's support for down migrations.
I would recommend adding more regression testing to ensure nx commands are working before merging pr's.

**Comment by mbarzda** [comment] 2022-09-09 16:19
> 

sure, but when linting is essential CI/CD task, I downgraded until the issue will be fixed

**Comment by mbarzda** [comment] 2022-09-09 16:24
> 



> If you have trouble by downgrading to 5.10 then remove node_modules and .angular folders.

I'd suggest to use `nx migrage nx@14.5.10` etc.

**Comment by meeroslav** [comment] 2022-09-12 12:09
Thank you @Anderman for reporting this issue.

**Closed** 2022-09-13 08:49 UTC
Labels: type: bug, scope: core
