### ISSUE TITLE
Command for deleting app/lib

### ISSUE THREAD

**Issue by piernik** [nrwl/nx#333] opened 2018-03-14 12:36 UTC
Is there a command to delete app or lib?

**Comment by Yonet** [comment] 2018-03-15 02:02
No there isn't. If you delete a lib or app 3 things you need to do:

1. Remove the app/lib
2.Remove the module import if the lib is imported into another app/lib.
3.Remove the app/lib from .angular-cli.json apps array.

Closing the issue.

**Closed by Yonet** 2018-03-15 02:02 UTC

**Comment by boicetomlin** [comment] 2018-08-10 10:28
Is there any intention to add the ability to delete or remove libs components or apps?

**Comment by mohyeid** [comment] 2018-09-27 23:05
I think deleting a library can be very helpful specially when refactoring code! Like splitting a lib into 2, and then delete the original one.

**Comment by hadrien-toma** [comment] 2019-04-02 10:23
@Yonet if these steps are deterministic, maybe creating a schematic to do this deletion is not so strange? May we re-open this issue?

**Comment by twjacobsen** [comment] 2019-04-29 09:41
Also remember when removing a lib, that `dist/.nx-results` should be updated - if you're using any if the `affected` commands. Otherwise, the removed ones will keep succeeding/failing depending on their state prior to removal

**Comment by benhastings** [comment] 2019-05-08 20:59
You need to remove the references in angular.json and nx.json (for anyone who stumbles upon this like I did)

**Comment by boicetomlin** [comment] 2019-05-08 21:21
> You need to remove the references in angular.json and nx.json (for anyone who stumbles upon this like I did)

The idea is to not have to do this - a command to remove a library that does the necessary cleanup.

**Comment by uloga** [comment] 2019-06-06 20:16
Does anyone has some great cheatsheet for nx their docs are all over the place you don't know what to follow. Great idea but the documentation and the tutorials are the worst I've seen so far!

**Comment by dianjuar** [comment] 2019-07-15 14:10
@Yonet Pleace update your solution and add 

- Remove the path from the `tsconfig.json`

**Comment by dalu** [comment] 2019-10-28 23:22
* remove nx and enjoy a life without a headache

**Comment by demisx** [comment] 2019-11-22 16:37
Shouldn't this be automated? After all,  @vsavkin and the gang always advocate for "automating anything you can". Am I missing something?

**Comment by nikbabchenko** [comment] 2019-12-09 13:44
That's true, delete command should be there

**Comment by jberndsen** [comment] 2020-01-15 10:59
Just adding my two cents here, I would also very much love to have a remove command for apps and libs, which would throw a warning if another app/lib still depends on it and updates the relevant configs (nx.json, workspace.json, tsconfigs, etc.). I really love Nx for the smoothness that the CLI gives me and manually working with the configs dampens that sentiment.

**Comment by skorunka** [comment] 2020-02-05 09:17
This would be very helpful.

**Comment by aclarturocastro** [comment] 2020-02-21 19:11
If you are using git, just discard changes

**Comment by demisx** [comment] 2020-02-21 19:44
@aclarturocastro Unless, you've realized you need to remove some libs later, after a few commits. 😄

**Comment by aclarturocastro** [comment] 2020-02-21 23:21
> @aclarturocastro Unless, you've realized you need to remove some libs later - after a few commits. 😄

Of course!  😄

**Comment by juristr** [comment] 2020-02-24 21:44
Although this issue is closed I'd like to give an update given this is a si much requested feature.

Good news! @jdpearce is actually working on a delete functionality, very much similar to our latest move schematic we have added. So keep an eye on our release log & announcements 😉

**Comment by fxck** [comment] 2020-03-29 08:42
For anyone looking for the current way of removing at the moment (in a single list). https://github.com/nrwl/nx/issues/333#issuecomment-373235524 and https://github.com/nrwl/nx/issues/333#issuecomment-511418575 combined.

1. Remove the module import if the lib is imported into another app/lib.
2. Remove the app/lib from .angular-cli.json apps array.
3. Remove the path to your project from the tsconfig.json
4. Remove project from nx.json

**Comment by jdpearce** [comment] 2020-03-30 09:57
@fxck There's an easier way now - just use `nx g @nrwl/workspace:rm <project name>`. This was released with version 9.1.3 last week. The docs site hasn't quite caught up yet, but it will soon.

**Comment by th3m7J0** [comment] 2020-04-24 01:22
@jdpearce yup works perfectly but, there is a problem if you will create an app by mistake without name it will create the files successfully in the apps folder just do  `nx g @nrwl/express:app` and hit enter for the name of the app and then the problem will occur again. in my case i need to delete them manually from `nx.json` `workspace.json` and generated files maybe also `proxy.conf.json` in you bind it with `--frontendProject`

**Comment by jdpearce** [comment] 2020-04-24 10:45
@th3m7J0 That sounds like a problem with the `@nrwl/express:app` schematic itself. Can you raise another issue for that, please?

**Comment by th3m7J0** [comment] 2020-04-24 14:58
@jdpearce the problem is not only related to `@nrwl/express:app` i also tried with `@nrwl/react:app` the diffrence between those if the app name is not specified by mistake (hit enter) :
1. for the express api it will create all generated files inside the apps folder as i sad above.
2. for angular or react it will create two folders the first one with "\t" as name and "\t-e2e".
In both cases the `rm` command wont work.

I think you need to fix that, because of the probability of being made by several developers is high.

**Comment by puvaasam** [comment] 2020-06-18 09:31
nx g @nrwl/workspace:remove lib-name
