### ISSUE TITLE
Error "Required property 'browser' is missing" when using "application" builder for Angular app

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#19928] opened 2023-10-30 10:12 UTC
### Current Behavior

If in project.json we set
```json
  "targets": {
    "build": {
      "executor": "@angular-devkit/build-angular:application",
```
and run `nx build`, this error will be produced:
```
 >  NX   Required property 'browser' is missing
```

### Expected Behavior

I'm not sure if it's a bug or a feature request, actually - please modify this issue if needed (I can re-create it if it's impossible to modify).

I expected `@angular-devkit/build-angular:application` to work just the same way (not sure what's the difference for Nx). Maybe it was false expectation :)

### Steps to Reproduce

1.
```
npx create-nx-workspace@latest angular-monorepo --preset=angular-monorepo

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Application name · angular-monorepo
✔ Default stylesheet format · scss
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Would you like to use Standalone Components in your application? · Yes
✔ Would you like to add routing? · Yes
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.0.2 workspace.
```

2. When everything is done, go to apps/angular-monorepo/project.json and edit it to have
```json
  "targets": {
    "build": {
      "executor": "@angular-devkit/build-angular:application",
```

3. Run `npx nx build angular-monorepo` (you don't even need to upgrade Angular to 17 - it will not reach that step).

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.8.1
   OS     : darwin-arm64
   npm    : 10.1.0
   
   nx                 : 17.0.2
   @nx/js             : 17.0.2
   @nx/jest           : 17.0.2
   @nx/linter         : 17.0.2
   @nx/eslint         : 17.0.2
   @nx/workspace      : 17.0.2
   @nx/angular        : 17.0.2
   @nx/cypress        : 17.0.2
   @nx/devkit         : 17.0.2
   @nx/eslint-plugin  : 17.0.2
   @nx/playwright     : 17.0.2
   @nrwl/tao          : 17.0.2
   @nx/web            : 17.0.2
   @nx/webpack        : 17.0.2
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Note from `@angular-devkit/build-angular:browser-esbuild`:

> The 'browser-esbuild' builder is a compatibility builder which will be removed in a future major version in favor of the 'application' build

**Comment by leosvelperez** [comment] 2023-10-30 11:52
Thanks for reporting this!

The error you're getting is a valid error because the `@angular-devkit/build-angular:application` has a slightly different schema compared to the `@angular-devkit/build-angular:browser` builder that's generated by default. So, the validation for the target options is failing. You also need to rename the `main` option to `browser`. Please note there are also some options that are not supported so be sure to check what's supported by that builder.

In the upcoming Angular v17 the `application` builder will be used by default when using the esbuild bundler.

I'm going to close this since the error received is the expected behavior.

**Closed by leosvelperez** 2023-10-30 11:52 UTC
Labels: type: bug

**Comment by e-oz** [comment] 2023-10-30 12:44
Thanks a lot, @leosvelperez !
---
For the future readers:
1. If you have a service worker, remove `"serviceWorker": true` and rename `ngswConfigPath` option to `serviceWorker`, so in the result you get `"serviceWorker": "apps/example-app/ngsw-config.json"`;
2. Convert polyfills from string to array: `"polyfills": ["apps/example-app/src/polyfills.ts"]`;
3. Rename option `main` to `browser` (`"browser": "apps/example-app//src/main.ts"`);
4. Modify `executor` option: `"executor": "@angular-devkit/build-angular:application"`;

**Comment by jakwarrior** [comment] 2023-11-29 07:45
> And remove
> 
> "optimization" "vendorChunk"
> 
> Fields :-)
> 
> Those are all missing in migraiton guide
> 
> https://update.angular.io/?l=3&v=15.0-17.0

"buildOptimizer" instead of "optimization", this one is still valid : [https://angular.io/guide/esbuild#using-the-application-builder](https://angular.io/guide/esbuild#using-the-application-builder)
[https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/builders/application/schema.json](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/builders/application/schema.json)
