### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jinisha** [nrwl/nx#10047] opened 2022-04-28 17:46 UTC
## Current Behavior
I am currently on 12.10.0 version. When I run nx migrate @nrwl/workspace@13.1.4 --verbose command I am getting an error.

package.json 

"dependencies": {
    "@angular/animations": "^12.2.0",
    "@angular/cdk": "^12.2.0",
    "@angular/common": "^12.2.0",
    "@angular/compiler": "^12.2.0",
    "@angular/core": "^12.2.0",
    "@angular/forms": "^12.2.0",
    "@angular/localize": "^12.2.9",
    "@angular/platform-browser": "^12.2.0",
    "@angular/platform-browser-dynamic": "^12.2.0",
    "@angular/router": "^12.2.0",
    "@nrwl/angular": "^12.10.1",
    "fs-extra": "^10.0.0",
    "http-status-codes": "^2.1.4",
    "keycloak-angular": "^7.3.1",
    "keycloak-js": "^9.0.3",
    "lodash.sortby": "^4.7.0",
    "minimist": "^1.2.5",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.27",
    "ngx-hotjar": "0.0.5",
    "node-fetch": "^2.6.1",
    "primeng": "^9.1.0",
    "rxjs": "^6.5.4",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.4"
 },
 "devDependencies": {
   "@angular-devkit/build-angular": "12.2.15",
    "@angular-eslint/eslint-plugin": "~12.3.0",
    "@angular-eslint/eslint-plugin-template": "~12.3.0",
    "@angular-eslint/template-parser": "~12.3.0",
    "@angular/cli": "12.2.15",
    "@angular/compiler-cli": "12.2.0",
    "@angular/language-service": "12.2.0",
    "@nrwl/cli": "^12.10.1",
    "@nrwl/cypress": "^12.10.1",
    "@nrwl/eslint-plugin-nx": "^12.10.1",
    "@nrwl/jest": "^12.10.1",
    "@nrwl/linter": "^12.10.1",
    "@nrwl/tao": "^12.10.1",
    "@nrwl/workspace": "^12.10.1",
    "@types/jest": "27.0.2",
    "@types/node": "14.14.33",
    "@typescript-eslint/eslint-plugin": "4.31.2",
    "@typescript-eslint/parser": "4.31.2",
    "cypress": "^9.5.1",
    "cypress-grep": "^2.10.1",
    "cypress-keycloak-commands": "^1.2.0",
    "cypress-multi-reporters": "^1.6.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-cypress": "^2.10.3",
    "husky": "^7.0.4",
    "jest": "27.2.3",
    "jest-junit": "^13.0.0",
    "jest-preset-angular": "10.0.1",
    "json-server": "^0.16.1",
    "lint-staged": "^12.1.2",
    "mocha": "^9.2.2",
    "mocha-junit-reporter": "^2.0.2",
    "ng-mocks": "^10.1.2",
    "ng-packagr": "^9.0.0",
    "npm": "~6.14.16",
    "postcss": "^8.3.9",
    "postcss-import": "^14.0.2",
    "postcss-preset-env": "^6.7.0",
    "postcss-url": "^10.1.1",
    "prettier": "^2.3.1",
    "sonar-scanner": "^3.1.0",
    "ts-jest": "27.0.5",
    "typescript": "4.3.5"
}

ERROR  The migrate command failed.

Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\src\command-line\connect-to-nx-cloud.js:38:36
    at Generator.next (<anonymous>)
    at C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\node_modules\tslib\tslib.js:114:16)
    at connectToNxCloudCommand (C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\src\command-line\connect-to-nx-cloud.js:36:20)
    at C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\src\command-line\migrate.js:560:73
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\AppData\Local\Temp\tmp-161692-6Qql83Kb3MgY\node_modules\nx\node_modules\tslib\tslib.js:115:62)

## Expected Behavior

Expect the migration to the newer version work as expected. 

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

**Comment by andziaoo7** [comment] 2022-05-02 07:29
I have the same error when trying to run nx g @nrwl/angular:move --project shared-ui-common-icons shared/ui/assets

Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\@nrwl\workspace\src\generators\move\lib\update-implicit-dependencies.js:12:16
    at Object.updateJson (C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\@nrwl\devkit\src\utils\json.js:45:26)
    at Object.updateImplicitDependencies (C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\@nrwl\workspace\src\generators\move\lib\update-implicit-dependencies.js:11:14)
    at Object.<anonymous> (C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\@nrwl\workspace\src\generators\move\move.js:38:40)
    at Generator.next (<anonymous>)
    at C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\tslib\tslib.js:114:16)
    at Object.moveGenerator (C:\Users\user\REPOS\projectName\node_modules\@nrwl\angular\node_modules\@nrwl\workspace\src\generators\move\move.js:22:20)


My package.json
"dependencies": {
    "@angular/animations": "12.2.16",
    "@angular/cdk": "12.2.13",
    "@angular/common": "12.2.16",
    "@angular/compiler": "12.2.16",
    "@angular/core": "12.2.16",
    "@angular/forms": "12.2.16",
    "@angular/material": "12.2.13",
    "@angular/material-moment-adapter": "12.2.13",
    "@angular/platform-browser": "12.2.16",
    "@angular/platform-browser-dynamic": "12.2.16",
    "@angular/router": "12.2.16",
    "@ngrx/effects": "12.5.1",
    "@ngrx/store": "12.5.1",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "@nrwl/angular": "12.10.1",
    "@storybook/addon-a11y": "6.4.19",
    "@storybook/addon-controls": "6.4.19",
    "@types/google-libphonenumber": "7.4.19",
    "country-telephone-data": "0.6.2",
    "file-saver": "2.0.5",
    "google-libphonenumber": "3.2.13",
    "husky": "7.0.4",
    "lodash": "4.17.21",
    "moment": "2.29.2",
    "node": "14.13.0",
    "rxjs": "6.6.3",
    "rxjs-etc": "10.4.0",
    "tslib": "2.0.0",
    "uuid": "8.3.1",
    "zone.js": "0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.2.17",
    "@angular-eslint/eslint-plugin": "12.3.1",
    "@angular-eslint/eslint-plugin-template": "12.3.1",
    "@angular-eslint/template-parser": "12.3.1",
    "@angular/cli": "12.2.17",
    "@angular/compiler-cli": "12.2.16",
    "@angular/language-service": "12.2.16",
    "@commitlint/cli": "11.0.0",
    "@commitlint/config-conventional": "11.0.0",
    "@ngrx/store-devtools": "12.5.1",
    "@nrwl/cli": "12.10.1",
    "@nrwl/eslint-plugin-nx": "12.10.1",
    "@nrwl/jest": "12.10.1",
    "@nrwl/linter": "12.10.1",
    "@nrwl/storybook": "12.10.1",
    "@nrwl/tao": "12.10.1",
    "@nrwl/workspace": "12.10.1",
    "@storybook/addon-backgrounds": "6.1.21",
    "@storybook/angular": "6.4.19",
    "@types/jest": "27.0.2",
    "@types/lodash": "4.14.162",
    "@types/node": "14.11.5",
    "@types/webpack": "4.41.22",
    "@typescript-eslint/eslint-plugin": "4.31.2",
    "@typescript-eslint/parser": "4.31.2",
    "cpx": "1.5.0",
    "dotenv": "10.0.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jest": "26.1.5",
    "eslint-plugin-jsdoc": "39.2.8",
    "eslint-plugin-ordered-imports": "0.6.0",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "eslint-plugin-rxjs": "5.0.2",
    "eslint-plugin-unicorn": "40.1.0",
    "jest": "27.2.3",
    "jest-preset-angular": "10.0.1",
    "prettier": "2.3.1",
    "replace-in-file": "6.1.0",
    "ts-jest": "27.0.5",
    "ts-node": "9.0.0",
    "typescript": "4.3.5"
  }

**Comment by ahinni** [comment] 2022-05-04 13:47
I had the same error using 12.10.0.  This is the line that it is failing on:

```
const nxCloudUsed = Object.values(nxJson.tasksRunnerOptions).find((r) => r.runner == '@nrwl/nx-cloud');
```

I took a look at my nx.json file, and it didn't have a taskRunnerOptions setting in it. I created a brand new workspace and copied what was in there and was able to get past this error.

This is what I added to my `nx.json`
```
"tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
```

**Comment by jinisha** [comment] 2022-05-04 23:22
Thanks @ahinni for the suggestion!

I tried what you suggested and I am getting a new error. Any idea how to fix this?

Error: Cannot find module 'nx/tasks-runners/default'
Require stack:
- C:\Users\Development\...\node_modules\@nrwl\workspace\src\tasks-runner\run-command.js
- C:\Users\Development\...\node_modules\@nrwl\workspace\src\command-line\run-one.js
- C:\Users\Development\...\node_modules\@nrwl\cli\lib\init-local.js 
- C:\Users\Development\...\node_modules\@nrwl\cli\bin\nx.js

**Comment by ahinni** [comment] 2022-05-05 01:10
I have no idea other than to try `{}` instead of all of the stuff I put in. ie. `tasksRunnerOptions: {}`... or figure out what that default task runner is, and how to install it.

**Comment by igl** [comment] 2022-08-31 21:18
FYI: First time user of `@nrwl/workspace:move` and i got the same error.

`--verbose` pointed me to a unsafe access of `compilerOptions.paths` in my tsconfig.json:

```
    at Function.keys (<anonymous>)
    at updateImports (/opt/foobar/node_modules/@nrwl/workspace/src/generators/move/lib/update-imports.js:29:27)
    at /opt/foobar/node_modules/@nrwl/workspace/src/generators/move/move.js:28:44
```

I guess i never connected my packages with ts paths, because I use [project references](https://www.typescriptlang.org/docs/handbook/project-references.html).

I still have lots to learn about how nx works under the hood!

**Comment by mandarini** [comment] 2023-02-14 13:19
Can you please retry with the latest version of Nx, and let me know if the issue is now gone?

**Comment by muuvmuuv** [comment] 2023-03-01 15:19
Ok, my issue came from using `angular.json` so I can `ng update` on my libs. Adding an empty `projects` prop fixed it.

**Comment by JayAhn2** [comment] 2023-03-07 19:12
Any plan for this bug? I've got this issue when I use `npx nx init`

**Comment by igl** [comment] 2023-03-22 12:35
There needs to be some more optional chaining (`?.`) in the value look ups.

I love lean configuration and I love that NX works with a single `nx.json` and nothing else.
We have about 20 packages in our mono-repo and only 1 needs a `"nx"` key in it's package.json to set some `implicitDependencies` and that's it.

I largely avoided the cli utils of NX due to these problems.

**Comment by caseyyee** [comment] 2023-03-31 18:47
same issue with `npx nx init`

**Comment by mandarini** [comment] 2023-04-13 07:56
@thiagodebastos hello! What version of Nx are you using?

**Comment by sebastian-kreft-simployer** [comment] 2023-04-21 14:15
Same problem for me with `nx g @nrwl/storybook:configuration`, NX version 15.9.2, just started the repo from scratch.

**Comment by AgentEnder** [comment] 2023-05-04 17:41
Hey 👋, I'm going to close this issue out. It looks like some people are still experiencing this, but the stack traces for folks are likely slightly different, and with different root causes.

If you hit this, can you open a new issue that contains `nx report` and the failure log when running with `--verbose` so each instance can be hit by triage?

Thanks!

**Closed by AgentEnder** 2023-05-04 17:41 UTC
Labels: type: bug, blocked: retry with latest, scope: core
