### ISSUE TITLE
`nx lint && ng lint` reports one file in multiple libs

### ISSUE THREAD

**Issue by skorunka** [nrwl/nx#842] opened 2018-10-22 10:09 UTC
After executing `npm run lint` I get this output:

```
PS C:\_\TechniServ\esel\esel.clients> npm run lint

> esel@0.0.0 lint C:\_\TechniServ\esel\esel.clients
> nx lint && ng lint

Linting "el-portal"...

ERROR: C:/_/TechniServ/esel/esel.clients/libs/common/core/src/lib/http/http-cache.service.ts[97, 12]: Type annotation in JSDoc is redundant in TypeScript code.

Lint errors found in the listed files.
Linting "el-admin"...


All files pass linting.
Linting "common-auth"...


All files pass linting.
Linting "common-core"...

ERROR: C:/_/TechniServ/esel/esel.clients/libs/common/core/src/lib/http/http-cache.service.ts[97, 12]: Type annotation in JSDoc is redundant in TypeScript code.

Lint errors found in the listed files.
Linting "common-logger"...


All files pass linting.
Linting "common-router"...


All files pass linting.
Linting "el-login"...


All files pass linting.
Linting "el-home"...

ERROR: C:/_/TechniServ/esel/esel.clients/libs/common/core/src/lib/http/http-cache.service.ts[97, 12]: Type annotation in JSDoc is redundant in TypeScript code.

```

One lint issues is reported multiple times, why is that? Thank you.

**Comment by jeneg** [comment] 2019-07-31 09:50
Got same problem. One file get linted 6 times in my case and that is really slowing down CI

**Comment by krawetko** [comment] 2019-12-04 06:32
Found a solution to this for Angular Porjects. In angular.json, for every lib/project in lint options, you need to add "files" property including only the files of this library/project - then it never goes outside of lib/project boundary. Example config of my lib in my angular.json:
` "some-lib": {
      "root": "libs/some-lib",
      "sourceRoot": "libs/some-lib/src",
      "projectType": "library",
      "prefix": "some",
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "files": ["libs/some-lib/src/**/*.ts"],
            "tsConfig": ["libs/some-lib/tsconfig.lib.json", "libs/some-lib/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**"]
          }
        },`

**Comment by vsavkin** [comment] 2019-12-04 16:58
This has been fixed. We now correctly set up excludes not to relint the same file multiple times.

Could you update your repo to latest to see if the issue persists?

**Comment by krawetko** [comment] 2019-12-05 06:10
@vsavkin Tried with `8.9.0` - the problem is still present

**Comment by krawetko** [comment] 2019-12-05 06:14
@vsavkin tried with `8.9.0` - the problem is still there.

**Comment by FrozenPandaz** [comment] 2019-12-24 05:19
@krawetko Every project is generated with exclusions of outside files:

https://github.com/nrwl/nx-examples/blob/master/angular.json#L96

Can you confirm you have this configuration? If so, can you please provide a repro (public repo) to help us investigate the issue?

**Comment by FrozenPandaz** [comment] 2020-03-27 17:43
Closing this issue as I haven't received a response for 3 months. If you continue to experience this issue, please open a new issue with a repo exhibiting the issue so we can easily debug.

**Closed by FrozenPandaz** 2020-03-27 17:43 UTC
Labels: blocked: retry with latest, scope: misc, type: bug
