### ISSUE TITLE
Eslint rule `enforce-module-boundaries` false positive

### ISSUE THREAD

**Issue by JesusTheHun** [nrwl/nx#15957] opened 2023-03-29 11:56 UTC
### Current Behavior

```ts
import * as Sentry from '@sentry/node';
// ^ ESLint: Projects should use relative imports to import from other files within the same project. Use "./path/to/file" instead of import from "@sentry/node"(@nrwl/nx/enforce-module-boundaries)

// EDIT : actually, even a simple import can cause an issue
import { hotjar } from "react-hotjar";
// ^ Same error
```

### Expected Behavior

No error

### Steps to Reproduce

Import any package with a namespace

### Nx Report

```shell
Node : 18.13.0
OS   : darwin arm64
npm  : 8.19.3
   
nx                      : 15.8.9
@nrwl/js                : 15.8.9
@nrwl/jest              : 15.8.9
@nrwl/linter            : 15.8.9
@nrwl/workspace         : 15.8.9
@nrwl/cli               : 15.8.9
@nrwl/cypress           : 15.8.9
@nrwl/devkit            : 15.8.9
@nrwl/esbuild           : 15.8.9
@nrwl/eslint-plugin-nx  : 15.8.9
@nrwl/node              : 15.8.9
@nrwl/react             : 15.8.9
@nrwl/tao               : 15.8.9
@nrwl/vite              : 15.8.9
@nrwl/webpack           : 15.8.9
typescript              : 4.9.5
```

**Comment by meeroslav** [comment] 2023-04-03 07:49
Thank you @JesusTheHun for reporting this.

This seems to be coming back but we can never reproduce it. Can you provide a minimal repo with this error?
Please also try to reinstall your dependencies and let me know if the error persists.

1. `rm -rf node_modules`
2. `npm ci/yarn --frozen-lockfile/pnpm install --frozen-lockfile`
3. Run lint again

**Comment by rmjwilbur** [comment] 2023-04-06 02:56
New to Nx but getting this as well on any imports/exports from @aws-amplify, ie: 

`
import { Auth } from '@aws-amplify/auth';
`

and

`
export { RestAPI as api } from '@aws-amplify/api-rest';
`

**Comment by rmjwilbur** [comment] 2023-04-07 21:11
Hope this example works for you: https://github.com/petconsole/mini-repo-1/blob/main/libs/pure-fe-api/src/ourYupSchema.ts

I'm also getting the issue on imports from yup, react, redux, etc.

**Comment by jogelin** [comment] 2023-04-12 15:22
@meeroslav I have the same issue when trying to switch from yarn to pnpm:

```
ESLint: Transitive dependencies are not allowed. Only packages defined in the "package.json" can be imported(@nrwl/nx/enforce-module-boundaries)
```

This is happening only on 2 dependencies: `'@auth0/auth0-angular'` and `'@cumul.io/ngx-cumulio-dashboard'`

After debugging, it seems that the rule is correct but the `nxdeps.json` contains wrong values, for example:
```
...
    "npm:@auth0/auth0-angular@2.0.2(@angular/common@15.2.5)(@angular/core@15.2.5)(@angular": {
      "type": "npm",
      "name": "npm:@auth0/auth0-angular@2.0.2(@angular/common@15.2.5)(@angular/core@15.2.5)(@angular",
      "data": {
        "version": "router@15.2.5)",
        "packageName": "@auth0/auth0-angular@2.0.2(@angular/common@15.2.5)(@angular/core@15.2.5)(@angular",
        "hash": "sha512-MdZakp0M3NbRd0HsNHzML9XPYyDPIF6oq6NCsn+dY1DKizQee6MP90PrezXDDQ3JpRkgbkVRL0cjEu7HHA8bug=="
      }
    },
    "npm:@auth0": {
      "type": "npm",
      "name": "npm:@auth0",
      "data": {
        "version": "auth0-spa-js@2.0.4",
        "packageName": "@auth0",
        "hash": "sha512-NgD6Fkm5Xnbned1VjhEW8irm1/Y8AWtdSLexgLXNwwBVgfnYicCVBu8w75m2t+4QljXkTcI7IXVEFhVmxMuxaA=="
      }
    },
...
```

As you can see, the version name is wrong. Hope this can help

**Comment by meeroslav** [comment] 2023-04-18 10:17
@jogelin, what you see is an issue with missing support for `pnpm` v8 (or lock file v6), which was merged two weeks ago but is only available since [16.0.0-beta.0](https://github.com/nrwl/nx/releases/tag/16.0.0-beta.0).

**Comment by meeroslav** [comment] 2023-04-18 10:21
@rmjwilbur, unfortunately, I could not reproduce this on a fresh clone of your repo.

![Screenshot 2023-04-18 at 12 20 07](https://user-images.githubusercontent.com/881612/232748182-b3b6dd2e-55dd-49df-aa7e-211d7524e430.png)

I'm closing this error as not reproducible. If someone can produce a repo where this can be reproduced on a clean state I will gladly re-open it.

**Comment by mzehetho** [comment] 2023-04-27 08:54
We faced the same issue after an eslint update.
We solved the original problem (we had both a lazy and a static import of the same module), but the linter still complained.
After deleting the NX cache the lint was gone.

**Comment by balintk** [comment] 2023-05-12 06:27
@meeroslav I might be wrong — I'm also new to Nx — but your screenshot shows that you only installed dependencies from the root `package.json` file. The sample repo @rmjwilbur prepared has a project-level `package.json` inside `libs/pure-fe-api`. I believe if you install that, too, you will get the error. Interestingly, ESLint doesn't complain about the missing module in case you skip installing that, which makes your linting pass. I can reproduce this behavior with my own repository.

**Closed** 2023-06-18 11:58 UTC
Labels: type: bug, blocked: repro needed, blocked: more info needed, scope: linter

**Comment by peterbbeu** [comment] 2023-06-23 17:50
@meeroslav I tried using the workspaces fix you mentioned above, but it doesn't install the packages, neither in the root node_modules nor in the lib node_modules.

1. add workspaces to root package.json
2. rm -rf node_modules (libs)
3. remove package-lock.json from libs
4. rm -rf node_modules (root level)
5. yarn --frozen-lockfile

Am I missing something?

**Comment by meeroslav** [comment] 2023-07-04 11:11
You can check the official yarn documentation here: https://classic.yarnpkg.com/lang/en/docs/workspaces/
