### ISSUE TITLE
js:tsc executor fails when run in a target not named "build"

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#17764] opened 2023-06-23 19:59 UTC
### Current Behavior

If you try to build something using the `@nrwl/js:tsc` executor that depends on some other packages in the repository, it works as long as the target that is running it is named "build".

It seems that if you name it anything else, it breaks some internal assumptions the package is making and prevents it from rewriting tsconfig path aliases such that the build fails with a bunch of Typescript resolve errors from the dependent packages.

### Expected Behavior

The executor should work in any target regardless of what it's named, unless there's some piece of documentation I'm missing that explains why this is the case.

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks

### Steps to Reproduce

1. clone repo
2. run `nx build js`
3. it builds successfully
4. change the "build" target in `sdk/js/project.json` to some other name
5. run `nx <new build name> js`
6. build now fails with a bunch of Typescript resolve errors

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 3.6.0
   Hasher : Native

   nx                 : 16.3.2
   lerna              : 5.6.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/detox          : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/next           : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/react-native   : 16.3.2
   @nx/rollup         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   	 @devcycle/bucketing-assembly-script
   	 @devcycle/openfeature-nodejs-provider
   	 @devcycle/bucketing-test-data
   	 @devcycle/bucketing
   	 @devcycle/devcycle-react-native-sdk
   	 @devcycle/types
   	 @devcycle/nodejs-server-sdk
   	 @devcycle/devcycle-react-sdk
   	 @devcycle/devcycle-js-sdk
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ajwootto** [comment] 2023-06-26 13:53
Hi @mandarini !

Sorry, I made a mistake in the repro steps. After renaming the target, I was correctly calling the newly-named target, eg. `nx <my new name> nodejs`

The problem appeared when that task was executed, where I received a bunch of Typescript errors about failures to resolve the dependent library code.

It may also be easier to reproduce in that repo with the "js" project, because it doesn't require protobuf and other tools to be installed.

Try the same instructions with `js` rather than `nodejs`

sorry for the confusion!

**Comment by ajwootto** [comment] 2023-06-26 14:12
I opened a PR against your repo that adds a reproduction of the issue:
https://github.com/mandarini/tsc-target-name/pull/1

**Comment by mandarini** [comment] 2023-06-26 14:20
Oooook ! I see the issue now! :) Thanks for the repro

**Comment by mandarini** [comment] 2023-06-26 14:55
@ajwootto temp workaround until I fix this: if you name the build target of the imported lib the same as the build target of the parent lib, then it works. But I'll fix this

**Comment by mandarini** [comment] 2023-06-26 15:02
So, the issue is:

For `@nx/js:tsc` executor and for `@nx/js:swc` executor, if one project imports another project, both projects' build targets need to have the same name.

**Comment by mandarini** [comment] 2023-06-27 15:18
We are not going to be fixing this now, will get to it soon, however. We want to follow a different approach @ajwootto .

For the time being here are two workarounds you can do:

## The scenario:

Here's the scenario:

* `parent-lib` has `my-build-1` target with `@nx/js:tsc` executor for building
* `parent-lib` depends on `child-lib` which has `my-build-2` target with `@nx/js:tsc` executor for building

## The two different workarounds

You can use one of the two:

### Same build names

You can name all the build targets with the same name. So, in the above scenario, rename `my-build-2` target of `child-lib` to `my-build-1`.

### Dummy same-name build target

You can create a dummy same-name build target in the project where you don't want to rename your actual build target, which will depend on the build target you want. So, in the above scenario, in the `project.json` of `child-lib` you can add this new target:
```
    "my-build-1": {
      "dependsOn": ["my-build-2"],
      "command": "echo dummy build",
      "options": {
        "outputPath": "dist/libs/mylib",
        "tsConfig": "libs/mylib/tsconfig.lib.json"
      }
    },
```


You can see my [reproduction repository](https://github.com/mandarini/tsc-target-name/tree/main) to understand better what I am saying (credits to @jaysoo for this solution).

**Comment by ajwootto** [comment] 2023-06-27 15:47
Thanks for looking into it @mandarini 

would it make sense to keep the issue open until then since it is technically a bug that is going to be fixed? Or is this expected behaviour?

**Comment by mandarini** [comment] 2023-06-27 15:52
Yeah, the reason I closed it is because the issue is not exactly what is described, but I guess we can keep it open, sure!

**Comment by ajwootto** [comment] 2023-06-27 15:53
> Yeah, the reason I closed it is because the issue is not exactly what is described, but I guess we can keep it open, sure!
@mandarini  yeah no worries, just didn't want it to get lost!

by the way I posted an edit to the comment above with some additional considerations

**Comment by mandarini** [comment] 2023-06-27 15:56
Oh no it will not get lost, it's already added in our "to-do" list haha! I wouldn't close it like that, under the carpet :P

**Closed** 2023-07-19 19:11 UTC
Labels: type: bug, scope: js
