### ISSUE TITLE
Livereload or HMR on Nx 12.6, Webpack5 & React App

### ISSUE THREAD

**Issue by Nightbr** [nrwl/nx#6506] opened 2021-07-26 08:58 UTC
Hello,

I have upgraded to Nx 12.6 & Webpack5 which is awesome and fixed a lot of compatibility issues with my libs and apps \o/

But it seems I lost the livereloading (reload the app in dev browser) on my React App. Also the major improvement on this is the HMR with Webpack5.

## Current Behavior

Not livereload or HMR on dev server for React App.

## Expected Behavior

When saving code modification, need to reload the module or App in browser.

## Steps to Reproduce

Nx workspace v12.6+, Webpack5 config, React App

1. nx serve app
2. modify code
3. no livereloading or HMR, need to Refresh web page manually

### Failure Logs

No errors

### Environment

Webpack5

```
  Node : 12.21.0
  OS   : linux x64
  yarn : 1.22.5
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.6.1
  @nrwl/cypress : 12.6.1
  @nrwl/devkit : 12.6.1
  @nrwl/eslint-plugin-nx : 12.6.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.1
  @nrwl/linter : 12.6.1
  @nrwl/nest : 12.6.1
  @nrwl/next : Not Found
  @nrwl/node : 12.6.1
  @nrwl/nx-cloud : 12.3.0
  @nrwl/react : 12.6.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.1
  @nrwl/web : 12.6.1
  @nrwl/workspace : 12.6.1
  @nrwl/storybook : 12.6.1
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

## Possible solutions

Seems react-fast-refresh works with webpack5, see https://dev.to/workingeeks/speeding-up-your-development-with-webpack-5-hmr-and-react-fast-refresh-of8

Add to that, I look into the code base and see there is a TODO for HMR & webpack5
https://github.com/nrwl/nx/blob/master/packages/react/plugins/webpack.ts#L58

If you need any more insight, feel free to ask me! 

Thanks for this awesome project :heart:

**Comment by Nightbr** [comment] 2021-07-26 14:51
i tried to dig this a little more:

In the serve config on project.json, I tried to enable HMR & LiveReload:

```json
"serve": {
      "executor": "@nrwl/web:dev-server",
      "options": {
        "buildTarget": "app:build",
        "open": true,
        "hmr": true
      },
      "configurations": {
        "production": {
          "buildTarget": "app:build:production"
        }
      }
    },
```

But don't seem to work.

I have `[HMR] Waiting for update signal from WDS...` in the console but no changes when I edit the code.

As a workaround, I would like to make Livereload works until HMR are stable.

I tried this config:
```json
"serve": {
      "executor": "@nrwl/web:dev-server",
      "options": {
        "buildTarget": "app:build",
        "open": true,
        "hmr": false,
        "liveReload": true,
        "watch": true
      },
      "configurations": {
        "production": {
          "buildTarget": "app:build:production"
        }
      }
    },
```
 But still no livereload, add to that when I debug the webpackConfig, I have watch option to false:

```
  watch: false,
  watchOptions: { poll: undefined },

```

**Comment by fetters5** [comment] 2021-07-26 22:40
I had the same issue which is caused by: https://github.com/webpack/webpack-dev-server/issues/2758.

 Supposedly the newest webpackdevserver 4.0.0-rc.0 fixes live reloading but you can also fix it with a custom config (See below)

custom config 
```
const getConfig = require('@nrwl/react/plugins/webpack');

module.exports = (config) => {

  config = getConfig(config);
  if (config.mode === 'development' && config.devServer) {
    config.target = 'web';
  }

  return {
    ...config,
  };
};
```

I have not figured out how to get HMR to work

**Comment by Nightbr** [comment] 2021-07-28 09:46
@fetters5 thanks for this fix, Livereloading is working with your fix :pray: Waiting Webpack-dev-server fix soon :+1: 

For HMR, I tried this config (inspired from the default React config in Nx):

```ts
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const webpack = require('webpack');

// Add React-specific configuration
function getWebpackConfig(config) {
  const { isWebpack5 } = require('@nrwl/web/src/webpack/entry');
  config.module.rules.push(
    {
      test: /\.(png|jpe?g|gif|webp)$/,
      loader: require.resolve('url-loader'),
      options: {
        limit: 10000, // 10kB
        name: '[name].[hash:7].[ext]',
      },
    },
    {
      test: /\.svg$/,
      oneOf: [
        // If coming from JS/TS file, then transform into React component using SVGR.
        {
          issuer: isWebpack5 ? /\.[jt]sx?$/ : { test: /\.[jt]sx?$/ },
          use: [
            {
              loader: require.resolve('@svgr/webpack'),
              options: {
                svgo: false,
                titleProp: true,
                ref: true,
              },
            },
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
                esModule: false,
              },
            },
          ],
        },
        // Fallback to plain URL loader.
        {
          use: [
            {
              loader: require.resolve('url-loader'),
              options: {
                limit: 10000, // 10kB
                name: '[name].[hash:7].[ext]',
              },
            },
          ],
        },
      ],
    }
  );

  // Fix devServer
  if (config.mode === 'development' && config.devServer) {
    config.target = 'web';
  }

  if (config.mode === 'development' && config['devServer'].hot) {
    // add `react-refresh/babel` to babel loader plugin
    const babelLoader = config.module.rules.find((rule) =>
      rule.loader.toString().includes('babel-loader')
    );
    if (babelLoader) {
      babelLoader.options['plugins'] = [
        ...(babelLoader.options['plugins'] || []),
        [
          require.resolve('react-refresh/babel'),
          {
            skipEnvCheck: true,
          },
        ],
      ];
    }
    // add https://github.com/pmmmwh/react-refresh-webpack-plugin to webpack plugin
    config.plugins.push(new ReactRefreshWebpackPlugin());
  }

  return config;
}

module.exports = getWebpackConfig;
```

---

I can see in the browser console that hmr is enable:

```
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.
```

And when I save changes:

```
[WDS] App updated. Recompiling... 
[WDS] App hot update...
```

But nothing is updated in the App.

Add to that I have a warning on vendor.js that is not found (so not properly served):

```
Erreur dans les liens source : Error: request failed with status 404
URL de la ressource : https://localhost:4200/vendor.js
URL du lien source : sockjs.js.map
```

I follow everything in the [React Refresh Webpack Plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) Readme (even installing react-reconciler) but I think I'm missing something.

Seems HMR is still experimental and I will stick to Livereload with the fix so far and wait until HMR is a bit more stable I think. Still I will try later to make it works and anybody is welcome to post their result & tests here too :+1:

**Comment by jaysoo** [comment] 2021-07-28 13:57
A patch is incoming very soon for this. :)

We need to update the react refresh plugin and also the dev-server.

**Comment by jaysoo** [comment] 2021-07-28 15:08
Will be in the next patch release this week.

Workaround for now:

```
yarn add -D react-refresh@0.10.0 webpack-dev-server@4.0.0-rc.0 @pmmmwh/react-refresh-webpack-plugin@0.5.0-rc.2
```

And then in the project config,  point `webpackConfig` to a local  copy.

e.g.

```

"demo": {
  "root": "apps/demo",
  "sourceRoot": "apps/demo/src",
  "projectType": "application",
  "targets": {
    "build": {
      "executor": "@nrwl/web:build",
      "outputs": ["{options.outputPath}"],
      "options": {
        ...
        "webpackConfig": "apps/demo/webpack.config.js"
      },
      ...
  }
}
```

Lastly, in the `webpack.config.js` file:

```
module.exports = (config) => {
  const createReactWebpackConfig = require('@nrwl/react/plugins/webpack');
  config = createReactWebpackConfig(config);
  config.target = 'web';
  return config;
};
```

**Comment by jugglingcats** [comment] 2021-07-28 17:15
@jaysoo I can't seem to get fast refresh working. The live reload is happening but my component state is reset, and there are errors in the console:

![image](https://user-images.githubusercontent.com/526349/127366841-a782200f-aa93-409e-86e8-cf32b1eeaadc.png)

Am probably doing something wrong in the setup. My steps were:

- Run default NX React project generator
- Migrated to webpack5 using `nx g @nrwl/web:webpack5`
- Followed your steps above (using npm rather than yarn)

**Comment by jaysoo** [comment] 2021-07-28 17:19
@jugglingcats I'll take a quick look, it is possible I missed something.

**Comment by jaysoo** [comment] 2021-07-28 17:46
@jugglingcats I know why... there is a problem that isn't fixable without the patch.

https://github.com/nrwl/nx/pull/6529/files#diff-04e4095306c62e71c2dc3ec54f2aae7dfd400759d73bc3eaf0f50e7dee6731f5R79

The `*.hot-update.js` files shouldn't be included in the generated HTML.

Probably better to just wait for a patch rather than patching node_modules manually. I'll get the PR reviewed and see if we can release it soon.

**Closed** 2021-07-29 18:16 UTC
Labels: scope: react, type: bug

**Comment by Nightbr** [comment] 2021-07-30 07:16
Hey, thanks for the update!

I upgraded to Nx 12.6.3 but If I enable `"hmr": true` in the project.json of the React app, but no changes are applied. Perhaps it is linked to the libs I used (ChakraUI, ApolloClient, ...). I will try to dig in libs repository to see the HMR compatibility.

Still works without hmr with livereload BTW

**Comment by sc-mavirdol** [comment] 2021-08-05 13:48
I upgraded to Nx 12.6.4 from 12.6.0. If I set the ```hmr: true``` and run the serve command I get the following:

> Error: NormalModuleFactory.afterResolve (ReactRefreshPlugin) is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
