### ISSUE TITLE
generator doesn't yet support the existing TypeScript setup

### ISSUE THREAD

**Issue by marianzburlea** [nrwl/nx#28651] opened 2024-10-26 12:39 UTC
### Current Behavior

Unable to generate new library using NX 20.

![Image](https://github.com/user-attachments/assets/5f4fa009-3033-44da-ac2b-816a4d849669)

```
~/fun/test/wow-ui on  main ⌚ 16:31:43
$ pnpm install @nx/next @nx/react -D -w
 WARN  2 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6
Packages: +581
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 965, reused 905, downloaded 7, added 581, done

devDependencies:
+ @nx/next 20.0.6
+ @nx/react 20.0.6

Done in 13.9s

~/fun/test/wow-ui on  main! ⌚ 16:32:07
$ nx g lib
✔ Which generator would you like to use? · @nx/next:library

 NX  Generating @nx/next:library

✔ Which directory do you want to create the library in? · lib
✔ Which stylesheet format would you like to use? · css

 NX   The "@nx/next:library" generator doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/next:library" generator. We'll soon release a new version of Nx with support for it.


~/fun/test/wow-ui on  main! ⌚ 16:35:18
```

### Expected Behavior

To generate a NextJS library in the `lib` folder as per my instructions.

### Steps to Reproduce

1. `pnpm install @nx/next @nx/react -D -w`
2. `nx g lib`

### Nx Report

 NX   The "@nx/next:library" generator doesn't yet support the existing TypeScript setup

We're working hard to support the existing TypeScript setup with the "@nx/next:library" generator. We'll soon release a new version of Nx with support for it.

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment] 2024-10-28 12:59
Closing as duplicate of #28652

**Closed by Coly010** 2024-10-28 12:59 UTC
Labels: type: bug
