### ISSUE TITLE
Error while attempting to generate library - Cannot find module '@schematics/angular/utility/route-utils'

### ISSUE THREAD

**Issue by st-clair-clarke** [nrwl/nx#657] opened 2018-07-31 09:09 UTC
Hi,
I upgraded from 
`@angular/cli": "^6.0.4" to @angular/cli": "^6.1.0".`

 I also upgraded to

`@nrwl/schematics": "^6.1.1"`

Now when I attempt to generate a libarary with the command,

`ng g lib shared-feature-store --prefix=medsoft --tags=shared,experimental`

...I am recieving the following error:

```
Cannot find module '@schematics/angular/utility/route-utils'
Error: Cannot find module '@schematics/angular/utility/route-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (J:\workspace\medsoft\node_modules\@nrwl\schematics\src\collection\library\index.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

My previous version ran fine.

Hope you can help. Thanks.

Cheers

**Comment by FrozenPandaz** [comment] 2018-07-31 15:00
Thank you for reporting.

Closing as a duplicate of https://github.com/nrwl/nx/issues/645 and will be fixed soon. Please follow the updates there.

**Closed by FrozenPandaz** 2018-07-31 15:00 UTC
Labels: duplicate
