### ISSUE TITLE
Upgrading nx from v16.1.0 to the latest version breaks serving nestjs apps

### ISSUE THREAD

**Issue by ElecTreeFrying** [nrwl/nx#16908] opened 2023-05-10 12:16 UTC
### Current Behavior

I updated to the latest version from v16.1.0, and now I'm getting this error. I also tried versions 16.1.1 to 16.1.4, but they also give this error. However, rolling back to v16.1.0 resolved the issue.

```
Error: Only URLs with a scheme in: file, data are supported by the default ESM loader. 
On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```

### Expected Behavior

Serve nestjs app successfully

### Steps to Reproduce

1. serve a nestjs app

### Nx Report

```shell
Node   : 16.20.0
   OS     : win32 x64
   npm    : 9.6.5
   Hasher : Native

   nx (global)        : 16.0.3
   nx                 : 16.1.2
   @nx/js             : 16.1.2
   @nx/jest           : 16.1.2
   @nx/linter         : 16.1.2
   @nx/workspace      : 16.1.2
   @nx/angular        : 16.1.2
   @nx/cypress        : 16.1.2
   @nx/devkit         : 16.1.2
   @nx/eslint-plugin  : 16.1.2
   @nx/nest           : 16.1.2
   @nx/node           : 16.1.2
   @nrwl/tao          : 16.1.2
   @nx/webpack        : 16.1.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.0.0
   @nguniversal/common         : 16.0.0
   @nguniversal/express-engine : 16.0.0
```

### Failure Logs

```shell
Error message: Only URLs with a scheme of 'file' or 'data' are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by maxfriedmann** [comment] 2023-05-10 12:26
@ElecTreeFrying duplicate of #16847?

**Closed** 2023-05-10 12:50 UTC
Labels: type: bug, scope: node
