### ISSUE TITLE
True ESM Support

### ISSUE THREAD

**Issue by Arilas** [nrwl/nx#20198] opened 2023-11-11 00:13 UTC
Nx is good tool, but it lacks support of ESM schematics and plugins. Right now the only way to implement a new plugin is to compile it to CommonJS. This brings a lot of problems, like some modules is not working (because they're true ESM packages, e.g. chalk v5).

So I think it's time to start supporting ESM.

What shouldn't support ESM:
1. Task Runners. Runners is `require`d in `run-command` and it's an easy task to add `import(modulePath)` as a default way, with fallback to require
2. Executors. Executors written in pure ESM doesn't work, because they're also require'd, so it's time to `import` them.
3. Generators.

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I would like to see ability to use ESM plugins with Nx

## Motivation
JS community is moving to ESM faster and faster, so it's time to support this movement

**Comment by AgentEnder** [comment] 2023-11-16 23:10
Closing as a duplicate of #15682

**Closed by AgentEnder** 2023-11-16 23:10 UTC
Labels: type: feature
