### ISSUE TITLE
Angular component generator don’t follow nx.json settings

### ISSUE THREAD

**Issue by mIaborde** [nrwl/nx#11161] opened 2022-07-15 13:50 UTC
## Current Behavior

`nx g @nrwl/angular:component myComponent` don’t follow `nx.json` `@nrwl/angular:component generator` settings.

**nx.json :**

```json
{
  ...default settings

  "generators": {
    "@nrwl/angular:application": {
      "style": "scss",
      "linter": "eslint",
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "jest"
    },
    "@nrwl/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "my-app"
}

```

**Command :**

```bash
nx g @nrwl/angular:component myComponent
```

**Result :**

```bash
CREATE apps/my-app/src/app/button/button.component.css
CREATE apps/my-app/src/app/button/button.component.html
CREATE apps/my-app/src/app/button/button.component.spec.ts
CREATE apps/my-app/src/app/button/button.component.ts
```

## Expected Behavior

**Command :**

```bash
nx g @nrwl/angular:component myComponent
```

**Result :**

```bash
CREATE apps/my-app/src/app/button/button.component.scss
CREATE apps/my-app/src/app/button/button.component.html
CREATE apps/my-app/src/app/button/button.component.spec.ts
CREATE apps/my-app/src/app/button/button.component.ts
```

## Steps to Reproduce

Generate a new nx workspace :

```bash
npx create-nx-workspace@14.4.0 \
    --name=my-org \
    --appName=my-app \
    --packageManager=npm \
    --preset=angular \
    --style=scss \
    --nxCloud=false
```

And run default component generator :

```bash
nx g @nrwl/angular:component myComponent
```

Same process run well on @nrwl/nx@13.x.

**Comment by leosvelperez** [comment] 2022-07-15 13:59
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/11004. Please note that the issue was already fixed in https://github.com/nrwl/nx/pull/11006 and should be released soon. Keep an eye on the releases to get the fix.

**Closed by leosvelperez** 2022-07-15 13:59 UTC
Labels: type: bug

**Comment by mIaborde** [comment] 2022-07-16 10:32
Oh my bad, thank you for your amazing work !
