### ISSUE TITLE
Failed to resolve module specifier "module". when importing @microsoft/signalr into nx app created in react

### ISSUE THREAD

**Issue by LeonieNFarmer** [nrwl/nx#18208] opened 2023-07-20 04:37 UTC
### Current Behavior

When I import @microsoft/signalr into a react nx app I get the following errors:

Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".

Uncaught ChunkLoadError: Loading chunk vendors-node_modules_microsoft_signalr_dist_esm_index_js failed.
(missing: http://localhost:4202/vendors-node_modules_microsoft_signalr_dist_esm_index_js.js)
    at __webpack_require__.f.j (jsonp chunk loading:27:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
    at Object.get (sharing:40:1)
    at get (consumes:80:1)
    at getStrictSingletonVersion (consumes:50:1)
    at consumes:133:1
    at consumes:85:1
    at webpack/sharing/consume/default/@microsoft/signalr/@microsoft/signalr (consumes:139:1)

### Expected Behavior

Expect nx apps to work with signalR

### GitHub Repo

https://github.com/LeonieNFarmer/nxwithsignalr

https://github.com/LeonieNFarmer/nxv16.5.3withsignalr

### Steps to Reproduce

1. Create a react nx application with module federation following this tutorial: https://nx.dev/recipes/module-federation/faster-builds (I have tested with latest version of nx and back to version 14.5.4)
2. Once this is working. Add signalr  on command line npm i @microsoft/signalr
3. Add a small test to Cart App as follows:

```
import styled from 'styled-components';
import NxWelcome from './nx-welcome';
import { HubConnectionState } from '@microsoft/signalr';

const StyledApp = styled.div`
  // Your style here
`;

export function App() {
  return (
    <StyledApp>
      {HubConnectionState.Connected}
      <NxWelcome title="cart" />
    </StyledApp>
  );
}

export default App;
```
4. Run you app again and check in cart. If you don't get the error (occasionally it works), delete package.lock and node_modules and re-install them. Run again.

### Nx Report

```shell
Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin x64
   npm  : 8.11.0
   
   nx : 14.5.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.5.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.4
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.5.4
   @nrwl/workspace : 14.5.4
   typescript : 4.7.2
   ---------------------------------------
   Community plugins:

(node:97967) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/foo/Projects/test2/nxversion14/node_modules/tslib/package.json.
```

### Failure Logs

```shell
cart:1 Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".

Uncaught ChunkLoadError: Loading chunk vendors-node_modules_microsoft_signalr_dist_esm_index_js failed.
(missing: http://localhost:4202/vendors-node_modules_microsoft_signalr_dist_esm_index_js.js)
    at __webpack_require__.f.j (jsonp chunk loading:27:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
    at Object.get (sharing:40:1)
    at get (consumes:80:1)
    at getStrictSingletonVersion (consumes:50:1)
    at consumes:133:1
    at consumes:85:1
    at webpack/sharing/consume/default/@microsoft/signalr/@microsoft/signalr (consumes:139:1)

The above error occurred in the <Route.Provider> component:

    at Routes (http://localhost:4200/vendors-node_modules_react-router-dom_index_js.js:2158:5)
    at Suspense
    at App
    at Router (http://localhost:4200/vendors-node_modules_react-router-dom_index_js.js:2092:15)
    at BrowserRouter (http://localhost:4200/vendors-node_modules_react-router-dom_index_js.js:936:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

We were successfully using nx with signalR up to approximately 2 weeks ago. Then this error started to happen when running on localhost.

I have reproduced it with different nx versions and different signalr version combinations. 

I think this may be caused by a change to a dependency. People on my team who haven't deleted and reinstalled package-lock and node-modules don't seem to have it. 

If I run in with --configuration=production flag, I don't get the bug.

**Comment by LeonieNFarmer** [comment] 2023-07-21 00:08
After further investigation, I am able to reproduce this bug in angular as well as react. I think it is a problem with @nx/web

**Comment by rajprakashyadav** [comment] 2023-07-28 12:26
@LeonieNFarmer Same issue with nx latest version for Angular. Did you able to resolve it? Its working with --configuration=production

**Comment by LeonieNFarmer** [comment] 2023-07-30 21:29
> @LeonieNFarmer Same issue with nx latest version for Angular. Did you able to resolve it? Its working with --configuration=production

Hi, I have not been able to solve it. After investigating it for a while I believe that the problem is with one of the dependencies within @nx/web. They do not have exact dependencies in this module they use ~ and ^ which mean the dependencies can be different each time you install the same version of @nx/web (that is very frustrating because it means we can't fix by going back versions - they continue to be broken as they import the updated breaking dependency).  I think it can only be solved by one of the @nx team finding the breaking dependency either fixing it and/or releasing a version with an exact dependency reference to a non-breaking version.

**Comment by JeanMeche** [comment] 2023-08-04 12:26
I'm x-post here, a similar issue has been reported here : https://github.com/angular-architects/module-federation-plugin/issues/350  Indeed it looks like a dependency issue !

**Comment by anoam99** [comment] 2023-08-08 07:26
I encountered a comparable problem while working with an nx NodeJS application. The issue stemmed from a function named requireFunc in the signalR's dist folder. During the build process, nx failed to recognize the require function and couldn't resolve all signalR dependencies. To resolve this, I replaced requireFunc with require and then executed npx patch-package @microsoft/signalR to save the modifications. Remember to run npx patch-package after each npm install.


I hope this will help you

**Comment by LeonieNFarmer** [comment] 2023-08-09 21:33
> Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".

Hi @alexandre-dev29 please can you share your npx patch-package code?

**Comment by anoam99** [comment] 2023-08-09 22:06
@LeonieNFarmer 

```
diff --git a/node_modules/@microsoft/signalr/dist/browser/signalr.js b/node_modules/@microsoft/signalr/dist/browser/signalr.js
index 182c6ec..9b879c8 100644
--- a/node_modules/@microsoft/signalr/dist/browser/signalr.js
+++ b/node_modules/@microsoft/signalr/dist/browser/signalr.js
@@ -2422,8 +2422,8 @@ class HttpConnection {
             // In order to ignore the dynamic require in webpack builds we need to do this magic
             // @ts-ignore: TS doesn't know about these names
             const requireFunc =  true ? require : 0;
-            webSocketModule = requireFunc("ws");
-            eventSourceModule = requireFunc("eventsource");
+            webSocketModule = require("ws");
+            eventSourceModule = require("eventsource");
         }
         if (!Platform.isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
             options.WebSocket = WebSocket;
diff --git a/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js b/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js
index 7c3b816..70dce89 100644
--- a/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js
+++ b/node_modules/@microsoft/signalr/dist/cjs/HttpConnection.js
@@ -37,8 +37,8 @@ class HttpConnection {
             // In order to ignore the dynamic require in webpack builds we need to do this magic
             // @ts-ignore: TS doesn't know about these names
             const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
-            webSocketModule = requireFunc("ws");
-            eventSourceModule = requireFunc("eventsource");
+            webSocketModule = require("ws");
+            eventSourceModule = require("eventsource");
         }
         if (!Utils_1.Platform.isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
             options.WebSocket = WebSocket;
diff --git a/node_modules/@microsoft/signalr/dist/esm/HttpConnection.js b/node_modules/@microsoft/signalr/dist/esm/HttpConnection.js
index bec7c58..7fd9211 100644
--- a/node_modules/@microsoft/signalr/dist/esm/HttpConnection.js
+++ b/node_modules/@microsoft/signalr/dist/esm/HttpConnection.js
@@ -34,8 +34,8 @@ export class HttpConnection {
             // In order to ignore the dynamic require in webpack builds we need to do this magic
             // @ts-ignore: TS doesn't know about these names
             const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
-            webSocketModule = requireFunc("ws");
-            eventSourceModule = requireFunc("eventsource");
+            webSocketModule = require("ws");
+            eventSourceModule = require("eventsource");
         }
         if (!Platform.isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
             options.WebSocket = WebSocket;
diff --git a/node_modules/@microsoft/signalr/dist/webworker/signalr.js b/node_modules/@microsoft/signalr/dist/webworker/signalr.js
index 182c6ec..9b879c8 100644
--- a/node_modules/@microsoft/signalr/dist/webworker/signalr.js
+++ b/node_modules/@microsoft/signalr/dist/webworker/signalr.js
@@ -2422,8 +2422,8 @@ class HttpConnection {
             // In order to ignore the dynamic require in webpack builds we need to do this magic
             // @ts-ignore: TS doesn't know about these names
             const requireFunc =  true ? require : 0;
-            webSocketModule = requireFunc("ws");
-            eventSourceModule = requireFunc("eventsource");
+            webSocketModule = require("ws");
+            eventSourceModule = require("eventsource");
         }
         if (!Platform.isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {
             options.WebSocket = WebSocket;
diff --git a/node_modules/@microsoft/signalr/src/HttpConnection.ts b/node_modules/@microsoft/signalr/src/HttpConnection.ts
index 375902b..34dc775 100644
--- a/node_modules/@microsoft/signalr/src/HttpConnection.ts
+++ b/node_modules/@microsoft/signalr/src/HttpConnection.ts
@@ -88,9 +88,8 @@ export class HttpConnection implements IConnection {
         if (Platform.isNode && typeof require !== "undefined") {
             // In order to ignore the dynamic require in webpack builds we need to do this magic
             // @ts-ignore: TS doesn't know about these names
-            const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
-            webSocketModule = requireFunc("ws");
-            eventSourceModule = requireFunc("eventsource");
+            eventSourceModule = require("eventsource");
+            webSocketModule = require("ws");
         }
 
         if (!Platform.isNode && typeof WebSocket !== "undefined" && !options.WebSocket) {

```

**Comment by Erbenos** [comment] 2023-09-06 08:23
Same happens in Angular

**Comment by statyan** [comment] 2023-10-05 21:39
Had the same issue with nx@16 and @microsoft/signalr.
I removed "ts-loader" package from devDeps, deleted package-lock.json and node_modules and re-installed everything once again, that did the trick. Also ensure for Angular16 projects you have "typescript": "4.9.5".

**Comment by bhiapp4** [comment] 2023-10-30 13:35
Could you please provide an update on this ?

**Comment by aleix10kst** [comment] 2023-11-15 15:51
@bhiapp4 we've just come across the same issue, and we've upgraded the @microsoft/signalr library to v8 (they just released the new version 18 hours ago). Now the issue is gone.

**Comment by ndcunningham** [comment] 2024-07-25 17:13
Closed as this has been address by the external lib

**Closed by ndcunningham** 2024-07-25 17:13 UTC
Labels: type: bug, scope: react
