### ISSUE TITLE
Nx run command with commas separated configuration is broken

### ISSUE THREAD

**Issue by Rafarel** [nrwl/nx#17275] opened 2023-05-28 11:00 UTC
### Current Behavior

When I run `ng run app:build --configuration=development,en` it does run the `ng run app:build:development,fr` that is my `defaultConfiguration` in my `build` target.

The `--configuration` argument is ignored if there is more than one configuration passed to it.

If I run `ng run app:build --configuration=en` it runs `ng run app:build:en` so that is ok with a single configuration it is able to override the `defaultConfiguration`.

### Expected Behavior

Being able to pass multiple configurations to the `--configuration` argument

### Steps to Reproduce

1. Have a build task with several configuration.
2. Try to run multiple configuration (to merge the options of an environment + a i18n configuration for exemple)

### Nx Report

```shell
Node   : 18.13.0
   OS     : darwin arm64
   npm    : 8.19.3
   Hasher : Native
   
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/express        : 16.2.1
   @nx/nest           : 16.2.1
   @nx/node           : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/webpack        : 16.2.1
   nx-cloud           : 16.0.5
   typescript         : 4.8.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.12.1
   @nguniversal/builders            : 15.1.0
   @nguniversal/express-engine      : 15.0.0
   ng-extract-i18n-merge            : 2.4.0
   nx-stylelint                     : 15.0.0
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Here is my build target

```
"build": {
      "executor": "@angular-devkit/build-angular:browser",
      "outputs": ["{options.outputPath}"],
      "options": {
        "outputPath": "dist/apps/app",
        "index": "apps/app/src/index.html",
        "main": "apps/app/src/main.ts",
        "polyfills": "apps/app/src/polyfills.ts",
        "tsConfig": "apps/app/tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "assets": [
          "apps/app/src/favicon.ico",
          "apps/app/src/manifest.webmanifest",
          "apps/app/src/assets",
          {
            "glob": "**/*",
            "input": "assets/shared",
            "output": "assets/shared"
          }
        ],
        "styles": ["apps/app/src/styles/styles.scss"],
        "stylePreprocessorOptions": {
          "includePaths": ["apps/app/src/styles"]
        },
        "scripts": []
      },
      "configurations": {
        "production": {
          "budgets": [
            {
              "type": "initial",
              "maximumWarning": "500kb",
              "maximumError": "1mb"
            },
            {
              "type": "anyComponentStyle",
              "maximumWarning": "2kb",
              "maximumError": "4kb"
            }
          ],
          "outputHashing": "all",
          "fileReplacements": [
            {
              "replace": "apps/app/src/environments/environment.ts",
              "with": "apps/app/src/environments/environment.prod.ts"
            }
          ]
        },
        "staging": {
          "outputHashing": "all",
          "fileReplacements": [
            {
              "replace": "apps/app/src/environments/environment.ts",
              "with": "apps/app/src/environments/environment.staging.ts"
            }
          ]
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true
        },
        "fr": {
          "localize": ["fr"],
          "baseHref": "/fr/"
        },
        "en": {
          "localize": ["en"],
          "baseHref": "/en/"
        }
      },
      "defaultConfiguration": "development,fr"
    }

**Comment by leosvelperez** [comment] 2023-05-29 08:33
Duplicate of https://github.com/nrwl/nx/issues/2839

**Closed by leosvelperez** 2023-05-29 08:33 UTC
Labels: type: bug
