### ISSUE TITLE
Add schematic to add e2e tests to an existing application

### ISSUE THREAD

**Issue by mrmeku** [nrwl/nx#1593] opened 2019-07-18 20:03 UTC
This is a feature request. 

Context: 
There already exists a schematic to generate an angular application for @nrwl/angular and @nrwl/react. 
This schematic generates 2 applications, the client and the e2e test suite. 

Feature request:
I think we should expose the schematic to generate an e2e test suite by itself such that users can split out e2e tests for sharding purposes or whatever reason they feel like

**Comment by vsavkin** [comment] 2019-12-05 14:58
Duplicate of this: https://github.com/nrwl/nx/issues/987

**Closed by vsavkin** 2019-12-05 14:58 UTC
Labels: type: feature
