### ISSUE TITLE
Peer dependency warning - jasmine-marbles

### ISSUE THREAD

**Issue by rajeev-john** [nrwl/nx#847] opened 2018-10-24 15:05 UTC
Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.3.1", would install "0.4.0").

Environment: Angular 7
Nrwl/nx: 6.4

Trying to update all the packages of the project using ng update --all=true

Package "@nrwl/nx" has an incompatible peer dependency to "jasmine-marbles" (requires "0.3.1", would install "0.4.0").
Incompatible peer dependencies found. See above.

package.json

> {
  "name": "tts.web-apps",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26",
    "@nrwl/nx": "6.4.0",
    "@ngrx/effects": "6.1.0",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0"
  },
  "devDependencies": {
    "@angular/cli": "7.0.2",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@angular-devkit/build-angular": "~0.10.0",
    "@ngrx/store-devtools": "6.1.0",
    "ngrx-store-freeze": "0.2.4",
    "@nrwl/schematics": "6.4.0",
    "jasmine-marbles": "0.3.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.3",
    "prettier": "1.13.7"
  }
}

**Comment by bcabanes** [comment] 2018-10-25 20:42
Hi @rajeev-john,
We will close this issue because it is a duplicate of #793 #804 addressed by #852.
It will be available in the next release.

**Closed by bcabanes** 2018-10-25 20:42 UTC

**Comment by rajeev-john** [comment] 2018-10-25 21:10
Thanks a lot for that information.

**Comment by sryzycki** [comment] 2019-01-15 17:02
@bcabanes Hi ya,

FYI, the very same warning message blocks running `ng update` on Nx `7.2.0`. Could it be due to Nx requiring a specific version `0.4.0` instead `~0.4.0`?

Kind of didn't want to create yet another ticket for that since there are three related to this peer dependency :)
