### ISSUE TITLE
Default Next.js app fails to build in brand new workspace

### ISSUE THREAD

**Issue by tundera** [nrwl/nx#9768] opened 2022-04-09 14:34 UTC
## Current Behavior

After creating a new Nx workspace with a Next.js application, the Next.js app fails to build even though no changes have been made to the app.

## Expected Behavior

Builds should succeed for new, unchanged Next.js apps in a freshly generated workspace.

## Steps to Reproduce

Here's a reproduction of the issue using [Codesandbox](https://codesandbox.io/s/still-dust-b07p6i?file=/sandbox.config.json). The Next.js app will run fine in the sandbox, but opening a new terminal window and attempting to build to will result in an error.

### Failure Logs

![CleanShot 2022-04-09 at 10 18 36](https://user-images.githubusercontent.com/61833561/162578161-5281871e-d46f-4d6a-89f9-618ef3215199.gif)

### Environment

```sh
 >  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   yarn : 1.22.17
   
   nx : 13.10.1
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.10.1
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.1
   @nrwl/eslint-plugin-nx : 13.10.1
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.1
   @nrwl/js : 13.10.1
   @nrwl/linter : 13.10.1
   @nrwl/nest : Not Found
   @nrwl/next : 13.10.1
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 13.2.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.10.1
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.1
   @nrwl/web : 13.10.1
   @nrwl/workspace : 13.10.1
   typescript : 4.6.3
   rxjs : 6.6.7
   ---------------------------------------
   Community plugins:

Done in 0.77s.
```

**Comment by gioragutt** [comment] 2022-04-09 16:32
Idk if this is related, I saw there might be a version mismatch between react and types/react after the react18 migration, perhaps this is the cause?
Could you check your package json versions of react packages?

**Comment by VincentThomas06** [comment] 2022-04-09 23:42
I think the error may be in the tsconfig.json. change jsx-transpilation to `preserve` or `react-jsx`

**Comment by rldnrl** [comment] 2022-04-10 02:35
I also got an error in the same part. This is because the `@type/react` and `@types/react-dom` versions are not updated. I manually updated to fix this issue.

**Comment by tundera** [comment] 2022-04-10 14:30
@rldnrl Yep, this is what will fix the issue. Just upgrade the `@types/react` and `@types/react-dom` versions to latest and the build succeeds. So the fix should be to update the templates to use the new types packages for `react` and `react-dom`. Thanks!

**Comment by ndcunningham** [comment] 2022-06-02 13:56
Should be fixed with: https://github.com/nrwl/nx/pull/9767

If the problem still persist please feel free to open

**Closed by ndcunningham** 2022-06-02 13:56 UTC
Labels: type: bug, scope: nextjs
