### ISSUE TITLE
Can't build publishable lib which depends on other libs

### ISSUE THREAD

**Issue by imcvakt** [nrwl/nx#3518] opened 2020-08-13 16:58 UTC
## Current Behavior
Trying to build a a publishable lib with other libs as dependencies fail. 
NX latest version.
Preset: React

## Expected Behavior
I wanna create publishable react libs which has other dependencies (non publishable) 

## Steps to Reproduce

1. npx create-nx-workspace@latest
2. use react template
3. nx generate @nrwl/react:library --name=a --importPath=a --publishable --no-interactive
4. nx generate @nrwl/react:library --name=b --no-interactive
5. import lib b at lib a
6. nx build b

### Failure Logs
![image](https://user-images.githubusercontent.com/52280827/90163815-82eebd00-dd8e-11ea-8c83-0cce4802bd9b.png)

![image](https://user-images.githubusercontent.com/52280827/90163872-9732ba00-dd8e-11ea-8cf4-f45f875e9d55.png)

**Comment by MmtBkn** [comment] 2020-10-25 21:13
It seems like you'd need to pass --buildable to step 4 and manually add `paths` yo your publishable library's `tsconfig.json`

`{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "paths": {
      "@test/lib2": ["dist/libs/lib2"]
    }
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
`

**Comment by mandarini** [comment] 2020-11-06 12:37
Hi there @imcvakt ! Thanks for filing an issue!

Did you try the solution that @MmtBkn provided? I believe it should solve your issue. Let me know if this helps, and I can close this issue!

**Comment by mandarini** [comment] 2020-11-06 16:47
Hi there @imcvakt ! After talking with some of my colleagues, things cleared a bit.
Right now this is by design. Publishable libs can only depend on other publishable libs. 

So, to solve your issue, you can make them both publishable. If you make them both publishable, and then import `b` into `a`, then you can run `nx build a --with-deps` and it will work like a charm (no need to do anything else - no need for any manual editing).

I will close this issue for now, but please reopen if my suggestions did not solve your issue! Thanks again! :)

**Closed by mandarini** 2020-11-06 16:47 UTC
Labels: scope: react, type: bug

**Comment by imcvakt** [comment] 2020-11-24 01:37
Sorry for the late response. I will try to check @MmtBkn workaround and I come back with more info... Even after that reply :P @mandarini
