### ISSUE TITLE
nx release version(registry) fails on first version.

### ISSUE THREAD

**Issue by eladhaim** [nrwl/nx#20672] opened 2023-12-08 22:20 UTC
### Current Behavior

When i create a new package and use the nx release version command using the registry to get the latest version, if the package doesn't exists(first version) the publish fails with 
npm ERR! 404 Not Found - GET package_url - no such package available

### Expected Behavior

Have the option to "force" publish the package even if it doesn't exists yet.

### Steps to Reproduce

1. create a new package
2. use the default settings to release 
3. nx release version $version

### Nx Report

```shell
Node   : 18.16.1
   OS     : darwin-arm64
   pnpm   : 8.7.4
   
   nx (global)        : 17.1.3
   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/jest           : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/nest           : 17.0.3
   @nx/node           : 17.0.3
   @nx/plugin         : 17.0.3
   @nx/webpack        : 17.0.3
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   ---------------------------------------
   Local workspace plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JamesHenry** [comment] 2023-12-14 20:10
Duplicate of https://github.com/nrwl/nx/issues/19971

**Closed by JamesHenry** 2023-12-14 20:10 UTC
Labels: type: bug, scope: core
