### ISSUE TITLE
Problem with Vscode's NX extension on dev container macos

### ISSUE THREAD

**Issue by MartinPELCAT** [nrwl/nx#20067] opened 2023-11-06 14:52 UTC
### Current Behavior

Issue with latest nx update on vscode macos.

## Components version

- docker desktop : [4.25.0]
- vscode : [1.84.0]
- vscode devcontainer extension : [0.321.0]
- nx extension: [18.10.0]

## OS

- MacOs : [14.1]
- CPU architecture : M2

## Vscode user configuration

**Local** installed extension :
```
ms-vscode-remote.remote-containers
```

**Dev container** installed extension :

```
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
esbenp.prettier-vscode
GitLab.gitlab-workflow
GraphQL.vscode-graphql
GraphQL.vscode-graphql-syntax
mikestead.dotenv
ms-vsliveshare.vsliveshare
mtxr.sqltools
mtxr.sqltools-driver-pg
mutantdino.resourcemonitor
naumovs.color-highlight
nrwl.angular-console
PKief.material-icon-theme
redhat.vscode-yaml
styled-components.vscode-styled-components
wix.vscode-import-cost
```

</details>

## Relevant screenshots and/or logs
<img width="555" alt="image" src="https://github.com/nrwl/nx/assets/35460122/d99fd2bd-8582-425a-a101-08dd10e89b8f">

<details>
<summary>[Log of the output of "Extension Host (remove)"]</summary>

```
2023-11-06 14:43:49.726 [info] Extension host with pid 1288 started
2023-11-06 14:43:49.749 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Lock acquired.
2023-11-06 14:43:49.838 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-11-06 14:43:49.840 [info] ExtensionService#_doActivateExtension vscode.tunnel-forwarding, startup: false, activationEvent: 'onTunnel'
2023-11-06 14:43:49.841 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:49.841 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:50.415 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-11-06 14:43:50.416 [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
2023-11-06 14:43:50.416 [info] ExtensionService#_doActivateExtension mutantdino.resourcemonitor, startup: true, activationEvent: '*'
2023-11-06 14:43:50.416 [info] ExtensionService#_doActivateExtension naumovs.color-highlight, startup: true, activationEvent: '*'
2023-11-06 14:43:50.542 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-11-06 14:43:50.542 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-11-06 14:43:50.620 [info] ExtensionService#_doActivateExtension mtxr.sqltools-driver-pg, startup: true, activationEvent: '*'
2023-11-06 14:43:50.845 [info] ExtensionService#_doActivateExtension GraphQL.vscode-graphql, startup: true, activationEvent: 'workspaceContains:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js,ts,toml},**/graphql.config.{json,yaml,yml,js,ts,toml},**/package.json'
2023-11-06 14:43:51.496 [info] Eager extensions activated
2023-11-06 14:43:51.496 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension GitLab.gitlab-workflow, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:51.497 [info] ExtensionService#_doActivateExtension nrwl.angular-console, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:52.359 [info] Extension host with pid 1781 started
2023-11-06 14:43:52.359 [error] Error: EEXIST: file already exists, open '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock'
2023-11-06 14:43:52.362 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Could not acquire lock, checking if the file is stale.
2023-11-06 14:43:52.364 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': The pid 1288 appears to be gone.
2023-11-06 14:43:52.364 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Deleting a stale lock.
2023-11-06 14:43:52.375 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Lock acquired.
2023-11-06 14:43:52.391 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-11-06 14:43:52.392 [info] ExtensionService#_doActivateExtension vscode.tunnel-forwarding, startup: false, activationEvent: 'onTunnel'
2023-11-06 14:43:52.392 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:52.392 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:52.392 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
2023-11-06 14:43:52.499 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
2023-11-06 14:43:52.670 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-11-06 14:43:52.670 [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
2023-11-06 14:43:52.670 [info] ExtensionService#_doActivateExtension mutantdino.resourcemonitor, startup: true, activationEvent: '*'
2023-11-06 14:43:52.670 [info] ExtensionService#_doActivateExtension naumovs.color-highlight, startup: true, activationEvent: '*'
2023-11-06 14:43:52.849 [info] ExtensionService#_doActivateExtension mtxr.sqltools-driver-pg, startup: true, activationEvent: '*'
2023-11-06 14:43:52.949 [info] ExtensionService#_doActivateExtension GraphQL.vscode-graphql, startup: true, activationEvent: 'workspaceContains:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js,ts,toml},**/graphql.config.{json,yaml,yml,js,ts,toml},**/package.json'
2023-11-06 14:43:53.460 [info] Eager extensions activated
2023-11-06 14:43:53.460 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.460 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.460 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.461 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.461 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.461 [info] ExtensionService#_doActivateExtension GitLab.gitlab-workflow, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:53.461 [info] ExtensionService#_doActivateExtension nrwl.angular-console, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:54.285 [info] Extension host with pid 1926 started
2023-11-06 14:43:54.285 [error] Error: EEXIST: file already exists, open '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock'
2023-11-06 14:43:54.289 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Could not acquire lock, checking if the file is stale.
2023-11-06 14:43:54.291 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': The pid 1781 appears to be gone.
2023-11-06 14:43:54.291 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Deleting a stale lock.
2023-11-06 14:43:54.302 [info] Lock '/root/.vscode-server/data/User/workspaceStorage/4ab2827894c69acbba10065452eb4362/vscode.lock': Lock acquired.
2023-11-06 14:43:54.339 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-11-06 14:43:54.339 [info] ExtensionService#_doActivateExtension vscode.tunnel-forwarding, startup: false, activationEvent: 'onTunnel'
2023-11-06 14:43:54.339 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:54.339 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-11-06 14:43:54.340 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: false, activationEvent: 'onFileSystem:git', root cause: vscode.git
2023-11-06 14:43:54.464 [info] ExtensionService#_doActivateExtension vscode.git, startup: false, activationEvent: 'onFileSystem:git'
2023-11-06 14:43:54.682 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-11-06 14:43:54.682 [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
2023-11-06 14:43:54.683 [info] ExtensionService#_doActivateExtension mutantdino.resourcemonitor, startup: true, activationEvent: '*'
2023-11-06 14:43:54.683 [info] ExtensionService#_doActivateExtension naumovs.color-highlight, startup: true, activationEvent: '*'
2023-11-06 14:43:54.850 [info] ExtensionService#_doActivateExtension mtxr.sqltools-driver-pg, startup: true, activationEvent: '*'
2023-11-06 14:43:54.911 [info] ExtensionService#_doActivateExtension GraphQL.vscode-graphql, startup: true, activationEvent: 'workspaceContains:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js,ts,toml},**/graphql.config.{json,yaml,yml,js,ts,toml},**/package.json'
2023-11-06 14:43:55.363 [info] Eager extensions activated
2023-11-06 14:43:55.363 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension GitLab.gitlab-workflow, startup: false, activationEvent: 'onStartupFinished'
2023-11-06 14:43:55.364 [info] ExtensionService#_doActivateExtension nrwl.angular-console, startup: false, activationEvent: 'onStartupFinished'
```

</details>

### Expected Behavior

It works.

### Steps to Reproduce

1. Install. new version of nx extension in remote container 

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node : 16.20.0
   OS   : linux arm64
   npm  : 8.19.4
   
   nx (global)             : 17.0.3
   nx                      : 15.9.6
   @nrwl/js                : 15.9.6
   @nrwl/jest              : 15.9.6
   @nrwl/linter            : 15.9.6
   @nrwl/workspace         : 15.9.6
   @nrwl/cli               : 15.9.6
   @nrwl/cypress           : 15.9.6
   @nrwl/devkit            : 15.9.6
   @nrwl/eslint-plugin-nx  : 15.9.6
   @nrwl/express           : 15.9.6
   @nrwl/nest              : 15.9.6
   @nrwl/node              : 15.9.6
   @nrwl/react             : 15.9.6
   @nrwl/tao               : 15.9.6
   @nrwl/web               : 15.9.6
   @nrwl/webpack           : 15.9.6
   @nrwl/nx-cloud          : 16.3.0
   typescript              : 4.9.5
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mxmnci** [comment] 2024-01-26 13:46
Also experiencing this issue on Mac OS. Extension is unusable within a dev container.

**Comment by MaxKless** [comment] 2024-05-16 11:33
Hey! I'm closing this as a duplicate of https://github.com/nrwl/nx-console/issues/1978 in the nx console repo.
I've worked with the original author of that issue a lot to reproduce it but it always worked for me. 
If you could provide a minimal reproduction and more information about your workspace & system, that would be great to help me track it down! Let's continue the discussion over there.
Thank you :)

**Closed by MaxKless** 2024-05-16 11:33 UTC
Labels: type: bug, scope: misc
