### ISSUE TITLE
Name clashes between app name and project dependency break project graph

### ISSUE THREAD

**Issue by sebastian1607** [nrwl/nx#2662] opened 2020-03-14 17:24 UTC
## Expected Behavior

An app could have the same name as a dependency.

## Current Behavior

If the project has an app, which has the same name like a project dependency, the app isn't recognized as part of the project graph anymore. As a result of the corrupted project graph, goals like `lint` or `affected:dep-graph` fail.

### Steps to Reproduce

1. create an nx workspace
2. add an app with the name of a dependecy, e.g. prettier
3. add prettier as an dependency if it isn't already there
4. e.g., run the `lint` goal to see the results of the corrupted project graph
5. you will see that there are files which do not belong to any project (beacuse the app isn't known any longer)

**Of course I know this isn't an useful name for an app, but there could be name clashes which are more realistic**

### Context

```
  @nrwl/angular : 9.1.2
  @nrwl/cli : 9.1.2
  @nrwl/cypress : 9.1.2
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.2
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.2
  @nrwl/web : Not Found
  @nrwl/workspace : 9.1.2
  typescript : 3.7.5
```

**Comment by FrozenPandaz** [comment] 2020-05-21 14:55
Closing this issue as a duplicate of https://github.com/nrwl/nx/issues/2396 which there is a PR #2997 to fix.

**Closed by FrozenPandaz** 2020-05-21 14:55 UTC
Labels: scope: core, type: bug
