### ISSUE TITLE
Still problems with Jest and ESM

### ISSUE THREAD

**Issue by GeofoxCoding** [nrwl/nx#9052] opened 2022-02-21 11:30 UTC
## Current Behavior
In a fresh minimal angular workspace of current version I can't use a third party package which is built of ES modules and run tests with Jest.

```
> nx run main:test

 FAIL   main  apps/main/src/app/app.component.spec.ts
  ● Test suite failed to run
                                                                                                                                                         
    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
...
SyntaxError: Cannot use import statement outside a module

      1 | import { Component, OnInit, ViewEncapsulation } from '@angular/core';
      2 |
    > 3 | import WebMap from '@arcgis/core/WebMap';
        | ^
```

## Expected Behavior
Because Jest is an important part of nx setup and more and more third party packages are built of ES modules we need support of such packages. 

## Steps to Reproduce
Although this problem has been discussed and documented a lot, I creates a repo again with our necessary dependency as an example.
https://github.com/GeofoxCoding/nx-esm-jest

run 
npm install
nx test main

Is there any current solution how to get our dependency @arcgis/core working in Nx Jest setup?

**Comment by Coly010** [comment] 2022-02-22 11:19
This is a duplicate of the following: https://github.com/nrwl/nx/issues/7844

There is a workaround here: https://github.com/nrwl/nx/issues/7844#issuecomment-1016624608

Closing as it's a duplicate

**Closed by Coly010** 2022-02-22 11:19 UTC
Labels: type: bug, scope: angular
