### ISSUE TITLE
[Vite][pnpm workspaces]: The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by batusai513** [nrwl/nx#20153] opened 2023-11-09 15:50 UTC
### Current Behavior

When generating vite libraries and trying to install and import one library into another library I get `The package may have incorrect main/module/exports specified in its package.json` when trying to build the packages. This only happens when there is a `pnpm workspace`

### Expected Behavior

The build command should finish successfully

### GitHub Repo

https://github.com/batusai513/nx-libs-poc

### Steps to Reproduce

1. Clone the repo
2. run `pnpm install`
3. run `pnpm nx run-many -t build`

### Nx Report

```shell
Node   : 18.18.2
   OS     : darwin-arm64
   pnpm   : 8.9.2

   nx                 : 17.0.3
   @nx/js             : 17.0.3
   @nx/linter         : 17.0.3
   @nx/eslint         : 17.0.3
   @nx/workspace      : 17.0.3
   @nx/cypress        : 17.0.3
   @nx/devkit         : 17.0.3
   @nx/eslint-plugin  : 17.0.3
   @nx/react          : 17.0.3
   @nx/storybook      : 17.0.3
   @nrwl/tao          : 17.0.3
   @nx/vite           : 17.0.3
   @nx/web            : 17.0.3
   typescript         : 5.1.6
```

### Failure Logs

```shell
pnpm nx run-many -t build

    ✔  nx run lib-x:build:production  [existing outputs match the cache, left as is]
    ✔  nx run libs-proc:build:production  [existing outputs match the cache, left as is]

    ✖  nx run lib-y:build:production
       vite v4.3.9 building for production...
✓ 2 modules transformed.

       [vite:dts] Start generate declaration files...
       ✓ built in 692ms
       [vite:dts] Declaration files built in 786ms.

       [commonjs--resolver] Failed to resolve entry for package "@myorg/lib-x". The package may have incorrect main/module/exports specified in its package.json.

        >  NX   Failed to resolve entry for package "@myorg/lib-x". The package may have incorrect main/module/exports specified in its package.json.

          Pass --verbose to see the stacktrace.



 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 3 projects (2s)

    ✔    2/3 succeeded [2 read from cache]

    ✖    1/3 targets failed, including the following:
         - nx run lib-y:build:production
```

### Package Manager Version

8.9.2

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by batusai513** [comment] 2023-12-06 18:29
Related to https://github.com/nrwl/nx/issues/20520

**Comment by teofilomonteiro** [comment] 2024-01-02 10:56
I left a comment here https://github.com/nrwl/nx/issues/19149#issuecomment-1873872347 maybe can solve your issue.

**Comment by MBelniak** [comment] 2024-04-03 15:06
Maybe this will help in your case? https://github.com/nrwl/nx/issues/18931#issuecomment-2034872283

**Comment by Coly010** [comment] 2024-05-16 10:57
Closing as duplicate of https://github.com/nrwl/nx/issues/20520

**Closed by Coly010** 2024-05-16 10:57 UTC
Labels: type: bug, scope: bundlers
