### ISSUE TITLE
Incompatible with eslint-config-prettier@8

### ISSUE THREAD

**Issue by binary64** [nrwl/nx#4859] opened 2021-02-22 14:44 UTC
```bash
npx create-nx-workspace nx-demo-3 --packageManager=yarn --style=less --nx-cloud=false --interactive=false --preset=empty --linter=eslint
cd nx-demo-3
yarn add -D @nrwl/jest @nrwl/node @nrwl/react @nrwl/next 
nx g @nrwl/next:app web
nx g @nrwl/next:app web2
nx lint web
```
works
but do
```
yarn upgrade --latest
nx lint web
```
shows error
```
> nx run web:lint 

Linting "web"...
Failed to load config "prettier/@typescript-eslint" to extend from.
Referenced from: /home/user/PhpstormProjects/nx-demo-3/node_modules/@nrwl/eslint-plugin-nx/src/index.js
```

**Comment by vsavkin** [comment] 2021-02-22 14:57
Thank you for submitting the issue. I believe it is a duplicate of this: https://github.com/nrwl/nx/issues/4856 so I'm going to close it. We are going to look at it soon.

**Closed by vsavkin** 2021-02-22 14:57 UTC
Labels: type: bug
