### ISSUE TITLE
nx migrate @angular/core doesn't update all packages

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#5648] opened 2021-05-13 09:32 UTC
## Current Behavior
running `nx migrate @angular/core`only updates package.json for @angular/core and not for all other @angular packages
## Expected Behavior
The behavior should be the same as when calling ng update @angular/core

### Environment

  Node : 14.16.0
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : 12.2.0
  @nrwl/next : Not Found
  @nrwl/node : 12.2.0
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : 12.2.0
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.5

**Comment by intellix** [comment] 2021-05-13 09:50
**Before:**
```
ng update @angular/core @angular/cli
```

**After:**
```
nx migrate latest
nx migrate @nrwl/nx-cloud
nx migrate @angular-devkit/build-angular
nx migrate @angular/animations
nx migrate @angular/cdk
nx migrate @angular/cli
nx migrate @angular/common
nx migrate @angular/compiler
nx migrate @angular/compiler-cli
nx migrate @angular/core
nx migrate @angular/flex-layout
nx migrate @angular/forms
nx migrate @angular/language-service
nx migrate @angular/material
nx migrate @angular/platform-browser
nx migrate @angular/platform-browser-dynamic
nx migrate @angular/router
nx migrate @angular/service-worker
nx migrate @angular/animations
nx migrate @angular/common
nx migrate @angular/compiler
nx migrate @angular/core
nx migrate @angular/forms
nx migrate @angular/localize
nx migrate @angular/platform-browser
nx migrate @angular/platform-browser-dynamic
nx migrate @angular/router

nx migrate --run-migrations=migrations.json
```

**Comment by mlebarron** [comment] 2021-05-26 16:29
@intellix my experience was every time I run `nx migrate <whatever>` instead of adding to the migrations.json file it overwrote it, which made it even worse.

**Comment by the-ult** [comment] 2021-08-03 08:15
The `@angular/cdk` and `@angular/material` packages are ignored as well

**Comment by KimBum** [comment] 2021-10-01 11:21
Same happens for `nx migrate latest`. As far as I can tell it does not update any other packages (even @nrwl ones) as long as the @nrwl/workspace package is already up to date. I tested that by manually downgrading @nrwl/workspace and then running `yarn nx migrate latest`. And voila, all related packages are now actually checked for the latest version.

### Output before with @nrwl/workspace@12.9.0
```yarn run v1.22.5
$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/workspace@12.9.0

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
Done in 29.14s.
```

### Output after downgrade of only @nrwl/workspace to @12.7.2
```yarn run v1.22.5
$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/angular@12.9.0
Fetching @nrwl/cypress@12.9.0
Fetching @nrwl/eslint-plugin-nx@12.9.0
Fetching @nrwl/linter@12.9.0
Fetching @nrwl/storybook@12.9.0
Fetching @nrwl/workspace@12.9.0

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
Done in 99.17s.
```

### Output after downgrade of only @nrwl/workspace and @nrwl/angular to @12.7.2
```yarn run v1.22.5
$ nx migrate latest
Fetching meta data about packages.
It may take a few minutes.
Fetching @nrwl/workspace@latest
Fetching @nrwl/angular@12.9.0
Fetching @nrwl/cypress@12.9.0
Fetching @nrwl/eslint-plugin-nx@12.9.0
Fetching @nrwl/linter@12.9.0
Fetching @nrwl/storybook@12.9.0
Fetching @ngrx/store@~12.4.0
Fetching @ngrx/effects@~12.4.0
Fetching @ngrx/entity@~12.4.0
Fetching @ngrx/router-store@~12.4.0
Fetching @ngrx/store-devtools@~12.4.0
Fetching @ngrx/component-store@~12.4.0
Fetching @angular/cli@~12.2.0
Fetching @angular-devkit/build-angular@~12.2.0
Fetching @angular-devkit/build-optimizer@^0.1202.0
Fetching @angular/core@^12.2.0
Fetching @angular/common@^12.2.0
Fetching @angular/forms@^12.2.0
Fetching @angular/compiler@^12.2.0
Fetching @angular/compiler-cli@^12.2.0
Fetching @angular/platform-browser@^12.2.0
Fetching @angular/platform-browser-dynamic@^12.2.0
Fetching @angular/platform-server@^12.2.0
Fetching @angular/router@^12.2.0
Fetching @angular/upgrade@^12.2.0
Fetching @angular/language-service@^12.2.0
Fetching @angular/animations@^12.2.0
Fetching ng-packagr@~12.2.0
Fetching typescript@~4.3.5
Fetching @nrwl/workspace@12.9.0
Fetching @ngrx/store@12.4.0
Fetching @ngrx/effects@12.4.0
Fetching @ngrx/entity@12.4.0
Fetching @ngrx/router-store@12.4.0
Fetching @ngrx/store-devtools@12.4.0
Fetching @ngrx/component-store@12.4.0
Fetching @angular/cli@12.2.7
Fetching @angular-devkit/build-angular@12.2.7
Fetching @angular-devkit/build-optimizer@0.1202.0
Fetching @angular/core@12.2.0
Fetching @angular/common@12.2.0
Fetching @angular/forms@12.2.0
Fetching @angular/compiler@12.2.0
Fetching @angular/compiler-cli@12.2.0
Fetching @angular/platform-browser@12.2.0
Fetching @angular/platform-browser-dynamic@12.2.0
Fetching @angular/platform-server@12.2.0
Fetching @angular/router@12.2.0
Fetching @angular/upgrade@12.2.0
Fetching @angular/language-service@12.2.0
Fetching @angular/animations@12.2.0
Fetching ng-packagr@12.2.2
Fetching typescript@4.3.5

>  NX  The migrate command has run successfully.

- package.json has been updated
- migrations.json has been generated

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- Run 'nx migrate --run-migrations'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
Done in 219.90s.
```

So it also seems like when any package in the list fulfills the version held by nx, the update process just stops.

Not sure if somehow the way dependency update work has changed, but documentation should also be updated in that case. Because currently it does say: 
> Not only does nx migrate update you to the latest version of Nx, but it also updates the versions of dependencies that we support and test such as Jest and Cypress. 

Which obviously does not seem to be the case anymore. But as Nx still acts as a wrapper, it should in my opinion actually update all dependencies. Or at least it should give an option to force update check on all dependencies.

If my findings are not related to this issue, please to tell me, as I would create a separate issue for this then.

**Comment by KimBum** [comment] 2021-10-04 12:29
Just saw this has been heavily requested for a while now. They created a feature request for it earlier this year (#4575), but nothing has happened yet.

**Comment by synth3** [comment] 2021-10-04 14:53
@KimBum that sounds like a feasible hackaround - how did you do the downgrade?

The following was not enough for me:

```bash
nx migrate @nrwl/workspace@12.7.2
nx migrate @nrwl/angular@12.7.2
```

**Comment by Den-dp** [comment] 2021-11-11 22:37
For Powershell users proposed workaround will look like this:
```powershell
nx migrate latest
$env:FORCE_NG_UPDATE='true'; ng update
```

**Comment by minijus** [comment] 2021-12-12 19:02
This issue is duplicate of #4575. The root cause of why `nx migrate` bumps only specified package is that it does not respect `packageGroup` metadata which is normally  taken into consideration during `ng update`

**Comment by minhhn999** [comment] 2021-12-14 17:23
i have the same problem with nx version 13.3.2. when i run nx migrate latest => it only upgrade @nrwl/* dependencies and does not upgrade angular version.

**Comment by mhamri** [comment] 2022-06-19 11:11
i have the same issue, I run the `nx migrate latest`  and all the angular package except cli updated to 14.0.2. so I wonder why cli was exempted from the udpate?

**Comment by nhhockeyplayer** [comment] 2022-07-04 16:51
same here

**Comment by tadamczak** [comment] 2022-07-20 08:14
@minhhn999 i have exactly same problem right now. Upgrading from 13 -> 14 and at first it worked and updated nx and angular packages. After branch reset it updates only "nx" package. Not even updating other @nrwl/* packages.

**Comment by FrozenPandaz** [comment] 2022-10-28 21:15
This is now supported! :tada:

**Closed by FrozenPandaz** 2022-10-28 21:15 UTC
Labels: type: bug, scope: core

**Comment by spierala** [comment] 2023-02-07 13:30
I just tried `nx migrate` in an NX 14 workspace ("@nrwl/cli": "14.8.6").

It did not migrate any of the Angular packages.

**Comment by kroeder** [comment] 2023-02-14 09:25
Does not work for me unfortunately 

```
npx nx@latest migrate latest
```

migrated all Nx deps from `15.0.0` to `15.7.0`, ran a bunch of migrations but completely ignored that I am on Angular 14

However, running `nx migrate @angular/cli` core, etc. updates the deps, adds migrations but some fail due to a migration setup error (probably because there's no angular.json anymore?) 

Anything I can do about this?
