### ISSUE TITLE
convertNxGenerator is throwing "Cannot read property 'engine' of undefined"

### ISSUE THREAD

**Issue by iKrishnaSahu** [nrwl/nx#10725] opened 2022-06-13 18:03 UTC
[convertNxGenerator](https://github.com/nrwl/nx/blob/5b17335f4ddffc6ad9f05cced5f7c41fd2e18875/packages/devkit/src/utils/invoke-nx-generator.ts#L42) is throwing `Cannot read property 'engine' of undefined`

## Current Behavior

Getting "Cannot read property 'engine' of undefined" while executing custom schematic

## Steps to Reproduce

1. Download following schematic project - [my-app-convertNxGenerator.zip](https://github.com/nrwl/nx/files/8893383/my-app-convertNxGenerator.zip)
2. Extract and run npm install and npm run build
3. Go inside dist/myapp and run `npm link`
4. In some other project, run  `ng g @ruf/myapp:app`

### Failure Logs

```
C:\Projects\projects\workspaces2\test-ws-nrwl142x>nx g @ruf/myapp:app 
>  NX  Generating @ruf/myapp:my-app
Cannot read property 'engine' of undefined
C:\Projects\projects\workspaces2\test-ws-nrwl142x>
```

### Environment
Check zip's package.json

**Comment by leosvelperez** [comment] 2022-06-14 11:27
Thanks for reporting this!

The issue is happening due to trying to run an Angular CLI schematic as an Nx generator. This is happening because:

- The collection exposes a schematic with a factory pointing to an Angular CLI schematic (the converted generator `compat.ts`)
- The `schema.json` of the schematic has `"cli": "nx"`, which tells Nx that it should run it as an Nx DevKit generator and not as an Angular CLI schematic.

> Also, there is some mismatch between the `@nrwl/*` packages versions installed in the provided repo. This didn't cause that particular issue, but be mindful of having those 'packages versions aligned to avoid unexpected issues.

To solve this, please provide an entry in the collection like the following:

```json
{
  ...
  "generators": {
    "my-app": {
      "description": "A blank schematic.",
      "factory": "./src/my-app/index#myApp",
      "aliases": ["app"],
      "schema": "./src/my-app/schema.json"
    }
  }
}
```

With that in place, the Nx CLI will use the generator implementation instead of the Angular CLI schematic implementation. Please note the schematic implementation will still be used if you're writing a schematic and do something like:

```ts
externalSchematic('@ruf/myapp', app-name', {})
```

Also note, if you run `ng g @ruf/myapp:app` in an Angular CLI workspace it does work correctly.

As a side note, if you plan to use the Nx DevKit to write your generators and expose them as schematics, please consider creating an [Nx Plugin](https://nx.dev/extending-nx/nx-devkit) for them. It will provide you with the right setup and with enhanced DX.

I'm going to close this since there's no issue on Nx side of things and this issue is caused by a wrong setup. If you still have an issue please feel free to leave a comment with it.

**Closed by leosvelperez** 2022-06-14 11:27 UTC
Labels: type: bug, scope: angular

**Comment by raeffs** [comment] 2022-11-25 13:59
@leosvelperez I have a similar issue: I have some local generators that are executed with the Angular CLI. but since the update of Nx (from 14.6.3 to 15.2.1) it looks like the generators are now executed with the Nx CLI which results in the same error. The schema.json does **not** contain `"cli": "nx"`. Is there a way to tell Nx to execute that generator with the Angular CLI like it used to in previous versions?
