### ISSUE TITLE
"styles.css - Error: (0 , _identifier.getUndoPath) is not a function" when building a fresh angular app

### ISSUE THREAD

**Issue by CedricMoore** [nrwl/nx#6617] opened 2021-08-05 14:26 UTC
## Current Behavior
I have created a brand new workspace using the command `npx create-nx-workspace@latest nestang`.
Here are my workspace configurations:
```
√ What to create in the new workspace · angular-nest
√ Application name                    · fliesen
√ Default stylesheet format           · scss
√ Use Nx Cloud? (It's free and doesn't require registration.) · No (also tried it with this on)
```
Serving/Building the angular app results in the following error:
```
styles.css - Error: (0 , _identifier.getUndoPath) is not a function
```
I do get the output `Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/` as well but there is nothing in localhost:4200 rather than `Cannot GET /`.

## Expected Behavior
The angular application should build and serve, navigating to `localhost:4200` should bring up the default NX angular boilerplate page.

## Steps to Reproduce
Create a brand new `angular-nest` workspace using the command `npx create-nx-workspace@latest nestang`.
Serve/Build the angular app using any method (i.e. vs Code console extension, or command line).

### Failure Logs
In NX console, after running the Serve command in the `Generate & Run Target` section, I get the following logs:
```
> Executing task: ng serve fliesen <


> nx run fliesen:serve:development 
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size  
vendor.js           | vendor        |   2.15 MB  
polyfills.js        | polyfills     | 472.93 kB  
styles.js           | styles        | 345.00 kB  
main.js             | main          |  15.97 kB  
runtime.js          | runtime       |   6.61 kB

                    | Initial Total |   2.97 MB

Build at: 2021-08-05T13:47:48.685Z - Hash: b6396d76abf57dec6123 - Time: 18028ms

styles.css - Error: (0 , _identifier.getUndoPath) is not a function



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
```

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 12.18.4
  OS   : win32 x64
  npm  : 6.14.6
  
  nx : Not Found
  @nrwl/angular : 12.6.4
  @nrwl/cli : 12.6.4
  @nrwl/cypress : 12.6.4
  @nrwl/devkit : 12.6.4
  @nrwl/eslint-plugin-nx : 12.6.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.4
  @nrwl/linter : 12.6.4
  @nrwl/nest : 12.6.4
  @nrwl/next : Not Found
  @nrwl/node : 12.6.4
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.4
  @nrwl/storybook : 12.6.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by nartc** [comment] 2021-08-05 14:44
Duplicate of #6612

**Closed** 2021-08-05 14:44 UTC
Labels: type: bug
