### ISSUE TITLE
The affected projects might have not been identified properly. The package(s) @swc/helpers, @nx/cypress, @nx/eslint-plugin, @nx/jest, @nx/js were not found

### ISSUE THREAD

**Issue by omykhayl** [nrwl/nx#20956] opened 2023-12-30 17:45 UTC
### Current Behavior

I'm trying to migrate my project to the latest Nx version (17). So, I do `nx migrate latest`, them execute migrations. After the migration when I run affected command I get the following message:

_The affected projects might have not been identified properly. The package(s) @swc/helpers, @nx/cypress, @nx/eslint-plugin, @nx/jest, @nx/js were not found. Please open an issue in GitHub including the package.json file._

### Expected Behavior

No warning is shown and affected command just works as expected

### Steps to Reproduce

1. `nx migrate latest`. Nx version before migration is: 16.7.4. New version is: 17.2.8
2. Add the following workaround to enable the next step (otherwise it will fail)
`"resolutions": {
    "jackspeak": "2.1.1"
  }` to the package.json. This is taken from here: https://github.com/cypress-io/cypress/issues/27370. If not done the [ERR_REQUIRE_ESM] error will fail the migration (related to `require('string-width')`)
3. `yarn nx migrate --run-migrations`
4. `yarn nx affected --target=build`

### Nx Report

```shell
Node   : 20.10.0
   OS     : darwin-x64
   yarn   : 1.22.21
   
   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/cypress        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/react          : 17.2.8
   @nx/storybook      : 17.2.8
   @nrwl/tao          : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   nx-cloud           : 16.5.2
   typescript         : 5.2.2
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

I have spent 2 days to make the migration succeed. Then found this workaround with resolutions: https://github.com/cypress-io/cypress/issues/27370

**Comment by omykhayl** [comment] 2023-12-30 17:49
my package.json

[package.json](https://github.com/nrwl/nx/files/13798820/package.json)

**Comment by attilacsanyi** [comment] 2024-04-19 08:57
This seems a [relevant issue](https://github.com/nrwl/nx/issues/22659). Let me know if anyone found the solution, thnaks.

**Comment by FrozenPandaz** [comment] 2024-05-13 18:22
Closing as a duplicate of https://github.com/nrwl/nx/issues/22659

**Closed by FrozenPandaz** 2024-05-13 18:22 UTC
Labels: type: bug, scope: core
