### ISSUE TITLE
Unable to create an Angular application

### ISSUE THREAD

**Issue by hadrien-toma** [nrwl/nx#15611] opened 2023-03-11 05:38 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/6162030/224467073-005c6677-51f1-4ef9-ab0b-dd33eab98481.png)

### Expected Behavior

Successful creation of the application

### Steps to Reproduce

```bash
docker run --rm --interactive --tty node /bin/bash -c "
	uname --all &&
	npm install --global npm &&
	echo \"npm -v -> \$(npm -v)\" &&
	echo \"node -v -> \$(node -v)\" &&
	npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nxCloud=false --packageManager=yarn &&
	cd workspace &&
	git init &&
	yarn add --ignore-engines --dev @nrwl/angular @nrwl/cli @nrwl/cypress @nrwl/eslint-plugin-nx @nrwl/jest @nrwl/js @nrwl/nest @nrwl/node @nrwl/nx-plugin @nrwl/storybook @nrwl/tao @nrwl/web @nrwl/workspace &&
	yarn add --ignore-engines @angular/compiler &&
	yarn add --ignore-engines --dev @angular/compiler-cli @angular-devkit/build-angular @badeball/cypress-cucumber-preprocessor @commitlint/cli @commitlint/config-conventional @compodoc/compodoc @cypress/webpack-preprocessor @storybook/addon-a11y @storybook/addon-actions @storybook/addon-controls @storybook/addon-docs @storybook/addon-essentials @storybook/addon-toolbars @storybook/addon-viewport @storybook/angular @typescript-eslint/eslint-plugin @typescript-eslint/parser cucumber-html-reporter cypress eslint eslint-config-prettier fkill-cli husky@4 injection-js json jsonc-eslint-parser ng-packagr postcss-preset-env prettier-plugin-organize-attributes webpack-bundle-analyzer &&
	node_modules/.bin/json --in-place -f package.json -e \"this.scripts['nx'] = 'nx';\" &&
	yarn run nx report &&
	yarn run nx generate @nrwl/angular:application --directory=foo/bar --minimal --name=baz --routing --standalone --strict --style=css &&
	/bin/sh
"
```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 19.7.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/angular           : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/nest              : 15.8.6
   @nrwl/node              : 15.8.6
   @nrwl/nx-plugin         : 15.8.6
   @nrwl/rollup            : 15.8.6
   @nrwl/storybook         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/web               : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @compodoc/compodoc : 1.1.19
   @storybook/angular : 6.5.16

Done in 0.78s.
```

### Failure Logs

```shell
SchematicsException [Error]: Project "foo-bar-baz" does not exist.
    at /tmp/tmp-597-5duL4AyMjuI7/node_modules/@schematics/angular/component/index.js:32:19

 >  NX   Project "foo-bar-baz" does not exist.

   Pass --verbose to see the stacktrace.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by leosvelperez** [comment] 2023-03-14 15:48
hey @hadrien-toma! Thanks for reporting this!

The issue is happening because an old version of `@angular-devkit/schematics` is hoisted at the workspace's root:

```shell
yarn why @angular-devkit/schematics
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@angular-devkit/schematics"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@angular-devkit/schematics@13.3.10"
info Reasons this module exists
   - "@compodoc#compodoc" depends on it
   - Hoisted from "@compodoc#compodoc#@angular-devkit#schematics"
info Disk size without dependencies: "7.2MB"
info Disk size with unique dependencies: "30.88MB"
info Disk size with transitive dependencies: "7.2MB"
info Number of shared dependencies: 40
=> Found "@nestjs/schematics#@angular-devkit/schematics@15.0.4"
info This module exists because "@nrwl#nest#@nestjs#schematics" depends on it.
info Disk size without dependencies: "708KB"
info Disk size with unique dependencies: "24.37MB"
info Disk size with transitive dependencies: "708KB"
info Number of shared dependencies: 40
✨  Done in 1.49s.
```

That old version then conflicts with a newer version of `@schematics/angular` which tries to use functionality that either changed or doesn't exist.

We recently switched to having that package as a peer dependency, so we can support multiple versions of Angular. Therefore, our packages will pick whatever is installed at the workspace's root. We automatically install the package if it's not installed when running any Angular generator, but in this case, the package is already installed (can be `require`d).

There's little we can do on our side in this case. I suggest you change your setup to install the relevant `@nrwl/angular` peer dependencies (`@angular-devkit/schematics`, `@schematics/angular`, `@angular-devkit/core`). Otherwise, you can generate the application before installing the additional packages (e.g. `@compodoc/compodoc`) that bring in an older version of `@angular-devkit/schematics`.

On a separate note, you don't need to install `@nrwl/cli` and `@nrwl/tao` anymore and instead, install `nx`. Also, there are several packages you're manually installing that are going to be installed by the Nx generators. You could simplify your setup above by relying on that.

I'm going to close this. Please make sure to install the peer dependencies or adjust the order in which the application generator is invoked and some packages are installed to avoid the issue. Feel free to reply if you still have issues after applying the suggestions.

**Closed by leosvelperez** 2023-03-14 15:48 UTC
Labels: type: bug, scope: angular

**Comment by hadrien-toma** [comment] 2023-03-14 23:18
Hey @leosvelperez, thanks for the clear answer and for your reactivity, now I understand!

Here is the fixed code following your advices:

```bash
docker run --rm --interactive --tty node /bin/bash -c "
	uname --all &&
	npm install --global npm &&
	echo \"npm -v -> \$(npm -v)\" &&
	echo \"node -v -> \$(node -v)\" &&
	npx --yes create-nx-workspace@latest workspace --preset=empty --cli=nx --interactive=false --nxCloud=false --packageManager=yarn &&
	cd workspace &&
	git init &&
	yarn add --ignore-engines --dev nx @nrwl/angular @nrwl/cypress @nrwl/eslint-plugin-nx @nrwl/jest @nrwl/js @nrwl/nest @nrwl/node @nrwl/nx-plugin @nrwl/storybook @nrwl/web @nrwl/workspace &&
	yarn add --ignore-engines @angular/compiler @angular-devkit/schematics @schematics/angular @angular-devkit/core &&
	yarn add --ignore-engines --dev @badeball/cypress-cucumber-preprocessor @commitlint/cli @commitlint/config-conventional @compodoc/compodoc @cypress/webpack-preprocessor @storybook/addon-a11y @storybook/addon-actions @storybook/addon-controls @storybook/addon-docs @storybook/addon-essentials @storybook/addon-toolbars @storybook/addon-viewport @storybook/angular cucumber-html-reporter fkill-cli husky injection-js json jsonc-eslint-parser ng-packagr postcss-preset-env prettier-plugin-organize-attributes webpack-bundle-analyzer &&
	node_modules/.bin/json --in-place -f package.json -e \"this.scripts['nx'] = 'nx';\" &&
	yarn run nx report &&
	yarn run nx generate @nrwl/angular:application --directory=foo/bar --minimal --name=baz --routing --standalone --strict --style=css &&
	/bin/sh
"
```

**Comment by hadrien-toma** [comment] 2023-03-15 06:45
Info: The app generated by this setup wasn't passing targets so I created this issue: https://github.com/nrwl/nx/issues/15687
