### ISSUE TITLE
Cannot migrate from 11.6.3 to 12

### ISSUE THREAD

**Issue by mehrad-rafigh** [nrwl/nx#5923] opened 2021-06-08 12:23 UTC
## Current Behavior
I cannot migrate my workspace from nx 11.6.3 to 12. Running the migrations I get the following error

```
>  NX  Running migrations from 'migrations.json'

Running migration update-ngcc-postinstall
Successfully finished update-ngcc-postinstall
---------------------------------------------------------
Running migration update-webpack-browser-config
Successfully finished update-webpack-browser-config
---------------------------------------------------------
Running migration update-storybook
Successfully finished update-storybook
---------------------------------------------------------
Running migration update-angular-eslint-rules
Successfully finished update-angular-eslint-rules
---------------------------------------------------------
Running migration convert-webpack-browser-build-target-to-delegate-build
Successfully finished convert-webpack-browser-build-target-to-delegate-build
---------------------------------------------------------
Running migration update-angular-config-v12
Cannot read property 'startsWith' of undefined
```

Alan from the Angular CLI Team answered my unrelated question in this issue.
https://github.com/angular/angular-cli/issues/21075#issuecomment-856668743

Our libraries do not have a builder property. 

## Expected Behavior
I can migrate to nx 12

### Environment
```
>  NX  Report complete - copy this into the issue template

  Node : 14.15.5
  OS   : linux x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.3.6
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : 12.3.6
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 12.3.6
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

```

**Comment by leosvelperez** [comment] 2021-06-08 12:49
Thanks for reporting this!

Please make sure all your targets for a project have a builder which is a required property. Targets are the specification of something that can be run in a project, and the builder specifies the function that will be run when the target is invoked. Without the builder, there's no way to know what to do when invoking the target. If you currently have targets without a builder, that means those targets are not being used and most likely, they are not needed or you need to add their builder property to make them usable.

I'm closing this one since it's a duplicate of https://github.com/nrwl/nx/issues/5655.

**Closed by leosvelperez** 2021-06-08 12:49 UTC
Labels: type: bug

**Comment by mehrad-rafigh** [comment] 2021-06-08 15:04
Hi @leosvelperez the only project that do not have a builder target are our libraries.
Those are used by the apps and thus do not have any builders. What is the way to migrate them?

**Comment by leosvelperez** [comment] 2021-06-08 15:14
Can you provide the project definition of any of those libraries?

**Comment by mehrad-rafigh** [comment] 2021-06-09 08:56
One example for a library definition would be the following
```
    "job-scheduler-modals": {
      "projectType": "library",
      "root": "libs/job-scheduler/modals",
      "sourceRoot": "libs/job-scheduler/modals/src",
      "prefix": "cg",
      "architect": {
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "libs/job-scheduler/modals/src/**/*.ts",
              "libs/job-scheduler/modals/src/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "outputs": [
            "coverage/libs/job-scheduler/modals"
          ],
          "options": {
            "jestConfig": "libs/job-scheduler/modals/jest.config.js",
            "passWithNoTests": true
          }
        }
      }
    }
```

Those libs are consumed by other libraries and the composite library is then consumed by an app. 
We generate everything with the ng command, so I am a bit baffled why the builder property is missing.

**Comment by leosvelperez** [comment] 2021-06-09 09:04
@mehrad-rafigh all targets in that project (`lint` and `test`) have a `builder` property. That project has all its targets correctly configured. I think you might be confusing the `builder` property with having a target named `build`, that's a different thing and having a specific target like that one is not a requirement. You need to check your projects' targets (objects inside `architect`) and see which one doesn't have a `builder` property defined inside.

**Comment by mehrad-rafigh** [comment] 2021-06-09 09:07
Thanks @leosvelperez that clears a big question mark in my head. I will take a look which one of the projects does not a have a builder property
