### ISSUE TITLE
Can't use enforce-module-boundaries when running ESLint directly

### ISSUE THREAD

**Issue by pauleustice** [nrwl/nx#26239] opened 2024-05-29 11:41 UTC
### Current Behavior

After upgrading various Nx packages from `16.9.1` to `18.2.3`, we now see this issue when running ESLint directly in GitHub.

`npx eslint {apps,libs}/**/*.{ts,js,component.html}`

```
No cached ProjectGraph is available. The rule will be skipped. If you encounter this error as part of running standard `nx` commands then please open an issue on https://github.com/nrwl/nx
```

We started noticing this when upgrading these packages:

<img width="1025" src="https://github.com/nrwl/nx/assets/1677737/410eddcd-0f1c-4954-8716-f72230291a0f">

It appears to output one warning per file (see screenshot below). To be clear, the message says to report issues when running it with Nx commands, which we're not. However, I'm reporting it because this issue only just started occurring for us.

I'm not sure if it has only just started _occurring_ in 18.x or is only now _visible_ in 18.x. We don't wish to use Nx to run linting as, when the cache is invalidated, it takes a LONG time to run hundreds of ESLint 'projects' (one process for every lib and app in our monorepo). It only takes <3 mins to lint the whole repo directly, so there's no benefit to using Nx. However, the rule itself is very useful so if there's a way to continue using it without running nx lint, please let me know :)

### Expected Behavior

The rule is enforced and does not return a warning

### GitHub Repo

https://github.com/nrwl/nx-examples

### Steps to Reproduce

1. Check out the `https://github.com/nrwl/nx-examples` repo
2. Delete the `.nx` folder if you have one
3. Run `npx eslint {apps,libs}/**/*.{ts,component.html}`
4. Observe the error

### Nx Report

```shell
From https://github.com/nrwl/nx-examples repo:


Node   : 21.7.3
OS     : darwin-arm64
yarn   : 1.22.21

nx                 : 19.1.0-beta.3
@nx/js             : 19.1.0-beta.3
@nx/jest           : 19.1.0-beta.3
@nx/linter         : 19.1.0-beta.3
@nx/eslint         : 19.1.0-beta.3
@nx/workspace      : 19.1.0-beta.3
@nx/angular        : 19.1.0-beta.3
@nx/cypress        : 19.1.0-beta.3
@nx/devkit         : 19.1.0-beta.3
@nx/eslint-plugin  : 19.1.0-beta.3
@nx/react          : 19.1.0-beta.3
@nrwl/tao          : 19.1.0-beta.3
@nx/web            : 19.1.0-beta.3
@nx/webpack        : 19.1.0-beta.3
typescript         : 5.4.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
Community plugins:
@ngrx/component-store : 17.0.1
@ngrx/effects         : 17.0.1
@ngrx/entity          : 17.0.1
@ngrx/router-store    : 17.0.1
@ngrx/store           : 17.0.1
@ngrx/store-devtools  : 17.0.1
```

### Failure Logs

<img width="1076" src="https://github.com/nrwl/nx/assets/1677737/a6663f88-44eb-4793-a50f-05efefad7383">

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This warning is contained within [packages/eslint-plugin-nx/src/utils/project-graph-utils.ts](https://github.com/nrwl/nx/blob/52d04d98641db85b7719806fcb9662fda5ac951d/packages/eslint-plugin/src/utils/project-graph-utils.ts#L50).

**Comment by anton-gorbikov** [comment] 2024-07-29 14:56
@pauleustice we had a similar issue https://github.com/nrwl/nx/issues/8110 . I was forced to write a script and execute it manually before each run to ensure project graph:

```js
const {createProjectGraphAsync} = require('@nx/workspace/src/core/project-graph');

process.env.NX_DAEMON = 'false';

createProjectGraphAsync({
	exitOnError: true,
});
```

**Comment by leosvelperez** [comment] 2024-08-19 08:21
Thanks for reporting this!

The ESLint rules provided by the `@nx/eslint-plugin` package require the project graph for their functionality. We used to have a way to create the project graph synchronously, but we removed it due to performance issues, and we can only construct it asynchronously now. On the other hand, ESLint rule implementations can only be synchronous, so, we can't construct the required project graph in those rules. Instead, those rules read the cached project graph, which is a synchronous operation.

That's why, if you run ESLint directly, you must ensure the project graph is constructed before linting your files with the ESLint CLI directly. You can do it with a script similar to the one mentioned in https://github.com/nrwl/nx/issues/26239#issuecomment-2256171294, or you could run a command like `nx report` which would create the project graph.

I'm closing this since it's working as intended.

**Closed by leosvelperez** 2024-08-19 08:21 UTC
Labels: type: bug, scope: linter

**Comment by pauleustice** [comment] 2024-08-27 10:14
Thanks for the background @anton-gorbikov, and for the further explanation, @leosvelperez. Running `nx report` seems like a quick way to create the project graph, but it's still going to look strange when its real purpose is to create the graph in order to run a specific ESLint rule.

Could that functionality not be built into the rule? There's already a condition that checks for the graph, so it doesn't feel like a huge ask to create it if it doesn't exist; after all that's a key dependency of the rule.

That feels like the right place to do it, rather than every single consuming repo have to add it in various places.
