### ISSUE TITLE
Get name of all libraries or apps in v16

### ISSUE THREAD

**Issue by nodegin** [nrwl/nx#16676] opened 2023-05-01 17:21 UTC
### Current Behavior

After upgrading to v16, the previous way to get name of all libraries or apps is no longer working.
`npx nx affected:libs --all --plain`
`npx nx affected:apps --all --plain`

### Expected Behavior

Like what in this issue discussed before
https://github.com/nrwl/nx/issues/7472

It should output all apps/libs in the project.

### Steps to Reproduce

1. Run the command in terminal
2. Observe the output

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.15.1
   OS     : darwin arm64
   pnpm   : 7.25.0
   Hasher : Native
   
   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nx/react          : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/vite           : 16.0.1
   @nx/web            : 16.0.1
   typescript         : 4.9.5
```

**Comment by AgentEnder** [comment] 2023-05-01 17:57
`nx show projects` will display a list of projects within the repo, does this satisfy your request?

**Comment by motabass** [comment] 2023-05-02 08:39
The commands should output affected apps or libs as they did in v15

**Comment by AgentEnder** [comment] 2023-05-02 17:38
Its not a bug, `affected:apps` and `affected:libs` had been marked as deprecated for a while, and were purposefully removed in Nx 16 in favor of some combination of:
- `nx print-affected`
- `nx show projects`
- `nx run {someTarget} --graph`
- `nx run-many -t {someTarget} --graph`
- `nx affected -t {someTarget} --graph`

**Comment by motabass** [comment] 2023-05-03 11:30
Thank you for the hint. 

I changed my command to `nx print-affected --type=app --select=projects` and changed parsing of the resulting string to split by `, ` instead of just ` ` (space). 

Everything works as expected with this again.

**Comment by Coly010** [comment] 2023-05-04 11:12
Glad this is working for you now! 🎉

**Closed by Coly010** 2023-05-04 11:12 UTC
Labels: type: feature, scope: core

**Comment by nodegin** [comment] 2023-05-05 16:58
@AgentEnder  Sorry for late reply. I tried `nx show projects` it works but it doesn't tell which one is apps/libs.
I tried `nx print-affected --type=app --select=projects` but I got unexpected error as the following output:
```
npx nx print-affected --type=app --select=projects
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
nx print-affected

Prints information about the projects and targets affected by changes

Run command using --base=[SHA1] (affected by the committed, uncommitted and untracked changes):
      --base  Base of the current branch (usually main)                                                                                       [string]

or using --base=[SHA1] --head=[SHA2] (affected by the committed changes):
      --base  Base of the current branch (usually main)                                                                                       [string]
      --head  Latest commit of the current branch (usually HEAD)                                                                              [string]

or using:
      --files        Change the way Nx is calculating the affected command by providing directly changed files, list of files delimited by commas or
                     spaces                                                                                                                   [string]
      --uncommitted  Uncommitted changes                                                                                                     [boolean]
      --untracked    Untracked changes                                                                                                       [boolean]

Options:
      --help               Show help                                                                                                         [boolean]
      --version            Show version number                                                                                               [boolean]
      --select             Select the subset of the returned json document (e.g., --select=projects)                                          [string]
      --type               Select the type of projects to be returned (e.g., --type=app)                              [string] [choices: "app", "lib"]
  -c, --configuration      This is the configuration to use when performing tasks on projects                                                 [string]
  -t, --targets, --target  Tasks to run for affected projects                                                                                 [string]
      --exclude            Exclude certain projects from being processed                                                                      [string]
      --all                All projects                                                                                                      [boolean]

Examples:
  print-affected                                         Print information about affected projects and the project graph
  print-affected --base=main --head=HEAD                 Print information about the projects affected by the changes between main and HEAD (e.g,. PR)
  print-affected -t test                                 Prints information about the affected projects and a list of tasks to test them
  print-affected -t build --select=projects              Prints the projects property from the print-affected output
  print-affected -t build --select=tasks.target.project  Prints the tasks.target.project property from the print-affected output

Find more information and examples at https://nx.dev/nx/print-affected

Error: Command failed: git diff --name-only --no-renames --relative "main" "HEAD"
fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at parseGitOutput (/Users/user/project/node_modules/.pnpm/nx@16.0.1/node_modules/nx/src/utils/command-line-utils.js:243:41)
    at getFilesUsingBaseAndHead (/Users/user/project/node_modules/.pnpm/nx@16.0.1/node_modules/nx/src/utils/command-line-utils.js:240:12)
    at parseFiles (/Users/user/project/node_modules/.pnpm/nx@16.0.1/node_modules/nx/src/utils/command-line-utils.js:199:20)
    at /Users/user/project/node_modules/.pnpm/nx@16.0.1/node_modules/nx/src/command-line/affected.js:78:155
    at Generator.next (<anonymous>)
    at /Users/user/project/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 61 6d 62 69 67 75 6f 75 73 20 61 72 67 75 6d 65 6e 74 20 27 6d 61 69 6e 27 3a 20 75 6e 6b 6e 6f 77 6e 20 72 65 76 69 73 69 6f 6e ... 135 more bytes>
  ],
  pid: 21821,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 61 6d 62 69 67 75 6f 75 73 20 61 72 67 75 6d 65 6e 74 20 27 6d 61 69 6e 27 3a 20 75 6e 6b 6e 6f 77 6e 20 72 65 76 69 73 69 6f 6e ... 135 more bytes>
}
```

**Comment by AgentEnder** [comment] 2023-05-05 17:07
The logs there state that you don't have a branch called 'main'. You need do one of:
- Update the base branch in nx.json https://nx.dev/reference/nx-json
- Pass --base
- Use the NX_BASE env variable
- Use `main` as your default branch

**Comment by nodegin** [comment] 2023-05-07 13:19
@AgentEnder I think the `affected` solution is rely on git history which is not an ideal solution, for example I am on `staging` branch and behind of `master` branch, running `npx nx print-affected --type=app --select=projects --base=master` is fine, but once I merged staging into master and sync the branches, the command is no longer working.

What I really looking for is a solution like `nx show projects` but can tell apps/libs without rely on git history.
