### ISSUE TITLE
Jenkins CI - npx nx affected --target=build throws as error

### ISSUE THREAD

**Issue by mikel67** [nrwl/nx#2422] opened 2020-02-03 16:23 UTC
## Expected Behavior

Build should execute on Jenkins with same source as executes on local environment

## Current Behavior

Source checked into git, Jenkins multi branch pipeline executes 

Build stage fails with error:

+ npx nx affected --target=build -- master HEAD
fatal: Not a valid object name affected
Command failed: git merge-base affected master
fatal: Not a valid object name affected

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Source repo available at https://git.symbiotics.co.za/mike.love/NXPoC.git
2. Checkout locally, build via npm install & npm run build => successful nx build
3. Run as Jenkinsmulti pipeline build 

### Context

Please provide any relevant information about your setup:

- version of Nx used (_Please run `nx report` at the root of your workspace and copy the results here if you are using Nx 8.6.1 or greater_)
- 3rd-party libraries and their versions
- and most importantly - a use-case that fails

**A minimal reproduction scenario allows us to quickly confirm a bug (or point out coding problem) as well as confirm that we are fixing the right problem.**

### Failure Logs

Extract of log file included below:

+ printenv
JENKINS_HOME=/var/lib/jenkins
MAIL=/var/mail/ubuntu
SSH_CLIENT=10.33.11.191 35228 22
USER=ubuntu
RUN_CHANGES_DISPLAY_URL=https://tools.symbiotics.co.za/jenkins/job/Symbiotics/job/ResearchAndDevelopment/job/Mike-NXPoC/job/master/1/display/redirect?page=changes
NODE_LABELS=AWSCLI-1.14 EC2 (us-east-1) - Ubuntu slave - general purpose (i-010bf32acc1726c8d)
HUDSON_URL=https://tools.symbiotics.co.za/jenkins/
GIT_COMMIT=822981fd6da97e2d71e35656d41c5b4c32f6bdea
SHLVL=1
HOME=/home/ubuntu
BUILD_URL=https://tools.symbiotics.co.za/jenkins/job/Symbiotics/job/ResearchAndDevelopment/job/Mike-NXPoC/job/master/1/
HUDSON_COOKIE=d35a3660-b7a9-47c5-b8b3-4b5d45c3f71d
JENKINS_SERVER_COOKIE=durable-e8c8bc3e63db0bf107f0b2bd92c8d9d3
JBOSS_HOME=/opt/wildfly-8.2.0.Final
WORKSPACE=/var/lib/jenkins/workspace/AndDevelopment_Mike-NXPoC_master
LOGNAME=ubuntu
NODE_NAME=EC2 (us-east-1) - Ubuntu slave - general purpose (i-010bf32acc1726c8d)
_=/usr/bin/java
STAGE_NAME=Env Setup
EXECUTOR_NUMBER=1
GIT_BRANCH=master
XDG_SESSION_ID=3
BUILD_DISPLAY_NAME=#1
HUDSON_HOME=/var/lib/jenkins
JOB_BASE_NAME=master
PATH=/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_12.14.1/bin:/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_12.14.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ubuntu/android-sdk-linux/tools:/home/ubuntu/android-sdk-linux/platform-tools
BUILD_ID=1
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
BUILD_TAG=jenkins-Symbiotics-ResearchAndDevelopment-Mike-NXPoC-master-1
LANG=en_US.UTF-8
NODEJS_HOME=/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_12.14.1
JENKINS_URL=https://tools.symbiotics.co.za/jenkins/
JOB_URL=https://tools.symbiotics.co.za/jenkins/job/Symbiotics/job/ResearchAndDevelopment/job/Mike-NXPoC/job/master/
GIT_URL=https://git.symbiotics.co.za/mike.love/NXPoC.git
BUILD_NUMBER=1
JENKINS_NODE_COOKIE=3d497345-2c4f-4f76-ae5e-5938937842cd
SHELL=/bin/bash
RUN_DISPLAY_URL=https://tools.symbiotics.co.za/jenkins/job/Symbiotics/job/ResearchAndDevelopment/job/Mike-NXPoC/job/master/1/display/redirect
HUDSON_SERVER_COOKIE=32f647d765b2b380
JOB_DISPLAY_URL=https://tools.symbiotics.co.za/jenkins/job/Symbiotics/job/ResearchAndDevelopment/job/Mike-NXPoC/job/master/display/redirect
JOB_NAME=Symbiotics/ResearchAndDevelopment/Mike-NXPoC/master
PWD=/var/lib/jenkins/workspace/AndDevelopment_Mike-NXPoC_master
LC_ALL=en_US.UTF-8
ANDROID_HOME=/home/ubuntu/android-sdk-linux
SSH_CONNECTION=10.33.11.191 35228 10.33.11.19 22
BRANCH_NAME=master
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] nodejs
[Pipeline] {
[Pipeline] sh
+ node -v
v12.14.1
+ npm -v
6.13.4
+ npx nx affected --target=build -- master HEAD
fatal: Not a valid object name affected
Command failed: git merge-base affected master
fatal: Not a valid object name affected

[Pipeline] }
[Pipeline] // nodejs
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] archive
The archive step is deprecated, please use archiveArtifacts instead.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by mehrad-rafigh** [comment] 2020-02-05 11:20
Jenkins only does a sparse checkout. Have you tried checking out the branch which has to be built/tested etc?

**Comment by vsavkin** [comment] 2020-02-05 15:48
Could you upload a repro to github?

**Comment by mikel67** [comment] 2020-02-05 18:54
Thanks for the response 

Repo pushed to Github. 
https://github.com/mikel67/NXPoC.git

@mehrad-rafigh, I have not yet verified direct checkout on the Jenkins agent. Will feedback  when I get a chance to test

**Comment by zakhenry** [comment] 2020-02-21 21:46
I have a similar problem - the issue arises when trying to compute affected when there is a shallow clone. Ideally it should be possible to just have a shallow clone of the current branch and the target branch (i.e. only 2 commits pulled for the whole repo).

The problem arises in https://github.com/nrwl/nx/blob/74716df4fc3c9bf17d44dc46136431d327a19b06/packages/workspace/src/command-line/shared.ts#L74-L81 where `git merge-base` is used to find a common ancestor.

I'm not sure if there is an alternative to `git merge-base` to work out how to find the minimal set of changed files in head only given no history

**Comment by mikel67** [comment] 2020-02-22 05:31
@zakhenry appreciate the comprehensive response.

**Comment by vsavkin** [comment] 2020-02-27 02:12
@zakhenry you could pass the files yourself, like this: 

```
nx affected --target=build --files=list-of-paths-with-commas
```

Where you generate the list by running `git diff --name-only --relative SHA1 SHA2`. It's a bit annoying but it should work.

**Comment by zakhenry** [comment] 2020-02-27 08:09
@vsavkin yep that is true however it will be quite a bit more eager than the git-merge technique as the git diff will pick up every single non matching file, whether or not it was caused by a change in the current branches divergence from the common ancestor. Weighed up it is probably faster overall to just clone deeply.

**Comment by vsavkin** [comment] 2020-03-04 22:14
@zakhenry yup. Another option, which isn't really a replacement for `affected`, is to use the the NxCloud distributed caching. So you run `nx run-many --target=build --all`, but it will only rebuild things that weren't cached. This isn't exactly the same (see last section of this: https://github.com/nrwl/nx-distributed-cache-example). 

I'm going to close this issue. I don't think there is a good fix for it. The workaround: Since you can pass the list of touched files directly, you can compute the list in the way that works in your CI env.

**Closed by vsavkin** 2020-03-04 22:14 UTC
Labels: blocked: repro needed, scope: misc, type: question / discussion

**Comment by tsoehnlin-aura** [comment] 2021-01-19 17:39
@vsavkin  This solution has limitations in the fact that any non-trivial change (e.g. adding in a whole new submodule) will result in a large file list.  This has impact on reporting in the CI system as the concatentated list of files will be embedded in the output/headings and the like. This could also have impact on shell limitations on the number of characters that are safely passed for given arguments or overall commmands.  

Would it be possible to formally support this model via arguments e.g. `nx affected --target=build --diff=SHA1..SHA2` and run this git operation internally?

**Comment by SanthoshKumar-Prodapt** [comment] 2021-03-25 22:25
@vsavkin , 

Just a suggestion, I had the same issue with jenkins where the origin develop was not fetched as jenkins was doing shadow cloning, I resolved the issue by enabling advanced clone option in multibranch pipline and enable fetch tags. It helped me.
I hope it helps you.
<img width="987" alt="Screenshot 2021-03-25 at 23 24 56" src="https://user-images.githubusercontent.com/74766911/112551469-576e8f00-8dc1-11eb-959b-a35e9f00c860.png">

**Comment by tomalaforge** [comment] 2021-05-20 16:08
Hello,

Does anyone succeded in using nx affected in a jenkins pipeline?

**Comment by nycynik** [comment] 2021-05-31 04:10
I don't have a solution, but wanted to share some information.

In pipeline jobs, it's not a problem, since you can indicate the branch to build, and sure that you have the base on that branch's last commit.  

The problem is multi-branch pipelines. And the issue is the affected command requires you to tell it what base you want to compare it to.  This branch also needs to be checked out in order for the comparison to work. This is rarely the case - when you have a PR from some other branch (feature* for example) - this is when `origin/main` (or master) is not checked out and the comparison has 

The solutions above all are trying to solve that issue, how to keep the checkout shallow/fast, but also have everything needed to do the comparison. 

There are two scenarios, one is where you are building a branch and the other where you are building a PR, they have different env variables and are different. 

The solution offered in the docs is to use something like this:

`def String baseSha = env.CHANGE_ID ? 'origin/main' : 'origin/main~1'`

This is what is used to generate the base, but this only works in certain situations, like when you are on the main branch, to begin with.

So my solution was just to also always `git checkout main`, and if on main, `checkout main~1`.

**Comment by santoshyadavdev** [comment] 2021-05-31 04:48
> I don't have a solution, but wanted to share some information.
> 
> In pipeline jobs, it's not a problem, since you can indicate the branch to build, and sure that you have the base on that branch's last commit.
> 
> The problem is multi-branch pipelines. And the issue is the affected command requires you to tell it what base you want to compare it to. This branch also needs to be checked out in order for the comparison to work. This is rarely the case - when you have a PR from some other branch (feature* for example) - this is when `origin/main` (or master) is not checked out and the comparison has
> 
> The solutions above all are trying to solve that issue, how to keep the checkout shallow/fast, but also have everything needed to do the comparison.
> 
> There are two scenarios, one is where you are building a branch and the other where you are building a PR, they have different env variables and are different.
> 
> The solution offered in the docs is to use something like this:
> 
> `def String baseSha = env.CHANGE_ID ? 'origin/main' : 'origin/main~1'`
> 
> This is what is used to generate the base, but this only works in certain situations, like when you are on the main branch, to begin with.
> 
> @santoshyadavdev 's solution worked for me.

Looks like you tagged me by mistake it's @SanthoshKumar-Prodapt

**Comment by maxisam** [comment] 2021-08-10 04:32
I think this is worth to mention in the document.

**Comment by vespertilian** [comment] 2022-03-22 05:11
Just for anyone else finding this thread.  @SanthoshKumar-Prodapt  fix worked for me ... just make sure you use `origin` in your branch name. Originally I just used develop and it did not work. 

Also I found it easier to add the command to my package.json and call that from jenkins.

```
    "test-affected-dev": "npm run affected:test -- --base=origin/develop --head=HEAD",
    "lint-affected-dev": "npm run affected:lint -- --base=origin/develop --head=HEAD",
```
