### ISSUE TITLE
Nx 9 Plans

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#1511] opened 2019-06-21 13:38 UTC
Nx 7 to Nx 8 was a big release:
- We added support for Web Components, React, Nest, Cypress, etc
- We restructured the packages and made Nx pluggable
- We launched [nx.dev](https://nx.dev)
 
Nx 9 is building upon this, making it a truly generic tool for modern web development.
 
## Generic Tool
 
Nx 8 is a generic development tool, which comes with Angular, React, Web, Express, Nest plugins. You can build your own: add support for Stencil, Svelte, Ember or anything else. If you want to do it, get in touch with us, and we will help you.
 
This year we are continuing on this journey. We are changing Nx.dev, so you can select technologies you are using, and see all the documentation written from that point of view.
 
 
## Supporting Design Systems
 
Nx is already a fantastic tool for design systems: you can develop components, test them, document them, use them in a variety of projects. When you change a component, you can run a test against that component and then test all the applications using that component. 

Many teams who are building design systems with Nx end up wiring up Storybook. It works, but it requires a little bit of setup. To make this easier, we are going to add a Storybook plugin for Nx.
 
 
## Nx Course
 
We provide a free online course on Nx at connect.nrwl.io. There you can also find a free book on building large enterprise applications using Nx. Both the course and the book are great, but they need a refresher. So we are working on updating them to cover all the recent additions to Nx.
 
 
## More Transparency
 
Historically, we haven't been very consistent at communicating our priorities and release plans. It was done ad hoc via blog posts and github issues. The Nx core team will do much better.
 
This issue is the first step in this process. We also added two milestones "next" and "nx9", so you can track what should be released in the next minor and major version of Nx.
 
 
## Bazel Support
 
We added experimental Bazel support a year ago. Unfortunately, at that point, Bazel wasn't mature enough to be used for most organizations. Now, even though still not perfect, Bazel support got a lot better. This is a good time to make Nx work with Bazel, and this time to make it production ready.

We are planning to make Regular Nx => Nx + Bazel transition straightforward. You can start with using regular Nx right now, and then, at some point, if you want to Bazelify it, you should be able to do it with minimal effort.
 
 
Let us know what your thoughts are.
 
Thanks!
Nx Core Team

**Comment by perjerz3434** [comment] 2019-06-21 14:27
Is there any plan for supporting GraphQL Apollo?

**Comment by oacs** [comment] 2019-06-22 17:51
Is there any plan for supporting Ngxs?

**Comment by vsavkin** [comment] 2019-06-23 21:48
@perjerz3434 yes to Apollo. We use apollo for many internal projects, and with clients, so we are planning to add @nrwl/apollo.

**Comment by Jordan-Hall** [comment] 2019-06-26 16:03
Moving into version 9 can we removed the Jest dependency in ```@nrwl/node```

**Comment by FrozenPandaz** [comment] 2019-06-28 20:37
@Jordan-Hall the dependency is needed to generate unit tests for `node` products. It should be hoisted as it depends on the same version as the workspace should be set to.

Vue support would be great. Building the application is easy but drawing dependencies is hard when using `.vue` files. Using `.ts` files it would be easy. Please create a new issue for Vue support and we can discuss more there.

**Comment by gauravapheleia** [comment] 2019-07-01 10:29
@FrozenPandaz  @Jordan-Hall  has the vue ticket been created? I would love to contribute on that front.

**Comment by Jordan-Hall** [comment] 2019-07-01 12:28
@gauravapheleia I've created an outline ticker for Vue support. https://github.com/nrwl/nx/issues/1541 I'm going to start looking into this from tomorrow.

**Comment by eleMental595** [comment] 2019-07-02 09:24
@Jordan-Hall @FrozenPandaz I have been working in vuejs for the last 6 months, and would love to contribute. Please show the way.

**Comment by Jordan-Hall** [comment] 2019-07-02 14:08
@eleMental595  That would be good. Move discussion on Vue to the ticket #1541

**Comment by wellrightamplify** [comment] 2019-07-04 15:26
Similar to Apollo would love to see AWS Amplify integration.  Obviously probably not for NX9.  We currently use Amplify in our NRWL/NX monorepo paired with Apollo Client.

**Comment by xmlking** [comment] 2019-07-07 17:26
Storebooks add great value to nx.
**Storebook** is for _visual/appearance_ testing where **Just** is for _correctness_ testing.
https://medium.com/better-programming/how-to-speed-up-angular-development-and-reduce-compilation-times-a32262d478bc

**Comment by jerome-nelson** [comment] 2019-07-17 17:20
Thanks for the Bazel conversion news!!

Are there any plans on open-sorucing contribution for this? Also any major challenges foreseen?

**Comment by akolybelnikov** [comment] 2019-07-25 09:52
I am looking into adding a Svelte project to our existing Nx/Angular monorepo. Any hints on where to start with it are really appreciated. Also, I would love to contribute with this regard.

**Comment by NikoMontana** [comment] 2019-07-30 12:42
NextJS with Now support would be more then great!

**Comment by oknoorap** [comment] 2019-08-10 10:31
Please support nextjs

**Comment by jafaircl** [comment] 2019-08-20 18:12
gatsby support would be awesome

**Comment by jaysoo** [comment] 2019-08-29 18:36
@NikoMontana @oknoorap Next.js support is being discussed, but we don't have a concrete plan yet. So stay tuned!

@jafaircl I think we are prioritizing Next.js over Gatsby for now. But keep letting us know what you'd like do see!

**Comment by mehrad-rafigh** [comment] 2019-09-01 03:47
Next.js would be great indeed. The possibility to render static-web pages would be great. Any chance, the community could take over @jaysoo?

**Comment by asherccohen** [comment] 2019-09-06 20:19
Definitely next.js and storybook would add great value to nx!

**Comment by creadicted** [comment] 2019-09-07 07:36
A better support for libraries in nestjs would be fantastic. If I use the libs folder I run in to issues with either linting errors, deep import warnings or circular dependencies. If I use another folder - I loose the benefits of nx.

**Comment by mcblum** [comment] 2019-09-09 13:06
Thanks for all the work on this @vsavkin. One thing that I would love to see if it fits the roadmap is an easier way to generate generic libs. For example, I'm structuring our NestJS microservices the same way as I would structure an Angular app, but there isn't (as far as I can tell) a super easy way to make a Nest feature lib. I used to just select the `typescript` option from the menu, but that appears to now be gone, so I have started doing it by hand. Not the end of the world, but since the Angular structure works so well I figured why not use it for services as well.

Thanks again for all of the work that you and the team have done to make us all better developers!

**Comment by ManAnRuck** [comment] 2019-09-09 16:20
prisma2 support would be also awesome! 👏 
it's currently in alpha, but in my eyes it's a gamechanger 📢

**Comment by ajonp** [comment] 2019-09-21 16:46
Sweet the Next.js app is great, now Gatsby would be even better ;)

**Comment by paynecodes** [comment] 2019-10-09 17:58
> Nx 8 is a generic development tool, which comes with Angular, React, Web, Express, Nest plugins. You can build your own: add support for Stencil, Svelte, Ember or anything else. If you want to do it, get in touch with us, and we will help you.

Is there any documentation for building support for other tools? It seems that energy should be focused here if not.

**Comment by jmcdo29** [comment] 2019-10-09 18:58
Now that Nest has its own CLI, will Nx support it in the future?

**Comment by ukaric** [comment] 2019-10-10 13:09
Pattern around nestjs microservices should be adopted imo, because each microservice should be its own app for multitude of reasons.

**Comment by mcblum** [comment] 2019-10-10 13:42
@ukaric each microservice is currently intended to be its own app, is it not? What would Nx do differently to support that?

**Comment by ukaric** [comment] 2019-10-10 14:21
@mcblum Yeah indeed i have expressed my self poorly. What I meant by standalone is they should be structured such that if you have project A and it has back-end appropriate microservices for project A will go under that project. And if latter on you have another one you can separate microservices by projects and still keep the benefits of nx style monorepo

**Comment by StefanNieuwenhuis** [comment] 2019-10-18 13:57
I would love to see StencilJs support! And I definitely want to contribute to making it happen. But where to start? 🤔 Can someone help me with that?

**Comment by mcblum** [comment] 2019-10-18 14:00
@ukaric I think I still don't understand :) 

> And if latter on you have another one you can separate microservices by projects and still keep the benefits of nx style monorepo

What is a project in this case? Since it's a monorepo, all of your projects should be in the same repo.

**Comment by mcblum** [comment] 2019-10-18 14:03
@StefanNieuwenhuis I can recommend reading through the source code and reviewing the schematics! If I wanted to add support for a new framework I'd evaluate how the project was generated, served and built for each type of app.

For example, since Nx supports both Angular and React, you should be able to check the differences and then formulate a plan for introducing StencilJs!

**Comment by StefanNieuwenhuis** [comment] 2019-10-18 14:10
Thanks for your reply. Existing schematics form a nice starting point indeed. Gonna take a look and I hope that I can formulate a plan.

**Comment by megagru** [comment] 2019-10-25 03:39
@vsavkin With Bazel, would it be possible to integrate Frameworks, that are not based on Javascript/Typescript, e.g. Java Spring?

**Comment by karocksjoelee** [comment] 2019-11-12 16:12
Hey ~ any plan on adding NativeScript + Angular or React Native ?

**Comment by Jordan-Hall** [comment] 2019-11-12 16:17
Hey @karocksjoelee 

NX wouldn't want to put time into native application due to the amazing work with the guys over at nStudio has done with xplat.

Xplat is an added value pack for Nx which provides additional app generators and optional supporting architecture for different platform/framework combinations.

I've personally used Xplat and the way they approach is astounding. https://nstudio.io/xplat

I'm unsure if react native is supported but if you find they github. It's an open source solution and they keen of people contributing

**Comment by karocksjoelee** [comment] 2019-11-12 16:20
@Jordan-Hall  Awesome ! I didn't knew about Xplat before  ( Just getting start ) . Thx : )

**Comment by paynecodes** [comment] 2019-11-12 17:54
Is NX still geared toward Angular devs? Xplat sure seems to be.

**Comment by Jordan-Hall** [comment] 2019-11-12 17:55
@paynecodes  xplat isn't gear towards anything. NX doesn't appear to be geared toward angular anymore. They own CLI coming on very well

**Comment by paynecodes** [comment] 2019-11-12 18:18
@Jordan-Hall Thank you for clearing that up. I see mention of Vue.js there as that is something NativeScript supports. I suppose I'm still trying to orient myself around this piece of tooling. It seems to me that it's still a bit too entrenched in certain stacks and there is no documentation for building new stacks. As an application developer, I just want to be able to choose my own stack, and I'm not, yet, seeing the benefit of a monorepo tool that doesn't allow that. 

I'm sure there are tradeoffs. I assume `nx` is able to do nice things by dictating the stack used. What are those things? 

Is there a near future where users are able to choose their own stack with the tradeoff being less deep integration with all of the `nx` cli?

**Comment by Jordan-Hall** [comment] 2019-11-12 18:23
@paynecodes  NX allows you to choose your own stack. 

I would suggest you first generate a blank nx workspace. If you don't want to use angular then choose the option to use nx cli and not angular.json. 

Once you have the blank workspace you can choose different set up such as react and nestjs or expressjs or even web component. 

However, I believe you are talking about bringing in the framework that's not supported?  Feel free to add the type of stack you are wanting. I'm sure the developers that will help integrate a build into NX to support your requirement

**Comment by stramel** [comment] 2019-11-15 22:11
I'm happy to see support coming for a tool like storybook. I was curious if there would be a docz alternative offered?

**Comment by Jordan-Hall** [comment] 2019-11-16 14:42
@stramel  Storybook has now been added with schematics for angular. When do you mean by docz alternative?

**Comment by stramel** [comment] 2019-11-18 15:42
@Jordan-Hall My apologies for the poorly worded comment. I use React with my team and have found that Docz works really well with it. I would love to see it offered as an alternative to Storybook.

**Comment by Jordan-Hall** [comment] 2019-11-19 14:47
@stramel Best asking one of the NX team @FrozenPandaz. For me, I wouldn't want to contribute it. But feel free add it yourself.

For me, nx would be better to be framework agnostic. From what i can see Docz is only supported in react

**Comment by NachoVazquez** [comment] 2019-11-23 17:18
It may be possible to make `jsx` optional for React projects. 
I'm trying to introduce Nx in my company, where the only requirement I got was the use of `jsx` instead of `tsx`. 

Thanks for this amazing tool BTW!

**Comment by nasr18** [comment] 2019-11-30 18:28
> I am looking into adding a Svelte project to our existing Nx/Angular monorepo. Any hints on where to start with it are really appreciated. Also, I would love to contribute with this regard.

@akolybelnikov did you add Svelte project? I also wanna add svelte.

**Comment by GreedyA1** [comment] 2019-12-02 08:08
are there any release dates for NX 9?

**Comment by beeman** [comment] 2019-12-02 14:49
> are there any release dates for NX 9?

It's generally released a few weeks after the Angular release with the same version number.

**Comment by paynecodes** [comment] 2019-12-02 16:19
I am under the impression this project isn’t so directly coupled with Angular. Is this still true?

**Comment by Jordan-Hall** [comment] 2019-12-02 16:31
@paynecodes  that is correct

**Comment by vsavkin** [comment] 2019-12-02 22:27
@GreedyA1 early December. Historically we were following devkit release cycles (which Angular depends on also), but we will stop doing it in 2020.

**Comment by jiayisheji** [comment] 2019-12-05 03:03
@vsavkin We can consider extending the code to the Angular microfront end.

**Comment by nicokoenig** [comment] 2019-12-11 07:57
Are there any plans to provide builder for node backend apps that supports a custom webpack config? 🙏

**Comment by F1LT3R** [comment] 2020-01-14 21:37
I would be interested to see Svelte and Sapper added. I would be happy to help there where I could.

**Comment by bladerunner41** [comment] 2020-01-15 00:44
I would be interested to see the [Cloudflare Wrangler CLI](https://github.com/cloudflare/wrangler) integrated - simliar to Nest/Express starters for BE API hosting.

**Comment by lexcaraig** [comment] 2020-03-10 08:43
Any plans on adding storybook/addon-docs for angular? I mean, it would be a big help if we have an schematics for this in default setup.

**Comment by jaysoo** [comment] 2020-04-15 01:53
@F1LT3R @bladerunner41 We welcome developers to write their own community plugins. Please see the new plugins page here: https://nx.dev/nx-plugins

**Comment by FrozenPandaz** [comment] 2020-05-29 19:17
Hi, sorry about this.

This was mislabeled as stale. We are testing ways to mark _not reproducible_ issues as stale so that we can focus on actionable items but our initial experiment was too broad and unintentionally labeled this issue as stale.

**Comment by jaysoo** [comment] 2020-09-22 13:48
Closing this since 9 has been release. Please see Nx 11 plans here https://github.com/nrwl/nx/issues/3377.

**Closed by jaysoo** 2020-09-22 13:48 UTC
Labels: scope: misc, type: docs

**Comment by khalid283** [comment] 2021-01-14 16:01
@wellrightamplify how did you implemented in nx?
