### ISSUE TITLE
Cannot read properties of undefined (reading 'exists')

### ISSUE THREAD

**Issue by bstrob** [nrwl/nx#10804] opened 2022-06-18 18:51 UTC
I got this error in a newly created Nx 13 workspace. I think it's somehow related to this bug: #10777 - the steps are the same.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/22637147/174452357-6b0c22c0-709a-4af9-bb5e-f3e58296323c.png">

```
>  NX   Report complete - copy this into the issue template

   Node : 16.14.0
   OS   : darwin x64
   npm  : 8.6.0
   
   nx : 13.10.5
   @nrwl/angular : 13.10.5
   @nrwl/cypress : 13.10.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.10.5
   @nrwl/eslint-plugin-nx : 13.10.5
   @nrwl/express : Not Found
   @nrwl/jest : 13.10.5
   @nrwl/js : Not Found
   @nrwl/linter : 13.10.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.10.5
   @nrwl/web : Not Found
   @nrwl/workspace : 13.10.5
   typescript : 4.6.4
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:

```

**Comment by leosvelperez** [comment] 2022-06-21 15:32
Thanks for reporting this!

This is a duplicate of https://github.com/nrwl/nx/issues/9869. Please note this was fixed in https://github.com/nrwl/nx/pull/10038 and released on Nv v14.0.4.

Please make to migrate to a version higher than v14.0.4 and up to v14.1.9 which is the latest version with Angular v13 if you need to stay there, otherwise, you can migrate to the latest version.

**Closed by leosvelperez** 2022-06-21 15:32 UTC
Labels: type: bug, blocked: retry with latest, scope: angular

**Comment by bstrobach** [comment] 2022-06-21 15:59
Thank you. Didn’t see this ticket. 
And thank you for the Angular 13 hint.

**Comment by up-the-dev** [comment] 2022-08-07 13:43
make sure you are applying exist method on correct model  and the  model is correctly imported
