### ISSUE TITLE
External Schematics for library generator is not working with @nrwl/angular v12.4.0

### ISSUE THREAD

**Issue by sandeeppatidar30** [nrwl/nx#6065] opened 2021-06-18 07:45 UTC
## Current Behavior

We have extended the nrwl lib generator to add our usecase but when we are using **ng g lib** using external schematics then it fails with below error -

**Error: Cannot find configuration for 'lib-name' in /angular.json.**

Please check attached screenshot of error and code
## Expected Behavior

It should generate lib without any error. Library generation using externalSchematics works with @nrwl/angular v12.3.6

## Steps to Reproduce
1.. Extend lib generaor 
         **export default function(schema: Schema): Rule {
      return (host: Tree, context: SchematicContext) => {
        return chain([
          externalSchematic('@nrwl/angular', 'lib', {
            ...schema,
          })
        ])(host, context);
      };
    }**

2. **run ng g lib mylib**

### Environment
Windows 10

### Complete error log

C:\workspace\tooling\ng12latest>ng g lib widgets
√ In which directory should the library be generated? (Leave it blank for default location under libs folder.) ·
Error: Cannot find configuration for 'widgets' in /angular.json.
    at Object.readProjectConfiguration (C:\workspace\tooling\ng12latest\node_modules\@nrwl\devkit\src\generators\project-configuration.js:108:15)
    at fixProjectWorkspaceConfig (C:\workspace\tooling\ng12latest\node_modules\@nrwl\angular\src\generators\library\lib\update-project.js:85:30)
    at Object.<anonymous> (C:\workspace\tooling\ng12latest\node_modules\@nrwl\angular\src\generators\library\lib\update-project.js:14:9)
    at Generator.next (<anonymous>)
    at C:\workspace\tooling\ng12latest\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\workspace\tooling\ng12latest\node_modules\tslib\tslib.js:113:16)
    at Object.updateProject (C:\workspace\tooling\ng12latest\node_modules\@nrwl\angular\src\generators\library\lib\update-project.js:10:20)
    at C:\workspace\tooling\ng12latest\node_modules\@nrwl\angular\src\generators\library\library.js:41:32
    at Generator.next (<anonymous>)
Cannot find configuration for 'widgets' in /angular.json.

**Comment by manfredsteyer** [comment] 2021-06-19 10:38
I have the same issue

**Comment by wizardnet972** [comment] 2021-06-20 12:20
same

**Comment by dschwank** [comment] 2021-06-21 08:22
Same here - it seems to work for `@nrwl/react` but is breaking for `@nrwl/angular`. Went back to 12.3.6.

**Comment by wizardnet972** [comment] 2021-06-21 08:25
I think the `name` is the problem. since `name` is an argument in `@angular-architure/ddd` the nx schematics think it's the name of the collection.

**Comment by Coly010** [comment] 2021-06-21 08:31
Hi @sandeeppatidar30 
Do you have a minimum repo I could use to investigate this further? 

It seems to be related to how Nx Devkit converts Generators to Schematics that are then used via `externalSchematic`.

**Comment by wizardnet972** [comment] 2021-06-28 05:53
@Coly010 
you can reprocedure the problem in this repo.  https://github.com/angular-architects/nx-ddd-plugin
Right now, the problem exists in nx 1.4+

**Comment by iameduardod** [comment] 2021-06-28 18:57
Any updates to resolving this? @Coly010  ?

**Closed** 2021-06-29 17:02 UTC
Labels: scope: angular, type: bug

**Comment by wizardnet972** [comment] 2021-06-30 07:13
@leosvelperez , @Coly010  Why this issue closed?  the problem still exists.

here how to reproduce:

```
$ npx create-nx-workspace nx-ddd (empty)
$ yarn add @nrwl/angular
$ yarn nx g @nrwl/angular:app ddd-ui
$ yarn add @angular-architects/ddd
$ yarn nx g @angular-architects/ddd:domain --name auth --directory ui --dry-run
```

got error:
```
yarn run v1.22.10
$ nx g @angular-architects/ddd:domain --name auth --directory ui --dry-run
✔ Would you like to add an associated application? (y/N) · false
"domain-options" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsLibrary" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAngularModule" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAngularComponent" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"SchematicsAngularService" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Error: Cannot find configuration for 'auth-ui-domain' in /angular.json.
    at Object.readProjectConfiguration (/Users/wizardnet972/code/nx-ddd/node_modules/@nrwl/devkit/src/generators/project-configuration.js:110:15)
    at fixProjectWorkspaceConfig (/Users/wizardnet972/code/nx-ddd/node_modules/@nrwl/angular/src/generators/library/lib/update-project.js:85:30)
    at Object.<anonymous> (/Users/wizardnet972/code/nx-ddd/node_modules/@nrwl/angular/src/generators/library/lib/update-project.js:14:9)
    at Generator.next (<anonymous>)
    at /Users/wizardnet972/code/nx-ddd/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/wizardnet972/code/nx-ddd/node_modules/tslib/tslib.js:113:16)
    at Object.updateProject (/Users/wizardnet972/code/nx-ddd/node_modules/@nrwl/angular/src/generators/library/lib/update-project.js:10:20)
    at /Users/wizardnet972/code/nx-ddd/node_modules/@nrwl/angular/src/generators/library/library.js:41:32
    at Generator.next (<anonymous>)
Cannot find configuration for 'auth-ui-domain' in /angular.json.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@manfredsteyer 

nx report:
```
yarn run v1.22.10
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.17.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : Not Found
  @nrwl/angular : 12.5.0
  @nrwl/cli : 12.5.0
  @nrwl/cypress : 12.5.0
  @nrwl/devkit : 12.5.0
  @nrwl/eslint-plugin-nx : 12.5.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.0
  @nrwl/linter : 12.5.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.0
  @nrwl/storybook : 12.5.0
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

✨  Done in 0.94s.
```

**Comment by Coly010** [comment] 2021-06-30 07:16
@wizardnet972 Closed automatically when @leosvelperez merged his code that fixes this. When the patch version is released, this will be fixed. 

You just have to wait for the patch version to be released then update to latest

**Comment by leosvelperez** [comment] 2021-06-30 15:53
https://github.com/nrwl/nx/releases/tag/12.5.1 is released now with the fix.
