### ISSUE TITLE
Nx dep-graph Invalid.asm.js

### ISSUE THREAD

**Issue by urosappdev** [nrwl/nx#1868] opened 2019-09-20 14:19 UTC
## Expected Behavior

`nx affected:dep-graph` or any other graph command should open a dependency graph.

Running e2e command should run e2e test suite.

## Current Behavior

Neither `e2e` nor `dep-graph` works.

## Failure Information (for bugs)

When running `yarn run e2e` errors out with

```
$ nx e2e
Project target does not exist.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Running `yarn dep-graph` errors out with
```
$ nx dep-graph
(node:16482) V8: /home/netrunner/rent/node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use
Done in 0.70s.
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `clone git@github.com:urosappdev/nx-bug.git`
2. `yarn install`
3. `yarn e2e` or `yarn dep-graph`

### Context

Please provide any relevant information about your setup:

- version of Nx used: `8.5.0`
- and most importantly - a use-case that fails

## Other

I'm running linux

`Linux netrunner 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux`

Yarn version : `1.17.3`

Node version: `v12.10.0`

Asdf version: `v0.7.4`

**Comment by FrozenPandaz** [comment] 2019-09-20 21:38
Hi @urosappdev,

Try `yarn e2e admin-e2e` to run e2e tests for the admin app. If you would like to run all `e2e` tests, you can use `yarn affected --target e2e` but it is strongly recommended to only run the sufficient e2e tests with `yarn affected --target e2e.

For `yarn dep-graph`, this is a duplicate of #1551 but the graph shows up properly in your browser.

**Comment by FrozenPandaz** [comment] 2019-09-20 21:40
I believe this should solve your issue. If not, feel free to reopen the issue.

**Closed by FrozenPandaz** 2019-09-20 21:40 UTC
