### ISSUE TITLE
@nrwl/node:library build srcRootForCompilationRoot rootDir regression bug

### ISSUE THREAD

**Issue by webberwang** [nrwl/nx#3625] opened 2020-08-29 03:19 UTC
## Current Behavior

`tsconfig.lib.json` `rootDir` is not respected, for example `{ "rootDir": "./src" }` still builds with `src` in the final output like `dist/src`

This is a regression bug, in `10.0.11` the `outDir` is still respected. As of `10.1.0`, we have to modify `srcRootForCompilationRoot` in `workspace.json` for this.

## Expected Behavior

Should output to `dist` folder without `src`

## Steps to Reproduce

`nx generate @nrwl/node:library --buildable`, modify `tsconfig.lib.json`, then `nx build [library-name]`

### Environment

```
nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 10.1.0
  @nrwl/cypress : 10.1.0
  @nrwl/eslint-plugin-nx : 10.1.0
  @nrwl/express : Not Found
  @nrwl/jest : 10.1.0
  @nrwl/linter : 10.1.0
  @nrwl/nest : 10.1.0
  @nrwl/next : 10.1.0
  @nrwl/node : 10.1.0
  @nrwl/react : 10.1.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.1.0
  @nrwl/web : 10.1.0
  @nrwl/workspace : 10.1.0
  typescript : 3.9.7
```

**Comment by mandarini** [comment] 2020-09-03 13:13
Hi there @webberwang ! Thanks for filing an issue!

This behaviour is intentional, it is not a bug. Please take a look at these PRs: [nrwl/nx/pull/3564](https://github.com/nrwl/nx/pull/3564) and [nrwl/nx/pull/3545](https://github.com/nrwl/nx/pull/3545).

However, maybe it would be more helpful to supply a flag that would make adding a root directory easier for the user. So, I'll try to work on that feature!

**Comment by webberwang** [comment] 2020-09-03 23:03
@mandarini I see, I think modifying default TS features can be confusing to users. Is there a rational to not support `rootDir`?

**Comment by Cammisuli** [comment] 2020-09-04 18:13
Hi @webberwang, let me explain a bit more of why we needed to remove the `rootDir` from tsconfigs. 

With Nx10 we moved everything to be TypeScript project references (https://www.typescriptlang.org/docs/handbook/project-references.html). This changed the behaviour of `rootDir` where `rootDir` is much more constrained. This then caused an issue when you try to import other Nx Node libs. IDEs would spit out an error that says something like:
 ```
File '/libs/my-node-lib/src/index.ts' is not under 'rootDir' '/libs/my-node-lib-two/src'. 'rootDir' is expected to contain all source files.ts(6059)
```

A solution was needed that would've worked if you're using Node, React and Angular together. 
We could've done one of 3 things:
1) Change the `rootDir` to point to the upmost parent by doing `../../..` (which causes issues with outputs where one build of a project will include all projects)
2) Tell people to manually update references in their `tsconfig.lib.json` whenever they import another Nx Node lib into a Node lib. (which 
3) Remove `rootDir` and let TypeScript automatically figure out the root. 

Option 3 was the one we chose because it allowed the same behaviour and workflow of previous versions of Nx. 

I know that having `rootDir` set changes the output of the builds, so we included the `srcRootForCompilationRoot` option.  This sets the `rootDir` option behind the scenes in the builder,  without having to set the rootDir specifically in the tsconfig (as that will cause IDE issues).  

Also note that we don't use the `outDir` property set in tsconfig either. Those options are specified in the workspace.json. 

So because `srcRootForCompilationRoot` is working as expected, I'm going to close this issue. 

If you want to talk more about this, you can message me on the Nrwl community slack and find me `@jon`.

**Closed by Cammisuli** 2020-09-04 18:13 UTC
Labels: scope: node, type: feature

**Comment by webberwang** [comment] 2020-09-04 18:23
thanks for the detailed explanation, glad to understand the high level overview
