### ISSUE TITLE
custom schematics fails after upgrade to 6.2.0

### ISSUE THREAD

**Issue by jasedwards** [nrwl/nx#710] opened 2018-08-15 16:10 UTC
I had two custom schematics.  I updated to 6.2 this morning and both are now failing.  The error is "Tree type is not supported".  I stripped one all the way down to what you see below and am still getting this error:

```javascript
function normalizeOptions(options): any {
  return {
    ...options,
     name: dasherize(options.name)
  };
}

export default function(schema: any): Rule {
  const options = normalizeOptions(schema);
  return chain([externalSchematic('@nrwl/schematics', 'lib', options)]);
}
```

Here is the I logged in schematics\src\rules\base.js.  this is the tree that is apparently invalid thought I have no idea what that means.  I just know this was working in 6.1.0:

```json
HostCreateTree {
  _backend: Empty { capabilities: { synchronous: true } },
  _id: -9,
  _ancestry: Set {},
  _dirCache: Map {},
  _record:
   CordHost {
     _cache:
      Map {
        '/' => <Directory>,
        '/__name@dasherize@if-flat__' => <Directory>,
        '/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts' => <File size(278)>,
        '/__name@dasherize@if-flat__/__name@dasherize__.module.spec.ts' => <File size(396)>,
        '/__name@dasherize@if-flat__/__name@dasherize__.module.ts' => <File size(482)> },
     _watchers: Map {},
     _back: SafeReadonlyHost { _delegate: [Object] },
     _filesToCreate:
      Set {
        '/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts',
        '/__name@dasherize@if-flat__/__name@dasherize__.module.spec.ts',
        '/__name@dasherize@if-flat__/__name@dasherize__.module.ts' },
     _filesToRename: Map {},
     _filesToRenameRevert: Map {},
     _filesToDelete: Set {},
     _filesToOverwrite: Set {} },
  _recordSync:
   SyncDelegateHost {
     _delegate:
      CordHost {
        _cache: [Object],
        _watchers: Map {},
        _back: [Object],
        _filesToCreate: [Object],
        _filesToRename: Map {},
        _filesToRenameRevert: Map {},
        _filesToDelete: Set {},
        _filesToOverwrite: Set {} } } }
```

**Comment by chgc** [comment] 2018-08-16 00:44
I had the same issue. I think it's Angular schematics's bug. In my custom schematics, it was caused by `filter`. After I remove filter, everything works fine again.

FYI: https://github.com/angular/angular-cli/issues/11683#issuecomment-410473240

**Comment by FrozenPandaz** [comment] 2018-08-17 16:15
Do you have a repo I can take a look at for this. I have the exact same schematic [here](https://github.com/FrozenPandaz/nx-examples/blob/nx710/tools/schematics/test/index.ts) with 6.2.0 and it seems to work.

Below are my Versions:
```sh
jason@Jason-PC-U:~/projects/work/temp/projj$ ng -v && npm ls @nrwl/schematics

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.0
Node: 8.11.1
OS: linux x64
Angular: 6.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.7.0
@angular-devkit/schematics        0.7.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.0
@schematics/update                0.7.0
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3

projj@0.0.0 /home/jason/projects/work/temp/projj
└── @nrwl/schematics@6.2.0
```

**Comment by jasedwards** [comment] 2018-09-17 14:14
looks like this may be fixed with https://github.com/angular/angular-cli/issues/11683 which is in release candidate now.

**Comment by jasedwards** [comment] 2018-09-17 16:16
@FrozenPandaz  I just created a brand new repo.  has all the exact versions my existing repo has and the exact same schematic.  it works on the new one but still not the old one.  I will just cross my fingers that the angular-cli issue solves this one.

**Comment by FrozenPandaz** [comment] 2018-10-02 14:46
Seems like this issue is fixed with the `angular-cli` issue.

**Closed by FrozenPandaz** 2018-10-02 14:46 UTC
Labels: blocked: repro needed
