### ISSUE TITLE
Changes on pnpm-lock.yaml marks all packages as affected

### ISSUE THREAD

**Issue by eladhaim** [nrwl/nx#15234] opened 2023-02-24 15:46 UTC
### Current Behavior

We have an integrated nx monorepo, when we add new npm package(pnpm install) our packages marked as affected even when non of them import the new one.

### Expected Behavior

For my understanding only packages that use the new added package should marked as affected, i was debugging the 
affected-project-graph a little bit and i understand that what flips all the package to affected is the workspace-projects locator that has the package manager lock files as global files that affect all packages, deleting the pnpm-lock.yaml file from this array fix the problem but i'm sure it will have other side effects also.
Is it something that you plan to add(analyzing the lock-files also?)
we are running with nx 15.7.2

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.16.0
   OS   : darwin x64
   pnpm : 7.21.0
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/nest              : 15.7.2
   @nrwl/node              : 15.7.2
   @nrwl/nx-cloud          : 15.1.0
   typescript              : 4.7.4
```

**Comment by AgentEnder** [comment] 2023-02-27 20:44
Closing as a duplicate of #15116

**Closed** 2023-04-20 11:58 UTC
Labels: type: bug, scope: core
