### ISSUE TITLE
@nrwl/next adds wrong entries in the include property present in the tsconfig.json of the newly created Next.js app

### ISSUE THREAD

**Issue by shettayyy** [nrwl/nx#13861] opened 2022-12-16 05:31 UTC
### Current Behavior

At present, the tsconfig.json for the newly created Next.js app looks like - 

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "types": ["jest", "node"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.js",
    "src/**/*.jsx",
    "next-env.d.ts"
  ],
  "exclude": ["node_modules", "jest.config.ts"]
}
```

This ends up showing false errors and typescript files under Next.js apps are not recognised by VSCode. It happens because of the wrong entries provided to the input property.

### Expected Behavior

The newly created Next.js app doesn't have a `src/` directory. So, the tsconfig should look like:

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "types": ["jest", "node"]
  },
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "next-env.d.ts"],
  "exclude": ["node_modules", "jest.config.ts"]
}
```

### Steps to Reproduce

1. Create a new workspace `npx create-nx-workspace@latest --preset=next --packageManager=yarn` OR add a new Next.js app - `npx nx g @nrwl/next:app my-app --directory=apps --tags=scope:my-app,type:app --style=css --linter=eslint --unitTestRunner=jest --e2eTestRunner=cypress --routing`
2. Open a typescript file available under pages
3. You should see false errors
4. I have provided detailed reproducible steps with screenshots here - https://stackoverflow.com/questions/74817534/vscode-is-unable-to-detect-the-tsconfig-that-resides-in-the-next-js-app-created

### Nx Report

```shell
Node : 16.17.1
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.3
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by atanaskanchev** [comment] 2022-12-16 08:39
Nicely put together, thanks @shettayyy I've reported similar issues couple of days back https://github.com/nrwl/nx/issues/13795 and 
https://github.com/nrwl/nx/issues/13790, that I believe have the same root cause.

**Comment by shettayyy** [comment] 2022-12-16 09:13
Thanks, @atanaskanchev and yes, I was seeing exactly the same false errors as you have reported.

**Comment by atanaskanchev** [comment] 2022-12-16 14:05
There's a PR in flight fixing that https://github.com/nrwl/nx/pull/13870

**Comment by FrozenPandaz** [comment] 2022-12-20 18:21
@ndcunningham @KaviiSuri did #13870 fix this issue?

**Comment by KaviiSuri** [comment] 2022-12-20 18:24
@FrozenPandaz yupp!

I already made an issue about this before the PR. It's #13754

I think this might be a duplicate

Let me know if i missed something! Would be happy to reiterate!

**Comment by ndcunningham** [comment] 2022-12-20 19:06
This should be addressed in the above PR. 
Feel free to reopen if the issue persists

**Closed by ndcunningham** 2022-12-20 19:06 UTC
Labels: type: bug, scope: nextjs
